### ISSUE TITLE
Sqlite3 with Electron 1.6.11 on Windows

### ISSUE THREAD

**Issue by godlatro** [electron/electron#10220]
Hi
How to install any Sqlite on Electron?

I will install node-gyp and node-pre-gyp and sqlite3 and python 3 6
but when I require sqlite3 module its say:

`Cannot find module 'C:\node\e2\node_modules\sqlite3\lib\binding\electron-v1.6-win32-x64\node_sqlite3.node'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (C:\node\e2\node_modules\electron\dist\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\node\e2\node_modules\sqlite3\lib\sqlite3.js:4:15)
    at Object.<anonymous> (C:\node\e2\node_modules\sqlite3\lib\sqlite3.js:190:3)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)`

Where I can get this electron-v1.6-win32-x64\node_sqlite3.node?

Any other ways to use sqlite3 in electron?

**Comment by enlight** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by TimNZ** [comment]
@godlatro 
https://github.com/mapbox/node-sqlite3/issues/761

Basically install module electron-rebuild and run ./node_modules/.bin/electron-rebuild

**Comment by godlatro** [comment]
@TimNZ 
I try to run this command (on windows) but  it have many errors
node-gyp cant find python and else

**Comment by marswong** [comment]
I had failed to build `sqlite3` for thousand times no matter how, for the `aws-sdk` relys on `child_process` so every time you `require('sqlite3')` on client side it could not be resolved.

Luckily, I found an awesome module can work like a charm on both client or server side - [sql.js](https://github.com/kripken/sql.js) created by the `emscripten`'s author.

If you are still in troubles with integrating `electron` and `sqlite`, you should have a try :)

**Comment by Saikartik19** [comment]
Error: C:\Program Files\nodejs\node.exe exited with code 1
Error output:
node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.0.0/electron-v1.8-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@4.0.0 and electron@1.8.4 (electron-v1.8 ABI, unknown) (falling back to source compile with node-gyp)
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack at PythonFinder. (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "configure" "--fallback-to-build" "--module=E:\HelloWorld\electron-quick-start\node_modules\sqlite3\lib\binding\electron-v1.8-win32-x64\node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=E:\HelloWorld\electron-quick-start\node_modules\sqlite3\lib\binding\electron-v1.8-win32-x64" "--napi_version=1" "--node_abi_napi=napi"
gyp ERR! cwd E:\HelloWorld\electron-quick-start\node_modules\sqlite3
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js configure --fallback-to-build --module=E:\HelloWorld\electron-quick-start\node_modules\sqlite3\lib\binding\electron-v1.8-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=E:\HelloWorld\electron-quick-start\node_modules\sqlite3\lib\binding\electron-v1.8-win32-x64 --napi_version=1 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack at ChildProcess. (E:\HelloWorld\electron-quick-start\node_modules\sqlite3\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack at maybeClose (internal/child_process.js:925:16)
node-pre-gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Windows_NT 10.0.16299
node-pre-gyp ERR! command "C:\Program Files\nodejs\node.exe" "E:\HelloWorld\electron-quick-start\node_modules\sqlite3\node_modules\node-pre-gyp\bin\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd E:\HelloWorld\electron-quick-start\node_modules\sqlite3
node-pre-gyp ERR! node -v v8.9.4
node-pre-gyp ERR! node-pre-gyp -v v0.9.0
node-pre-gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sqlite3@4.0.0 install: node-pre-gyp install --fallback-to-build
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@4.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\NexGen43\AppData\Roaming\npm-cache_logs\2018-03-22T13_24_03_247Z-debug.log

at ChildProcess.childProcess.once.code (E:\HelloWorld\electron-quick-start\node_modules\builder-util\src\util.ts:252:14)
at Object.onceWrapper (events.js:317:30)
at emitTwo (events.js:126:13)
at ChildProcess.emit (events.js:214:7)
at maybeClose (internal/child_process.js:925:16)
at Socket.stream.socket.on (internal/child_process.js:346:11)
at emitOne (events.js:116:13)
at Socket.emit (events.js:211:7)
at Pipe._handle.close [as _onclose] (net.js:554:12)
From previous event:
at rebuild (E:\HelloWorld\electron-quick-start\node_modules\electron-builder-lib\out\util\yarn.js:93:22)
at E:\HelloWorld\electron-quick-start\node_modules\electron-builder-lib\src\util\yarn.ts:20:11
at Generator.next ()
at runCallback (timers.js:789:20)
at tryOnImmediate (timers.js:751:5)
at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
at installOrRebuild (E:\HelloWorld\electron-quick-start\node_modules\electron-builder-lib\out\util\yarn.js:31:21)
at E:\HelloWorld\electron-quick-start\node_modules\electron-builder\src\cli\install-app-deps.ts:58:42
at Generator.next ()
From previous event:
at installAppDeps (E:\HelloWorld\electron-quick-start\node_modules\electron-builder\out\cli\install-app-deps.js:51:21)
at then (E:\HelloWorld\electron-quick-start\node_modules\electron-builder\src\cli\cli.ts:48:33)
at runCallback (timers.js:789:20)
at tryOnImmediate (timers.js:751:5)
at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
at Object.args [as handler] (E:\HelloWorld\electron-quick-start\node_modules\electron-builder\src\cli\cli.ts:48:33)
at Object.runCommand (E:\HelloWorld\electron-quick-start\node_modules\yargs\lib\command.js:235:44)
at Object.parseArgs [as _parseArgs] (E:\HelloWorld\electron-quick-start\node_modules\yargs\yargs.js:1014:30)
at Object.get [as argv] (E:\HelloWorld\electron-quick-start\node_modules\yargs\yargs.js:957:21)
at Object. (E:\HelloWorld\electron-quick-start\node_modules\electron-builder\src\cli\cli.ts:42:15)
at Module._compile (module.js:643:30)
at Object.Module._extensions..js (module.js:654:10)
at Module.load (module.js:556:32)
at tryModuleLoad (module.js:499:12)
at Function.Module._load (module.js:491:3)
at Function.Module.runMain (module.js:684:10)
at startup (bootstrap_node.js:187:16)
at bootstrap_node.js:608:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-quick-start@1.0.0 postinstall: electron-builder install-app-deps
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-quick-start@1.0.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:

This is what Issue I'm facing. Please help !
