### ISSUE TITLE
electron-packager ChecksumMismatchError

### ISSUE THREAD

**Issue by rykotovark** [electron/electron#10256]
electron-userland/electron-prebuilt#264

As @zeke suggested I post it here. 

Windows 8.1
npm 5.0.3
electron 1.7.6
electron-packager 8.7.2

`electron-packager .` gives the following output:
```

Downloading electron-v1.7.5-win32-ia32.zip
[============================================>] 100.0% of 44.44 MB (504.97 kB/s)
{ Error
    at ChecksumMismatchError.ErrorWithFilename (C:\Users\kotor\AppData\Roaming\npm\node_modules\electron-packager\node_modules\sumchecker\build.js:41:124)
    at new ChecksumMismatchError (C:\Users\kotor\AppData\Roaming\npm\node_modules\electron-packager\node_modules\sumchecker\build.js:56:127)
    at Hash.<anonymous> (C:\Users\kotor\AppData\Roaming\npm\node_modules\electron-packager\node_modules\sumchecker\build.js:196:22)
    at emitNone (events.js:105:13)
    at Hash.emit (events.js:207:7)
    at emitReadable_ (_stream_readable.js:502:10)
    at emitReadable (_stream_readable.js:496:7)
    at addChunk (_stream_readable.js:263:7)
    at readableAddChunk (_stream_readable.js:239:11)
    at Hash.Readable.push (_stream_readable.js:197:10)
    at Hash.Transform.push (_stream_transform.js:151:32)
    at Hash._flush (crypto.js:91:8)
    at Hash.<anonymous> (_stream_transform.js:141:12)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:105:13)
    at Hash.emit (events.js:207:7) filename: 'electron-v1.7.5-win32-ia32.zip' }
```

**Comment by MarshallOfSound** [comment]
@rykotovark Can you blow away your Electron cache folder, should force the checksums to redownload 👍

**Comment by rykotovark** [comment]
I'll try that, btw where is cache folder location?

**Comment by rykotovark** [comment]
I've googled and deleted `C:\Users\<user>\AppData\Roaming\<yourAppName>\Cache` folder, but the error remains the same.

**Comment by MarshallOfSound** [comment]
@rykotovark It's your `C:\Users\<username>\.electron` folder

**Comment by rykotovark** [comment]
@MarshallOfSound Didn't help. Now it downloads SHASUM256.txt after electron archive and fails with the same error.

**Comment by woodev01** [comment]
I'm having this same issue. Tried packaging for OSX and Linux separately, and tried packaging for --all. All had the exact same error as @rykotovark.

**Comment by chrisfranko** [comment]
I'm having this issue on OSX

**Comment by AlexzAK** [comment]
Same error on OSX

**Comment by AlexzAK** [comment]
version of electron-packager 8.7.0 has no such issue

**Comment by saenzramiro** [comment]
I have the same issue right now.

**Comment by dhruvdutt** [comment]
I'm too facing similar issues while installation.
I cloned [https://github.com/zalmoxisus/remotedev-app](remotedev-app) and ran `yarn install`

![image](https://user-images.githubusercontent.com/5961873/35209242-b81b3a64-ff72-11e7-952d-d57a7ec9a4ff.png)

**Comment by thehalvo** [comment]
updating electron-packager worked for me

`npm install electron-packager -g`

As [discussed here](https://github.com/electron-userland/electron-prebuilt/issues/264)

**Comment by nZeus** [comment]
`npm install electron-packager -g` didn't help, `resolutions` didn't help...
But then I switched to node 6.12.0, and I could finally install it :/

**Comment by MarshallOfSound** [comment]
I'm going to close this out as the checksums are checked on release nowadays to ensure that we don't release a bad checksum file.  If you get these errors I'd suggest two things:

* Ensure your electron dependencies are up to date (`electron-packager`, Etc.)
* Delete your electron cache folder
