### ISSUE TITLE
compile electron self,but cannot download libchromiumcontent.

### ISSUE THREAD

**Issue by MiyamuraMiyako** [electron/electron#10383]
* Electron version: v1.7.5
* Operating system: Ubuntu16.04.2

```
git submodule status vendor/libchromiumcontent
 349396d62b4dece64c95727e2bbfb20dda987241 vendor/libchromiumcontent (v51.0.2704.61-473-g349396d)

Downloading libchromiumcontent.zip...
https://s3.amazonaws.com/github-janky-artifacts/libchromiumcontent/linux/mips64el/349396d62b4dece64c95727e2bbfb20dda987241/libchromiumcontent.zip
Traceback (most recent call last):
  File "/home/zgx/electron/vendor/libchromiumcontent/script/download", line 180, in <module>
    sys.exit(main())
  File "/home/zgx/electron/vendor/libchromiumcontent/script/download", line 61, in main
    args.force)
  File "/home/zgx/electron/vendor/libchromiumcontent/script/download", line 126, in download_if_needed
    download(destination, base_url, commit, filename)
  File "/home/zgx/electron/vendor/libchromiumcontent/script/download", line 136, in download
    download_and_extract(destination, url)
  File "/home/zgx/electron/vendor/libchromiumcontent/script/download", line 149, in download_and_extract
    with contextlib.closing(urllib2.urlopen(url)) as u:
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "./script/bootstrap.py", line 261, in <module>
    sys.exit(main())
  File "./script/bootstrap.py", line 58, in main
    libcc_static_library_path)
  File "./script/bootstrap.py", line 163, in setup_libchromiumcontent
    subprocess.check_call([sys.executable, download, '-s'] + args)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python', '/home/zgx/electron/vendor/libchromiumcontent/script/download', '-s', '-f', '-c', '349396d62b4dece64c95727e2bbfb20dda987241', '--target_arch', 'mips64el', 'https://s3.amazonaws.com/github-janky-artifacts/libchromiumcontent', '/home/zgx/electron/vendor/download/libchromiumcontent']' returned non-zero exit status 1
```
I try ```wget https://s3.amazonaws.com/github-janky-artifacts/libchromiumcontent/linux/mips64el/349396d62b4dece64c95727e2bbfb20dda987241/libchromiumcontent.zip```,but return HTTP403.

May be bootstrap script is mistake?

this is my shell command:```./script/bootstrap.py -v --target_arch=mips64el```

**Comment by MarshallOfSound** [comment]
@MiyamuraMiyako Libchromiumcontent is not built for the arch you provided `mips64el`, hence it can't find the prebuilt to download

**Comment by MiyamuraMiyako** [comment]
@MarshallOfSound Thank you, I will try compile this lib on mips64el platform.

**Comment by toberyan** [comment]
excuse me~ I'm trying to compile libchromiumcontent on mips64el platform too.Have you finished compiling it?  I downloaded this lib sources and I'm puzzled with it. Could you share your release library on the github? Thank you and look forward your prompt  reply @MiyamuraMiyako

**Comment by MiyamuraMiyako** [comment]
@toberyan I've given this job to Lonngson, and they are contacting libchromiumcontent and electron project, but they are still working on it.
As you can see, the electron project already has mips64el branches, and I believe they will be able to accomplish this task soon.

**Comment by toberyan** [comment]
@MiyamuraMiyako Thank you for all,I will try to compile the electron project with mips64el branch.

**Comment by MiyamuraMiyako** [comment]
@toberyan Hope to hear your good news.
