### ISSUE TITLE
messed main process when bundled

### ISSUE THREAD

**Issue by aprilmintacpineda** [electron/electron#10485]
* Electron@1.6.11
* Windows 10 64bit

I want to bundle all my main processes into one uglified and minified file, just like you would with your JS files on the web. I use Electron with ES6 and electron understands ES6 via `-r babel-register .`, I am not sure if there are any other ways to do that.

Now if I don't bundle all the main processes, the app behaves and runs normally. Once I bundle all the main process files and use the bundled file, the app throws an error that has something to do with `path`.

I did a lot of research but I can't find any solution for this. I have read this https://github.com/chentsulin/electron-react-boilerplate/issues/139 and also have tried this https://github.com/chentsulin/electron-react-boilerplate/issues/139#issuecomment-207596776 and also have read this https://github.com/chentsulin/electron-react-boilerplate/pull/197 but nothing seems to work for me.

### The error

```
App threw an error during load
TypeError: Path must be a string. Received undefined
    at assertPath (path.js:7:11)
    at Object.basename (path.js:799:5)
    at Object.<anonymous> (C:/Users/aprilpineda/Documents/projects/desktop/experiments/1-lendingInfoSys/app/scripts/main.js:1:701)
    at Object.<anonymous> (C:/Users/aprilpineda/Documents/projects/desktop/experiments/1-lendingInfoSys/app/scripts/main.js:1:1034)
    at n (C:/Users/aprilpineda/Documents/projects/desktop/experiments/1-lendingInfoSys/app/scripts/main.js:1:101)
    at Object.<anonymous> (C:/Users/aprilpineda/Documents/projects/desktop/experiments/1-lendingInfoSys/app/scripts/main.js:1:32483)
    at n (C:/Users/aprilpineda/Documents/projects/desktop/experiments/1-lendingInfoSys/app/scripts/main.js:1:101)
    at Object.<anonymous> (C:/Users/aprilpineda/Documents/projects/desktop/experiments/1-lendingInfoSys/app/scripts/main.js:1:1677)
    at n (C:/Users/aprilpineda/Documents/projects/desktop/experiments/1-lendingInfoSys/app/scripts/main.js:1:101)
    at Object.<anonymous> (C:/Users/aprilpineda/Documents/projects/desktop/experiments/1-lendingInfoSys/app/scripts/main.js:1:2597)
    at Object.e.__esModule.default (C:/Users/aprilpineda/Documents/projects/desktop/experiments/1-lendingInfoSys/app/scripts/main.js:1:3022)
    at n (C:/Users/aprilpineda/Documents/projects/desktop/experiments/1-lendingInfoSys/app/scripts/main.js:1:101)
    at C:/Users/aprilpineda/Documents/projects/desktop/experiments/1-lendingInfoSys/app/scripts/main.js:1:477
    at Object.<anonymous> (C:/Users/aprilpineda/Documents/projects/desktop/experiments/1-lendingInfoSys/app/scripts/main.js:1:2)
    at Object.<anonymous> (C:\Users\aprilpineda\Documents\projects\desktop\experiments\1-lendingInfoSys\app\scripts\main.js:821:3)
    at Module._compile (module.js:571:32)
    at loader (C:\Users\aprilpineda\Documents\projects\desktop\experiments\1-lendingInfoSys\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\aprilpineda\Documents\projects\desktop\experiments\1-lendingInfoSys\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at loadApplicationPackage (C:\Users\aprilpineda\Documents\projects\desktop\experiments\1-lendingInfoSys\node_modules\electron\dist\resources\default_app.asar\main.js:283:12)
```

### My webpack config

```
const webpack = require('webpack');
const ExtractTextWebpackPlugin = require('extract-text-webpack-plugin');
const OptimizeCssAssetsWebpackPlugin = require('optimize-css-assets-webpack-plugin');
const path = require('path');
const fs = require('fs');

var uglifyJsPlugin = process.env.PROD == 1? [
  new webpack.optimize.UglifyJsPlugin({
    sourceMap: false,
    output: {
      comments: false
    },
    compressor: {
      warnings: false
    }
  }),

  new webpack.DefinePlugin({
    'process.env': {
      NODE_ENV: JSON.stringify('production')
    }
  })
] : [];

var uglifyCssPlugin = process.env.PROD == 1? [ new OptimizeCssAssetsWebpackPlugin() ] : []

var node_modules = {};

fs.readdirSync('node_modules')
  .filter(function(x) {
    return ['.bin'].indexOf(x) === -1;
  })
  .forEach(function(mod) {
    node_modules[mod] = 'commonjs ' + mod;
  });

module.exports = [
  {
    externals: node_modules,
    node: {
      __filename: true,
      __dirname: true
    },
    target: 'electron-renderer',
    name: 'react-stuff',
    entry: path.join(__dirname, '/resources/scripts/entry.js'),
    output: {
      filename: 'app.js',
      path: path.join(__dirname, '/app/scripts')
    },
    module: {
      loaders: [
        {
          test: /\.js/,
          loader: 'babel-loader',
          exclude: /node_modules/,
          query: {
            presets: ['react', 'es2017', 'es2016', 'es2015'],
            plugins: ['babel-plugin-transform-object-rest-spread', 'babel-plugin-transform-class-properties']
          }
        }
      ]
    },
    plugins: uglifyJsPlugin
  },

  {
    externals: node_modules,
    node: {
      global: true,
      __filename: true,
      __dirname: true
    },
    target: 'electron-main',
    name: 'electron main',
    entry: path.join(__dirname, '/main_process/entry.js'),
    output: {
      pathinfo: true,
      filename: 'main.js',
      path: path.join(__dirname, '/app/scripts')
    },
    module: {
      loaders: [
        {
          test: /\.js/,
          loader: 'babel-loader',
          exclude: /node_modules/,
          query: {
            presets: ['react', 'es2017', 'es2016', 'es2015'],
            plugins: ['babel-plugin-transform-object-rest-spread', 'babel-plugin-transform-class-properties']
          }
        }
      ]
    },
    plugins: uglifyJsPlugin
  },

  {
    name: 'stylesheets',
    entry: path.join(__dirname, '/resources/styles/entry.sass'),
    output: {
      filename: 'app.css',
      path: path.join(__dirname, '/app/styles')
    },
    module: {
      loaders: [
        {
          test: /\.sass/,
          loader: ExtractTextWebpackPlugin.extract({
            use: 'css-loader?url=false!sass-loader?url=false',
            fallback: 'style-loader'
          })
        }
      ]
    },
    plugins: [
      new ExtractTextWebpackPlugin('app.css')
    ].concat(uglifyCssPlugin)
  }
];
```

P.S.

Please don't close the issue until the problem is solved, I think a lot of other people out there are still struggling with this.

**Comment by MarshallOfSound** [comment]
This issue always comes back to webpack messing with paths through `__dirname` and `__filename`.  Somehow you have to tell WebPack not to screw with those paths 😄

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by aprilmintacpineda** [comment]
@MarshallOfSound since you spent time reading that why didn't you give a solution? I already added the following lines to my webpack config, I thought these are enough to tell webpack not to screw with `__dirname` and `__filename`

```
node: {
  global: true,
  __filename: true,
  __dirname: true
},
```

I mean no disrespect but if this issue always comes back, somebody should do something about that.

**Comment by MarshallOfSound** [comment]
> GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the community or to the Slack Channel.

Gonna preface by saying IMO you shouldn't be using webpack + electron.  That said:

You need to set your webpack target to "node"

**Comment by aprilmintacpineda** [comment]
I have tried targeting node and I have been through here https://github.com/webpack/webpack/issues/1599 and those solutions don't work. I tried running with only `console.log(__dirname)` and `__dirname` was equal to the string `main_process`, and `__filename` was equal to the string `main_process\entry.js`.

Let's face this, I have always asked in slack chats and they would simply pass you by with not a care in what you said. That's why I attempted to post this here.

**Comment by peteringram0** [comment]
@aprilmintacpineda Did u ever get the issue sorted at all? Im seeing the same thing with my __dirname being messed up on production builds. Similar config to you. Thanks,

**Comment by aprilmintacpineda** [comment]
@peteringram0 This was a long time ago. I've already forgotten it. However, should you wish to figure it out yourself, I open-sourced a project of mine.

Please check out the repo here -> https://github.com/aprilmintacpineda/lending-information-management-system
