### ISSUE TITLE
Build fails when running on Windows 10, trying to build for x64 arch type

### ISSUE THREAD

**Issue by anupam** [electron/electron#10722]
Trying to build electron from the master branch, the bootstrap.py command succeeds but build fails with this : 
```
ninja: Entering directory `out\R'
[938/1192] LINK_EMBED(DLL) node.dll
FAILED: C:\Python27\python.exe gyp-win-tool link-with-manifests environment.x64 True node.dll "C:\Python27\python.exe gyp-win-tool link-wrapper environment.x64 False link.exe /nologo /IMPLIB:node.dll.lib /DLL /OUT:node.dll @node.dll.rsp" 2 mt.exe rc.exe "obj\vendor\node\node.node.dll.intermediate.manifest" obj\vendor\node\node.node.dll.generated.manifest
v8.lib(api.obj) : MSIL .netmodule or module compiled with /GL found; restarting link with /LTCG; add /LTCG to the link command line to improve linker performance
C:\Users\denimuser\playground\electron\vendor\download\libchromiumcontent\static_library\v8.lib : fatal error LNK1107: invalid or corrupt file: cannot read at 0x1260DFEC
Traceback (most recent call last):
  File "gyp-win-tool", line 323, in <module>
    sys.exit(main(sys.argv[1:]))
  File "gyp-win-tool", line 29, in main
    exit_code = executor.Dispatch(args)
  File "gyp-win-tool", line 71, in Dispatch
    return getattr(self, method)(*args[1:])
  File "gyp-win-tool", line 179, in ExecLinkWithManifests
    subprocess.check_call(ldcmd + add_to_ld)
  File "C:\Python27\lib\subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'C:\Python27\python.exe gyp-win-tool link-wrapper environment.x64 False link.exe /nologo /IMPLIB:node.dll.lib /DLL /OUT:node.dll @node.dll.rsp node.dll.manifest.res' returned non-zero exit status 1107
[938/1192] CXX obj\atom\browser\api\electron_lib.atom_api_app.obj
ninja: build stopped: subcommand failed.
```

I have node js and python 64 bit installed with Visual Studio 2015 update 3 x64 build. 
Any help is greatly appreciated.

**Comment by jkleinsc** [comment]
@anupam we were experimenting with how we build libchromiumcontent and in so doing caused an issue with building release builds.  Once #10759 is merged this issue will be resolved.
