### ISSUE TITLE
Uncaught Error: ENOTDIR: not a directory, readlink '/Users/xzns/Documents/code/electron/electron/spec/fixtures/asar/a.asar/dir1/link1'     at Object.fs.readlinkSync (fs.js:997:18)

### ISSUE THREAD

**Issue by francescoyang** [electron/electron#10816]
fs.js:997 Uncaught Error: ENOTDIR: not a directory, readlink '~Documents/code/electron/electron/spec/fixtures/asar/a.asar/dir1/link1'
    at Object.fs.readlinkSync (fs.js:997:18)
    at addExtraFieldsSync (/Users/xzns/Documents/code/electron/Rocket.Chat.Electron/node_modules/fs-jetpack/lib/inspect.js:82:30)
    at Object.inspectSync [as sync] (~/Documents/code/electron/Rocket.Chat.Electron/node_modules/fs-jetpack/lib/inspect.js:107:3)
    at walkSync (/Users/xzns/Documents/code/electron/Rocket.Chat.Electron/node_modules/fs-jetpack/lib/utils/tree_walker.js:15:24)
    at list.sync.forEach (/Users/xzns/Documents/code/electron/Rocket.Chat.Electron/node_modules/fs-jetpack/lib/utils/tree_walker.js:24:7)
    at Array.forEach (native)
    at walkSync (/Users/xzns/Documents/code/electron/Rocket.Chat.Electron/node_modules/fs-jetpack/lib/utils/tree_walker.js:23:21)
    at list.sync.forEach (/Users/xzns/Documents/code/electron/Rocket.Chat.Electron/node_modules/fs-jetpack/lib/utils/tree_walker.js:24:7)
    at Array.forEach (native)
    at walkSync (/Users/xzns/Documents/code/electron/Rocket.Chat.Electron/node_modules/fs-jetpack/lib/utils/tree_walker.js:23:21)

Help

**Comment by sofianguy** [comment]
Hi @francescoyang can you please provide us with the following for us to better help you:
- Electron version
- operating system
- steps to reproduce issue

**Comment by sofianguy** [comment]
@francescoyang 
Thank you for your issue!

We haven't gotten a response to our questions in our [comment](https://github.com/electron/electron/issues/10816#issuecomment-337290235). With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
