### ISSUE TITLE
BrowserWindow gets destroyed although there's an event.preventDefault in close handler

### ISSUE THREAD

**Issue by stoically** [electron/electron#10871]
Hi,

* Electron version: 1.6.15, 1.7.9 and 1.8.2-beta1
* Operating system: Ubuntu 16.04.3 LTS

### Expected behavior

Should be able to cancel the closing of the BrowserWindow, hide it instead and show it again.

### Actual behavior

BrowserWindow gets destroyed although there's an event.preventDefault call in the close handler.

Error Alert:
```
Uncaught Exception:
Error: Object has been destroyed
    at MenuItem.click (/home/user/.nvm/versions/node/v8.7.0/lib/node_modules/electron/dist/resources/electron.asar/browser/api/menu-item.js:52:9)
    at Function.executeCommand (/home/user/.nvm/versions/node/v8.7.0/lib/node_modules/electron/dist/resources/electron.asar/browser/api/menu.js:121:15)
```

### How to reproduce

Make sure that `libappindicator1` is installed
`git clone` https://github.com/stoically/electron-issue.git
`cd electron-issue`
`electron .`
Close BrowserWindow by clicking on the X
Try to restore BrowserWindow by right-clicking on the "E" Tray Icon and selecting "Show Example"

### Notes

Besides the minimal bootstrap, what matters is this part:
```javascript
  mainWindow.on('close', function (event) {
    if (app.isQuiting) {
      return;
    }
    mainWindow.hide();
    event.preventDefault()
  });
```

```javascript
  const contextMenu = Menu.buildFromTemplate([
    {label: 'Show Example', type: 'normal', click: mainWindow.show},
``` 

To my knowledge and based on my research the `event.preventDefault` should prevent the mainWindow from getting destroyed. Hopefully I didn't make a simple rookie mistake. If I can provide further Information please let me know.

Thanks for your work!

Best regards

**Comment by stoically** [comment]
It works like a charm after changing
```
{label: 'Show Example', type: 'normal', click: mainWindow.show}
```
to
```
{label: 'Show Example', type: 'normal', click: () => mainWindow.show()}
```

Not exactly sure what's the difference here, but it works. Oh well.
