### ISSUE TITLE
Electron bootstrap checksum failure

### ISSUE THREAD

**Issue by seriouz** [electron/electron#10904]
Electron bootstrapping is failing.

This is the command i use `> python script/bootstrap.py -v`

And here is the problem:

```
npm info lifecycle dugite@1.47.0~postinstall: dugite@1.47.0

> dugite@1.47.0 postinstall C:\code\electron\node_modules\dugite
> node ./script/download-git.js

Validation failed. Expected 'db14ddc1281606b001a44b70f2fc3deda6e60686de06d135056205216c2a5663' but got 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855'
Downloading Git from: https://github.com/desktop/dugite-native/releases/download/v2.14.3-rc1/dugite-native-v2.14.3-win32-23.tar.gz
Error raised while downloading https://github.com/desktop/dugite-native/releases/download/v2.14.3-rc1/dugite-native-v2.14.3-win32-23.tar.gz { [Error: connect ETIMEDOUT 192.30.253.112:443]
  code: 'ETIMEDOUT',
  errno: 'ETIMEDOUT',
  syscall: 'connect',
  address: '192.30.253.112',
  port: 443 }
.
.
.
.
.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! dugite@1.47.0 postinstall: `node ./script/download-git.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the dugite@1.47.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 1, true ]

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jm\AppData\Roaming\npm-cache\_logs\2017-10-25T08_10_44_938Z-debug.log
None
Traceback (most recent call last):
  File "script/bootstrap.py", line 261, in <module>
    sys.exit(main())
  File "script/bootstrap.py", line 55, in main
    update_node_modules('.')
  File "C:\code\electron\script\lib\util.py", line 289, in update_node_modules
    execute_stdout(args, env)
  File "C:\code\electron\script\lib\util.py", line 184, in execute_stdout
    raise e
subprocess.CalledProcessError: Command '['npm.cmd', 'install', '--verbose']' returned non-zero exit status 1
```

* Electron version: Current Master Branch
* Operating system: Win x64

**Comment by sofianguy** [comment]
@seriouz Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
