### ISSUE TITLE
autoUpdater.quitAndInstall() is losing context when reloading main window

### ISSUE THREAD

**Issue by magne4000** [electron/electron#10952]
* Electron version: 1.7.6, 1.7.8
* Operating system: MacOS

### Expected behavior
`autoUpdater.quitAndInstall()` should install the update and restart the app

### Actual behavior
`autoUpdater.quitAndInstall()` trigger the following error
<pre>
[20:00:41:0288] [error] Error: No update available, can't quit and install
    at sagaPrepareQuit (/Users/magne/workspace/browserX/release/mac/Station QA.app/Contents/Resources/app.asar/app/app/sagas.js:74:27)
    at sagaPrepareQuit.next (<anonymous>)
    at wrappedTryCatch (/Users/magne/workspace/browserX/release/mac/Station QA.app/Contents/Resources/app.asar/app/utils/sagas.ts:12:20)
    at wrappedTryCatch.next (<anonymous>)
    at next (/Users/magne/workspace/browserX/release/mac/Station QA.app/Contents/Resources/app.asar/node_modules/redux-saga/lib/internal/proc.js:311:27)
    at currCb (/Users/magne/workspace/browserX/release/mac/Station QA.app/Contents/Resources/app.asar/node_modules/redux-saga/lib/internal/proc.js:388:7)
    at tryCatcher (/Users/magne/workspace/browserX/release/mac/Station QA.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/magne/workspace/browserX/release/mac/Station QA.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:512:31)
    at Promise._settlePromise (/Users/magne/workspace/browserX/release/mac/Station QA.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:569:18)
    at Promise._settlePromise0 (/Users/magne/workspace/browserX/release/mac/Station QA.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/Users/magne/workspace/browserX/release/mac/Station QA.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/promise.js:693:18)
    at Async._drainQueue (/Users/magne/workspace/browserX/release/mac/Station QA.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/Users/magne/workspace/browserX/release/mac/Station QA.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues (/Users/magne/workspace/browserX/release/mac/Station QA.app/Contents/Resources/app.asar/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
</pre>

### How to reproduce
~~Use `autoUpdater.checkForUpdates()` as intended (from browser process), but instead of calling `autoUpdater.quitAndInstall()` right away, call `reload()` method on main window, then call `autoUpdater.quitAndInstall()`~~

Use `autoUpdater.checkForUpdates()` as intended (from browser process), wait for it to actually download the update, and call `autoUpdater.checkForUpdates()` once again

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
