### ISSUE TITLE
Exception with Menu.setApplicationMenu(null) since 1.8.2-beta.2

### ISSUE THREAD

**Issue by simast** [electron/electron#11052]
* Electron version: 1.8.2-beta.2
* Operating system: macOS 10.13.1

### Expected behavior

As per documentation `Menu.setApplicationMenu(null)` should remove menu bar in Windows/Linux and do nothing in macOS.

### Actual behavior

Exception is thrown (starting with Electron 1.8.2-beta.2 version):

```
TypeError: Cannot read property 'constructor' of null
    at Function.Menu.setApplicationMenu (<hidden>/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/api/menu.js:136:21)
    at App._electron.app.on (<hidden>)
    at emitTwo (events.js:130:20)
    at App.emit (events.js:213:7)
```

### How to reproduce

Try calling static `Menu.setApplicationMenu(null)` from app `ready` event.

**Comment by felixrieseberg** [comment]
Yep, that's a bug. On it!
