### ISSUE TITLE
Link error occurred when building 1.8.2-beta2 using Release configuration

### ISSUE THREAD

**Issue by BSoD-Ultimate** [electron/electron#11071]
* Electron version: 1.8.2-beta2
* Operating system: windows 8.1

I attempted to build Electron 1.8.2-beta2 from the source. No Error occurred when performing the debug build. However, when I tried to build Electron using release configuration, the script raised an error during linkage of node.dll. The linker seems cannot find a proper .lib file related to v8 javascript engine, it generated the following error:

```

PS D:\electron> python script/build.py -c R
ninja: Entering directory `out\R'
[1/21] LINK_EMBED(DLL) node.dll
FAILED: C:\Python27\python.exe gyp-win-tool link-with-manifests environment.x86 True node.dll "C:\Python27\python.exe gyp-win-tool link-wrapper environment.x86 False link.exe /nologo /IMPLIB:node.dll.lib /DLL /OUT:node.dll @node.dll.rsp" 2 mt.exe rc.exe "obj\vendor\node\node.node.dll.intermediate.manifest" obj\vendor\node\node.node.dll.generated.manifest
node.inspector_agent.obj : error LNK2001: unresolved external symbol "public: __thiscall v8::HandleScope::HandleScope(class v8::Isolate *)" (??0HandleScope@v8@@QAE@PAVIsolate@1@@Z)

node.node_crypto.obj : error LNK2001: unresolved external symbol "public: __thiscall v8::HandleScope::HandleScope(class v8::Isolate *)" (??0HandleScope@v8@@QAE@PAVIsolate@1@@Z)

node.tls_wrap.obj : error LNK2001: unresolved external symbol "public: __thiscall v8::HandleScope::HandleScope(class v8::Isolate *)" (??0HandleScope@v8@@QAE@PAVIsolate@1@@Z)

--- unresolved external symbol errors ---

node.osfhandle.obj : error LNK2019: unresolved external symbol "public: static class std::unique_ptr<class v8::TracingCpuProfiler,struct std::default_delete<class v8::TracingCpuProfiler> > __cdecl v8::TracingCpuProfiler::Create(class v8::Isolate *)" (?Create@TracingCpuProfiler@v8@@SA?AV?$unique_ptr@VTracingCpuProfiler@v8@@U?$default_delete@VTracingCpuProfiler@v8@@@std@@@std@@PAVIsolate@2@@Z) referenced in function "void __cdecl node::ReferenceSymbols(void)" (?ReferenceSymbols@node@@YAXXZ)

node.osfhandle.obj : error LNK2019: unresolved external symbol "public: static bool __cdecl v8_inspector::V8InspectorSession::canDispatchMethod(class v8_inspector::StringView const &)" (?canDispatchMethod@V8InspectorSession@v8_inspector@@SA_NABVStringView@2@@Z) referenced in function "void __cdecl node::ReferenceSymbols(void)" (?ReferenceSymbols@node@@YAXXZ)

node.dll : fatal error LNK1120: 434 unresolved externals

Traceback (most recent call last):

  File "gyp-win-tool", line 323, in <module>

    sys.exit(main(sys.argv[1:]))

  File "gyp-win-tool", line 29, in main

    exit_code = executor.Dispatch(args)

  File "gyp-win-tool", line 71, in Dispatch

    return getattr(self, method)(*args[1:])

  File "gyp-win-tool", line 179, in ExecLinkWithManifests

    subprocess.check_call(ldcmd + add_to_ld)

  File "C:\Python27\lib\subprocess.py", line 186, in check_call

    raise CalledProcessError(retcode, cmd)

subprocess.CalledProcessError: Command 'C:\Python27\python.exe gyp-win-tool link-wrapper environment.x86 False link.exe /nologo /IMPLIB:node.dll.lib /DLL /OUT:node.dll @node.dll.rsp node.dll.manifest.res' returned non-zero exit status 1120

ninja: build stopped: subcommand failed.

```

### Expected behavior
The build script performed with no error happens and release build was successfully generated.

Both downloading libchromiumcontent from amazon-AWS and building libchromiumcontent on my own from the source when executing bootstrap.py can cause the above error when building release binaries of Electron.

PS: I need to build Electron and libchromiumcontent from the source code because I was required to create native node-modules on Electron. Getting debug symbols of chromium libraries helps a lot in the 
debug process.

**Comment by MarshallOfSound** [comment]
@BSoD-Ultimate Just did a clean clone and on latest master ran

```bash
python script\bootstrap.py -v
python script\build.py -c R
```

And it didn't hit any linking issues, can you try again from a fresh bootstrap?

**Comment by BSoD-Ultimate** [comment]
The issue occurred on tag v1.8.2-beta.2. So it will be fixed in further releases, right? If so I will close the issue.
