### ISSUE TITLE
Failed to read responseText from XMLHttpRequest with type arraybuffer

### ISSUE THREAD

**Issue by Crecket** [electron/electron#11083]
* Electron version: 1.8.1
* Operating system: Microsoft Windows 10 Education

### Expected behavior
The http request should be handled without throwing an error.

### Actual behavior
An error is thrown when a request is done with the type ArrayBuffer. This is caused by the [following code](https://github.com/electron/electron/blob/master/lib/renderer/api/remote.js#L67) where it tries to access the 'responseText' property when it isn't accessible.

`Uncaught (in promise) DOMException: Failed to read the 'responseText' property from 'XMLHttpRequest': The value is only accessible if the object's 'responseType' is '' or 'text' (was 'arraybuffer')`

### How to reproduce
Send a request with the responseType 'arrayBuffer'
```JS 
var xhr = new XMLHttpRequest();
xhr.responseType = "arraybuffer";
xhr.open("get", "http://example.com/");
xhr.onload = function(data) {
};
xhr.send();
```

**Comment by felixrieseberg** [comment]
I'm unable to reproduce the issue with Electron 1.8.2. Is it still breaking for you with the latest version?

**Comment by Crecket** [comment]
I think it has to do with the target page not returning an actual arraybuffer, I replaced my personal url with example.com. I'll create a working example as soon as I can

**Comment by Crecket** [comment]
It looks like the issue is more complicated than I thought. It might have to do with the request using  responsType arraybuffer, but the response returns json data thanks to the error that occurred. So electron sees the json response and tries to access responseText on the result when it shouldn't be possible?

I can't seem to reliably replicate it in a test repository since it only seems to happen for the specific API endpoint that I am using.

```
Uncaught (in promise) DOMException: Failed to read the 'responseText' property from 'XMLHttpRequest': The value is only accessible if the object's 'responseType' is '' or 'text' (was 'arraybuffer').
    at valueToMeta (E:\www\BunqDesktop\node_modules\electron\dist\resources\electron.asar\renderer\api\remote.js:72:36)
    at valueToMeta (E:\www\BunqDesktop\node_modules\electron\dist\resources\electron.asar\renderer\api\remote.js:72:18)
    at Array.map (native)
    at wrapArgs (E:\www\BunqDesktop\node_modules\electron\dist\resources\electron.asar\renderer\api\remote.js:96:15)
    at Object.remoteMemberFunction (E:\www\BunqDesktop\node_modules\electron\dist\resources\electron.asar\renderer\api\remote.js:117:95)
    at AttachmentImage._callee$ (file:///E:/www/BunqDesktop/app/react/BunqDesktop.js:100361:46)
    at tryCatch (file:///E:/www/BunqDesktop/app/react/BunqDesktop.js:100562:40)
    at Generator.invoke [as _invoke] (file:///E:/www/BunqDesktop/app/react/BunqDesktop.js:100796:22)
    at Generator.prototype.(anonymous function) [as throw] (file:///E:/www/BunqDesktop/app/react/BunqDesktop.js:100614:21)
    at step (file:///E:/www/BunqDesktop/app/react/BunqDesktop.js:100288:191)
```

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v2.0.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons.

Thanks in advance! Your help is appreciated.
