### ISSUE TITLE
[build] unable to find glibconfig.h

### ISSUE THREAD

**Issue by elegos** [electron/electron#11195]
* Electron version: 1.7.9
* Operating system: Fedora 27 (64 bit)

### Expected behavior

The electron `create-dist.py` should compile, finding `glibconfig.h`

### Actual behavior

```
FAILED: ../../vendor/llvm-build/Release+Asserts/bin/clang++ -MMD -MF obj/brightray/browser/linux/brightray.notification_presenter_linux.o.d -DV8_USE_EXTERNAL_STARTUP_DATA -DV8_PROMISE_INTERNAL_FIELD_COUNT=1 -DSK_SUPPORT_LEGACY_GETTOPDEVICE -DSK_SUPPORT_LEGACY_BITMAP_CONFIG -DSK_SUPPORT_LEGACY_DEVICE_VIRTUAL_ISOPAQUE -DSK_SUPPORT_LEGACY_N32_NAME -DSK_SUPPORT_LEGACY_SETCONFIG -DSK_IGNORE_ETC1_SUPPORT -DSK_IGNORE_GPU_DITHER -DDISABLE_NACL -DTOOLKIT_VIEWS -DUSE_AURA -DUSE_X11 -DUSE_NSS_CERTS -DUSE_NSS -D_LARGEFILE_SOURCE -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64 -DNDEBUG -I../.. -I/home/makerpm/rpmbuild/BUILD/electron/vendor/download/libchromiumcontent/src -I/home/makerpm/rpmbuild/BUILD/electron/vendor/download/libchromiumcontent/src/skia/config -I/home/makerpm/rpmbuild/BUILD/electron/vendor/download/libchromiumcontent/src/third_party/boringssl/src/include -I/home/makerpm/rpmbuild/BUILD/electron/vendor/download/libchromiumcontent/src/third_party/skia/include/core -I/home/makerpm/rpmbuild/BUILD/electron/vendor/download/libchromiumcontent/src/third_party/mojo/src -I/home/makerpm/rpmbuild/BUILD/electron/vendor/download/libchromiumcontent/src/third_party/WebKit -I/home/makerpm/rpmbuild/BUILD/electron/vendor/download/libchromiumcontent/static_library/gen -Wno-inconsistent-missing-override -Wno-undefined-var-template -I/home/makerpm/rpmbuild/BUILD/electron/vendor/debian_jessie_amd64-sysroot/usr/include/gtk-2.0 -I/home/makerpm/rpmbuild/BUILD/electron/vendor/debian_jessie_amd64-sysroot/usr/lib64/gtk-2.0/include -I/home/makerpm/rpmbuild/BUILD/electron/vendor/debian_jessie_amd64-sysroot/usr/include/pango-1.0 -I/home/makerpm/rpmbuild/BUILD/electron/vendor/debian_jessie_amd64-sysroot/usr/include/glib-2.0 -I/home/makerpm/rpmbuild/BUILD/electron/vendor/debian_jessie_amd64-sysroot/usr/lib64/glib-2.0/include -I/home/makerpm/rpmbuild/BUILD/electron/vendor/debian_jessie_amd64-sysroot/usr/include/cairo -I/home/makerpm/rpmbuild/BUILD/electron/vendor/debian_jessie_amd64-sysroot/usr/include/pixman-1 -I/home/makerpm/rpmbuild/BUILD/electron/vendor/debian_jessie_amd64-sysroot/usr/include/freetype2 -I/home/makerpm/rpmbuild/BUILD/electron/vendor/debian_jessie_amd64-sysroot/usr/include/libpng16 -I/home/makerpm/rpmbuild/BUILD/electron/vendor/debian_jessie_amd64-sysroot/usr/include/harfbuzz -I/home/makerpm/rpmbuild/BUILD/electron/vendor/debian_jessie_amd64-sysroot/usr/include/gdk-pixbuf-2.0 -I/home/makerpm/rpmbuild/BUILD/electron/vendor/debian_jessie_amd64-sysroot/usr/include/atk-1.0 -I/home/makerpm/rpmbuild/BUILD/electron/vendor/debian_jessie_amd64-sysroot/usr/include/dbus-1.0 -I/home/makerpm/rpmbuild/BUILD/electron/vendor/debian_jessie_amd64-sysroot/usr/lib64/dbus-1.0/include -I/home/makerpm/rpmbuild/BUILD/electron/vendor/debian_jessie_amd64-sysroot/usr/include/gconf/2 -pthread -I/home/makerpm/rpmbuild/BUILD/electron/vendor/debian_jessie_amd64-sysroot/usr/include/nss3 -I/home/makerpm/rpmbuild/BUILD/electron/vendor/debian_jessie_amd64-sysroot/usr/include/nspr4 -Wno-deprecated-register -Wno-sentinel --sysroot=/home/makerpm/rpmbuild/BUILD/electron/vendor/debian_jessie_amd64-sysroot -m64 -march=x86-64 -O2 -g -fno-ident -fdata-sections -ffunction-sections -std=c++11 -Wno-reserved-user-defined-literal -D__STRICT_ANSI__ -fno-rtti  -c ../../brightray/browser/linux/notification_presenter_linux.cc -o obj/brightray/browser/linux/brightray.notification_presenter_linux.o
In file included from ../../brightray/browser/linux/notification_presenter_linux.cc:8:
In file included from ../../brightray/browser/linux/libnotify_notification.h:11:
In file included from ../../brightray/browser/linux/libnotify_loader.h:8:
In file included from /home/makerpm/rpmbuild/BUILD/electron/vendor/debian_jessie_amd64-sysroot/usr/include/libnotify/notify.h:25:
In file included from /home/makerpm/rpmbuild/BUILD/electron/vendor/debian_jessie_amd64-sysroot/usr/include/glib-2.0/glib.h:30:
In file included from /home/makerpm/rpmbuild/BUILD/electron/vendor/debian_jessie_amd64-sysroot/usr/include/glib-2.0/glib/galloca.h:32:
/home/makerpm/rpmbuild/BUILD/electron/vendor/debian_jessie_amd64-sysroot/usr/include/glib-2.0/glib/gtypes.h:32:10: fatal error: 'glibconfig.h' file not found
#include <glibconfig.h>
         ^~~~~~~~~~~~~~
1 error generated.
ninja: build stopped: subcommand failed.

Traceback (most recent call last):
  File "./script/create-dist.py", line 314, in <module>
    sys.exit(main())
  File "./script/create-dist.py", line 85, in main
    force_build()
  File "./script/create-dist.py", line 114, in force_build
    execute([sys.executable, build, '-c', 'Release'])
  File "/home/makerpm/rpmbuild/BUILD/electron/script/lib/util.py", line 174, in execute
    raise e
subprocess.CalledProcessError: Command '['/usr/bin/python', '/home/makerpm/rpmbuild/BUILD/electron/script/build.py', '-c', 'Release']' returned non-zero exit status 1
```

### How to reproduce

Here attached ([atom.zip](https://github.com/electron/electron/files/1490043/atom.zip)) you can find a simple docker-based environment which will let you reproduce the error easily without have the need of a Fedora workstation (the build instructions are inside the `spec/electron.1.7.9.spec` file, but you just need to execute `build.sh` via `./build.sh`).

With Fedora 27, install all the dev requirements and execute `bootstrap.py` first and `create-dist.py` after. The second process will fail as reported, not finding `glibconfig.h`.

As far as I've understood

, `vendor/debian_jessie_amd64-sysroot` is bound to the local `/`, so it should include the right folder (`-I/home/makerpm/rpmbuild/BUILD/electron/vendor/debian_jessie_amd64-sysroot/usr/lib64/glib-2.0/include`).

The header file is right where it should be:
```
$ ls -l /usr/lib64/glib-2.0/include
totale 8
-rw-r--r--. 1 root root 5554  1 nov 16.18 glibconfig.h
```

The file is provided by `glib2-devel` (which is installed)

UPDATE:
I thought it was a chroot, but it's not. Apparently the header file is in the following path: `debian_jessie_amd64-sysroot/usr/lib/x86_64-linux-gnu/glib-2.0/include/glibconfig.h`, but it's not in the CXXFLAGS include dirs somehow

**Comment by elegos** [comment]
Update:

if I try to build using the local `clang` (using `./script/bootstrap.py --clang_dir /usr`), I come up with a different error during the `./script/create-dist.py` (this with 1.8.x, due to some lib incompatibilities with old 1.7.x deps):

```
...
[858/1191] CXX obj/vendor/breakpad/src/common/dwarf/dump_syms.elf_reader.o
FAILED: /usr/bin/clang++ -MMD -MF obj/vendor/node/src/node.node_crypto.o.d '-DNODE_ARCH="x64"' '-DNODE_PLATFORM="linux"' -DNODE_WANT_INTERNALS=1 -DV8_DEPRECATION_WARNINGS=1 -DNODE_SHARED_MODE -DNODE_USE_V8_PLATFORM=0 '-DNODE_RELEASE_URLBASE="https://atom.io/download/electron"' -DHAVE_INSPECTOR=1 -DHAVE_OPENSSL=1 -D__POSIX__ -DHTTP_PARSER_STRICT=0 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D_POSIX_C_SOURCE=200112 -DV8_USE_EXTERNAL_STARTUP_DATA -DV8_PROMISE_INTERNAL_FIELD_COUNT=1 -DSK_SUPPORT_LEGACY_GETTOPDEVICE -DSK_SUPPORT_LEGACY_BITMAP_CONFIG -DSK_SUPPORT_LEGACY_DEVICE_VIRTUAL_ISOPAQUE -DSK_SUPPORT_LEGACY_N32_NAME -DSK_SUPPORT_LEGACY_SETCONFIG -DSK_IGNORE_ETC1_SUPPORT -DSK_IGNORE_GPU_DITHER -DDISABLE_NACL -DTOOLKIT_VIEWS -DUSE_AURA -DUSE_X11 -DUSE_NSS_CERTS -DUSE_NSS -D_LARGEFILE64_SOURCE -DNDEBUG -I../../vendor/node/src -I../../vendor/node/tools/msvs/genfiles -I../../vendor/node/deps/uv/src/ares -Igen -I../../vendor/node/deps/openssl/openssl/include -I../../vendor/node/deps/zlib -I../../vendor/node/deps/http_parser -I../../vendor/node/deps/cares/include -I../../vendor/node/deps/uv/include -I/home/makerpm/rpmbuild/BUILD/electron/vendor/download/libchromiumcontent/src -I/home/makerpm/rpmbuild/BUILD/electron/vendor/download/libchromiumcontent/src/third_party/icu/source/common -I/home/makerpm/rpmbuild/BUILD/electron/vendor/download/libchromiumcontent/src/third_party/icu/source/i18n -I/home/makerpm/rpmbuild/BUILD/electron/vendor/download/libchromiumcontent/src/v8 -I/home/makerpm/rpmbuild/BUILD/electron/vendor/download/libchromiumcontent/src/v8/include -Wno-inconsistent-missing-override -Wno-undefined-var-template -Wno-parentheses-equality -Wno-unused-function -Wno-sometimes-uninitialized -Wno-pointer-sign -Wno-string-plus-int -Wno-unused-variable -Wno-unused-value -Wno-deprecated-declarations -Wno-return-type -Wno-shift-negative-value -Wno-format -Wno-varargs -fPIC --sysroot=/home/makerpm/rpmbuild/BUILD/electron/vendor/debian_jessie_amd64-sysroot -m64 -march=x86-64 -O2 -g -fno-ident -fdata-sections -ffunction-sections -std=c++11 -D__STRICT_ANSI__ -fno-rtti  -c ../../vendor/node/src/node_crypto.cc -o obj/vendor/node/src/node.node_crypto.o
In file included from ../../vendor/node/src/node_crypto.cc:50:
/usr/bin/../lib/gcc/x86_64-redhat-linux/7/../../../../include/c++/7/math.h:65:12: error: target of using declaration conflicts with declaration already in scope
using std::isinf;
           ^
/usr/bin/../lib/gcc/x86_64-redhat-linux/7/../../../../include/c++/7/cmath:599:3: note: target of using declaration
  isinf(double __x)
  ^
/home/makerpm/rpmbuild/BUILD/electron/vendor/debian_jessie_amd64-sysroot/usr/include/x86_64-linux-gnu/bits/mathcalls.h:201:19: note: conflicting declaration
__MATHDECL_1 (int,isinf,, (_Mdouble_ __value)) __attribute__ ((__const__));
                  ^
In file included from ../../vendor/node/src/node_crypto.cc:50:
/usr/bin/../lib/gcc/x86_64-redhat-linux/7/../../../../include/c++/7/math.h:66:12: error: target of using declaration conflicts with declaration already in scope
using std::isnan;
           ^
/usr/bin/../lib/gcc/x86_64-redhat-linux/7/../../../../include/c++/7/cmath:626:3: note: target of using declaration
  isnan(double __x)
  ^
/home/makerpm/rpmbuild/BUILD/electron/vendor/debian_jessie_amd64-sysroot/usr/include/x86_64-linux-gnu/bits/mathcalls.h:234:19: note: conflicting declaration
__MATHDECL_1 (int,isnan,, (_Mdouble_ __value)) __attribute__ ((__const__));
                  ^
2 errors generated.
ninja: build stopped: subcommand failed.

Traceback (most recent call last):
  File "./script/create-dist.py", line 314, in <module>
    sys.exit(main())
  File "./script/create-dist.py", line 85, in main
    force_build()
  File "./script/create-dist.py", line 114, in force_build
    execute([sys.executable, build, '-c', 'Release'])
  File "/home/makerpm/rpmbuild/BUILD/electron/script/lib/util.py", line 174, in execute
    raise e
subprocess.CalledProcessError: Command '['/usr/bin/python', '/home/makerpm/rpmbuild/BUILD/electron/script/build.py', '-c', 'Release']' returned non-zero exit status 1
```

It seems it has some conflicts with the standard Math lib?

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
