### ISSUE TITLE
ZeroMQ build with Electron throws error

### ISSUE THREAD

**Issue by sona15** [electron/electron#11280]
I have installed zeromq using > npm install zeromq
Then I ran this manually >
npm rebuild zeromq --runtime=electron --target=1.7.6
When I start my electron app with command> npm run electron:serve
I get the follwoing error:

App threw an error during load
Error: The system cannot find message text for message number 0x%1 in the messag
e file for %2.
\?\C:\Users\17-11-17\dist\node_modules\zeromq\build\Release\zmq.node
at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)

at Object.Module._extensions..node (module.js:598:18)
at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
at Module.load (module.js:488:32)
at tryModuleLoad (module.js:447:12)
at Function.Module._load (module.js:439:3)
at Module.require (module.js:498:17)
at require (internal/module.js:20:19)
at Object.<anonymous> (C:\Users\17-11-17\dist\node_modules\zeromq\lib\index.js:6:11)
at Object.<anonymous> (C:\Users\17-11-17\dist\node_modules\zeromq\lib\index.js:848:3)

**Comment by sofianguy** [comment]
@sona15 
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by kadharmfn** [comment]
@sona15 .. I am facing the same issue. Have you found the solution?

**Comment by kadharmfn** [comment]
@sona15 sorry, ignore. npm rebuild zeromq --runtime=electron --target=1.7.12 worked for me
