### ISSUE TITLE
Symbol lookup error : SHA512

### ISSUE THREAD

**Issue by MaggieNgWu** [electron/electron#11497]
### Environment
OS: Ubuntu 14.04 TLS
Electron: 1.7.10
Electron-rebuild: 1.6.0
node: v8.9.2
npm: 5.6.0

### Error
I installed module [bigchaindb js driver](https://github.com/bigchaindb/js-bigchaindb-driver), and try to use that module in electron. Below is my code:

```
const driver = require('bigchaindb-driver')
const API_PATH = 'http://localhost:9984/api/v1/';
var zila={
		"publicKey": "QhLyduKhqNSaR8e27BzNAsU8hBZzrDEi82t2t34HGfx",
  		"privateKey": "DuvuQjGH6AdKiKyFh6rgx1wBENkuHEUnLxmCfjysPMk5" 
	}
var conn = new driver.Connection(API_PATH);
const assetdata = {
	'test':{
		'serial_number':'dds=26373',
		'manufacturer':'car Tech Inc.'
	},
	'BBset':{
		'manufacturer':'car Tech Inc.'
	}
}

const metadata = { 'planet':'earth'}

try {
	//Asset creation
	const txCreateZilaSimple = driver.Transaction.makeCreateTransaction(
		assetdata,
		metadata,
		[driver.Transaction.makeOutput(
			driver.Transaction.makeEd25519Condition(zila.publicKey))],
		zila.publicKey
	)
	var txCreateZilaSimpleSigned = driver.Transaction.signTransaction(txCreateZilaSimple, zila.privateKey)
	conn.postTransaction(txCreateZilaSimpleSigned)
	.then(() => conn.pollStatusAndFetchTransaction(txCreateZilaSimpleSigned.id))
	.then(retrievedTx => console.log('Transaction', retrievedTx.id, 'successfully posted.'))

} catch (err) {
	console.log(err);
}

```
I get an error below: **Undefined symbol SHA512**
But I put this code in the test folder and run "node XXX.js", it can run smoothly.

```
$ npm start

> DataTradingDemo@1.3.0 start /home/maggie/Workspace/FirstElectron
> electron .

/home/maggie/Workspace/FirstElectron/node_modules/electron/dist/electron .: symbol lookup error: /home/maggie/Workspace/FirstElectron/node_modules/ed25519/build/Release/ed25519.node: undefined symbol: SHA512
npm ERR! file sh
npm ERR! code ELIFECYCLE
npm ERR! errno ENOENT
npm ERR! syscall spawn
npm ERR! DataTradingDemo@1.3.0 start: `electron .`
npm ERR! spawn ENOENT
npm ERR! 
npm ERR! Failed at the DataTradingDemo@1.3.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/maggie/.npm/_logs/2017-12-21T09_21_32_798Z-debug.log
```
Anyone has idea?

**Comment by MaggieNgWu** [comment]
The content in /home/maggie/.npm/_logs/2017-12-21T09_21_32_798Z-debug.log is:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@5.6.0
3 info using node@v8.9.2
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle DataTradingDemo@1.3.0~prestart: DataTradingDemo@1.3.0
6 info lifecycle DataTradingDemo@1.3.0~start: DataTradingDemo@1.3.0
7 verbose lifecycle DataTradingDemo@1.3.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle DataTradingDemo@1.3.0~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/maggie/Workspace/FirstElectron/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/local/go/bin
9 verbose lifecycle DataTradingDemo@1.3.0~start: CWD: /home/maggie/Workspace/FirstElectron
10 silly lifecycle DataTradingDemo@1.3.0~start: Args: [ '-c', 'electron .' ]
11 info lifecycle DataTradingDemo@1.3.0~start: Failed to exec start script
12 verbose stack Error: DataTradingDemo@1.3.0 start: `electron .`
12 verbose stack spawn ENOENT
12 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
12 verbose stack     at emitTwo (events.js:126:13)
12 verbose stack     at ChildProcess.emit (events.js:214:7)
12 verbose stack     at maybeClose (internal/child_process.js:925:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
13 verbose pkgid DataTradingDemo@1.3.0
14 verbose cwd /home/maggie/Workspace/FirstElectron
15 verbose Linux 3.13.0-123-generic
16 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
17 verbose node v8.9.2
18 verbose npm  v5.6.0
19 error file sh
20 error code ELIFECYCLE
21 error errno ENOENT
22 error syscall spawn
23 error DataTradingDemo@1.3.0 start: `electron .`
23 error spawn ENOENT
24 error Failed at the DataTradingDemo@1.3.0 start script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 1, true ]


```

**Comment by MarshallOfSound** [comment]
This is not an issue with Electron, it'll be an issue with that native module trying to link to something that doesn't exist.  I'd recommend following up with that module which development dependencies are required on linux

**Comment by MaggieNgWu** [comment]
Yes, I upgrade that module, and problem solved.
