### ISSUE TITLE
MACOS: Unable to start electron using npm start

### ISSUE THREAD

**Issue by muhammadInam** [electron/electron#11513]
* Electron version: 1.8.2 beta-2
* Operating system: MACOSX

### Expected behavior

app should run on npm start

### Actual behavior

Error occurs after running npm start

### How to reproduce
I simply cloned the repo and then from terminal, navigated to the directory. After running npm install, I tried npm start and following error came:

> electron@1.8.2-beta.2 start /Users/inam/GitHub/electron
> python ./script/start.py

>Traceback (most recent call last):
>  File "./script/start.py", line 40, in <module>
    sys.exit(main())
  File "./script/start.py", line 34, in main
    subprocess.check_call([electron] + sys.argv[1:])
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 535, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@1.8.2-beta.2 start: `python ./script/start.py`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron@1.8.2-beta.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

Kindly let me know if its an issue at my end.

**Comment by MarshallOfSound** [comment]
You don't need to clone the `electron` repo to use Electron, building Electron is quite complicated.  All you should need is the `electron` npm module.

```bash
npm i electron
```

It will download prebuilt binaries for your system for you 👍
