### ISSUE TITLE
Please help me with packaging Mac 

### ISSUE THREAD

**Issue by pikvik** [electron/electron#11533]
Hi,
This is in reference to the electron app I am working on.
in the development alls running fine but when I package it with yarn its giving error, tired googling and going through endless ways but couldn't resolve. It would be of immense appreciation if you can please help me .

below is the terminal display :

Apogees-MacBook-Pro:Asystguard-Mac apogee$ sudo yarn package-mac
Password:
yarn run v1.3.2
$ npm run build && build -m

asystguard@2.1.0 build /Users/apogee/Desktop/Asystguard-Mac
concurrently "npm run build-main" "npm run build-renderer"
[0]
[0] > asystguard@2.1.0 build-main /Users/apogee/Desktop/Asystguard-Mac
[0] > cross-env NODE_ENV=production node --trace-warnings -r babel-register ./node_modules/webpac
k/bin/webpack --config webpack.config.main.prod.js --colors
[0]
[1]
[1] > asystguard@2.1.0 build-renderer /Users/apogee/Desktop/Asystguard-Mac
[1] > cross-env NODE_ENV=production node --trace-warnings -r babel-register ./node_modules/webpac
k/bin/webpack --config webpack.config.renderer.prod.js --colors
[1]
[1] (node:23955) DeprecationWarning: Chunk.modules is deprecated. Use Chunk.getNumberOfModules/ma
pModules/forEachModule/containsModule instead.
[1] at /Users/apogee/Desktop/Asystguard-Mac/node_modules/extract-text-webpack-plugin/index.js
:271:25
[1] at /Users/apogee/Desktop/Asystguard-Mac/node_modules/async/dist/async.js:3096:16
[1] at eachOfArrayLike (/Users/apogee/Desktop/Asystguard-Mac/node_modules/async/dist/async.js
:1055:9)
[1] at eachOf (/Users/apogee/Desktop/Asystguard-Mac/node_modules/async/dist/async.js:1103:5)
[1] at Object.eachLimit (/Users/apogee/Desktop/Asystguard-Mac/node_modules/async/dist/async.j
s:3158:5)
[1] at ExtractTextPlugin. (/Users/apogee/Desktop/Asystguard-Mac/node_modules/extra
ct-text-webpack-plugin/index.js:268:10)
[1] at Compilation.applyPluginsAsyncSeries (/Users/apogee/Desktop/Asystguard-Mac/node_modules
/tapable/lib/Tapable.js:206:13)
[1] at Compilation.seal (/Users/apogee/Desktop/Asystguard-Mac/node_modules/webpack/lib/Compil
ation.js:605:8)
[1] at applyPluginsParallel.err (/Users/apogee/Desktop/Asystguard-Mac/node_modules/webpack/li
b/Compiler.js:504:17)
[1] at /Users/apogee/Desktop/Asystguard-Mac/node_modules/tapable/lib/Tapable.js:289:11
[1] at _addModuleChain (/Users/apogee/Desktop/Asystguard-Mac/node_modules/webpack/lib/Compila
tion.js:507:11)
[1] at processModuleDependencies.err (/Users/apogee/Desktop/Asystguard-Mac/node_modules/webpa
ck/lib/Compilation.js:477:14)
[1] at _combinedTickCallback (internal/process/next_tick.js:131:7)
[1] at process._tickCallback (internal/process/next_tick.js:180:9)
[0] /Users/apogee/Desktop/Asystguard-Mac/node_modules/webpack-sources/node_modules/source-map/lib
/source-map-generator.js:276
[1] throw new Error(
[1] ^
[1]
[1] Error: original.line and original.column are not numbers -- you probably meant to omit the or
iginal mapping entirely and only map the generated position. If so, pass null for the original ma
pping instead of an object with empty or null values.
[1] at SourceMapGenerator_validateMapping [as _validateMapping] (/Users/apogee/Desktop/Asystg
uard-Mac/node_modules/webpack-sources/node_modules/source-map/lib/source-map-generator.js:276:15)
[1] at SourceMapGenerator_addMapping [as addMapping] (/Users/apogee/Desktop/Asystguard-Mac/no
de_modules/webpack-sources/node_modules/source-map/lib/source-map-generator.js:110:12)
[1] at /Users/apogee/Desktop/Asystguard-Mac/node_modules/webpack-sources/node_modules/source-
map/lib/source-map-generator.js:72:17
[1] at Array.forEach ()
[1] at BasicSourceMapConsumer.SourceMapConsumer_eachMapping [as eachMapping] (/Users/apogee/D
esktop/Asystguard-Mac/node_modules/webpack-sources/node_modules/source-map/lib/source-map-consume
r.js:157:14)
[1] at Function.SourceMapGenerator_fromSourceMap [as fromSourceMap] (/Users/apogee/Desktop/As
ystguard-Mac/node_modules/webpack-sources/node_modules/source-map/lib/source-map-generator.js:48:
24)
[1] at SourceMapSource.node (/Users/apogee/Desktop/Asystguard-Mac/node_modules/webpack-source
s/lib/SourceMapSource.js:32:35)
[1] at SourceMapSource.proto.sourceAndMap (/Users/apogee/Desktop/Asystguard-Mac/node_modules/
webpack-sources/lib/SourceAndMapMixin.js:30:18)
[1] at getTaskForFile (/Users/apogee/Desktop/Asystguard-Mac/node_modules/webpack/lib/SourceMa
pDevToolPlugin.js:33:30)
[1] at chunk.files.forEach.file (/Users/apogee/Desktop/Asystguard-Mac/node_modules/webpack/li
b/SourceMapDevToolPlugin.js:91:21)
[1] at Array.forEach ()
[1] at /Users/apogee/Desktop/Asystguard-Mac/node_modules/webpack/lib/SourceMapDevToolPlugin.j
s:89:18
[1] at Array.forEach ()
[1] at Compilation. (/Users/apogee/Desktop/Asystguard-Mac/node_modules/webpack/lib
/SourceMapDevToolPlugin.js:88:12)
[1] at Compilation.applyPlugins1 (/Users/apogee/Desktop/Asystguard-Mac/node_modules/tapable/l
ib/Tapable.js:75:14)
[1] at self.applyPluginsAsync.err (/Users/apogee/Desktop/Asystguard-Mac/node_modules/webpack/
lib/Compilation.js:670:11)
[1] at next (/Users/apogee/Desktop/Asystguard-Mac/node_modules/tapable/lib/Tapable.js:202:11)
[1] at Compilation. (/Users/apogee/Desktop/Asystguard-Mac/node_modules/babili-webp
ack-plugin/lib/index.js:106:11)
[1] at Compilation.applyPluginsAsyncSeries (/Users/apogee/Desktop/Asystguard-Mac/node_modules
/tapable/lib/Tapable.js:206:13)
[1] at self.applyPluginsAsync.err (/Users/apogee/Desktop/Asystguard-Mac/node_modules/webpack/
lib/Compilation.js:666:10)
[1] at next (/Users/apogee/Desktop/Asystguard-Mac/node_modules/tapable/lib/Tapable.js:202:11)
[1] at ExtractTextPlugin. (/Users/apogee/Desktop/Asystguard-Mac/node_modules/extra
ct-text-webpack-plugin/index.js:345:4)
[1] at Compilation.applyPluginsAsyncSeries (/Users/apogee/Desktop/Asystguard-Mac/node_modules
/tapable/lib/Tapable.js:206:13)
[1] at sealPart2 (/Users/apogee/Desktop/Asystguard-Mac/node_modules/webpack/lib/Compilation.j
s:662:9)
[1] at next (/Users/apogee/Desktop/Asystguard-Mac/node_modules/tapable/lib/Tapable.js:202:11)
[1] at ExtractTextPlugin. (/Users/apogee/Desktop/Asystguard-Mac/node_modules/extra
ct-text-webpack-plugin/index.js:317:5)
[1] at /Users/apogee/Desktop/Asystguard-Mac/node_modules/async/dist/async.js:473:16
[1] at iteratorCallback (/Users/apogee/Desktop/Asystguard-Mac/node_modules/async/dist/async.j
s:1050:13)
[1] at /Users/apogee/Desktop/Asystguard-Mac/node_modules/async/dist/async.js:958:16
[1] at /Users/apogee/Desktop/Asystguard-Mac/node_modules/extract-text-webpack-plugin/index.js
:301:6
[1] npm ERR! code ELIFECYCLE
npm ERR! errno 1
[1] npm ERR! asystguard@2.1.0 build-renderer: cross-env NODE_ENV=production node --trace-warning s -r babel-register ./node_modules/webpack/bin/webpack --config webpack.config.renderer.prod.js - -colors
[1] npm ERR! Exit status 1
[1] npm ERR!
npm ERR! Failed at the asystguard@2.1.0 build-renderer script.
[1] npm ERR! This is probably not a problem with npm. There is likely additional logging output a
bove.
[1]
[1] npm ERR! A complete log of this run can be found in:
[1] npm ERR! /Users/apogee/.npm/_logs/2017-12-27T12_17_19_076Z-debug.log
[1] npm run build-renderer exited with code 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! asystguard@2.1.0 build: concurrently "npm run build-main" "npm run build-renderer"
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the asystguard@2.1.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above
.

npm ERR! A complete log of this run can be found in:
npm ERR! /Users/apogee/.npm/_logs/2017-12-27T12_17_19_315Z-debug.log

COMPLETE LOG:

0 info it worked if it ends with ok
1 verbose cli [ '/Users/apogee/.nvm/versions/node/v9.2.0/bin/node',
1 verbose cli '/Users/apogee/.nvm/versions/node/v9.2.0/bin/npm',
1 verbose cli 'run',
1 verbose cli 'build-renderer' ]
2 info using npm@5.6.0
3 info using node@v9.2.0
4 verbose run-script [ 'prebuild-renderer', 'build-renderer', 'postbuild-renderer' ]
5 info lifecycle asystguard@2.1.0prebuild-renderer: asystguard@2.1.0
6 info lifecycle asystguard@2.1.0build-renderer: asystguard@2.1.0
7 verbose lifecycle asystguard@2.1.0build-renderer: unsafe-perm in lifecycle true
8 verbose lifecycle asystguard@2.1.0build-renderer: PATH: /Users/apogee/.nvm/versions/node/v9.2.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/apogee/Desktop/Asystguard-Mac/node_modules/.bin:/Users/apogee/.nvm/versions/node/v9.2.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/apogee/Desktop/Asystguard-Mac/node_modules/.bin:/Users/apogee/Desktop/Asystguard-Mac/node_modules/.bin:/usr/local/share/.config/yarn/link/node_modules/.bin:/Users/apogee/Desktop/Asystguard-Mac/node_modules/.bin:/usr/local/share/.config/yarn/link/node_modules/.bin:/Users/apogee/.nvm/versions/node/v9.2.0/lib/node_modules/npm/bin/node-gyp-bin:/Users/apogee/.nvm/versions/node/v9.2.0/bin/node_modules/npm/bin/node-gyp-bin:/Users/apogee/.cargo/bin:/usr/local/openssl/bin:/Users/apogee/.nvm/versions/node/v9.2.0/bin:/usr/local/bin:/Users/apogee/.local/bin:/usr/local/opt/qt/bin:/usr/local/autoconf/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/sbin:/usr/local/share/dotnet:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Users/apogee/.cargo/bin:/usr/local/openssl/bin:/Users/apogee/.local/bin:/usr/local/opt/qt/bin:/usr/local/autoconf/bin
9 verbose lifecycle asystguard@2.1.0build-renderer: CWD: /Users/apogee/Desktop/Asystguard-Mac
10 silly lifecycle asystguard@2.1.0build-renderer: Args: [ '-c',
10 silly lifecycle 'cross-env NODE_ENV=production node --trace-warnings -r babel-register ./node_modules/webpack/bin/webpack --config webpack.config.renderer.prod.js --colors' ]
11 silly lifecycle asystguard@2.1.0build-renderer: Returned: code: 1 signal: null
12 info lifecycle asystguard@2.1.0build-renderer: Failed to exec build-renderer script
13 verbose stack Error: asystguard@2.1.0 build-renderer: cross-env NODE_ENV=production node --trace-warnings -r babel-register ./node_modules/webpack/bin/webpack --config webpack.config.renderer.prod.js --colors
13 verbose stack Exit status 1
13 verbose stack at EventEmitter. (/Users/apogee/.nvm/versions/node/v9.2.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:285:16)
13 verbose stack at EventEmitter.emit (events.js:159:13)
13 verbose stack at ChildProcess. (/Users/apogee/.nvm/versions/node/v9.2.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack at ChildProcess.emit (events.js:159:13)
13 verbose stack at maybeClose (internal/child_process.js:943:16)
13 verbose stack at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
14 verbose pkgid asystguard@2.1.0
15 verbose cwd /Users/apogee/Desktop/Asystguard-Mac
16 verbose Darwin 16.7.0
17 verbose argv "/Users/apogee/.nvm/versions/node/v9.2.0/bin/node" "/Users/apogee/.nvm/versions/node/v9.2.0/bin/npm" "run" "build-renderer"
18 verbose node v9.2.0
19 verbose npm v5.6.0
20 error code ELIFECYCLE
21 error errno 1
22 error asystguard@2.1.0 build-renderer: cross-env NODE_ENV=production node --trace-warnings -r babel-register ./node_modules/webpack/bin/webpack --config webpack.config.renderer.prod.js --colors
22 error Exit status 1
23 error Failed at the asystguard@2.1.0 build-renderer script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

Thanks & Regards,

Vikas Kr Pandey
+918680986581

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
