### ISSUE TITLE
[BUG] Electron 1.8.2-beta.3 crash with browser console

### ISSUE THREAD

**Issue by devildant** [electron/electron#11548]
hello,

with the version 1.8.2-beta.3 electron crashes directly if you try to enter characters in the console (browser.webContents.openDevTools();)

stack : 
```
14 verbose stack Error: APP@2.2.2 start: `electron main`
14 verbose stack Exit status 3221225477
14 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:283:16)
14 verbose stack     at emitTwo (events.js:125:13)
14 verbose stack     at EventEmitter.emit (events.js:213:7)
14 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:125:13)
14 verbose stack     at ChildProcess.emit (events.js:213:7)
14 verbose stack     at maybeClose (internal/child_process.js:897:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
15 verbose pkgid APP@2.2.2
16 verbose cwd D:\dev\electron\APP
17 verbose Windows_NT 10.0.16299
18 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "start"
19 verbose node v8.1.3
20 verbose npm  v5.0.3
21 error code ELIFECYCLE
22 error errno 3221225477
23 error APP@2.2.2 start: `electron main`
23 error Exit status 3221225477
24 error Failed at the APP@2.2.2 start script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 3221225477, true ]
```

platform : windows 10
note : no problem with version 1.8.2-beta.2

**Comment by devildant** [comment]
sorry for duplicate 
[](https://github.com/electron/electron/issues/11375)

**Comment by MarshallOfSound** [comment]
Closing as duplicate #11375
