### ISSUE TITLE
Screen API 

### ISSUE THREAD

**Issue by pfrazee** [electron/electron#11635]
* Electron version: 1.
* Operating system: MacOS 10.13.12

### Expected behavior

The screen API should import as expected.

### Actual behavior

An exception is emitted:

```js
Uncaught Exception:
TypeError: Cannot set property 'domain' of null
at EventEmitter.init (events.js:62:15)
at EventEmitter (events.js:27:21)
at Object. (/Applications/Beaker Browser.app/Contents/Resources/electron.asar/browser/api/screen.js:6:14)
at Object. (/Applications/Beaker Browser.app/Contents/Resources/electron.asar/browser/api/screen.js:10:3)
at Module._compile (module.js:569:30)
at Object.Module._extensions..js (module.js:580:10)
at Module.load (module.js:503:32)
at tryModuleLoad (module.js:466:12)
at Function.Module._load (module.js:458:3)
at Module.require (module.js:513:17)
at require (internal/module.js:11:18)
at Object.get [as screen] (/Applications/Beaker Browser.app/Contents/Resources/electron.asar/browser/api/exports/electron.js:11:16)
at getScreenAPI (/Applications/Beaker Browser.app/Contents/Resources/app.asar/background-process.build.js:1667:29)
at defaultState (/Applications/Beaker Browser.app/Contents/Resources/app.asar/background-process.build.js:1572:18)
at restoreState (/Applications/Beaker Browser.app/Contents/Resources/app.asar/background-process.build.js:1563:28)
at createShellWindow (/Applications/Beaker Browser.app/Contents/Resources/app.asar/background-process.build.js:1471:60)
at ensureOneWindowExists (/Applications/Beaker Browser.app/Contents/Resources/app.asar/background-process.build.js:1525:5)
at App.electron.app.on (/Applications/Beaker Browser.app/Contents/Resources/app.asar/background-process.build.js:5809:35)
at emitTwo (events.js:125:13)
at App.emit (events.js:213:7)
```

### How to reproduce

It happens very sporadically for my users. I have not been able to reproduce, but it's been reported at least twice.

**Comment by pfrazee** [comment]
Turns out this was happening when the macOS `'activate'` event fired. The screen API is only available after `'ready'` and so what's probably happening is, `'activate'` is getting fired before `'ready'`. I'm adding guards in my application. We'll see if that solves it.

**Comment by akashnimare** [comment]
@codebytere this should be closed.
