### ISSUE TITLE
Exception at Post Install in Linux

### ISSUE THREAD

**Issue by salman-pathan** [electron/electron#11852]
* Electron version: 1.8.2
* Operating system: Ubuntu 17.10 (64)

### Expected behavior

Electron should install as dependency

### Actual behavior

Post Installation Error

### How to reproduce

I ran the command i.e. npm install electron --save, to save electron as my project dependency, but it ran into exception.

###Error

Downloading electron-v1.8.2-linux-x64.zip
Error: read ECONNRESET
/home/salman/Documents/Practice/Viper/node_modules/electron/install.js:47
  throw err
  ^

Error: read ECONNRESET
    at _errnoException (util.js:1022:11)
    at TLSWrap.onread (net.js:615:25)
npm WARN viper@0.0.1 No description
npm WARN viper@0.0.1 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@1.8.2 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron@1.8.2 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/salman/.npm/_logs/2018-02-07T08_41_56_920Z-debug.log

[2018-02-07T08_41_56_920Z-debug.log](https://github.com/electron/electron/files/1702402/2018-02-07T08_41_56_920Z-debug.log)

**Comment by jeffvandyke** [comment]
What npm version are you using? `npm init -y && npm install electron --save` works fine for me on npm 5.6.0

**Comment by codebytere** [comment]
`ECONNRESET` means the other side of the TCP conversation abruptly closed its end of the connection; this is most probably due to one or more application protocol errors. I don't believe this is an issue with Electron; try re-checking your node/npm versions and trying again.
