### ISSUE TITLE
not ok 11 app module app.exit(exitCode) exits gracefully on macos

### ISSUE THREAD

**Issue by ckerr** [electron/electron#12050]
This causes intermittent CI failures, showing up several times a week but is not reliably reproducible.

[Example](https://mac-ci.electronjs.org/blue/organizations/jenkins/Electron%20org%2Felectron/detail/PR-12037/3/pipeline)

```text
not ok 11 app module app.exit(exitCode) exits gracefully on macos
  AssertionError [ERR_ASSERTION]: false == true
      at ChildProcess.exec (/Users/electron/workspace/ctron_org_electron_PR-12037-TWW4HVB7PMGXB75WUNR2QMXJH33XQBHCRTABBUJLBSRYSKBW4FWA/spec/api-app-spec.js:172:11)
      at ChildProcess.exithandler (child_process.js:294:5)
      at emitTwo (events.js:126:13)
      at ChildProcess.emit (events.js:214:7)
      at maybeClose (internal/child_process.js:925:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
```

**Comment by ckerr** [comment]
https://github.com/electron/electron/pull/12122 adds code to print out the callback arguments on failure

**Comment by ckerr** [comment]
Reported by @codebytere:

```text
not ok 11 app module app.exit(exitCode) exits gracefully on macos
  AssertionError [ERR_ASSERTION]: err:
  Error: Command failed: osascript -e 'quit app "Electron"'
  0:19: execution error: Electron got an error: Application isn't running. (-600)

  stdout:
  stderr:
  0:19: execution error: Electron got an error: Application isn't running. (-600)
      at ChildProcess.exec (/Users/electron/workspace/ctron_org_electron_PR-12135-L7Z3XUORCSZLFC5IRGEKKXN45FRRDP7LFWFLEUSOY5JQUN2URWTQ/spec/api-app-spec.js:172:11)
      at ChildProcess.exithandler (child_process.js:291:5)
      at ChildProcess.emit (events.js:159:13)
      at maybeClose (internal/child_process.js:943:16)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:220:5)
```
