### ISSUE TITLE
update.py on MacOSX fails 

### ISSUE THREAD

**Issue by slimandslam** [electron/electron#12070]
* Electron version: v1.8.2
* Operating system: MacOSX 10.12.6
* Python 2.7.10
* npm 5.6
* nodejs 9.6.1
* Xcode 9.2
* pyobjc installed

### Expected behavior

The command "./script/bootstrap.py -v" should succeed

### Actual behavior

Fails as indicated below

### How to reproduce

```
$ git clone https://github.com/electron/electron
$ cd electron
$ ./script/bootstrap.py -v
...
... [edited for brevity and clarity]
...
...
added 1099 packages in 46.763s
npm verb exit [ 0, true ]
npm info ok
git submodule status vendor/libchromiumcontent
 8c526e52d02a574b6d3cbaf2014cdccb9a0e3185 vendor/libchromiumcontent (v51.0.2704.61-745-g8c526e5)

Downloading libchromiumcontent.tar.bz2...
https://s3.amazonaws.com/github-janky-artifacts/libchromiumcontent/osx/x64/8c526e52d02a574b6d3cbaf2014cdccb9a0e3185/libchromiumcontent.tar.bz2
...................................................................................................................................................................................
Extracting...
Downloading libchromiumcontent-static.tar.bz2...
https://s3.amazonaws.com/github-janky-artifacts/libchromiumcontent/osx/x64/8c526e52d02a574b6d3cbaf2014cdccb9a0e3185/libchromiumcontent-static.tar.bz2
.............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
Extracting...
/usr/bin/python /Users/slimandslam/Desktop/MyProject/electron/script/update.py
Traceback (most recent call last):
  File "script/update-external-binaries.py", line 66, in <module>
    sys.exit(main())
  File "script/update-external-binaries.py", line 28, in main
    download_and_unzip('Mantle')
  File "script/update-external-binaries.py", line 50, in download_and_unzip
    zip_path = download_framework(framework)
  File "script/update-external-binaries.py", line 61, in download_framework
    download('Download ' + framework, url, path)
  File "/Users/slimandslam/Desktop/MyProject/electron/script/lib/util.py", line 85, in download
    web_file = urllib2.urlopen(url)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 469, in error
    result = self._call_chain(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 656, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 431, in open
    response = self._open(req, data)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 449, in _open
    '_open', req)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1240, in https_open
    context=self._context)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1197, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:590)>
Traceback (most recent call last):
  File "/Users/slimandslam/Desktop/MyProject/electron/script/update.py", line 100, in <module>
    sys.exit(main())
  File "/Users/slimandslam/Desktop/MyProject/electron/script/update.py", line 23, in main
    update_external_binaries()
  File "/Users/slimandslam/Desktop/MyProject/electron/script/update.py", line 38, in update_external_binaries
    subprocess.check_call([sys.executable, uf])
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python', 'script/update-external-binaries.py']' returned non-zero exit status 1
None
Traceback (most recent call last):
  File "./script/bootstrap.py", line 282, in <module>
    sys.exit(main())
  File "./script/bootstrap.py", line 68, in main
    run_update(defines, args.msvs)
  File "./script/bootstrap.py", line 259, in run_update
    execute_stdout(args)
  File "/Users/slimandslam/Desktop/MyProject/electron/script/lib/util.py", line 184, in execute_stdout
    raise e
subprocess.CalledProcessError: Command '['/usr/bin/python', '/Users/slimandslam/Desktop/MyProject/electron/script/update.py']' returned non-zero exit status 1
$
```

**Comment by MarshallOfSound** [comment]
> TLSV1_ALERT_PROTOCOL_VERSION

You need to update your local version of python2 in order to support newer TLS versions that Github now requires 👍

**Comment by WangMl** [comment]
Why python 2.7.14, but also burst this wrong？

**Comment by WangMl** [comment]
@slimandslam Hi, is this problem solved? How to solve?

**Comment by slimandslam** [comment]
I did this......
$ openssl version
to see the version. If it's not "OpenSSL 1.0.2n  7 Dec 2017"
then
$ brew install openssl
and then
$ brew link --force openssl
and then
$ brew install python

**Comment by MartinMa** [comment]
I followed the [electron build instructions](https://electronjs.org/docs/development/build-instructions-gn) and get this error on Windows 10.

The [linked depot tools setup guide](http://commondatastorage.googleapis.com/chrome-infra-docs/flat/depot_tools/docs/html/depot_tools_tutorial.html#_setting_up) states very clearly to add `depot_tools` to the start of PATH, so that the built-in Python version 2.7.6 is used.

@MarshallOfSound Do you have a hint what I can do? Should I, in departure from the instructions, remove `depot_tools` from PATH, so that the script uses my locally installed `Python 2.7.13`?

I was running the `gclient` command which took almost two hours to run. At the very end i got this error. This is my trace. Do I need to run gclient again and wait another two hours to see if it works or can I somehow continue where the error occured?
```
Hook ''C:\depot_tools\win_tools-2_7_6_bin\python\bin\python.exe' src/electron/script/apply-patches --project-root=. --commit' took 51.06 secs
Running hooks:   3% ( 2/64) electron_external_binaries
________ running 'C:\depot_tools\win_tools-2_7_6_bin\python\bin\python.exe src/electron/script/update-external-binaries.py' in 'C:\Users\mmaedler\Projects\electron-gn'
Downloading http://github.com/electron/electron-frameworks/releases/download/v1.4.0/directxsdk-x64.zip to c:\users\mmaedler\appdata\local\temp\electron-1znoxd\directxsdk-x64.zip
Traceback (most recent call last):
  File "src/electron/script/update-external-binaries.py", line 73, in <module>
  File "src/electron/script/update-external-binaries.py", line 32, in main
  File "src/electron/script/update-external-binaries.py", line 57, in download_and_unzip
  File "src/electron/script/update-external-binaries.py", line 68, in download_framework
  File "C:\Users\mmaedler\Projects\electron-gn\src\electron\script\lib\util.py", line 66, in download
    web_file = urllib2.urlopen(url)
  File "C:\depot_tools\win_tools-2_7_6_bin\python\bin\lib\urllib2.py", line 127, in urlopen
    return _opener.open(url, data, timeout)
  File "C:\depot_tools\win_tools-2_7_6_bin\python\bin\lib\urllib2.py", line 410, in open
    response = meth(req, response)
  File "C:\depot_tools\win_tools-2_7_6_bin\python\bin\lib\urllib2.py", line 523, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\depot_tools\win_tools-2_7_6_bin\python\bin\lib\urllib2.py", line 442, in error
    result = self._call_chain(*args)
  File "C:\depot_tools\win_tools-2_7_6_bin\python\bin\lib\urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "C:\depot_tools\win_tools-2_7_6_bin\python\bin\lib\urllib2.py", line 629, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "C:\depot_tools\win_tools-2_7_6_bin\python\bin\lib\urllib2.py", line 404, in open
    response = self._open(req, data)
  File "C:\depot_tools\win_tools-2_7_6_bin\python\bin\lib\urllib2.py", line 422, in _open
    '_open', req)
  File "C:\depot_tools\win_tools-2_7_6_bin\python\bin\lib\urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "C:\depot_tools\win_tools-2_7_6_bin\python\bin\lib\urllib2.py", line 1222, in https_open
    return self.do_open(httplib.HTTPSConnection, req)
  File "C:\depot_tools\win_tools-2_7_6_bin\python\bin\lib\urllib2.py", line 1184, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [Errno 1] _ssl.c:507: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version>
Error: Command 'C:\\depot_tools\\win_tools-2_7_6_bin\\python\\bin\\python.exe src/electron/script/update-external-binaries.py' returned non-zero exit status 1 in C:\Users\mmaedler\Projects\electron-gn
```

**Comment by nornagon** [comment]
@MartinMa unfortunately this is an issue in depot_tools, see https://crbug.com/868864. The workaround for now is to re-run `electron/script/update-external-binaries.py` with a newer python, then re-run `gclient sync` and it should pick up where it left off.
