### ISSUE TITLE
urlopen error [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version

### ISSUE THREAD

**Issue by WangMl** [electron/electron#12088]
* Electron version: 1.8.2
* Operating system: macOS 10.12
* Python version: 2.7.14
* NodeJS version: 8.2.0
* XCode version: 8.3.3
* pyobjc: installed

### Expected behavior

bootstrap.py success

### Actual behavior

urllib2.URLError
### How to reproduce
1.  ./script/bootstrap.py -v
```
/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python /Users/adminyunshipeicom/electron_182/electron/script/update.py
Traceback (most recent call last):
  File "script/update-external-binaries.py", line 66, in <module>
    sys.exit(main())
  File "script/update-external-binaries.py", line 28, in main
    download_and_unzip('Mantle')
  File "script/update-external-binaries.py", line 50, in download_and_unzip
    zip_path = download_framework(framework)
  File "script/update-external-binaries.py", line 61, in download_framework
    download('Download ' + framework, url, path)
  File "/Users/adminyunshipeicom/electron_182/electron/script/lib/util.py", line 85, in download
    web_file = urllib2.urlopen(url)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 467, in error
    result = self._call_chain(*args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 654, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 429, in open
    response = self._open(req, data)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 447, in _open
    '_open', req)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1241, in https_open
    context=self._context)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/urllib2.py", line 1198, in do_open
    raise URLError(err)
urllib2.URLError: <urlopen error [SSL: TLSV1_ALERT_PROTOCOL_VERSION] tlsv1 alert protocol version (_ssl.c:661)>
Traceback (most recent call last):
  File "/Users/adminyunshipeicom/electron_182/electron/script/update.py", line 100, in <module>
    sys.exit(main())
  File "/Users/adminyunshipeicom/electron_182/electron/script/update.py", line 23, in main
    update_external_binaries()
  File "/Users/adminyunshipeicom/electron_182/electron/script/update.py", line 38, in update_external_binaries
    subprocess.check_call([sys.executable, uf])
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python', 'script/update-external-binaries.py']' returned non-zero exit status 1
None
Traceback (most recent call last):
  File "./script/bootstrap.py", line 282, in <module>
    sys.exit(main())
  File "./script/bootstrap.py", line 68, in main
    run_update(defines, args.msvs)
  File "./script/bootstrap.py", line 259, in run_update
    execute_stdout(args)
  File "/Users/adminyunshipeicom/electron_182/electron/script/lib/util.py", line 184, in execute_stdout
    raise e
subprocess.CalledProcessError: Command '['/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python', '/Users/adminyunshipeicom/electron_182/electron/script/update.py']' returned non-zero exit status 1
```

**Comment by WangMl** [comment]
OpenSSL 0.9.8zh,Is it because openssl version is too low? Urgently needed help！Thanks

**Comment by MarshallOfSound** [comment]
Duplicate #12070

You even commented on that issue, so you knew this was raising a duplicate

For reference I currently have Python 2.7.10 on my machine and it works 👌
