### ISSUE TITLE
Flake: chromium feature navigator.serviceWorker should register for file scheme

### ISSUE THREAD

**Issue by alexeykuzmin** [electron/electron#12173]
E.g. https://mac-ci.electronjs.org/blue/organizations/jenkins/Electron%20org%2Felectron/detail/PR-12170/2/pipeline/8

```
not ok 762 chromium feature navigator.serviceWorker should register for file scheme
  Error: done() invoked with non-Error: unexpected error : [object Object]
      at w.webContents.on (/Users/electron/workspace/ctron_org_electron_PR-12170-UUKDTUEJU3P2TH5LWQ2KRTQZPTDVV24N72APHKHIKS3GHEUJN56A/spec/chromium-spec.js:142:11)
      at CallbacksRegistry.apply (/Users/electron/workspace/ctron_org_electron_PR-12170-UUKDTUEJU3P2TH5LWQ2KRTQZPTDVV24N72APHKHIKS3GHEUJN56A/out/D/Electron.app/Contents/Resources/electron.asar/common/api/callbacks-registry.js:47:25)
      at EventEmitter.ipcRenderer.on (/Users/electron/workspace/ctron_org_electron_PR-12170-UUKDTUEJU3P2TH5LWQ2KRTQZPTDVV24N72APHKHIKS3GHEUJN56A/out/D/Electron.app/Contents/Resources/electron.asar/renderer/api/remote.js:261:21)
      at emitThree (events.js:136:13)
      at EventEmitter.emit (events.js:217:7)

```

**Comment by ckerr** [comment]
i don't think this was supposed to be closed?

Still happening, but now with the new debug info:

```text
ok 774 chromium feature navigator.language should not be empty
not ok 775 chromium feature navigator.serviceWorker should register for file scheme
  Error: done() invoked with non-Error: Failed to register a ServiceWorker: The script has an unsupported MIME type ('text/plain').
  undefined
      at C:\projects\electron\spec\node_modules\mocha\lib\runnable.js:380:21
      at w.webContents.on (C:\projects\electron\spec\chromium-spec.js:147:11)
      at CallbacksRegistry.apply (C:\projects\electron\out\D\resources\electron.asar\common\api\callbacks-registry.js:47:25)
      at EventEmitter.ipcRenderer.on (C:\projects\electron\out\D\resources\electron.asar\renderer\api\remote.js:261:21)
      at EventEmitter.emit (events.js:127:13)
ok 776 chromium feature navigator.serviceWorker should register for intercepted file scheme
ok 777 chromium feature window.open returns a BrowserWindowProxy object
ok 778 chromium feature window.open accepts "nodeIntegration" as feature
```

**Comment by ckerr** [comment]
This seems to be affecting 1-8-x as well...

**Comment by ckerr** [comment]
Because of course it's in 1-7-x as well.

https://windows-ci.electronjs.org/project/AppVeyor/electron/build/1.0.3677/job/m3fx3fwtd047duyv

https://windows-ci.electronjs.org/project/AppVeyor/electron/build/1.0.3677/job/d80xc7ay1psi05uf
