### ISSUE TITLE
Invalid or unexpected token at createScript

### ISSUE THREAD

**Issue by mrmowji** [electron/electron#12210]
I'm new to Electron and just tried to run its example from [the website](https://electronjs.org/docs/tutorial/first-app). The quick-start repository runs OK. But the other simple walk-through example throws this error:

```
D:\Project\Electron\To-Do>npm start

> to-do@1.0.0 start D:\Project\Electron\To-Do
> electron .


App threw an error during load
D:\Project\Electron\To-Do\main.js:1
(function (exports, require, module, __filename, __dirname, process, global, Buf
fer) { return function (exports, require, module, __filename, __dirname) { ي┐╜ي┐
╜c

                                                                           ^

SyntaxError: Invalid or unexpected token
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:533:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at loadApplicationPackage (D:\Project\Electron\To-Do\node_modules\electron\d
ist\resources\default_app.asar\main.js:287:12)
    at Object.<anonymous> (D:\Project\Electron\To-Do\node_modules\electron\dist\
resources\default_app.asar\main.js:329:5)
    at Object.<anonymous> (D:\Project\Electron\To-Do\node_modules\electron\dist\
resources\default_app.asar\main.js:366:3)
```

`package.json`
```js
{
  "name": "to-do",
  "version": "1.0.0",
  "description": "",
  "main": "main.js",
  "scripts": {
    "start": "electron ."
  },
  "author": "Mojtaba Javan",
  "license": "ISC",
  "devDependencies": {
    "electron": "^1.8.3"
  }
}
```
`main.js`
```js
const {app, BrowserWindow} = require('electron')
  
  function createWindow () {
    // Create the browser window.
    win = new BrowserWindow({width: 800, height: 600})
  
    // and load the index.html of the app.
    win.loadURL(url.format({
      pathname: path.join(__dirname, 'index.html'),
      protocol: 'file:',
      slashes: true
    }))
  }
  
  app.on('ready', createWindow)
```
`index.html`
```html
<!DOCTYPE html>
  <html>
    <head>
      <meta charset="UTF-8">
      <title>Hello World!</title>
    </head>
    <body>
      <h1>Hello World!</h1>
      We are using node <script>document.write(process.versions.node)</script>,
      Chrome <script>document.write(process.versions.chrome)</script>,
      and Electron <script>document.write(process.versions.electron)</script>.
    </body>
  </html>
```

Electron: **1.8.3**
Node.js: **8.2.1**
Chromium: **59.0.3071.115**
OS: **Windows 7 64-bit**

**Comment by garyamorris** [comment]
I have the same issue on my windows machine, but not on Mac OSX.

**Comment by terencechow** [comment]
Problem occurred on my raspberry pi 3

Linux raspberrypi 4.14.52-v7+ armv7l GNU/Linux

electron 2.0.5
electron-download 3.3.0

**Comment by steamknight** [comment]
I had the same issue. For me it was because my main.js file was UTF-16 encoded. Converting it to UTF-8 did the trick.

**Comment by miniak** [comment]
> I had the same issue. For me it was because my main.js file was UTF-16 encoded. Converting it to UTF-8 did the trick.

Does not seem to be an issue with Electron. Closing.
