### ISSUE TITLE
Flaky Test: not ok 762 chromium feature navigator.serviceWorker should register for file scheme

### ISSUE THREAD

**Issue by ckerr** [electron/electron#12214]
Spotted [in the wild](https://mac-ci.electronjs.org/blue/organizations/jenkins/Electron%20org%2Felectron/detail/PR-12213/1/pipeline). 

```text
not ok 762 chromium feature navigator.serviceWorker should register for file scheme
  Error: done() invoked with non-Error: unexpected error : [object Object]
      at w.webContents.on (/Users/electron/workspace/ctron_org_electron_PR-12213-XOAVRAUNHHVF6KGX3G2AVYMO7DC2C7PYSAP3TUZOHSIX6ZNBMYXA/spec/chromium-spec.js:142:11)
      at CallbacksRegistry.apply (/Users/electron/workspace/ctron_org_electron_PR-12213-XOAVRAUNHHVF6KGX3G2AVYMO7DC2C7PYSAP3TUZOHSIX6ZNBMYXA/out/D/Electron.app/Contents/Resources/electron.asar/common/api/callbacks-registry.js:47:25)
      at EventEmitter.ipcRenderer.on (/Users/electron/workspace/ctron_org_electron_PR-12213-XOAVRAUNHHVF6KGX3G2AVYMO7DC2C7PYSAP3TUZOHSIX6ZNBMYXA/out/D/Electron.app/Contents/Resources/electron.asar/renderer/api/remote.js:261:21)
      at emitThree (events.js:136:13)
      at EventEmitter.emit (events.js:217:7)
```

**Comment by deepak1556** [comment]
Merging this to https://github.com/electron/electron/issues/12173
