### ISSUE TITLE
Possible CI flake: node feature contexts setInterval called under Chromium event loop in browser process can be scheduled in time

### ISSUE THREAD

**Issue by ckerr** [electron/electron#12237]
Found in the wild at [here](https://arm64-ci.electronjs.org/blue/organizations/jenkins/Electron%20ARM64%2Felectron/detail/PR-12236/1/pipeline) in a one-liner backport branch that had already passed & merged in master.

```text
not ok 831 node feature contexts setInterval called under Chromium event loop in browser process can be scheduled in time
  Error: done() called multiple times
      at Suite.describe (/var/lib/jenkins/workspace/ron_ARM64_electron_PR-12236-EU723A3C757G34V6S3IPEHQZT3NDQJBEQF7J74MEHBDS44S6XKYA/spec/node-spec.js:185:7)
      at Suite.describe (/var/lib/jenkins/workspace/ron_ARM64_electron_PR-12236-EU723A3C757G34V6S3IPEHQZT3NDQJBEQF7J74MEHBDS44S6XKYA/spec/node-spec.js:184:5)
      at Suite.describe (/var/lib/jenkins/workspace/ron_ARM64_electron_PR-12236-EU723A3C757G34V6S3IPEHQZT3NDQJBEQF7J74MEHBDS44S6XKYA/spec/node-spec.js:136:3)
      at Object.<anonymous> (/var/lib/jenkins/workspace/ron_ARM64_electron_PR-12236-EU723A3C757G34V6S3IPEHQZT3NDQJBEQF7J74MEHBDS44S6XKYA/spec/node-spec.js:10:1)
      at Object.<anonymous> (/var/lib/jenkins/workspace/ron_ARM64_electron_PR-12236-EU723A3C757G34V6S3IPEHQZT3NDQJBEQF7J74MEHBDS44S6XKYA/spec/node-spec.js:400:3)
      at Module._compile (module.js:642:30)
      at Object.Module._extensions..js (module.js:653:10)
```

**Comment by ckerr** [comment]
Seen also in this 1-8-x backport:
https://arm64-ci.electronjs.org/blue/organizations/jenkins/Electron%20ARM64%2Felectron/detail/PR-12261/1/pipeline
