### ISSUE TITLE
Flake: BrowserWindow module "webPreferences" option "sandbox" option releases memory after popup is closed

### ISSUE THREAD

**Issue by ckerr** [electron/electron#12233]
Encountered at https://arm64-ci.electronjs.org/blue/organizations/jenkins/Electron%20ARM64%2Felectron/detail/PR-12229/1/pipeline with a backport PR related to notifications.

```text
not ok 140 BrowserWindow module "webPreferences" option "sandbox" option releases memory after popup is closed
  AssertionError [ERR_ASSERTION]: false == true
      at /var/lib/jenkins/workspace/ron_ARM64_electron_PR-12229-4BDUWQCKQ5YWNAQTA2EY7HKQBOXCTI5ZOHCR57TYUKY3YMO37AWQ/spec/api-browser-window-spec.js:1454:11
      at CallbacksRegistry.apply (/var/lib/jenkins/workspace/ron_ARM64_electron_PR-12229-4BDUWQCKQ5YWNAQTA2EY7HKQBOXCTI5ZOHCR57TYUKY3YMO37AWQ/out/D/resources/electron.asar/common/api/callbacks-registry.js:47:25)
      at EventEmitter.ipcRenderer.on (/var/lib/jenkins/workspace/ron_ARM64_electron_PR-12229-4BDUWQCKQ5YWNAQTA2EY7HKQBOXCTI5ZOHCR57TYUKY3YMO37AWQ/out/D/resources/electron.asar/renderer/api/remote.js:261:21)
      at emitThree (events.js:136:13)
      at EventEmitter.emit (events.js:217:7)
```

**Comment by codebytere** [comment]
No longer an issue.
