### ISSUE TITLE
Error: Cannot get property 'id' on missing remote object

### ISSUE THREAD

**Issue by bpasero** [electron/electron#12316]
* Electron version: 2.0.0-beta.4
* Operating system: macOS 10.13.3

### Expected behavior

A reload of the window works.

### Actual behavior

A reload of the window does not work.

### How to reproduce

* run VSCode exploration ([download](https://az764295.vo.msecnd.net/exploration/6bc3274250cc949c7fb1d654cbb6e59c8ddad697/VSCode-darwin-exploration.zip))
* run "Reload Window" command
* sometimes I see the window stay blank after doing so and checking the console I see:

```
Uncaught (in promise) Error: Cannot get property 'id' on missing remote object 3
Error: Cannot get property 'id' on missing remote object 3
    at throwRPCError (/Applications/Visual Studio Code - Exploration.app/Contents/Resources/electron.asar/browser/rpc-server.js:143:17)
    at EventEmitter.<anonymous> (/Applications/Visual Studio Code - Exploration.app/Contents/Resources/electron.asar/browser/rpc-server.js:384:7)
    at emitThree (events.js:136:13)
    at EventEmitter.emit (events.js:217:7)
    at WebContents.<anonymous> (/Applications/Visual Studio Code - Exploration.app/Contents/Resources/electron.asar/browser/api/web-contents.js:295:13)
    at emitTwo (events.js:126:13)
    at WebContents.emit (events.js:214:7)
    at throwRPCError (/Applications/Visual Studio Code - Exploration.app/Contents/Resources/electron.asar/browser/rpc-server.js:143:17)
    at EventEmitter.<anonymous> (/Applications/Visual Studio Code - Exploration.app/Contents/Resources/electron.asar/browser/rpc-server.js:384:7)
    at emitThree (events.js:136:13)
    at EventEmitter.emit (events.js:217:7)
    at WebContents.<anonymous> (/Applications/Visual Studio Code - Exploration.app/Contents/Resources/electron.asar/browser/api/web-contents.js:295:13)
    at emitTwo (events.js:126:13)
    at WebContents.emit (events.js:214:7)
    at Object.exception (/Applications/Visual Studio Code - Exploration.app/Contents/Resources/electron.asar/renderer/api/remote.js:209:30)
    at metaToValue (/Applications/Visual Studio Code - Exploration.app/Contents/Resources/electron.asar/renderer/api/remote.js:213:28)
    at Object.descriptor.get [as id] (/Applications/Visual Studio Code - Exploration.app/Contents/Resources/electron.asar/renderer/api/remote.js:132:16)
    at file:///Applications/Visual%20Studio%20Code%20-%20Exploration.app/Contents/Resources/app/out/vs/workbench/electron-browser/bootstrap/index.js:11:97
    at new Promise (<anonymous>)
    at file:///Applications/Visual%20Studio%20Code%20-%20Exploration.app/Contents/Resources/app/out/vs/workbench/electron-browser/bootstrap/index.js:10:838
```

**Comment by bpasero** [comment]
Some more details: We seem to be doing a very early call to [`remote.getCurrentWindow().id`](https://github.com/Microsoft/vscode/blob/master/src/vs/workbench/electron-browser/bootstrap/index.js#L31) from our `index.js` which is loaded from our `index.html` that is loaded into the window.

**Comment by bpasero** [comment]
Steps:
* setup VSCode to run out of sources (https://github.com/Microsoft/vscode/wiki/How-to-Contribute#build-and-run)
* start it up
* open some editors
* close some editors
* trigger reload (Cmd+R)

=> window stays blank

![before](https://user-images.githubusercontent.com/900690/37505866-551e3648-28e7-11e8-9fd3-c5bdb9c3ad9d.gif)

**Comment by MarshallOfSound** [comment]
Easy link for later --> https://github.com/electron/electron/compare/3c5ba35d63f4ef2d5f309157e060cf521f7fb6ad...e1b19140e57beaa64160c5e954f96f095fac89c5

**Comment by bpasero** [comment]
@MarshallOfSound repro in Electron or with VS Code? I can easily repro with VS Code and could do some testing if needed...

**Comment by MarshallOfSound** [comment]
@batjko Either, I couldn't repro from a vscode clone :thinking:

**Comment by smotaal** [comment]
Early in the day I left this in #12339:

https://github.com/code-therapy/electron-preload-remote-too-soon

hope it helps

**Comment by MarshallOfSound** [comment]
Thanks for the repro @smotaal was super helpful 👍
