### ISSUE TITLE
Issue with sqlite3 in windows 10

### ISSUE THREAD

**Issue by Saikartik19** [electron/electron#12411]
Error: C:\Program Files\nodejs\node.exe exited with code 1
Error output:
node-pre-gyp ERR! Tried to download(403): https://mapbox-node-binary.s3.amazonaws.com/sqlite3/v4.0.0/electron-v1.8-win32-x64.tar.gz
node-pre-gyp ERR! Pre-built binaries not found for sqlite3@4.0.0 and electron@1.8.4 (electron-v1.8 ABI, unknown) (falling back to source compile with node-gyp)
gyp ERR! build error
gyp ERR! stack Error: msbuild failed with exit code: 1
gyp ERR! stack at ChildProcess.onExit (C:\Users\NexGen43\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:258:23)
gyp ERR! stack at emitTwo (events.js:126:13)
gyp ERR! stack at ChildProcess.emit (events.js:214:7)
gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Users\NexGen43\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "build" "--fallback-to-build" "--module=E:\HelloWorld\electron-quick-start\node_modules\sqlite3\lib\binding\electron-v1.8-win32-x64\node_sqlite3.node" "--module_name=node_sqlite3" "--module_path=E:\HelloWorld\electron-quick-start\node_modules\sqlite3\lib\binding\electron-v1.8-win32-x64" "--napi_version=1" "--node_abi_napi=napi"
gyp ERR! cwd E:\HelloWorld\electron-quick-start\node_modules\sqlite3
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Users\NexGen43\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js build --fallback-to-build --module=E:\HelloWorld\electron-quick-start\node_modules\sqlite3\lib\binding\electron-v1.8-win32-x64\node_sqlite3.node --module_name=node_sqlite3 --module_path=E:\HelloWorld\electron-quick-start\node_modules\sqlite3\lib\binding\electron-v1.8-win32-x64 --napi_version=1 --node_abi_napi=napi' (1)
node-pre-gyp ERR! stack at ChildProcess. (E:\HelloWorld\electron-quick-start\node_modules\sqlite3\node_modules\node-pre-gyp\lib\util\compile.js:83:29)
node-pre-gyp ERR! stack at emitTwo (events.js:126:13)
node-pre-gyp ERR! stack at ChildProcess.emit (events.js:214:7)
node-pre-gyp ERR! stack at maybeClose (internal/child_process.js:925:16)
node-pre-gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
node-pre-gyp ERR! System Windows_NT 10.0.16299
node-pre-gyp ERR! command "C:\Program Files\nodejs\node.exe" "E:\HelloWorld\electron-quick-start\node_modules\sqlite3\node_modules\node-pre-gyp\bin\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd E:\HelloWorld\electron-quick-start\node_modules\sqlite3
node-pre-gyp ERR! node -v v8.9.4
node-pre-gyp ERR! node-pre-gyp -v v0.9.0
node-pre-gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sqlite3@4.0.0 install: node-pre-gyp install --fallback-to-build
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the sqlite3@4.0.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\NexGen43\AppData\Roaming\npm-cache_logs\2018-03-22T15_44_58_069Z-debug.log

at ChildProcess.childProcess.once.code (E:\HelloWorld\electron-quick-start\node_modules\builder-util\src\util.ts:252:14)
at Object.onceWrapper (events.js:317:30)
at emitTwo (events.js:126:13)
at ChildProcess.emit (events.js:214:7)
at maybeClose (internal/child_process.js:925:16)
at Socket.stream.socket.on (internal/child_process.js:346:11)
at emitOne (events.js:116:13)
at Socket.emit (events.js:211:7)
at Pipe._handle.close [as _onclose] (net.js:554:12)
From previous event:
at rebuild (E:\HelloWorld\electron-quick-start\node_modules\electron-builder-lib\out\util\yarn.js:93:22)
at E:\HelloWorld\electron-quick-start\node_modules\electron-builder-lib\src\util\yarn.ts:20:11
at Generator.next ()
at runCallback (timers.js:789:20)
at tryOnImmediate (timers.js:751:5)
at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
at installOrRebuild (E:\HelloWorld\electron-quick-start\node_modules\electron-builder-lib\out\util\yarn.js:31:21)
at E:\HelloWorld\electron-quick-start\node_modules\electron-builder\src\cli\install-app-deps.ts:58:42
at Generator.next ()
From previous event:
at installAppDeps (E:\HelloWorld\electron-quick-start\node_modules\electron-builder\out\cli\install-app-deps.js:51:21)
at then (E:\HelloWorld\electron-quick-start\node_modules\electron-builder\src\cli\cli.ts:48:33)
at runCallback (timers.js:789:20)
at tryOnImmediate (timers.js:751:5)
at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
at Object.args [as handler] (E:\HelloWorld\electron-quick-start\node_modules\electron-builder\src\cli\cli.ts:48:33)
at Object.runCommand (E:\HelloWorld\electron-quick-start\node_modules\yargs\lib\command.js:235:44)
at Object.parseArgs [as _parseArgs] (E:\HelloWorld\electron-quick-start\node_modules\yargs\yargs.js:1014:30)
at Object.get [as argv] (E:\HelloWorld\electron-quick-start\node_modules\yargs\yargs.js:957:21)
at Object. (E:\HelloWorld\electron-quick-start\node_modules\electron-builder\src\cli\cli.ts:42:15)
at Module._compile (module.js:643:30)
at Object.Module._extensions..js (module.js:654:10)
at Module.load (module.js:556:32)
at tryModuleLoad (module.js:499:12)
at Function.Module._load (module.js:491:3)
at Function.Module.runMain (module.js:684:10)
at startup (bootstrap_node.js:187:16)
at bootstrap_node.js:608:3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-quick-start@1.0.0 postinstall: electron-builder install-app-deps

**Comment by sofianguy** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](https://atom-slack.herokuapp.com/).
