### ISSUE TITLE
"unable to checkout"

### ISSUE THREAD

**Issue by mpl1337** [electron/electron#12429]
```
Submodule path 'vendor/pdf_viewer/vendor/grit': checked out '9536fb6429147d27ef1563088341825db0a893cd'
Submodule path 'vendor/requests': checked out 'e4d59bedfd3c7f4f254f4f5d036587bcd8152458'
Unable to checkout '584e6370849aa73025e6206109f25f441cb6cf9f' in submodule path 'vendor/node'
None
Traceback (most recent call last):
  File "script\bootstrap.py", line 282, in <module>
    sys.exit(main())
  File "script\bootstrap.py", line 34, in main
    update_submodules()
  File "script\bootstrap.py", line 136, in update_submodules
    execute_stdout(['git', 'submodule', 'update', '--init', '--recursive'])
  File "C:\Users\Michael\Desktop\Neuer Ordner\electron\script\lib\util.py", line 184, in execute_stdout
    raise e
subprocess.CalledProcessError: Command '['git', 'submodule', 'update', '--init', '--recursive']' returned non-zero exit status 1
```

Win10
python 2.7.12

whats wrong?

**Comment by MarshallOfSound** [comment]
Yeah sometimes git does weird stuff like this, just run `npm run clean` and then bootstrap again

**Comment by codebytere** [comment]
Closing as the above should remedy the issue; please @ me if that doesn't work and we'll continue to help you fix it :)

**Comment by et265831** [comment]
Hi @codebytere, 
I got exactly the same error log as @mpl1337  did. 
I ran the clean script and bootstrap for multiple times. same error.

> Unable to checkout '584e6370849aa73025e6206109f25f441cb6cf9f' in submodule path 'vendor/node'
None
Traceback (most recent call last):
  File "script\bootstrap.py", line 282, in <module>
    sys.exit(main())
  File "script\bootstrap.py", line 34, in main
    update_submodules()
  File "script\bootstrap.py", line 136, in update_submodules
    execute_stdout(['git', 'submodule', 'update', '--init', '--recursive'])
  File "C:\Users\Hotdesk Account\Desktop\electron\script\lib\util.py", line 184, in execute_stdout
    raise e
subprocess.CalledProcessError: Command '['git', 'submodule', 'update', '--init', '--recursive']' returned non-zero exit status 1

Win10
python 2.7
git 2.16.2

Could you please help?
