### ISSUE TITLE
Got NODE_MODULE_VERSION 54. Please try re-compiling or re-installing error when using node-escpos

### ISSUE THREAD

**Issue by mozillo** [electron/electron#12433]
* Electron version: 1.8.4
* Operating system: MacOS Sierra 

### Expected behavior
Using node-escpos
Excepted getting response from printer

### Actual behavior
But got errors from console

```
App threw an error during load
Error: The module '/Users/mot/Repos/leandesktop/node_modules/usb/src/binding/usb_bindings.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 51. This version of Node.js requires
NODE_MODULE_VERSION 54. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/mot/Repos/lean-flow-desktop/node_modules/usb/usb.js:5:38)
    at Object.<anonymous> (/Users/mot/Repos/lean-flow-desktop/node_modules/usb/usb.js:448:3)
```

**Comment by MarshallOfSound** [comment]
Please see our tutorial on [using native modules with Electron](https://github.com/electron/electron/blob/master/docs/tutorial/using-native-node-modules.md)

**Comment by mozillo** [comment]
Issue solved.
After npm install or yarn:
```
./node_modules/.bin/electron-rebuild -p -t "dev,prod,optional"
// -p for parallel
```
