### ISSUE TITLE
File build.ninja not found

### ISSUE THREAD

**Issue by KennyBarraud** [electron/electron#12540]
Hi,
I'm trying to build electron on windows 10 and I'm following the instructions on this [page](https://electronjs.org/docs/development/build-instructions-windows).
But when I'm calling the build, I don't have any out directory and even if I create the missing directory, the cmd said that it needs a build.ninja file.
So I called a second time the bootstrap script however I don't have any build.ninja file.
Where or how do I get this file ?

**Comment by KennyBarraud** [comment]
Ok so I figured out that the bootstapping failed

`
Downloading libchromiumcontent-static.tar.bz2...
https://s3.amazonaws.com/github-janky-artifacts/libchromiumcontent/win/x64/76a718409b7b859c6b708492e89aab0389fe447f/libchromiumcontent-static.tar.bz2
.......Traceback (most recent call last):
  File "D:\Retest Electron\electron\vendor\libchromiumcontent\script\download", line 167, in <module>
    sys.exit(main())
  File "D:\Retest Electron\electron\vendor\libchromiumcontent\script\download", line 65, in main
    download(args.path, base_url, commit, STATIC_LIBRARY_FILENAME)
  File "D:\Retest Electron\electron\vendor\libchromiumcontent\script\download", line 137, in download
    download_and_extract(destination, url)
  File "D:\Retest Electron\electron\vendor\libchromiumcontent\script\download", line 145, in download_and_extract
    chunk = u.read(1024*1024)
  File "C:\Python 2.7.14\lib\socket.py", line 384, in read
    data = self._sock.recv(left)
  File "C:\Python 2.7.14\lib\httplib.py", line 597, in read
    s = self.fp.read(amt)
  File "C:\Python 2.7.14\lib\socket.py", line 384, in read
    data = self._sock.recv(left)
  File "C:\Python 2.7.14\lib\ssl.py", line 766, in recv
    return self.read(buflen)
  File "C:\Python 2.7.14\lib\ssl.py", line 653, in read
    v = self._sslobj.read(len)
socket.error: [Errno 10054] Une connexion existante a d¹ Ûtre fermÚe par lÆh¶te distant
Traceback (most recent call last):
  File "script\bootstrap.py", line 282, in <module>
    sys.exit(main())
  File "script\bootstrap.py", line 61, in main
    libcc_static_library_path)
  File "script\bootstrap.py", line 166, in setup_libchromiumcontent
    subprocess.check_call([sys.executable, script, '-s'] + args)
  File "C:\Python 2.7.14\lib\subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Python 2.7.14\\python.exe', 'D:\\Retest Electron\\electron\\vendor\\libchromiumcontent\\script\\download', '-s', '-f', '-c', '76a718409b7b859c6b708492e89aab0389fe447f', '--target_arch', 'x64', 'https://s3.amazonaws.com/github-janky-artifacts/libchromiumcontent', 'D:\\Retest Electron\\electron\\vendor\\download\\libchromiumcontent']' returned non-zero exit status 1
`

**Comment by KennyBarraud** [comment]
Finally, it succeeds to download the lib chromium content by opening the console in administrator mode. However I have a new issue : 
```
C:\Python 2.7.14\python.exe C:\TestElectron\electron\script\update.py
Download directxsdk-x64     1806291  [100.0%]
Traceback (most recent call last):
  File "C:\TestElectron\electron\script\update.py", line 105, in <module>
    sys.exit(main())
  File "C:\TestElectron\electron\script\update.py", line 24, in main
    return update_gyp()
  File "C:\TestElectron\electron\script\update.py", line 53, in update_gyp
    return (run_gyp(target_arch, 0) or run_gyp(target_arch, 1))
  File "C:\TestElectron\electron\script\update.py", line 58, in run_gyp
    import_vs_env(target_arch)
  File "C:\TestElectron\electron\script\lib\util.py", line 249, in import_vs_env
    env = get_vs_env('[15.0,16.0)', vs_arch)
  File "C:\TestElectron\electron\script\lib\env_util.py", line 81, in get_vs_env
    stdout=subprocess.PIPE)
  File "C:\Python 2.7.14\lib\subprocess.py", line 390, in __init__
    errread, errwrite)
  File "C:\Python 2.7.14\lib\subprocess.py", line 640, in _execute_child
    startupinfo)
WindowsError: [Error 2] Le fichier spÚcifiÚ est introuvable
None
Traceback (most recent call last):
  File "script\bootstrap.py", line 280, in <module>
    sys.exit(main())
  File "script\bootstrap.py", line 68, in main
    run_update(defines, args.msvs)
  File "script\bootstrap.py", line 257, in run_update
    execute_stdout(args)
  File "C:\TestElectron\electron\script\lib\util.py", line 184, in execute_stdout
    raise e
subprocess.CalledProcessError: Command '['C:\\Python 2.7.14\\python.exe', 'C:\\TestElectron\\electron\\script\\update.py']' returned non-zero exit status 1
```

If anyone has the same issue and could tell me how to solve it, it'd be great.

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
