### ISSUE TITLE
s390x support- Failed to find Electron v1.8.2-beta.5 for linux-s390x 

### ISSUE THREAD

**Issue by imdurgadas** [electron/electron#12789]
* Electron version: v1.8.2-beta.5
* Operating system: Linux s390x

### Expected behavior
npm install  electron@1.8.2-beta.5   --> Installs electron on s390x

### Actual behavior
Error: Failed to find Electron v1.8.2-beta.5 for linux-s390x at https://github.com/electron/electron/releases/download/v1.8.2-beta.5/electron-v1.8.2-beta.5-linux-s390x.zip

### How to reproduce
on s390x , npm install  electron@1.8.2-beta.5
 ```
Downloading electron-v1.8.2-beta.5-linux-s390x.zip
Error: GET https://github.com/electron/electron/releases/download/v1.8.2-beta.5/electron-v1.8.2-beta.5-linux-s390x.zip returned 404
/home/theia/theia/node_modules/electron/install.js:47
  throw err
  ^

Error: Failed to find Electron v1.8.2-beta.5 for linux-s390x at https://github.com/electron/electron/releases/download/v1.8.2-beta.5/electron-v1.8.2-beta.5-linux-s390x.zip
    at Request.<anonymous> (/home/theia/theia/node_modules/nugget/index.js:169:61)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestResponse (/home/theia/theia/node_modules/request/request.js:1068:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:551:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:117:23)
    at TLSSocket.socketOnData (_http_client.js:440:20)
    at emitOne (events.js:116:13)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@1.8.2-beta.5 postinstall: `node install.js`
```

**Comment by miniak** [comment]
@imdurgadas this is not a supported HW platform.
