### ISSUE TITLE
menu.popup options object should be optional

### ISSUE THREAD

**Issue by tzvetelin-vassilev** [electron/electron#12915]
I have the following code that worked in versions before 2.0.0
------------------------------------------
const remote = require('electron').remote

const contextMenu = new remote.Menu();
contextMenu.append(new remote.MenuItem({label: "myLabel", click: () => console.log("click")}));

function showContextMenu() {
	contextMenu.popup();
}

<body onContextMenu="showContextMenu()" />

------------------------------------------

This code throws:

remote.js:209 Uncaught Error: Could not call remote function ''. Check that the function signature is correct. Underlying error: Options must be an object
Error: Could not call remote function ''. Check that the function signature is correct. Underlying error: Options must be an object
    at callFunction (/Users/vassilev/Projects/electron-test-app/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/rpc-server.js:257:11)
    at EventEmitter.<anonymous> (/Users/vassilev/Projects/electron-test-app/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/rpc-server.js:357:5)
    at emitMany (events.js:147:13)
    at EventEmitter.emit (events.js:224:7)
    at WebContents.<anonymous> (/Users/vassilev/Projects/electron-test-app/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/api/web-contents.js:295:13)
    at emitTwo (events.js:126:13)
    at WebContents.emit (events.js:214:7)
    at callFunction (/Users/vassilev/Projects/electron-test-app/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/rpc-server.js:257:11)
    at EventEmitter.<anonymous> (/Users/vassilev/Projects/electron-test-app/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/rpc-server.js:357:5)
    at emitMany (events.js:147:13)
    at EventEmitter.emit (events.js:224:7)
    at WebContents.<anonymous> (/Users/vassilev/Projects/electron-test-app/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/api/web-contents.js:295:13)
    at emitTwo (events.js:126:13)
    at WebContents.emit (events.js:214:7)
    at Object.exception (/Users/vassilev/Projects/electron-test-app/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/renderer/api/remote.js:209:30)
    at metaToValue (/Users/vassilev/Projects/electron-test-app/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/renderer/api/remote.js:213:28)
    at Object.remoteMemberFunction (/Users/vassilev/Projects/electron-test-app/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/renderer/api/remote.js:113:16)
    at showContextMenu (file:///Users/vassilev/Projects/electron-test-app/index.js:49:14)
    at HTMLBodyElement.oncontextmenu (file:///Users/vassilev/Projects/electron-test-app/index.html:8:96)
exception @ /Users/vassilev/Projects/electron-test-app/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/renderer/api/remote.js:209
metaToValue @ /Users/vassilev/Projects/electron-test-app/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/renderer/api/remote.js:213
remoteMemberFunction @ /Users/vassilev/Projects/electron-test-app/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/renderer/api/remote.js:113
showContextMenu @ index.js:49
oncontextmenu @ index.html:8

**Comment by MarshallOfSound** [comment]
The docs indicate `menu.popup` requires an options object, it is non-optional

https://electronjs.org/docs/api/menu#menupopupoptions

**Comment by alexcroox** [comment]
Since upgrading to 2.0.0 all my popup menus were broken until I replaced

`menu.popup()`

with an empty object

`menu.popup({})`

@tzvetelin-vassilev is correct though, all options in the docs are optional so I think the error handling needs looking at to ensure the absence of an options object still counts as an empty one.

**Comment by MarshallOfSound** [comment]
@alexcroox @tzvetelin-vassilev I want to be clear here 

* This is not a bug (it is working as documented)
* This change is 100% allowed and not a regression as `2.0.0` is a semver bump (allows breaking changes)

I'll reopen this to add the ability for no options object to be passed
