### ISSUE TITLE
electron\script\bootstrap.py fail's during update.py script execution

### ISSUE THREAD

**Issue by TriRozhka** [electron/electron#13060]
branch: master
OS: Windows 7 x64
was working on 05/20/18

**Expected Behavior**
bootstrap.py -v finishes succesfully

**Actual behavior**
bootstrap.py -v fails during update.py

**To Reproduce**
Follow the guide at https://github.com/electron/electron/blob/master/docs/development/build-instructions-windows.md

**Additional Information**
It happens even with clean setup
Error log:
C:\Python27\python.exe H:\Projects\Visual\electron\script\update.py
Traceback (most recent call last):
  File "vendor\gyp\gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "vendor\gyp\pylib\gyp\__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "vendor\gyp\pylib\gyp\__init__.py", line 538, in main
    return gyp_main(args)
  File "vendor\gyp\pylib\gyp\__init__.py", line 523, in gyp_main
    generator.GenerateOutput(flat_list, targets, data, params)
  File "vendor\gyp\pylib\gyp\generator\ninja.py", line 2486, in GenerateOutput
    pool.map(CallGenerateOutputForConfig, arglists)
  File "C:\Python27\lib\multiprocessing\pool.py", line 251, in map
    return self.map_async(func, iterable, chunksize).get()
  File "C:\Python27\lib\multiprocessing\pool.py", line 567, in get
    raise self._value
UnicodeDecodeError: 'ascii' codec can't decode byte 0xf2 in position 5822: ordin
al not in range(128)
None
Traceback (most recent call last):
  File "script\bootstrap.py", line 298, in <module>
    sys.exit(main())
  File "script\bootstrap.py", line 73, in main
    run_update(defines, args.msvs)
  File "script\bootstrap.py", line 275, in run_update
    execute_stdout(args)
  File "H:\Projects\Visual\electron\script\lib\util.py", line 184, in execute_st
dout
    raise e
subprocess.CalledProcessError: Command '['C:\\Python27\\python.exe', 'H:\\Projec
ts\\Visual\\electron\\script\\update.py']' returned non-zero exit status 1

**Comment by TriRozhka** [comment]
tested at another pc - no problem. closing.
