### ISSUE TITLE
MenuItem click (item, bw, ev) {} throws: ev.preventDefault is not a function

### ISSUE THREAD

**Issue by JieJiSS** [electron/electron#13355]
* Electron Version: v1.8.7
* Operating System (Platform and Version): macOS 10.12.4 Retina
* Last known working Electron version: Well, electron@1.6.18 also fails on my PC.

**Expected Behavior**
According to the `electron.d.ts` definitely typed file released [here](https://github.com/electron/electron/releases/tag/v1.8.7), line 31 to 39:

```ts
interface Event extends GlobalEvent {
    preventDefault: () => void;
    sender: WebContents;
    returnValue: any;
    ctrlKey?: boolean;
    metaKey?: boolean;
    shiftKey?: boolean;
    altKey?: boolean;
}
```

and `ev` is an instance of `Electron.Event`, so I wrote

```js
menu.append(new MenuItem({
    label: "Always On Top",
    type: "checkbox",
    checked: false,
    click (item, browserWindow, ev) {
        if(browserWindow === win[0]) { // main window
            ev.preventDefault(); // ignore
        } else {
            // ...
        }
    }
}));
```

and expected `Always On Top` MenuItem to keep it's `checked` value unchanged when the user right-click on the main window and clicked the `Always On Top` item.

**Actual behavior**

I got a `TypeError` (showing in an alert box).

```js
A JavaScript error occurred in the main process:
Uncaught Exception:
TypeError: ev.preventDefault is not a function
    at click (path/to/project/main.js:20:16)
    at MenuItem.click ($HOME/.nvm/versions/node/v8.0.0/lib/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/api/menu-item.js:52:9)
    at Function.executeCommand ($HOME/.nvm/versions/node/v8.0.0/lib/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/api/menu.js:34:15)
    at Menu.popup ($HOME/.nvm/versions/node/v8.0.0/lib/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/api/menu.js:90:8)
    at WebContents.<anonymous> ($HOME/Work/Code/js/im-lazy/progress-timer/main.js:134:14)
    at emitTwo (events.js:125:13)
    at WebContents.emit (events.js:213:7)
```

And `Object.keys(ev)` resulted in printing `[ 'shiftKey', 'ctrlKey', 'altKey', 'metaKey' ]`.

**To Reproduce**

```js
const { app, BrowserWindow, Menu, MenuItem } = require("electron");
let win = [];

const menu = new Menu();
menu.append(new MenuItem({
    label: "Always On Top",
    type: "checkbox",
    checked: false,
    click (item, rightclickWindow, ev) {
        if(rightclickWindow === win[0]) { // main window
            console.log(Object.keys(ev));
            ev.preventDefault();
            ev.stopPropagation();
            return false; // ignore
        } else {
            console.log("OK");
        }
    }
}));

function createMainWindow () {
    win = [];
    let mainWin = new BrowserWindow({
        width: 380, 
        height: 300,
        background: "#ffffff",
        show: false,
        resizable: false,
    });

    mainWin.on("ready-to-show", () => {
        mainWin.show();
        mainWin.focus();
    });

    mainWin.loadURL(
        url.format({
            pathname: path.join(__dirname, "/src/main.html"),
            protocol: "file:",
            slashes: true
        })
    );

    mainWin.on("closed", () => {
        win.forEach(w => {
            if(!w.isDestroyed() && w.isClosable())
                w.close();
        })
        win = [];
    });

    win.push(mainWin);
}

function createSubWindow (...args) {
    // ...
}
```

**Screenshots**

**Additional Information**

**Comment by JieJiSS** [comment]
Also, I've tried to use:

```js
mainWin.webContents.on("context-menu", ev => {
    console.log(Object.keys(ev)); // [ 'preventDefault', 'sender' ]
    ev.preventDefault();
});
```

as a temporary patch, but this too didn't work. The menu was popped up as usual.

**Comment by JieJiSS** [comment]
I've been trying to debug the Main Process, and I got a stack trace via debugger:

```js
(6) click (/Users/jiejiss/Work/Code/js/im-lazy/progress-timer/main.js:20)
(5) MenuItem.click (/Users/jiejiss/Work/Code/js/im-lazy/progress-timer/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/api/menu-item.js:52)
(4) executeCommand (/Users/jiejiss/Work/Code/js/im-lazy/progress-timer/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/api/menu.js:34)
(3) Menu.popup (/Users/jiejiss/Work/Code/js/im-lazy/progress-timer/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/api/menu.js:90)
(2) (anonymous function) (/Users/jiejiss/Work/Code/js/im-lazy/progress-timer/main.js:134)
(1) emitTwo (events.js:130)
(0) emit (events.js:213)
```

However, when I inspected on `(4) browser/api/menu.js:34` and `(3) browser/api/menu.js:90`, it became quite confusing: the 90th line of `menu.js` is:

```js
this.popupAt(newWindow, newX, newY, newPosition, asyncPopup)
```

and the 31th to 35th line of `menu.js` is 

```js
executeCommand: (event, id) => {
  const command = this.commandsMap[id]
  if (!command) return
  command.click(event, BrowserWindow.getFocusedWindow(), webContents.getFocusedWebContents())
}
```

It seems that there's a stack (few stacks) hiding between `(4)` and `(3)`... I guess that might be C/C++ napi calls. (please correct me if I was wrong... I'm still new to electron)

**Comment by JieJiSS** [comment]
tested on v2.0.2, still occurs.

**Comment by JieJiSS** [comment]
Now I'm using a workaround (only for `MenuItem.prototype.type === "checkbox"`):

```js
click (item, rightclickWindow) {
    if(rightclickWindow === win[0]) { // main window
        item.click(); // since ev.preventDefault is undefined
        // notice that this will call click(item, undefined, event) again!
    } else {
        if(rightclickWindow === undefined) // fired by item.click(), ignore
            return false;
        if(rightclickWindow === null) {
            item.click(); // the window is not focused and thus arguments[1] is null
            return false;
        }
        // ...
    }
}
```

**Comment by JieJiSS** [comment]
I've recognized that there exists related useful events:

```js
app.on("browser-window-created", function (event, targetWindow) {
    targetWindow.webContents.on("context-menu", function (ev, params) {
        menu.popup(targetWindow, params.x, params.y);
    })
});

ipcMain.on("show-context-menu", function (event) {
    // event.sender works in this case
    const targetWindow = BrowserWindow.fromWebContents(event.sender);
    menu.popup(targetWindow);
});
```

In both cases, `targetWindow` is an instance of Electron.BrowserWindow and refers to the being-right-clicked window, which means that using a global variable to store the `targetWindow`, update it when events are fired, and use it in `click(item, bw, event) { ... }` can be possible. However, I'm not sure whether this method is robust enough or not.

**Comment by JieJiSS** [comment]
Any progress so far?

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron v4.2.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by JieJiSS** [comment]
ok, I will try v4.2 tonight
