### ISSUE TITLE
Menu.setApplicationMenu

### ISSUE THREAD

**Issue by kikimanTo** [electron/electron#13661]
* Electron Version: 2.0.4
* Operating System (Platform and Version): Windows 10 Home
* Last known working Electron version: 

This is the code I have.

const electron = require('electron');
const url = require('url');
const path = require('path');

const {app, BrowserWindow, Menu} = require('electron');

let mainWindow;

// Listen for app to be ready.
app.on('ready', function(){
    //Create window
    mainWindow = new BrowserWindow({});
    //Load HTML into window
    mainWindow.loadURL(url.format({
        pathname: path.join(__dirname, 'mainWindow.html'),
        protocol:'file:',
        slashes: true
    }));

    // Build menu from template
    const mainMenu = Menu.buildFromTemplate(mainMenuTemplate);
    // Insert menu
    Menu.setApplictionMenu(mainMenu);
});

// Create menu template

const mainMenuTemplate = [
    {
        label:'File'
    }
];

And that's the error I get.

> [Main` Instruction]
> A JavaScript error occurred in the main process
> 
> [Content]
> Uncaught Exception:
> TypeError: Menu.setApplictionMenu is not a function
>     at App.<anonymous> (C:\Users\deyan\Desktop\fortnitebr\main.js:23:10)
>     at emitTwo (events.js:131:20)
>     at App.emit (events.js:214:7)
>

**Comment by decarbonite** [comment]
You seem to have a typo in your functions name, it should be setApplicationMenu instead of setApplictionMenu
