### ISSUE TITLE
Error: Cannot create BrowserWindow before app is ready

### ISSUE THREAD

**Issue by kikimanTo** [electron/electron#13669]
* Electron Version: 2.0.4
* Operating System (Platform and Version): Windows 10 Home
* Last known working Electron version: 2.0.4

I've just got this error, don't know where it's coming from.

> App threw an error during load
Error: Cannot create BrowserWindow before app is ready
    at Object.<anonymous> (C:\Users\deyan\Desktop\fortnitebr\main.js:8:14)
    at Object.<anonymous> (C:\Users\deyan\Desktop\fortnitebr\main.js:39:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at loadApplicationPackage (C:\Users\deyan\Desktop\fortnitebr\node_modules\electron\dist\resources\default_app.asar\main.js:287:12)
    at Object.<anonymous> (C:\Users\deyan\Desktop\fortnitebr\node_modules\electron\dist\resources\default_app.asar\main.js:328:5)
    at Object.<anonymous> (C:\Users\deyan\Desktop\fortnitebr\node_modules\electron\dist\resources\default_app.asar\main.js:365:3)

This is the code.

> const electron = require('electron');
// const app = electron.app;
// const BrowserWindow = electron.BrowserWindow;
// const Menu = electron.Menu;

const {BrowserWindow, app} = require('electron');

mainWindow = new BrowserWindow({width: 800, height: 600, frame: false});

(function () {

  var remote = require('remote'); 
  var BrowserWindow = remote.require('browser-window'); 

 function init() { 
      document.getElementById("min-btn").addEventListener("click", function (e) {
           var window = BrowserWindow.getFocusedWindow();
           window.minimize(); 
      });

      document.getElementById("max-btn").addEventListener("click", function (e) {
           var window = BrowserWindow.getFocusedWindow(); 
           window.maximize(); 
      });

      document.getElementById("close-btn").addEventListener("click", function (e) {
           var window = BrowserWindow.getFocusedWindow();
           window.close();
      }); 
 }; 

 document.onreadystatechange = function () {
      if (document.readyState == "complete") {
           init(); 
      }
 };

})();

**Comment by MarshallOfSound** [comment]
Thanks @haroldiedema

**Comment by z0xyz** [comment]
For reference, I was using the `app.whenReady()` method -which works just fine- but the second callback function was  called by appending parenthesis rather than just referencing its plain signature, which resulted in the same apparently generic error message.
