### ISSUE TITLE
Node-serialport and electron-rebuild not working

### ISSUE THREAD

**Issue by Melander00** [electron/electron#13897]
* Electron Version: 2.0.5
* Operating System (Platform and Version): Windows 7 x64
* Last known working Electron version: Not Sure

**Expected Behavior**
I expect that when i try to use node-serialport it will not work when i use it in electron beacuse it is a native node module, so i can use electron-rebuild to rebuild it to electrons node.js version.

**Actual behavior**
When i tried using node-serialport without rebuilding i got:
```
Uncaught Error: The system could not locate message text for message number 0x%1 in the message file for %2.
\\?\C:\xampp\htdocs\True\RentiX\node_modules\serialport\build\Release\serialport.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:172:20)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at bindings (C:\xampp\htdocs\True\RentiX\node_modules\bindings\bindings.js:81:44)
    at Object.<anonymous> (C:\xampp\htdocs\True\RentiX\node_modules\serialport\lib\bindings\win32.js:2:36)
```
and when i tried to use electron-rebuild i got this error message in git bash:
```
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'rebuild' ]
2 info using npm@5.6.0
3 info using node@v8.11.3
4 verbose run-script [ 'prerebuild', 'rebuild', 'postrebuild' ]
5 info lifecycle serialporttest@1.0.0~prerebuild: serialporttest@1.0.0
6 info lifecycle serialporttest@1.0.0~rebuild: serialporttest@1.0.0
7 verbose lifecycle serialporttest@1.0.0~rebuild: unsafe-perm in lifecycle true
8 verbose lifecycle serialporttest@1.0.0~rebuild: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\xampp\htdocs\True\serialportTest\node_modules\.bin;C:\Users\Samuel\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\Samuel\bin;C:\Program Files (x86)\AMD APP\bin\x86_64;C:\Program Files (x86)\AMD APP\bin\x86;C:\Program Files\Common Files\Microsoft Shared\Windows Live;C:\Program Files (x86)\Common Files\Microsoft Shared\Windows Live;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files (x86)\ATI Technologies\ATI.ACE\Core-Static;C:\Program Files (x86)\Brackets\command;C:\ProgramData\chocolatey\bin;C:\Program Files\dotnet;C:\Program Files\nodejs;C:\Program Files\Git\cmd;C:\Users\Samuel\AppData\Local\Programs\Python\Python37-32\Scripts;C:\Users\Samuel\AppData\Local\Programs\Python\Python37-32;C:\Users\Samuel\AppData\Local\.meteor;C:\Users\Samuel\AppData\Roaming\npm;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
9 verbose lifecycle serialporttest@1.0.0~rebuild: CWD: C:\xampp\htdocs\True\serialportTest
10 silly lifecycle serialporttest@1.0.0~rebuild: Args: [ '/d /s /c', 'electron-rebuild -f -w serialport' ]
11 silly lifecycle serialporttest@1.0.0~rebuild: Returned: code: 4294967295  signal: null
12 info lifecycle serialporttest@1.0.0~rebuild: Failed to exec rebuild script
13 verbose stack Error: serialporttest@1.0.0 rebuild: `electron-rebuild -f -w serialport`
13 verbose stack Exit status 4294967295
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:285:16)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at EventEmitter.emit (events.js:214:7)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at emitTwo (events.js:126:13)
13 verbose stack     at ChildProcess.emit (events.js:214:7)
13 verbose stack     at maybeClose (internal/child_process.js:925:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
14 verbose pkgid serialporttest@1.0.0
15 verbose cwd C:\xampp\htdocs\True\serialportTest
16 verbose Windows_NT 6.1.7601
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "rebuild"
18 verbose node v8.11.3
19 verbose npm  v5.6.0
20 error code ELIFECYCLE
21 error errno 4294967295
22 error serialporttest@1.0.0 rebuild: `electron-rebuild -f -w serialport`
22 error Exit status 4294967295
23 error Failed at the serialporttest@1.0.0 rebuild script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 4294967295, true ]
```
and i thought maybe it worked but no i got this instead now when i open the electron app:

```
App threw an error during load
Error: Could not locate the bindings file. Tried:
 → C:\xampp\htdocs\True\serialportTest\node_modules\serialport\build\serialport.node
 → C:\xampp\htdocs\True\serialportTest\node_modules\serialport\build\Debug\serialport.node
 → C:\xampp\htdocs\True\serialportTest\node_modules\serialport\build\Release\serialport.node
 → C:\xampp\htdocs\True\serialportTest\node_modules\serialport\out\Debug\serialport.node
 → C:\xampp\htdocs\True\serialportTest\node_modules\serialport\Debug\serialport.node
 → C:\xampp\htdocs\True\serialportTest\node_modules\serialport\out\Release\serialport.node
 → C:\xampp\htdocs\True\serialportTest\node_modules\serialport\Release\serialport.node
 → C:\xampp\htdocs\True\serialportTest\node_modules\serialport\build\default\serialport.node
 → C:\xampp\htdocs\True\serialportTest\node_modules\serialport\compiled\8.9.3\win32\x64\serialport.node
    at bindings (C:\xampp\htdocs\True\serialportTest\node_modules\bindings\bindings.js:93:9)
    at Object.<anonymous> (C:\xampp\htdocs\True\serialportTest\node_modules\serialport\lib\bindings\win32.js:2:36)
    at Object.<anonymous> (C:\xampp\htdocs\True\serialportTest\node_modules\serialport\lib\bindings\win32.js:111:3)
    at Module._compile (module.js:642:30)
    at Object.Module._extensions..js (module.js:653:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)

```
**To Reproduce**
`npm init`    in new folder
`npm install --save electron`
Create file named main.js and have it say `require("serialport")`
`npm install --save serialport`
`npm install --save-dev electron-rebuild`
**In package.json**
"scripts": {
"rebuild": "electron-rebuild -f -w  serialport"
}
`npm run rebuild`
And then
`electron .`

**Additional Information**
I have tried with using npm to install using
```
export npm_config_target=1.2.3
export npm_config_arch=x64
export npm_config_target_arch=x64
export npm_config_disturl=https://atom.io/download/electron
export npm_config_runtime=electron
export npm_config_build_from_source=true
HOME=~/.electron-gyp npm install
```
and it got some errors in swedish about VCBuild.exe not found or something like that.

I would really appreciate help as i've tried so many different "solutions".

**Comment by MarshallOfSound** [comment]
This is not an Electron issue, it looks like you are missing the native dependencies required to build the serialport module on your machine.  I'd recommend reading the documentation for that module

**Comment by FelixPcll** [comment]
I'm rebuilding the serialport, but when I open npm start, an error occurred as if I didn't rebuild
