### ISSUE TITLE
Electron: __ was compiled against a different version of Node.js

### ISSUE THREAD

**Issue by liushaohua** [electron/electron#13936]
When trying to package electron app on macOS Sierra using electron-installer-dmg, I get the following:
```
Error: Cannot open /Users/liushaohua/Documents/DATA/IMTalk/node_modules/hello.node: Error: The module '/Users/liushaohua/Documents/DATA/IMTalk/node_modules/hello.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 57. This version of Node.js requires
NODE_MODULE_VERSION 64. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.<anonymous> (/Users/liushaohua/Documents/DATA/IMTalk/dist/electron/main.js:24435:223)
    at Object.module.exports.module.exports (/Users/liushaohua/Documents/DATA/IMTalk/dist/electron/main.js:24436:30)
```
Versions:
```
Node v8.11.1
npm: 5.6.0
electron: 3.0.0-beta.4
```
Is there any solution to this problem?

**Comment by MarshallOfSound** [comment]
https://electronjs.org/docs/tutorial/using-native-node-modules

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).
