### ISSUE TITLE
Missing remote object should never be missing

### ISSUE THREAD

**Issue by CharlieHess** [electron/electron#14054]
* Electron Version: 3.0.0-beta.4
* Operating System (Platform and Version): All 
* Last known working Electron version: < 3.0.0

Remote objects assigned in a preload script can go missing in 3.0, causing errors at very unexpected times:

```
Cannot call function 'bounce' on missing remote object 12
    at throwRPCError (/Applications/Slack.app/Contents/Resources/electron.asar/browser/rpc-server.js:145:17)
    at EventEmitter.<anonymous> (/Applications/Slack.app/Contents/Resources/electron.asar/browser/rpc-server.js:357:7)
    at EventEmitter.emit (events.js:182:13)
    at EventEmitter.emit (domain.js:442:20)
    at WebContents.<anonymous> (/Applications/Slack.app/Contents/Resources/electron.asar/browser/api/web-contents.js:287:13)
    at WebContents.emit (events.js:182:13)
    at WebContents.EventEmitter.emit (domain.js:442:20)
    at WebContents.topLevelDomainCallback (domain.js:121:23)
```

This is an error we'd never expect to see, since our preload script assigns a remote object at the import level:

``` js
import { remote } from 'electron';

const { app } = remote;
const dock = app.dock;

bounce(type: 'critical' | 'informational') {
  const id = dock.bounce(type);
}
```

@paulcbetts reported this in the [electronhq](https://electronhq.slack.com/archives/C3DQJHAQ3/p1532018231000066) Slack; it looks like all he did was receive a notification on the Electron 3 build of Slack posted there.

Since `remote` relies on `ipc.sendSync`, I wonder if it's fixed by https://github.com/electron/electron/pull/13941?

**Comment by javer** [comment]
Hit with the same issue using `screen` or `desktopCapturer` in preload script.

Affected Electron versions: `v3.0.0-beta.1`...`v3.0.0-beta.5`

This issue can be easily reproduced using copy of electron-quick-start repository with one additional commit on top of it.
Steps to reproduce:
1. Install app and start it
```sh
git clone https://github.com/javer/electron-quick-start
cd electron-quick-start
git checkout electron3-missing-remote-bug-reproduce
npm install
npm start
```
2. Open Developers Console (Cmd+Alt+I)
3. Refresh the page (Cmd+R)
4. See error in console:
```
Uncaught Error: Cannot call function 'getAllDisplays' on missing remote object 1
Error: Cannot call function 'getAllDisplays' on missing remote object 1
    at throwRPCError (node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/rpc-server.js:145)
    at EventEmitter.<anonymous> (node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/rpc-server.js:357)
    at EventEmitter.emit (events.js:182)
    at WebContents.<anonymous> (node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/api/web-contents.js:287)
    at WebContents.emit (events.js:182)
    at throwRPCError (node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/rpc-server.js:145)
    at EventEmitter.<anonymous> (node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/rpc-server.js:357)
    at EventEmitter.emit (events.js:182)
    at WebContents.<anonymous> (node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/api/web-contents.js:287)
    at WebContents.emit (events.js:182)
    at metaToException (./electron-quick-start/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/renderer/api/remote.js:271)
    at Object.exception (./electron-quick-start/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/renderer/api/remote.js:219)
    at metaToValue (./electron-quick-start/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/renderer/api/remote.js:223)
    at Object.remoteMemberFunction (./electron-quick-start/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/renderer/api/remote.js:123)
    at Object.<anonymous> (./electron-quick-start/renderer.js:4)
    at Object.<anonymous> (./electron-quick-start/renderer.js:6)
    at Module._compile (internal/modules/cjs/loader.js:711)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722)
    at Module.load (internal/modules/cjs/loader.js:620)
    at tryModuleLoad (internal/modules/cjs/loader.js:559)
```
5. Every time you refresh the page the number of missing remote object increases.

Issue is not connected with opened Developers Console and reproduces without it. All you need is refresh page with preload script at least once.

**Comment by eric8810** [comment]
```javascript
Error: Cannot call function 'setSize' on missing remote object 12
Error: Cannot call function 'setSize' on missing remote object 12
    at throwRPCError (:8080/Users/chenghan/Desktop/code/electron-zenchat/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/rpc-server.js:145)
    at EventEmitter.<anonymous> (:8080/Users/chenghan/Desktop/code/electron-zenchat/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/rpc-server.js:357)
    at EventEmitter.emit (events.js:182)
    at WebContents.<anonymous> (:8080/Users/chenghan/Desktop/code/electron-zenchat/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/api/web-contents.js:287)
    at WebContents.emit (events.js:182)
    at throwRPCError (:8080/Users/chenghan/Desktop/code/electron-zenchat/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/rpc-server.js:145)
    at EventEmitter.<anonymous> (:8080/Users/chenghan/Desktop/code/electron-zenchat/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/rpc-server.js:357)
    at EventEmitter.emit (events.js:182)
    at WebContents.<anonymous> (:8080/Users/chenghan/Desktop/code/electron-zenchat/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/api/web-contents.js:287)
    at WebContents.emit (events.js:182)
    at metaToException (/Users/chenghan/Desktop/code/electron-zenchat/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/renderer/api/remote.js:271)
    at Object.exception (/Users/chenghan/Desktop/code/electron-zenchat/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/renderer/api/remote.js:219)
    at metaToValue (/Users/chenghan/Desktop/code/electron-zenchat/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/renderer/api/remote.js:223)
    at Object.remoteMemberFunction (/Users/chenghan/Desktop/code/electron-zenchat/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/renderer/api/remote.js:123)
    at VueComponent.mounted (Main.vue?48a8:144)
    at callHook (vue.esm.js?efeb:2921)
    at Object.insert (vue.esm.js?efeb:4158)
    at invokeInsertHook (vue.esm.js?efeb:5960)
    at Vue.patch [as __patch__] (vue.esm.js?efeb:6179)
    at Vue._update (vue.esm.js?efeb:2660)
```

same problem here

**Comment by SwiTool** [comment]
I can confirm I have the same error/problem on `v3.0.0-beta.5`

**Comment by sidneys** [comment]
Confirming that the issue persists on `v.3.0.0-beta.7`.

**Comment by dsabanin** [comment]
I see that issue in 4.0.2 when trying to access ```remote.process.env```
