### ISSUE TITLE
node 10.7 required: napi_create_threadsafe_function not defined

### ISSUE THREAD

**Issue by karissa** [electron/electron#14247]
* Electron Version: 3.0, 2.x
* Operating System (Platform and Version): Ubuntu

With node 10, napi_create_threadsafe_function is an unknown symbol in the electron context.

The same library, called [deltachat-node](https://github.com/deltachat/deltachat-node) works fine in a [CLI protoype](https://github.com/deltachat/deltachat-cli) on node > 10.7

```sh
$ git clone https://github.com/deltachat/deltachat-desktop
$ npm install
$ npm run dev
```

This is the full output when running a command to login:

```
okdistribute@okdistribute:~/node_modules/deltachat-desktop$ npm run dev

> deltachat-desktop@1.0.0 dev /home/okdistribute/node_modules/deltachat-desktop
> npm run build && electron . --debug --disable-http-cache


> deltachat-desktop@1.0.0 build /home/okdistribute/node_modules/deltachat-desktop
> buble src --output build

(node:6734) Warning: N-API is an experimental feature and could change at any time.
Missing config file: Creating new one
/home/okdistribute/node_modules/deltachat-desktop/node_modules/electron/dist/electron --debug --disable-http-cache .: symbol lookup error: /home/okdistribute/node_modules/deltachat-node/build/Debug/deltachat.node: undefined symbol: napi_create_threadsafe_function
```

Do you know if it's possible to cross-compile somehow? (electron-builder did not solve the issue, it just gave me a more detailed error message about how napi functions are not defined)

```
> deltachat-desktop@1.0.0 rebuild-delta /home/okdistribute/node_modules/deltachat-desktop
> cd node_modules/deltachat-node && cross-env HOME=~/.electron-gyp node-gyp rebuild --target=2.0.7 --runtime=electron --arch=x64 --dist-url=https://atom.io/download/atom-shell

make: Entering directory '/home/okdistribute/node_modules/deltachat-desktop/node_modules/deltachat-node/build'
  CC(target) Release/obj.target/deltachat/src/module.o
../src/module.c:16:3: error: unknown type name ‘napi_threadsafe_function’
   napi_threadsafe_function threadsafe_event_handler;
   ^~~~~~~~~~~~~~~~~~~~~~~~
../src/module.c: In function ‘dc_event_handler’:
../src/module.c:48:9: warning: implicit declaration of function ‘napi_call_threadsafe_function’; did you mean ‘napi_create_function’? [-Wimplicit-function-declaration]
         napi_call_threadsafe_function(dcn_context->threadsafe_event_handler, dcn_event, napi_tsfn_blocking);
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
         napi_create_function
../src/module.c:48:89: error: ‘napi_tsfn_blocking’ undeclared (first use in this function); did you mean ‘napi_run_script’?
         napi_call_threadsafe_function(dcn_context->threadsafe_event_handler, dcn_event, napi_tsfn_blocking);
                                                                                         ^~~~~~~~~~~~~~~~~~
                                                                                         napi_run_script
../src/module.c:48:89: note: each undeclared identifier is reported only once for each function it appears in
../src/module.c: In function ‘imap_thread_func’:
../src/module.c:115:3: warning: implicit declaration of function ‘napi_acquire_threadsafe_function’; did you mean ‘napi_create_function’? [-Wimplicit-function-declaration]
   napi_acquire_threadsafe_function(dcn_context->threadsafe_event_handler);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   napi_create_function
../src/module.c:123:3: warning: implicit declaration of function ‘napi_release_threadsafe_function’; did you mean ‘napi_create_function’? [-Wimplicit-function-declaration]
   napi_release_threadsafe_function(dcn_context->threadsafe_event_handler, napi_tsfn_release);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   napi_create_function
../src/module.c:123:75: error: ‘napi_tsfn_release’ undeclared (first use in this function); did you mean ‘napi_is_promise’?
   napi_release_threadsafe_function(dcn_context->threadsafe_event_handler, napi_tsfn_release);
                                                                           ^~~~~~~~~~~~~~~~~
                                                                           napi_is_promise
../src/module.c: In function ‘smtp_thread_func’:
../src/module.c:138:75: error: ‘napi_tsfn_release’ undeclared (first use in this function); did you mean ‘napi_is_promise’?
   napi_release_threadsafe_function(dcn_context->threadsafe_event_handler, napi_tsfn_release);
                                                                           ^~~~~~~~~~~~~~~~~
                                                                           napi_is_promise
../src/module.c: In function ‘dcn_context_new’:
../src/module.c:230:41: warning: assignment makes integer from pointer without a cast [-Wint-conversion]
   dcn_context->threadsafe_event_handler = NULL;
                                         ^
In file included from ../src/napi-macros-extensions.h:1:0,
                 from ../src/module.c:9:
../src/module.c: In function ‘dcn_set_event_handler’:
../src/module.c:1181:22: warning: implicit declaration of function ‘napi_create_threadsafe_function’; did you mean ‘napi_create_function’? [-Wimplicit-function-declaration]
   NAPI_STATUS_THROWS(napi_create_threadsafe_function(
                      ^
../../napi-macros/napi-macros.h:21:8: note: in definition of macro ‘NAPI_STATUS_THROWS’
   if ((call) != napi_ok) { \
        ^~~~
../src/module.c: In function ‘dcn_unset_event_handler’:
../src/module.c:1281:75: error: ‘napi_tsfn_release’ undeclared (first use in this function); did you mean ‘napi_is_promise’?
   napi_release_threadsafe_function(dcn_context->threadsafe_event_handler, napi_tsfn_release);
                                                                           ^~~~~~~~~~~~~~~~~
                                                                           napi_is_promise
In file included from ../src/napi-macros-extensions.h:1:0,
                 from ../src/module.c:9:
../src/module.c: In function ‘dcn_msg_get_filebytes’:
../src/napi-macros-extensions.h:32:22: warning: implicit declaration of function ‘napi_create_bigint_int64’; did you mean ‘napi_create_int64’? [-Wimplicit-function-declaration]
   NAPI_STATUS_THROWS(napi_create_bigint_int64(env, name, &return_int64)); \
                      ^
../../napi-macros/napi-macros.h:21:8: note: in definition of macro ‘NAPI_STATUS_THROWS’
   if ((call) != napi_ok) { \
        ^~~~
../src/module.c:1615:3: note: in expansion of macro ‘NAPI_RETURN_UINT64’
   NAPI_RETURN_UINT64(filebytes);
   ^~~~~~~~~~~~~~~~~~
deltachat.target.mk:105: recipe for target 'Release/obj.target/deltachat/src/module.o' failed
make: *** [Release/obj.target/deltachat/src/module.o] Error 1
make: Leaving directory '/home/okdistribute/node_modules/deltachat-desktop/node_modules/deltachat-node/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/okdistribute/.nvm/versions/node/v10.9.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:239:12)
gyp ERR! System Linux 4.15.0-32-generic
gyp ERR! command "/home/okdistribute/.nvm/versions/node/v10.9.0/bin/node" "/home/okdistribute/.nvm/versions/node/v10.9.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--target=2.0.7" "--runtime=electron" "--arch=x64" "--dist-url=https://atom.io/download/atom-shell"
gyp ERR! cwd /home/okdistribute/node_modules/deltachat-desktop/node_modules/deltachat-node
gyp ERR! node -v v10.9.0
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! deltachat-desktop@1.0.0 rebuild-delta: `cd node_modules/deltachat-node && cross-env HOME=~/.electron-gyp node-gyp rebuild --target=2.0.7 --runtime=electron --arch=x64 --dist-url=https://atom.io/download/atom-shell`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the deltachat-desktop@1.0.0 rebuild-delta script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/okdistribute/.npm/_logs/2018-08-21T20_50_16_351Z-debug.log
```

**Comment by ralphtheninja** [comment]
`electron` needs to based on at least `v10.6.0` to support [`napi_create_threadsafe_function()`](https://nodejs.org/dist/latest-v10.x/docs/api/all.html#n_api_napi_create_threadsafe_function) and at least `v10.7.0` to support [`napi_create_bigint_int64()`](https://nodejs.org/dist/latest-v10.x/docs/api/all.html#n_api_napi_create_bigint_int64).

**Comment by codebytere** [comment]
We're not yet on a version of Node that supports that function. 
Please see electronjs.org for the versions of Node bundled with different versions of Electron.

**Comment by ralphtheninja** [comment]
> @ralphtheninja it'll go out in in 4.0.0-beta.1, after Chromium 67 is merged, but you'll be able to access it in the master nightlies once C67 has been merged and before the 4-0-x branch has been cut.

Awesome! Thanks for info :smile:

**Comment by orange4glace** [comment]
Do I have to build nightly build version manually? If so, is there any information for it?

**Comment by codebytere** [comment]
the nightly build works just like a beta or stable, `npm install electron@nightly`!

**Comment by orange4glace** [comment]
@codebytere That's awesome, Thank you! :)
