### ISSUE TITLE
All Electron based apps crash at launch on Ubuntu 18.10

### ISSUE THREAD

**Issue by sryze** [electron/electron#14541]
I have tried using a number of Electron apps on Ubuntu 18.10 (which is not released yet) , e.g. VS Code, Atom, Skype, and none of them work - they all segfault immediately after launch with the similar stack traces:

Atom (1.30.0):

```
#0  0x0000000000b87650 in  ()
#1  0x00007ffff7d833e2 in node::http2::Http2Session::Callbacks::Callbacks(bool) () at /usr/share/atom/libnode.so
#2  0x00007ffff7d834a5 in  () at /usr/share/atom/libnode.so
#3  0x00007ffff7fe398a in call_init (l=<optimized out>, argc=argc@entry=1, argv=argv@entry=0x7fffffffe008, env=env@entry=0x7fffffffe018)
    at dl-init.c:72
#4  0x00007ffff7fe3a89 in call_init (env=0x7fffffffe018, argv=0x7fffffffe008, argc=1, l=<optimized out>) at dl-init.c:30
#5  0x00007ffff7fe3a89 in _dl_init (main_map=0x7ffff7ffe190, argc=1, argv=0x7fffffffe008, env=0x7fffffffe018) at dl-init.c:119
#6  0x00007ffff7fd40ca in _dl_start_user () at /lib64/ld-linux-x86-64.so.2
#7  0x0000000000000001 in  ()
#8  0x00007fffffffe41c in  ()
#9  0x0000000000000000 in  ()
```

VS Code (package version: 1.27.1-1536226049):

```
#0  0x0000000000ab6fd0 in  ()
#1  0x00007ffff7d839a2 in node::http2::Http2Session::Callbacks::Callbacks(bool) () at /usr/share/code/libnode.so
#2  0x00007ffff7d83a65 in  () at /usr/share/code/libnode.so
#3  0x00007ffff7fe398a in call_init (l=<optimized out>, argc=argc@entry=1, argv=argv@entry=0x7fffffffe108, env=env@entry=0x7fffffffe118)
    at dl-init.c:72
#4  0x00007ffff7fe3a89 in call_init (env=0x7fffffffe118, argv=0x7fffffffe108, argc=1, l=<optimized out>) at dl-init.c:30
#5  0x00007ffff7fe3a89 in _dl_init (main_map=0x7ffff7ffe190, argc=1, argv=0x7fffffffe108, env=0x7fffffffe118) at dl-init.c:119
#6  0x00007ffff7fd40ca in _dl_start_user () at /lib64/ld-linux-x86-64.so.2
#7  0x0000000000000001 in  ()
#8  0x00007fffffffe4d9 in  ()
#9  0x0000000000000000 in  ()
```

* Output of `node_modules/.bin/electron --version`: 
* Operating System (Platform and Version): Ubuntu 18.10 amd64
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable):

**Comment by MarshallOfSound** [comment]
Duplicate #13972
