### ISSUE TITLE
`setEnabled` calls are "queued" up such that if I disable the window twice, I need to enable it twice to reverse the state. Is that expeceted?

### ISSUE THREAD

**Issue by pushkin-** [electron/electron#14632]
* Output of `node_modules/.bin/electron --version`: 2.0.0
* Operating System (Platform and Version): Windows 10

**Expected Behavior**
When I disable a window twice via `setEnabled(false)`, I expect the second disable to have no effect.

**Actual behavior**
The second disable is "queued" up, such that I am forced to enable the window twice to get back to normal.

**To Reproduce**
In the electronquickstart repo, in main.js' `createWindow()`, add these lines:

    mainWindow.setEnabled(false);
    mainWindow.setEnabled(false);
    mainWindow.setEnabled(true);

You see the same issue if you do it in reverse:

    mainWindow.setEnabled(true);
    mainWindow.setEnabled(false); // this doesn't actually disable it, because the window was enabled from the getgo

The window will be disabled when launched. If this is expected behavior, can the [docs](https://github.com/electron/electron/blob/master/docs/api/browser-window.md#winsetenabledenable) be updated to explain this behavior.

**Comment by ckerr** [comment]
This does appear to be the case on Windows and Linux.

[Code](https://github.com/electron/electron/blob/560b1c17af6fa42d42615b3a3ccbae73f5bbaf25/atom/browser/native_window_views.cc#L397):

```cc
void NativeWindowViews::SetEnabled(bool enable) {
  // Handle multiple calls of SetEnabled correctly.
  if (enable) {
    --disable_count_;
    if (disable_count_ != 0)
      return;
  } else {
    ++disable_count_;
    if (disable_count_ != 1)
      return;
  }
```

...so we just update the docs, right? Well, maybe not. The Mac version [doesn't](https://github.com/electron/electron/blob/560b1c17af6fa42d42615b3a3ccbae73f5bbaf25/atom/browser/native_window_mac.mm#L583) appear to support this:

```ObjC
void NativeWindowMac::SetEnabled(bool enable) {
  if (enable) {
    [window_ beginSheet:window_
        completionHandler:^(NSModalResponse returnCode) {
          NSLog(@"modal enabled");
          return;
        }];
  } else {
    [window_ endSheet:[window_ attachedSheet]];
  }
}
```

Looks like the `disable_count__` idiom comes from https://github.com/electron/electron/commit/1104dded24d36b5b213939a6270ead85c8d52d1e from https://github.com/electron/electron/pull/6140, and then [this spec](https://github.com/electron/electron/pull/6140/commits/2c5f4aadfb609689965b9ae4921f47cedcb4cfdf) was the next commit.

And sure enough, if I comment out the `disable_count__` code in `NativeWindowViews::SetEnabled()` to make Windows and Linux behave the same as on Mac, the spec starts failing:

```text
not ok 10 BrowserWindow module parent window modal option disables parent window recursively
  AssertionError [ERR_ASSERTION]: Input A expected to strictly equal input B:
  + expected - actual
  
  - true
  + false
      at Context.it (/home/charles/electron/electron-gn/src/electron/spec/api-browser-window-spec.js:2973:16)
      at runCallback (timers.js:696:18)
      at tryOnImmediate (timers.js:667:5)
```

We should try to find a different fix for this spec so that the client experience will be consistent across all platforms.

**Comment by BinaryMuse** [comment]
I started to untangle this a little bit today; here's what I found.

On Windows and Linux, when you create a new modal window using `new BrowserWindow({ parent, modal: true })`, we [disable the parent window while the child window is shown](https://github.com/electron/electron/blob/d678d9ee7521d93e7a269f02966332151122c42a/atom/browser/native_window_views.cc#L344-L347). When the child window is hidden, we [re-enable the parent window](https://github.com/electron/electron/blob/d678d9ee7521d93e7a269f02966332151122c42a/atom/browser/native_window_views.cc#L370-L372). If the parent window was *already* disabled when the child window was shown, then this would be a bug (we would not want to re-enable the parent window unless it was enabled in the first place). The `disable_count_` check seems to be a mechanism to ensure that every call to `SetEnabled(false)` needs to be matched with a call to `SetEnabled(true)`, preventing this bug. Similarly, if we show more than one child modal, we only want to re-enable the parent window after *all* the modal windows have been closed. (This is what the spec that @ckerr mentioned is testing.)

One option would be to think about these two things separately (that is, (1) whether the user wants the window to be enabled or disabled based on calls to `BrowserWindow#setEnabled` and (2) whether a window should be *allowed* to be enabled or disabled based on how many modal children it has). We would be able to remove the `disable_count_` check and replace it with a count of modal children, and separately add a boolean flag that tracks the user's preference for the window to be enabled or disabled. Any time one of the these two changes, the window is enabled or disabled by considering both data.

On macOS, this gets trickier. To start with, modal children aren't really child windows, per se, but instead, sheets (the little drop-down windows that exist within other windows). When we show a modal child window on macOS, we [use set the child window as a sheet of its parent](https://github.com/electron/electron/blob/d678d9ee7521d93e7a269f02966332151122c42a/atom/browser/native_window_mac.mm#L535-L542). When the window is hidden, we [remove the sheet](https://github.com/electron/electron/blob/d678d9ee7521d93e7a269f02966332151122c42a/atom/browser/native_window_mac.mm#L563-L568). This *essentially* means that there can only ever be one modal child at a time on macOS. Furthermore, the implementation of `IsEnabled` just [checks to see if there are any sheets attached to the window](https://github.com/electron/electron/blob/d678d9ee7521d93e7a269f02966332151122c42a/atom/browser/native_window_mac.mm#L581-L583).

This get's even tricker, though; based on an old conversation @codebytere shared with me and some brief research, there doesn't seem to be a great way to disable an `NSWindow`. As a workaround, to disable a window on macOS, we just [set the window as a sheet of itself](https://github.com/electron/electron/blob/d678d9ee7521d93e7a269f02966332151122c42a/atom/browser/native_window_mac.mm#L585-L595). This seems to have a couple odd effects, including not being able to quit the app when the main window is disabled, not being able to re-enable the window (`endSheet:returnCode: requires a non-nil sheet` is logged), and `IsEnabled` does not properly return `true`. (As a side note, the logic for `SetEnabled` on macOS is reversed, so passing `true` disables the window and passing `false` enables it). I'm less certain what to do about this.

**Comment by BinaryMuse** [comment]
Since the situation with modal windows on macOS is and will remain very different than on Windows and Linux, I'm tempted to ignore the macOS issues for now and solve this for the other two platforms (and tackle macOS separately).

**Comment by ckerr** [comment]
Clarifying question: what are the use cases for multiple modal windows? Is this a feature that needs to be supported?

**Comment by BinaryMuse** [comment]
@ckerr I doubt it, but would removing that feature negate the need to track the initial enabled/disabled state?

**Comment by MarshallOfSound** [comment]
@ckerr I think the use case is stacked modal windows.  I.e. Imagine a notes app

1. Main Window - Has a list of notes with 'rename' buttons, user clicks rename opening window (2)
2. Rename Window - Is a child "modal" window, user starts editing the name then cancels with unsaved changes opening window (3)
3. Confirm Window - Is a child "modal" window, prompting user if they are sure they want to lose changes.

Probably better examples out there but that's just an example use-case, I don't think we can remove the ability to stack modals.

**Comment by BinaryMuse** [comment]
@ckerr Totally! If it makes any difference, at least on my Linux VM, setting multiple modal children on a single window doesn't seem to work very well. I'll do some more research today.

**Comment by BinaryMuse** [comment]
@MarshallOfSound I think this issue is less about *stacked* modals — I think the code would handle that well — but setting multiple modal windows to a *single* parent (which kinda doesn't make sense; which modal can you interact with in that case?)
