### ISSUE TITLE
Can't build electron: runas rebuild fails

### ISSUE THREAD

**Issue by Anrock** [electron/electron#14892]
* Output of `node_modules/.bin/electron --version`: master 7dc7cd1d89d5b2ffc63b03679d77d00de073a7b8
* Operating System (Platform and Version): OSX 10.13.6

**Expected Behavior**
`$ (cd electron/spec && npm i --nodedir=../../out/Debug/gen/node_headers)`
from https://electronjs.org/docs/development/build-instructions-gn#tests executes successfuly.

**Actual behavior**
It fails with message:
```
> runas@3.1.1 install /Users/vladislav.shtepin/Projects/electron-gn/src/electron/spec/node_modules/runas
> node-gyp rebuild

gyp: /Users/vladislav.shtepin/Projects/electron-gn/src/electron/spec/out/Debug/gen/node_headers/common.gypi not found (cwd: /Users/vladislav.shtepin/Projects/electron-gn/src/electron/spec/node_modules/runas) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/vladislav.shtepin/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/Users/vladislav.shtepin/.nvm/versions/node/v8.9.4/bin/node" "/Users/vladislav.shtepin/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/vladislav.shtepin/Projects/electron-gn/src/electron/spec/node_modules/runas
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN electron-test@0.1.0 No description
npm WARN electron-test@0.1.0 No repository field.
npm WARN electron-test@0.1.0 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: abstract-socket@2.0.0 (node_modules/abstract-socket):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for abstract-socket@2.0.0: wanted {"os":"linux","arch":"any"} (current: {"os":"darwin","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! runas@3.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the runas@3.1.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/vladislav.shtepin/.npm/_logs/2018-10-01T08_58_25_187Z-debug.log
```

**To Reproduce**
Follow https://electronjs.org/docs/development/build-instructions-gn

**Comment by MarshallOfSound** [comment]
@Anrock You need to build the node headers

```bash
ninja -C out/Debug third_party/electron_node:headers
```

**Comment by Anrock** [comment]
@MarshallOfSound this step is listed in instructions and i did it. And i did it multiple times when runas failed. Just did it once again, got 
```
ninja: Entering directory `out/Debug'
ninja: no work to do.
```
and runas still fails.
Anything else i can try?

**Comment by MarshallOfSound** [comment]
@Anrock Oh I just realized that path looks a bit wrong, can you try

```bash
(cd electron/spec && npm i --nodedir=../../../out/Debug/gen/node_headers)
```

This path in your log `/Users/vladislav.shtepin/Projects/electron-gn/src/electron/spec/out/Debug/gen/node_headers/common.gypi`

should be

`/Users/vladislav.shtepin/Projects/electron-gn/src/out/Debug/gen/node_headers/common.gypi`

**Comment by Anrock** [comment]
@MarshallOfSound didn't work. Strangely, there's no common.gypi there. It's actually in out/Debug/gen/node_headers/include/node
```
$ tree out/Debug/gen/node_headers
out/Debug/gen/node_headers
└── include
    └── node
        ├── common.gypi
        ├── config.gypi
        ├── libplatform
        │   ├── libplatform-export.h
        │   ├── libplatform.h
        │   └── v8-tracing.h
        ├── node.h
        ├── node_api.h
        ├── node_api_types.h
        ├── node_buffer.h
        ├── node_object_wrap.h
        ├── node_version.h
        ├── uv
        │   ├── aix.h
        │   ├── android-ifaddrs.h
        │   ├── bsd.h
        │   ├── darwin.h
        │   ├── errno.h
        │   ├── linux.h
        │   ├── os390.h
        │   ├── posix.h
        │   ├── pthread-barrier.h
        │   ├── stdint-msvc2008.h
        │   ├── sunos.h
        │   ├── threadpool.h
        │   ├── tree.h
        │   ├── unix.h
        │   ├── version.h
        │   └── win.h
        ├── uv.h
        ├── v8-inspector-protocol.h
        ├── v8-inspector.h
        ├── v8-platform.h
        ├── v8-profiler.h
        ├── v8-testing.h
        ├── v8-util.h
        ├── v8-value-serializer-version.h
        ├── v8-version-string.h
        ├── v8-version.h
        ├── v8.h
        ├── v8config.h
        ├── zconf.h
        └── zlib.h
```

Pointing to it still produces same error though:
```
$ (cd electron/spec && file ../../out/Debug/gen/node_headers/include/node/common.gypi)
../../out/Debug/gen/node_headers/include/node/common.gypi: ASCII text
$ (cd electron/spec && npm i --nodedir=../../out/Debug/gen/node_headers/include/node)

> runas@3.1.1 install /Users/vladislav.shtepin/Projects/electron-gn/src/electron/spec/node_modules/runas
> node-gyp rebuild

gyp: /Users/vladislav.shtepin/Projects/electron-gn/src/electron/spec/out/Debug/gen/node_headers/include/node/common.gypi not found (cwd: /Users/vladislav.shtepin/Projects/electron-gn/src/electron/spec/node_modules/runas) while reading includes of binding.gyp while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/Users/vladislav.shtepin/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/Users/vladislav.shtepin/.nvm/versions/node/v8.9.4/bin/node" "/Users/vladislav.shtepin/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/vladislav.shtepin/Projects/electron-gn/src/electron/spec/node_modules/runas
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN electron-test@0.1.0 No description
npm WARN electron-test@0.1.0 No repository field.
npm WARN electron-test@0.1.0 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: abstract-socket@2.0.0 (node_modules/abstract-socket):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for abstract-socket@2.0.0: wanted {"os":"linux","arch":"any"} (current: {"os":"darwin","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! runas@3.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the runas@3.1.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/vladislav.shtepin/.npm/_logs/2018-10-01T13_30_40_696Z-debug.log
```

However using absolute paths seems to fix this error and introduce another one:
```
$ COMMON_GYPI_DIR=~/Projects/electron-gn/src/out/Debug/gen/node_headers/include/node
$ (cd electron/spec && npm i --nodedir=$COMMON_GYPI_DIR)

> runas@3.1.1 install /Users/vladislav.shtepin/Projects/electron-gn/src/electron/spec/node_modules/runas
> node-gyp rebuild

  CXX(target) Release/obj.target/runas/src/main.o
In file included from ../src/main.cc:1:
../../nan/nan.h:24:10: fatal error: 'node_version.h' file not found
#include <node_version.h>
         ^~~~~~~~~~~~~~~~
1 error generated.
make: *** [Release/obj.target/runas/src/main.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/vladislav.shtepin/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:126:13)
gyp ERR! stack     at ChildProcess.emit (events.js:214:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:198:12)
gyp ERR! System Darwin 17.7.0
gyp ERR! command "/Users/vladislav.shtepin/.nvm/versions/node/v8.9.4/bin/node" "/Users/vladislav.shtepin/.nvm/versions/node/v8.9.4/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/vladislav.shtepin/Projects/electron-gn/src/electron/spec/node_modules/runas
gyp ERR! node -v v8.9.4
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN electron-test@0.1.0 No description
npm WARN electron-test@0.1.0 No repository field.
npm WARN electron-test@0.1.0 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: abstract-socket@2.0.0 (node_modules/abstract-socket):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for abstract-socket@2.0.0: wanted {"os":"linux","arch":"any"} (current: {"os":"darwin","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! runas@3.1.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the runas@3.1.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/vladislav.shtepin/.npm/_logs/2018-10-01T13_35_12_031Z-debug.log
```

**Comment by MarshallOfSound** [comment]
@Anrock Have you tried if our `npm test` command works?  It should do all this path stuff for you

**Comment by Anrock** [comment]
@MarshallOfSound just tried, npm test works. So why docs then advice to run this brittle command instead of npm test?

**Comment by MarshallOfSound** [comment]
@Anrock `npm test` uses `spec-runner.js` which is a script I wrote after these docs were written 😄 Looks like a docs update is all that is needed 👍

**Comment by Anrock** [comment]
@MarshallOfSound not sure, but looks like after running npm test and building node headers i can no longer compile electron. Running `ninja -C out/Debug` fails shortly after start with
```
ninja -C out/Debug
ninja: Entering directory `out/Debug'
[74/28649] LINK ./gcapi_example
FAILED: gcapi_example
TOOL_VERSION=1538044926 ../../build/toolchain/mac/linker_driver.py ../../third_party/llvm-build/Release+Asserts/bin/clang++  -stdlib=libc++ -arch x86_64 -segprot PROTECTED_MEMORY rw r -Werror -Wl,-ObjC -Wl,-rpath,@loader_path/. -Wl,-rpath,@loader_path/../../.. -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.5 -o "./gcapi_example" -Wl,-filelist,"./gcapi_example.rsp"  -framework Cocoa
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Traceback (most recent call last):
  File "../../build/toolchain/mac/linker_driver.py", line 229, in <module>
    Main(sys.argv)
  File "../../build/toolchain/mac/linker_driver.py", line 79, in Main
    subprocess.check_call(compiler_driver_args)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['../../third_party/llvm-build/Release+Asserts/bin/clang++', '-stdlib=libc++', '-arch', 'x86_64', '-segprot', 'PROTECTED_MEMORY', 'rw', 'r', '-Werror', '-Wl,-ObjC', '-Wl,-rpath,@loader_path/.', '-Wl,-rpath,@loader_path/../../..', '-isysroot', '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk', '-mmacosx-version-min=10.5', '-o', './gcapi_example', '-Wl,-filelist,./gcapi_example.rsp', '-framework', 'Cocoa']' returned non-zero exit status 1
[83/28649] ACTION //base:base_nocompile_tests_run_nocompile(//build/toolchain/mac:clang_x64)
ninja: build stopped: subcommand failed.
```
Can this be related or should i file a new issue?
