### ISSUE TITLE
Master not buildable: ld: library not found for -lgcc_s.10.5

### ISSUE THREAD

**Issue by Anrock** [electron/electron#14943]
* Output of `node_modules/.bin/electron --version`: master  at e06bc311a9456fc557556728aee00404903c4baa
* Operating System (Platform and Version): OSX 10.13.6

**Expected Behavior**
`ninja -C ./out/Debug` builds electron

**Actual behavior**
Build errors out with:
```
ninja: Entering directory `./out/Debug'
[37/28569] LINK ./gcapi_example
FAILED: gcapi_example
TOOL_VERSION=1538044926 ../../build/toolchain/mac/linker_driver.py ../../third_party/llvm-build/Release+Asserts/bin/clang++  -stdlib=libc++ -arch x86_64 -segprot PROTECTED_MEMORY rw r -Werror -Wl,-ObjC -Wl,-rpath,@loader_path/. -Wl,-rpath,@loader_path/../../.. -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk -mmacosx-version-min=10.5 -o "./gcapi_example" -Wl,-filelist,"./gcapi_example.rsp"  -framework Cocoa
ld: library not found for -lgcc_s.10.5
clang: error: linker command failed with exit code 1 (use -v to see invocation)
Traceback (most recent call last):
  File "../../build/toolchain/mac/linker_driver.py", line 229, in <module>
    Main(sys.argv)
  File "../../build/toolchain/mac/linker_driver.py", line 79, in Main
    subprocess.check_call(compiler_driver_args)
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['../../third_party/llvm-build/Release+Asserts/bin/clang++', '-stdlib=libc++', '-arch', 'x86_64', '-segprot', 'PROTECTED_MEMORY', 'rw', 'r', '-Werror', '-Wl,-ObjC', '-Wl,-rpath,@loader_path/.', '-Wl,-rpath,@loader_path/../../..', '-isysroot', '/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk', '-mmacosx-version-min=10.5', '-o', './gcapi_example', '-Wl,-filelist,./gcapi_example.rsp', '-framework', 'Cocoa']' returned non-zero exit status 1
[46/28567] CXX obj/printing/test_support/test_print_backend.o
ninja: build stopped: subcommand failed.
```

**To Reproduce**
Follow https://electronjs.org/docs/development/build-instructions-gn

**Comment by nornagon** [comment]
You're trying to build all of chromium in addition to electron. You need to specify `electron` as the target to build:

```sh
$ ninja -C out/Debug electron
```

**Comment by Anrock** [comment]
Thanks. I guess we're in a dire need of some hassle-free wrapper scripts.
