### ISSUE TITLE
npm install does not work

### ISSUE THREAD

**Issue by chamerling** [electron/electron#15393]
* Output of `node_modules/.bin/electron --version`: Nothing, can't install but wanted to install latest and older
* Operating System (Platform and Version): OS X 10.13

**Expected Behavior**

Have a fresh electron in my node_modules

**Actual behavior**

Can not install

```
npm install electron@latest

> electron@3.0.6 postinstall /Users/chamerling/src/chamerling/foobar/node_modules/electron
> node install.js

Downloading tmp-17067-0-electron-v3.0.6-darwin-x64.zip
Error: getaddrinfo ENOTFOUND github-production-release-asset-2e65be.s3.amazonaws.com github-production-release-asset-2e65be.s3.amazonaws.com:443
/Users/chamerling/src/chamerling/foobar/node_modules/electron/install.js:49
  throw err
  ^

Error: getaddrinfo ENOTFOUND github-production-release-asset-2e65be.s3.amazonaws.com github-production-release-asset-2e65be.s3.amazonaws.com:443
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:58:26)
npm WARN babel-loader@8.0.4 requires a peer of @babel/core@^7.0.0 but none is installed. You must install peer dependencies yourself.
```

**To Reproduce**

`npm install electron`

```

**Comment by chamerling** [comment]
Seems to be fixed now

**Comment by AhmedMKamal** [comment]
I'm facing the same issue here

```
> electron@8.0.1 postinstall E:\WorkSpace\Projects\temp\Angular Electron\node_modules\electron
> node install.js

(node:10840) UnhandledPromiseRejectionWarning: RequestError: getaddrinfo ENOTFOUND github-production-release-asset-2e65be.s3.amazonaws.com
    at ClientRequest.<anonymous> (E:\WorkSpace\Projects\temp\Angular Electron\node_modules\got\source\request-as-event-emitter.js:178:14)
    at Object.onceWrapper (events.js:300:26)
    at ClientRequest.emit (events.js:215:7)
    at ClientRequest.origin.emit (E:\WorkSpace\Projects\temp\Angular Electron\node_modules\@szmarczak\http-timer\source\index.js:37:11)
    at TLSSocket.socketErrorListener (_http_client.js:407:9)
    at TLSSocket.emit (events.js:210:5)
    at emitErrorNT (internal/streams/destroy.js:84:8)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(node:10840) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10840) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by canserkanuren** [comment]
Any update on this ?
