### ISSUE TITLE
electron 3.0.5 window.setTitle sometimes fails with "missing remote object 1"

### ISSUE THREAD

**Issue by starpit** [electron/electron#15429]
* Output of `node_modules/.bin/electron --version`: 3.0.5
* Operating System (Platform and Version): travis ubuntu 14
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): the 2 series does not seem to have this issue

**Expected Behavior**
window.setTitle, when issued on did-finish-load, should always succeed

**Actual behavior**
With electron 3.0, we are seeing spurious failures.

```javascript
    unknown error: Cannot call function 'setTitle' on missing remote object 1
Error: Cannot call function 'setTitle' on missing remote object 1
    at throwRPCError (/home/travis/build/.../electron.asar/browser/rpc-server.js:145:17)
    at EventEmitter.<anonymous> (/home/travis/build/.../electron.asar/browser/rpc-server.js:357:7)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (/home/travis/build/.../electron.asar/browser/api/web-contents.js:293:13)
    at WebContents.emit (events.js:182:13)
  Error: An unknown server-side error occurred while processing the command.
      at execute(<Function>, "setTitle", Create an action with limits, using let, "require") - api.js:300:19
```

**To Reproduce**
We will see if we can bottle up this issue

**Screenshots**

**Additional Information**

**Comment by starpit** [comment]
hmm, this might be a spectron issue (running spectron 5.0)...

**Comment by MarshallOfSound** [comment]
Duplicate #14965 (same underlying issue)
