### ISSUE TITLE
Unable to use native module vscode-nsfw  with Electron 4.0.0-beta.5

### ISSUE THREAD

**Issue by bpasero** [electron/electron#15436]
* Output of `node_modules/.bin/electron --version`: 4.0.5-beta.5
* Operating System (Platform and Version): Windows 10
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): 3.0.6

**Expected Behavior**
A native module works when compiled against Electron.

**Actual behavior**
A native module `vscode-nsfw` when required throws the following error:

```
Error: The specified module could not be found.
\\?\C:\Users\bpasero\Desktop\vscode-nsfw\node_modules\vscode-nsfw\build\Release\nsfw.node
```

**To Reproduce**
* setup a `.yarnrc` file with belows contents
```ini
disturl "https://atom.io/download/electron"
target "4.0.0-beta.5"
runtime "electron"
```
* add a dependency to `package.json`: `"vscode-nsfw": "*"`
* run `yarn`
* require `vscode-nsfw` in the electron app
* get the error

When I follow the same steps by compiling this module against a globally installed `node.js 10.11.0` (the same as `Electron 4.0.0-beta.5`) I can successfully load the module. As such I assume that it is not the modules fault here.

**Comment by MarshallOfSound** [comment]
@bpasero Is it only this module or all vscode native modules?  We have tests for native modules so it's probably something specific to this one

**Comment by bpasero** [comment]
@MarshallOfSound yeah all of our other modules seem to work just fine.

**Comment by MarshallOfSound** [comment]
I don't see anything to suspect in the `binding.gyp` and don't have a windows machine on hand to test.

refs: https://github.com/Axosoft/nsfw/blob/master/binding.gyp

**Comment by bpasero** [comment]
Also I should mention, the file `nsfw.node` does exist on disk (even though the error message seems to indicate something different). And there are no build errors, just warnings.

**Comment by MarshallOfSound** [comment]
@bpasero Can you try renaming `electron.exe` to `node.exe` and see if it loads?

**Comment by bpasero** [comment]
@MarshallOfSound does not look like it helped (I used the same module that I compiled previously but renamed electron.exe to node.exe):

![image](https://user-images.githubusercontent.com/900690/47674217-1b667e00-dbb7-11e8-9431-b23283c0159f.png)

**Comment by nornagon** [comment]
`the specified procedure could not be found` and `the specified module could not be found` are different errors.

It looks like there might be an issue with the delay_load hook that node-gyp implements. Can you confirm that:

1. the module is linked with `/DELAYLOAD:node.exe`
2. `win_delay_load_hook.cc` is built as part of the module

**Comment by bpasero** [comment]
@nornagon here is the output from building:

```
verbose 11.841 C:\Users\bpasero\Desktop\vscode-nsfw\node_modules\vscode-nsfw>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-
in\node-gyp.js" rebuild )  else (node "" rebuild )                                                                                                                                                        
gyp info it worked if it ends with ok                                                                                                                                                                     
gyp info using node-gyp@3.8.0                                                                                                                                                                             
gyp info using node@10.11.0 | win32 | x64                                                                                                                                                                 
gyp info spawn C:\Python27\python.EXE                                                                                                                                                                     
gyp info spawn args [ 'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',                                                                                           
gyp info spawn args   'binding.gyp',                                                                                                                                                                      
gyp info spawn args   '-f',                                                                                                                                                                               
gyp info spawn args   'msvs',                                                                                                                                                                             
gyp info spawn args   '-G',                                                                                                                                                                               
gyp info spawn args   'msvs_version=auto',                                                                                                                                                                
gyp info spawn args   '-I',                                                                                                                                                                               
gyp info spawn args   'C:\\Users\\bpasero\\Desktop\\vscode-nsfw\\node_modules\\vscode-nsfw\\build\\config.gypi',                                                                                          
gyp info spawn args   '-I',                                                                                                                                                                               
gyp info spawn args   'C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\addon.gypi',                                                                                                 
gyp info spawn args   '-I',                                                                                                                                                                               
gyp info spawn args   'C:\\Users\\bpasero\\.node-gyp\\4.0.0-beta.5\\include\\node\\common.gypi',                                                                                                          
gyp info spawn args   '-Dlibrary=shared_library',                                                                                                                                                         
gyp info spawn args   '-Dvisibility=default',                                                                                                                                                             
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\bpasero\\.node-gyp\\4.0.0-beta.5',                                                                                                                      
gyp info spawn args   '-Dnode_gyp_dir=C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp',                                                                                              
gyp info spawn args   '-Dnode_lib_file=C:\\Users\\bpasero\\.node-gyp\\4.0.0-beta.5\\<(target_arch)\\node.lib',                                                                                            
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\bpasero\\Desktop\\vscode-nsfw\\node_modules\\vscode-nsfw',                                                                                            
gyp info spawn args   '-Dnode_engine=v8',                                                                                                                                                                 
gyp info spawn args   '--depth=.',                                                                                                                                                                        
gyp info spawn args   '--no-parallel',                                                                                                                                                                    
gyp info spawn args   '--generator-output',                                                                                                                                                               
gyp info spawn args   'C:\\Users\\bpasero\\Desktop\\vscode-nsfw\\node_modules\\vscode-nsfw\\build',                                                                                                       
gyp info spawn args   '-Goutput_dir=.' ]                                                                                                                                                                  
gyp info spawn C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe                                                                                                                                        
gyp info spawn args [ 'build/binding.sln',                                                                                                                                                                
gyp info spawn args   '/clp:Verbosity=minimal',                                                                                                                                                           
gyp info spawn args   '/nologo',                                                                                                                                                                          
gyp info spawn args   '/p:Configuration=Release;Platform=x64' ]                                                                                                                                           
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.                                                                                               
  NSFW.cpp                                                                                                                                                                                                
  Queue.cpp                                                                                                                                                                                               
  NativeInterface.cpp                                                                                                                                                                                     
  Controller.cpp                                                                                                                                                                                          
  Watcher.cpp                                                                                                                                                                                             
..\src\NSFW.cpp(56): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\Users\bpasero\Desktop\vscode-nsfw\node_modules\vscode-nsfw\build\nsfw.vcxproj]                                     
  C:\Users\bpasero\Desktop\vscode-nsfw\node_modules\nan\nan.h(1655): note: see declaration of 'Nan::Callback::Call'                                                                                       
..\src\NSFW.cpp(98): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\Users\bpasero\Desktop\vscode-nsfw\node_modules\vscode-nsfw\build\nsfw.vcxproj]                                     
  C:\Users\bpasero\Desktop\vscode-nsfw\node_modules\nan\nan.h(1655): note: see declaration of 'Nan::Callback::Call'                                                                                       
..\src\NSFW.cpp(212): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\Users\bpasero\Desktop\vscode-nsfw\node_modules\vscode-nsfw\build\nsfw.vcxproj]                                    
  C:\Users\bpasero\Desktop\vscode-nsfw\node_modules\nan\nan.h(1655): note: see declaration of 'Nan::Callback::Call'                                                                                       
..\src\NSFW.cpp(258): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\Users\bpasero\Desktop\vscode-nsfw\node_modules\vscode-nsfw\build\nsfw.vcxproj]                                    
  C:\Users\bpasero\Desktop\vscode-nsfw\node_modules\nan\nan.h(1655): note: see declaration of 'Nan::Callback::Call'                                                                                       
..\src\NSFW.cpp(260): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\Users\bpasero\Desktop\vscode-nsfw\node_modules\vscode-nsfw\build\nsfw.vcxproj]                                    
  C:\Users\bpasero\Desktop\vscode-nsfw\node_modules\nan\nan.h(1655): note: see declaration of 'Nan::Callback::Call'                                                                                       
..\src\NSFW.cpp(285): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\Users\bpasero\Desktop\vscode-nsfw\node_modules\vscode-nsfw\build\nsfw.vcxproj]                                    
  C:\Users\bpasero\Desktop\vscode-nsfw\node_modules\nan\nan.h(1655): note: see declaration of 'Nan::Callback::Call'                                                                                       
..\src\NSFW.cpp(327): warning C4996: 'Nan::Callback::Call': was declared deprecated [C:\Users\bpasero\Desktop\vscode-nsfw\node_modules\vscode-nsfw\build\nsfw.vcxproj]                                    
  C:\Users\bpasero\Desktop\vscode-nsfw\node_modules\nan\nan.h(1655): note: see declaration of 'Nan::Callback::Call'                                                                                       
     Creating library C:\Users\bpasero\Desktop\vscode-nsfw\node_modules\vscode-nsfw\build\Release\nsfw.lib and object C:\Users\bpasero\Desktop\vscode-nsfw\node_modules\vscode-nsfw\build\Release\nsfw.exp
  Generating code                                                                                                                                                                                         
  All 1285 functions were compiled because no usable IPDB/IOBJ from previous compilation was found.                                                                                                       
  Finished generating code                                                                                                                                                                                
  nsfw.vcxproj -> C:\Users\bpasero\Desktop\vscode-nsfw\node_modules\vscode-nsfw\build\Release\\nsfw.node                                                                                                  
  nsfw.vcxproj -> C:\Users\bpasero\Desktop\vscode-nsfw\node_modules\vscode-nsfw\build\Release\nsfw.pdb (Full PDB)                                                                                         
gyp info ok                                                                                                                                                                                               
success Saved lockfile.                                                                                                                                                                                   
Done in 11.65s.    
```

**Comment by deepak1556** [comment]
@bpasero the module is built without `win_delay_load_hook` https://github.com/Axosoft/nsfw/blob/master/binding.gyp#L13

**Comment by bpasero** [comment]
@deepak1556 interesting, may I ask what the background of this is if you are aware? Why would you disable this in the build and why is it making a difference in Electron?

**Comment by MarshallOfSound** [comment]
@bpasero Without the delay hook it will try to run against `node.exe`, the delay hook allows `node-gyp` to inject some logic to reroute the `LoadLibrary` call to the current executable.  This is what allows you to use renamed `electron.exe` binaries (and in fact `electron.exe` in the first place).

**Comment by bpasero** [comment]
@MarshallOfSound is this something that should maybe be documented? It seems this is a new requirement since Electron 4.0.x?

**Comment by bpasero** [comment]
Actually I just tried to recompile with the `win_delay_load_hook` line removed from `binding.gyp` and I am still seeing an error:

![image](https://user-images.githubusercontent.com/900690/47715932-86f52d80-dc41-11e8-8c94-a2b0e1f1b44d.png)

**Comment by bpasero** [comment]
I should add that this module gets loaded in a forked process from the renderer (so it will be loaded in an environment `RUN_AS_NODE`).

**Comment by nornagon** [comment]
Yes, this changed in 4.0.0 because in 4.0.0 we build as a single static executable, not as `electron.exe` + `node.dll`. Previously, native modules were linked against `node.dll`, but that dll no longer exists. So we have to do some trickery to make native modules work.

Unfortunately the build output you pasted does not show the link command, so I can't tell if it's correctly linking with `/DELAYLOAD:node.lib`. Can you add more `--verbose` flags (possibly to the node-gyp invocation itself) and try again?

I don't think `RUN_AS_NODE` should make a difference here.

**Comment by bpasero** [comment]
Btw I noticed that if I compile `vscode-nsfw` with `"win_delay_load_hook": "true"` and try to load the module on macOS, I am getting this error:

```
Uncaught Exception:
Error: Cannot find module '/Users/bpasero/Desktop/nodemodule/node_modules/vscode-nsfw'
    at Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
    at Function.Module._resolveFilename (/Users/bpasero/Library/Application Support/Electron Fiddle/electron-bin/4.0.0-beta.5/Electron.app/Contents/Resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.Module._load (internal/modules/cjs/loader.js:510:25)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/private/var/folders/rp/xjpqwtvs1q1gg1bb8ww0mtxr0000gn/T/tmp-50541A0diyk0o3sbZ/main.js:6:13)
    at Object.<anonymous> (/private/var/folders/rp/xjpqwtvs1q1gg1bb8ww0mtxr0000gn/T/tmp-50541A0diyk0o3sbZ/main.js:55:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
```

So I think changing the `binding.gyp` is not an option for macOS/Linux at least.

**Comment by bpasero** [comment]
Oh, I believe that this is exactly what I see on Windows too when I changed the module to include the hook. So now on all platforms the module cannot be loaded anymore it seems. Are there other changes required so that a native module can build with `"win_delay_load_hook": "true"`?

**Comment by bpasero** [comment]
Actually this might be a red herring, because there seems to be a difference if you depend on the module from NPM or a GitHub branch (I only tested GitHub branch).

**Comment by rhwu** [comment]
We had similar issue when using https://github.com/jitsi/jitsi-meet-electron-utils with electron 4.0.0. Switch electron back to 3.0.7 solves the problem.

Hope this helps to identify the issue.

**Comment by bpasero** [comment]
I was able to solve this problem by removing the following line from `binding.gyp`:

`win_delay_load_hook: false`

The "module not found" issue was unrelated and only appeared because I depended on a GitHub branch directly via `package.json` instead of publishing a new version with this change (which is needed to trigger some file operations that are required as part of the `prepublish` step). 

Sorry for the confusion and thanks for the help!

**Comment by nornagon** [comment]
Good to know, we should add a note to the 4.x release notes indicating that delay load hooks are required to be enabled.

**Comment by MarshallOfSound** [comment]
> Good to know, we should add a note to the 4.x release notes indicating that delay load hooks are required to be enabled.

Should probably be added to our native module guide as well 👍
