### ISSUE TITLE
Error in installing electron on Linux On Power machine.

### ISSUE THREAD

**Issue by munish-usit** [electron/electron#15450]
I have successfully installed Node js but getting an error while installing electron on LOP(ppc64le) machine. 

Operating System -- Linux on Power (ppc64le)

Steps:
1. Install Node Js (ppc64) version.
2. Run command -- npm install electron --save-dev

-------------------------------------------------------------------------------------------------------------------
Error:

Error: Failed to find Electron v3.0.6 for linux-ppc64 at https://github.com/electron/electron/releases/download/v3.0.6/electron-v3.0.6-linux-ppc64.zip
    at Request.<anonymous> (/home/smunish/.npm/_npx/2910/lib/node_modules/electron/node_modules/nugget/index.js:169:61)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at Request.onRequestResponse (/home/smunish/.npm/_npx/2910/lib/node_modules/electron/node_modules/request/request.js:1066:10)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:544:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:117:17)
    at TLSSocket.socketOnData (_http_client.js:440:20)
    at emitOne (events.js:116:13)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@3.0.6 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron@3.0.6 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by MarshallOfSound** [comment]
@munish-usit Electron does not support the `ppc64` arch.  We currently only support `x64`, `ia32`, `arm64` and `armv7l`.

**Comment by munish-usit** [comment]
@MarshallOfSound  Does your team have any plan to support ppc64 arch in future?
