### ISSUE TITLE
[Question] Can't load native module on manually-built electron

### ISSUE THREAD

**Issue by orange4glace** [electron/electron#15473]
Hi. I'm stuck on some issue with native module and electron (N-API) , so I need to debug electron itself.
I built a latest nightly electron build with following [instructions](https://github.com/electron/electron/blob/master/docs/development/build-instructions-gn.md) on Windows 10.
Build with debug configuration was successful with no error.
But when I run an electron app with my own electron build,  it ends up with following error. (`out/Debug/electron.exe [path-to-my-app]`)
```
App threw an error during load
Error: The specified procedure could not be found.
\\?\C:\Users\orang\Downloads\webgl_external_arraybuffer_bug\build\Release\NODE_GYP_MODULE_NAME.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:160:31)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\orang\Downloads\webgl_external_arraybuffer_bug\main.js:5:17)
    at Object.<anonymous> (C:\Users\orang\Downloads\webgl_external_arraybuffer_bug\main.js:20:3)
```

The version of the electron I built is 4.0.0-nightly-20181010 and I build my native module with following command which is `HOME=~/.electron-gyp node-gyp configure build --target=4.0.0-nightly.20181010 --arch=x64 --dist-url=https://atom.io/download/electron`.

The module works normally when it is run with npm version of electron with same version.

Anyone has an idea? Thanks.

**Comment by MarshallOfSound** [comment]
@orange4glace You can't load native modules on a debug build of Electron, you need to build it in release mode 👍

**Comment by orange4glace** [comment]
Oh, I have to debug it with release mode? that's awful :o
Thanks!

**Comment by orange4glace** [comment]
@MarshallOfSound Just for curious, I have to debug Blink part, how can I print a log properly? Is std::out ok with it or is there any better way like using chromium's own logging? (It would be appreciate with a snippet if there's any :D)

**Comment by MarshallOfSound** [comment]
@orange4glace You can log from any cpp file with

```cpp
LOG(ERROR) << "This is my log"
```
