### ISSUE TITLE
'cannot set property 'domain' of null'

### ISSUE THREAD

**Issue by pashvin** [electron/electron#15980]
We have one recent report from our customer about this issue.
Don't know how to reproduce the issue yet.

Electron version is 2.x

Tue Dec 04 2018 12:05:37 GMT-0500 (EST) TypeError: Cannot set property 'domain' of null
at EventEmitter.init (events.js:63:15)
at EventEmitter (events.js:28:21)
at Object. (/Applications/Mitel Teamwork.app/Contents/Resources/electron.asar/browser/api/screen.js:7:14)
at Object. (/Applications/Mitel Teamwork.app/Contents/Resources/electron.asar/browser/api/screen.js:19:3)
at Module._compile (module.js:642:30)
at Object.Module._extensions..js (module.js:653:10)
at Module.load (module.js:561:32)
at tryModuleLoad (module.js:504:12)
at Function.Module._load (module.js:496:3)
at Module.require (module.js:586:17)

**Comment by pashvin** [comment]
I don't know how to reproduce yet but putting some check on domain property may stop javascript crash.

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

We cannot move forward without steps to reproduce with [electron-quick-start](https://github.com/electron/electron-quick-start). 

We would be happy to reopen this issue when you find a way to reproduce this issue.

**Comment by pashvin** [comment]
There not always step to reproduce it. But you should at least do code review and check if there are possible condition to make some object null and it is trying to access null object. The crash report has clear code line number so closing without any investigation is really not helping.

**Comment by vsvipul** [comment]
Facing similar problems [here](https://github.com/zulip/zulip-electron/issues/737). Should be reopened, i guess.
