### ISSUE TITLE
Electron 4.0.0-beta.10 does not start

### ISSUE THREAD

**Issue by tommoor** [electron/electron#16115]
version (if applicable): Electron 4.0.0-beta.10

**Expected Behavior**
Electron should start

**Actual behavior**
An error is output from Node:

```
internal/validators.js:125
    throw new ERR_INVALID_ARG_TYPE(name, 'string', value);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "file" argument must be of type string. Received type object
    at validateString (internal/validators.js:125:11)
    at normalizeSpawnArguments (child_process.js:399:3)
    at Object.spawn (child_process.js:532:38)
    at Object.<anonymous> (/Users/tom/abstract/ui-electron-3/desktop/node_modules/electron/cli.js:7:18)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
```

**To Reproduce**
This seems to reproduce just by attempting to use the latest beta release and was caused by this commit: https://github.com/electron/electron/commit/eb8fcf833c1e898206d183a8b4a415cd487179c5 in this PR https://github.com/electron/electron/pull/15916

**Additional Information**

Calling `electron.toString()` here seems to resolve the issue https://github.com/electron/electron/blob/master/npm/cli.js#L7

**Comment by MarshallOfSound** [comment]
> it seems that a new String is not recognized as a "string" by Node's spawn.

That is... unfortunate 😢

**Comment by anker2000** [comment]
I'm getting the same error

**Comment by silverspex** [comment]
I get the same error after updating to beta 10. No changes to package.json or anything else.

**Comment by Stoyvo** [comment]
Also experiencing an issue. Possibly related to node integration for upcoming v5?

**Comment by tommoor** [comment]
The fix has landed, it'll be going out in beta 11 soon

https://github.com/electron/electron/pull/16118
