### ISSUE TITLE
app throwing error when run the command NPM RUN ELECTRON

### ISSUE THREAD

**Issue by vamsideepak** [electron/electron#16145]
App threw an error during load
Error: A dynamic link library (DLL) initialization routine failed.
\\?\C:\Users\admin\Desktop\electron\electron-app\node_modules\java\build\Release\nodejavabridge_bindings.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:740:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:166:20)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at Module.require (internal/modules/cjs/loader.js:658:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (C:\Users\admin\Desktop\electron\electron-app\node_modules\java\lib\nodeJavaBridge.js:21:16)
    at Object.<anonymous> (C:\Users\admin\Desktop\electron\electron-app\node_modules\java\lib\nodeJavaBridge.js:316:3)

**Comment by sofianguy** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
