### ISSUE TITLE
openpgp in 4.0 not working

### ISSUE THREAD

**Issue by jano-m** [electron/electron#16187]
* Output of `node_modules/.bin/electron --version`: v4.0.0
* Operating System (Platform and Version): win
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable): 3.1.0-beta.4

**Expected Behavior**
const openpgp = require('openpgp')
async function readKey() {
  let armored = await openpgp.key.readArmored(pubkey);
  console.log(armored);
  publicKeys = armored.keys;
}
readKey();
should print '{keys: [Object]}'

**Actual behavior**
It will print 
```
{ keys: [],
  err:
   [ TypeError: (var).countUse is not a function
         at Object.transformPair (C:\Users\Jan\Documents\editor\node_modules\openpgp\dist\openpgp.js:23051:20)
         at Promise (C:\Users\Jan\Documents\editor\node_modules\openpgp\dist\openpgp.js:29722:65)
         at new Promise (<anonymous>)
         at Object.dearmor [as decode] (C:\Users\Jan\Documents\editor\node_modules\openpgp\dist\openpgp.js:29710:10)
         at Object.readArmored (C:\Users\Jan\Documents\editor\node_modules\openpgp\dist\openpgp.js:32247:41)
         at readKey (C:\Users\Jan\Documents\editor\config\pgp.js:53:35)
         at Object.<anonymous> (C:\Users\Jan\Documents\editor\config\pgp.js:57:1)
         at Object.<anonymous> (C:\Users\Jan\Documents\editor\config\pgp.js:75:3)
         at Module._compile (internal/modules/cjs/loader.js:693:30)
         at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10) ] } 
```
instead. Note that countUse does not occur anywhere in openpgp package. It must come from Electron 4.0

**Comment by jano-m** [comment]
The latest version of openpgp: 4.3.0

**Comment by nornagon** [comment]
I suspect this is the same root cause as #16195 (i.e., that we switched from OpenSSL to BoringSSL). That's a somewhat weird error though. Can you include an example of a pubkey that causes the issue? the code as pasted isn't a complete repro.

**Comment by jano-m** [comment]
[electron-quick-start.zip](https://github.com/electron/electron/files/2722820/electron-quick-start.zip)
I have created a clone of electron-quick-start, generate new public key with gpg and added the problematic code at the beginning of main.js. Still the same problem. Attaching as a zip file.

**Comment by twiss** [comment]
This error comes from here: https://cs.chromium.org/chromium/src/third_party/blink/renderer/core/streams/TransformStream.js?q=%5C.countUse&sq=package:chromium&l=69&dr=C

**Comment by nornagon** [comment]
`new TransformStream()` in Electron 4.0.1 does not trigger any error on my machine.

**Comment by datenstau** [comment]
I've got this error in 4.0:
`Error: Error encrypting message: Unknown cipher
    at Cipheriv.createCipherBase (internal/crypto/cipher.js:79:18)
    at Cipheriv.createCipherWithIV (internal/crypto/cipher.js:119:20)
    at new Cipheriv (internal/crypto/cipher.js:225:22)
    at new createCipheriv (crypto.js:105:10)
    at nodeEncrypt ([...]/node_modules/openpgp/dist/openpgp.js:24159:21)
    at aesEncrypt ([...]/node_modules/openpgp/dist/openpgp.js:24121:12)
    at Object.encrypt ([...]/node_modules/openpgp/dist/openpgp.js:24056:14)
    at SymEncryptedSessionKey.encrypt ([...]/node_modules/openpgp/dist/openpgp.js:38643:49)`

Definitively a bug with BoringSSL. Node.js v8.12.0 and electron v3.0.4 work as expected.

**Comment by nornagon** [comment]
@datenstau can you tell what cipher it's trying to create? boringssl doesn't support every cipher that openssl does, but it does have the major ones. However, it doesn't support every alias for a cipher that openssl supports. It's quite possible that boringssl already supports the cipher you're trying to use, just under a different name.

**Comment by datenstau** [comment]
@nornagon openpgp is trying to use aes-256-cfb in this case.
