### ISSUE TITLE
Unable to use native module sharp with Electron 4.0.1

### ISSUE THREAD

**Issue by pupupu-land** [electron/electron#16344]
Output of node_modules/.bin/electron --version: 4.0.1
Operating System (Platform and Version): Windows 10
Output of node_modules/.bin/electron --version on last known working Electron version (if applicable): 3.0.7

**Expected Behavior**
A native module works when compiled against Electron.

**Actual behavior**
A native module sharp when required throws the following error:

```
Error: The specified module could not be found.
\\?\D:\pro\my\project\dmce-erp\client\node_modules\sharp\build\Release\sharp.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:160:31)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at bindings (D:\pro\my\project\dmce-erp\client\node_modules\bindings\bindings.js:84:48)
    at Object.<anonymous> (D:\pro\my\project\dmce-erp\client\node_modules\sharp\lib\constructor.js:10:34)
```

**To Reproduce**

setup a .yarnrc file with belows contents
disturl "https://atom.io/download/electron"
target "4.0.1"
runtime "electron"

add a dependency to package.json: "sharp": "^0.21.0"
run yarn
require sharp in the electron app
get the error

**sharp's binding.gyp**
`win_delay_load_hook` is not set to false, when I set `win_delay_load_hook=true`, still have this error

**Comment by MarshallOfSound** [comment]
See https://github.com/lovell/sharp/issues/1522 and https://github.com/lgeiger/node-abi/pull/55#issuecomment-452588421
