### ISSUE TITLE
Apps cannot be launched from \\.\ volume paths

### ISSUE THREAD

**Issue by Jotune** [electron/electron#16349]
Output of `node_modules/.bin/electron --version`: 6.5.0
Operating System : Windows 10 x64
Electron version:  4.0.1

**Actual behaviors**
I cannot start my app from a volume path. Let's say: `\\.\Volume{1df47f9b-1263-11e9-8722-f46d04fd6ee0}\myapp.exe`.

```
 fs.js:115
    throw err;
    ^

Error: EISDIR: illegal operation on a directory, lstat '\\.\Volume{1df47f9b-1263-11e9-8722-f46d04fd6ee0}\'
    at realpathSync (fs.js:1393:5)
    at Object.fs.realpathSync (ELECTRON_ASAR.js:318:24)
    at toRealPath (internal/modules/cjs/loader.js:205:13)
    at Function.Module._findPath (internal/modules/cjs/loader.js:271:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:25)
    at Function.Module._load (internal/modules/cjs/loader.js:510:25)
    at Function.Module.runMain (internal/modules/cjs/loader.js:746:12)
    at startup (internal/bootstrap/node.js:282:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:759:3)
```

**To Reproduce**
Get the volume path of your drive using `mountvol ` int the CMD and try to execute your electron app from it.

**Additional Information**

- I can run any other app from the volume path that is not electron.
- The app is bundled with electron-packager and works perfectly if started using the letter path `C:\myapp.exe`. 
- There is a similar issue at #7152 but I'm working with the latest node and electron.

**Comment by felixrieseberg** [comment]
I'm trying to understand how important this bug is, given that this surely never worked and we've never had any complaints. Why would you not just launch the app from a drive path?

**Comment by Jotune** [comment]
It works using NW.JS which uses Chromium and Node.js as well.
Electron.exe will resolve the path of the app / asar to load it. If the drive is not mapped, it can't execute the app. Changing this behavior may require a lot of work. As there is an alternative, it may not be important to fix this issue.
