### ISSUE TITLE
Cannot get property 'xxx' on missing remote object 59802

### ISSUE THREAD

**Issue by BigSteel** [electron/electron#16426]
* Output of `node_modules/.bin/electron --version`: 3.0.9
* Operating System (Platform and Version):mac and win10

The rendering process loads the object of the main process by ('electron').remote. The page sometimes has an uncaptured exception when it is refreshed.

Error message:Cannot get property 'proportion' on missing remote object 59802
Error: Cannot get property 'proportion' on missing remote object 59802
    at throwRPCError (F:\xxxxxx\node_modules\electron\dist\resources\electron.asar\browser\rpc-server.js:145:17)
    at EventEmitter.<anonymous> (F:\xxxxxx\node_modules\electron\dist\resources\electron.asar\browser\rpc-server.js:397:7)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (F:\xxxxxx\node_modules\electron\dist\resources\electron.asar\browser\api\web-contents.js:293:13)
    at WebContents.emit (events.js:182:13)
    at throwRPCError (F:\xxxxxx\node_modules\electron\dist\resources\electron.asar\browser\rpc-server.js:145:17)
    at EventEmitter.<anonymous> (F:\xxxxxx\node_modules\electron\dist\resources\electron.asar\browser\rpc-server.js:397:7)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (F:\xxxxxx\node_modules\electron\dist\resources\electron.asar\browser\api\web-contents.js:293:13)
    at WebContents.emit (events.js:182:13)
    at metaToException (F:\xxxxxx\node_modules\electron\dist\resources\electron.asar\renderer\api\remote.js:271:17)
    at Object.exception (F:\xxxxxx\node_modules\electron\dist\resources\electron.asar\renderer\api\remote.js:219:30)
    at metaToValue (F:\xxxxxx\node_modules\electron\dist\resources\electron.asar\renderer\api\remote.js:223:28)

**Comment by BigSteel** [comment]
I am using electron2.0.16 and will not encounter this problem.

**Comment by codebytere** [comment]
This has been fixed in latest versions of 3-1-x and later.
