### ISSUE TITLE
Electron 5.0.1

### ISSUE THREAD

**Issue by mike-seekwell** [electron/electron#16562]
* Output of `node_modules/.bin/electron --version`:
v5.0.0-beta.1
* Operating System (Platform and Version):
OS X 10.13.6
* Output of `node_modules/.bin/electron --version` on last known working Electron version (if applicable):
v4.0.1

**Actual behavior**
I'm getting the error below when attempting to upgrade to 5.0.0-beta.1
```
Error: Could not detect abi for version 5.0.0-beta.1 and runtime electron.  Updating "node-abi" might help solve this issue if it is a new release of electron
    at getAbi (/Users/mritchie712/seekwell/desktop/node_modules/prebuild-install/node_modules/node-abi/index.js:30:9)
    at module.exports (/Users/mritchie712/seekwell/desktop/node_modules/prebuild-install/rc.js:64:12)
    at Object.<anonymous> (/Users/mritchie712/seekwell/desktop/node_modules/prebuild-install/bin.js:8:25)
    at Module._compile (internal/modules/cjs/loader.js:722:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:733:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:775:12)
    at startup (internal/bootstrap/node.js:300:19)
```
**To Reproduce**
If you use the following package.json, you should get the error. I tried `sudo yarn add node-abi` (which got 2.5.1), but that did not help.

```
  "devDependencies": {
    "electron": "5.0.0-beta.1",
    "electron-builder": "^20.34.0",
    "electron-toolkit": "^1.0.24"
  },
  "dependencies": {
    "@google-cloud/logging-winston": "^0.10.2",
    "acorn": "^5.3.0",
    "asn1": "^0.2.3",
    "chokidar": "^2.0.0",
    "cuid": "^2.0.2",
    "electron-context-menu": "^0.9.1",
    "electron-debug": "^1.5.0",
    "electron-in-page-search": "^1.3.2",
    "electron-json-storage": "^3.1.0",
    "electron-unhandled": "^1.0.0",
    "electron-updater": "^4.0.5",
    "express": "^4.16.2",
    "fuzzball": "^0.14.0",
    "google-auth-library": "^0.12.0",
    "googleapis": "^23.0.0",
    "inject-tunnel-ssh": "^0.0.5",
    "keytar-prebuild": "^4.0.4",
    "moment": "^2.22.2",
    "moment-timezone": "^0.5.21",
    "mysql2": "^1.5.1",
    "node-abi": "^2.5.1",
    "node-pty": "^0.7.8",
    "pandas-js": "^0.2.4",
    "pg": "^7.3.0",
    "pg-hstore": "^2.3.2",
    "sequelize": "^4.8.4",
    "shortid": "^2.2.8",
    "snowflake-sdk": "mike-seekwell/snowflake-sdk#master",
    "stream-splitter": "^0.3.2",
    "tedious": "^2.3.1",
    "temp": "^0.8.3",
    "tern": "^0.21.0",
    "winston": "2.4.4",
    "winston-electron": "^0.2.0",
    "xterm": "^3.9.1"
  },
  "resolutions": {
    "asn1.js": "4.10.1",
    "asn1.js-rfc5280": "3.0.0",
    "asn1.js-rfc2560": "4.0.0",
    "parse-asn1": "5.1.1",
    "ocsp": "1.0.3"
  }

```

**Comment by nornagon** [comment]
Upgrade to node-abi 2.6.0.

**Comment by adeperio** [comment]
Im getting this issue at the moment. Upgrading node-api to 2.6.0 didnt work
