### ISSUE TITLE
Can't install Electron on FreeBSD

### ISSUE THREAD

**Issue by sailorsamoor** [electron/electron#16620]
Can't install Electron through npm. I have such log:

[sailorsamoor@twin ~/electron-quick-start]% npm install

> electron@4.0.3 postinstall /usr/home/sailorsamoor/electron-quick-start/node_modules/electron
> node install.js

Downloading tmp-40647-0-electron-v4.0.3-freebsd-x64.zip
Error: GET https://github.com/electron/electron/releases/download/v4.0.3/electron-v4.0.3-freebsd-x64.zip returned 404
/usr/home/sailorsamoor/electron-quick-start/node_modules/electron/install.js:49
  throw err
  ^

Error: Failed to find Electron v4.0.3 for freebsd-x64 at https://github.com/electron/electron/releases/download/v4.0.3/electron-v4.0.3-freebsd-x64.zip
    at Request.<anonymous> (/usr/home/sailorsamoor/electron-quick-start/node_modules/nugget/index.js:169:61)
    at Request.emit (events.js:182:13)
    at Request.onRequestResponse (/usr/home/sailorsamoor/electron-quick-start/node_modules/request/request.js:1066:10)
    at ClientRequest.emit (events.js:182:13)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:556:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
    at TLSSocket.socketOnData (_http_client.js:442:20)
    at TLSSocket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@4.0.3 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron@4.0.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/sailorsamoor/.npm/_logs/2019-01-30T19_09_04_529Z-debug.log

**Comment by nornagon** [comment]
We don't provide prebuilt binaries for freebsd, as we don't officially support that platform.

**Comment by anatoli26** [comment]
There's electron 4 in the ports for FreeBSD since end of May 2019 (https://www.freshports.org/devel/electron4/). Maybe this could be made to work now?
