### ISSUE TITLE
Flakey FATAL crash on Windows 32 bit tests

### ISSUE THREAD

**Issue by MarshallOfSound** [electron/electron#16753]
Electron Version: master (C72)

I believe this is crashing during the `BrowserWindow.restore() should restore the previous window size` spec

Example Build: https://windows-ci.electronjs.org/project/AppVeyor/electron-67iac/build/1.0.5413

```
[7600:0204/181948.870:FATAL:focus_controller.cc(238)] Check failed: rules_->CanFocusWindow(window, nullptr). 
Backtrace:
	logging::LogMessage::~LogMessage [0x033CEDF7+103]
	wm::FocusController::SetFocusedWindow [0x033B8DF2+124]
	wm::FocusController::ResetFocusWithinActiveWindow [0x033B8D5D+109]
	views::DesktopNativeWidgetAura::ClearNativeFocus [0x057F7902+50]
	views::View::OnFocus [0x045EA769+25]
	views::Button::OnFocus [0x057F068B+11]
	views::LabelButton::OnFocus [0x057D784B+11]
	views::View::Focus [0x045EA799+33]
	views::FocusManager::SetFocusedViewWithReason [0x045DCFCD+343]
	views::AccessiblePaneView::SetPaneFocus [0x057E4F4D+189]
	atom::MenuBar::SetPaneFocus [0x060A4348+88]
	views::AccessiblePaneView::SetPaneFocusAndFocusDefault [0x057E5069+25]
	views::FocusManager::RestoreFocusedView [0x045DD511+87]
	views::DesktopNativeWidgetAura::HandleActivationChanged [0x057F6587+191]
	views::HWNDMessageHandler::PostProcessActivateMessage [0x045F8E1F+133]
	views::HWNDMessageHandler::OnWndProc [0x045F7E56+326]
	gfx::WindowImpl::WndProc [0x0370146C+154]
	base::win::WrappedWindowProc<&gfx::WindowImpl::WndProc> [0x037012B0+80]
	CallNextHookEx [0x773F8E71+177]
	CallNextHookEx [0x773F90D1+785]
	CallNextHookEx [0x773F932C+1388]
	CallNextHookEx [0x773F9529+1897]
	KiUserCallbackDispatcher [0x77ED0666+54]
	RealGetWindowClassW [0x773FC30F+287]
	(No symbol) [0x716A3405]
	BufferedPaintUnInit [0x716D2A35+213]
	(No symbol) [0x716A33A3]
	(No symbol) [0x716A2E58]
	RealGetWindowClassW [0x773FC2A5+181]
	views::HWNDMessageHandler::OnSysCommand [0x045FC936+384]
	views::HWNDMessageHandler::_ProcessWindowMessage [0x045F8ADC+3172]
	views::HWNDMessageHandler::OnWndProc [0x045F7D89+121]
	gfx::WindowImpl::WndProc [0x0370146C+154]
	base::win::WrappedWindowProc<&gfx::WindowImpl::WndProc> [0x037012B0+80]
	CallNextHookEx [0x773F8E71+177]
	GetAncestor [0x773FAE9D+461]
	EndTask [0x774278E4+3028]
	SendMessageW [0x773FE8B9+313]
	views::HWNDMessageHandler::Restore [0x045F749A+24]
	mate::internal::Invoker<mate::internal::IndicesHolder<0>,int>::DispatchToCallback [0x0324C91A+56]
	mate::internal::Dispatcher<void __cdecl(atom::api::BrowserWindow *)>::DispatchToCallback [0x055034F5+117]
	v8::internal::FunctionCallbackArguments::Call [0x024A95A3+595]
	v8::internal::Builtins::InvokeApiFunction [0x02458505+5221]
	v8::internal::BuiltinArguments::BuiltinArguments [0x02456F1A+522]
	v8::internal::Builtin_HandleApiCall [0x02456B1B+107]
	Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_NoBuiltinExit [0x02F4A310+80]
	Builtins_InterpreterEntryTrampoline [0x02CC8042+642]
	Builtins_InterpreterEntryTrampoline [0x02CC8042+642]
	Builtins_InterpreterEntryTrampoline [0x02CC8042+642]
	Builtins_ArgumentsAdaptorTrampoline [0x02CB6800+160]
An error occurred inside the spec runner: Error: Electron tests failed with code 3221226525.
    at runElectronTests (C:\projects\src\electron\script\spec-runner.js:53:11)
    at main (C:\projects\src\electron\script\spec-runner.js:27:9)
    at process._tickCallback (internal/process/next_tick.js:68:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

**Comment by deepak1556** [comment]
This should have been fixed in master with https://github.com/electron/electron/pull/16581 , did this crash happen after that ?

**Comment by codebytere** [comment]
This no longer occurs and can be closed.
