### ISSUE TITLE
remote API is flaking on 5.0.x

### ISSUE THREAD

**Issue by MarshallOfSound** [electron/electron#17039]
The current `5-0-x` branch and `master` are experiencing random `remote` API failures again.  We should look into this and fix before 5.0 stable.

Example: https://circleci.com/gh/electron/electron/138325

**Comment by nornagon** [comment]
another flake, on master:
```
not ok 25 app module BrowserWindow events should emit remote-get-builtin event when remote.getBuiltin() is invoked
  Error: Cannot get property 'id' on missing remote object 76
      at throwRPCError (C:\projects\src\out\Default\resources\electron.asar\browser\rpc-server.js:149:19)
      at C:\projects\src\out\Default\resources\electron.asar\browser\rpc-server.js:400:9
      at EventEmitter.<anonymous> (C:\projects\src\out\Default\resources\electron.asar\browser\rpc-server.js:273:27)
      at EventEmitter.emit (events.js:188:13)
      at WebContents.<anonymous> (C:\projects\src\out\Default\resources\electron.asar\browser\api\web-contents.js:365:29)
      at WebContents.emit (events.js:188:13)
```

**Comment by MarshallOfSound** [comment]
Another one https://windows-ci.electronjs.org/project/AppVeyor/electron-9vmit/build/1.0.4452?fullLog=true

```
not ok 25 app module BrowserWindow events should emit remote-get-builtin event when remote.getBuiltin() is invoked
  Error: Cannot get property 'id' on missing remote object 76
      at throwRPCError (C:\projects\src\out\Default\resources\electron.asar\browser\rpc-server.js:149:19)
      at C:\projects\src\out\Default\resources\electron.asar\browser\rpc-server.js:400:9
      at EventEmitter.<anonymous> (C:\projects\src\out\Default\resources\electron.asar\browser\rpc-server.js:273:27)
      at EventEmitter.emit (events.js:188:13)
      at WebContents.<anonymous> (C:\projects\src\out\Default\resources\electron.asar\browser\api\web-contents.js:365:29)
      at WebContents.emit (events.js:188:13)
```

Interestingly the **exact same** id and test that @nornagon 's example is for.  If someone starts to look at this, that test on Windows seems like a solid place to start 👍
