### ISSUE TITLE
BrowserView example code from docs doesn't work

### ISSUE THREAD

**Issue by waffln** [electron/electron#17096]
* **Electron Version** (output of `node_modules/.bin/electron --version`):
  * 4.0.3
* **Operating System** (Platform and Version):
  * Windows 10 (1803)

### Expected Behavior
I expected the example to work. Not much more i can type here.

### Actual behavior
I received this error:
` App threw an error during load
Error: Cannot create BrowserWindow before app is ready
    at Object.<anonymous> (C:\Users\waffeln\Fast-Git\SmashScoreBoard\test.js:4:11)
    at Object.<anonymous> (C:\Users\waffeln\Fast-Git\SmashScoreBoard\test.js:17:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at loadApplicationPackage (C:\Users\waffeln\AppData\Roaming\npm\node_modules\electron\dist\resources\default_app.asar\main.js:119:12)
    at Object.<anonymous> (C:\Users\waffeln\AppData\Roaming\npm\node_modules\electron\dist\resources\default_app.asar\main.js:164:5)
    at Object.<anonymous> (C:\Users\waffeln\AppData\Roaming\npm\node_modules\electron\dist\resources\default_app.asar\main.js:204:3)`

### To Reproduce
Simply copy the example code to a fresh JavaScript file and run it using `electron file.js`

**Comment by waffln** [comment]
I mistakenly added this issue to the electron repo where instead i wanted to submit it to the electron website. Find the issue here: https://github.com/electron/electronjs.org/issues/2188
