### ISSUE TITLE
useContentSize flake on Windows CI

### ISSUE THREAD

**Issue by MarshallOfSound** [electron/electron#17130]
Build: https://windows-ci.electronjs.org/project/AppVeyor/electron-hew04/build/1.0.4722

```
not ok 233 BrowserWindow module "useContentSize" option make window created with content size when used
  AssertionError [ERR_ASSERTION]: Expected values to be strictly equal:
  
  124 !== 400
  
      at Context.<anonymous> (C:\projects\src\electron\spec\api-browser-window-spec.js:1230:14)
      at callFn (C:\projects\src\electron\spec\node_modules\mocha\lib\runnable.js:372:21)
      at Test.Runnable.run (C:\projects\src\electron\spec\node_modules\mocha\lib\runnable.js:364:7)
      at Runner.runTest (C:\projects\src\electron\spec\node_modules\mocha\lib\runner.js:455:10)
      at C:\projects\src\electron\spec\node_modules\mocha\lib\runner.js:573:12
      at next (C:\projects\src\electron\spec\node_modules\mocha\lib\runner.js:369:14)
      at C:\projects\src\electron\spec\node_modules\mocha\lib\runner.js:379:7
      at next (C:\projects\src\electron\spec\node_modules\mocha\lib\runner.js:303:14)
      at Immediate._onImmediate (C:\projects\src\electron\spec\node_modules\mocha\lib\runner.js:347:5)
      at processImmediate (timers.js:632:19)
```

I've seen this a few times (every time with 124 as the failed value)

**Comment by ckerr** [comment]
This flake hasn't been touched in quite awhile and I don't remember seeing it recently, so I'm going to close this issue. If this is in error and it's still an ongoing issue, please reopen this ticket. Thanks!
