### ISSUE TITLE
Auto Updater has an error

### ISSUE THREAD

**Issue by Dear-Min** [electron/electron#17307]
* **Electron Version: 4.0.8

* **Operating System: Windows 10

* **Last Known Working Electron version: 3.0.3

After Updating to Electron 4 my auto update has broken.

This is the message at the console.log

Uncaught (in promise) Error: Update info doesn't contain sha2 checksum: {
  "version": "2.0.1010",
  "files": [
    {
      "url": "NovaClient-Setup-2.0.1010.exe",
      "sha512": "QQu3FEKC9fmhkt547i5WV9WioyXYtpgHAXDXadEJh/atiIGw+/9B2Gf3tqZetbrwlo/vMcpcVojynCqWaW4N1Q==",
      "size": 111918934
    }
  ],
  "path": "NovaClient-Setup-2.0.1010.exe",
  "sha512": "QQu3FEKC9fmhkt547i5WV9WioyXYtpgHAXDXadEJh/atiIGw+/9B2Gf3tqZetbrwlo/vMcpcVojynCqWaW4N1Q==",
  "releaseDate": "2019-03-09T08:44:59.507Z"
}
    at validateUpdateInfo (C:\Users\Administrator\AppData\Local\Programs\NovaClient\resources\app.asar\node_modules\electron-auto-updater\src\GenericProvider.ts:58:11)
    at C:\Users\Administrator\AppData\Local\Programs\NovaClient\resources\app.asar\node_modules\electron-auto-updater\src\GitHubProvider.ts:37:5
From previous event:
    at GitHubProvider.getLatestVersion (C:\Users\Administrator\AppData\Local\Programs\NovaClient\resources\app.asar\node_modules\electron-auto-updater\out\GitHubProvider.js:69:11)
    at C:\Users\Administrator\AppData\Local\Programs\NovaClient\resources\app.asar\node_modules\electron-auto-updater\src\AppUpdater.ts:136:38
From previous event:
    at NsisUpdater.doCheckForUpdates (C:\Users\Administrator\AppData\Local\Programs\NovaClient\resources\app.asar\node_modules\electron-auto-updater\out\AppUpdater.js:217:11)
    at C:\Users\Administrator\AppData\Local\Programs\NovaClient\resources\app.asar\node_modules\electron-auto-updater\src\AppUpdater.ts:123:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:694:18)
    at tryOnImmediate (timers.js:665:5)
    at processImmediate (timers.js:647:5)
From previous event:
    at NsisUpdater._checkForUpdates (C:\Users\Administrator\AppData\Local\Programs\NovaClient\resources\app.asar\node_modules\electron-auto-updater\out\AppUpdater.js:180:11)
    at NsisUpdater.checkForUpdates (C:\Users\Administrator\AppData\Local\Programs\NovaClient\resources\app.asar\node_modules\electron-auto-updater\src\AppUpdater.ts:102:35)
    at callFunction (C:\Users\Administrator\AppData\Local\Programs\NovaClient\resources\electron.asar\browser\rpc-server.js:252:24)
    at C:\Users\Administrator\AppData\Local\Programs\NovaClient\resources\electron.asar\browser\rpc-server.js:411:10
    at EventEmitter.ipcMain.on.args (C:\Users\Administrator\AppData\Local\Programs\NovaClient\resources\electron.asar\browser\rpc-server.js:275:21)
    at EventEmitter.emit (events.js:182:13)
    at WebContents.<anonymous> (C:\Users\Administrator\AppData\Local\Programs\NovaClient\resources\electron.asar\browser\api\web-contents.js:368:21)
    at WebContents.emit (events.js:182:13)

**Comment by MarshallOfSound** [comment]
This error is thrown by the electron-auto-updater npm package not by electron itself.  You should raise this on that projects issue tracker
