### ISSUE TITLE
The network name cannot be found

### ISSUE THREAD

**Issue by dengf** [electron/electron#17403]
* **Electron Version: **
  * v2.0.9
* **Operating System:**
  * Windows 7 x64 
* **Last Known Working Electron version:**:
  * Not applicable. This is a one-user specific problem

### Expected Behavior
The native blpapi.node should be loaded w/o complaining

### Actual Behavior
ELECTRON_ASAR.js:166 return old.apply(this, arguments)
Error: The network name cannot be found.

\\?\c:\applications\resources\app.asar.unpacked\node_modules\blpapi\build\Release\blpapijs.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:180:18)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)

### To Reproduce
The distribution works fine except on this particular user.

**Comment by miniak** [comment]
This does not seem to be an issue with Electron

**Comment by dengf** [comment]
Thanks and apologies. The issue in our case in particular was caused by a environment variable with a value assigned a network drive. In case anyone else ran into the same issue.
