### ISSUE TITLE
No such module: atom_common_event

### ISSUE THREAD

**Issue by Zrylhh** [electron/electron#17638]
- Electron version: 4.1.0
- OS version: Windows 7

stack :
```
A JavaScript error occured in the main process
Uncaught Exception:

No such module: atom_common_event
	at binding (internal/bootstrap/loaders.js:82:36)
	at process.atomBinding (C:\Program Files\ASAPP\asapp\resources\electron.asar\common\atom-binding-setup.js:9:16)
	at Object.<anonymous> (C:\Program Files\ASAPP\asapp\resources\electron.asar\browser\rpc-serverjs:10:30)
	at Object.<anonymous> (C:\Program Files\ASAPP\asapp\resources\electron.asar\browser\rpc-server.js:560:3)
	at Module._compile (internal/modules/cjs/loaderjs:711:30)
	at Object.Module._extensions.js (intenal/modules/cjs/loader.js:722:10)
	at Module.load (internal/modules/cjs/loader.js:620:32)
	at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
	at Function.Module._load (internal/modules/cjs/loader.js:551:3)
	at Module.require (internal/modules/cjs/loader.js:658:17)
```

How to Reproduce: have no idea, I'm looking for possible bug now.

I have search other related question like #8423, [#41721](https://github.com/Microsoft/vscode/issues/41721#issue-289135009),but still confused about this.

**Comment by codebytere** [comment]
@Zrylhh can you please include the snippet of code that caused this? We are unable to look at this issue otherwise.

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
