### ISSUE TITLE
The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be  less than 248 characters

### ISSUE THREAD

**Issue by singhiskamal** [electron/electron#17689]
Hi 
I am running a script which will gonna "createWindowsInstaller" using electron-winstaller but i am getting this error of " The specified path, file name, or both are too long".I am using windows 7. So my question is , is this is possible in windows 7 or should i use some other operating system like Ubuntu or Mac? 

Error response: 

System.AggregateException: One or more errors occurred. ---> System.IO.PathTooLo
ngException: The specified path, file name, or both are too long. The fully qual
ified file name must be less than 260 characters, and the directory name must be
 less than 248 characters.
   at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 m
axPathLength, Boolean expandShortPaths)
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPath
Length, Boolean expandShortPaths)
   at System.IO.Path.InternalGetDirectoryName(String path)
   at Squirrel.ReleasePackage.<>c__DisplayClass14_0.<extractZipWithEscaping>b__0
()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceled
Exceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationTo
ken cancellationToken)
   at Squirrel.ReleasePackage.CreateReleasePackage(String outputFile, String pac
kagesRootDir, Func`2 releaseNotesProcessor, Action`1 contentsPostProcessHook)
   at Squirrel.Update.Program.Releasify(String package, String targetDir, String
 packagesDir, String bootstrapperExe, String backgroundGif, String signingOpts,
String baseUrl, String setupIcon, Boolean generateMsi, String frameworkVersion,
Boolean generateDeltas)
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
   at Squirrel.Update.Program.Main(String[] args)
---> (Inner Exception #0) System.IO.PathTooLongException: The specified path, fi
le name, or both are too long. The fully qualified file name must be less than 2
60 characters, and the directory name must be less than 248 characters.
   at System.IO.Path.LegacyNormalizePath(String path, Boolean fullCheck, Int32 m
axPathLength, Boolean expandShortPaths)
   at System.IO.Path.NormalizePath(String path, Boolean fullCheck, Int32 maxPath
Length, Boolean expandShortPaths)
   at System.IO.Path.InternalGetDirectoryName(String path)
   at Squirrel.ReleasePackage.<>c__DisplayClass14_0.<extractZipWithEscaping>b__0
()
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()<---

**Comment by codebytere** [comment]
This is a Windows platform-level limitation unfortunately!
