### ISSUE TITLE
Error: Cannot find module 'node-ffi'

### ISSUE THREAD

**Issue by zensabbah** [electron/electron#17745]
I'm new on NodeJS/ElectronJS.
I need to use User.dll functions.
My actual situation is:

Windows 10 on Parallels
Node -v = 10.15.3 (LTS)
NPM -v = 6.9.0

I installed:

`npm install --global --production windows-build-tools`

`npm install win32-api`
```
npm install ffi (gives me several "\ffi.cc(***): warning C4996: 'v8::Value::To
Object': .... deprecated)
```

 I added `var FFI = require('node-ffi');` in my "main.js" and when I try to compile with `npm start`

I obtain this error:
`Error: Cannot find module 'node-ffi'
    at Module._resolveFilename (internal/modules/cjs/loader.js:584:15)`

What's wrong?

**Comment by djfyaci** [comment]
How to solve it?

**Comment by Venryx** [comment]
Well, you're supposed to call `require("ffi")` instead of `require("node-ffi")`. (the npm package was renamed)

That said, I'm having a different issue after the above fix:
```
An error has occurred:
Error: Could not locate the bindings file. Tried:
 ΓåÆ C:\Root\Apps\@V\Venryx\Desktop\build\binding.node
 ΓåÆ C:\Root\Apps\@V\Venryx\Desktop\build\Debug\binding.node
 ΓåÆ C:\Root\Apps\@V\Venryx\Desktop\build\Release\binding.node
 ΓåÆ C:\Root\Apps\@V\Venryx\Desktop\out\Debug\binding.node
 ΓåÆ C:\Root\Apps\@V\Venryx\Desktop\Debug\binding.node
 ΓåÆ C:\Root\Apps\@V\Venryx\Desktop\out\Release\binding.node
 ΓåÆ C:\Root\Apps\@V\Venryx\Desktop\Release\binding.node
 ΓåÆ C:\Root\Apps\@V\Venryx\Desktop\build\default\binding.node
 ΓåÆ C:\Root\Apps\@V\Venryx\Desktop\compiled\10.2.0\win32\x64\binding.node
    at bindings (C:\Root\Apps\@V\Venryx\Desktop\Dist\index.js:50407:9)
    at Object.<anonymous> (C:\Root\Apps\@V\Venryx\Desktop\Dist\index.js:47994:68)
    at __webpack_require__ (C:\Root\Apps\@V\Venryx\Desktop\Dist\index.js:30:30)
    at Object.<anonymous> (C:\Root\Apps\@V\Venryx\Desktop\Dist\index.js:47894:11)
    at __webpack_require__ (C:\Root\Apps\@V\Venryx\Desktop\Dist\index.js:30:30)
    at Module.<anonymous> (C:\Root\Apps\@V\Venryx\Desktop\Dist\index.js:47810:61)
    at __webpack_require__ (C:\Root\Apps\@V\Venryx\Desktop\Dist\index.js:30:30)
    at Module.<anonymous> (C:\Root\Apps\@V\Venryx\Desktop\Dist\index.js:47787:65)
    at __webpack_require__ (C:\Root\Apps\@V\Venryx\Desktop\Dist\index.js:30:30)
    at Module.<anonymous> (C:\Root\Apps\@V\Venryx\Desktop\Dist\index.js:46755:77)
```

**Comment by Venryx** [comment]
Found out my error was because Webpack was bundling the "ref" library's source code into the main project js-bundle, meaning when ref tried to find its folder-path (so it could load the binding.node dll file), it was incorrectly searching in the main project folder instead of its package folder. To fix it, I added this:
```
webpackConfig.externals = {
	"ffi": "commonjs ffi",
	"ref": "commonjs ref",
};
```

**Comment by zensabbah** [comment]
Thanks dude!

**Comment by AhmadHoranieh** [comment]
Hey, when I try to implement this it still seems to error out.

I'm using ffi-napi instead of ffi and have my webpack.config set to this.

```
{
  /**
   * This is the main entry point for your application, it's the first file
   * that runs in the main process.
   */
  entry: ['./src/main/app.ts'],
  // Put your normal webpack config below here
  externals: {
    "ffi": "commonjs ffi",
    "ref": "commonjs ref",
  },
  module: {
    rules: require('./webpack.rules'),
  },
  resolve: {
    extensions: ['.js', '.ts', '.jsx', '.tsx', '.css', '.json'],
    alias: require('./webpack.aliases'),
  },
  stats: 'minimal',
  
}
```

I still get errors relating to fs, os, assert and path. Any idea how I can solve this issue?
