### ISSUE TITLE
[chrome-devtools] TypeError: Cannot read property 'Symbol(Bindings.NetworkProject._frameAttributionSymbol)' of null

### ISSUE THREAD

**Issue by megancooper** [electron/electron#17772]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** 4.0.3
* **Operating System:** macOS Mojave

### Actual Behavior

When I refresh my application (Using CMD + R), I sometimes see the TypeError below. It seems like its on the MainProcess side because it does not print in the electron app's window console. I'm not sure if this is a common bug, or something associated with Mac? It looks like a chrome-devtools error, but I'm not sure where to begin debugging this so I'm posting this here hoping someone else has encountered the issue.

My app is built using React and Redux.
```
[56901:0411/155839.680802:ERROR:CONSOLE(966)] "TypeError: Cannot read property 'Symbol(Bindings.NetworkProject._frameAttributionSymbol)' of null TypeError: Cannot read property 'Symbol(Bindings.NetworkProject._frameAttributionSymbol)' of null
[1]     at Function.removeFrameAttribution (chrome-devtools://devtools/bundled/shell.js:6899:88)
[1]     at Bindings.SASSSourceMapping._sourceMapDetached (chrome-devtools://devtools/bundled/shell.js:6475:318)
[1]     at SDK.SourceMapManager.dispatchEventToListeners (chrome-devtools://devtools/bundled/shell.js:489:23)
[1]     at SDK.SourceMapManager.detachSourceMap (chrome-devtools://devtools/bundled/shell.js:5644:48)
[1]     at SDK.CSSModel._resetStyleSheets (chrome-devtools://devtools/bundled/shell.js:3905:202)
[1]     at SDK.ResourceTreeModel.dispatchEventToListeners (chrome-devtools://devtools/bundled/shell.js:489:23)
[1]     at SDK.ResourceTreeModel._frameNavigated (chrome-devtools://devtools/bundled/shell.js:5437:6)
[1]     at SDK.PageDispatcher.frameNavigated (chrome-devtools://devtools/bundled/shell.js:5536:47)
[1]     at Protocol.InspectorBackend._DispatcherPrototype.dispatch (chrome-devtools://devtools/bundled/shell.js:3379:26)
[1]     at SDK.Target._onMessage (chrome-devtools://devtools/bundled/shell.js:3332:31)", source: chrome-devtools://devtools/bundled/shell.js (966)
```

**Comment by pavloldev6** [comment]
I have got exactly the same error. To me it happens when I use electron-reload and point it to my web source files of Angular project which I run in Electron. As soon as I make a change in Angular source files and save that file, I get this error in the terminal console.

**Comment by codebytere** [comment]
Looks like that's coming from somewhere [around here](https://chromium.googlesource.com/chromium/src/third_party/+/master/blink/renderer/devtools/front_end/bindings/NetworkProject.js?autodive=0%2F#71), which means that `uiSourceCode` is mostly likely what's `null` here 🤔

**Comment by codebytere** [comment]
@pavloldev6 do you happen to have a repro?

**Comment by pavloldev6** [comment]
@codebytere I don't but I can come up with one if it will help

**Comment by ford04** [comment]
Also happens for me on windows, when I reload *while* having chrome devtools open.

**Comment by shlajin** [comment]
Happens to me as well. Changing the source code, then invoking `location.reload()`

**Comment by codebytere** [comment]
@pavloldev6 that'd be great, thanks!

**Comment by beautyfree** [comment]
Same error

**Comment by jbe456** [comment]
I had a similar issue happening anytime I would start recording on the profiler (Chromium Version 79.0.3945.79 (Official Build) Arch Linux (64-bit)):

```
timeline_module.js:1063 Uncaught (in promise) TypeError: Cannot read property 'Symbol(_frameAttributionSymbol)' of null
    at Function.removeFrameAttribution (://devtools/bundled/bindings/NetworkProject.js:10)
    at SASSSourceMapping._sourceMapDetached (://devtools/bundled/bindings/SASSSourceMapping.js:6)
    at SourceMapManager.dispatchEventToListeners (://devtools/bundled/common/Object.js:12)
    at SourceMapManager.detachSourceMap (://devtools/bundled/sdk/SourceMapManager.js:28)
    at CSSModel._resetStyleSheets (://devtools/bundled/sdk/CSSModel.js:75)
    at async Promise.all (://devtools/bundled/index 7)
    at async Target.suspend (://devtools/bundled/sdk/Target.js:24)
    at async Promise.all (://devtools/bundled/index 0)
    at async Timeline.TimelineController._startRecordingWithCategories (timeline_module.js:136)
    at async Timeline.TimelineController.startRecording (timeline_module.js:121) 
```

From the stack, I knew it was related to style sheets, so after debugging the profiler, I managed to track it down to a few lines of code triggering the issue that looked like this:

```html
<div
    css={
      background: 'grey';
      :hover {
        color: 'red';
      }
    }
  >
```

We are using [React](https://reactjs.org) and [Emotion](https://emotion.sh/) and removing the lines related to `:hover{ ... }` would make the profiler work again:

```html
<div
    css={
      background: 'grey';
    }
  >
```

Of course this was not a solution since we needed those lines. Plus the `:hover{ ... }` pattern was used 40 times in our code without any issues for the other ones. So the real problem was a combination of this syntax and other stylesheets being generated in the same file. The solution was to break down the files into smaller file with less stylsheets generated per file. This made the profiler work again.

Another weird thing is that the same code base could be profiled by some and not by other... maybe related to different version of Chrome.

Hope it helps people having the same issue.

**Comment by none23** [comment]
@jbe456 Thanks a lot! I was facing the same issue using emotion in a next-js app (not using electron). Setting `{ sourceMap: false }` for babel-plugin-emotion fixed it for me.

**Comment by randing89** [comment]
@jbe456 Thanks. I encountered this issue in our app (not using electron or next-js) and the source map was from some external library. I had to do this in order to turn off the source map from emotion in the runtime.
```
{
        test: /path_to_the_broken_modules_folder\/.*\.js$/,
        loader: "string-replace-loader",
        options: {
          search: "process\\.env\\.NODE_ENV",
          replace: '"production"',
          flags: "g"
        }
      }
```

**Comment by bannier** [comment]
One workaround that worked for me is to disable CSS source maps in devtools settings.

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

If this is still reproducible on a supported version, please open a new issue with any other new information that a maintainer should know.

Thank you for taking the time to report this issue and helping to make Electron better! Your help is appreciated.
