### ISSUE TITLE
getGPUInfo failing on 32bit Windows since Node 12 upgrade

### ISSUE THREAD

**Issue by MarshallOfSound** [electron/electron#17845]
```
not ok 61 app module getGPUInfo() API succeeds with complete GPUInfo
      at getGPUInfo (C:\projects\src\electron\spec\api-app-spec.js:969:31)
      at processTicksAndRejections (internal/process/task_queues.js:86:5)
      at async Context.<anonymous> (C:\projects\src\electron\spec\api-app-spec.js:991:28)
```

Appears to be a regression caused by https://github.com/electron/electron/commit/ffd2224bbe818a12596a9db07bace2b364dcbd41

**Comment by MarshallOfSound** [comment]
Fixed by #17877
