### ISSUE TITLE
gclient sync failed on Mac while building electron 4.0.0

### ISSUE THREAD

**Issue by betterRunner** [electron/electron#17878]
- Operating System (Platform and Version):
Mac 10.13.6

- electron version
^4.0.0

- To reproduce:
According to https://electronjs.org/docs/development/build-instructions-gn
`
mkdir electron-gn && cd electron-gn
gclient config \
    --name "src/electron" \
    --unmanaged \
    https://github.com/electron/electron
gclient sync --with_branch_heads --with_tags
`

then throw the error:

> [1:23:23] Still working on:
[1:23:23]   src
Syncing projects:  66% ( 2/ 3) src
src (ERROR)
[0:00:00] Started.
[0:00:00] running "git cat-file -e 69.0.3497.106^{commit}" in "/Users/shenmou/.git_cache/chromium.googlesource.com-chromium-src"
[0:00:00] fatal: Not a valid object name 69.0.3497.106^{commit}

> 

> Traceback (most recent call last):
  File "/Users/shenmou/code/depot_tools/metrics.py", line 266, in print_notice_and_exit
    yield
  File "/Users/shenmou/code/depot_tools/gclient.py", line 3155, in <module>
    sys.exit(main(sys.argv[1:]))
  File "/Users/shenmou/code/depot_tools/gclient.py", line 3141, in main
    return dispatcher.execute(OptionParser(), argv)
  File "/Users/shenmou/code/depot_tools/subcommand.py", line 252, in execute
    return command(parser, args[1:])
  File "/Users/shenmou/code/depot_tools/gclient.py", line 2699, in CMDsync
    ret = client.RunOnDeps('update', args)
  File "/Users/shenmou/code/depot_tools/gclient.py", line 1734, in RunOnDeps
    patch_refs=patch_refs, target_branches=target_branches)
  File "/Users/shenmou/code/depot_tools/gclient_utils.py", line 894, in flush
    reraise(e[0], e[1], e[2])
  File "/Users/shenmou/code/depot_tools/gclient_utils.py", line 971, in run
    self.item.run(*self.args, **self.kwargs)
  File "/Users/shenmou/code/depot_tools/gclient.py", line 910, in run
    file_list)
  File "/Users/shenmou/code/depot_tools/gclient_scm.py", line 133, in RunCommand
    return getattr(self, command)(options, args, file_list)
  File "/Users/shenmou/code/depot_tools/gclient_scm.py", line 587, in update
    self._UpdateMirrorIfNotContains(mirror, options, rev_type, revision)
  File "/Users/shenmou/code/depot_tools/gclient_scm.py", line 997, in _UpdateMirrorIfNotContains
    lock_timeout=getattr(options, 'lock_timeout', 0))
  File "/Users/shenmou/code/depot_tools/git_cache.py", line 580, in populate
    lockfile.lock()
  File "/Users/shenmou/code/depot_tools/git_cache.py", line 157, in lock
    raise LockError("%s is already locked" % self.path)
LockError: /Users/shenmou/.git_cache/chromium.googlesource.com-chromium-src is already locked

I tried serval times but did not worked out,
the network should be finesince I can clone the chromium by running the git clone cmd.
Thanks.

**Comment by codebytere** [comment]
Did you follow the guidelines exactly? If you're cloning down and setting up electron you shouldn't be dealing with a version of Chromium as old as 69; we have 74 in master. I suggest nuking all existing artifacts and trying again.

**Comment by betterRunner** [comment]
@codebytere yes I think I followed the guidelines except that I set the git url to my project (with Electron v4.0.0, that's why it uses chromium 69) instead of the official one. And I successfully built it in Windows with the same operation.

**Comment by betterRunner** [comment]
@codebytere  Sorry to bother again but our problem is not solved yet. We also tried to build the Electron 5.0.0, and the same error raised: "fatal: Not a valid object name 73.0.3683.121^{commit}"

**Comment by MarshallOfSound** [comment]
@betterRunner Are you sure you're running `gclient sync --with_branch_heads --with_tags` (you need the `--with_tags`).  Also ensure your depot_tools is up to date 👍 We have clean VMs on every CI runs and it's working so it'll be a configuration / argument thing specific to the way you're using `gclient`

**Comment by hxkuc** [comment]
@betterRunner  did you fixed it , i have the same problem

**Comment by pfrazee** [comment]
I ran into this, try deleting your `~/.git_cache/`
