### ISSUE TITLE
v5.0.0-beta.9: Error: Cannot find module ("main" entry point deinfed in package.json is being ignored)

### ISSUE THREAD

**Issue by vladimiry** [electron/electron#17893]
### Issue Details

* **Electron Version:** v5.0.0-beta.9
* **Operating System:** linux x64
* **Last Known Working Electron version:**: v5.0.0-beta.8

### Expected Behavior
The app is able to use node modules.

### Actual Behavior
The app is not able to use node modules. See stacktrace:
```
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'some-module'
Require stack:
- /home/user/dev/_github/electron-packagejson-main/node_modules/electron/dist/resources/app.asar/main.js
- 
    at Module._resolveFilename (internal/modules/cjs/loader.js:664:15)
    at Function.Module._resolveFilename (/home/user/dev/_github/electron-packagejson-main/node_modules/electron/dist/resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.Module._load (internal/modules/cjs/loader.js:582:27)
    at Module.require (internal/modules/cjs/loader.js:720:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/home/user/dev/_github/electron-packagejson-main/node_modules/electron/dist/resources/app.asar/main.js:1:20)
    at Module._compile (internal/modules/cjs/loader.js:813:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:825:10)
    at Module.load (internal/modules/cjs/loader.js:682:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:614:12)
```

### To Reproduce
- `git clone https://github.com/vladimiry-forks/electron-packagejson-main.git`
- `cd electron-packagejson-main`
- `npm install` or `yarn --pure-lockfile` (yarn is preferred)
- `npx asar p app ./node_modules/electron/dist/resources/app.asar`
- `./node_modules/electron/dist/electron`

### Additional Information
Renaming `./app/node_modules/some-module/lib.js` to `index.js` makes it work which means v5.0.0-beta.9 ignores the `main` property defined in `package.json` file. So v5.0.0-beta.9 fails to load any dependency that relies on custom `main` entry point defined in `package.json`.

**Comment by nathanlesage** [comment]
Can confirm on macOS 10.14.4 using electron `5.0.0-beta.9`. Adding an `index.js`-file to the root of any of the non-working node-modules (content something like `module.exports = {}`) resolves the "Module not found"-issue for that specific module.

**This only applies to ASAR-files. If building an app without ASAR enabled, it will still work as expected. Electron `5.0.0-beta.8` does not exhibit this bug.**

So the bug definitely concerns the way ASAR-files are handled by Electron.

**Comment by vladimiry** [comment]
> This only applies to ASAR-files.

I confirm this, forgot to mention initially.

It also works if I let's say put `node_modules` to `./node_modules/electron/dist/resources/`, so not packaged to Asar.

**Comment by ckerr** [comment]
This was fixed by https://github.com/electron/electron/pull/17906, not sure why this didn't get autoclosed
