### ISSUE TITLE
requestSingleInstance specs crashing on master

### ISSUE THREAD

**Issue by MarshallOfSound** [electron/electron#17992]
```
ok 13 app module app.exit(exitCode) exits gracefully # SKIP -
Unhandled exception in main spec runner: { AssertionError: expected 3221226505 to equal 1
    at ChildProcess.<anonymous> (C:\projects\src\electron\spec-main\api-app-spec.ts:204:27)
    at Object.onceWrapper (events.js:282:20)
    at ChildProcess.emit (events.js:194:13)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
  message: 'expected 3221226505 to equal 1',
  showDiff: true,
  actual: 3221226505,
  expected: 1 }
not ok 14 app module app.requestSingleInstanceLock prevents the second launch of app
  AssertionError: expected 3221226505 to equal 1
      at ChildProcess.<anonymous> (electron\spec-main\api-app-spec.ts:204:27)
      at Process.ChildProcess._handle.onexit (internal/child_process.js:254:12)
```

Example build: https://windows-ci.electronjs.org/project/AppVeyor/electron-67iac/builds/62557?fullLog=true

**Comment by codebytere** [comment]
Does this still happen or can we close this?

**Comment by VerteDinde** [comment]
It seems like we addressed this flake, so I'm going to close this out.
