### ISSUE TITLE
Error with signing Electron package using Code signing certificate

### ISSUE THREAD

**Issue by rptwsthi** [electron/electron#18132]
We exported .exe and followed process as defined here https://electronjs.org/docs/tutorial/windows-store-guide, after that I configured and used `electron-windows-store`  to export .appx and sign that. 

We have purchased code signing certificate form Godaddy. I exported _pfx_ s defined here https://au.godaddy.com/help/windows-install-codedriver-signing-certificate-and-create-pfx-file-2698?locale=en. 

Check my request for exporting appx signing that below.

>>       electron-windows-store `  
>>       --input-directory D:\Arpit\GSWindows\LiveBuild\GSWDesktop `
>>       --output-directory D:\Arpit\GSWindows\Output `
>>       --package-version 1.0.0.0 `
>>       --windows-kit 'C:\Program Files (x86)\Windows Kits\10\App Certification Kit' `
>>       --desktop-converter 'C:\Users\DELL\AppData\Local\Microsoft\WindowsApps\Microsoft.DesktopAppConverter_8wekyb3d8bbwe' `
>>       --publisher 'CN=Ifcondition' `
>>       --package-name GoSession `
>>       --dev-cert 'D:\Arpit\GSWindows\Certificates\GSCertificate.pfx' `
>>       --cert-pass ##########

Once `appx` is exported and it comes to signing the certificate, it gives an **Error:**

> The following certificate was selected:
>     Issued to: Ifcondition
>     Issued by: Go Daddy Secure Certificate Authority - G2
>     Expires:   ### ### ## ##:##:## ####
>     SHA1 hash: ###########################################
> 
> Done Adding Additional Store
> 
> Error information: "Error: SignerSign() failed." (-2147024885/0x8007000b)
> 
> SignTool Error: An unexpected internal error has occurred.
> 
> Error: C:\Program Files (x86)\Windows Kits\10\App Certification Kit\signtool.exe exited with code: 1
>     at ChildProcess.child.on (C:\Users\DELL\AppData\Roaming\npm\node_modules\electron-windows-store\lib\utils.js:74:23)
>     at ChildProcess.emit (events.js:182:13)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)
> Error: C:\Program Files (x86)\Windows Kits\10\App Certification Kit\signtool.exe exited with code: 1
>     at ChildProcess.child.on (C:\Users\DELL\AppData\Roaming\npm\node_modules\electron-windows-store\lib\utils.js:74:23)
>     at ChildProcess.emit (events.js:182:13)
>     at Process.ChildProcess._handle.onexit (internal/child_process.js:240:12)

 
I also tried signing exported appx using SignTool with following request:

>   .\SignTool sign /f "D:\Arpit\GSWindows\Certificates\GSCertificate.pfx" /p ########## SHA256 "D:\Arpit\GSWindows\Output\GoSession.appx"

Which also gives similar **Error**:
> Done Adding Additional Store
> SignTool Error: File not found: SHA256
> SignTool Error: An unexpected internal error has occurred.
> Error information: "Error: SignerSign() failed." (-2146889723/0x80091005)

I have checked several reference document to understand the process and error but I couldn;t figure the problem, here are some links which found useful:
https://docs.microsoft.com/en-us/windows/uwp/packaging/sign-app-package-using-signtool
https://docs.microsoft.com/en-us/uwp/schemas/appxpackage/appxmanifestschema/element-identity

**Comment by codebytere** [comment]
cc @MarshallOfSound
