### ISSUE TITLE
accidental exit with errno 3221225477 and errno 3

### ISSUE THREAD

**Issue by hurryhuang1007** [electron/electron#18403]
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

- **Electron Version:**
  - 4.2.2 & 5.0.1
- **Operating System:**
  - Windows 10
- **Last Known Working Electron version:**
  - 3.1.9

### Expected Behavior

Successfully execute the `getInfos` method I defined in `fn.js` without accidental exit.

### Actual Behavior

Working fine under electron3.1.9 .
Successful execution under electron4.2.2 but unexpectedly exited immediately.
Successful execution under electron5.0.1 but unexpectedly exited after a while.
Unexpected exit message sometimes for `errno 3221225477` sometimes for`errno 3`. ( both electron 4.2.2 and 5.0.1 )

![image](https://user-images.githubusercontent.com/21291247/58156957-e718f300-7ca9-11e9-8720-3cb62bb1fd2a.png)

**errno 3221225477 log:**

```log
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Region\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@6.9.0
3 info using node@v10.15.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle xslide@0.0.0~prestart: xslide@0.0.0
6 info lifecycle xslide@0.0.0~start: xslide@0.0.0
7 verbose lifecycle xslide@0.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle xslide@0.0.0~start: PATH: C:\Users\Region\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\workspace\Xslide\node_modules\.bin;C:\Python27\;C:\Python27\Scripts;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;%USERPROFILE%\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\nodejs\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Users\Region\AppData\Local\Microsoft\WindowsApps;C:\Users\Region\AppData\Roaming\npm;C:\Users\Region\AppData\Local\Programs\Microsoft VS Code\bin
9 verbose lifecycle xslide@0.0.0~start: CWD: C:\workspace\Xslide
10 silly lifecycle xslide@0.0.0~start: Args: [ '/d /s /c', 'electron .' ]
11 silly lifecycle xslide@0.0.0~start: Returned: code: 3221225477  signal: null
12 info lifecycle xslide@0.0.0~start: Failed to exec start script
13 verbose stack Error: xslide@0.0.0 start: `electron .`
13 verbose stack Exit status 3221225477
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\Region\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\Region\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:970:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid xslide@0.0.0
15 verbose cwd C:\workspace\Xslide
16 verbose Windows_NT 10.0.17134
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Region\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v10.15.3
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 3221225477
22 error xslide@0.0.0 start: `electron .`
22 error Exit status 3221225477
23 error Failed at the xslide@0.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 3221225477, true ]
```

**errno 3 log:**

```log
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Users\\Region\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@6.9.0
3 info using node@v10.15.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle xslide@0.0.0~prestart: xslide@0.0.0
6 info lifecycle xslide@0.0.0~start: xslide@0.0.0
7 verbose lifecycle xslide@0.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle xslide@0.0.0~start: PATH: C:\Users\Region\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\workspace\Xslide\node_modules\.bin;C:\Python27\;C:\Python27\Scripts;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;%USERPROFILE%\.dnx\bin;C:\Program Files\Microsoft DNX\Dnvm\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\nodejs\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Users\Region\AppData\Local\Microsoft\WindowsApps;C:\Users\Region\AppData\Roaming\npm;C:\Users\Region\AppData\Local\Programs\Microsoft VS Code\bin
9 verbose lifecycle xslide@0.0.0~start: CWD: C:\workspace\Xslide
10 silly lifecycle xslide@0.0.0~start: Args: [ '/d /s /c', 'electron .' ]
11 silly lifecycle xslide@0.0.0~start: Returned: code: 3  signal: null
12 info lifecycle xslide@0.0.0~start: Failed to exec start script
13 verbose stack Error: xslide@0.0.0 start: `electron .`
13 verbose stack Exit status 3
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\Region\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\index.js:301:16)
13 verbose stack     at EventEmitter.emit (events.js:189:13)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\Region\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:189:13)
13 verbose stack     at maybeClose (internal/child_process.js:970:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid xslide@0.0.0
15 verbose cwd C:\workspace\Xslide
16 verbose Windows_NT 10.0.17134
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Region\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v10.15.3
19 verbose npm  v6.9.0
20 error code ELIFECYCLE
21 error errno 3
22 error xslide@0.0.0 start: `electron .`
22 error Exit status 3
23 error Failed at the xslide@0.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 3, true ]
```

### To Reproduce

```sh
$ git clone https://github.com/hurryhuang1007/Xslide.git -b electron@4.2.2-demo
or
$ git clone https://github.com/hurryhuang1007/Xslide.git -b electron@5.0.1-demo
```

```sh
$ cd ./Xslide
$ npm i
$ npm run rebuild
$ npm start
```

The `getInfos` method will be executed automatically after the app is opened for five seconds.
So you just have to wait.

### Additional Information

In particular, the version of ffi, ref, ref-struct, etc. used in the `electron@5.0.1-demo` branch is a modified version of @lxe, because they do not currently support node12. But I think this should not be the source of this problem.

**Comment by hurryhuang1007** [comment]
This project is actually part of our product and our products are ready to use electron@5. So this becomes a big problem.

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
