### ISSUE TITLE
Crash in onbeforeunload dialog

### ISSUE THREAD

**Issue by nornagon** [electron/electron#18431]
### Issue Details

* **Electron Version:**
  * master (e32cf5c41)
* **Operating System:**
  * macOS 10.14.4
* **Last Known Working Electron version:**
  * Unknown, but I'm pretty sure this crash is new to 6.0.x

### Expected Behavior
A wonderful crash-free experience for all `onbeforeunload` users.

### Actual Behavior
```
Unhandled exception in main spec runner: TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'WebContents'
    --- property 'webContents' closes the circle
    at JSON.stringify (<anonymous>)
    at WebContents.<anonymous> (/Users/nornagon/work/electron-bootstrap/src/electron/spec/node_modules/mocha/lib/runnable.js:407:64)
    at WebContents.emit (events.js:194:13)
not ok 1 webContents module will-prevent-unload event emits if beforeunload returns false
  TypeError: Converting circular structure to JSON
      --> starting at object with constructor 'WebContents'
      --- property 'webContents' closes the circle
      at JSON.stringify (<anonymous>)
Received signal 11 SEGV_MAPERR 0000000001f8
0   libbase.dylib                       0x00000001128c43b1 base::debug::CollectStackTrace(void**, unsigned long) + 33
1   libbase.dylib                       0x0000000112589ecb base::debug::StackTrace::StackTrace(unsigned long) + 75
2   libbase.dylib                       0x0000000112589f1d base::debug::StackTrace::StackTrace(unsigned long) + 29
3   libbase.dylib                       0x000000011257e0f5 base::debug::StackTrace::StackTrace() + 37
4   libbase.dylib                       0x00000001128c4221 base::debug::(anonymous namespace)::StackDumpSignalHandler(int, __siginfo*, void*) + 1393
5   libsystem_platform.dylib            0x00007fff7a836b5d _sigtramp + 29
6   ???                                 0x000000000000ffff 0x0 + 65535
7   libcontent.dylib                    0x00000001164e9129 void base::internal::FunctorTraits<void (content::WebContentsImpl::*)(int, int, IPC::Message*, bool, bool, std::__1::basic_string<unsigned short, base::string16_internals::string16_char_traits, std::__1::allocator<unsigned short> > const&), void>::Invoke<void (content::WebContentsImpl::*)(int, int, IPC::Message*, bool, bool, std::__1::basic_string<unsigned short, base::string16_internals::string16_char_traits, std::__1::allocator<unsigned short> > const&), content::WebContentsImpl*, int, int, IPC::Message*, bool, bool, std::__1::basic_string<unsigned short, base::string16_internals::string16_char_traits, std::__1::allocator<unsigned short> > const&>(void (content::WebContentsImpl::*)(int, int, IPC::Message*, bool, bool, std::__1::basic_string<unsigned short, base::string16_internals::string16_char_traits, std::__1::allocator<unsigned short> > const&), content::WebContentsImpl*&&, int&&, int&&, IPC::Message*&&, bool&&, bool&&, std::__1::basic_string<unsigned short, base::string16_internals::string16_char_traits, std::__1::allocator<unsigned short> > const&) + 313
8   libcontent.dylib                    0x00000001164e8f51 void base::internal::InvokeHelper<false, void>::MakeItSo<void (content::WebContentsImpl::*)(int, int, IPC::Message*, bool, bool, std::__1::basic_string<unsigned short, base::string16_internals::string16_char_traits, std::__1::allocator<unsigned short> > const&), content::WebContentsImpl*, int, int, IPC::Message*, bool, bool, std::__1::basic_string<unsigned short, base::string16_internals::string16_char_traits, std::__1::allocator<unsigned short> > const&>(void (content::WebContentsImpl::*&&)(int, int, IPC::Message*, bool, bool, std::__1::basic_string<unsigned short, base::string16_internals::string16_char_traits, std::__1::allocator<unsigned short> > const&), content::WebContentsImpl*&&, int&&, int&&, IPC::Message*&&, bool&&, bool&&, std::__1::basic_string<unsigned short, base::string16_internals::string16_char_traits, std::__1::allocator<unsigned short> > const&) + 241
9   libcontent.dylib                    0x00000001164e8e0b void base::internal::Invoker<base::internal::BindState<void (content::WebContentsImpl::*)(int, int, IPC::Message*, bool, bool, std::__1::basic_string<unsigned short, base::string16_internals::string16_char_traits, std::__1::allocator<unsigned short> > const&), base::internal::UnretainedWrapper<content::WebContentsImpl>, int, int, IPC::Message*>, void (bool, bool, std::__1::basic_string<unsigned short, base::string16_internals::string16_char_traits, std::__1::allocator<unsigned short> > const&)>::RunImpl<void (content::WebContentsImpl::*)(int, int, IPC::Message*, bool, bool, std::__1::basic_string<unsigned short, base::string16_internals::string16_char_traits, std::__1::allocator<unsigned short> > const&), std::__1::tuple<base::internal::UnretainedWrapper<content::WebContentsImpl>, int, int, IPC::Message*>, 0ul, 1ul, 2ul, 3ul>(void (content::WebContentsImpl::*&&)(int, int, IPC::Message*, bool, bool, std::__1::basic_string<unsigned short, base::string16_internals::string16_char_traits, std::__1::allocator<unsigned short> > const&), std::__1::tuple<base::internal::UnretainedWrapper<content::WebContentsImpl>, int, int, IPC::Message*>&&, std::__1::integer_sequence<unsigned long, 0ul, 1ul, 2ul, 3ul>, bool&&, bool&&, std::__1::basic_string<unsigned short, base::string16_internals::string16_char_traits, std::__1::allocator<unsigned short> > const&) + 251
10  libcontent.dylib                    0x00000001164e8beb base::internal::Invoker<base::internal::BindState<void (content::WebContentsImpl::*)(int, int, IPC::Message*, bool, bool, std::__1::basic_string<unsigned short, base::string16_internals::string16_char_traits, std::__1::allocator<unsigned short> > const&), base::internal::UnretainedWrapper<content::WebContentsImpl>, int, int, IPC::Message*>, void (bool, bool, std::__1::basic_string<unsigned short, base::string16_internals::string16_char_traits, std::__1::allocator<unsigned short> > const&)>::RunOnce(base::internal::BindStateBase*, bool, bool, std::__1::basic_string<unsigned short, base::string16_internals::string16_char_traits, std::__1::allocator<unsigned short> > const&) + 155
11  libcontent.dylib                    0x000000011631b21b base::OnceCallback<void (bool, bool, std::__1::basic_string<unsigned short, base::string16_internals::string16_char_traits, std::__1::allocator<unsigned short> > const&)>::Run(bool, bool, std::__1::basic_string<unsigned short, base::string16_internals::string16_char_traits, std::__1::allocator<unsigned short> > const&) && + 187
12  libcontent.dylib                    0x000000011631b7ae content::(anonymous namespace)::CloseDialogCallbackWrapper::Run(bool, bool, std::__1::basic_string<unsigned short, base::string16_internals::string16_char_traits, std::__1::allocator<unsigned short> > const&) + 126
13  libcontent.dylib                    0x00000001164e9bfd void base::internal::FunctorTraits<void (content::(anonymous namespace)::CloseDialogCallbackWrapper::*)(bool, bool, std::__1::basic_string<unsigned short, base::string16_internals::string16_char_traits, std::__1::allocator<unsigned short> > const&), void>::Invoke<void (content::(anonymous namespace)::CloseDialogCallbackWrapper::*)(bool, bool, std::__1::basic_string<unsigned short, base::string16_internals::string16_char_traits, std::__1::allocator<unsigned short> > const&), scoped_refptr<content::(anonymous namespace)::CloseDialogCallbackWrapper>, bool, bool, std::__1::basic_string<unsigned short, base::string16_internals::string16_char_traits, std::__1::allocator<unsigned short> > const&>(void (content::(anonymous namespace)::CloseDialogCallbackWrapper::*)(bool, bool, std::__1::basic_string<unsigned short, base::string16_internals::string16_char_traits, std::__1::allocator<unsigned short> > const&), scoped_refptr<content::(anonymous namespace)::CloseDialogCallbackWrapper>&&, bool&&, bool&&, std::__1::basic_string<unsigned short, base::string16_internals::string16_char_traits, std::__1::allocator<unsigned short> > const&) + 205
14  libcontent.dylib                    0x00000001164e9aa0 void base::internal::InvokeHelper<false, void>::MakeItSo<void (content::(anonymous namespace)::CloseDialogCallbackWrapper::*)(bool, bool, std::__1::basic_string<unsigned short, base::string16_internals::string16_char_traits, std::__1::allocator<unsigned short> > const&), scoped_refptr<content::(anonymous namespace)::CloseDialogCallbackWrapper>, bool, bool, std::__1::basic_string<unsigned short, base::string16_internals::string16_char_traits, std::__1::allocator<unsigned short> > const&>(void (content::(anonymous namespace)::CloseDialogCallbackWrapper::*&&)(bool, bool, std::__1::basic_string<unsigned short, base::string16_internals::string16_char_traits, std::__1::allocator<unsigned short> > const&), scoped_refptr<content::(anonymous namespace)::CloseDialogCallbackWrapper>&&, bool&&, bool&&, std::__1::basic_string<unsigned short, base::string16_internals::string16_char_traits, std::__1::allocator<unsigned short> > const&) + 144
15  libcontent.dylib                    0x00000001164e99dd void base::internal::Invoker<base::internal::BindState<void (content::(anonymous namespace)::CloseDialogCallbackWrapper::*)(bool, bool, std::__1::basic_string<unsigned short, base::string16_internals::string16_char_traits, std::__1::allocator<unsigned short> > const&), scoped_refptr<content::(anonymous namespace)::CloseDialogCallbackWrapper>, bool>, void (bool, std::__1::basic_string<unsigned short, base::string16_internals::string16_char_traits, std::__1::allocator<unsigned short> > const&)>::RunImpl<void (content::(anonymous namespace)::CloseDialogCallbackWrapper::*)(bool, bool, std::__1::basic_string<unsigned short, base::string16_internals::string16_char_traits, std::__1::allocator<unsigned short> > const&), std::__1::tuple<scoped_refptr<content::(anonymous namespace)::CloseDialogCallbackWrapper>, bool>, 0ul, 1ul>(void (content::(anonymous namespace)::CloseDialogCallbackWrapper::*&&)(bool, bool, std::__1::basic_string<unsigned short, base::string16_internals::string16_char_traits, std::__1::allocator<unsigned short> > const&), std::__1::tuple<scoped_refptr<content::(anonymous namespace)::CloseDialogCallbackWrapper>, bool>&&, std::__1::integer_sequence<unsigned long, 0ul, 1ul>, bool&&, std::__1::basic_string<unsigned short, base::string16_internals::string16_char_traits, std::__1::allocator<unsigned short> > const&) + 141
16  libcontent.dylib                    0x00000001164e9850 base::internal::Invoker<base::internal::BindState<void (content::(anonymous namespace)::CloseDialogCallbackWrapper::*)(bool, bool, std::__1::basic_string<unsigned short, base::string16_internals::string16_char_traits, std::__1::allocator<unsigned short> > const&), scoped_refptr<content::(anonymous namespace)::CloseDialogCallbackWrapper>, bool>, void (bool, std::__1::basic_string<unsigned short, base::string16_internals::string16_char_traits, std::__1::allocator<unsigned short> > const&)>::RunOnce(base::internal::BindStateBase*, bool, std::__1::basic_string<unsigned short, base::string16_internals::string16_char_traits, std::__1::allocator<unsigned short> > const&) + 128
17  Electron Framework                  0x0000000108affe35 base::OnceCallback<void (bool, std::__1::basic_string<unsigned short, base::string16_internals::string16_char_traits, std::__1::allocator<unsigned short> > const&)>::Run(bool, std::__1::basic_string<unsigned short, base::string16_internals::string16_char_traits, std::__1::allocator<unsigned short> > const&) && + 149
18  Electron Framework                  0x000000010a359fd4 atom::AtomJavaScriptDialogManager::RunBeforeUnloadDialog(content::WebContents*, content::RenderFrameHost*, bool, base::OnceCallback<void (bool, std::__1::basic_string<unsigned short, base::string16_internals::string16_char_traits, std::__1::allocator<unsigned short> > const&)>) + 132
19  libcontent.dylib                    0x000000011631beac content::WebContentsImpl::RunBeforeUnloadConfirm(content::RenderFrameHost*, bool, IPC::Message*) + 1404
20  libcontent.dylib                    0x000000011571cd6a content::RenderFrameHostImpl::OnRunBeforeUnloadConfirm(bool, IPC::Message*) + 746
21  libcontent.dylib                    0x0000000115845638 void base::DispatchToMethodImpl<content::RenderFrameHostImpl*, void (content::RenderFrameHostImpl::*)(bool, IPC::Message*), std::__1::tuple<bool>, std::__1::tuple<IPC::Message&>, 0ul, 0ul>(content::RenderFrameHostImpl* const&, void (content::RenderFrameHostImpl::*)(bool, IPC::Message*), std::__1::tuple<bool>&&, std::__1::tuple<IPC::Message&>*, std::__1::integer_sequence<unsigned long, 0ul>, std::__1::integer_sequence<unsigned long, 0ul>) + 184
22  libcontent.dylib                    0x000000011584556b void base::DispatchToMethod<content::RenderFrameHostImpl*, void (content::RenderFrameHostImpl::*)(bool, IPC::Message*), std::__1::tuple<bool>, std::__1::tuple<IPC::Message&> >(content::RenderFrameHostImpl* const&, void (content::RenderFrameHostImpl::*)(bool, IPC::Message*), std::__1::tuple<bool>&&, std::__1::tuple<IPC::Message&>*) + 139
23  libcontent.dylib                    0x000000011571ca20 bool IPC::MessageT<FrameHostMsg_RunBeforeUnloadConfirm_Meta, std::__1::tuple<bool>, std::__1::tuple<bool, std::__1::basic_string<unsigned short, base::string16_internals::string16_char_traits, std::__1::allocator<unsigned short> > > >::DispatchDelayReply<content::RenderFrameHostImpl, void, void (content::RenderFrameHostImpl::*)(bool, IPC::Message*)>(IPC::Message const*, content::RenderFrameHostImpl*, void*, void (content::RenderFrameHostImpl::*)(bool, IPC::Message*)) + 704
24  libcontent.dylib                    0x00000001157186c5 content::RenderFrameHostImpl::OnMessageReceived(IPC::Message const&) + 3333
25  libcontent.dylib                    0x0000000115f6c369 content::RenderProcessHostImpl::OnMessageReceived(IPC::Message const&) + 889
26  libipc.dylib                        0x00000001301a08a5 IPC::ChannelProxy::Context::OnDispatchMessage(IPC::Message const&) + 149
27  libipc.dylib                        0x00000001301a6327 void base::internal::FunctorTraits<void (IPC::ChannelProxy::Context::*)(IPC::Message const&), void>::Invoke<void (IPC::ChannelProxy::Context::*)(IPC::Message const&), scoped_refptr<IPC::ChannelProxy::Context>, IPC::Message>(void (IPC::ChannelProxy::Context::*)(IPC::Message const&), scoped_refptr<IPC::ChannelProxy::Context>&&, IPC::Message&&) + 151
28  libipc.dylib                        0x00000001301a61d6 void base::internal::InvokeHelper<false, void>::MakeItSo<void (IPC::ChannelProxy::Context::*)(IPC::Message const&), scoped_refptr<IPC::ChannelProxy::Context>, IPC::Message>(void (IPC::ChannelProxy::Context::*&&)(IPC::Message const&), scoped_refptr<IPC::ChannelProxy::Context>&&, IPC::Message&&) + 102
29  libipc.dylib                        0x00000001301a6143 void base::internal::Invoker<base::internal::BindState<void (IPC::ChannelProxy::Context::*)(IPC::Message const&), scoped_refptr<IPC::ChannelProxy::Context>, IPC::Message>, void ()>::RunImpl<void (IPC::ChannelProxy::Context::*)(IPC::Message const&), std::__1::tuple<scoped_refptr<IPC::ChannelProxy::Context>, IPC::Message>, 0ul, 1ul>(void (IPC::ChannelProxy::Context::*&&)(IPC::Message const&), std::__1::tuple<scoped_refptr<IPC::ChannelProxy::Context>, IPC::Message>&&, std::__1::integer_sequence<unsigned long, 0ul, 1ul>) + 99
30  libipc.dylib                        0x00000001301a601e base::internal::Invoker<base::internal::BindState<void (IPC::ChannelProxy::Context::*)(IPC::Message const&), scoped_refptr<IPC::ChannelProxy::Context>, IPC::Message>, void ()>::RunOnce(base::internal::BindStateBase*) + 62
31  libbase.dylib                       0x000000011257176c base::OnceCallback<void ()>::Run() && + 92
32  libbase.dylib                       0x0000000112725ad1 base::TaskAnnotator::RunTask(char const*, base::PendingTask*) + 1025
33  libbase.dylib                       0x00000001127511f6 base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl(base::sequence_manager::LazyNow*, bool*) + 1350
34  libbase.dylib                       0x000000011275168a base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork() + 90
35  libbase.dylib                       0x0000000112939b8c base::MessagePumpCFRunLoopBase::RunWork() + 124
36  libbase.dylib                       0x0000000112939afc ___ZN4base24MessagePumpCFRunLoopBase13RunWorkSourceEPv_block_invoke + 28
37  libbase.dylib                       0x00000001125704ea base::mac::CallWithEHFrame(void () block_pointer) + 10
38  libbase.dylib                       0x0000000112938ba5 base::MessagePumpCFRunLoopBase::RunWorkSource(void*) + 101
39  CoreFoundation                      0x00007fff4e16031b __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION__ + 17
40  CoreFoundation                      0x00007fff4e1602c1 __CFRunLoopDoSource0 + 108
41  CoreFoundation                      0x00007fff4e1441bb __CFRunLoopDoSources0 + 195
42  CoreFoundation                      0x00007fff4e143783 __CFRunLoopRun + 1196
43  CoreFoundation                      0x00007fff4e143085 CFRunLoopRunSpecific + 459
44  HIToolbox                           0x00007fff4d4219db RunCurrentEventLoopInMode + 292
45  HIToolbox                           0x00007fff4d421715 ReceiveNextEventCommon + 603
46  HIToolbox                           0x00007fff4d4214a6 _BlockUntilNextEventMatchingListInModeWithFilter + 64
47  AppKit                              0x00007fff4b7bbffb _DPSNextEvent + 965
48  AppKit                              0x00007fff4b7bad93 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 1361
49  AppKit                              0x00007fff4b7b4eb0 -[NSApplication run] + 699
50  libbase.dylib                       0x000000011293b201 base::MessagePumpNSApplication::DoRun(base::MessagePump::Delegate*) + 305
51  libbase.dylib                       0x00000001129382a8 base::MessagePumpCFRunLoopBase::Run(base::MessagePump::Delegate*) + 152
52  libbase.dylib                       0x0000000112752386 base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run(bool, base::TimeDelta) + 774
53  libbase.dylib                       0x00000001126d19a5 base::RunLoop::RunWithTimeout(base::TimeDelta) + 901
54  libbase.dylib                       0x00000001126d161a base::RunLoop::Run() + 42
55  libcontent.dylib                    0x00000001150454fe content::BrowserMainLoop::MainMessageLoopRun() + 510
56  libcontent.dylib                    0x00000001150451f9 content::BrowserMainLoop::RunMainMessageLoopParts() + 361
57  libcontent.dylib                    0x0000000115049b28 content::BrowserMainRunnerImpl::Run() + 344
58  libcontent.dylib                    0x000000011503f118 content::BrowserMain(content::MainFunctionParams const&) + 200
59  libcontent.dylib                    0x00000001178496d6 content::RunBrowserProcessMain(content::MainFunctionParams const&, content::ContentMainDelegate*) + 134
60  libcontent.dylib                    0x000000011784adc2 content::ContentMainRunnerImpl::RunServiceManager(content::MainFunctionParams&, bool) + 1266
61  libcontent.dylib                    0x000000011784a7e8 content::ContentMainRunnerImpl::Run(bool) + 600
62  libcontent.dylib                    0x0000000117847179 content::ContentServiceManagerMainDelegate::RunEmbedderProcess() + 57
63  libembedder.dylib                   0x000000018c7465cf service_manager::Main(service_manager::MainParams const&) + 1631
64  libcontent.dylib                    0x0000000117849609 content::ContentMain(content::ContentMainParams const&) + 89
65  Electron Framework                  0x0000000108982ff0 AtomMain + 112
66  Electron                            0x0000000107cc7d54 main + 84
67  libdyld.dylib                       0x00007fff7a6513d5 start + 1
68  ???                                 0x0000000000000006 0x0 + 6
[end of stack trace]
```

### To Reproduce
The test labelled `emits if beforeunload returns false` produces this failure occasionally (not all the time).

**Comment by nornagon** [comment]
err, actually i think this might have been an issue i caused locally by rewriting

```
      w.once('closed', () => done())
```
to
```
      w.once('closed', done)
```

still seems like it shouldn't have segfaulted though.
