### ISSUE TITLE
protocol.registerSchemesAsPrivileged has error in 5.0.1 and 5.0.2

### ISSUE THREAD

**Issue by xinnian88** [electron/electron#18450]
TypeError: protocol.registerSchemesAsPrivileged is not a function
    at Object.<anonymous> (/Users/xinnian/workspace/electron-example/src/main.js:4:10)
    at Object.<anonymous> (/Users/xinnian/workspace/electron-example/src/main.js:88:3)
    at Module._compile (internal/modules/cjs/loader.js:711:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:722:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:559:12)
    at Function.Module._load (internal/modules/cjs/loader.js:551:3)
    at loadApplicationPackage (/usr/local/lib/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js:287:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js:328:5)
    at Object.<anonymous> (/usr/local/lib/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js:365:3)

**Comment by ridesky** [comment]
+1
