### ISSUE TITLE
Tests failing on Rock960c

### ISSUE THREAD

**Issue by evmiguel** [electron/electron#18550]
### Issue Details

* **Electron Version:**
  * master build 5/21/2019
* **Operating System:**
  * Linux linaro-alip 4.4.154

### Expected Behavior
100% of tests to pass

#### Test Suite Output: 05/30/2019
- tests 168
- pass 163
- fail 5

Failed tests:
```
not ok 57 BrowserWindow module window.close() should emit beforeunload handler
not ok 188 BrowserWindow module "webPreferences" option nativeWindowOpen option loads native addons correctly after reload
not ok 197 BrowserWindow module beforeunload handler returning empty string would prevent close
not ok 213 BrowserWindow module "after each" hook: closeTheWindow
not ok 213 BrowserWindow module "before each" hook: openTheWindow
```

#### Test Suite Output: 06/06/2019
- tests 687
- pass 665
- fail 22

Failed tests: 
```
not ok 190 BrowserWindow module "webPreferences" option nativeWindowOpen option loads native addons correctly after reload
not ok 198 BrowserWindow module beforeunload handler returning false would prevent close
not ok 199 BrowserWindow module beforeunload handler returning empty string would prevent close
not ok 244 BrowserWindow module window.getNativeWindowHandle() returns valid handle
not ok 555 process module process.getIOCounters() returns an io counters object
not ok 747 renderer nodeIntegrationInSubFrames without anything special turned on should load preload scripts in top level iframes
not ok 751 renderer nodeIntegrationInSubFrames without anything special turned on should correctly reply to the nested sub-frames with using event.reply
not ok 753 renderer nodeIntegrationInSubFrames with sandbox on should load preload scripts in top level iframes
not ok 756 renderer nodeIntegrationInSubFrames with sandbox on should correctly reply to the sub-frames with using event.reply
not ok 757 renderer nodeIntegrationInSubFrames with sandbox on should correctly reply to the nested sub-frames with using event.reply
not ok 760 renderer nodeIntegrationInSubFrames with context isolation on should load preload scripts in nested iframes
not ok 766 renderer nodeIntegrationInSubFrames with sandbox, context isolation on should load preload scripts in nested iframes
not ok 767 renderer nodeIntegrationInSubFrames with sandbox, context isolation on should correctly reply to the main frame with using event.reply
not ok 769 renderer nodeIntegrationInSubFrames with sandbox, context isolation on should correctly reply to the nested sub-frames with using event.reply
not ok 770 renderer nodeIntegrationInSubFrames with sandbox, context isolation on should not expose globals in main world
not ok 771 renderer nodeIntegrationInSubFrames with webview on should load preload scripts in top level iframes
not ok 772 renderer nodeIntegrationInSubFrames with webview on should load preload scripts in nested iframes
not ok 773 renderer nodeIntegrationInSubFrames with webview on should correctly reply to the main frame with using event.reply
not ok 774 renderer nodeIntegrationInSubFrames with webview on should correctly reply to the sub-frames with using event.reply
not ok 775 renderer nodeIntegrationInSubFrames with webview on should correctly reply to the nested sub-frames with using event.reply
not ok 776 renderer nodeIntegrationInSubFrames with webview on should not expose globals in main world
not ok 778 renderer nodeIntegrationInSubFrames with sandbox, webview on should load preload scripts in top level iframes
```

### To Reproduce
Run on a Rock960c device, with apt sources from testing

**Comment by evmiguel** [comment]
Dependencies to be installed when running test suite:

Reqs:
- apt:
  - make
  - g++
  - git

- npm:
  - yargs
  - chai-as-promised
  - mocha
  - dirty-chai
  - dbus-native
  - acorn
  - ws
  - q
  - multiparty
  - dugite
  - semver
  - plist

**Comment by evmiguel** [comment]
# Output of each test run

## BrowserWindow module window.close() should emit beforeunload handler
```
(process:1151): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.
[1179:0531/190557.362189:ERROR:gl_surface_glx.cc(424)] glxQueryVersion failed
[1179:0531/190557.363082:ERROR:gl_initializer_x11.cc(147)] GLSurfaceGLX::InitializeOneOff failed.
[1179:0531/190557.381750:ERROR:viz_main_impl.cc(170)] Exiting GPU process due to errors during initialization
[1151:0531/190557.400558:WARNING:gpu_process_host.cc(1206)] The GPU process has crashed 1 time(s)
GPU process crashed (killed=false)
[1151:0531/190557.695377:WARNING:gpu_process_host.cc(983)] Reinitialized the GPU process after a crash. The reported initialization time was 190 ms
[1151:0531/190557.715466:ERROR:viz_process_transport_factory.cc(323)] Switching to software compositing.
1..2
not ok 1 BrowserWindow module window.close() should emit unload handler
  Error: ENOENT: no such file or directory, open '/home/linaro/src/electron/spec/fixtures/api/close'
      at Object.openSync (fs.js:453:3)
      at Object.func [as openSync] (electron/js2c/asar.js:155:31)
      at Object.readFileSync (fs.js:353:35)
      at Object.fs.readFileSync (electron/js2c/asar.js:557:40)
      at /home/linaro/src/electron/spec/api-browser-window-spec.js:211:28
      at CallbacksRegistry.apply (/home/linaro/src/out/Default/resources/electron.asar/renderer/callbacks-registry.js:41:29)
      at /home/linaro/src/out/Default/resources/electron.asar/renderer/api/remote.js:281:23
      at EventEmitter.<anonymous> (/home/linaro/src/out/Default/resources/electron.asar/renderer/api/remote.js:271:13)
      at EventEmitter.emit (events.js:194:13)
      at Object.onMessage (/home/linaro/src/out/Default/resources/electron.asar/renderer/init.js:43:16)
[1151:0531/190607.235812:WARNING:internal_linux.cc(64)] Failed to read /proc/1216/stat
[1151:0531/190608.552491:INFO:CONSOLE(0)] "Blocked attempt to show a 'beforeunload' confirmation panel for a frame that never had a user gesture since its load. https://www.chromestatus.com/feature/5082396709879808", source: file:///home/linaro/src/electron/spec/fixtures/api/close-beforeunload-false.html (0)
[1151:0531/190608.567788:INFO:CONSOLE(41)] "Uncaught (in promise) Error: ERR_FAILED (-2) loading 'file:///home/linaro/src/electron/spec/fixtures/api/close-beforeunload-false.html'", source: /home/linaro/src/out/Default/resources/electron.asar/renderer/callbacks-registry.js (41)
ok 2 BrowserWindow module window.close() should emit beforeunload handler
# tests 2
# pass 1
# fail 1
[1151:0531/190609.412259:WARNING:internal_linux.cc(64)] Failed to read /proc/1189/stat
[1151:0531/190609.441550:WARNING:discardable_shared_memory_manager.cc(410)] Some MojoDiscardableSharedMemoryManagerImpls are still alive. They will be leaked.
[1151:0531/190609.452081:WARNING:internal_linux.cc(64)] Failed to read /proc/1187/stat
```

## BrowserWindow module "webPreferences" option nativeWindowOpen option loads native addons correctly after reload
```

(process:1248): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.
Unable to revert mtime: /usr/local/share/fonts
[1276:0531/190741.112944:ERROR:gl_surface_glx.cc(424)] glxQueryVersion failed
[1276:0531/190741.113090:ERROR:gl_initializer_x11.cc(147)] GLSurfaceGLX::InitializeOneOff failed.
[1276:0531/190741.127537:ERROR:viz_main_impl.cc(170)] Exiting GPU process due to errors during initialization
[1248:0531/190741.149389:WARNING:gpu_process_host.cc(1206)] The GPU process has crashed 1 time(s)
GPU process crashed (killed=false)
[1248:0531/190741.336527:WARNING:gpu_process_host.cc(983)] Reinitialized the GPU process after a crash. The reported initialization time was 57 ms
[1248:0531/190741.363879:ERROR:viz_process_transport_factory.cc(323)] Switching to software compositing.
[1284:0531/190741.958155:ERROR:command_buffer_proxy_impl.cc(126)] ContextResult::kTransientFailure: Failed to send GpuChannelMsg_CreateCommandBuffer.
[1284:0531/190741.958260:ERROR:context_provider_command_buffer.cc(144)] GpuChannelHost failed to create command buffer.
1..44
ok 1 BrowserWindow module "webPreferences" option "preload" option does not leak require
[1248:0531/190750.483471:WARNING:internal_linux.cc(64)] Failed to read /proc/1315/stat
ok 2 BrowserWindow module "webPreferences" option "preload" option does not leak require when sandbox is enabled
ok 3 BrowserWindow module "webPreferences" option "preload" option does not leak require when context isolation is enabled
[1248:0531/190753.545242:WARNING:internal_linux.cc(64)] Failed to read /proc/1345/stat
ok 4 BrowserWindow module "webPreferences" option "preload" option does not leak require when context isolation and sandbox are enabled
ok 5 BrowserWindow module "webPreferences" option "preload" option loads the script before other scripts in window
ok 6 BrowserWindow module "webPreferences" option "preload" option can successfully delete the Buffer global
[1248:0531/190758.779082:WARNING:internal_linux.cc(64)] Failed to read /proc/1383/stat
[1248:0531/190800.791383:INFO:CONSOLE(5)] "'window.webkitStorageInfo' is deprecated. Please use 'navigator.webkitTemporaryStorage' or 'navigator.webkitPersistentStorage' instead.", source: /home/linaro/src/electron/spec/fixtures/module/access-blink-apis.js (5)
[1248:0531/190800.875235:INFO:CONSOLE(23)] "(node:1397) [DEP0016] DeprecationWarning: 'GLOBAL' is deprecated, use 'global'", source: internal/process/warning.js (23)
ok 7 BrowserWindow module "webPreferences" option "preload" option has synchronous access to all eventual window APIs
ok 8 BrowserWindow module "webPreferences" option session preload scripts can set multiple session preload script
ok 9 BrowserWindow module "webPreferences" option session preload scripts without sandbox loads the script before other scripts in window including normal preloads
ok 10 BrowserWindow module "webPreferences" option session preload scripts with sandbox loads the script before other scripts in window including normal preloads
ok 11 BrowserWindow module "webPreferences" option "additionalArguments" option adds extra args to process.argv in the renderer process
ok 12 BrowserWindow module "webPreferences" option "additionalArguments" option adds extra value args to process.argv in the renderer process
ok 13 BrowserWindow module "webPreferences" option "node-integration" option disables node integration by default
[1248:0531/190810.614592:WARNING:internal_linux.cc(64)] Failed to read /proc/1458/stat
ok 14 BrowserWindow module "webPreferences" option "enableRemoteModule" option without sandbox enables the remote module by default
[1248:0531/190812.660336:WARNING:internal_linux.cc(64)] Failed to read /proc/1471/stat
ok 15 BrowserWindow module "webPreferences" option "enableRemoteModule" option without sandbox disables the remote module when false
[1248:0531/190814.029965:WARNING:internal_linux.cc(64)] Failed to read /proc/1484/stat
ok 16 BrowserWindow module "webPreferences" option "enableRemoteModule" option with sandbox enables the remote module by default
ok 17 BrowserWindow module "webPreferences" option "enableRemoteModule" option with sandbox disables the remote module when false
ok 18 BrowserWindow module "webPreferences" option "sandbox" option exposes ipcRenderer to preload script
ok 19 BrowserWindow module "webPreferences" option "sandbox" option exposes ipcRenderer to preload script (path has special chars)
ok 20 BrowserWindow module "webPreferences" option "sandbox" option exposes "loaded" event to preload script
ok 21 BrowserWindow module "webPreferences" option "sandbox" option exposes "exit" event to preload script
ok 22 BrowserWindow module "webPreferences" option "sandbox" option should open windows in same domain with cross-scripting enabled
ok 23 BrowserWindow module "webPreferences" option "sandbox" option should open windows in another domain with cross-scripting disabled
ok 24 BrowserWindow module "webPreferences" option "sandbox" option should inherit the sandbox setting in opened windows
ok 25 BrowserWindow module "webPreferences" option "sandbox" option should open windows with the options configured via new-window event listeners
ok 26 BrowserWindow module "webPreferences" option "sandbox" option should set ipc event sender correctly
[1248:0531/190834.813536:WARNING:internal_linux.cc(64)] Failed to read /proc/1715/stat
ok 27 BrowserWindow module "webPreferences" option "sandbox" option supports calling preventDefault on new-window events
ok 28 BrowserWindow module "webPreferences" option "sandbox" option properly manages remote object references after page reload
ok 29 BrowserWindow module "webPreferences" option "sandbox" option properly manages remote object references after page reload in child window
[1:0531/190843.855529:WARNING:internal_linux.cc(64)] Failed to read /proc/self/stat
[1:0531/190843.856935:WARNING:process_metrics_linux.cc(620)] Failed to open /proc/meminfo
[1:0531/190843.857661:WARNING:internal_linux.cc(64)] Failed to read /proc/1/stat
[1248:0531/190843.898127:INFO:CONSOLE(0)] "Uncaught (in promise) Error: Failed to create memory dump", source: file:///home/linaro/src/electron/spec/fixtures/api/preload.html (0)
ok 30 BrowserWindow module "webPreferences" option "sandbox" option validates process APIs access in sandboxed renderer
[1:0531/190846.153173:WARNING:internal_linux.cc(64)] Failed to read /proc/self/stat
[1:0531/190846.154642:WARNING:process_metrics_linux.cc(620)] Failed to open /proc/meminfo
[1:0531/190846.155448:WARNING:internal_linux.cc(64)] Failed to read /proc/1/stat
[1248:0531/190846.305423:INFO:CONSOLE(0)] "Uncaught (in promise) Error: Failed to create memory dump", source: file:///home/linaro/src/electron/spec/fixtures/pages/webview-did-attach-event.html (0)
[1248:0531/190846.687393:INFO:CONSOLE(7)] "a", source: file:///home/linaro/src/electron/spec/fixtures/pages/a.html (7)
ok 31 BrowserWindow module "webPreferences" option "sandbox" option webview in sandbox renderer
ok 32 BrowserWindow module "webPreferences" option "sandbox" option event handling works for window events
[1248:0531/190850.145305:INFO:CONSOLE(41)] "Uncaught (in promise) Error:  (-3) loading 'file:///home/linaro/src/electron/spec/fixtures/api/sandbox.html?webcontents-stop'", source: /home/linaro/src/out/Default/resources/electron.asar/renderer/callbacks-registry.js (41)
ok 33 BrowserWindow module "webPreferences" option "sandbox" option event handling works for stop events
ok 34 BrowserWindow module "webPreferences" option "sandbox" option event handling works for web contents events
[1248:0531/190852.387297:WARNING:internal_linux.cc(64)] Failed to read /proc/1820/stat
[1248:0531/190852.418247:WARNING:internal_linux.cc(64)] Failed to read /proc/1808/stat
ok 35 BrowserWindow module "webPreferences" option nativeWindowOpen option opens window of about:blank with cross-scripting enabled
[1248:0531/190854.188370:WARNING:internal_linux.cc(64)] Failed to read /proc/1823/stat
ok 36 BrowserWindow module "webPreferences" option nativeWindowOpen option opens window of same domain with cross-scripting enabled
[1248:0531/190855.934157:WARNING:internal_linux.cc(64)] Failed to read /proc/1836/stat
ok 37 BrowserWindow module "webPreferences" option nativeWindowOpen option blocks accessing cross-origin frames
[1248:0531/190858.504353:WARNING:internal_linux.cc(64)] Failed to read /proc/1849/stat
[1248:0531/190858.506337:WARNING:internal_linux.cc(64)] Failed to read /proc/1861/stat
ok 38 BrowserWindow module "webPreferences" option nativeWindowOpen option opens window from <iframe> tags
[1248:0531/190900.314764:WARNING:internal_linux.cc(64)] Failed to read /proc/1875/stat
not ok 39 BrowserWindow module "webPreferences" option nativeWindowOpen option loads native addons correctly after reload
  AssertionError: expected 'Require echo failed: /home/linaro/src/electron/spec/fixtures/native-addon/echo/build/Release/echo.node: wrong ELF class: ELFCLASS32' to equal 'function'
      at /home/linaro/src/electron/spec/api-browser-window-spec.js:2030:30
      at CallbacksRegistry.apply (/home/linaro/src/out/Default/resources/electron.asar/renderer/callbacks-registry.js:41:29)
      at /home/linaro/src/out/Default/resources/electron.asar/renderer/api/remote.js:281:23
      at EventEmitter.<anonymous> (/home/linaro/src/out/Default/resources/electron.asar/renderer/api/remote.js:271:13)
      at EventEmitter.emit (events.js:194:13)
      at Object.onMessage (/home/linaro/src/out/Default/resources/electron.asar/renderer/init.js:43:16)
ok 40 BrowserWindow module "webPreferences" option nativeWindowOpen option should inherit the nativeWindowOpen setting in opened windows
[1248:0531/190904.998185:ERROR:frame_sink_provider_impl.cc(34)] No RenderWidgetHost exists with id 6 in process 133
[1248:0531/190904.998781:ERROR:frame_sink_provider_impl.cc(51)] No RenderWidgetHost exists with id 6 in process 133
[1248:0531/190905.013462:WARNING:internal_linux.cc(64)] Failed to read /proc/1912/stat
[1248:0531/190905.138022:WARNING:internal_linux.cc(64)] Failed to read /proc/1900/stat
ok 41 BrowserWindow module "webPreferences" option nativeWindowOpen option should open windows with the options configured via new-window event listeners
[1248:0531/190907.941830:ERROR:frame_sink_provider_impl.cc(34)] No RenderWidgetHost exists with id 6 in process 138
[1248:0531/190907.945842:ERROR:frame_sink_provider_impl.cc(51)] No RenderWidgetHost exists with id 6 in process 138
[1248:0531/190907.954872:WARNING:internal_linux.cc(64)] Failed to read /proc/1940/stat
[1248:0531/190908.072389:WARNING:internal_linux.cc(64)] Failed to read /proc/1928/stat
ok 42 BrowserWindow module "webPreferences" option nativeWindowOpen option retains the original web preferences when window.location is changed to a new origin
[1248:0531/190911.721185:WARNING:internal_linux.cc(64)] Failed to read /proc/1968/stat
[1248:0531/190911.827943:WARNING:internal_linux.cc(64)] Failed to read /proc/1955/stat
ok 43 BrowserWindow module "webPreferences" option nativeWindowOpen option should have nodeIntegration disabled in child windows
[1248:0531/190913.627058:WARNING:internal_linux.cc(64)] Failed to read /proc/1995/stat
ok 44 BrowserWindow module "webPreferences" option "disableHtmlFullscreenWindowResize" option prevents window from resizing when set
[1248:0531/190915.402741:WARNING:internal_linux.cc(64)] Failed to read /proc/2009/stat
# tests 44
# pass 43
# fail 1
[1248:0531/190915.835894:WARNING:internal_linux.cc(64)] Failed to read /proc/1284/stat
[1248:0531/190915.877334:WARNING:discardable_shared_memory_manager.cc(410)] Some MojoDiscardableSharedMemoryManagerImpls are still alive. They will be leaked.
[1248:0531/190915.889764:WARNING:internal_linux.cc(64)] Failed to read /proc/1285/stat
```
## BrowserWindow module beforeunload handler returning empty string would prevent close
```

(process:2029): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.
Unable to revert mtime: /usr/local/share/fonts
[2058:0531/191000.961083:ERROR:gl_surface_glx.cc(424)] glxQueryVersion failed
[2058:0531/191000.961203:ERROR:gl_initializer_x11.cc(147)] GLSurfaceGLX::InitializeOneOff failed.
[2058:0531/191000.974596:ERROR:viz_main_impl.cc(170)] Exiting GPU process due to errors during initialization
[2029:0531/191000.999846:WARNING:gpu_process_host.cc(1206)] The GPU process has crashed 1 time(s)
GPU process crashed (killed=false)
[2029:0531/191001.155475:WARNING:gpu_process_host.cc(983)] Reinitialized the GPU process after a crash. The reported initialization time was 49 ms
[2029:0531/191001.171669:ERROR:viz_process_transport_factory.cc(323)] Switching to software compositing.
[2061:0531/191001.791940:ERROR:command_buffer_proxy_impl.cc(126)] ContextResult::kTransientFailure: Failed to send GpuChannelMsg_CreateCommandBuffer.
[2061:0531/191001.792067:ERROR:context_provider_command_buffer.cc(144)] GpuChannelHost failed to create command buffer.
1..6
ok 1 BrowserWindow module beforeunload handler returning undefined would not prevent close
[2029:0531/191010.640304:WARNING:internal_linux.cc(64)] Failed to read /proc/2095/stat
[2029:0531/191011.983033:INFO:CONSOLE(0)] "Blocked attempt to show a 'beforeunload' confirmation panel for a frame that never had a user gesture since its load. https://www.chromestatus.com/feature/5082396709879808", source: file:///home/linaro/src/electron/spec/fixtures/api/close-beforeunload-false.html (0)
[2029:0531/191011.999137:INFO:CONSOLE(41)] "Uncaught (in promise) Error: ERR_FAILED (-2) loading 'file:///home/linaro/src/electron/spec/fixtures/api/close-beforeunload-false.html'", source: /home/linaro/src/out/Default/resources/electron.asar/renderer/callbacks-registry.js (41)
ok 2 BrowserWindow module beforeunload handler returning false would prevent close
[2029:0531/191012.252611:WARNING:internal_linux.cc(64)] Failed to read /proc/2109/stat
[2029:0531/191013.955871:WARNING:internal_linux.cc(64)] Failed to read /proc/2123/stat
not ok 3 BrowserWindow module beforeunload handler returning empty string would prevent close
  Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves. (/home/linaro/src/electron/spec/api-browser-window-spec.js)
[2029:0531/191044.436784:INFO:CONSOLE(0)] "Blocked attempt to show a 'beforeunload' confirmation panel for a frame that never had a user gesture since its load. https://www.chromestatus.com/feature/5082396709879808", source: file:///home/linaro/src/electron/spec/fixtures/api/beforeunload-false-prevent3.html (0)
[2029:0531/191044.536989:INFO:CONSOLE(0)] "Blocked attempt to show a 'beforeunload' confirmation panel for a frame that never had a user gesture since its load. https://www.chromestatus.com/feature/5082396709879808", source: file:///home/linaro/src/electron/spec/fixtures/api/beforeunload-false-prevent3.html (0)
[2029:0531/191044.586779:INFO:CONSOLE(0)] "Blocked attempt to show a 'beforeunload' confirmation panel for a frame that never had a user gesture since its load. https://www.chromestatus.com/feature/5082396709879808", source: file:///home/linaro/src/electron/spec/fixtures/api/beforeunload-false-prevent3.html (0)
ok 4 BrowserWindow module beforeunload handler emits for each close attempt
[2029:0531/191044.818287:WARNING:internal_linux.cc(64)] Failed to read /proc/2137/stat
[2029:0531/191046.692176:INFO:CONSOLE(0)] "Blocked attempt to show a 'beforeunload' confirmation panel for a frame that never had a user gesture since its load. https://www.chromestatus.com/feature/5082396709879808", source: file:///home/linaro/src/electron/spec/fixtures/api/beforeunload-false-prevent3.html (0)
[2029:0531/191046.704302:WARNING:internal_linux.cc(64)] Failed to read /proc/2163/stat
[2029:0531/191046.840048:INFO:CONSOLE(0)] "Blocked attempt to show a 'beforeunload' confirmation panel for a frame that never had a user gesture since its load. https://www.chromestatus.com/feature/5082396709879808", source: file:///home/linaro/src/electron/spec/fixtures/api/beforeunload-false-prevent3.html (0)
[2029:0531/191046.851845:WARNING:internal_linux.cc(64)] Failed to read /proc/2166/stat
[2029:0531/191046.928339:INFO:CONSOLE(0)] "Blocked attempt to show a 'beforeunload' confirmation panel for a frame that never had a user gesture since its load. https://www.chromestatus.com/feature/5082396709879808", source: file:///home/linaro/src/electron/spec/fixtures/api/beforeunload-false-prevent3.html (0)
[2029:0531/191046.939796:WARNING:internal_linux.cc(64)] Failed to read /proc/2168/stat
ok 5 BrowserWindow module beforeunload handler emits for each reload attempt
[2029:0531/191047.132797:WARNING:internal_linux.cc(64)] Failed to read /proc/2151/stat
[2029:0531/191048.903792:INFO:CONSOLE(0)] "Blocked attempt to show a 'beforeunload' confirmation panel for a frame that never had a user gesture since its load. https://www.chromestatus.com/feature/5082396709879808", source: file:///home/linaro/src/electron/spec/fixtures/api/beforeunload-false-prevent3.html (0)
[2029:0531/191048.917733:WARNING:internal_linux.cc(64)] Failed to read /proc/2183/stat
[2029:0531/191048.921264:INFO:CONSOLE(41)] "Uncaught (in promise) Error: ERR_FAILED (-2) loading 'about:blank'", source: /home/linaro/src/out/Default/resources/electron.asar/renderer/callbacks-registry.js (41)
[2029:0531/191049.093864:INFO:CONSOLE(0)] "Blocked attempt to show a 'beforeunload' confirmation panel for a frame that never had a user gesture since its load. https://www.chromestatus.com/feature/5082396709879808", source: file:///home/linaro/src/electron/spec/fixtures/api/beforeunload-false-prevent3.html (0)
[2029:0531/191049.104772:WARNING:internal_linux.cc(64)] Failed to read /proc/2186/stat
[2029:0531/191049.121752:INFO:CONSOLE(41)] "Uncaught (in promise) Error: ERR_FAILED (-2) loading 'about:blank'", source: /home/linaro/src/out/Default/resources/electron.asar/renderer/callbacks-registry.js (41)
[2029:0531/191049.180589:INFO:CONSOLE(0)] "Blocked attempt to show a 'beforeunload' confirmation panel for a frame that never had a user gesture since its load. https://www.chromestatus.com/feature/5082396709879808", source: file:///home/linaro/src/electron/spec/fixtures/api/beforeunload-false-prevent3.html (0)
[2029:0531/191049.195313:WARNING:internal_linux.cc(64)] Failed to read /proc/2188/stat
[2029:0531/191049.212304:INFO:CONSOLE(41)] "Uncaught (in promise) Error: ERR_FAILED (-2) loading 'about:blank'", source: /home/linaro/src/out/Default/resources/electron.asar/renderer/callbacks-registry.js (41)
ok 6 BrowserWindow module beforeunload handler emits for each navigation attempt
# tests 6
# pass 5
# fail 1
[2029:0531/191049.858720:WARNING:internal_linux.cc(64)] Failed to read /proc/2061/stat
[2029:0531/191049.891643:WARNING:discardable_shared_memory_manager.cc(410)] Some MojoDiscardableSharedMemoryManagerImpls are still alive. They will be leaked.
[2029:0531/191049.905702:WARNING:internal_linux.cc(64)] Failed to read /proc/2069/stat
```

## BrowserWindow module "after each" hook: closeTheWindow
```

(process:2269): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.
Unable to revert mtime: /usr/local/share/fonts
[2298:0531/191252.741487:ERROR:gl_surface_glx.cc(424)] glxQueryVersion failed
[2298:0531/191252.741614:ERROR:gl_initializer_x11.cc(147)] GLSurfaceGLX::InitializeOneOff failed.
[2298:0531/191252.755735:ERROR:viz_main_impl.cc(170)] Exiting GPU process due to errors during initialization
[2269:0531/191252.773033:WARNING:gpu_process_host.cc(1206)] The GPU process has crashed 1 time(s)
GPU process crashed (killed=false)
[2269:0531/191252.930832:WARNING:gpu_process_host.cc(983)] Reinitialized the GPU process after a crash. The reported initialization time was 48 ms
[2269:0531/191252.946362:ERROR:viz_process_transport_factory.cc(323)] Switching to software compositing.
[2301:0531/191253.594030:ERROR:command_buffer_proxy_impl.cc(107)] ContextResult::kTransientFailure: Shared memory region is not valid
[2301:0531/191253.594114:ERROR:context_provider_command_buffer.cc(144)] GpuChannelHost failed to create command buffer.
1..0
# tests 0
# pass 0
# fail 0
[2269:0531/191259.250864:WARNING:internal_linux.cc(64)] Failed to read /proc/2301/stat
[2269:0531/191259.298586:WARNING:discardable_shared_memory_manager.cc(410)] Some MojoDiscardableSharedMemoryManagerImpls are still alive. They will be leaked.
[2269:0531/191259.312349:WARNING:internal_linux.cc(64)] Failed to read /proc/2309/stat
```

## BrowserWindow module "before each" hook: openTheWindow
```

(process:2338): Gtk-WARNING **: Locale not supported by C library.
	Using the fallback 'C' locale.
Unable to revert mtime: /usr/local/share/fonts
[2366:0531/191321.853446:ERROR:gl_surface_glx.cc(424)] glxQueryVersion failed
[2366:0531/191321.853594:ERROR:gl_initializer_x11.cc(147)] GLSurfaceGLX::InitializeOneOff failed.
[2366:0531/191321.870280:ERROR:viz_main_impl.cc(170)] Exiting GPU process due to errors during initialization
[2338:0531/191321.887601:WARNING:gpu_process_host.cc(1206)] The GPU process has crashed 1 time(s)
GPU process crashed (killed=false)
[2338:0531/191322.068410:WARNING:gpu_process_host.cc(983)] Reinitialized the GPU process after a crash. The reported initialization time was 57 ms
[2338:0531/191322.078853:ERROR:viz_process_transport_factory.cc(323)] Switching to software compositing.
1..0
# tests 0
# pass 0
# fail 0
[2338:0531/191328.323694:WARNING:internal_linux.cc(64)] Failed to read /proc/2369/stat
[2338:0531/191328.349634:WARNING:discardable_shared_memory_manager.cc(410)] Some MojoDiscardableSharedMemoryManagerImpls are still alive. They will be leaked.
```

**Comment by codebytere** [comment]
We don't currently test on Rock960c so if this isn't something that is affecting a specific end-user behavior it's not something the maintainer team will be able to look into. We would happily accept PRs, but i'm going to close this for now as a wontfix.
