### ISSUE TITLE
registerSchemesAsPrivileged is not a function 

### ISSUE THREAD

**Issue by ridesky** [electron/electron#18727]
```
import {
  app,
  protocol
} from 'electron'

protocol.registerSchemesAsPrivileged([{
  scheme: 'seek',
  privileges: {
    standard: true,
    secure: true,
    allowServiceWorkers: true,
    supportFetchAPI: true,
    corsEnabled: true
  }
}]);
```
 It return : 
```
  App threw an error during load
  TypeError: electron.protocol.registerSchemesAsPrivileged is not a function
      at eval (webpack:///./src/main/index.js?:15:19)
      at Module../src/main/index.js (D:\2_Project\Onchain\seek\dist\electron\main.js:1464:1)
      at __webpack_require__ (D:\2_Project\Onchain\seek\dist\electron\main.js:21:30)
      at eval (webpack:///./src/main/index.dev.js?:11:1)
      at Object../src/main/index.dev.js (D:\2_Project\Onchain\seek\dist\electron\main.js:1452:1)
      at __webpack_require__ (D:\2_Project\Onchain\seek\dist\electron\main.js:21:30)
      at eval (webpack:///multi_./src/main/index.dev.js_./src/main/index.js?:1:1)
      at Object.0 (D:\2_Project\Onchain\seek\dist\electron\main.js:1558:1)
      at __webpack_require__ (D:\2_Project\Onchain\seek\dist\electron\main.js:21:30)
      at D:\2_Project\Onchain\seek\dist\electron\main.js:85:18
```

### Issue Details

* **Electron Version:**
    - "electron": "^4.2.4",
    - "electron-builder": "^20.19.2",
* **Operating System:**
  - win10 (17134)

**Comment by ridesky** [comment]
Fixed in 5.0.0.

**Comment by codebytere** [comment]
That was introduced in 5-0-x, as confirmed by the fact that it does not exist in 4-2-x [protocol documentation](https://github.com/electron/electron/blob/4-2-x/docs/api/protocol.md).

**Comment by gustavooavila** [comment]
It's back at ^5.0.6

**Comment by t12ouble** [comment]
fixed with
`protocol.registerSchemesAsPrivileged([
  { scheme: 'scheme1', privileges: { standard: true, secure: true } },
  { scheme: 'scheme2', privileges: { standard: true, secure: true } }
])`

**Comment by Jenifer-TheCoder** [comment]
This is due to version mismatch between the electron version of the app you might be using and the version of any node package you are trying to execute.
