### ISSUE TITLE
使用electron vue 打包遇到的问题

### ISSUE THREAD

**Issue by I-find-you11** [electron/electron#18789]
If you provide a URL, please list the commands required to clone/setup/run your repo e.g.
```sh
 OKAY  take it away `electron-builder`

  • electron-builder version=20.43.0
  • loaded configuration file=package.json ("build" field)
  • writing effective config file=build\builder-effective-config.yaml
  • no native production dependencies
  • packaging       platform=win32 arch=x64 electron=2.0.18 appOutDir=build\win-unpacked
  ⨯ remove C:\Users\yl\Desktop\electronApp\vitaldebug\build\win-unpacked\resources\app.asar: The process cannot access the file because it is being used by another process.
github.com/develar/go-fs-util.EnsureEmptyDir
        /Volumes/data/go/pkg/mod/github.com/develar/go-fs-util@v2.0.1-0.20181113101504-f6630ccc0e93+incompatible/fs.go:101
github.com/develar/app-builder/pkg/electron.unpackElectron.func1.1
        /Volumes/data/Documents/app-builder/pkg/electron/electronUnpack.go:39
github.com/develar/app-builder/pkg/util.MapAsyncConcurrency.func2
        /Volumes/data/Documents/app-builder/pkg/util/async.go:67
runtime.goexit
        /usr/local/Cellar/go/1.12.1/libexec/src/runtime/asm_amd64.s:1337

Error: C:\Users\yl\Desktop\electronApp\VitalDebug\node_modules\app-builder-bin\win\x64\app-builder.exe exited with code 1
    at ChildProcess.childProcess.once.code (C:\Users\yl\Desktop\electronApp\VitalDebug\node_modules\builder-util\src\util.ts:244:14)
    at Object.onceWrapper (events.js:317:30)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
From previous event:
    at _unpack (C:\Users\yl\Desktop\electronApp\VitalDebug\node_modules\app-builder-lib\out\electron\ElectronFramework.js:298:18)
    at unpack (C:\Users\yl\Desktop\electronApp\VitalDebug\node_modules\app-builder-lib\out\electron\ElectronFramework.js:257:18)
    at ElectronFramework.prepareApplicationStageDirectory (C:\Users\yl\Desktop\electronApp\VitalDebug\node_modules\app-builder-lib\src\electron\ElectronFramework.ts:125:12)
    at C:\Users\yl\Desktop\electronApp\VitalDebug\node_modules\app-builder-lib\src\platformPackager.ts:180:21
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.doPack (C:\Users\yl\Desktop\electronApp\VitalDebug\node_modules\app-builder-lib\src\platformPackager.ts:167:165)
    at C:\Users\yl\Desktop\electronApp\VitalDebug\node_modules\app-builder-lib\src\platformPackager.ts:113:16
    at Generator.next (<anonymous>)
From previous event:
    at WinPackager.pack (C:\Users\yl\Desktop\electronApp\VitalDebug\node_modules\app-builder-lib\src\platformPackager.ts:111:95)
    at C:\Users\yl\Desktop\electronApp\VitalDebug\node_modules\app-builder-lib\src\packager.ts:430:24
    at Generator.next (<anonymous>)
    at xfs.stat (C:\Users\yl\Desktop\electronApp\VitalDebug\node_modules\fs-extra-p\node_modules\fs-extra\lib\mkdirs\mkdirs.js:56:16)
    at C:\Users\yl\Desktop\electronApp\VitalDebug\node_modules\graceful-fs\polyfills.js:285:20
    at FSReqWrap.oncomplete (fs.js:153:5)
From previous event:
    at Packager.doBuild (C:\Users\yl\Desktop\electronApp\VitalDebug\node_modules\app-builder-lib\src\packager.ts:396:24)
    at C:\Users\yl\Desktop\electronApp\VitalDebug\node_modules\app-builder-lib\src\packager.ts:366:57
    at Generator.next (<anonymous>)
    at C:\Users\yl\Desktop\electronApp\VitalDebug\node_modules\graceful-fs\graceful-fs.js:111:16
    at C:\Users\yl\Desktop\electronApp\VitalDebug\node_modules\graceful-fs\graceful-fs.js:45:10
    at FSReqWrap.oncomplete (fs.js:135:15)
From previous event:
    at Packager._build (C:\Users\yl\Desktop\electronApp\VitalDebug\node_modules\app-builder-lib\src\packager.ts:335:133)
    at C:\Users\yl\Desktop\electronApp\VitalDebug\node_modules\app-builder-lib\src\packager.ts:331:23
    at Generator.next (<anonymous>)
    at runCallback (timers.js:810:20)
    at tryOnImmediate (timers.js:768:5)
    at processImmediate [as _immediateCallback] (timers.js:745:5)
From previous event:
    at Packager.build (C:\Users\yl\Desktop\electronApp\VitalDebug\node_modules\app-builder-lib\src\packager.ts:288:14)
    at build (C:\Users\yl\Desktop\electronApp\VitalDebug\node_modules\app-builder-lib\src\index.ts:59:28)
    at build (C:\Users\yl\Desktop\electronApp\VitalDebug\node_modules\electron-builder\src\builder.ts:228:10)
    at then (C:\Users\yl\Desktop\electronApp\VitalDebug\node_modules\electron-builder\src\cli\cli.ts:49:19)
    at <anonymous>
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vital@0.0.1 build: `node .electron-vue/build.js && electron-builder`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the vital@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\yl\AppData\Roaming\npm-cache\_logs\2019-06-14T08_15_58_537Z-debug.log
```

**Comment by I-find-you11** [comment]
我需要关闭掉我的编辑器重新打开项目才能打包成功

**Comment by Veiintc** [comment]
1、兄dei。。这是英文社区且不是中国人的项目，你问问题包括题目和说明最好用英文，机翻也可以（This is an English community project and not a Chinese project. You should ask questions including questions and instructions in English）

2、从字面意思上你应该去 electron-vue或者 electron-builld那边提issues （You should literally go to electron vue or electron builld to raise issues）

3、从报错信息上来看，是你的asar处在被占用，你得检查一下你的写法，是不是有代码或者其他工具占用了你的asar（According to the error message, it is your asar that is occupied. You should check your writing method to see if there is any code or other tool that is occupied by your asar）
remove C:\Users\yl\Desktop\electronApp\vitaldebug\build\win-unpacked\resources\app.asar: The process cannot access the file because it is being used by another process.

**Comment by malept** [comment]
This looks like an issue with `electron-builder` and not Electron itself, so I'm going to close this for now until there is some evidence that shows otherwise.
