### ISSUE TITLE
electron-update fail for mac

### ISSUE THREAD

**Issue by WzFFzW** [electron/electron#18786]
### Issue Details
in mac, auto-update error.  But in window, auto-update success.

#### Error message
Uncaught Exception:
TypeError: Error processing argument at index 0, conversion failure from #<Object>
    at Server.server.listen (/Applications/mycode.app/Contents/Resources/app.asar/node_modules/electron-updater/src/MacUpdater.ts:118:32)
    at Object.onceWrapper (events.js:314:30)
    at emitNone (events.js:105:13)
    at Server.emit (events.js:207:7)
    at emitListeningNT (net.js:1346:10)
    at _combinedTickCallback (internal/process/next_tick.js:135:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

the file of zip is downloaded success

electron-updater: 3.0.3

* **Electron Version:*1.8.4*
  * 
* **Operating System:*mac10.13.6*
  * 
* **Last Known Working Electron version:*5.x*
  * 

### Expected Behavior

no error

**Comment by MarshallOfSound** [comment]
`electron-updater` is not an electron module, it is a third party module that is probably broken.  Although unfortunate there is nothing we can do about that, you should raise this issue with the maintainer of that module

**Comment by paco3346** [comment]
For anyone else who stumbles across this like I did- the issue ended up being with electron-updater > `3.2.*`. I hard coded to to `3.1.4` and the issue went away.
