### ISSUE TITLE
Not able to execute protractor tests with electron-angular app

### ISSUE THREAD

**Issue by Jayasankar-m** [electron/electron#18825]
* [x ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

Not able to execute protractor tests with electron-angular app
Sample application and tests available at [https://github.com/Jayasankar-m/electron-angular-protractor.git](https://github.com/Jayasankar-m/electron-angular-protractor.git)
- Tests run fine when executed with chrome browser
- Tests fail when tried with electron

* **Electron Version:**
  * v5.0.4
* **Operating System:**
  * Windows 10  x64 
* **Last Known Working Electron version:**
  * N/A

### Expected Behavior

Should be possible to execute autoamtion tests using protractor/webdriver for electron based app using the electron-chromedriver.

### Actual Behavior
Tests throws the following error when executed. 

`[10:59:47] I/launcher - Running 1 instances of WebDriver
[10:59:47] I/hosted - Using the selenium server at http://localhost:9515
[10:59:48] E/launcher - unknown error: Failed to create a Chrome process.
  (Driver info: chromedriver=76.0.3783.1 (e74cdb57d7c7a6c37e9b21d8557e53bbdba17e42-refs/branch-heads/3783@{#2}),platform=Windows NT 10.0.16299 x86_64)
[10:59:48] E/launcher - WebDriverError: unknown error: Failed to create a Chrome process.
  (Driver info: chromedriver=76.0.3783.1 (e74cdb57d7c7a6c37e9b21d8557e53bbdba17e42-refs/branch-heads/3783@{#2}),platform=Windows NT 10.0.16299 x86_64)
    at Object.checkLegacyResponse (C:\Jayasankar\wip\electron\node_modules\selenium-webdriver\lib\error.js:546:15)
    at parseHttpResponse (C:\Jayasankar\wip\electron\node_modules\selenium-webdriver\lib\http.js:509:13)
    at doSend.then.response (C:\Jayasankar\wip\electron\node_modules\selenium-webdriver\lib\http.js:441:30)
    at process._tickCallback (internal/process/next_tick.js:68:7)
From: Task: WebDriver.createSession()
    at Function.createSession (C:\Jayasankar\wip\electron\node_modules\selenium-webdriver\lib\webdriver.js:769:24)
    at createDriver (C:\Jayasankar\wip\electron\node_modules\selenium-webdriver\index.js:170:33)
    at Builder.build (C:\Jayasankar\wip\electron\node_modules\selenium-webdriver\index.js:635:14)
    at Hosted.getNewDriver (C:\Jayasankar\wip\electron\node_modules\protractor\built\driverProviders\driverProvider.js:53:33)
    at Runner.createBrowser (C:\Jayasankar\wip\electron\node_modules\protractor\built\runner.js:195:43)
    at q.then.then (C:\Jayasankar\wip\electron\node_modules\protractor\built\runner.js:339:29)
    at _fulfilled (C:\Jayasankar\wip\electron\node_modules\q\q.js:834:54)
    at C:\Jayasankar\wip\electron\node_modules\q\q.js:863:30
    at Promise.promise.promiseDispatch (C:\Jayasankar\wip\electron\node_modules\q\q.js:796:13)
    at C:\Jayasankar\wip\electron\node_modules\q\q.js:556:49
[10:59:48] E/launcher - Process exited with error code 199`

### To Reproduce
1. Clone `https://github.com/Jayasankar-m/electron-angular-protractor.git`
2. `npm install`
3. `node ./node_modules/protractor/bin/webdriver-manager update`
4. Start node server by executing 'startserver.bat'
5. #### Execute chrome tests
      Execute 'execute-chrome-test.bat'
      **-  Tests Pass**
6.  #### Execute electron tests
      Execute 'execute-electron-test.bat'
      **- Tests Fail**

**Comment by codebytere** [comment]
Closing as this is not an issue with `electron` itself; please open an issue on crbug.com as this seems to be originating on Chromium's end.
