### ISSUE TITLE
Self Signed certificated error only in electron

### ISSUE THREAD

**Issue by Alt791350** [electron/electron#19501]
* Electron version: 5.0.8
* Operating system: Ubuntu 18.04.1 64-bit

### Expected behavior

Connect to the IMAP server and print to console amount of unseen email in inbox.

### Actual behavior

The following error is being thrown ONLY when in an electron app.
The code shows expected behavior outside of electron.

Error:
```
[connection] Error: Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
{ Error [ERR_STREAM_DESTROYED]: Cannot call write after a stream was destroyed
    at doWrite (_stream_writable.js:411:19)
    at clearBuffer (_stream_writable.js:545:7)
    at Socket.Writable.uncork (_stream_writable.js:319:7)
    at JSStreamSocket.doWrite (internal/js_stream_socket.js:161:17)
    at JSStream.onwrite (internal/js_stream_socket.js:19:57)
    at Socket.ondata (internal/js_stream_socket.js:63:22)
    at Socket.emit (events.js:194:13)
    at addChunk (_stream_readable.js:296:12)
    at readableAddChunk (_stream_readable.js:277:11)
    at Socket.Readable.push (_stream_readable.js:232:10) source: 'socket' }
[connection] Error: Error: self signed certificate
{ Error: self signed certificate
    at TLSSocket.onConnectSecure (_tls_wrap.js:1257:34)
    at TLSSocket.emit (events.js:194:13)
    at TLSSocket._finishInit (_tls_wrap.js:734:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:566:12)
    at Socket.ondata (internal/js_stream_socket.js:63:22)
    at Socket.emit (events.js:194:13)
    at addChunk (_stream_readable.js:296:12)
    at readableAddChunk (_stream_readable.js:277:11)
    at Socket.Readable.push (_stream_readable.js:232:10)
    at TCP.onStreamRead (internal/stream_base_commons.js:165:17) code: 'DEPTH_ZERO_SELF_SIGNED_CERT', source: 'socket' }
```

### How to reproduce

* Grab the following code
* Paste it in a file
* Replace credentials with a valid gmail account (of course)
* Install `imap` and `electron` via npm
* Run the code through electron

Code:
```
const {app} = require("electron")
const Imap = require("imap")

app.on("ready", function() {
	var mail = new Imap({
		user: "**********@gmail.com",
		password: "************",
		host: "imap.gmail.com",
		port: 993,
		tls: true,
		debug: console.log
	})
	
	mail.once("ready", function() {
		mail.openBox('INBOX', true, function(err, box) {
			if (err) throw err
			mail.search(['UNSEEN'], function(err, results) {
				if (err) throw err
				console.log("Got 'results'!")
				console.dir(results.length)
				mail.end()
			})
		})
	})
	
	mail.on("error", function(err) {
		console.error(err)
	})
	
	mail.once("end", function() {
		console.log("Closing connection")
		process.exit(0)
	})
	
	mail.connect()
})
```

**Comment by Alt791350** [comment]
And it suddenly works again. I left my computer for 2 hours and it suddenly works.
Great...

**Comment by electron-triage** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 6.1.x or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by electron-triage** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
