### ISSUE TITLE
Error: Bad EXE format

### ISSUE THREAD

**Issue by bert2002** [electron/electron#19526]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 5.0.8
* **Operating System:**
  * Ubuntu 18.04.2
* **Last Known Working Electron version:**
  * N/A

### Expected Behavior
Running a windows application.

### Actual Behavior
Application is not starting and no log files are produces. 

### To Reproduce
I am building my application like this:
```
npm install
webpack --config webpack.main.config.js
electron --enable-logging --no-sandbox ./compile.js
build --win
```
part of the package.json
```
  "build": {
    "generateUpdatesFilesForAllChannels": "false",
    "detectUpdateChannel": "true",
    "artifactName": "application-${version}.${ext}",
    "publish": [
      {
        "provider": "generic",
        "url": "https://application.com/updates/"
      }
    ],
    "appId": "application",
    "files": [
      "build",
      "main.jsc",
      "preload.js"
    ],
    "win": {
      "target": "portable",
      "verifyUpdateCodeSignature": false
    }
  }
```
### Additional Information
I am running the application to test purposes with wine (wine-4.0.1) and getting following error:
```
[17:52:34.126] [error] Error: Bad EXE format for \\?\C:\users\user\Temp\c143a296-757b-48d5-aac3-b70427d255fa.tmp.node.
\\?\C:\users\user\Temp\c143a296-757b-48d5-aac3-b70427d255fa.tmp.node
    at process.func [as dlopen] (electron/js2c/asar.js:155:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:881:18)
    at Object.func [as .node] (electron/js2c/asar.js:164:18)
    at Module.load (internal/modules/cjs/loader.js:701:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:633:12)
    at Function.Module._load (internal/modules/cjs/loader.js:625:3)
    at Module.require (internal/modules/cjs/loader.js:739:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (C:\users\user\Temp\1Oj9n4eNCXTsN8ObTVqUuDk7DHW\resources\app.asar\node_modules\pkcs11js\index.js:1:18)
    at Module._compile (internal/modules/cjs/loader.js:839:30)

```

Any idea what could cause this?

Thanks,
bert

**Comment by MarshallOfSound** [comment]
Your native module was not built correctly, the `.node` file is for a native node module.  Ensure you are building the native module for the correct electron version
