### ISSUE TITLE
JS Exception when Cmd+C on MAC in dev tools

### ISSUE THREAD

**Issue by sergeyd63** [electron/electron#20592]
### Issue Details

* **Electron Version:**
  * 6.0.12
* **Operating System:**
  * macOS 10.14.6

### Expected Behavior
Copy the selected in dev tools

### Actual Behavior
JavaScript exception

### To Reproduce
* Go to dev tools
* Select some text (Elements, Sources,...)
* Press Cmd+C

### Exception Details
Uncaught Exception: 
TypeError: Cannot read property 'focusOnWebView' of undefined 
at click (/Users/dev/Documents/GitHub/Zerp-app-WebView/Electron/app/out/main/menu.js:56:27) 
at MenuItem.click (/Users/dev/Documents/GitHub/Zerp-app-WebView/Electron/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/api/menu-item.js:48:17) 
at Function.executeCommand (/Users/dev/Documents/GitHub/Zerp-app-WebView/Electron/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/api/menu.js:32:17)

### Additional Information
Have defined the menu 'Copy' item as follows:
`{
        label: 'Copy', 
        accelerator: 'CmdOrCtrl+C', 
        click: (item, focusedWindow) => {
            focusedWindow.focusOnWebView();
            focusedWindow.webContents.send('copy-webview');
        }
    }`
The error occurs because the `focusedWindow` is undefined
Adding the check for `undefined` fixes the exception, but than nothing is copied

I'm new to Electron, so would appreciate any feedback

Thank you

**Comment by miniak** [comment]
You should use the `{ role: 'copy' }` instead of implementing custom logic
