### ISSUE TITLE
Can't get package using AES128-SHA256 to work with Electron

### ISSUE THREAD

**Issue by zachfeldman** [electron/electron#20759]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
7.0.0
* **Operating System:**
Mac Os Mojave 10.4.6

* **Last Known Working Electron version:**
N/A

### Expected Behavior
I'm trying to use the dorita980 Roomba lib with Electron https://github.com/koalazak/dorita980. When I try to bring the two together, their lib attempts to connect to the Roomba via TLS using the AES128-SHA256 cipher. From a few similar threads on here, it seems Electron using BoringSSL and/or doesn't support AES128-SHA256 out of the box.

### Actual Behavior
When I run electron appName.js, I get:

```
App threw an error during load
Error: error:100000b1:SSL routines:OPENSSL_internal:NO_CIPHER_MATCH
    at Object.createSecureContext (_tls_common.js:177:13)
    at Object.connect (_tls_wrap.js:1403:48)
    at Object.buildBuilder (/Users/zachfeldman/Dropbox/dev/vacuumBar/node_modules/mqtt/lib/connect/tls.js:13:20)
    at MqttClient.wrapper [as streamBuilder] (/Users/zachfeldman/Dropbox/dev/vacuumBar/node_modules/mqtt/lib/connect/index.js:140:36)
    at MqttClient._setupStream (/Users/zachfeldman/Dropbox/dev/vacuumBar/node_modules/mqtt/lib/client.js:277:22)
    at new MqttClient (/Users/zachfeldman/Dropbox/dev/vacuumBar/node_modules/mqtt/lib/client.js:258:8)
    at Object.connect (/Users/zachfeldman/Dropbox/dev/vacuumBar/node_modules/mqtt/lib/connect/index.js:143:10)
    at localV2 (/Users/zachfeldman/Dropbox/dev/vacuumBar/node_modules/dorita980/lib/v2/local.js:30:23)
    at new local (/Users/zachfeldman/Dropbox/dev/vacuumBar/node_modules/dorita980/index.js:17:10)
    at Object.<anonymous> (/Users/zachfeldman/Dropbox/dev/vacuumBar/vacuumBar.js:28:23)
    at Module._compile (internal/modules/cjs/loader.js:880:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10)
    at Module.load (internal/modules/cjs/loader.js:735:32)
    at Module._load (internal/modules/cjs/loader.js:648:12)
    at Module._load (electron/js2c/asar.js:715:26)
    at Function.Module._load (electron/js2c/asar.js:715:26)
    at loadApplicationPackage (/Users/zachfeldman/.nvm/versions/node/v9.11.1/lib/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js:109:16)
    at Object.<anonymous> (/Users/zachfeldman/.nvm/versions/node/v9.11.1/lib/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js:155:9)
    at Module._compile (internal/modules/cjs/loader.js:880:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10)
    at Module.load (internal/modules/cjs/loader.js:735:32)
    at Module._load (internal/modules/cjs/loader.js:648:12)
```

### To Reproduce
Any sample app with dorita980 that is run through the Electron command line runner seems to return this issue.

Thanks for any ideas, including how to build Electron with this Cipher, or how to add a Cipher in some way.

**Comment by David-Hari** [comment]
I just ran into this problem too. I'm using dorita980 and electron on Windows 10.
Anyone have a workaround?

**Comment by zachfeldman** [comment]
Hey @David-Hari in case it's helpful, here's the code for my project:
https://github.com/zachfeldman/vacuumbar

What I ended up doing is setting up two apps, one for the dorita980 commands that also has an express server, and an electron app that sends http requests to the express server. This is the only workaround that worked for me. Hope that helps!

**Comment by David-Hari** [comment]
That is a good idea, but I was really hoping for something quick and simple.
Sadly, there are no GUI frameworks for NodeJS that don't require a heap of non-js dependencies like Qt or Visual Studio tools.

I guess I'll just put this project on hold for now. Maybe I'll look at doing it in Python instead.

**Comment by zachfeldman** [comment]
Yeah it is kinda sad eh! What are you trying to do with dorita? Cool lib! I <3 my roomba

**Comment by David-Hari** [comment]
I was going to make a simple Windows app to do some basic things. Mainly just list the rooms and allow me to choose which ones I want to clean.

**Comment by David-Hari** [comment]
I found that it works (well, there are no errors. I haven't actually tried anything useful yet) when I set the cipher to `'AES128-SHA'` instead of `'AES128-SHA256'` on [this line](https://github.com/koalazak/dorita980/blob/52e4c02277d5eb552f6d1b2043a0bba6dd5cda92/lib/v2/local.js#L24).

A quick google of supported ciphers in BoringSSL turned up [this file](https://github.com/google/boringssl/blob/master/include/openssl/tls1.h), which does mention `AES128-SHA256`. But that is listed under the comment `// TLS v1.2 ciphersuites`, so perhaps it is not supported by Electron.

I don't know enough about security to make sense of this, but it would be nice to have an option to pass the type of cipher to dorita980 so it could be overridden.

**Comment by zachfeldman** [comment]
Ahh nice. Yeah I've been really enjoying my menubar app so I get it!

Totally wish I could just combine the two apps, maybe someone who's more familiar with electron will give us a good answer one day. It's a great project nonetheless :)

**Comment by David-Hari** [comment]
I think this is more on @koalazak now, rather than the Electron devs. Assuming that dorita980 can indeed work with other ciphers.

**Comment by nornagon** [comment]
Glad you got it to work! It does seem like boringssl doesn't support that cipher suite, and I think it's beyond us to add it, but working with AES128-SHA seems like a good option if that's available to you. I'm closing this issue since it seems like you've found a path forward, but if you hit another roadblock feel free to comment and I can reopen.

**Comment by koalazak** [comment]
> I think this is more on @koalazak now, rather than the Electron devs. Assuming that dorita980 can indeed work with other ciphers.

some combinations of `robots models+openssl+node version` only works with `AES128-SHA256` connecting to some robots. You can see the thread of the decision here:
https://github.com/koalazak/dorita980/issues/95
https://github.com/koalazak/dorita980/issues/88

So `AES128-SHA256` works with all robots but other cyphers don't.
Anyway I can add an environment variable to allow you to overwrite this value in dorita980 under your responsability :p. 
Lets follow the issue in https://github.com/koalazak/dorita980/issues/102
thank you
