### ISSUE TITLE
Can't Install Electron correctly

### ISSUE THREAD

**Issue by wonderlandpark** [electron/electron#20761]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 7.0.0
* **Operating System:**
  * Raspbian GNU/Linux 9.4
* **Last Known Working Electron version:**
  * N/A

### Expected Behavior
Electron Package should be installed

### Actual Behavior
```
root@pi:/home/pi/MagicMirror# npm i electron@latest

> electron@7.0.0 postinstall /home/pi/MagicMirror/node_modules/electron
> node install.js

(node:1928) UnhandledPromiseRejectionWarning: HTTPError: Response code 404 (Not Found)
    at EventEmitter.emitter.on.response (/home/pi/MagicMirror/node_modules/got/source/as-stream.js:35:24)
    at EventEmitter.emit (events.js:180:13)
    at module.exports (/home/pi/MagicMirror/node_modules/got/source/get-response.js:22:10)
    at ClientRequest.handleResponse (/home/pi/MagicMirror/node_modules/got/source/request-as-event-emitter.js:155:5)
    at Object.onceWrapper (events.js:272:13)
    at ClientRequest.emit (events.js:185:15)
    at ClientRequest.origin.emit.args [as emit] (/home/pi/MagicMirror/node_modules/@szmarczak/http-timer/source/index.js:37:11)
    at HTTPParser.parserOnIncomingClient (_http_client.js:540:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:117:17)
    at TLSSocket.socketOnData (_http_client.js:445:20)
(node:1928) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1928) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
+ electron@7.0.0
added 2 packages in 40.967s
```
Then When I run the Project,
```

/home/pi/MagicMirror/node_modules/electron/index.js:14
    throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again')
    ^

Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
    at getElectronPath (/home/pi/MagicMirror/node_modules/electron/index.js:14:11)
    at Object.<anonymous> (/home/pi/MagicMirror/node_modules/electron/index.js:18:18)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at Object.<anonymous> (/home/pi/MagicMirror/node_modules/electron/cli.js:3:16)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! magicmirror@2.9.0 start: `sh run-start.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the magicmirror@2.9.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-10-27T00_35_37_411Z-debug.log
```

Also, when I reinstall, it has same issue.

### To Reproduce
Just do `npm i latest`

**Comment by wonderlandpark** [comment]
Opps, duplicate of #20723

**Comment by DevinKott-KA** [comment]
At least it's nice to know that I'm not crazy!

**Comment by xiaoshan5733** [comment]
I solved the problem, you should config like this in your ~/.npmrc file:

```
arch=armv7l
```

You can get arch from `uname -m`

**Comment by tycrek** [comment]
Adding on to @xiaoshan5733 , if you want to use command line parameters, I used the following:

`sudo npm i -g electron --arch=armv7l`
