### ISSUE TITLE
Electronic installation failed

### ISSUE THREAD

**Issue by imxue** [electron/electron#21054]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  *  7.1.1
* **Operating System:**
  *  Windows 10 
* **Last Known Working Electron version:**
  *  6.0.0
### Expected Behavior

Electronic startup success
### Actual Behavior

E:\electron-quick-start\node_modules\electron\index.js:14
    throw new Error('Electron failed to install correctly, please delete node_mo
dules/electron and try installing again')
    ^

Error: Electron failed to install correctly, please delete node_modules/electron
 and try installing again
    at getElectronPath (E:\electron-quick-start\node_modules\electron\index.js:1
4:11)
    at Object.<anonymous> (E:\electron-quick-start\node_modules\electron\index.j
s:18:18)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:947:10)
    at Module.load (internal/modules/cjs/loader.js:790:32)
    at Function.Module._load (internal/modules/cjs/loader.js:703:12)
    at Module.require (internal/modules/cjs/loader.js:830:19)
    at require (internal/modules/cjs/helpers.js:68:18)
    at Object.<anonymous> (E:\electron-quick-start\node_modules\electron\cli.js:
3:16)
    at Module._compile (internal/modules/cjs/loader.js:936:30)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this comm
and.

### Additional Information

I tried to delete node_modules  , reinstall but still not

**Comment by luy19** [comment]
You should search the issue tracker: https://github.com/electron/get/issues/124#issuecomment-549157747
