### ISSUE TITLE
 LoopBack connector "loopback-connector-sqlite3" is not installed

### ISSUE THREAD

**Issue by satheshramasamy** [electron/electron#21092]
tprs_api@1.0.0 start C:\Users\RD\Documents\TPRS\tprs_api
> electron index.js

 C:\Users\RD\AppData\Roaming\Electron\database.sqlite3

WARNING: LoopBack connector "loopback-connector-sqlite3" is not installed as any of the following modules:

 ./connectors/loopback-connector-sqlite3
loopback-connector-sqlite3

To fix, run:

    npm install loopback-connector-sqlite3 --save

(node:6472) UnhandledPromiseRejectionWarning: Error:
WARNING: LoopBack connector "loopback-connector-sqlite3" is not installed as any of the following modules:

 ./connectors/loopback-connector-sqlite3
loopback-connector-sqlite3

To fix, run:

    npm install loopback-connector-sqlite3 --save

    at DataSource.setup (C:\Users\RD\Documents\TPRS\tprs_api\node_modules\loopback-datasource-juggler\lib\datasource.js:448:26)
    at new DataSource (C:\Users\RD\Documents\TPRS\tprs_api\node_modules\loopback-datasource-juggler\lib\datasource.js:138:8)
    at Registry.createDataSource (C:\Users\RD\Documents\TPRS\tprs_api\node_modules\loopback\lib\registry.js:364:12)
    at Function.loopback.createDataSource (C:\Users\RD\Documents\TPRS\tprs_api\node_modules\loopback\lib\loopback.js:347:41)
    at C:\Users\RD\Documents\TPRS\tprs_api\server\server.js:68:33
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
(node:6472) UnhandledPromiseRejectionWarning: Error:
WARNING: LoopBack connector "loopback-connector-sqlite3" is not installed as any of the following modules:

 ./connectors/loopback-connector-sqlite3
loopback-connector-sqlite3

To fix, run:

    npm install loopback-connector-sqlite3 --save

    at DataSource.setup (C:\Users\RD\Documents\TPRS\tprs_api\node_modules\loopback-datasource-juggler\lib\datasource.js:448:26)
    at new DataSource (C:\Users\RD\Documents\TPRS\tprs_api\node_modules\loopback-datasource-juggler\lib\datasource.js:138:8)
    at Registry.createDataSource (C:\Users\RD\Documents\TPRS\tprs_api\node_modules\loopback\lib\registry.js:364:12)
    at Function.loopback.createDataSource (C:\Users\RD\Documents\TPRS\tprs_api\node_modules\loopback\lib\loopback.js:347:41)
    at C:\Users\RD\Documents\TPRS\tprs_api\server\server.js:68:33
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
(node:6472) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6472) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6472) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:6472) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

pls help me!

**Comment by codebytere** [comment]
This does not seem to be an issue with Electron - all errors in that stacktrace originate from Node.js itself. I recommend seeking more help from either the module itself, or Node.js.
