### ISSUE TITLE
Only on test : `Error: Electron failed to install correctly, please delete node_modules/electron and try installing again`

### ISSUE THREAD

**Issue by Vilsafur** [electron/electron#21220]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v6.1.4
* **Operating System:**
  * Windows 10 x64
* **Last Known Working Electron version:**
  * ?

### Expected Behavior
I need to run `npm test`, work fine if I run `npm run electron:serve`

### Actual Behavior
I got this error :
```
RUNTIME EXCEPTION  Exception occurred while loading your tests

Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
    at getElectronPath (C:\Users\cyril.poidevin\Documents\Repositories\Tools\deploiement-doc\dist\webpack:\node_modules\electron\index.js:14:1)
    at Object.<anonymous> (C:\Users\cyril.poidevin\Documents\Repositories\Tools\deploiement-doc\dist\webpack:\node_modules\electron\index.js:18:1)
    at Object../node_modules/electron/index.js (C:\Users\cyril.poidevin\Documents\Repositories\Tools\deploiement-doc\dist\main.js:49016:30)
    at __webpack_require__ (C:\Users\cyril.poidevin\Documents\Repositories\Tools\deploiement-doc\dist\webpack:\webpack\bootstrap:19:1)
    at Module../src/store/Base/actions.ts (C:\Users\cyril.poidevin\Documents\Repositories\Tools\deploiement-doc\dist\webpack:\src\store\Base\actions.ts:1:1)
    at __webpack_require__ (C:\Users\cyril.poidevin\Documents\Repositories\Tools\deploiement-doc\dist\webpack:\webpack\bootstrap:19:1)
    at Module../src/store/Base/index.ts (C:\Users\cyril.poidevin\Documents\Repositories\Tools\deploiement-doc\dist\webpack:\src\store\Base\index.ts:1:1)    
    at __webpack_require__ (C:\Users\cyril.poidevin\Documents\Repositories\Tools\deploiement-doc\dist\webpack:\webpack\bootstrap:19:1)
    at Module../tests/unit/components/Base.spec.ts (C:\Users\cyril.poidevin\Documents\Repositories\Tools\deploiement-doc\dist\webpack:\tests\unit\components\Base.spec.ts:1:1)
    at __webpack_require__ (C:\Users\cyril.poidevin\Documents\Repositories\Tools\deploiement-doc\dist\webpack:\webpack\bootstrap:19:1)
    at run (C:\Users\cyril.poidevin\Documents\Repositories\Tools\deploiement-doc\dist\webpack:\node_modules\mochapack\lib\entry.js:3:1)
    at Array.forEach (<anonymous>)
    at Object../node_modules/mochapack/lib/entry.js (C:\Users\cyril.poidevin\Documents\Repositories\Tools\deploiement-doc\dist\webpack:\node_modules\mochapack\lib\entry.js:10:1)
    at __webpack_require__ (C:\Users\cyril.poidevin\Documents\Repositories\Tools\deploiement-doc\dist\webpack:\webpack\bootstrap:19:1)
    at C:\Users\cyril.poidevin\Documents\Repositories\Tools\deploiement-doc\dist\webpack:\webpack\bootstrap:83:1
    at Object.<anonymous> (C:\Users\cyril.poidevin\Documents\Repositories\Tools\deploiement-doc\dist\main.js:87:10)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object._module2.default._extensions.<computed> [as .js] (C:\Users\cyril.poidevin\Documents\Repositories\Tools\deploiement-doc\node_modules\mochapack\src\util\registerRequireHook.js:99:12)
    at Module.load (internal/modules/cjs/loader.js:914:32)
    at Function.Module._load (internal/modules/cjs/loader.js:822:14)
    at Module.require (internal/modules/cjs/loader.js:956:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at C:\Users\cyril.poidevin\Documents\Repositories\Tools\deploiement-doc\node_modules\mocha\lib\mocha.js:334:36
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (C:\Users\cyril.poidevin\Documents\Repositories\Tools\deploiement-doc\node_modules\mocha\lib\mocha.js:331:14)
    at Mocha.run (C:\Users\cyril.poidevin\Documents\Repositories\Tools\deploiement-doc\node_modules\mocha\lib\mocha.js:809:10)
    at cb (C:\Users\cyril.poidevin\Documents\Repositories\Tools\deploiement-doc\node_modules\mochapack\src\runner\TestRunner.js:96:21)
    at C:\Users\cyril.poidevin\Documents\Repositories\Tools\deploiement-doc\node_modules\mochapack\src\webpack\compiler\registerReadyCallback.js:12:7
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\cyril.poidevin\Documents\Repositories\Tools\deploiement-doc\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:61:1)     
    at AsyncSeriesHook.lazyCompileHook (C:\Users\cyril.poidevin\Documents\Repositories\Tools\deploiement-doc\node_modules\tapable\lib\Hook.js:154:20)
    at C:\Users\cyril.poidevin\Documents\Repositories\Tools\deploiement-doc\node_modules\webpack\lib\Compiler.js:304:22
    at Compiler.emitRecords (C:\Users\cyril.poidevin\Documents\Repositories\Tools\deploiement-doc\node_modules\webpack\lib\Compiler.js:499:39)
    at C:\Users\cyril.poidevin\Documents\Repositories\Tools\deploiement-doc\node_modules\webpack\lib\Compiler.js:298:10
    at C:\Users\cyril.poidevin\Documents\Repositories\Tools\deploiement-doc\node_modules\webpack\lib\Compiler.js:485:14
    at eval (eval at create (C:\Users\cyril.poidevin\Documents\Repositories\Tools\deploiement-doc\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:14:1)
    at callback (C:\Users\cyril.poidevin\Documents\Repositories\Tools\deploiement-doc\node_modules\copy-webpack-plugin\dist\index.js:126:17)
    at afterEmit (C:\Users\cyril.poidevin\Documents\Repositories\Tools\deploiement-doc\node_modules\copy-webpack-plugin\dist\index.js:220:13)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\cyril.poidevin\Documents\Repositories\Tools\deploiement-doc\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:10:1)     
    at AsyncSeriesHook.lazyCompileHook (C:\Users\cyril.poidevin\Documents\Repositories\Tools\deploiement-doc\node_modules\tapable\lib\Hook.js:154:20)
    at C:\Users\cyril.poidevin\Documents\Repositories\Tools\deploiement-doc\node_modules\webpack\lib\Compiler.js:482:27
    at C:\Users\cyril.poidevin\Documents\Repositories\Tools\deploiement-doc\node_modules\neo-async\async.js:2818:7
    at done (C:\Users\cyril.poidevin\Documents\Repositories\Tools\deploiement-doc\node_modules\neo-async\async.js:3522:9)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\cyril.poidevin\Documents\Repositories\Tools\deploiement-doc\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:4:1)      
    at C:\Users\cyril.poidevin\Documents\Repositories\Tools\deploiement-doc\node_modules\webpack\lib\Compiler.js:464:33
    at MemoryFileSystem.writeFile (C:\Users\cyril.poidevin\Documents\Repositories\Tools\deploiement-doc\node_modules\memory-fs\lib\MemoryFileSystem.js:328:9)
    at writeOut (C:\Users\cyril.poidevin\Documents\Repositories\Tools\deploiement-doc\node_modules\webpack\lib\Compiler.js:462:30)
    at C:\Users\cyril.poidevin\Documents\Repositories\Tools\deploiement-doc\node_modules\webpack\lib\Compiler.js:476:7
    at arrayIterator (C:\Users\cyril.poidevin\Documents\Repositories\Tools\deploiement-doc\node_modules\neo-async\async.js:3467:9)
    at done (C:\Users\cyril.poidevin\Documents\Repositories\Tools\deploiement-doc\node_modules\neo-async\async.js:3527:9)
    at AsyncSeriesHook.eval [as callAsync] (eval at create (C:\Users\cyril.poidevin\Documents\Repositories\Tools\deploiement-doc\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:4:1)      
    at C:\Users\cyril.poidevin\Documents\Repositories\Tools\deploiement-doc\node_modules\webpack\lib\Compiler.js:464:33
    at MemoryFileSystem.writeFile (C:\Users\cyril.poidevin\Documents\Repositories\Tools\deploiement-doc\node_modules\memory-fs\lib\MemoryFileSystem.js:328:9)
    at writeOut (C:\Users\cyril.poidevin\Documents\Repositories\Tools\deploiement-doc\node_modules\webpack\lib\Compiler.js:462:30)
    at C:\Users\cyril.poidevin\Documents\Repositories\Tools\deploiement-doc\node_modules\webpack\lib\Compiler.js:476:7
    at arrayIterator (C:\Users\cyril.poidevin\Documents\Repositories\Tools\deploiement-doc\node_modules\neo-async\async.js:3467:9)
    at timesSync (C:\Users\cyril.poidevin\Documents\Repositories\Tools\deploiement-doc\node_modules\neo-async\async.js:2297:7)
    at Object.eachLimit (C:\Users\cyril.poidevin\Documents\Repositories\Tools\deploiement-doc\node_modules\neo-async\async.js:3463:5)
    at emitFiles (C:\Users\cyril.poidevin\Documents\Repositories\Tools\deploiement-doc\node_modules\webpack\lib\Compiler.js:358:13)
    at Immediate._onImmediate (C:\Users\cyril.poidevin\Documents\Repositories\Tools\deploiement-doc\node_modules\memory-fs\lib\MemoryFileSystem.js:288:4)
    at processImmediate (internal/timers.js:439:21)
    at process.topLevelDomainCallback (domain.js:130:23)
```

### To Reproduce
I use electron installed by vue-cli.
In a store, I've this code:
```javascript
import { remote } from 'electron';
...
const configPath = remote.getGlobal('configPath');
```

If I replace `const configPath = remote.getGlobal('configPath');` by `const configPath = './';`, my tests pass.

**Comment by MarshallOfSound** [comment]
> I need to run npm test, work fine if I run npm run electron:serve

This sounds like an issue with your app or vue, not with Electron itself

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron or code assistance requests should be directed to the [community](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support) or to the [Slack Channel](https://github.com/electron/electron/blob/master/docs/tutorial/support.md#finding-support).

**Comment by Vilsafur** [comment]
Ok, sorry for inconvenience, I post in the community forum.
