### ISSUE TITLE
electron-rebuild error

### ISSUE THREAD

**Issue by nbsu** [electron/electron#21492]
**1. I use ffi to call c++ dll , then I got error as follow, and I connot found NODE_MODULE_VERSION 69 in node release list, WHY ?**
Error: The module '\\?\C:\WORK\mgtv\node_modules\ref\build\Release\binding.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 64. This version of Node.js requires
NODE_MODULE_VERSION 69. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:160:31)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at bindings (C:\WORK\mgtv\node_modules\bindings\bindings.js:76:44)
    at Object.<anonymous> (C:\WORK\mgtv\node_modules\ref\lib\ref.js:5:47)

**2.  I try to .\node_modules\.bin\electron-rebuild.cmd, but still error. 
    It seems I can't download file from gh-contractor-zcbenz.s3.amazonaws.com. 
     How to config to use local file (node-v4.0.8-headers.tar.gz) ?**
× Rebuild Failed

An unhandled error occurred inside electron-rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@6.0.1
gyp info using node@10.11.0 | win32 | x64
gyp info find Python using Python version 2.7.14 found at "C:\Python27\python.exe"
gyp http GET https://electronjs.org/headers/v4.0.8/node-v4.0.8-headers.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: getaddrinfo ENOENT gh-contractor-zcbenz.s3.amazonaws.com gh-contractor-zcbenz.s3.amazonaws.com:443

gyp ERR! stack     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\WORK\\mgtv\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebui
ld" "--target=4.0.8" "--arch=x64" "--dist-url=https://electronjs.org/headers" "--build-from-source" "--msvs_version=2015
"
gyp ERR! cwd C:\WORK\mgtv\node_modules\ffi
gyp ERR! node -v v10.11.0
gyp ERR! node-gyp -v v6.0.1
gyp ERR! not ok

Failed with exit code: 1

Error: gyp info it worked if it ends with ok
gyp info using node-gyp@6.0.1
gyp info using node@10.11.0 | win32 | x64
gyp info find Python using Python version 2.7.14 found at "C:\Python27\python.exe"
gyp http GET https://electronjs.org/headers/v4.0.8/node-v4.0.8-headers.tar.gz
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: getaddrinfo ENOENT gh-contractor-zcbenz.s3.amazonaws.com gh-contractor-zcbenz.s3.amazonaws.com:443

gyp ERR! stack     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:57:26)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\WORK\\mgtv\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebui
ld" "--target=4.0.8" "--arch=x64" "--dist-url=https://electronjs.org/headers" "--build-from-source" "--msvs_version=2015
"
gyp ERR! cwd C:\WORK\mgtv\node_modules\ffi
gyp ERR! node -v v10.11.0
gyp ERR! node-gyp -v v6.0.1
gyp ERR! not ok

Failed with exit code: 1
    at SafeSubscriber._error (C:\WORK\mgtv\node_modules\spawn-rx\lib\src\index.js:267:84)
    at SafeSubscriber.__tryOrUnsub (C:\WORK\mgtv\node_modules\rxjs\internal\Subscriber.js:205:16)
    at SafeSubscriber.error (C:\WORK\mgtv\node_modules\rxjs\internal\Subscriber.js:156:26)
    at Subscriber._error (C:\WORK\mgtv\node_modules\rxjs\internal\Subscriber.js:92:26)
    at Subscriber.error (C:\WORK\mgtv\node_modules\rxjs\internal\Subscriber.js:72:18)
    at MapSubscriber.Subscriber._error (C:\WORK\mgtv\node_modules\rxjs\internal\Subscriber.js:92:26)
    at MapSubscriber.Subscriber.error (C:\WORK\mgtv\node_modules\rxjs\internal\Subscriber.js:72:18)
    at SafeSubscriber._next (C:\WORK\mgtv\node_modules\spawn-rx\lib\src\index.js:242:65)
    at SafeSubscriber.__tryOrUnsub (C:\WORK\mgtv\node_modules\rxjs\internal\Subscriber.js:205:16)
    at SafeSubscriber.next (C:\WORK\mgtv\node_modules\rxjs\internal\Subscriber.js:143:22)

**Comment by MarshallOfSound** [comment]
This issue is for `electron-rebuild` not `electron` itself.  Please follow that projects issue guidelines
