### ISSUE TITLE
Post install is failing

### ISSUE THREAD

**Issue by achamsanjeevakumar** [electron/electron#21637]
i am trying of current version of electron. but running into following issue. However issues doesn't exist with version ^5.0.0

> electron@7.1.7 postinstall /Users/sacham/codeBase/playarea/electron/electron-quick-start/node_modules/electron
> node install.js

(node:8336) UnhandledPromiseRejectionWarning: RequestError: self signed certificate in certificate chain
    at ClientRequest.<anonymous> (/Users/sacham/codeBase/playarea/electron/electron-quick-start/node_modules/got/source/request-as-event-emitter.js:178:14)
    at Object.onceWrapper (events.js:300:26)
    at ClientRequest.emit (events.js:215:7)
    at ClientRequest.origin.emit (/Users/sacham/codeBase/playarea/electron/electron-quick-start/node_modules/@szmarczak/http-timer/source/index.js:37:11)
    at TLSSocket.socketErrorListener (_http_client.js:406:9)
    at TLSSocket.emit (events.js:210:5)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(node:8336) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:8336) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
npm notice created a lockfile as package-lock.json. You should commit this file.
+ electron@7.1.7

**Comment by lizeze** [comment]
Will it be the reason of your network

**Comment by achamsanjeevakumar** [comment]
Other things are working properly, not sure why is issue with electron@7.1.7

**Comment by jdfwarrior** [comment]
It's something they changed in version > 7. I've seen it mentioned elsewhere but the issue got closed. Not sure why as it is still affecting people

**Comment by codebytere** [comment]
This should be working correctly in all supported versions of Electron.

**Comment by allanbowe** [comment]
I get the same behaviour on a windows install inside a corporate firewall
