### ISSUE TITLE
Electron cannot execute typescript

### ISSUE THREAD

**Issue by Rokt33r** [electron/electron#21688]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
v7.1.7
* **Operating System:**
macOS 10.14.6

### Expected Behavior
Electron can execute typescript.

> Announcing TypeScript support in Electron https://electronjs.org/blog/typescript

### Actual Behavior

It throws an error.

```
App threw an error during load
~/src/main/app.ts:1
import { app, BrowserWindow } from 'electron'
^^^^^^

SyntaxError: Cannot use import statement outside a module
    at Module._compile (internal/modules/cjs/loader.js:815:22)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10)
    at Module.load (internal/modules/cjs/loader.js:735:32)
    at Module._load (internal/modules/cjs/loader.js:648:12)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at loadApplicationPackage (~/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js:109:16)
    at Object.<anonymous> (~/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js:155:9)
    at Module._compile (internal/modules/cjs/loader.js:880:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:892:10)
```

### To Reproduce

Create `main.ts`

```ts
import { app, BrowserWindow } from 'electron'

let win: BrowserWindow | null = null

app.on('ready', () => {
  win = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      nodeIntegration: true
    }
  })
})

```

Run it with `electron`

```sh
electron main.ts
```

**Comment by MarshallOfSound** [comment]
That blog post only refers to generating type defs for Electron, it doesn't specify anywhere that Electron can run typescript without transpilation
