### ISSUE TITLE
Provide Electron 7 pre-built binary for arm32v7 (e.g. raspberry pi 3 and 4)

### ISSUE THREAD

**Issue by Ciantic** [electron/electron#22004]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for a feature request that matches the one I want to file, without success.

### Problem Description

Electron 7 does not have pre-built binaries for arm32v7 e.g. raspberry pi 4 (with current raspbian which is still 32bit) and raspberry pi 3.

Dockerfile
```Dockerfile
FROM arm32v7/node

WORKDIR /foo
RUN npm init -y
RUN npm install electron@^7 --unsafe-perm
```

Throws error:

```
> electron@7.1.11 postinstall /foo/node_modules/electron
> node install.js

(node:38) UnhandledPromiseRejectionWarning: HTTPError: Response code 404 (Not Found)
```

However it works just fine with `arm64v8/node` because Electron does provide arm64 binaries.

Note for Electron 6 there exists arm32v7 binaries, so I have to resort using Electron 6 branch.

**Comment by malept** [comment]
What is the output when you run the following on your Raspberry Pi 3, Raspberry Pi 4, and the Docker container:

```
uname -m
node --eval='console.log(os.platform()); console.log(os.arch()); console.log(process.config.variables.arm_version)'

**Comment by Ciantic** [comment]
@malept

```
docker run --rm -it arm32v7/node /bin/bash
root@9c5bef0bb0a5:/# uname -m
armv7l
root@9c5bef0bb0a5:/# node --eval='console.log(os.platform()); console.log(os.arch()); console.log(process.config.variables.arm_version)'
linux
arm
7
```

Note, I ran that in the Docker which uses the arm emulation. I build the RPI images using docker. 

However notice that `npm install electron@^6 --unsafe-perm` works just fine, so something is wrong with Electron 7.

**Comment by malept** [comment]
Can you run:

```
DEBUG='@electron/get:*' npm install electron@^7 --unsafe-perm
```

and paste the output here? _(Preferably inside a `<details>` tag for issue brevity)_

**Comment by Ciantic** [comment]
Okay here it is. I just wonder, do you have Docker? It should be easy for you to try.

<details>
```
> core-js@3.6.4 postinstall /foo/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> electron@7.1.11 postinstall /foo/node_modules/electron
> node install.js

  @electron/get:index Checking the cache for electron-v7.1.11-linux-arm.zip (https://github.com/electron/electron/releases/download/v7.1.11/electron-v7.1.11-linux-arm.zip) +0ms
  @electron/get:index Cache miss +47ms
  @electron/get:index Downloading https://github.com/electron/electron/releases/download/v7.1.11/electron-v7.1.11-linux-arm.zip to /tmp/electron-download-tMNEVs/electron-v7.1.11-linux-arm.zip with options: undefined +224ms
(node:73) UnhandledPromiseRejectionWarning: HTTPError: Response code 404 (Not Found)
    at EventEmitter.<anonymous> (/foo/node_modules/got/source/as-stream.js:35:24)
    at EventEmitter.emit (events.js:321:20)
    at module.exports (/foo/node_modules/got/source/get-response.js:22:10)
    at ClientRequest.handleResponse (/foo/node_modules/got/source/request-as-event-emitter.js:155:5)
    at Object.onceWrapper (events.js:428:26)
    at ClientRequest.emit (events.js:333:22)
    at ClientRequest.origin.emit (/foo/node_modules/@szmarczak/http-timer/source/index.js:37:11)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:602:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:17)
    at TLSSocket.socketOnData (_http_client.js:471:22)
(node:73) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:73) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN foo@1.0.0 No description
npm WARN foo@1.0.0 No repository field.

+ electron@7.1.11
added 85 packages from 91 contributors and audited 102 packages in 33.207s

2 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
```
</details>

**Comment by malept** [comment]
Docker only works for that container if you're running it on ARM hardware.

**Comment by Ciantic** [comment]
Same problem applies to Docker inside raspberry pi itself:

<details>

```
pi@raspberrypi:~ $ docker run --rm -it node /bin/bash
Unable to find image 'node:latest' locally
latest: Pulling from library/node
cc3b08e804cc: Pull complete
aa649f4f33c2: Pull complete
901c0c16dce9: Pull complete
715a264d83dc: Pull complete
854dcba3350b: Pull complete
301cb43662ca: Pull complete
d8abae2f3fa7: Pull complete
df6ac69ad783: Pull complete
2cfe42dd85fa: Pull complete
Digest: sha256:944f469fc0eb34391766f9598d094a38f3fd629791c43972abfa2ce3b1b587f6
Status: Downloaded newer image for node:latest
root@20a0d3b56b51:/# mkdir /foo
root@20a0d3b56b51:/# cd /foo/
root@20a0d3b56b51:/foo# npm init -y
Wrote to /foo/package.json:

{
  "name": "foo",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}


root@20a0d3b56b51:/foo# DEBUG='@electron/get:*' npm install electron@^7 --unsafe-perm

> core-js@3.6.4 postinstall /foo/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon:
> https://opencollective.com/core-js
> https://www.patreon.com/zloirock

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> electron@7.1.11 postinstall /foo/node_modules/electron
> node install.js

  @electron/get:index Checking the cache for electron-v7.1.11-linux-arm.zip (https://github.com/electron/electron/releases/download/v7.1.11/electron-v7.1.11-linux-arm.zip) +0ms
  @electron/get:index Cache miss +11ms
  @electron/get:index Downloading https://github.com/electron/electron/releases/download/v7.1.11/electron-v7.1.11-linux-arm.zip to /tmp/electron-download-QlmUdG/electron-v7.1.11-linux-arm.zip with options: undefined +101ms
(node:39) UnhandledPromiseRejectionWarning: HTTPError: Response code 404 (Not Found)
    at EventEmitter.<anonymous> (/foo/node_modules/got/source/as-stream.js:35:24)
    at EventEmitter.emit (events.js:321:20)
    at module.exports (/foo/node_modules/got/source/get-response.js:22:10)
    at ClientRequest.handleResponse (/foo/node_modules/got/source/request-as-event-emitter.js:155:5)
    at Object.onceWrapper (events.js:428:26)
    at ClientRequest.emit (events.js:333:22)
    at ClientRequest.origin.emit (/foo/node_modules/@szmarczak/http-timer/source/index.js:37:11)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:602:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:116:17)
    at TLSSocket.socketOnData (_http_client.js:471:22)
(node:39) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:39) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN foo@1.0.0 No description
npm WARN foo@1.0.0 No repository field.

+ electron@7.1.11
added 85 packages from 91 contributors and audited 102 packages in 14.95s

2 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

```

</details>

**Comment by Ciantic** [comment]
Problem begins from this line:

https://github.com/electron/electron/blob/master/npm/install.js#L28

<details>

```console
pi@raspberrypi:~ $ docker run --rm -it node
Welcome to Node.js v13.7.0.
Type ".help" for more information.
> process.arch
'arm'
>  process.env.npm_config_arch
undefined
>

```

</details>

**Comment by Ciantic** [comment]
And here it is without any Docker, for those who wonder will it work with Raspbian, the answer is nope:

<details>

```console
pi@raspberrypi:~/temp $ wget https://nodejs.org/dist/v12.14.1/node-v12.14.1-linux-armv7l.tar.xz
--2020-02-05 18:24:21--  https://nodejs.org/dist/v12.14.1/node-v12.14.1-linux-armv7l.tar.xz
Resolving nodejs.org (nodejs.org)... 2606:4700:10::6814:162e, 2606:4700:10::6814:172e, 104.20.23.46, ...
Connecting to nodejs.org (nodejs.org)|2606:4700:10::6814:162e|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 12332096 (12M) [application/x-xz]
Saving to: ‘node-v12.14.1-linux-armv7l.tar.xz’

node-v12.14.1-linux-armv7l.tar.xz                           100%[=========================================================================================================================================>]  11.76M  5.43MB/s    in 2.2s

2020-02-05 18:24:24 (5.43 MB/s) - ‘node-v12.14.1-linux-armv7l.tar.xz’ saved [12332096/12332096]

pi@raspberrypi:~/temp $ tar -xf node-v12.14.1-linux-armv7l.tar.xz
pi@raspberrypi:~/temp $ cd node-v12.14.1-linux-armv7l/
pi@raspberrypi:~/temp/node-v12.14.1-linux-armv7l $ cd bin/
pi@raspberrypi:~/temp/node-v12.14.1-linux-armv7l/bin $ node
> process.arch
'arm'
> process.env.npm_config_arch
undefined
> process.platform
'linux'

```

</details>

**Comment by malept** [comment]
> Which is running with ARM hardware... (Btw Docker for Windows and Mac uses ARM emulation when you use base images `arm32v7/*` so it's reproducible with them too. You can literally build a ARM binary inside Windows with those images and it's readily usable with arm hardware.)

I don't currently have access to any computer that can install Docker for Windows or Mac.

Anyway, the problem here is that the following code is not working correctly and I'm not sure why:

https://github.com/electron/get/blob/ba2119f4b15e33f64f11b054add51d8491d1264a/src/utils.ts#L49-L73

**Comment by Ciantic** [comment]
@malept I Found the bug!

<details>
https://github.com/electron/get/blob/master/src/index.ts#L64-L68

```typescript
  const artifactDetails: ElectronArtifactDetails = _artifactDetails.isGeneric
    ? {
        ..._artifactDetails,
      }
    : {
        platform: process.platform,
        arch: getHostArch(),
        ..._artifactDetails, // <------------- THIS LINE OVERWRITES THE ARCH!
      };
```

because post_install also includes arch:


https://github.com/electron/electron/blob/master/npm/install.js#L28

```javascript
downloadArtifact({
  version,
  artifactName: 'electron',
  force: process.env.force_no_cache === 'true',
  cacheRoot: process.env.electron_config_cache,
  platform: process.env.npm_config_platform || process.platform,
  arch: process.env.npm_config_arch || process.arch
})
```

</details>

**Comment by malept** [comment]
Ah, that'd do it. I have a fix.
