### ISSUE TITLE
Loading a PDF shows a grey screen on 9.x

### ISSUE THREAD

**Issue by nornagon** [electron/electron#22286]
### Issue Details

* **Electron Version:**
  * 9.0.0-beta.2
* **Operating System:**
  * macOS
* **Last Known Working Electron version:**
  * Works in 10.x

### Expected Behavior
The PDF should be displayed when loading.

### Actual Behavior
A gray background is shown, with icons overlaid. This shows in the console:

```
[73878:0219/111910.348869:INFO:CONSOLE(0)] "(BLESSED_EXTENSION context for mhjfbmdgcfjbbpaeojofohoefgiehjai) extensions::mimeHandlerPrivate:21: Uncaught ReferenceError: Mojo is not defined{ReferenceError: Mojo is not defined
    at extensions::mimeHandlerPrivate:21:1
    at chrome-extension://mhjfbmdgcfjbbpaeojofohoefgiehjai/browser_api.js:169:19
    at new Promise (<anonymous>)
    at createBrowserApiForMimeHandlerView (chrome-extension://mhjfbmdgcfjbbpaeojofohoefgiehjai/browser_api.js:168:10)
    at createBrowserApi (chrome-extension://mhjfbmdgcfjbbpaeojofohoefgiehjai/browser_api.js:238:10)
    at main (chrome-extension://mhjfbmdgcfjbbpaeojofohoefgiehjai/main.js:83:15)
    at chrome-extension://mhjfbmdgcfjbbpaeojofohoefgiehjai/main.js:93:1}", source: chrome-extension://mhjfbmdgcfjbbpaeojofohoefgiehjai/index.html (0)
[73878:0219/111910.349162:ERROR:extension_function_dispatcher.cc(473)] Unknown Extension API - mimeHandlerPrivate.getStreamInfo
[73878:0219/111910.371171:INFO:CONSOLE(0)] "Unchecked runtime.lastError: Access to extension API denied.", source: chrome-extension://mhjfbmdgcfjbbpaeojofohoefgiehjai/index.html (0)
[73878:0219/111910.373402:INFO:CONSOLE(174)] "Uncaught (in promise) TypeError: Cannot read property 'tabId' of undefined", source: chrome-extension://mhjfbmdgcfjbbpaeojofohoefgiehjai/browser_api.js (174)
[73878:0219/111912.912978:INFO:CONSOLE(0)] "The resource https://royalsocietypublishing.org/wro/ie23~product.css was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.", source:  (0)
[73878:0219/111912.913081:INFO:CONSOLE(0)] "The resource https://royalsocietypublishing.org/wro/ie23~product.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.", source:  (0)
```

### To Reproduce
Run this in 9.0.0-beta.2: https://gist.github.com/c98208fa8158be6c6bbeeb812cfdeb73

**Comment by sofianguy** [comment]
fixed https://github.com/electron/electron/pull/22054

**Comment by Tobias-Keller** [comment]
Have this problem on Windows Server 2016. On Windows 10 it works with 9.0.7

**Comment by MrinaliMangal** [comment]
what was causing below error and how you removed that?
[73878:0219/111910.371171:INFO:CONSOLE(0)] "Unchecked runtime.lastError: Access to extension API denied.", source: chrome-extension://mhjfbmdgcfjbbpaeojofohoefgiehjai/index.html (0)
I am getting the same error while loading my extension.
