### ISSUE TITLE
Electron 8.0.2 Install Failed Because Of Wrong Download URL Path

### ISSUE THREAD

**Issue by SliceWire** [electron/electron#22480]
At Electron v8.0.2 preinstall, Download URL Is: https://npm.taobao.org/mirrors/electron/v8.0.2/electron-v8.0.2-win32-x64.zip But It Is A 404 Error. The Correct URL Is: https://npm.taobao.org/mirrors/electron/8.0.2/electron-v8.0.2-win32-x64.zip
PLEASE UPDATE PREINSTALL SCRIPT FOR ELECTRON V8.0.2

Here's The Error Message:

> electron@8.0.2 postinstall c:\Users\Documents\Apps\slicewire-apps\slicewire-app\node_modules\.pnpm\registry.npmjs.org\electron\8.0.2\node_modules\electron
> node install.js

(node:10192) UnhandledPromiseRejectionWarning: HTTPError: Response code 404 (Not Found) for https://npm.taobao.org/mirrors/electron/v8.0.2/electron-v8.0.2-win32-x64.zip
    at EventEmitter.emitter.on.response (C:\Users\Documents\Apps\slicewire-apps\slicewire-app\node_modules\.pnpm\registry.npmjs.org\got\9.6.0\node_modules\got\source\as-stream.js:35:24)
    at EventEmitter.emit (events.js:198:13)
    at module.exports (C:\Users\Documents\Apps\slicewire-apps\slicewire-app\node_modules\.pnpm\registry.npmjs.org\got\9.6.0\node_modules\got\source\get-response.js:22:10)
    at ClientRequest.handleResponse (C:\Users\Documents\Apps\slicewire-apps\slicewire-app\node_modules\.pnpm\registry.npmjs.org\got\9.6.0\node_modules\got\source\request-as-event-emitter.js:155:5)
    at Object.onceWrapper (events.js:286:20)
    at ClientRequest.emit (events.js:203:15)
    at ClientRequest.origin.emit.args [as emit] (C:\Users\Documents\Apps\slicewire-apps\slicewire-app\node_modules\.pnpm\registry.npmjs.org\@szmarczak\http-timer\1.1.2\node_modules\@szmarczak\http-timer\source\index.js:37:11)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:565:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:111:17)
    at TLSSocket.socketOnData (_http_client.js:451:20)
(node:10192) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:10192) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by RoderickQiu** [comment]
This should be a taobao registry problem. (They are not updating for v7.1.12, too)

Anyway, as a taobao registry user, I'm being long seeing Electron fails to install correctly too, with error msgs like
```shell
throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again')
    ^

Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
    at getElectronPath (/Users/roderickqiu/Documents/wnr/node_modules/electron/index.js:14:11)
    at Object.<anonymous> (/Users/roderickqiu/Documents/wnr/node_modules/electron/index.js:18:18)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/roderickqiu/Documents/wnr/node_modules/electron/cli.js:3:16)
```

**Comment by MarshallOfSound** [comment]
This is a problem with the taobao mirror not with Electron itself

**Comment by lilulu2018** [comment]
try
npm config set electron_mirror http://npm.taobao.org/mirrors/electron/
npm config set electron_custom_dir 8.0.2

**Comment by SliceWire** [comment]
ok!
