### ISSUE TITLE
Windows on Arm Package Install Error

### ISSUE THREAD

**Issue by elcho** [electron/electron#22553]
I am trying to build my electron app for Arm running Windows. Following [these](https://www.electronjs.org/docs/tutorial/windows-arm) official Electron docs, I

- emptied my app's node_modules directory
- ran this command from Command Prompt: `set npm_config_arch=arm64`
- ran `yarn` to install packages

After installing some packages I got the following error:
    [4/4] Building fresh packages...
[6/12] ⠐ electron                                                                                                       [-/12] ⠐ waiting...                                                                                                     [8/12] ⠐ electron-chromedriver                                                                                          [7/12] ⠈ node-sass                                                                                                      error D:\Projects\SPS\fieldapp-ui\node_modules\electron-chromedriver: Command failed.
Exit code: 1
Command: node ./download-chromedriver.js
Arguments:
Directory: D:\Projects\SPS\fieldapp-ui\node_modules\electron-chromedriver
Output:
D:\Projects\SPS\fieldapp-ui\node_modules\electron-chromedriver\download-chromedriver.js:19
  if (err != null) throw err
                   ^

Error: Failed to find Electron v3.0.0 for win32-arm64 at https://github.com/electron/electron/releases/download/v3.0.0/chromedriver-v3.0.0-win32-arm64.zip
    at Request.<anonymous> (D:\Projects\SPS\fieldapp-ui\node_modules\nugget\index.js:169:61)
    at Request.emit (events.js:223:5)
    at Request.onRequestResponse (D:\Projects\SPS\fieldapp-ui\node_modules\request\request.js:1066:10)
    at ClientRequest.emit (events.js:223:5)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:583:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:115:17)
    at TLSSocket.socketOnData (_http_client.js:456:22)

**Comment by malept** [comment]
Per the page you linked, support for win32/arm64 was added to Electron in 6.0.8, so that would explain why that particular chromedriver version doesn't exist.

**Comment by elcho** [comment]
I am using electron version "^7.1.11". This package seems to be a dependency of electron and is calling for that version.

**Comment by malept** [comment]
Electron itself does not have a dependency on chromedriver, so it must be a dependency of another module in your app.

**Comment by elcho** [comment]
You are right and I got the build to complete successfully. I tried installing on my ARM64 based pc and got the following error:
"64-bit Windows is required"

My machine is a Surface Pro X running windows 10 Home edition with an ARM64-based architecture.

**Comment by malept** [comment]
Since I don't have access to an ARM64-based Windows device, I can't assist you any further.

For most questions about Electron there are a lot of options. Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people at this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.

**Comment by elcho** [comment]
I will try to reach out. Thanks for your quick response!

**Comment by aiqin-bao** [comment]
I have also encountered this problem, which is the M1 of the latest Mac, is there any way to solve it
