### ISSUE TITLE
403 on  https://electronjs.org/headers/v4.2.12/win-arm64/node.lib 

### ISSUE THREAD

**Issue by ajouve** [electron/electron#22773]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 4.1.3
* **Operating System:**
  * Windows 10

### Expected Behavior

Should run `yarn` command with no problem

### Actual Behavior

Running `yarn` I have an error 403 on https://electronjs.org/headers/v4.2.12/win-arm64/node.lib 

### Logs

```
 • electron-builder  version=21.2.0
  • loaded configuration  file=package.json ("build" field)
  • rebuilding native dependencies  dependencies=robotjs@0.6.0 platform=win32 arch=x64
  • install prebuilt binary  name=robotjs version=0.6.0 platform=win32 arch=x64
  • build native dependency from sources  name=robotjs
                                          version=0.6.0
                                          platform=win32
                                          arch=x64
                                          reason=prebuild-install failed with error (run with env DEBUG=electron-builder to get more information)
                                          error=prebuild-install info begin Prebuild-install version 5.3.3
    prebuild-install info looking for cached prebuild @ C:\Users\antoi\AppData\Roaming\npm-cache\_prebuilds\fa27be-robotjs-v0.6.0-electron-v69-win32-x64.tar.gz
    prebuild-install http request GET https://github.com/octalmage/robotjs/releases/download/v0.6.0/robotjs-v0.6.0-electron-v69-win32-x64.tar.gz
    prebuild-install http 404 https://github.com/octalmage/robotjs/releases/download/v0.6.0/robotjs-v0.6.0-electron-v69-win32-x64.tar.gz
    prebuild-install WARN install No prebuilt binaries found (target=4.2.12 runtime=electron arch=x64 libc= platform=win32)
  • rebuilding native dependency  name=robotjs version=0.6.0
  ⨯ cannot execute  cause=exit status 1
                    out=yarn run v1.22.4
    $ prebuild-install || node-gyp rebuild
    C:\Users\antoi\Documents\ijkoa\ijkoa-electron-app\node_modules\robotjs>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
    info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
                    errorOut=prebuild-install WARN install No prebuilt binaries found (target=4.2.12 runtime=electron arch=x64 libc= platform=win32)
    gyp info it worked if it ends with ok
    gyp info using node-gyp@5.0.5
    gyp info using node@12.16.1 | win32 | x64
    gyp info find Python using Python version 2.7.15 found at "C:\Users\antoi\.windows-build-tools\python27\python.exe"
    gyp http GET https://electronjs.org/headers/v4.2.12/node-v4.2.12-headers.tar.gz
    gyp http 200 https://electronjs.org/headers/v4.2.12/node-v4.2.12-headers.tar.gz
    gyp http GET https://electronjs.org/headers/v4.2.12/SHASUMS256.txt
    gyp http GET https://electronjs.org/headers/v4.2.12/win-x86/node.lib
    gyp http GET https://electronjs.org/headers/v4.2.12/win-x64/node.lib
    gyp http GET https://electronjs.org/headers/v4.2.12/win-arm64/node.lib
    gyp http 403 https://electronjs.org/headers/v4.2.12/win-arm64/node.lib
    gyp WARN install got an error, rolling back install
    gyp http 200 https://electronjs.org/headers/v4.2.12/SHASUMS256.txt
    gyp ERR! configure error
    gyp ERR! stack Error: 403 status code downloading arm64 node.lib
    gyp ERR! stack     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\install.js:335:22)
    gyp ERR! stack     at Request.emit (events.js:323:22)
    gyp ERR! stack     at Request.onRequestResponse (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1066:10)
    gyp ERR! stack     at ClientRequest.emit (events.js:311:20)
    gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:603:27)
    gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
    gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:476:22)
    gyp ERR! stack     at TLSSocket.emit (events.js:311:20)
    gyp ERR! stack     at addChunk (_stream_readable.js:294:12)
    gyp ERR! stack     at readableAddChunk (_stream_readable.js:275:11)
    gyp ERR! System Windows_NT 10.0.18362
    gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
    gyp ERR! cwd C:\Users\antoi\Documents\ijkoa\ijkoa-electron-app\node_modules\robotjs
    gyp ERR! node -v v12.16.1
    gyp ERR! node-gyp -v v5.0.5
    gyp ERR! not ok
    error Command failed with exit code 1.
                    command='C:\Program Files\nodejs\node.exe' 'C:\Program Files (x86)\Yarn\bin\yarn.js' run install
                    workingDir=C:\Users\antoi\Documents\ijkoa\ijkoa-electron-app\node_modules\robotjs
error Command failed with exit code 1.
```

**Comment by MarshallOfSound** [comment]
Electron 4 does not support arm64 on Windows, you have to be on at least Electron 6 to support that.
