### ISSUE TITLE
BrowserWindow setProxy throws ERR_SOCKS_CONNECTION_FAILED

### ISSUE THREAD

**Issue by dafivius** [electron/electron#22885]
* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v8.2.0
* **Operating System:**
  * macOS 10.13.6

### Expected Behavior
Success page load via socks5 proxy. Proxy requires username and password

### Actual Behavior
```
Error: ERR_CONNECTION_CLOSED (-100) loading 'https://workingsite.com'
    at rejectAndCleanup (electron/js2c/browser_init.js:6026:21)
    at WebContents.failListener (electron/js2c/browser_init.js:6036:11)
    at WebContents.emit (events.js:210:5) {
  errno: -100,
  code: 'ERR_CONNECTION_CLOSED',
  url: 'https://workingsite.com'
}
```

### To Reproduce
Clean installation of Electron
```
app.on('login', (event, webContents, request, authInfo, callback) => {
    console.log('onLogin', authInfo);
    let fullProxy = `${authInfo.host}:${authInfo.port}`; 
    callback('username', 'password'); //supply credentials to server
});
```
```
let window = new BrowserWindow({
        show: true,
        webPreferences: {
             nodeIntegration: true
        }
    });

    window.webContents.session.setProxy({proxyRules: 'socks5://host:port'}).then((data) => {

        window.loadURL('https://workingsite.com').then((res) => {
            console.log(res);
        }).catch((err) => {
            console.log(err);
        })
    }).catch((err) => {
        console.log(err);
    });
    window.webContents.openDevTools();
```
App's on('login') handler never fires, and i cant load site via socks5 proxy. 
workingsite.com - is just example, socks5 host and port are correct, proxy server is working good.
What im doing wrong? And how to resolve that issue?

**Comment by fjx2000** [comment]
does electron support socks5 with auth ?

**Comment by rfirefly** [comment]
Is still couldn't work
