### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by neicras** [electron/electron#22950]
Hello, I have this Uncaught Exception Error when starting up an application (Upwork: https://www.upwork.com/ab/downloads/). 

Details:
Uncaught Exception:
Error: Failed to set path
    at Object.<anonymous> (/electron.asar/browser/init.js:151:5)
    at Object.<anonymous> (/electron.asar/browser/init.js:192:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
    at Function.Module._load (internal/modules/cjs/loader.js:533:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:746:12)
    at startup (internal/bootstrap/node.js:282:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:759:3)

There is not much answers after an hour of research. Most answers point to a problem with running electron. Some answers point to access problem with the "application support" folder under my user. How do I verify and how to solve?
![Screenshot 2020-04-03 at 11 12 00 AM](https://user-images.githubusercontent.com/33999550/78323568-d19c7700-75a4-11ea-8f1c-10e5d2d7eeab.png)

**Comment by sofianguy** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way 😀

**Comment by sofianguy** [comment]
Thank you for your issue!

We haven't gotten a response to our questions in our comment above. With only the information that is currently in the issue, we don't have enough information to take action. I'm going to close this but don't hesitate to reach out if you have or find the answers we need, we'll be happy to reopen the issue.
