### ISSUE TITLE
Error invoke apply_all_patches.py during glient runhooks on windows

### ISSUE THREAD

**Issue by tuxianchao** [electron/electron#22964]
hi ,I ‘m try to clone and build electron source use **gclient**  on windows, but i get error every time.
it's like run hooks error.

```
set DEPOT_TOOLS_WIN_TOOLCHAIN=0

set GIT_CACHE_PATH=.git_cache

gclient config --name "src/electron" --unmanaged https://github.com/electron/electron

gclient sync --with_branch_heads --with_tags -v --nohooks

gclient  runhooks
```

but run hooks get error every time

```
D:\tuut\electron-gn>gclient runhooks

________ running 'vpython.bat src/electron/script/apply_all_patches.py src/electron/patches/config.json' in 'D:\tuut\electron-gn'
Traceback (most recent call last):
  File "src/electron/script/apply_all_patches.py", line 35, in <module>
    main()
  File "src/electron/script/apply_all_patches.py", line 31, in main
    apply_patches(json.load(config_json))
  File "src/electron/script/apply_all_patches.py", line 17, in apply_patches
    committer_name="Electron Scripts", committer_email="scripts@electron")
  File "D:\tuut\electron-gn\src\electron\script\lib\git.py", line 95, in import_patches
    newvalue='HEAD'
  File "D:\tuut\electron-gn\src\electron\script\lib\git.py", line 119, in update_ref
    return subprocess.check_call(args)
  File "D:\work\depot_tools\bootstrap-3_8_0_chromium_8_bin\python\bin\Lib\subprocess.py", line 185, in check_call
    retcode = call(*popenargs, **kwargs)
  File "D:\work\depot_tools\bootstrap-3_8_0_chromium_8_bin\python\bin\Lib\subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "D:\work\depot_tools\bootstrap-3_8_0_chromium_8_bin\python\bin\Lib\subprocess.py", line 394, in __init__
    errread, errwrite)
  File "D:\work\depot_tools\bootstrap-3_8_0_chromium_8_bin\python\bin\Lib\subprocess.py", line 644, in _execute_child
    startupinfo)
WindowsError: [Error 2]
Error: Command 'vpython.bat src/electron/script/apply_all_patches.py src/electron/patches/config.json' returned non-zero exit status 1 in D:\tuut\electron-gn
Hook 'vpython.bat src/electron/script/apply_all_patches.py src/electron/patches/config.json' took 12.61 secs

D:\tuut\electron-gn>
D:\tuut\electron-gn>where python
C:\Python27\python.exe
D:\work\depot_tools\python.bat

D:\tuut\electron-gn>where git
D:\work\depot_tools\git.bat

```
It fails to execute "git -C update-ref" for some reason that I don't really understand.

**Comment by codebytere** [comment]
@tuxianchao we recommend that you use [`build-tools`](https://github.com/electron/build-tools) to build electron locally - that should abstract away these issues for you.

**Comment by tuxianchao** [comment]
> @tuxianchao we recommend that you use [`build-tools`](https://github.com/electron/build-tools) to build electron locally - that should abstract away these issues for you.

thank you ，I solve this problem，Maybe it's the reason for bad  network env.But in the end, I succeeded
