### ISSUE TITLE
I am getting a Javascript error when trying to run electron.

### ISSUE THREAD

**Issue by caradoct** [electron/electron#23210]
I am trying to plot graphs out of plotly using electron. I get this error:

> Uncaught Exception:
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be one of type string, Buffer, or URL. Received type boolean
    at Object.mkdirSync (fs.js:756:10)
    at main (/usr/local/lib/node_modules/orca/bin/graph.js:109:8)
    at Object.<anonymous> (/usr/local/lib/node_modules/orca/bin/orca_electron.js:100:25)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at loadApplicationPackage (/usr/local/lib/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js:109:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/electron/dist/Electron.app/Contents/Resources/default_app.asar/main.js:155:9)
    at Module._compile (internal/modules/cjs/loader.js:786:30)

I am using OSX 10.14.16 and electron 6.1.4.

The output .png file is made but the scatter plot on it is broken.

### Preflight Checklist

* [ ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [ ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 
* **Operating System:**
  * 
* **Last Known Working Electron version:**
  *

**Comment by MarshallOfSound** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by caradoct** [comment]
Hi Samuel,

Thanks for the email. I re-submitted the bug  and completed the template properly (I hope).
Any help would be greatly appreciated!

Cheers,

Tom

**Comment by sofianguy** [comment]
Thank you for taking the time to report this issue and helping to make Electron better.

The version of Electron you reported this on has been superseded by newer releases. 

If you're still experiencing this issue in Electron 7.x.y or later, please add a comment specifying the version you're testing with and any other new information that a maintainer trying to reproduce the issue should know.

I'm setting the `blocked/need-info` label for the above reasons. This issue will be closed 7 days from now if there is no response.

Thanks in advance! Your help is appreciated.

**Comment by caradoct** [comment]
Hi Sofia,

Thanks. I will upgrade and re-test.

Cheers,

Tom

**Comment by sofianguy** [comment]
Closing this as there has been no activity. If you find this is still an issue on a later version of Electron, we'd be happy to reopen.
