### ISSUE TITLE
Cannot create BrowserWindow before app is ready

### ISSUE THREAD

**Issue by fengshanbieyuan** [electron/electron#23476]
### Preflight Checklist

* [√] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [√] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [√] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  *  v8.2.3
* **Operating System:**
  *  macOS 10.15.4 (19E287)
* **Last Known Working Electron version:**
  *  sorry, I don't know.

### Expected Behavior

My app works.

### Actual Behavior

not works and I got an error like this.
```
Uncaught Exception:
Error: Cannot create BrowserWindow before app is ready
    at createWindow (/Users/tom/Documents/wsWP/react-cn-mirrot/build/CN-Mirror-darwin-x64/CN-Mirror.app/Contents/Resources/app/main.js:11:24)
    at App.<anonymous> (/Users/tom/Documents/wsWP/react-cn-mirrot/build/CN-Mirror-darwin-x64/CN-Mirror.app/Contents/Resources/app/main.js:98:9)
    at App.emit (events.js:210:5)
```

### To Reproduce

same error like #14425, #13669. But maybe I found the reason about this error.
I cloned my project from `electron-quick-start` and I built my app.
I clicked the icon when my app was jumpping in the dock, I got this error :
```
Uncaught Exception:
Error: Cannot create BrowserWindow before app is ready
    at createWindow (/Users/tom/Documents/wsWP/react-cn-mirrot/build/CN-Mirror-darwin-x64/CN-Mirror.app/Contents/Resources/app/main.js:11:24)
    at App.<anonymous> (/Users/tom/Documents/wsWP/react-cn-mirrot/build/CN-Mirror-darwin-x64/CN-Mirror.app/Contents/Resources/app/main.js:98:9)
    at App.emit (events.js:210:5)
```
I think the `activate` event was received by app and it was not ready, so the app was trying to create a new window.
```
app.on('activate', function () {
    // On macOS it's common to re-create a window in the app when the
    // dock icon is clicked and there are no other windows open.
    if (BrowserWindow.getAllWindows().length === 0) {
        createWindow();
    }
})
```
Finally , I removed this function . It works.
I think the `activate` event should not be send when the app is starting.
Is this a bug?

**Comment by nornagon** [comment]
I think it's correct to send the `activate` event before `ready` (it's plausible that your app might want to store the fact that it was clicked and then do something later after `ready` is fired), but it's not correct in electron-quick-start to attempt creating the window when receiving that event before ready. I've made a PR to electron-quick-start to fix it.

Thanks for the report!
