### ISSUE TITLE
403 on https://electronjs.org/headers/v9.0.0/node-v9.0.0-headers.tar.gz

### ISSUE THREAD

**Issue by shahan312** [electron/electron#23545]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 9.0.0-beta.24
* **Operating System:**
  * Windows 10 Pro (1903)
* **Last Known Working Electron version:**
  * 8.2.5

### Expected Behavior
I should be able to run `yarn` with no issues.

### Actual Behavior
When running `yarn` I receive a 403 error on `https://electronjs.org/headers/v9.0.0/node-v9.0.0-headers.tar.gz` 

### To Reproduce
Can get the same error when visiting the URL directly.

### Logs
```
PS C:\Users\conta_000\Documents\electron> yarn install
yarn install v1.22.4
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
success Saved lockfile.
$ electron-builder install-app-deps
  • electron-builder  version=22.6.0
  • loaded configuration  file=package.json ("build" field)
  • rebuilding native dependencies  dependencies=cld@2.7.0, spellchecker@3.7.0 platform=win32 arch=x64
  • rebuilding native dependency  name=cld version=2.7.0
  • rebuilding native dependency  name=spellchecker version=3.7.0
  ⨯ cannot execute  cause=exit status 1
                    out=yarn run v1.22.4
    $ node-gyp rebuild

    C:\Users\conta_000\Documents\electron\node_modules\spellchecker>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
    info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

                    errorOut=gyp info it worked if it ends with ok
    gyp info using node-gyp@5.1.0
    gyp info using node@12.16.3 | win32 | x64
    gyp info find Python using Python version 3.8.2 found at "C:\Python38\python.exe"
    gyp http GET https://electronjs.org/headers/v9.0.0/node-v9.0.0-headers.tar.gz
    gyp http 403 https://electronjs.org/headers/v9.0.0/node-v9.0.0-headers.tar.gz
    gyp WARN install got an error, rolling back install
    gyp ERR! configure error
    gyp ERR! stack Error: 403 response downloading https://electronjs.org/headers/v9.0.0/node-v9.0.0-headers.tar.gz
    gyp ERR! stack     at Request.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\install.js:188:14)
    gyp ERR! stack     at Request.emit (events.js:322:22)
    gyp ERR! stack     at Request.onRequestResponse (C:\Program Files\nodejs\node_modules\npm\node_modules\request\request.js:1066:10)
    gyp ERR! stack     at ClientRequest.emit (events.js:310:20)
    gyp ERR! stack     at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:596:27)
    gyp ERR! stack     at HTTPParser.parserOnHeadersComplete (_http_common.js:119:17)
    gyp ERR! stack     at TLSSocket.socketOnData (_http_client.js:469:22)
    gyp ERR! stack     at TLSSocket.emit (events.js:310:20)
    gyp ERR! stack     at addChunk (_stream_readable.js:286:12)
    gyp ERR! stack     at readableAddChunk (_stream_readable.js:268:9)
    gyp ERR! System Windows_NT 10.0.18362
    gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
    gyp ERR! cwd C:\Users\conta_000\Documents\electron\node_modules\spellchecker
    gyp ERR! node -v v12.16.3
    gyp ERR! node-gyp -v v5.1.0
    gyp ERR! not ok
    error Command failed with exit code 1.

                    command='C:\Program Files\nodejs\node.exe' 'C:\Users\conta_000\AppData\Roaming\npm\node_modules\yarn\bin\yarn.js' run install
                    workingDir=C:\Users\conta_000\Documents\electron\node_modules\spellchecker
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

### Additional Information
I didn't have this issue a few days ago on version v9.0.0-beta.22, but is now reproducible on that version too.

**Comment by codebytere** [comment]
@shahan312 `v9.0.0` is not a version that has been released yet. That is thus expected.
