### ISSUE TITLE
Recursive rmdir in original-fs returns error while trying to remove folder, that contains asar file.

### ISSUE THREAD

**Issue by zziger** [electron/electron#23871]
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 9.0.0
* **Operating System:**
  * macOS 10.15.5

### Expected Behavior
```js
const fs = require('original-fs');
fs.rmdirSync('./foldername', { recursive: true });
```
Should delete folder recursively

### Actual Behavior
If the folder contains asar files, code throws an error
```
TypeError: Cannot read property 'code' of null
    at rimrafSync (internal/fs/rimraf.js:184:13)
    at internal/fs/rimraf.js:211:9
    at Array.forEach (<anonymous>)
    at _rmdirSync (internal/fs/rimraf.js:210:25)
    at rimrafSync (internal/fs/rimraf.js:180:7)
```

### To Reproduce
* Create a folder with asar file in it (asar file must be valid)
* Create js file (or enter interactive shell)
* Execute
```js
const fs = require('original-fs');
fs.rmdirSync('./foldername', { recursive: true });
```

### Screenshots
![image](https://user-images.githubusercontent.com/27638710/83383803-8ceb5b80-a3ee-11ea-959d-685f4c5f4ec9.png)
![image](https://user-images.githubusercontent.com/27638710/83383823-9674c380-a3ee-11ea-9de4-f6481aea945d.png)

**Comment by zziger** [comment]
Tested on Electron version `v10.0.0-beta.1`, same error.
