### ISSUE TITLE
Electron 9 fails to install. 

### ISSUE THREAD

**Issue by Musicus69** [electron/electron#23878]
* Electron version: Electron 9
* Operating system: MacOS Catalina 10.15.5

### Expected behavior

When I run 
**yarn add electron electron-builder concurrently wait-on --dev** 
these dev dependencies should install. 
### Actual behavior

I get this error and I don't see electron in my node_modules folder or in package.json:

8c8590211c08:documents kuv599$ yarn add electron electron-builder concurrently wait-on --dev
yarn add v1.22.4
info No lockfile found.
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
[3/3] ⢀ electron
[2/3] ⢀ ejs
error /Users/kuv599/Documents/node_modules/electron: Command failed.
Exit code: 1
Command: node install.js
Arguments: 
Directory: /Users/kuv599/Documents/node_modules/electron
Output:
RequestError: read ECONNRESET
    at ClientRequest.<anonymous> (/Users/kuv599/Documents/node_modules/got/source/request-as-event-emitter.js:178:14)
    at Object.onceWrapper (events.js:422:26)
    at ClientRequest.emit (events.js:327:22)
    at ClientRequest.origin.emit (/Users/kuv599/Documents/node_modules/@szmarczak/http-timer/source/index.js:37:11)
    at TLSSocket.socketErrorListener (_http_client.js:463:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:100:8)
    at emitErrorCloseNT (internal/streams/destroy.js:68:3)

8c8590211c08:documents kuv599$ 

I have built apps with Electron (before v.9) and it worked fine, so I'm not sure why I can't even install it anymore. Any help would be greatly appreciated!

**Comment by codebytere** [comment]
This issue should be opened on `electron-builder`.

**Comment by yuefeng007** [comment]
npm i electron 

I encountered the same situation
