### ISSUE TITLE
crypto module missing chacha20-poly1305 cipher

### ISSUE THREAD

**Issue by andersk** [electron/electron#24024]
The Electron `crypto` module is missing the `chacha20-poly1305` cipher.

```console
$ electron --version
v9.0.3
$ electron -i
> cipher = crypto.createCipheriv("chacha20-poly1305", crypto.randomBytes(32), crypto.randomBytes(12), {authTagLength: 16})
Thrown:
Error: Unknown cipher
    at Cipheriv.createCipherBase (internal/crypto/cipher.js:101:19)
    at Cipheriv.createCipherWithIV (internal/crypto/cipher.js:119:20)
    at new Cipheriv (internal/crypto/cipher.js:223:22)
    at Object.createCipheriv (crypto.js:115:10)
    at repl:1:8
    at Script.runInContext (vm.js:127:20)
    at REPLServer.defaultEval (repl.js:407:29)
    at bound (domain.js:419:14)
    at REPLServer.runBound [as eval] (domain.js:432:12)
    at REPLServer.onLine (repl.js:716:10)
> crypto.getCiphers().join(" ")
'aes-128-cbc aes-128-cfb aes-128-ctr aes-128-ecb aes-128-gcm aes-128-ofb
aes-192-cbc aes-192-ctr aes-192-ecb aes-192-gcm aes-192-ofb aes-256-cbc
aes-256-cfb aes-256-ctr aes-256-ecb aes-256-gcm aes-256-ofb des-cbc des-ecb
des-ede des-ede-cbc des-ede3-cbc rc2-cbc rc4'
```

Same results in Electron 10.0.0-beta.2. By comparison, it works fine in Node.js.

```console
$ node --version
v10.19.0
$ node
> cipher = crypto.createCipheriv("chacha20-poly1305", crypto.randomBytes(32), crypto.randomBytes(12), {authTagLength: 16})
Cipheriv {
  _handle: {},
  _decoder: null,
  _options: { authTagLength: 16 },
  writable: true,
  readable: true }
> cipher.update("plaintext", "utf8")
<Buffer bd 3c f0 04 c0 53 04 e1 1b>
> cipher.final()
<Buffer >
> cipher.getAuthTag()
<Buffer 31 77 3a ec 2e 9c ce 14 dc 8d 03 f7 da 44 cc 53>
> crypto.getCiphers().join(" ")
'aes-128-cbc aes-128-cbc-hmac-sha1 aes-128-cbc-hmac-sha256 aes-128-ccm
aes-128-cfb aes-128-cfb1 aes-128-cfb8 aes-128-ctr aes-128-ecb aes-128-gcm
aes-128-ocb aes-128-ofb aes-128-xts aes-192-cbc aes-192-ccm aes-192-cfb
aes-192-cfb1 aes-192-cfb8 aes-192-ctr aes-192-ecb aes-192-gcm aes-192-ocb
aes-192-ofb aes-256-cbc aes-256-cbc-hmac-sha1 aes-256-cbc-hmac-sha256
aes-256-ccm aes-256-cfb aes-256-cfb1 aes-256-cfb8 aes-256-ctr aes-256-ecb
aes-256-gcm aes-256-ocb aes-256-ofb aes-256-xts aes128 aes128-wrap aes192
aes192-wrap aes256 aes256-wrap aria-128-cbc aria-128-ccm aria-128-cfb
aria-128-cfb1 aria-128-cfb8 aria-128-ctr aria-128-ecb aria-128-gcm aria-128-ofb
aria-192-cbc aria-192-ccm aria-192-cfb aria-192-cfb1 aria-192-cfb8 aria-192-ctr
aria-192-ecb aria-192-gcm aria-192-ofb aria-256-cbc aria-256-ccm aria-256-cfb
aria-256-cfb1 aria-256-cfb8 aria-256-ctr aria-256-ecb aria-256-gcm aria-256-ofb
aria128 aria192 aria256 bf bf-cbc bf-cfb bf-ecb bf-ofb blowfish camellia-128-cbc
camellia-128-cfb camellia-128-cfb1 camellia-128-cfb8 camellia-128-ctr
camellia-128-ecb camellia-128-ofb camellia-192-cbc camellia-192-cfb
camellia-192-cfb1 camellia-192-cfb8 camellia-192-ctr camellia-192-ecb
camellia-192-ofb camellia-256-cbc camellia-256-cfb camellia-256-cfb1
camellia-256-cfb8 camellia-256-ctr camellia-256-ecb camellia-256-ofb camellia128
camellia192 camellia256 cast cast-cbc cast5-cbc cast5-cfb cast5-ecb cast5-ofb
chacha20 chacha20-poly1305 des des-cbc des-cfb des-cfb1 des-cfb8 des-ecb des-ede
des-ede-cbc des-ede-cfb des-ede-ecb des-ede-ofb des-ede3 des-ede3-cbc
des-ede3-cfb des-ede3-cfb1 des-ede3-cfb8 des-ede3-ecb des-ede3-ofb des-ofb des3
des3-wrap desx desx-cbc id-aes128-CCM id-aes128-GCM id-aes128-wrap
id-aes128-wrap-pad id-aes192-CCM id-aes192-GCM id-aes192-wrap id-aes192-wrap-pad
id-aes256-CCM id-aes256-GCM id-aes256-wrap id-aes256-wrap-pad
id-smime-alg-CMS3DESwrap rc2 rc2-128 rc2-40 rc2-40-cbc rc2-64 rc2-64-cbc rc2-cbc
rc2-cfb rc2-ecb rc2-ofb rc4 rc4-40 rc4-hmac-md5 seed seed-cbc seed-cfb seed-ecb
seed-ofb sm4 sm4-cbc sm4-cfb sm4-ctr sm4-ecb sm4-ofb'
```

I found #16566 about the AES-GCM ciphers, but that one seems to have been fixed (by [this boringssl commit](https://boringssl.googlesource.com/boringssl/+/7ef4223fb32431529a797c5b8d3bf26ece6c138b), I assume) and this is not.

### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 9.0.3
* **Operating System:**
  * Ubuntu 20.04 amd64
* **Last Known Working Electron version:**
  * None (Electron 3.1.13 lists the cipher, although it doesn’t work as expected)

**Comment by codebytere** [comment]
We use BoringSSL and not OpenSSL as Node.js does owing to our embedding structure - BoringSSL is a fork of OpenSSL with some esoteric functionality stripped out. In order to fix this, we would need to apply patches on top of BoringSSL, which would add nontrivial maintenance cost we strive to avoid. As such, i'm going to label this a `wontfix`, but you're welcome to open a feature request against BoringSSL itself, and if they add it it will become available through Electron.
