### ISSUE TITLE
autoUpdater System.Exception: Checksummed file size doesn't match

### ISSUE THREAD

**Issue by mahnunchik** [electron/electron#24149]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  *  8.3.2
* **Operating System:**
  *  Windows 10 (1909)
* **Last Known Working Electron version:**
  *  -

### Expected Behavior

Windows `autoUpdater` works.

### Actual Behavior

Windows `autoUpdater` could not update because the errror:

```bash
[2020-06-16 02:54:48.845] [info] updater error: Error: Command failed: 4294967295
System.AggregateException: One or more errors occurred. ---> System.Exception: Checksummed file size doesn't match: C:\Users\User\AppData\Local\com\packages\com.app-1.3.1-full.nupkg
   at Squirrel.UpdateManager.DownloadReleasesImpl.checksumPackage(ReleaseEntry downloadedRelease)
   at Squirrel.UpdateManager.DownloadReleasesImpl.<>c__DisplayClass2_0.<<DownloadReleases>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<>c__DisplayClass13_1`1.<<ForEachAsync>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.DownloadReleasesImpl.<DownloadReleases>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<DownloadReleases>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Update.Program.<Update>d__5.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at System.Threading.Tasks.Task.Wait()
   at Squirrel.Update.Program.executeCommandLine(String[] args)
   at Squirrel.Update.Program.main(String[] args)
   at Squirrel.Update.Program.Main(String[] args)
---> (Inner Exception #0) System.Exception: Checksummed file size doesn't match: C:\Users\User\AppData\Local\com\packages\com.app-1.3.1-full.nupkg
   at Squirrel.UpdateManager.DownloadReleasesImpl.checksumPackage(ReleaseEntry downloadedRelease)
   at Squirrel.UpdateManager.DownloadReleasesImpl.<>c__DisplayClass2_0.<<DownloadReleases>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Utility.<>c__DisplayClass13_1`1.<<ForEachAsync>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.DownloadReleasesImpl.<DownloadReleases>d__2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.UpdateManager.<DownloadReleases>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Squirrel.Update.Program.<Update>d__5.MoveNext()<---


    at AutoUpdater.emitError (electron/js2c/browser_init.js:339:24)
    at electron/js2c/browser_init.js:324:23
    at ChildProcess.<anonymous> (electron/js2c/browser_init.js:428:14)
    at ChildProcess.emit (events.js:210:5)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
```

### To Reproduce

1. Build WIndows app https://github.com/electron/electron-quick-start using https://github.com/electron/windows-installer/ with support https://github.com/electron/update.electronjs.org
2. Release new version

### Additional Information

Electron forge was used.

**Comment by Lunchb0ne** [comment]
I feel like it might be hashing the wrong file?

**Comment by mahnunchik** [comment]
@Lunchb0ne nope. It seems the update server makes strange things https://github.com/electron/update.electronjs.org/blob/master/index.js#L213-L217

**Comment by mahnunchik** [comment]
I don't know the correct place for this issue, but let's try find a solution.

**Question:** How to ship delta updates for Windows app?

---

My investigation:

[electron/windows-installer](https://github.com/electron/windows-installer/) with `remoteReleases` enabled produces `RELEASES` file in the following form:

```txt
847085EC064106CAAF79ABE03DD580FE5441D254 com.example-1.2.1-delta.nupkg 121364
F2DEA6650084C84DC1CE1F0637747973E4D4C91D com.example-1.2.1-full.nupkg 67481398
6AA6ECEF57B84CB8AAC9625F32AB6C979327A0A4 com.example-1.3.0-delta.nupkg 4544954
BE5AA158400251768A46E792DC01C95810027F46 com.example-1.3.0-full.nupkg 67507429
DF8C26CCE335CB549BD6C5493CDF5FD86DFD35B4 com.example-1.3.1-delta.nupkg 94499
5F7205F20FF5B66C3276727BF6EDB0828D688A45 com.example-1.3.1-full.nupkg 67507429
```

But only `com.example-1.3.1-delta.nupkg` and `com.example-1.3.1-full.nupkg` are from the latest release and release page/url prefix on GitHub.

---

[update.electronjs.org](https://github.com/electron/update.electronjs.org/) makes strange thing: it adds url prefix to the first item. But it is prefix of latest release not from first one: https://github.com/electron/update.electronjs.org/blob/master/index.js#L213-L218

Response from `http://update.electronjs.org/repo/name/win32-x64/1.2.0/RELEASES`:
```
847085EC064106CAAF79ABE03DD580FE5441D254 https://github.com/repo/name/releases/download/v1.3.1/com.example-1.2.1-delta.nupkg 121364
F2DEA6650084C84DC1CE1F0637747973E4D4C91D com.example-1.2.1-full.nupkg 67481398
6AA6ECEF57B84CB8AAC9625F32AB6C979327A0A4 com.example-1.3.0-delta.nupkg 4544954
BE5AA158400251768A46E792DC01C95810027F46 com.example-1.3.0-full.nupkg 67507429
DF8C26CCE335CB549BD6C5493CDF5FD86DFD35B4 com.example-1.3.1-delta.nupkg 94499
5F7205F20FF5B66C3276727BF6EDB0828D688A45 com.example-1.3.1-full.nupkg 67507429
```

Url prefix of `v1.3.1` release is added to `1.2.1` file.

---

[vercel/hazel](https://github.com/vercel/hazel/) update server adds latest release prefix to each asset: https://github.com/vercel/hazel/blob/master/lib/cache.js#L70-L73

So only last two asset path are correct.

**Comment by mahnunchik** [comment]
@MarshallOfSound I thin you may know how to set up delta updates. But it seems patched installer is used in the Google-Play-Music-Desktop-Player-UNOFFICIAL- https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/master/package.json#L122

**Comment by mahnunchik** [comment]
@felixrieseberg It may be related to the issue that `fiddle` doesn't use delta updates https://github.com/electron/fiddle/blob/master/forge.config.js#L63

**Comment by Lunchb0ne** [comment]
Yeah, @mahnunchik seems about to be correct

**Comment by mahnunchik** [comment]
It seems update server of `Google-Play-Music-Desktop-Player-UNOFFICIAL-` uses only 2 assets and adds full url path to each. https://github.com/MarshallOfSound/Google-Play-Music-Desktop-Player-UNOFFICIAL-/blob/93476f52a1ea9a6509006a5515b537880d36a336/src/main/features/core/autoUpdater.js#L12

Example: https://update.gpmdp.xyz/update/win/1.0.0/RELEASES

**Comment by electron-triage** [comment]
The Electron version reported on this issue is no longer supported. See our [supported versions documentation](https://www.electronjs.org/docs/tutorial/support#supported-versions).

**If you're still experiencing this issue on a supported version, please open a new issue with an updated repro - a [Fiddle](https://www.electronjs.org/fiddle) is very appreciated.**

Electron has a large issues backlog. To help our team prioritize, we're closing older issues and asking for new issues with updated repro steps if it affects a supported version. This helps sort what issues are still relevant and helps us fix them more quickly.

Thanks for your patience and understanding!

**Comment by junbong** [comment]
Hi,
Couple of years passed, but is there any solution for this checksum issue?
Same here at Electron v16.0.4

**Comment by hivenet-adnanetellou** [comment]
Facing same issue here... no news on this ?

**Comment by KuznetsovNikita** [comment]
When you remove all releases in `RELEASES` file except last 2 it's updated

Before
```
847085EC064106CAAF79ABE03DD580FE5441D254 com.example-1.2.1-delta.nupkg 121364
F2DEA6650084C84DC1CE1F0637747973E4D4C91D com.example-1.2.1-full.nupkg 67481398
6AA6ECEF57B84CB8AAC9625F32AB6C979327A0A4 com.example-1.3.0-delta.nupkg 4544954
BE5AA158400251768A46E792DC01C95810027F46 com.example-1.3.0-full.nupkg 67507429
DF8C26CCE335CB549BD6C5493CDF5FD86DFD35B4 com.example-1.3.1-delta.nupkg 94499
5F7205F20FF5B66C3276727BF6EDB0828D688A45 com.example-1.3.1-full.nupkg 67507429
```

Works:
```
DF8C26CCE335CB549BD6C5493CDF5FD86DFD35B4 com.example-1.3.1-delta.nupkg 94499
5F7205F20FF5B66C3276727BF6EDB0828D688A45 com.example-1.3.1-full.nupkg 67507429
```
