### ISSUE TITLE
Electron fails to install 

### ISSUE THREAD

**Issue by skebanga** [electron/electron#24157]
I am unable to install electron

Platform: Ubuntu 20.04 (fresh install)

Reproduction steps:

```
$ sudo apt install npm
$ npm --version
6.14.4
$ sudo npm install -g electron
/usr/local/bin/electron -> /usr/local/lib/node_modules/electron/cli.js

> core-js@3.6.5 postinstall /usr/local/lib/node_modules/electron/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

$ electron
/usr/local/lib/node_modules/electron/index.js:14
    throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again')
    ^

Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
    at getElectronPath (/usr/local/lib/node_modules/electron/index.js:14:11)
    at Object.<anonymous> (/usr/local/lib/node_modules/electron/index.js:18:18)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/electron/cli.js:3:16)

```

**Comment by skebanga** [comment]
Looking at the source code, I can see that it requires a file "path.txt" to exist. 

`path.txt` does not exist.

```
$ cat /usr/local/lib/node_modules/electron/index.js
...

var pathFile = path.join(__dirname, 'path.txt') // <---- this file does not exist

function getElectronPath () {
  if (fs.existsSync(pathFile)) {
    ...
  } else {
    throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again')
  }
}

module.exports = getElectronPath()
```

**Comment by codebytere** [comment]
@skebanga by default you should not be using `sudo`.

See https://github.com/electron/electron/blob/33ef0d23a66a6f9dd4b7bece071bfe0363bbf558/docs/tutorial/installation.md#L139 for more information.

**Comment by skebanga** [comment]
I don't understand, in the linked installation guide it says:

> ## Global Installation
> You can also install the `electron` command globally in your `$PATH`:
> 
>     npm install electron -g

Of course, if I do this without `root` access, it will fail to write to `/usr/local/lib/node_modules`, because my local user does not have write access to `/usr`

```
$ npm install electron -g
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules/electron
npm WARN checkPermissions Missing write access to /usr/local/lib/node_modules
npm ERR! code EACCES
npm ERR! syscall access
npm ERR! path /usr/local/lib/node_modules/electron
npm ERR! errno -13
npm ERR! Error: EACCES: permission denied, access '/usr/local/lib/node_modules/electron'
npm ERR!  { [Error: EACCES: permission denied, access '/usr/local/lib/node_modules/electron']
npm ERR!   stack:
npm ERR!    'Error: EACCES: permission denied, access \'/usr/local/lib/node_modules/electron\'',
npm ERR!   errno: -13,
npm ERR!   code: 'EACCES',
npm ERR!   syscall: 'access',
npm ERR!   path: '/usr/local/lib/node_modules/electron' }
npm ERR! 
npm ERR! The operation was rejected by your operating system.
npm ERR! It is likely you do not have the permissions to access this file as the current user
npm ERR! 
npm ERR! If you believe this might be a permissions issue, please double-check the
npm ERR! permissions of the file and its containing directories, or try running
npm ERR! the command again as root/Administrator.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/steve/.npm/_logs/2020-06-16T19_14_11_522Z-debug.log
```

The only way to write to `/usr` is as root, typically done via `sudo`.

So if `npm install -g` wants to install to `/usr`, but I can't use `sudo`, how do I do this?

**Comment by yaqwsx** [comment]
@skebanga: The following command did the job for me:

```
$ sudo npm install -g electron --unsafe-perm=true --allow-root
```
