### ISSUE TITLE
zeromq - No native build was found for platform=win32 arch=x64

### ISSUE THREAD

**Issue by MrSpijker** [electron/electron#24255]
### Issue Details

* **Electron Version:**
  * "electron": "^9.0.3",
  * "zeromq": "^6.0.0-beta.6"
* **Operating System:**
  * Windows 10 x64

### Expected Behavior
`import zeromq from 'zeromq'` in my saga in order to process incoming messages

### Actual Behavior
So I'm trying to add zeromq to my electron project but it throws the following error:
```
Uncaught Error: No native build was found for platform=win32 arch=x64 runtime=electron abi=80 uv=1 libc=glibc
    at Function.load.path (webpack-internal:///./node_modules/node-gyp-build/index.js:56)
    at load (webpack-internal:///./node_modules/node-gyp-build/index.js:21)
    at Object.eval (webpack-internal:///./node_modules/zeromq/lib/native.js:6)
    at eval (webpack-internal:///./node_modules/zeromq/lib/native.js:15)
    at Object../node_modules/zeromq/lib/native.js (main.4ef85cb0a7647b84aadd.js:60798)
    at __webpack_require__ (main.4ef85cb0a7647b84aadd.js:790)
    at fn (main.4ef85cb0a7647b84aadd.js:101)
    at eval (webpack-internal:///./node_modules/zeromq/lib/index.js:3)
    at Object../node_modules/zeromq/lib/index.js (main.4ef85cb0a7647b84aadd.js:60786)
    at __webpack_require__ (main.4ef85cb0a7647b84aadd.js:790)
```

### To Reproduce
Electron-boilerplate with latest electron version + latest zeromq version

### Output
After digging around on I tried to rebuild the electron module with 
`npm i --save-dev zeromq --build-from-target`
This does not throw any exotic error but when I use rebuild commands I get:

```
$ HOME=~/.electron-gyp node-gyp rebuild --target=6.0.0 --arch=x64 --dist-url=https://electronjs.org/headers
gyp info it worked if it ends with ok
gyp info using node-gyp@7.0.0
gyp info using node@10.16.3 | win32 | x64
gyp info find Python using Python version 3.7.4 found at "C:\Users\foo\AppData\Local\Programs\Python\Python37\python.exe"
gyp http GET https://electronjs.org/headers/v6.0.0/node-v6.0.0-headers.tar.gz
gyp http 200 https://electronjs.org/headers/v6.0.0/node-v6.0.0-headers.tar.gz
gyp http GET https://electronjs.org/headers/v6.0.0/SHASUMS256.txt
gyp http GET https://electronjs.org/headers/v6.0.0/win-x86/node.lib
gyp http GET https://electronjs.org/headers/v6.0.0/win-x64/node.lib
gyp http GET https://electronjs.org/headers/v6.0.0/win-arm64/node.lib
gyp http 200 https://electronjs.org/headers/v6.0.0/SHASUMS256.txt
gyp http 403 https://electronjs.org/headers/v6.0.0/win-arm64/node.lib
gyp http 200 https://electronjs.org/headers/v6.0.0/win-x86/node.lib
gyp http 200 https://electronjs.org/headers/v6.0.0/win-x64/node.lib
gyp info find VS using VS2019 (16.6.30204.135) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Users\foo\AppData\Local\Programs\Python\Python37\python.exe
gyp info spawn args [ 'C:\\Users\\foo\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\foo\\Desktop\\project\\app\\node_modules\\zeromq\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\foo\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\foo\\AppData\\Local\\node-gyp\\Cache\\6.0.0\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\foo\\AppData\\Local\\node-gyp\\Cache\\6.0.0',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\foo\\AppData\\Roaming\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\foo\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\6.0.0\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\foo\\Desktop\\project\\app\\node_modules\\zeromq',gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\foo\\Desktop\\project\\app\\node_modules\\zeromq\\build',
gyp info spawn args   '-Goutput_dir=.' ]
?[37;40mgyp?[0m ?[0m?[32minfo?[0m ?[0m?[35mspawn?[0m C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe
?[0m?[37;40mgyp?[0m ?[0m?[32minfo?[0m ?[0m?[35mspawn args?[0m [ 'build/binding.sln',
?[0m?[37;40mgyp?[0m ?[0m?[32minfo?[0m ?[0m?[35mspawn args?[0m   '/clp:Verbosity=minimal',
?[0m?[37;40mgyp?[0m ?[0m?[32minfo?[0m ?[0m?[35mspawn args?[0m   '/nologo',
?[0m?[37;40mgyp?[0m ?[0m?[32minfo?[0m ?[0m?[35mspawn args?[0m   '/p:Configuration=Release;Platform=x64' ]
?[0mBuilding the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
  build_libzmq
  Downloading libzmq source...

foo@DESKTOP-B9VRT2S MINGW64 ~/Desktop/project/app/node_modules/zeromq (feature/0MQ-node-integration)
$ HOME=~/.electron-gyp node-gyp rebuild --target=9.0.3 --arch=x64 --dist-url=https://electronjs.org/headers
gyp info it worked if it ends with ok
gyp info using node-gyp@7.0.0
gyp info using node@10.16.3 | win32 | x64
gyp info find Python using Python version 3.7.4 found at "C:\Users\foo\AppData\Local\Programs\Python\Python37\python.exe"
gyp http GET https://electronjs.org/headers/v9.0.3/node-v9.0.3-headers.tar.gz
gyp http 200 https://electronjs.org/headers/v9.0.3/node-v9.0.3-headers.tar.gz
gyp http GET https://electronjs.org/headers/v9.0.3/SHASUMS256.txt
gyp http GET https://electronjs.org/headers/v9.0.3/win-x64/node.lib
gyp http GET https://electronjs.org/headers/v9.0.3/win-x86/node.lib
gyp http GET https://electronjs.org/headers/v9.0.3/win-arm64/node.lib
gyp http 200 https://electronjs.org/headers/v9.0.3/SHASUMS256.txt
gyp http 200 https://electronjs.org/headers/v9.0.3/win-x64/node.lib
gyp http 200 https://electronjs.org/headers/v9.0.3/win-arm64/node.lib
gyp http 200 https://electronjs.org/headers/v9.0.3/win-x86/node.lib
gyp info find VS using VS2019 (16.6.30204.135) found at:
gyp info find VS "C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools"
gyp info find VS run with --verbose for detailed information
gyp info spawn C:\Users\foo\AppData\Local\Programs\Python\Python37\python.exe
gyp info spawn args [ 'C:\\Users\\foo\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\gyp\\gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'msvs',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\foo\\Desktop\\project\\app\\node_modules\\zeromq\\build\\config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\foo\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   'C:\\Users\\foo\\AppData\\Local\\node-gyp\\Cache\\9.0.3\\include\\node\\common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=C:\\Users\\foo\\AppData\\Local\\node-gyp\\Cache\\9.0.3',
gyp info spawn args   '-Dnode_gyp_dir=C:\\Users\\foo\\AppData\\Roaming\\npm\\node_modules\\node-gyp',
gyp info spawn args   '-Dnode_lib_file=C:\\\\Users\\\\foo\\\\AppData\\\\Local\\\\node-gyp\\\\Cache\\\\9.0.3\\\\<(target_arch)\\\\node.lib',
gyp info spawn args   '-Dmodule_root_dir=C:\\Users\\foo\\Desktop\\project\\app\\node_modules\\zeromq',gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'C:\\Users\\foo\\Desktop\\project\\app\\node_modules\\zeromq\\build',
gyp info spawn args   '-Goutput_dir=.' ]
?[37;40mgyp?[0m ?[0m?[32minfo?[0m ?[0m?[35mspawn?[0m C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe
?[0m?[37;40mgyp?[0m ?[0m?[32minfo?[0m ?[0m?[35mspawn args?[0m [ 'build/binding.sln',
?[0m?[37;40mgyp?[0m ?[0m?[32minfo?[0m ?[0m?[35mspawn args?[0m   '/clp:Verbosity=minimal',
?[0m?[37;40mgyp?[0m ?[0m?[32minfo?[0m ?[0m?[35mspawn args?[0m   '/nologo',
?[0m?[37;40mgyp?[0m ?[0m?[32minfo?[0m ?[0m?[35mspawn args?[0m   '/p:Configuration=Release;Platform=x64' ]
?[0mBuilding the projects in this solution one at a time. To enable parallel build, please add the "-m" switch.
  build_libzmq
  Downloading libzmq source...
  Building libzmq...
  C:\Users\foo\Desktop\project\app\node_modules\zeromq\build\Release\..\..\script\build.sh: line 60:
  cmake: command not found
C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Microsoft\VC\v160\Microsoft.CppCommon.targ
ets(231,5): error MSB6006: "cmd.exe" exited with code 127. [C:\Users\foo\Desktop\project\appl\node_mod
ules\zeromq\build\libzmq.vcxproj]
?[37;40mgyp?[0m ?[0m?[31;40mERR!?[0m ?[0m?[35mbuild error?[0m 
?[0m?[37;40mgyp?[0m ?[0m?[31;40mERR!?[0m ?[0m?[35mstack?[0m Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1
?[0m?[37;40mgyp?[0m ?[0m?[31;40mERR!?[0m ?[0m?[35mstack?[0m     at ChildProcess.onExit (C:\Users\foo\AppData\Roaming\npm\node_modules\node-gyp\lib\build.js:194:23)
?[0m?[37;40mgyp?[0m ?[0m?[31;40mERR!?[0m ?[0m?[35mstack?[0m     at ChildProcess.emit (events.js:198:13)
?[0m?[37;40mgyp?[0m ?[0m?[31;40mERR!?[0m ?[0m?[35mstack?[0m     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
?[0m?[37;40mgyp?[0m ?[0m?[31;40mERR!?[0m ?[0m?[35mSystem?[0m Windows_NT 10.0.17763
?[0m?[37;40mgyp?[0m ?[0m?[31;40mERR!?[0m ?[0m?[35mcommand?[0m "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\foo\\AppData\\Roaming\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--target=9.0.3" "--arch=x64" "--dist-url=https://electronjs.org/headers"
?[0m?[37;40mgyp?[0m ?[0m?[31;40mERR!?[0m ?[0m?[35mcwd?[0m C:\Users\foo\Desktop\project\app\node_modules\zeromq
?[0m?[37;40mgyp?[0m ?[0m?[31;40mERR!?[0m ?[0m?[35mnode -v?[0m v10.16.3
?[0m?[37;40mgyp?[0m ?[0m?[31;40mERR!?[0m ?[0m?[35mnode-gyp -v?[0m v7.0.0
?[0m?[37;40mgyp?[0m ?[0m?[31;40mERR!?[0m ?[0m?[35mnot ok?[0m
?[0m
```

And when I dig a bit deeper into the npm log I find the following:

```
89 verbose stack Error: zeromq@6.0.0-beta.6 install: `node-gyp-build`
89 verbose stack Exit status 1
89 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
89 verbose stack     at EventEmitter.emit (events.js:198:13)
89 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
89 verbose stack     at ChildProcess.emit (events.js:198:13)
89 verbose stack     at maybeClose (internal/child_process.js:982:16)
89 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
90 verbose pkgid zeromq@6.0.0-beta.6
91 verbose cwd C:\Users\foo\Desktop\project\app
92 verbose Windows_NT 10.0.17763
93 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "zeromq" "--save-dev" "--build-from-source"
94 verbose node v10.16.3
95 verbose npm  v6.14.5
96 error code ELIFECYCLE
97 error errno 1
98 error zeromq@6.0.0-beta.6 install: `node-gyp-build`
98 error Exit status 1
99 error Failed at the zeromq@6.0.0-beta.6 install script.
99 error This is probably not a problem with npm. There is likely additional logging output above.
100 verbose exit [ 1, true ]
```

I also tried defining the zeromq module in webpack by using externals:
```
 externals: {
    zeromq: 'zeromq'
  }`
Or
`  externals: {
    zeromq: 'require(zeromq)'
  }
```
I also used added a node loader to my config to be able to deal with it (😎)
The only change this gives me is that the log of my zeromq shows up as **undefined**

I dived into the whole electron-rebuild rabbit hole but nothing seems to work. I read some stuff about changing files in the zeromq library but that just feels wrong. No way to maintain fixes like that.

I'm very grateful for any input you can provide me with because I'm kind of at my wits end here 😅🙏

**Comment by MrSpijker** [comment]
This error was due to zeromq not serving the binary for said version.
Using 5.2.0 and running `npm rebuild zeromq --runtime=electron --target=9.0.3` solved it for me :)

**Comment by OMY-onlymissyou** [comment]
> npm rebuild zeromq --runtime=electron --target=9.0.3

Hello, what does this command mean
