### ISSUE TITLE
download electron-v9.1.0-win32-ia32.zip giving error- Response code 403 (Forbidden)

### ISSUE THREAD

**Issue by debchy** [electron/electron#24444]
my code is trying to download any of the bellow as per verstion i mention
https://github.com/electron/electron/releases/download/v9.1.0/electron-v9.1.0-win32-ia32.zip
or
https://github.com/electron/electron/releases/download/v9.0.3/electron-v9.0.3-win32-ia32.zip

I am under proxy. i set NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0'
then it's showing that [HTTPError]: Response code 403 (Forbidden)

For more info:
```
GotError [HTTPError]: Response code 403 (Forbidden)
    at EventEmitter.<anonymous> (C:\Currently Working\Mirsal-DesktopApp - Copy (3)\node_modules\got\source\as-stream.js:35:24)
    at EventEmitter.emit (events.js:196:13)
    at EventEmitter.emit (domain.js:494:23)
    at module.exports (C:\Currently Working\Mirsal-DesktopApp - Copy (3)\node_modules\got\source\get-response.js:22:10)
    at ClientRequest.handleResponse (C:\Currently Working\Mirsal-DesktopApp - Copy (3)\node_modules\got\source\request-as-event-emitter.js:155:5)
    at Object.onceWrapper (events.js:284:20)
    at ClientRequest.emit (events.js:201:15)
    at ClientRequest.EventEmitter.emit (domain.js:494:23)
    at ClientRequest.origin.emit (C:\Currently Working\Mirsal-DesktopApp - Copy (3)\node_modules\@szmarczak\http-timer\source\index.js:37:11)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:572:23) {
  name: 'HTTPError',
  host: 'github.com',
  hostname: 'github.com',
  method: 'GET',
  path: '/electron/electron/releases/download/v9.1.0/electron-v9.1.0-win32-ia32.zip',
  socketPath: undefined,
  protocol: 'https:',
  url: 'https://github.com/electron/electron/releases/download/v9.1.0/electron-v9.1.0-win32-ia32.zip',
  gotOptions: {
    path: '/electron/electron/releases/download/v9.1.0/electron-v9.1.0-win32-ia32.zip',
    protocol: 'https:',
    slashes: true,
    auth: null,
    host: 'github.com',
    port: null,
    hostname: 'github.com',
    hash: null,
    search: null,
    query: null,
    pathname: '/electron/electron/releases/download/v9.1.0/electron-v9.1.0-win32-ia32.zip',
    href: 'https://github.com/electron/electron/releases/download/v9.1.0/electron-v9.1.0-win32-ia32.zip',
    retry: {
      retries: [Function],
      methods: [Set],
      statusCodes: [Set],
      errorCodes: [Set]
    },
    headers: {
      'user-agent': 'got/9.6.0 (https://github.com/sindresorhus/got)',
      'accept-encoding': 'gzip, deflate'
    },
    hooks: {
      beforeRequest: [],
      beforeRedirect: [],
      beforeRetry: [],
      afterResponse: [],
      beforeError: [],
      init: []
    },
    decompress: true,
    throwHttpErrors: true,
    followRedirect: true,
    stream: true,
    form: false,
    json: false,
    cache: false,
    useElectronNet: false,
    method: 'GET'
  },
  statusCode: 403,
  statusMessage: 'Forbidden',
  headers: {
    'cache-control': 'no-cache',
    pragma: 'no-cache',
    'content-type': 'text/html; charset=utf-8',
    connection: 'close',
    'content-length': '8375'
  },
  body: undefined
}
```

**Comment by codebytere** [comment]
@debchy please report issues of this nature to GitHub - they're hosting the resources in this case.
