### ISSUE TITLE
Packaged electron app (electron-packager/electron-builder) exe does not work on Windows 10 S

### ISSUE THREAD

**Issue by markibanez** [electron/electron#24700]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * 9.1.0
* **Operating System:**
  * Windows 10 (2004)
* **Last Known Working Electron version:**
  * Not Applicable

### Expected Behavior
For the app to launch and open its window

### Actual Behavior
Shows a javascript error dialog show 
```
Uncaught Exception:
Error: spawn UNKNOWN
     at ChildProcess.spawn (internal/child_process.js:394:11)
     at spawn (child_process.js:549:9)
     at new Shell (C:\Program Files\WindowsApps\...)
     at module.exports (C:\Program Files\WindowsApps\...)
     at Object.<anonymous> (C:\Program Files\WindowsApps\...)
     at Modules._compile (internal/modules/cjs/loader.js:967:30)
     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1004:10)
     at Module.load (internal/modules/cjs/loader.js:815:32)
     at Module._load (internal/modules/cjs/loader.js:727:14)
     at Function.Module._load (electron/js2c/asar.js:769:28)
```

### To Reproduce

1. Package app with electron-packager or electron-builder
2. Create appx package with makeappx.exe
3. Sign appx package with test certificate from Microsoft (AppxTestRootAgency.pfx - https://docs.microsoft.com/en-us/windows/msix/desktop/desktop-to-uwp-test-windows-s). 
4. Install and launch appx package on Windows 10. At this point the app works on regular Windows 10, but not on Windows 10 S

### Screenshots
![image](https://user-images.githubusercontent.com/7534847/88241965-58916e80-ccbe-11ea-9165-355438e503bc.png)

**Comment by markibanez** [comment]
Nevermind, it was an issue with node-powershell. If you use it in your electron code, it will cause problems when running in Windows 10 S. The code below was the culprit.

```
    let ps;
    if (process.platform == 'win32') {
        const Shell = require('node-powershell');

        //the next line causes the error
        ps = new Shell({
            executionPolicy: 'Bypass',
            noProfile: true
        });
    }
```
