### ISSUE TITLE
Error when compiling electron

### ISSUE THREAD

**Issue by pangufirst** [electron/electron#24732]
environment win10pro-1909、VS2017-15.9.25、python2.7.17、nodejs10.11.0
When I compiling electron4.0.2 on windows10，I got it

```
ninja: Entering directory `out/Debug'
[1/16348] ACTION //mojo/public/tools/bindings:precompile_templates(//build/toolchain/win:win_clang_x64)
FAILED: gen/mojo/public/tools/bindings/cpp_templates.zip gen/mojo/public/tools/bindings/java_templates.zip gen/mojo/public/tools/bindings/js_templates.zip
E:/depot_tools/bootstrap-3_8_0_chromium_8_bin/python/bin/python.exe ../../mojo/public/tools/bindings/mojom_bindings_generator.py --use_bundled_pylibs precompile -o gen/mojo/public/tools/bindings
Traceback (most recent call last):
  File "../../mojo/public/tools/bindings/mojom_bindings_generator.py", line 505, in <module>
    sys.exit(main())
  File "../../mojo/public/tools/bindings/mojom_bindings_generator.py", line 501, in main
    return args.func(args, remaining_args)
  File "../../mojo/public/tools/bindings/mojom_bindings_generator.py", line 315, in _Precompile
    template_expander.PrecompileTemplates(generator_modules, args.output_dir)
  File "E:\src\mojo\public\tools\bindings\pylib\mojom\generate\template_expander.py", line 54, in PrecompileTemplates
    ignore_errors=False)
  File "E:\src\mojo\public\tools\bindings\pylib\mojom\generate\..\..\..\..\..\..\..\third_party\jinja2\environment.py", line 709, in compile_templates
    code = self.compile(source, name, filename, True, True)
  File "E:\src\mojo\public\tools\bindings\pylib\mojom\generate\..\..\..\..\..\..\..\third_party\jinja2\environment.py", line 591, in compile
    self.handle_exception(exc_info, source_hint=source_hint)
  File "E:\src\mojo\public\tools\bindings\pylib\mojom\generate\..\..\..\..\..\..\..\third_party\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "E:\src\mojo\public\tools\bindings\generators\js_templates\lite\enum_definition.tmpl", line 5, in template
    {%- set enum_name = enum|lite_closure_type -%}
jinja2.exceptions.TemplateAssertionError: no filter named 'lite_closure_type'
[6/16348] CXX obj/skia/skia_core_and_effects/SkDraw_vertices.obj
ninja: build stopped: subcommand failed.
```

**Comment by ckerr** [comment]
Thanks for the report!

This happens once in awhile and this trace is outside of Electron's codebase. Occasionally hiccups happen upstream. I'd suggest running [`e sync`](https://github.com/electron/build-tools) again in awhile and trying again.

Since this appears to be a transient error -- e.g., master is building for me at the moment -- I'm going to close this ticket, at least for the time being.

**Comment by ckerr** [comment]
One followup to the above comment: sometimes if there is a temporary depot_tools issue, you can go into `build-tools/third_party/depot_tools` and try bumping the snapshot forwards or backwards to a different commit. For example, in the last couple of days I hit a build failure where sync failed with a GN error "Var is the only allowed function" and I was able to get past it by git pulling a new version.

Ordinarily it's safest to leave that alone and let build-tools figure out what depot-tools snapshot to use -- but when that's not working, this can be a useful workaround.

**Comment by pangufirst** [comment]
Sorry for the late reply, and finally the compilation is completed on the linux system.
