### ISSUE TITLE
SimpleURLLoader does not work with register*Protocol

### ISSUE THREAD

**Issue by sentialx** [electron/electron#25157]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * master
* **Operating System:**
  * Windows 10
* **Last Known Working Electron version:**
  * undefined

### Expected Behavior
SimpleURLLoader and `net` should work with protocols registered through `register*Protocol` APIs.

### Actual Behavior
Making a request using `SimpleURLLoader` to an URL with a custom scheme registered through `register*Protocol` throws -302 (ERR_UNKNOWN_URL_SCHEME), but works fine with `intercept*Protocol`. `net` module doesn't even try to make a request to a scheme that is not in `kSupportedProtocols`.

It does not respect `NonNetworkURLLoaderFactoryMap` and reaches this code (removing the check makes the request fail with -2):
https://source.chromium.org/chromium/chromium/src/+/master:net/url_request/url_request_job_manager.cc;l=63?q=UNKNOWN_URL_SCHEME

### To Reproduce
https://gist.github.com/ca870d4558119e31e991bb5cf61981c5

The app should print `asdf` and `test` in the console.

**Comment by RangerMauve** [comment]
This would be very nice to have. Are there pointers for where in the code one would need to go to get started on implementing something like this?

**Comment by RangerMauve** [comment]
It's happening on GNOME linux, too, so I don't think it's platform dependent

**Comment by ckerr** [comment]
The gist shows the issue as reported:

```
Error: Protocol "asdf:" not supported
    at parseOptions (electron/js2c/browser_init.js:101:2955)
    at new ClientRequest (electron/js2c/browser_init.js:101:4200)
    at Net.a.request (electron/js2c/browser_init.js:101:7943)
    at makeRequest (/home/charles/virtualbox-shared/triage/25157/main.js:20:27)
    at App.createWindow (/home/charles/virtualbox-shared/triage/25157/main.js:14:3)
    at App.emit (events.js:310:20)
Error: Protocol "test:" not supported
    at parseOptions (electron/js2c/browser_init.js:101:2955)
    at new ClientRequest (electron/js2c/browser_init.js:101:4200)
    at Net.a.request (electron/js2c/browser_init.js:101:7943)
    at makeRequest (/home/charles/virtualbox-shared/triage/25157/main.js:20:27)
    at App.createWindow (/home/charles/virtualbox-shared/triage/25157/main.js:15:3)
    at App.emit (events.js:310:20)
```

@RangerMauve is correct that it's not OS-dependent. I'm seeing it on both Windows and Linux, which makes sense for a protocol registration issue.

This isn't a new issue -- the repro gives the same output (albeit with different line numbers) for Electron 9 and 8 as well.

**Comment by RangerMauve** [comment]
I think this is still an issue?

**Comment by RangerMauve** [comment]
Bump

**Comment by RangerMauve** [comment]
This would still be nice to have.

**Comment by RangerMauve** [comment]
This would still be nice to have.

**Comment by MarshallOfSound** [comment]
This has been supported for quite a while now
