### ISSUE TITLE
can not find .node file

### ISSUE THREAD

**Issue by LodoF** [electron/electron#25185]
### Issue Details

* **Electron Version: 4.0.0
* **Operating System: Windows 10
* **Last Known Working Electron version:4.0.0

### Expected Behavior
 electron work

### Actual Behavior
I import a dependency package compiled by C ++ and this package is existed,  but I couldn't find it when I started electron。

### To Reproduce

```sh
 Error: The specified module could not be found.
  \\?\D:\qtbox\58pic_box\node_modules\setfolderreadonly\lib\napi-v3\setfolderreadonly.node
      at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:160:31)
      at Object.Module._extensions..node (internal/modules/cjs/loader.js:722:18)
      at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:160:31)
      at Module.load (internal/modules/cjs/loader.js:602:32)
      at tryModuleLoad (internal/modules/cjs/loader.js:541:12)
      at Function.Module._load (internal/modules/cjs/loader.js:533:3)
      at Module.require (internal/modules/cjs/loader.js:640:17)
      at require (internal/modules/cjs/helpers.js:20:18)
      at Object.<anonymous> (D:\qtbox\58pic_box\node_modules\setfolderreadonly\main.js:4:15)
      at Object.<anonymous> (D:\qtbox\58pic_box\node_modules\setfolderreadonly\main.js:30:3)

```

**Comment by MarshallOfSound** [comment]
Electron 4.0 is unsupported, please update to the latest stable version of Electron and re-test

**Comment by 15262480325** [comment]
My version is 17.1.2, and I'm also experiencing this issue. Is it possible that the Windows system is missing a certain library?

**Comment by 15262480325** [comment]
![image](https://github.com/electron/electron/assets/28424434/45f0f154-73a5-40e7-a54e-f57ff7669163)
