### ISSUE TITLE
Electron and custom openssl engine

### ISSUE THREAD

**Issue by heol-files** [electron/electron#25497]
I tried to add a custom PKCS11 private key engine in my electron project to open a TSL socket with my HSM.
And it does not work, I get the error:
>  MQTT connect err: Error [ERR_CRYPTO_CUSTOM_ENGINE_NOT_SUPPORTED]: Custom engines not supported by this OpenSSL
    at Object.createSecureContext (_tls_common.js:184:15)
    at Object.connect (_tls_wrap.js:1576:48)
    at Object.buildBuilder (C:\Users\henri\git\xot_client\nodejs\xot_client\node_modules\mqtt\lib\connect\tls.js:17:20)
    at MqttClient.wrapper [as streamBuilder] (C:\Users\henri\git\xot_client\nodejs\xot_client\node_modules\mqtt\lib\connect\index.js:153:36)
    at MqttClient._setupStream (C:\Users\henri\git\xot_client\nodejs\xot_client\node_modules\mqtt\lib\client.js:298:22)
    at new MqttClient (C:\Users\henri\git\xot_client\nodejs\xot_client\node_modules\mqtt\lib\client.js:277:8)
    at Object.connect (C:\Users\henri\git\xot_client\nodejs\xot_client\node_modules\mqtt\lib\connect\index.js:155:16)
    at XMS.connect (C:\Users\henri\git\xot_client\nodejs\xot_client\dist\backend\XMS.js:88:30)
    at Tokens.<anonymous> (C:\Users\henri\git\xot_client\nodejs\xot_client\dist\backend\electron.js:355:13)
    at Tokens.emit (events.js:310:20) {
  code: 'ERR_CRYPTO_CUSTOM_ENGINE_NOT_SUPPORTED'

Is this something that could be fixed (recompiling electron with other libs/settings/configuration) or added in newer versions of Electron?

I'm running Electron v10.1.2 and node v12.18.4
And i set the OPENSSL_CONF=./pkcs11.conf with:
`openssl_conf = openssl_init

[openssl_init]
engines = engine_section

[engine_section]
pkcs11 = pkcs11_section

[pkcs11_section]
engine_id = pkcs11
dynamic_path = ../../3rd-party/pkcs11.dll
MODULE_PATH = ./iidxp11_u32.dll
init = 0
`
I have another node js test project without Electron and it works fine.

**Comment by MarshallOfSound** [comment]
Electron does not use openssl, we utilize boringssl instead as a drop in replacement.  This config is probably unsupported by boringssl

**Comment by heol-files** [comment]
Hmmm... not good
So there is no way around it? 
What is the reason for this change between openssl and boringss?l
