### ISSUE TITLE
Build fails with python 3

### ISSUE THREAD

**Issue by bentucker** [electron/electron#25553]
### Preflight Checklist

* [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [X] I have searched the issue tracker for similar issues, with no success.

```bash
$ ninja -C out/Release electron
ninja: Entering directory `out/Release'
```
```python
[6/34010] ACTION //mojo/public/tools/bindings:precompile_templates(//build/toolchain/linux:clang_x64)
FAILED: gen/mojo/public/tools/bindings/cpp_templates.zip gen/mojo/public/tools/bindings/java_templates.zip gen/mojo/public/tools/bindings/js_templates.zip gen/mojo/public/tools/bindings/ts_templates.zip
python ../../mojo/public/tools/bindings/mojom_bindings_generator.py -o gen/mojo/public/tools/bindings --use_bundled_pylibs precompile
Traceback (most recent call last):
  File "../../mojo/public/tools/bindings/mojom_bindings_generator.py", line 390, in <module>
    sys.exit(main())
  File "../../mojo/public/tools/bindings/mojom_bindings_generator.py", line 385, in main
    return args.func(args, remaining_args)
  File "../../mojo/public/tools/bindings/mojom_bindings_generator.py", line 256, in _Precompile
    generator_modules = LoadGenerators(",".join(_BUILTIN_GENERATORS.keys()))
  File "../../mojo/public/tools/bindings/mojom_bindings_generator.py", line 71, in LoadGenerators
    generator_module = importlib.import_module(
  File "/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<<REDACTED>>/mojo/public/tools/bindings/generators/mojom_mojolpm_generator.py", line 7, in <module>
    from mojom_cpp_generator import _NameFormatter as CppNameFormatter
ModuleNotFoundError: No module named 'mojom_cpp_generator'
[19/34010] CXX obj/ppapi/cpp/objects/var_private.o
ninja: build stopped: subcommand failed.
```
I was able to resolve this by running ninja inside a virtual env using python 2.

```bash
$ pew new electron -p python2
(electron) $ ninja -C out/Release electron
ninja: Entering directory `out/Release'
[11928/33968] CXX obj/third_party/webrtc/pc/peerconnection/peer_connection_factory.o
```

The build hasn't completed yet, but this got me past the mojo issue. I'll post an update when the build finishes.

**Comment by bentucker** [comment]
Update: build finished successfully using the python2 virtual env.

**Comment by nornagon** [comment]
`mojom_bindings_generator.py` is upstream code, not ours. Best to report this to Chromium: https://crbug.com/new.
