### ISSUE TITLE
Slack Mac desktop app crash

### ISSUE THREAD

**Issue by mehmetsaygin** [electron/electron#25823]
Hi,

For 2 days I can't start the Slack mac desktop app. [Version 4.10.0 (6415)]
Reinstalled the app but it didn't help.

I am getting this error message;

A JavaScript error occurred in the main process

Uncaught Exception:
Error: Tried to send an error but the reporter was not initialized!
    at Object.notify (/Applications/Slack.app/Contents/Resources/app.asar/dist/main.bundle.js:2:1559504)
    at notifyError (/Applications/Slack.app/Contents/Resources/app.asar/dist/main.bundle.js:2:1751146)
    at /Applications/Slack.app/Contents/Resources/app.asar/dist/main.bundle.js:2:1751706
    at /Applications/Slack.app/Contents/Resources/app.asar/dist/main.bundle.js:2:2104510
    at CatchErrorSubscriber.onError (/Applications/Slack.app/Contents/Resources/app.asar/dist/main.bundle.js:2:2104600)
    at CatchErrorSubscriber._error (/Applications/Slack.app/Contents/Resources/app.asar/dist/main.bundle.js:2:2105201)
    at CatchErrorSubscriber.Subscriber.error (/Applications/Slack.app/Contents/Resources/app.asar/dist/main.bundle.js:2:50808)
    at TapSubscriber._error (/Applications/Slack.app/Contents/Resources/app.asar/dist/main.bundle.js:2:2107587)
    at TapSubscriber.Subscriber.error (/Applications/Slack.app/Contents/Resources/app.asar/dist/main.bundle.js:2:50808)
    at TakeUntilSubscriber.Subscriber._error (/Applications/Slack.app/Contents/Resources/app.asar/dist/main.bundle.js:2:51167)

How can I fix this?
Have a nice day.

**Comment by lorenzorivosecchi** [comment]
Me too, Slack Desktop for Mac Version 4.10.0

**Comment by lorenzorivosecchi** [comment]
Fixed by upgrading to 4.10.1

https://apps.apple.com/it/app/slack/id803453959?mt=12

**Comment by mehmetsaygin** [comment]
Thank you very much, it was not available yesterday. It works now.
