### ISSUE TITLE
A random error

### ISSUE THREAD

**Issue by adel-sbeh** [electron/electron#26025]
This error keeps occurring randomly when the URL of the `webview` changes.
```
Error occurred in handler for 'ELECTRON_GUEST_VIEW_MANAGER_CALL': Error:  (-3) loading 'file:///C:/Users/win10/Desktop/My%20projects/EnderServices/Apps/installed/com/enderadel/test/content/_main.html'
    at rejectAndCleanup (electron/js2c/browser_init.js:205:1288)
    at WebContents.failListener (electron/js2c/browser_init.js:205:1505)
    at WebContents.emit (events.js:322:22) {
  errno: -3,
  code: '',
  url: 'file:///C:/Users/win10/Desktop/My%20projects/EnderServices/Apps/installed/com/enderadel/test/content/_main.html'
}
```
<a href="https://ibb.co/YhYKvcj"><img src="https://i.ibb.co/zZjLKXf/Test-10-18-2020-9-54-47-PM.png" alt="Test-10-18-2020-9-54-47-PM" border="0"></a>

**Comment by adel-sbeh** [comment]
Oh, the repository is https://github.com/EnderAdel/EnderFramework.

**Comment by nornagon** [comment]
Thanks for reaching out!

We require the template to be filled out on all new issues and pull requests. We do this so that we can be certain we have all the information we need to address your submission efficiently. This allows the maintainers to spend more time fixing bugs, implementing enhancements, and reviewing and merging pull requests.

Thanks for understanding and meeting us half way :grinning:

**Comment by adel-sbeh** [comment]
```js
document.addEventListener("DOMContentLoaded", function(){
  var sInt = setInterval(() => {
    document.getElementById("_cover").style.display = "block";
    if(doneLoadingInfo(-1) == (tN - 1)){
      content = document.getElementById("_contentView");
      if(!isSub){
        content.setAttribute("src", appPath + "content\\_main.html");
      }else{
        content.setAttribute("src", path.join(appPath, "content\\", subInfo.url));
      }
      content.addEventListener("dom-ready", function(){
        content.focus();
      });
      content.addEventListener("DOM", function(){ });
      _content = content;
      content.setAttribute("preload", startPath_ + "dp\\_manager\\_contentPreload.js");
      document.getElementById("_cover").style.display = "none";
      var enableDevTools = "no", enableSpellcheck = "no", enableJavaScript = "yes";
      if(devTools_){
        enableDevTools = "yes";
      }
      if(spellcheck_){
        enableSpellcheck = "yes";
      }
      if(!JavaScript_){
        enableJavaScript = "no";
      }
      content.setAttribute("webpreferences", "devTools=" + enableDevTools + ", nodeIntegration=yes, nodeIntegrationInWorker=yes, nodeIntegrationInSubFrames=yes, sandbox=no, webviewTag=yes, enableRemoteModule=yes, javascript=" + enableJavaScript + ", webSecurity=yes, images=yes, textAreasAreResizable=no, webgl=yes, experimentalFeatures=no, scrollBounce=no, defaultFontFamily=\"standard\", defaultFontSiz=16, defaultMonospaceFontSize=13, minimumFontSize=0, defaultEncoding=\"ISO-8859-1\", offscreen=no, contextIsolation=no, nativeWindowOpen=no, safeDialogs=no, navigateOnDragDrop=no, autoplayPolicy=\"no-user-gesture-required\" disableHtmlFullscreenWindowResize=no, spellcheck=" + enableSpellcheck);
      content.setAttribute("enableremotemodule", "true");
      var first = true, isMainLoad = true;
      content.addEventListener('did-frame-finish-load', (e) => {
        if(e.isMainFrame && first){
          first = false;
          doneLoadingInfo();
        }else if(e.isMainFrame){
          isMainLoad = false;
        }
      });
      content.addEventListener('will-navigate', function(){
        isMainLoad = true;
      });
      content.addEventListener('did-start-loading', function(){
        if(isMainLoad == true){
          document.getElementById("_cover").style.display = "block";
        }
      });
      content.addEventListener('did-finish-loading', function(){
        isMainLoad = false;
      });
      var showSrrorScreen = function(){
        document.getElementById("_cover").style.display = "block";
        document.getElementById("_ErrorScreen").style.display = "block";
      }, hideErrorScreen = function(){
        document.getElementById("_cover").style.display = "block";
        document.getElementById("_ErrorScreen").style.display = "none";
      };
      content.addEventListener('did-fail-load', function(e){
        if(e.isMainFrame){
          showSrrorScreen();
        }else{
          alert("Error!");
        }
      });
      content.addEventListener('crashed', function(e){
        document.getElementById("_CrashScreen").style.display = "block";
      });
      content.addEventListener('dom-ready', function (){
        try{
          document.getElementById("_cover").style.display = "block";
          content.insertCSS(style);
          content.executeJavaScript("global.path_ = \"" + appPath.replace(/\\/g, "\\\\") + "\";");
        }catch{
          alert("Something went wrong!");
          showSrrorScreen();
        }
      });
      content.addEventListener('ipc-message', event => {
        [...]
      });
      content.addEventListener("did-stop-loading", function(){
          document.getElementById("_cover").style.display = "none";
      });
      content.addEventListener('new-window', function(e){
        const opn_ = require("opn");
        opn_(e.url);
      });
      content.addEventListener('enter-html-full-screen', function(){
        document.getElementById("_maxWin").style.display = "none";
        document.getElementById("_exitFullscreen").style.display = "inline-block";
        var ETH = document.querySelectorAll("[hideInFullscreen]");
        for(var i = 0; i < ETH.length; i++)
          ETH[i].classList.add("FSH");
      });
      content.addEventListener('leave-html-full-screen', function(){
        document.getElementById("_maxWin").style.display = "inline-block";
        document.getElementById("_exitFullscreen").style.display = "none";
        var ETH = document.querySelectorAll("[hideInFullscreen]");
        for(var i = 0; i < ETH.length; i++)
          ETH[i].classList.remove("FSH");
      });
      setTimeout(function(){
        if(devTools_){
          content.openDevTools();
        }
      }, 1000);
      clearInterval(sInt);
    }
  }, 10);
});
```

**Comment by adel-sbeh** [comment]
```html
<!DOCTYPE html>
<html lang="en">
  <head>
    [...]
  </head>
  <body window-background>
    <webview id="_contentView" hideInFullscreen style="display: none;"></webview>
    <div id="_cover" class="cover"></div>
    <div id="__longLoading" class="cover" style="display: none;">
      <loading></loading>
    </div>
    <div id="_longLoading" class="cover" style="display: none;">
      <loading></loading>
    </div>
    <div id="_ErrorScreen" style="display: none;">
      <float center pageCenter20>
        <h1 boldText>An error has accured!</h1>
        <h3 lightText>This page has failed to load, the page path might be incorrect.</h3>
        <button primary>Reload</button>
        <button>Go home</button>
      </float>
    </div>
    <div id="_CrashScreen" style="display: none;">
      <float center pagecenter20>
        <h1 boldtext>Oops, something went wrong!</h1>
        <h3 lighttext>The app has crashed! You might want to report this to the app's developers.</h3>
        <button primary>Close the app</button>
        <button>restart</button>
      </float>
    </div>
  </body>
</html>
```

**Comment by ckerr** [comment]
Hi @adel-sbeh, thanks for the test case.

It looks like it might be incomplete -- for example I see a preload.js referenced in the first code body that doesn't seem to be included here, and it's not clear to me from this code whether the preload is needed for this test or not. Would it be possible to reduce this down to the *minimal test case* that reproduces the issue by itself without any other code?

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

Also, please respond to @nornagon's previous request for the information that the new issue template prompts you for. Even if this repro works as-is, we wouldn't know if we were testing it correctly because we don't know the other required information, e.g. what platform you're running on, what version of Electron to test with, and so on.

I understand how providing an isolated test case and filling out issue information can be a headache; but without it, there's no practical way for a small team like Electron's to make headway in our issue tracker. Thank you for meeting us halfway!

**Comment by adel-sbeh** [comment]
I found the cause of this error. It was an `executeJavaScript` function.
