### ISSUE TITLE
npm ERR! Failed at the macos-alias@0.2.11 install script.

### ISSUE THREAD

**Issue by Jaikub97** [electron/electron#26337]
###  electron 打包异常，出现错误
`D:\project\PC_IM\electron_vplus_gd\node_modules\macos-alias>if not defined npm_config_node_gyp (node "C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )`

macos本身是mac系统开发的，但是我也执行过\macos-alias依赖下载，win10环境，node_modules存在macos-alias；主要问题还是
**if not defined npm_config_node_gyp**

附属详细的报文：
`开始打包...
  • electron-builder version=19.56.2
  • loaded configuration file=package.json ("build" field)
  • writing effective config file=dist\electron-builder.yaml
  • rebuilding native production dependencies platform=win32 arch=ia32
Error: C:\Program Files\nodejs\node.exe exited with code 1
Output:

> macos-alias@0.2.11 install D:\project\PC_IM\electron_vplus_gd\node_modules\macos-alias
> node-gyp rebuild

D:\project\PC_IM\electron_vplus_gd\node_modules\macos-alias>if not defined npm_config_node_gyp (node "C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
�ڴ˽��������һ������һ����Ŀ����Ҫ���ò������ɣ������ӡ�-m�����ء�
  volume.cc
  win_delay_load_hook.cc
D:\project\PC_IM\electron_vplus_gd\node_modules\macos-alias\src\volume.cc(9,1): fatal error C1189: #error:  This platform is not implemented yet [D:\project\PC_IM\electron_vplus_gd\node_modules\macos-alias\build\volume.vcxproj]

Error output:
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\MSBuild\Current\Bin\MSBuild.exe` failed with exit code: 1   
gyp ERR! stack     at ChildProcess.onExit (C:\Users\Administrator\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\build.js:194:23) 
gyp ERR! stack     at ChildProcess.emit (events.js:321:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\Administrator\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\project\PC_IM\electron_vplus_gd\node_modules\macos-alias
gyp ERR! node -v v12.16.0
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! macos-alias@0.2.11 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the macos-alias@0.2.11 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2020-11-04T08_40_41_661Z-debug.log

    at ChildProcess.<anonymous> (D:\project\PC_IM\electron_vplus_gd\node_modules\builder-util\src\util.ts:241:14)
    at Object.onceWrapper (events.js:428:26)
    at ChildProcess.emit (events.js:321:20)
    at maybeClose (internal/child_process.js:1021:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
From previous event:
    at spawn (D:\project\PC_IM\electron_vplus_gd\node_modules\builder-util\src\util.ts:200:3)
    at D:\project\PC_IM\electron_vplus_gd\node_modules\electron-builder-lib\src\util\yarn.ts:171:5
From previous event:
    at rebuild (D:\project\PC_IM\electron_vplus_gd\node_modules\electron-builder-lib\out\util\yarn.js:93:22)
    at D:\project\PC_IM\electron_vplus_gd\node_modules\electron-builder-lib\src\util\yarn.ts:20:11
    at Generator.next (<anonymous>)
    at processImmediate (internal/timers.js:456:21)
From previous event:
    at installOrRebuild (D:\project\PC_IM\electron_vplus_gd\node_modules\electron-builder-lib\out\util\yarn.js:31:21)
    at D:\project\PC_IM\electron_vplus_gd\node_modules\electron-builder-lib\src\packager.ts:442:7
    at Generator.next (<anonymous>)
From previous event:
    at Packager.installAppDependencies (D:\project\PC_IM\electron_vplus_gd\node_modules\electron-builder-lib\out\packager.js:496:11)
    at D:\project\PC_IM\electron_vplus_gd\node_modules\electron-builder-lib\src\packager.ts:356:20
    at Generator.next (<anonymous>)
From previous event:
    at Packager.doBuild (D:\project\PC_IM\electron_vplus_gd\node_modules\electron-builder-lib\out\packager.js:432:11)
    at D:\project\PC_IM\electron_vplus_gd\node_modules\electron-builder-lib\src\packager.ts:308:52
    at Generator.next (<anonymous>)
    at D:\project\PC_IM\electron_vplus_gd\node_modules\graceful-fs\graceful-fs.js:144:16
    at D:\project\PC_IM\electron_vplus_gd\node_modules\graceful-fs\graceful-fs.js:61:14
    at FSReqCallback.oncomplete (fs.js:154:23)
From previous event:
    at Packager._build (D:\project\PC_IM\electron_vplus_gd\node_modules\electron-builder-lib\out\packager.js:376:11)
    at D:\project\PC_IM\electron_vplus_gd\node_modules\electron-builder-lib\src\packager.ts:270:23
    at Generator.next (<anonymous>)
    at processImmediate (internal/timers.js:456:21)
From previous event:
    at Packager.build (D:\project\PC_IM\electron_vplus_gd\node_modules\electron-builder-lib\out\packager.js:332:11)
    at D:\project\PC_IM\electron_vplus_gd\node_modules\electron-builder\src\builder.ts:310:40
    at Generator.next (<anonymous>)
From previous event:
    at _build (D:\project\PC_IM\electron_vplus_gd\node_modules\electron-builder\out\builder.js:61:21)
    at Object.build (D:\project\PC_IM\electron_vplus_gd\node_modules\electron-builder\src\builder.ts:280:10)
    at buildTarget (D:\project\PC_IM\electron_vplus_gd\ele-build.js:122:13)
    at build (D:\project\PC_IM\electron_vplus_gd\ele-build.js:86:13)
    at Object.<anonymous> (D:\project\PC_IM\electron_vplus_gd\ele-build.js:76:1)
    at Module._compile (internal/modules/cjs/loader.js:1157:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1177:10)
    at Module.load (internal/modules/cjs/loader.js:1001:32)
    at Function.Module._load (internal/modules/cjs/loader.js:900:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47`

**Comment by Jaikub97** [comment]
win10 
electron1.6.5
node 12.16.0
node-gyp 7.1.2
python 2.7

**Comment by jkleinsc** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!
