### ISSUE TITLE
vm module timeout option not working in main process

### ISSUE THREAD

**Issue by Prinzhorn** [electron/electron#26560]
# Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** v11.0.1
* **Operating System:** Ubuntu 20.04
* **Last Known Working Electron version:** None, I tried 6 through 11

I must assume this is a known issue, since the tests are disabled

https://github.com/electron/electron/blob/e017d8714e75fdc861af612404ea67229e827665/script/node-disabled-tests.json#L151

but I haven't found a mention in the issues. I also cannot find a list of differences between Electron and Node.js. Maybe this would be a great addition? E.g. the use of BoringSSL and all other things that are known to be different and potentially breaking when relying on Node.js compatibility. E.g. similar to this https://www.electronjs.org/docs/development/electron-vs-nwjs but "Differences between Node.js and Electron's Node.js fork".

Anyway, this is about the vm module:

### Expected Behavior

I expect `runInNewContext`s `timeout` option of the vm module to be respected.

### Actual Behavior

It never times out.

### To Reproduce

```js
console.log('runnin');

try {
  require('vm').runInNewContext('while (true);', {}, { timeout: 1 });
} catch (err) {
  console.error(err);
}

console.log('stoppin');
```

Electron:

```
$ npx electron@11 index.js
runnin
# Blocks forever
```

Node.js:

```
$ node index.js 
runnin
vm.js:131
      return super.runInContext(contextifiedObject, ...args);
                   ^

Error: Script execution timed out after 1ms
    at Script.runInContext (vm.js:131:20)
    at doWithTimeout (/home/alex/Projects/Bandsalat/src/issues/vm2-timeout/node_modules/vm2/lib/main.js:467:17)
    at VM.run (/home/alex/Projects/Bandsalat/src/issues/vm2-timeout/node_modules/vm2/lib/main.js:849:10)
    at Object.<anonymous> (/home/alex/Projects/Bandsalat/src/issues/vm2-timeout/index.js:5:24)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47 {
  code: 'ERR_SCRIPT_EXECUTION_TIMEOUT'
}

```

### Additional Information

Originally reported to the vm2 module https://github.com/patriksimek/vm2/issues/307
The comments might help tracing this down https://github.com/patriksimek/vm2/issues/307#issuecomment-728277419

This is explicitly about the **main** process. I don't care about vm being removed from the renderer https://github.com/electron/electron/pull/26087

**Comment by Prinzhorn** [comment]
Turns out it _does_ work in a Worker Thread

```js
const { Worker, isMainThread } = require('worker_threads');

if (isMainThread) {
  console.log('spawnin');
  new Worker(__filename);
} else {
  console.log('runnin');

  try {
    require('vm').runInNewContext('while (true);', {}, { timeout: 1 });
  } catch (err) {
    console.error(err);
  }

  console.log('stoppin');
}
```

```
 $ npx electron@11 worker.js
spawnin
runnin
Error: Script execution timed out after 1ms
    at Script.runInContext (vm.js:130:18)
    at Script.runInNewContext (vm.js:135:17)
    at Object.runInNewContext (vm.js:302:38)
    at Object.<anonymous> (/home/alex/Projects/Bandsalat/src/issues/vm2-timeout/worker.js:10:19)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Function.Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at MessagePort.<anonymous> (internal/main/worker_thread.js:162:24) {
  code: 'ERR_SCRIPT_EXECUTION_TIMEOUT'
}
stoppin

```

I'm doing everything in a worker thread far away from the main process anyway. It's still a bug that the timeout does not work directly in the main process, but it doesn't concern me anymore.

**Comment by ckerr** [comment]
Thanks for reporting this and for including a testcase!

Also, I like the idea of a "known differences" document but it's off-topic for this ticket. Could you file a separate ticket for that so that it can be tracked separately?

> I must assume this is a known issue, since the tests are disabled

Looks like this test has been disabled since we first started running Node.js's test suite in our CI back in https://github.com/electron/electron/commit/1d06f67672a8c148d25a633fc31ae1734087e3df. At that time about 10% of the tests were failing. So this is a known issue in the sense that it's on the exclude list; but since it was one out of hundreds, I don't know if this one has had any specific discussion.
