### ISSUE TITLE
requiring a module that starts with a shebang line fails with a syntax error

### ISSUE THREAD

**Issue by jaked** [electron/electron#26592]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:**
  * v11.0.1
* **Operating System:**
  * macOS 10.14.6
* **Last Known Working Electron version:**
  * v9.1.0

### Expected Behavior

Requiring a module that starts with a shebang line succeeds.

### Actual Behavior

Requiring a module that starts with a shebang line fails with a syntax error. E.g.
```
/private/var/folders/zb/2d7jvr510w7d63g61hm1g4_h0000gn/T/tmp-73288O40CVBPJ0VFF/renderer.js:1
(function (exports, require, module, __filename, __dirname, process, global, Buffer) { return function (exports, require, module, __filename, __dirname) { #! /usr/bin/env node
                                                                                                                                                           ^

SyntaxError: Invalid or unexpected token
    at new Script (vm.js:88:7)
    at createScript (vm.js:261:10)
    at Object.runInThisContext (vm.js:309:10)
    at wrapSafe (internal/modules/cjs/loader.js:1047:15)
    at Module._compile (internal/modules/cjs/loader.js:1108:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12694)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
```

(Lots of modules in the wild ship with shebang lines; I ran into it with `browser-sync`.)

### To Reproduce

Gist for Electron Fiddle: https://gist.github.com/jaked/2b261d8cfbdf2b5c74d7bd8c373dd5fd

### Additional Information

This seems to be due to a Node bug (see https://github.com/nodejs/node/issues/36173) and the fact that Electron monkey patches `Module.wrapper` (see https://github.com/electron/electron/commit/a4fcc32799).

**Comment by ckerr** [comment]
Confirmed as described. Works in 9.3.4, broken in 10.1.6 and 11.0.1. @jaked's diagnosis smells plausible too.

```
vm.js:96 Uncaught /tmp/tmp-1022880XUpb6qNNthx7/renderer.js:1
(function (exports, require, module, __filename, __dirname, process, global, Buffer) { return function (exports, require, module, __filename, __dirname) { #! /usr/bin/env node
                                                                                                                                                           ^

SyntaxError: Invalid or unexpected token
    at new Script (vm.js:88:7)
    at createScript (vm.js:261:10)
    at Object.runInThisContext (vm.js:309:10)
    at wrapSafe (internal/modules/cjs/loader.js:1047:15)
    at Module._compile (internal/modules/cjs/loader.js:1108:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12694)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
```

**Comment by shmulka** [comment]
Can also confirm seeing the same error in 10.1.4 and 11.0.0 when requiring requirejs. Works fine up to 9.3.4

**Comment by kevinwang89** [comment]
I met the exact same problem,  electron 13.1.9
