### ISSUE TITLE
npm i --save-dev electron -> HTTPError

### ISSUE THREAD

**Issue by cyberpwnn** [electron/electron#26841]
```
HTTPError: Response code 404 (Not Found) for https://github.com/electron/electron/releases/download/v11.0.3/electron-v11.0.3-win32-amd64.zip
    at EventEmitter.<anonymous> (C:\Users\cyberpwn\Documents\development\workspace\MyGuide\hololens\node_modules\got\source\as-stream.js:35:24)
    at EventEmitter.emit (events.js:223:5)
    at module.exports (C:\Users\cyberpwn\Documents\development\workspace\MyGuide\hololens\node_modules\got\source\get-response.js:22:10)
    at ClientRequest.handleResponse (C:\Users\cyberpwn\Documents\development\workspace\MyGuide\hololens\node_modules\got\source\request-as-event-emitter.js:155:5)
    at Object.onceWrapper (events.js:313:26)
    at ClientRequest.emit (events.js:228:7)
    at ClientRequest.origin.emit (C:\Users\cyberpwn\Documents\development\workspace\MyGuide\hololens\node_modules\@szmarczak\http-timer\source\index.js:37:11)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:583:27)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:115:17)
    at TLSSocket.socketOnData (_http_client.js:456:22)
```

**Comment by mrluffya** [comment]
### Advise / 建议
尝试通过设置 _'electron_mirror'_ 重新安装，
通过搜索引擎基于位置选择合适的 _'electron_mirror'_

translator e.g.
>Try to reinstall by setting _'electron_mirror'_
Select the appropriate _'electron_mirror'_ through the search engine based on location.


### Try / 尝试解决
```sh
$ # 请参阅：**electron#26827**
$ npm config set electron_mirror https://npm.taobao.org/mirrors/electron/
$ npm config set registry https://registry.npm.taobao.org
$ npm config set disturl https://npm.taobao.org/dist
$ # 重新安装 e.g.
$ npm cache clean -f && rm -rf -v node_modules/electron
$ npm install electron@9.2.1
```


### Additional Information / 附加信息
[electron#26827](#26827)

**Comment by MarshallOfSound** [comment]
It looks like you have a setting on machine that is making node believe it's architecture is `amd64` and therefore Electron tries to fetch an equivalent binary (which doesn't exist).  Please either ensure `process.arch` is `x64` on your machine or set `npm_config_arch=x64` before installing electron
