### ISSUE TITLE
electron install failed：unable to verify the first certificate

### ISSUE THREAD

**Issue by faxinwang** [electron/electron#26910]
### Preflight Checklist

* [ ] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ ] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

I have checked [Electron download failed #21353](https://github.com/electron/electron/issues/21353), but I think it's not the same problem with this one. 

### Issue Details

* **Electron Version:** 
  * 
* **Operating System:** windows
  * 
* **Last Known Working Electron version:**
  * 

### Expected Behavior

1. ** I run `yarn add electron` to install electron but exited with the following errors:**
```
yarn add v1.22.5
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@2.1.3: The platform "win32" is incompatible with this module.
info "fsevents@2.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > @vue/composition-api@1.0.0-beta.21" has unmet peer dependency "vue@>= 2.5 < 3".
warning " > element-ui@2.14.1" has unmet peer dependency "vue@^2.5.17".
warning " > ts-loader@8.0.11" has unmet peer dependency "webpack@*".
[5/5] Building fresh packages...
[5/5] ⡀ electron
[2/5] ⡀ core-js
[-/5] ⢀ waiting...
[-/5] ⢀ waiting...
error D:\Learn\web\quasar\node_modules\electron: Command failed.
Exit code: 1
Command: node install.js
Arguments:
Directory: D:\Learn\web\quasar\node_modules\electron
Output:
RequestError: unable to verify the first certificate
    at ClientRequest.<anonymous> (D:\Learn\web\quasar\node_modules\got\source\request-as-event-emitter.js:178:14)
    at Object.onceWrapper (events.js:418:26)
    at ClientRequest.emit (events.js:323:22)
    at ClientRequest.origin.emit (D:\Learn\web\quasar\node_modules\@szmarczak\http-timer\source\index.js:37:11)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:311:20)
```

2. **Then I set strict-ssl to false of both npm and yarn, and tried `yarn add electron` again, don't work.**

3. **Then I look into node_modules/electron/install.js  and added some `console.log('--',xx)`, and run node .\install.js, got some output:**

```
--remote url: https://github.com/electron/electron/releases/download/v11.0.4/electron-v11.0.4-win32-x64.zip
--cache: Cache {
  cacheRoot: 'C:\\Users\\Administrator\\AppData\\Local\\electron\\Cache'
}
--downloadArtifact err GotError [RequestError]: unable to verify the first certificate
    at ClientRequest.<anonymous> (D:\Learn\web\quasar\node_modules\got\source\request-as-event-emitter.js:178:14)
    at Object.onceWrapper (events.js:418:26)
    at ClientRequest.emit (events.js:323:22)
    at ClientRequest.origin.emit (D:\Learn\web\quasar\node_modules\@szmarczak\http-timer\source\index.js:37:11)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:311:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  name: 'RequestError',
  code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE',
  host: 'github.com',
  hostname: 'github.com',
  method: 'GET',
  path: '/electron/electron/releases/download/v11.0.4/electron-v11.0.4-win32-x64.zip',
  socketPath: undefined,
  protocol: 'https:',
  url: 'https://github.com/electron/electron/releases/download/v11.0.4/electron-v11.0.4-win32-x64.zip',
  gotOptions: {
    path: '/electron/electron/releases/download/v11.0.4/electron-v11.0.4-win32-x64.zip',
    protocol: 'https:',
    slashes: true,
    auth: null,
    host: 'github.com',
    port: null,
    hostname: 'github.com',
    hash: null,
    search: null,
    query: null,
    pathname: '/electron/electron/releases/download/v11.0.4/electron-v11.0.4-win32-x64.zip',
    href: 'https://github.com/electron/electron/releases/download/v11.0.4/electron-v11.0.4-win32-x64.zip',
    retry: {
      retries: [Function],
      methods: [Set],
      statusCodes: [Set],
      errorCodes: [Set]
    },
    headers: {
      'user-agent': 'got/9.6.0 (https://github.com/sindresorhus/got)',
      'accept-encoding': 'gzip, deflate'
    },
    hooks: {
      beforeRedirect: [],
      afterResponse: [],
    throwHttpErrors: true,
    followRedirect: true,
    stream: true,
    json: false,
    cache: false,
    useElectronNet: false,
    method: 'GET'
  }
}
--downloadArtifact err.stack RequestError: unable to verify the first certificate
    at ClientRequest.<anonymous> (D:\Learn\web\quasar\node_modules\got\source\request-as-event-emitter.js:178:14)
    at Object.onceWrapper (events.js:418:26)
    at ClientRequest.emit (events.js:323:22)
    at ClientRequest.origin.emit (D:\Learn\web\quasar\node_modules\@szmarczak\http-timer\source\index.js:37:11)
    at TLSSocket.socketErrorListener (_http_client.js:426:9)
    at TLSSocket.emit (events.js:311:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```
4. ** I checked the cache folder 'C:\Users\Administrator\AppData\Local\electron\Cache' and found the target version has already cached (why don't it just use the cached zip file?). **

5. **Note that I have set ELECTRON_MIRROR to https://npm.taobao.org/mirrors/electron/ of both npm and yarn. **

6. **Then I deleted ELECTRON_MIRROR config item of both npm and yarn, still don't work.**

7. **Note: expect for electron, other packages can be installed normally.**

8. **I use npm to install electron, it also failed with this errors:**
```
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@11.0.4 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron@11.0.4 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

Any help is appreciated!!!

**Comment by luwuer** [comment]
So，why closing this issue without any other explain

**Comment by faxinwang** [comment]
sorry, I forgot what have I done to make it work. I should have recorded it.

**Comment by luwuer** [comment]
Okay, i will updated to this issue if i find out the solution

**Comment by faxinwang** [comment]
It's nice of you to do that. Thanks.

**Comment by luwuer** [comment]
The error is occurred when [electron 
 download zip](https://github.com/electron/electron/blob/3b38ba2ed8cc3437bcc0736aca00d6979e235c33/npm/install.js#L22-L32).

There has two workarounds：
1. Manually download electron.zip (for example: 10.3.0)
    - download zip from https://github.com/electron/electron/releases/download/v10.3.0/electron-v10.3.0-win32-x64.zip
    - unzip to `node_modules/electron/dist/`
    - add a file which named `path.txt` to `node_modules/electron/`
      
        `path.txt`
        ```
        electron.exe
        ```
2. Add environment variable (work for me but not very clearly)
    - `set ELECTRON_MIRROR=http://npm.taobao.org/mirrors/electron/`
    - use `cnpm` to install electron (`yarn` didn't work either)

**Comment by wuqi** [comment]
This issue is still exist now...

**Comment by Lao-Qi** [comment]
I also encountered this problem, checked for two days

**Comment by RadioAc** [comment]
This issue is still exist now

**Comment by Enerwen** [comment]
system：windows 10
electron：17.2.0
1、set ELECTRON_MIRROR=http://npm.taobao.org/mirrors/electron/ in environment variables
2、execute: yarn install
it work for me

**Comment by gastrodia** [comment]
```
PS D:\code\editor> pnpm i -D electron  
 WARN  Moving @vitejs/plugin-vue that was installed by a different package manager to "node_modules/.ignored
 WARN  Moving typescript that was installed by a different package manager to "node_modules/.ignored
 WARN  Moving vite that was installed by a different package manager to "node_modules/.ignored
 WARN  Moving vue-tsc that was installed by a different package manager to "node_modules/.ignored
 WARN  Moving vue that was installed by a different package manager to "node_modules/.ignored
│     at ClientRequest.origin.emit (D:\code\editor\node_modules\.pnpm\@szmarczak+http-timer@1.1.2\node_modules\@szmarczak\http-timer\source\index.js:37:1  
│     at TLSSocket.socketErrorListener (node:_http_client:454:9)
│     at TLSSocket.emit (node:events:527:28)
│     at emitErrorNT (node:internal/streams/destroy:157:8)
│     at emitErrorCloseNT (node:internal/streams/destroy:122:3)
│     at processTicksAndRejections (node:internal/process/task_queues:83:21)
└─ Failed in 6.6s
 ELIFECYCLE  Command failed with exit code 1.
PS D:\code\editor> yarn add electron -D
yarn add v1.22.19
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/2] ⠈ esbuild
error D:\code\editor\node_modules\electron: Command failed.
Exit code: 1                                               
Command: node install.js                                   
Arguments:                                                 
Directory: D:\code\editor\node_modules\electron            
Output:
RequestError: unable to verify the first certificate
    at ClientRequest.<anonymous> (D:\code\editor\node_modules\got\source\request-as-event-emitter.js:178:14)
    at Object.onceWrapper (node:events:642:26)
    at ClientRequest.emit (node:events:539:35)
    at ClientRequest.origin.emit (D:\code\editor\node_modules\@szmarczak\http-timer\source\index.js:37:11)
    at TLSSocket.socketErrorListener (node:_http_client:454:9)
    at TLSSocket.emit (node:events:527:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

```

**Comment by gastrodia** [comment]
`
pnpm install  -D https://registry.npmmirror.com/-/binary/electron/v16.2.7/v16.2.7.tar.gz
`
select electron for `https://registry.npmmirror.com/binary.html?path=electron`

**Comment by leolei032** [comment]
> 
not work for me

**Comment by leolei032** [comment]
> 

This issue is still exist now...

**Comment by sikaco** [comment]
> This issue is still exist now...

run this:
```
NODE_TLS_REJECT_UNAUTHORIZED=0 yarn
```

The only way I founded could resolve this problem.

**Comment by AAAAsea** [comment]
> Could you tell me how to run this ? I've tried but failed.

**Comment by rohxty** [comment]
This issue is still exist now...

**Comment by rohxty** [comment]
> system：windows 10 electron：17.2.0 1、set ELECTRON_MIRROR=http://npm.taobao.org/mirrors/electron/ in environment variables 2、execute: yarn install it work for me

it work for me，Thanks.

**Comment by IOLOII** [comment]
# step1:
```bash
yarn global install cnpm

# or pnpm npm
```

# step2:
```bash
cnpm install electron --global
```
<details>
<summary>See detail</summary>

```bash

macuser@macuserdeMac-mini /Users/macuser/repos/some_project                                                                               master
⚡ yarn global add cnpm    
yarn global v1.22.22
[1/4] 🔍  Resolving packages...
warning cnpm > npm > npmlog@7.0.1: This package is no longer supported.
warning cnpm > npminstall > @npmcli/arborist > npmlog@7.0.1: This package is no longer supported.
warning cnpm > npminstall > node-gyp > npmlog@6.0.2: This package is no longer supported.
warning cnpm > npm > libnpmexec > npmlog@7.0.1: This package is no longer supported.
warning cnpm > npminstall > bin-links > rimraf@3.0.2: Rimraf versions prior to v4 are no longer supported
warning cnpm > npminstall > pacote > read-package-json@6.0.4: This package is no longer supported. Please use @npmcli/package-json instead.
warning cnpm > npm > init-package-json > read-package-json@6.0.4: This package is no longer supported. Please use @npmcli/package-json instead.
warning cnpm > npm > npmlog > gauge@5.0.2: This package is no longer supported.
warning cnpm > npminstall > node-gyp > npmlog > gauge@4.0.4: This package is no longer supported.
warning cnpm > npm > npmlog > are-we-there-yet@4.0.2: This package is no longer supported.
warning cnpm > npminstall > node-gyp > npmlog > are-we-there-yet@3.0.1: This package is no longer supported.
warning cnpm > npm > libnpmdiff > @npmcli/disparity-colors@3.0.1: This package is no longer supported.
warning cnpm > npminstall > node-gyp > make-fetch-happen > cacache > glob@8.1.0: Glob versions prior to v9 are no longer supported
warning cnpm > npminstall > node-gyp > make-fetch-happen > cacache > @npmcli/move-file@2.0.1: This functionality has been moved to @npmcli/fs
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "generator-code > yeoman-generator@7.4.0" has unmet peer dependency "@yeoman/types@^1.1.1".
warning "generator-code > yeoman-generator@7.4.0" has unmet peer dependency "mem-fs@^4.0.0".
warning "generator-code > yeoman-generator > mem-fs-editor@11.1.4" has unmet peer dependency "mem-fs@^4.0.0".
warning " > tailwind-config-viewer@2.0.4" has unmet peer dependency "tailwindcss@1 || 2 || 2.0.1-compat || 3".
warning "yo > yeoman-environment@4.4.3" has unmet peer dependency "@yeoman/types@^1.1.1".
warning "yo > yeoman-environment@4.4.3" has unmet peer dependency "mem-fs@^4.0.0".
warning Workspaces can only be enabled in private projects.
warning Workspaces can only be enabled in private projects.
[4/4] 🔨  Building fresh packages...
success Installed "cnpm@9.4.0" with binaries:
      - cnpm
✨  Done in 38.75s.
(base) 
macuser@macuserdeMac-mini /Users/macuser/repos/some_project                                                                               master
⚡ cnpm i electron --global
Downloading electron to /Users/macuser/.nvm/versions/node/v20.18.2/lib/node_modules/electron_tmp
Copying /Users/macuser/.nvm/versions/node/v20.18.2/lib/node_modules/electron_tmp/.store/electron@34.2.0/node_modules/electron to /Users/macuser/.nvm/versions/node/v20.18.2/lib/node_modules/electron
Installing electron's dependencies to /Users/macuser/.nvm/versions/node/v20.18.2/lib/node_modules/electron/node_modules
[1/3] @types/node@^20.9.0 installed at node_modules/.store/@types+node@20.17.19/node_modules/@types/node
[2/3] extract-zip@^2.0.1 installed at node_modules/.store/extract-zip@2.0.1/node_modules/extract-zip
[3/3] @electron/get@^2.0.0 installed at node_modules/.store/@electron+get@2.0.3/node_modules/@electron/get
^C
(base) 
macuser@macuserdeMac-mini /Users/macuser/repos/some_project                                                                               master
⚡ 
(base) 
macuser@macuserdeMac-mini /Users/macuser/repos/some_project                                                                               master
⚡ cnpm i electron --global
Downloading electron to /Users/macuser/.nvm/versions/node/v20.18.2/lib/node_modules/electron_tmp
Copying /Users/macuser/.nvm/versions/node/v20.18.2/lib/node_modules/electron_tmp/.store/electron@34.2.0/node_modules/electron to /Users/macuser/.nvm/versions/node/v20.18.2/lib/node_modules/electron
Installing electron's dependencies to /Users/macuser/.nvm/versions/node/v20.18.2/lib/node_modules/electron/node_modules
[1/3] extract-zip@^2.0.1 installed at node_modules/.store/extract-zip@2.0.1/node_modules/extract-zip
[2/3] @types/node@^20.9.0 installed at node_modules/.store/@types+node@20.17.19/node_modules/@types/node
[3/3] @electron/get@^2.0.0 installed at node_modules/.store/@electron+get@2.0.3/node_modules/@electron/get
deprecate @electron/get@2.0.3 › global-agent@3.0.0 › boolean@^3.0.1 Package no longer supported. Contact Support at https://www.npmjs.com/support for more info.
Recently updated (since 2025-02-12): 1 packages (detail see file /Users/macuser/.nvm/versions/node/v20.18.2/lib/node_modules/electron/node_modules/.recently_updates.txt)
  2025-02-14
    → @types/node@^20.9.0(20.17.19) (06:35:47)
Run 1 script(s) in 8s.
All packages installed (69 packages installed from npm registry, used 8s(network 210ms), speed 0B/s, json 0(0B), tarball 0B, manifests cache hit 67, etag hit 0 / miss 0)
[electron@34.2.0] link /Users/macuser/.nvm/versions/node/v20.18.2/bin/electron@ -> /Users/macuser/.nvm/versions/node/v20.18.2/lib/node_modules/electron/cli.js

(base) 
macuser@macuserdeMac-mini /Users/macuser/repos/some_project                                                                               master
⚡ cnpm i electron-rebuild  --global
Downloading electron-rebuild to /Users/macuser/.nvm/versions/node/v20.18.2/lib/node_modules/electron-rebuild_tmp
Copying /Users/macuser/.nvm/versions/node/v20.18.2/lib/node_modules/electron-rebuild_tmp/.store/electron-rebuild@3.2.9/node_modules/electron-rebuild to /Users/macuser/.nvm/versions/node/v20.18.2/lib/node_modules/electron-rebuild
Installing electron-rebuild's dependencies to /Users/macuser/.nvm/versions/node/v20.18.2/lib/node_modules/electron-rebuild/node_modules
[1/14] debug@^4.1.1 installed at node_modules/.store/debug@4.4.0/node_modules/debug
[2/14] semver@^7.3.5 installed at node_modules/.store/semver@7.7.1/node_modules/semver
[3/14] node-api-version@^0.1.4 installed at node_modules/.store/node-api-version@0.1.4/node_modules/node-api-version
[4/14] detect-libc@^2.0.1 installed at node_modules/.store/detect-libc@2.0.3/node_modules/detect-libc
[5/14] node-abi@^3.0.0 installed at node_modules/.store/node-abi@3.74.0/node_modules/node-abi
[6/14] fs-extra@^10.0.0 installed at node_modules/.store/fs-extra@10.1.0/node_modules/fs-extra
[7/14] got@^11.7.0 installed at node_modules/.store/got@11.8.6/node_modules/got
[8/14] tar@^6.0.5 installed at node_modules/.store/tar@6.2.1/node_modules/tar
[9/14] yargs@^17.0.1 installed at node_modules/.store/yargs@17.7.2/node_modules/yargs
[10/14] @malept/cross-spawn-promise@^2.0.0 installed at node_modules/.store/@malept+cross-spawn-promise@2.0.0/node_modules/@malept/cross-spawn-promise
[11/14] chalk@^4.0.0 installed at node_modules/.store/chalk@4.1.2/node_modules/chalk
[12/14] ora@^5.1.0 installed at node_modules/.store/ora@5.4.1/node_modules/ora
[13/14] node-gyp@^9.0.0 installed at node_modules/.store/node-gyp@9.4.1/node_modules/node-gyp
[14/14] lzma-native@^8.0.5 installed at node_modules/.store/lzma-native@8.0.6/node_modules/lzma-native
deprecate node-gyp@9.4.1 › npmlog@^6.0.0 This package is no longer supported.
deprecate node-gyp@9.4.1 › rimraf@^3.0.2 Rimraf versions prior to v4 are no longer supported
deprecate node-gyp@9.4.1 › glob@^7.1.4 Glob versions prior to v9 are no longer supported
deprecate node-gyp@9.4.1 › npmlog@6.0.2 › gauge@^4.0.3 This package is no longer supported.
deprecate node-gyp@9.4.1 › npmlog@6.0.2 › are-we-there-yet@^3.0.0 This package is no longer supported.
deprecate node-gyp@9.4.1 › glob@7.2.3 › inflight@^1.0.4 This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
deprecate node-gyp@9.4.1 › make-fetch-happen@10.2.1 › cacache@16.1.3 › glob@^8.0.1 Glob versions prior to v9 are no longer supported
deprecate node-gyp@9.4.1 › make-fetch-happen@10.2.1 › cacache@16.1.3 › @npmcli/move-file@^2.0.0 This functionality has been moved to @npmcli/fs
Recently updated (since 2025-02-12): 1 packages (detail see file /Users/macuser/.nvm/versions/node/v20.18.2/lib/node_modules/electron-rebuild/node_modules/.recently_updates.txt)
  2025-02-14
    → got@11.8.6 › @types/responselike@1.0.3 › @types/node@*(22.13.4) (06:35:22)
Run 1 script(s) in 680ms.
All packages installed (168 packages installed from npm registry, used 1s(network 1s), speed 4.52MB/s, json 124(947.88KB), tarball 5.47MB, manifests cache hit 39, etag hit 0 / miss 0)
[electron-rebuild@3.2.9] link /Users/macuser/.nvm/versions/node/v20.18.2/bin/electron-rebuild@ -> /Users/macuser/.nvm/versions/node/v20.18.2/lib/node_modules/electron-rebuild/lib/src/cli.js
```
</details>

```bash
macuser@macuserdeMac-mini /Users/macuser/repos/some_project                                                                               master
⚡ electron -v           
v34.2.0
```

**Comment by amrit-moomie** [comment]
> add or edit `.npmrc`
> 
> ```
> strict-ssl = false
> electron_mirror=https://cdn.npmmirror.com/binaries/electron/
> electron_builder_binaries_mirror=https://npmmirror.com/mirrors/electron-builder-binaries/
> ```

this worked for me!
