### ISSUE TITLE
Error: The specified module could not be found

### ISSUE THREAD

**Issue by ahadcove** [electron/electron#26987]
* **Electron Version:** 11.0.4
* **Operating System:** Windows
* **Last Known Working Electron version:** N/A

### Expected Behavior
When the native library is installed, electron shouldn't throw any errors

### Actual Behavior
An error was thrown when trying to load a library that contains a native module. It works on mac, just now windows.

```
Error: The specified module could not be found.
\\?\C:\Users\bk\Coding\Electron-Bug-Test\node_modules\cue-sdk-cove\build\Release\cuesdk.node
    at process.func [as dlopen] (electron/js2c/asar_bundle.js:5:1812)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1203:18)
    at Object.func [as .node] (electron/js2c/asar_bundle.js:5:1812)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12710)
    at Module.require (internal/modules/cjs/loader.js:1032:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at load (C:\Users\bk\Coding\Electron-Bug-Test\node_modules\node-gyp-build\index.js:21:10)    at Object.<anonymous> (C:\Users\bk\Coding\Electron-Bug-Test\node_modules\cue-sdk-cove\index.js:1:42)
```

### To Reproduce
On a Windows Computer:
```sh
$ git clone https://github.com/ahadcove/electron-bug-test.git
$ cd electron-bug-test
$ npm install
$ npm start
```

**Comment by nornagon** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!
