### ISSUE TITLE
Babel targets.electron bug after updating my app 7.3.3 to 11.1.0

### ISSUE THREAD

**Issue by Devilanc** [electron/electron#27087]
### Preflight Checklist

* [ v] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [ v] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [v ] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version: 11.1.0
  * 
* **Operating System: Windows 10 
  * 
* **Last Known Working Electron version: 7.3.3
  * 

### To Reproduce
After Updating my electron application to 11.1.0 (Latest),
Babel bug window is opened.

Says:

Error: [BABEL] C:\Users\Devilanc\Desktop\Dev\novaclient\app\main.dev.js: Invalid Option: 'undefined' is not a valid value for 'targets.electron'. (While processing: "C:\\Users\\Devilanc\\Desktop\\Dev\\novaclient\\babel.config.js$0")
    at semverifyTarget (C:\Users\Devilanc\Desktop\Dev\novaclient\node_modules\@babel\preset-env\lib\targets-parser.js:145:11)
    at __default (C:\Users\Devilanc\Desktop\Dev\novaclient\node_modules\@babel\preset-env\lib\targets-parser.js:151:92)
    at Object.keys.filter.sort.reduce.targets (C:\Users\Devilanc\Desktop\Dev\novaclient\node_modules\@babel\preset-env\lib\targets-parser.js:200:43)
    at Array.reduce (<anonymous>)
    at getTargets (C:\Users\Devilanc\Desktop\Dev\novaclient\node_modules\@babel\preset-env\lib\targets-parser.js:188:104)
    at C:\Users\Devilanc\Desktop\Dev\novaclient\node_modules\@babel\preset-env\lib\index.js:225:46
    at C:\Users\Devilanc\Desktop\Dev\novaclient\node_modules\@babel\helper-plugin-utils\lib\index.js:19:12
    at C:\Users\Devilanc\Desktop\Dev\novaclient\node_modules\@babel\core\lib\config\full.js:167:14
    at cachedFunction (C:\Users\Devilanc\Desktop\Dev\novaclient\node_modules\@babel\core\lib\config\caching.js:33:19)
    at loadPresetDescriptor (C:\Users\Devilanc\Desktop\Dev\novaclient\node_modules\@babel\core\lib\config\full.js:257:36)

**Comment by Kilian** [comment]
This is not an issue in Electron but rather one in Babel and does not follow our issue template or have a reproducible case, so closing this out.

If you're using babel-preset-env (which you are), you might have to update it and it's dependencies (in particular electron-to-chromium). Probably an easy fix: remove and reinstall your node_modules completely.
