### ISSUE TITLE
A dynamic link library (DLL) initialization routine failed.

### ISSUE THREAD

**Issue by HackerBoy856** [electron/electron#27134]
win 10
node v12.18.3
electron 2.0.18
The program runs normally, but I have a button, I click to call a dll file, and an error is reported the first time I click it:

ffi.Library Error: A dynamic link library (DLL) initialization routine failed.
\\?\F:\web\electron-vue-proj\node_modules\ref-napi\prebuilds\win32-x64\electron.napi.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:166:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:166:20)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at load (webpack-internal:///./node_modules/node-gyp-build/index.js:21:10)
    at Object.eval (webpack-internal:///./node_modules/ref-napi/lib/ref.js:8:111)

When clicking again without closing the program:
ffi.Library TypeError: ffi.Library is not a function
    at VueComponent.clickTest2 (Home.vue?76f2:74)
    at invokeWithErrorHandling (vue.esm.js?a026:1863)
    at VueComponent.invoker (vue.esm.js?a026:2188)
    at invokeWithErrorHandling (vue.esm.js?a026:1863)
    at VueComponent.Vue.$emit (vue.esm.js?a026:3897)
    at VueComponent.handleClick (F:\web\electron-vue-proj\node_modules\element-ui\lib\element-ui.common.js:9417)
    at invokeWithErrorHandling (vue.esm.js?a026:1863)
    at HTMLButtonElement.invoker (vue.esm.js?a026:2188)
    at HTMLButtonElement.original._wrapper (vue.esm.js?a026:7565)

How to solve it

**Comment by HackerBoy856** [comment]
@MarshallOfSound Can you help me see the problem? Thank you

**Comment by codebytere** [comment]
Closing as Electron v2 hasn't been supported for several years. Please feel free to comment again if this issue crops up on a [supported version](https://www.electronjs.org/docs/tutorial/support).
