### ISSUE TITLE
tried installing electron@11.2.1 but an error occurred

### ISSUE THREAD

**Issue by bharatsingh100** [electron/electron#27554]
Downloading electron-v11.2.1-win32-x64.zip: [===========================================================================] 100% ETA: 0.0 seconds  
Error: Generated checksum for "electron-v11.2.1-win32-x64.zip" did not match expected checksum.
    at Hash.<anonymous> (C:\Users\Angrygermankid\Desktop\NodeJS\electron-demo\node_modules\sumchecker\index.js:133:20)
    at Hash.emit (events.js:315:20)
    at emitReadable_ (_stream_readable.js:556:12)
    at onEofChunk (_stream_readable.js:534:5)
    at readableAddChunk (_stream_readable.js:251:5)
    at Hash.Readable.push (_stream_readable.js:212:10)
    at Hash.Transform.push (_stream_transform.js:152:32)
    at done (_stream_transform.js:220:17)
    at _stream_transform.js:143:7
    at Hash._flush (internal/crypto/hash.js:73:3)
npm WARN electron-demo@1.0.0 No description
npm WARN electron-demo@1.0.0 No repository field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@11.2.1 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron@11.2.1 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by ckerr** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!
