### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by pawankushwah850** [electron/electron#27568]
A JavaScript error occurred in the main process
Uncaught Exception:
ReferenceError: f is not defined
    at Object.<anonymous> (/home/kali/Documents/electron_projects/index.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
    at Module.load (internal/modules/cjs/loader.js:992:32)
    at Module._load (internal/modules/cjs/loader.js:885:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12738)
    at loadApplicationPackage (/home/kali/Documents/electron_projects/node_modules/electron/dist/resources/default_app.asar/main.js:110:16)
    at Object.<anonymous> (/home/kali/Documents/electron_projects/node_modules/electron/dist/resources/default_app.asar/main.js:222:9)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)

**Comment by ckerr** [comment]
Thanks for reporting this and helping to make Electron better!

Would it be possible for you to make a standalone testcase with only the code necessary to reproduce the issue? For example, [Electron Fiddle](https://www.electronjs.org/fiddle) is a great tool for making small test cases and makes it easy to publish your test case to a [gist](https://gist.github.com) that Electron maintainers can use.

Stand-alone test cases make fixing issues go more smoothly: it ensure everyone's looking at the same issue, it removes all unnecessary variables from the equation, and it can also provide the basis for automated regression tests.

I'm adding the `blocked/needs-repro` label for this reason. After you make a test case, please link to it in a followup comment.

Also, please provide the information that was requested by the [issue template](https://github.com/electron/electron/tree/master/.github/ISSUE_TEMPLATE) that was presented when you first filled out this issue. This is necessary because it's difficult to triage issues efficiently and correctly without enough information.


Thanks in advance! Your help is appreciated.

**Comment by kazzyagu** [comment]
having same isue - app not defined

**Comment by newcanopies** [comment]
hi @kazzyagu 

are you running on WSL2 or docker?
