### ISSUE TITLE
DCHECK in `inter_process_time_ticks_converter.cc` with tls

### ISSUE THREAD

**Issue by codebytere** [electron/electron#27717]
### Preflight Checklist

* [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
* [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
* [x] I have searched the issue tracker for an issue that matches the one I want to file, without success.

### Issue Details

* **Electron Version:** `master`
* **Operating System:** Windows 10
* **Last Known Working Electron version:** Unknown

### Expected Behavior

When using tls in the renderer process, there is no DCHECK

### Actual Behavior

When running https://gist.github.com/6f167d9eace04059a09cb36360272c21, the following DCHECK is seen:

```sh
[12112:0211/125720.288:FATAL:inter_process_time_ticks_converter.cc(57)] Check failed: remote_time_ticks <= remote_upper_bound_ (157666804000 bogo-microseconds vs. 157666803000 bogo-microseconds)    
Backtrace:
        base::debug::CollectStackTrace [0x00007FF754E9A8D2+18] (o:\base\debug\stack_trace_win.cc:303)
        base::debug::StackTrace::StackTrace [0x00007FF754DFEB52+18] (o:\base\debug\stack_trace.cc:195)
        logging::LogMessage::~LogMessage [0x00007FF754E169E8+200] 
(o:\base\logging.cc:566)
        logging::LogMessage::~LogMessage [0x00007FF754E17910+16] (o:\base\logging.cc:559)
        blink::InterProcessTimeTicksConverter::ToLocalTimeTicks [0x00007FF752BE606E+146] (o:\third_party\blink\common\loader\inter_process_time_ticks_converter.cc:58)
        content::Navigator::RecordNavigationMetrics [0x00007FF7544A4553+831] (o:\content\browser\renderer_host\navigator.cc:988)    
        content::Navigator::DidNavigate [0x00007FF7544A4157+2275] 
(o:\content\browser\renderer_host\navigator.cc:436)
        content::RenderFrameHostImpl::DidCommitNavigationInternal 
[0x00007FF7544B9550+2384] (o:\content\browser\renderer_host\render_frame_host_impl.cc:8996)
        content::RenderFrameHostImpl::DidCommitNavigation [0x00007FF7544B8896+1014] (o:\content\browser\renderer_host\render_frame_host_impl.cc:9450)
        base::internal::Invoker<base::internal::BindState<void (content::RenderFrameHostImpl::*)(content::NavigationRequest *, mojo::StructPtr<content::mojom::DidCommitProvisionalLoadParams>, mojo::StructPtr<content::mojom::DidCommitProvisionalLoadInterfaceParams 
[0x00007FF7544DD669+73] (o:\base\bind_internal.h:679)
        base::OnceCallback<void (mojo::StructPtr<content::mojom::DidCommitProvisionalLoadParams>, mojo::StructPtr<content::mojom::DidCommitProvisionalLoadInterfaceParams>)>::Run [0x00007FF752C6C146+66] (o:\base\callback.h:102)
        content::mojom::NavigationClient_CommitNavigation_ForwardToCallback::Accept [0x00007FF752C6C05F+319] (o:\fake\prefix\gen\content\common\navigation_client.mojom.cc:664)
        mojo::InterfaceEndpointClient::HandleValidatedMessage [0x00007FF75500AE43+729] (o:\mojo\public\cpp\bindings\lib\interface_endpoint_client.cc:549)
        mojo::MessageDispatcher::Accept [0x00007FF755A6CF62+226] (o:\mojo\public\cpp\bindings\lib\message_dispatcher.cc:41)
        mojo::InterfaceEndpointClient::HandleIncomingMessage [0x00007FF75500BF22+66] (o:\mojo\public\cpp\bindings\lib\interface_endpoint_client.cc:356)
        IPC::`anonymous namespace'::ChannelAssociatedGroupController::AcceptOnProxyThread [0x00007FF755AF3EE5+501] (o:\ipc\ipc_mojo_bootstrap.cc:945)
        base::internal::Invoker<base::internal::BindState<void (IPC::(anonymous namespace)::ChannelAssociatedGroupController::*)(mojo::Message),scoped_refptr<IPC::(anonymous namespace)::ChannelAssociatedGroupController>,mojo::Message>,void ()>::RunOnce [0x00007FF755AF1642+82] (o:\base\bind_internal.h:679)
        base::TaskAnnotator::RunTask [0x00007FF754E64500+448] (o:\base\task\common\task_annotator.cc:163)
        base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl [0x00007FF7559642BD+509] (o:\base\task\sequence_manager\thread_controller_with_message_pump_impl.cc:352)    
        base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork [0x00007FF755963F0E+206] (o:\base\task\sequence_manager\thread_controller_with_message_pump_impl.cc:266)        
        base::MessagePumpForUI::DoRunLoop [0x00007FF754EA3F67+247] (o:\base\message_loop\message_pump_win.cc:225)
        base::MessagePumpWin::Run [0x00007FF754EA345C+156] (o:\base\message_loop\message_pump_win.cc:82)
        base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run [0x00007FF755964CF0+368] (o:\base\task\sequence_manager\thread_controller_with_message_pump_impl.cc:463)
        base::RunLoop::Run [0x00007FF754E468F7+855] (o:\base\run_loop.cc:135)
        content::BrowserMainLoop::MainMessageLoopRun [0x00007FF7541633F8+184] (o:\content\browser\browser_main_loop.cc:1411)        
        content::BrowserMainRunnerImpl::Run [0x00007FF75416535F+143] (o:\content\browser\browser_main_runner_impl.cc:151)
        content::BrowserMain [0x00007FF7541604C0+272] (o:\content\browser\browser_main.cc:47)
        content::RunBrowserProcessMain [0x00007FF752DB8B91+93] (o:\content\app\content_main_runner_impl.cc:514)
        content::ContentMainRunnerImpl::RunBrowser [0x00007FF752DB999C+988] (o:\content\app\content_main_runner_impl.cc:994)        
        content::ContentMainRunnerImpl::Run [0x00007FF752DB9592+450] (o:\content\app\content_main_runner_impl.cc:875)
        content::RunContentProcess [0x00007FF752DB871C+1552] (o:\content\app\content_main.cc:372)
        content::ContentMain [0x00007FF752DB8806+61] (o:\content\app\content_main.cc:398)
        wWinMain [0x00007FF751B11486+874] (o:\electron\shell\app\electron_main.cc:212)
        __scrt_common_main_seh [0x00007FF759F1FD92+262] (d:\A01\_work\6\s\src\vctools\crt\vcstartup\src\startup\exe_common.inl:288) 
        BaseThreadInitThunk [0x00007FFF663F7034+20]
        RtlUserThreadStart [0x00007FFF6665D0D1+33]
Task trace:
Backtrace:
        IPC::`anonymous namespace'::ChannelAssociatedGroupController::Accept [0x00007FF755AF0DD7+1671] (o:\ipc\ipc_mojo_bootstrap.cc:896)
        mojo::SimpleWatcher::Context::Notify [0x00007FF755025456+302] (o:\mojo\public\cpp\system\simple_watcher.cc:99)

ERROR Error: Command failed: C:\Users\codebytere\Developer\electron-gn\src\out\Testing\electron.exe .
    at checkExecSyncError (child_process.js:630:11)
    at Object.execFileSync (child_process.js:648:15)
    at Command.<anonymous> (C:\Users\codebytere\.electron_build_tools\src\e:76:20)
    at Command.listener (C:\Users\codebytere\.electron_build_tools\node_modules\commander\index.js:291:8)
    at Command.emit (events.js:315:20)
    at Command.parseArgs (C:\Users\codebytere\.electron_build_tools\node_modules\commander\index.js:672:12)
    at Command.parse (C:\Users\codebytere\.electron_build_tools\node_modules\commander\index.js:459:21)
    at Object.<anonymous> (C:\Users\codebytere\.electron_build_tools\src\e:217:9)
    at Module._compile (internal/modules/cjs/loader.js:1137:30)   
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1157:10)
```

### To Reproduce

Run https://gist.github.com/6f167d9eace04059a09cb36360272c21

**Comment by codebytere** [comment]
No longer occurring as of https://github.com/electron/electron/pull/27731
