### ISSUE TITLE
Using worker_thread, an exception occurs after using Command+Q to exit the app

### ISSUE THREAD

**Issue by Vict0r-Chen** [electron/electron#27876]
### Issue Details

My code is very simple:
```
const { Worker } = require('worker_threads');
let script = `console.log('working...');`;
new Worker(script, { eval: true });
```
I can see working output in the console, but when I exit the program with command+q, I see an exception in the console: `my-electron-app/node_modules/_electron@11.3.0@electron/dist/Electron.app/Contents/MacOS/Electron exited with signal SIGSEGV`

When I run with `sudo npm start`, I also see a popup about "Electron quit unexpectedly"
* **Electron Version:**
  * 11.3.0
* **Operating System:**
  * macOS 11.2
* **Last Known Working Electron version:**
  * Don't known

### To Reproduce
$ git clone https://github.com/Vict0r-Chen/electron-worker-threads.git
$ npm install
$ npm start

### Screenshots

![image](https://user-images.githubusercontent.com/71090097/108825826-75987200-75fe-11eb-841e-7cd81e272fe0.png)

### Additional Information

```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/usr/local/bin/node',
1 verbose cli   '/usr/local/lib/node_modules/cnpm/node_modules/.bin/npm',
1 verbose cli   '--userconfig=/Users/victor/.cnpmrc',
1 verbose cli   '--disturl=https://npm.taobao.org/mirrors/node',
1 verbose cli   '--registry=https://r.npm.taobao.org',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.14.7
3 info using node@v12.18.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle my-electron-app@1.0.0~prestart: my-electron-app@1.0.0
6 info lifecycle my-electron-app@1.0.0~start: my-electron-app@1.0.0
7 verbose lifecycle my-electron-app@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle my-electron-app@1.0.0~start: PATH: /usr/local/lib/node_modules/cnpm/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/victor/Documents/Code/HJC/ElectronTest/my-electron-app/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands
9 verbose lifecycle my-electron-app@1.0.0~start: CWD: /Users/victor/Documents/Code/HJC/ElectronTest/my-electron-app
10 silly lifecycle my-electron-app@1.0.0~start: Args: [ '-c', 'electron .' ]
11 silly lifecycle my-electron-app@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle my-electron-app@1.0.0~start: Failed to exec start script
13 verbose stack Error: my-electron-app@1.0.0 start: `electron .`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/cnpm/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/cnpm/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid my-electron-app@1.0.0
15 verbose cwd /Users/victor/Documents/Code/HJC/ElectronTest/my-electron-app
16 verbose Darwin 20.3.0
17 verbose argv "/usr/local/bin/node" "/usr/local/lib/node_modules/cnpm/node_modules/.bin/npm" "--userconfig=/Users/victor/.cnpmrc" "--disturl=https://npm.taobao.org/mirrors/node" "--registry=https://r.npm.taobao.org" "start"
18 verbose node v12.18.3
19 verbose npm  v6.14.7
20 error code ELIFECYCLE
21 error errno 1
22 error my-electron-app@1.0.0 start: `electron .`
22 error Exit status 1
23 error Failed at the my-electron-app@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by codebytere** [comment]
@Vict0r-Chen this is unfortunately a function of the version of Node.js we use in `v11.x` - this is fixed in `v12.x` but we'd need to patch a fair bit of Node.js code back to fix it in `v11.x` and as such that's unlikely to happen for that line. I'm going to label this a wontfix for now and direct you to 12, which is about to be stable, but if i determine another better way to fix it i'm happy to revisit.

**Comment by Vict0r-Chen** [comment]
> @Vict0r-Chen this is unfortunately a function of the version of Node.js we use in `v11.x` - this is fixed in `v12.x` but we'd need to patch a fair bit of Node.js code back to fix it in `v11.x` and as such that's unlikely to happen for that line. I'm going to label this a wontfix for now and direct you to 12, which is about to be stable, but if i determine another better way to fix it i'm happy to revisit.

@codebytere Thanks for the reply.
In fact, the node I used is v12.18.3, and I tried to switch to node v11,15,0 and v14.16.0 and got the same result, so how should I avoid this problem? thanks again.

**Comment by codebytere** [comment]
@Vict0r-Chen i'm referring to Electron `v12.x`, not Node.js `v12.x` :)

**Comment by Vict0r-Chen** [comment]
@codebytere After I upgraded to `electron 12.0.0-beta.30`, the above script can be executed as expected, and there is no prompt when I exit the application with `cmd+q`, but when I use `ffi-napi` in `worker_thread`, everything becomes Strange:
```
let script = `
    console.log('working...');
    const ffi = require("ffi-napi");
    console.log('done');
`;
new Worker(script, { eval: true });
```
For the above code, 'working...' and 'done' will output as expected, but when the code is executed, the application will automatically exit and output the following error:
```
working...
work finished
/Users/victor/Documents/my-electron-app/node_modules/_electron@12.0.0-beta.30@electron/dist/Electron.app/Contents/MacOS/Electron exited with signal SIGSEGV
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-electron-app@1.0.0 start: `electron .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the my-electron-app@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/victor/.npm/_logs/2021-03-01T09_47_59_880Z-debug.log
```
2021-03-01T09_47_59_880Z-debug.log:
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'start' ]
2 info using npm@6.14.6
3 info using node@v12.18.3
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle my-electron-app@1.0.0~prestart: my-electron-app@1.0.0
6 info lifecycle my-electron-app@1.0.0~start: my-electron-app@1.0.0
7 verbose lifecycle my-electron-app@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle my-electron-app@1.0.0~start: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/victor/Documents/Code/my-electron-app/node_modules/.bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Apple/usr/bin:/Library/Frameworks/Mono.framework/Versions/Current/Commands
9 verbose lifecycle my-electron-app@1.0.0~start: CWD: /Users/victor/Documents/my-electron-app
10 silly lifecycle my-electron-app@1.0.0~start: Args: [ '-c', 'electron .' ]
11 silly lifecycle my-electron-app@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle my-electron-app@1.0.0~start: Failed to exec start script
13 verbose stack Error: my-electron-app@1.0.0 start: `electron .`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid my-electron-app@1.0.0
15 verbose cwd /Users/victor/Documents/my-electron-app
16 verbose Darwin 20.3.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "start"
18 verbose node v12.18.3
19 verbose npm  v6.14.6
20 error code ELIFECYCLE
21 error errno 1
22 error my-electron-app@1.0.0 start: `electron .`
22 error Exit status 1
23 error Failed at the my-electron-app@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```
