### ISSUE TITLE
npm install issue

### ISSUE THREAD

**Issue by CraftedCat** [electron/electron#27908]
### Issue Details

* **Electron Version:**
electron-forge@5.2.4
* **Operating System:**
Название ОС:                      Майкрософт Windows 10 Pro
Версия ОС:                        10.0.19041 Н/Д построение 19041

165 verbose stack SyntaxError: Unexpected end of JSON input while parsing near '...jZtcQ==","shasum":"c1'
165 verbose stack     at JSON.parse (<anonymous>)
165 verbose stack     at parseJson (C:\Users\cat\AppData\Roaming\npm\node_modules\npm\node_modules\json-parse-better-errors\index.js:7:17)
165 verbose stack     at C:\Users\cat\AppData\Roaming\npm\node_modules\npm\node_modules\node-fetch-npm\src\body.js:96:50
165 verbose stack     at processTicksAndRejections (internal/process/task_queues.js:97:5)
166 verbose cwd C:\Users\cat
167 verbose Windows_NT 10.0.19041
168 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\cat\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "electron-forge"
169 verbose node v12.18.3
170 verbose npm  v6.14.8
171 error Unexpected end of JSON input while parsing near '...jZtcQ==","shasum":"c1'
172 verbose exit [ 1, true ]

**Comment by CraftedCat** [comment]
founded in docs
