### ISSUE TITLE
[Bug]: Compile failure

### ISSUE THREAD

**Issue by amyipdev** [electron/electron#28184]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

9-master

### What operating system are you using?

Other Linux

### Operating System Version

Arch Linux

### What arch are you using?

x64

### Last Known Working Electron version

9.4.3-1

### Expected Behavior

It should compile correctly.

### Actual Behavior

It fails to compile with the error:
```py
FAILED: gen/components/payments/mojom/payment_request_data.mojom-blink-forward.h gen/components/payments/mojom/payment_request_data.mojom-blink-import-headers.h gen/components/payments/mojom/payment_request_data.mojom-blink-test-utils.cc gen/components/payments/mojom/payment_request_data.mojom-blink-test-utils.h gen/components/payments/mojom/payment_request_data.mojom-blink.cc gen/components/payments/mojom/payment_request_data.mojom-blink.h 
python ../../mojo/public/tools/bindings/mojom_bindings_generator.py --use_bundled_pylibs -o gen generate -d ../../ -I ../../ --bytecode_path gen/mojo/public/tools/bindings --filelist=__components_payments_mojom_mojom_blink__generator___build_toolchain_linux_unbundle_default__rule..rsp -g c++ --variant blink --typemap gen/components/payments/mojom/mojom_blink__type_mappings --for_blink --scrambled_message_id_salt_path ../../chrome/VERSION
Traceback (most recent call last):
  File "/home/amy/.cache/paru/clone/electron9/src/src/out/Release/../../mojo/public/tools/bindings/mojom_bindings_generator.py", line 449, in <module>
    sys.exit(main())
  File "/home/amy/.cache/paru/clone/electron9/src/src/out/Release/../../mojo/public/tools/bindings/mojom_bindings_generator.py", line 444, in main
    return args.func(args, remaining_args)
  File "/home/amy/.cache/paru/clone/electron9/src/src/out/Release/../../mojo/public/tools/bindings/mojom_bindings_generator.py", line 243, in _Generate
    processor._GenerateModule(
  File "/home/amy/.cache/paru/clone/electron9/src/src/out/Release/../../mojo/public/tools/bindings/mojom_bindings_generator.py", line 212, in _GenerateModule
    generator.GenerateFiles(filtered_args)
  File "/home/amy/.cache/paru/clone/electron9/src/src/mojo/public/tools/bindings/generators/mojom_cpp_generator.py", line 541, in GenerateFiles
    self.WriteWithComment(self._GenerateModuleHeader(),
  File "/home/amy/.cache/paru/clone/electron9/src/src/mojo/public/tools/mojom/mojom/generate/template_expander.py", line 35, in GeneratorInternal
    return ApplyTemplate(args[0], path_to_template, parameters, **kwargs)
  File "/home/amy/.cache/paru/clone/electron9/src/src/mojo/public/tools/mojom/mojom/generate/template_expander.py", line 28, in ApplyTemplate
    return template.render(params)
  File "/home/amy/.cache/paru/clone/electron9/src/src/third_party/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/amy/.cache/paru/clone/electron9/src/src/third_party/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/amy/.cache/paru/clone/electron9/src/src/third_party/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/amy/.cache/paru/clone/electron9/src/src/third_party/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "gen/mojo/public/tools/bindings/cpp_templates.zip/tmpl_4b4c750a11f14c4ee990ca69a07408825b11d62d.py", line 179, in <module>
  File "gen/mojo/public/tools/bindings/cpp_templates.zip/tmpl_3cfd1c143e820f5d5f5c850420142fd64dfa3890.py", line 39, in <module>
  File "/home/amy/.cache/paru/clone/electron9/src/src/third_party/jinja2/runtime.py", line 478, in __next__
    ctx._after = ctx._safe_next()
  File "/home/amy/.cache/paru/clone/electron9/src/src/third_party/jinja2/runtime.py", line 455, in _safe_next
    return next(self._iterator)
  File "/home/amy/.cache/paru/clone/electron9/src/src/mojo/public/tools/bindings/generators/mojom_cpp_generator.py", line 940, in <genexpr>
    return (StructConstructor(struct.fields, ordinal_fields[:param_count])
  File "/home/amy/.cache/paru/clone/electron9/src/src/mojo/public/tools/bindings/generators/mojom_cpp_generator.py", line 203, in __init__
    self._params = set(params)
TypeError: unhashable type: 'StructField'
[2000/32588] ACTION //net/base/registry_controlled_domains:registry_controlled_domains(//build/toolchain/linux/unbundle:default)
ninja: build stopped: subcommand failed.
==> ERROR: A failure occurred in build().
```

Using the AUR PKGBUILD.

**Comment by nornagon** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electron) a try.

I hope this helps!
