### ISSUE TITLE
[Bug]: Electron not compatible with latest selenium-webdriver

### ISSUE THREAD

**Issue by kr3l** [electron/electron#28197]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

10.1.3

### What operating system are you using?

Windows

### Operating System Version

Windows 10.0.19042 Build 19042

### What arch are you using?

x64

### Expected Behavior

Should start electron.

This is the same issue as https://github.com/electron/electron/issues/22408, which was closed because it happened on an unsupported electron version. 

### Actual Behavior

Fails with (node:20272) UnhandledPromiseRejectionWarning: SessionNotCreatedError: session not created: No matching capabilities found

To reproduce, follow the instructions https://www.electronjs.org/docs/tutorial/using-selenium-and-webdriver under 'Setting up with WebDriverJS'. The instructions work for selenium-webdriver 3.4.0, but no longer work for more recent versions of selenium-webdriver, like selenium-webdriver 4.0.0-beta.1.

I used the following test file:

```
const webdriver = require('selenium-webdriver');
const ChildProcess = require('child_process');
const chromedriver = require('chromedriver');

const chromedriverProcess = ChildProcess.spawn(
    chromedriver.path, // process path goes here
    [], // arguments go here
    {
        stdio: 'inherit'
    }
);
const electronBinary = 'MyElectronBinary.exe';
const driver = new webdriver.Builder()
    // The "9515" is the port opened by chrome driver.
    .usingServer('http://localhost:9515')
    .withCapabilities({
        chromeOptions: {
            // Here is the path to your Electron binary.
            binary: electronBinary
        }
    })
    .forBrowser('electron')
    .build();

driver.get('http://www.google.com');
driver.findElement(webdriver.By.name('q')).sendKeys('webdriver');
driver.findElement(webdriver.By.name('btnG')).click();
driver.wait(() => {
    return driver.getTitle().then((title) => {
        return title === 'webdriver - Google Search';
    });
}, 1000);

driver.quit();
```

which fails to start electron from the test and results in this error:

```
"C:\Program Files\nodejs\node.exe" test.js
Debugger listening on ws://127.0.0.1:59483/3a02c408-6f58-4570-9706-b52a5bf931f6
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
Starting ChromeDriver 85.0.4183.38 (9047dbc2c693f044042bbec5c91401c708c7c26a-refs/branch-heads/4183@{#779}) on port 9515
Only local connections are allowed.
Please see https://chromedriver.chromium.org/security-considerations for suggestions on keeping ChromeDriver safe.
ChromeDriver was started successfully.
(node:20272) UnhandledPromiseRejectionWarning: SessionNotCreatedError: session not created: No matching capabilities found
    at Object.throwDecodedError (C:\Downloads\MyCode\node_modules\selenium-webdriver\lib\error.js:517:15)
    at parseHttpResponse (C:\Downloads\MyCode\node_modules\selenium-webdriver\lib\http.js:671:13)
    at Executor.execute (C:\Downloads\MyCode\node_modules\selenium-webdriver\lib\http.js:597:28)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:20272) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch
(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:20272) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
(node:20272) UnhandledPromiseRejectionWarning: SessionNotCreatedError: session not created: No matching capabilities found
    at Object.throwDecodedError (C:\Downloads\MyCode\node_modules\selenium-webdriver\lib\error.js:517:15)
    at parseHttpResponse (C:\Downloads\MyCode\node_modules\selenium-webdriver\lib\http.js:671:13)
    at Executor.execute (C:\Downloads\MyCode\node_modules\selenium-webdriver\lib\http.js:597:28)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:20272) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch
(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:20272) UnhandledPromiseRejectionWarning: SessionNotCreatedError: session not created: No matching capabilities found
    at Object.throwDecodedError (C:\Downloads\MyCode\node_modules\selenium-webdriver\lib\error.js:517:15)
    at parseHttpResponse (C:\Downloads\MyCode\node_modules\selenium-webdriver\lib\http.js:671:13)
    at Executor.execute (C:\Downloads\MyCode\node_modules\selenium-webdriver\lib\http.js:597:28)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:20272) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch
(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
(node:20272) UnhandledPromiseRejectionWarning: SessionNotCreatedError: session not created: No matching capabilities found
    at Object.throwDecodedError (C:\Downloads\MyCode\node_modules\selenium-webdriver\lib\error.js:517:15)
    at parseHttpResponse (C:\Downloads\MyCode\node_modules\selenium-webdriver\lib\http.js:671:13)
    at Executor.execute (C:\Downloads\MyCode\node_modules\selenium-webdriver\lib\http.js:597:28)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:20272) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch
(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 5)
(node:20272) UnhandledPromiseRejectionWarning: SessionNotCreatedError: session not created: No matching capabilities found
    at Object.throwDecodedError (C:\Downloads\MyCode\node_modules\selenium-webdriver\lib\error.js:517:15)
    at parseHttpResponse (C:\Downloads\MyCode\node_modules\selenium-webdriver\lib\http.js:671:13)
    at Executor.execute (C:\Downloads\MyCode\node_modules\selenium-webdriver\lib\http.js:597:28)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:20272) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch
(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 6)
(node:20272) UnhandledPromiseRejectionWarning: SessionNotCreatedError: session not created: No matching capabilities found
    at Object.throwDecodedError (C:\Downloads\MyCode\node_modules\selenium-webdriver\lib\error.js:517:15)
    at parseHttpResponse (C:\Downloads\MyCode\node_modules\selenium-webdriver\lib\http.js:671:13)
    at Executor.execute (C:\Downloads\MyCode\node_modules\selenium-webdriver\lib\http.js:597:28)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:20272) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch
(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 7)
```

Any help on this is appreciated.

**Comment by kr3l** [comment]
We got this working by making the following two changes to the snippet:

```
const driver = new webdriver.Builder()
    .usingServer('http://localhost:9515')
    .withCapabilities({
        'goog:chromeOptions': {  // CHANGED FROM chromeOptions TO goog:chromeOptions
            binary: electronBinary
        }
    })
    .forBrowser('chrome') // CHANGED FROM 'electron' to 'chrome'
    .build();
```

(see https://github.com/SeleniumHQ/selenium/issues/9286)

Not sure if the 'old' options should still work or not, or if the documentation at https://www.electronjs.org/docs/tutorial/using-selenium-and-webdriver should be updated to reflect these required changes.

**Comment by nornagon** [comment]
@kr3l nice sleuthing! Do you want to try your hand at making a PR to update those docs? https://github.com/electron/electron/edit/master/docs/tutorial/using-selenium-and-webdriver.md

**Comment by kr3l** [comment]
All sleuthing was done by @diemol! The proposed docs change is in #28231
