### ISSUE TITLE
[Bug]: electron exited with signal SIGSEGV on sample project

### ISSUE THREAD

**Issue by cjbarth** [electron/electron#28778]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

^12.0.5

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 20.04 on WSL 2

### What arch are you using?

x64

### Expected Behavior

The demo app would launch.

I used the sample from the README:

```shell
git clone https://github.com/electron/electron-quick-start
cd electron-quick-start
npm install
npm start
```

I was getting the error about a missing `libnss3.so` on a different project, but corrected that by following this: https://stackoverflow.com/a/65107381/271351. I then started getting this `SIGSEGV` on that project, so I tried this demo project as a minimal repro, and still got the problem.

I also did an `apt update` and and `apt upgrade` before this.

### Actual Behavior

```shell
/home/cjbarth/code/electron-quick-start/node_modules/electron/dist/electron exited with signal SIGSEGV
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-quick-start@1.0.0 start: `electron .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-quick-start@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/cjbarth/.npm/_logs/2021-04-22T13_38_52_211Z-debug.log
```

```shell
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'start' ]
2 info using npm@6.14.4
3 info using node@v10.19.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle electron-quick-start@1.0.0~prestart: electron-quick-start@1.0.0
6 info lifecycle electron-quick-start@1.0.0~start: electron-quick-start@1.0.0
7 verbose lifecycle electron-quick-start@1.0.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle electron-quick-start@1.0.0~start: PATH: /usr/share/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/cjbarth/code/electron-quick-start/node_modules/.bin:/home/cjbarth/bin:/home/cjbarth/.local/bin:/usr/bin:/home/cjbarth/.cargo/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/mnt/c/Program Files/WindowsApps/Microsoft.WindowsTerminal_1.7.1033.0_x64__8wekyb3d8bbwe:/mnt/c/Program Files/ImageMagick-7.0.11-Q16-HDRI:/mnt/c/Program Files (x86)/Common Files/Intel/Shared Files/cpp/bin/Intel64:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program Files (x86)/ChinaScribe:/mnt/c/Program Files (x86)/Plantronics/Spokes3G/:/mnt/c/Program Files (x86)/NVIDIA Corporation/PhysX/Common:/mnt/c/Program Files/NVIDIA Corporation/NVIDIA NvDLISR:/mnt/c/Program Files/dotnet/:/mnt/c/Program Files/Git/cmd:/mnt/c/Program Files (x86)/Smart Projects/IsoBuster:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program Files/Microsoft SQL Server/130/Tools/Binn/:/mnt/c/Program Files/Microsoft SQL Server/Client SDK/ODBC/170/Tools/Binn/:/mnt/c/Program Files (x86)/dotnet/:/mnt/c/Program Files/Docker/Docker/resources/bin:/mnt/c/ProgramData/DockerDesktop/version-bin:/mnt/c/Users/chris/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/chris/AppData/Local/Programs/Microsoft VS Code/bin:/mnt/c/Users/chris/AppData/Local/GitHubDesktop/bin:/mnt/c/Users/chris/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/chris/.dotnet/tools:/mnt/c/Users/chris/AppData/Local/gitkraken/bin:/mnt/c/Users/chris/.dotnet/tools:/snap/bin:~/code/pico-sdk
9 verbose lifecycle electron-quick-start@1.0.0~start: CWD: /home/cjbarth/code/electron-quick-start
10 silly lifecycle electron-quick-start@1.0.0~start: Args: [ '-c', 'electron .' ]
11 silly lifecycle electron-quick-start@1.0.0~start: Returned: code: 1  signal: null
12 info lifecycle electron-quick-start@1.0.0~start: Failed to exec start script
13 verbose stack Error: electron-quick-start@1.0.0 start: `electron .`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:198:13)
13 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:198:13)
13 verbose stack     at maybeClose (internal/child_process.js:982:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
14 verbose pkgid electron-quick-start@1.0.0
15 verbose cwd /home/cjbarth/code/electron-quick-start
16 verbose Linux 5.4.72-microsoft-standard-WSL2
17 verbose argv "/usr/bin/node" "/usr/bin/npm" "start"
18 verbose node v10.19.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error electron-quick-start@1.0.0 start: `electron .`
22 error Exit status 1
23 error Failed at the electron-quick-start@1.0.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by MarshallOfSound** [comment]
> Ubuntu 20.04 on WSL 2

Electron does not support being run under a vanilla WSL environment, it will attempt to download and launch the Linux app and that will not work as there is no linux desktop environment.  Either configure `xvfb` or launch the app from cmd/powershell instead.
