### ISSUE TITLE
can't set process.env.NODE_ENV value (node catches error)

### ISSUE THREAD

**Issue by cyberlobster** [electron/electron#28908]
when I am trying to set process.env.NODE_ENV value to development and run the program I encounter an error
I am using wsl and Xserver (also used vue electron builder for the project)
this is the error:

```
App threw an error during load
SyntaxError: Invalid left-hand side in assignment
    at Object../src/background.js (/home/cyberlobster/projects/libeleli/dist_electron/index.js:1780:1)
    at __webpack_require__ (/home/cyberlobster/projects/libeleli/dist_electron/index.js:20:30)
    at eval (webpack:///multi_./src/background.js?:1:18)
    at Object.0 (/home/cyberlobster/projects/libeleli/dist_electron/index.js:1791:1)
    at __webpack_require__ (/home/cyberlobster/projects/libeleli/dist_electron/index.js:20:30)
    at /home/cyberlobster/projects/libeleli/dist_electron/index.js:84:18
    at Object.<anonymous> (/home/cyberlobster/projects/libeleli/dist_electron/index.js:87:10)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
    at Module.load (internal/modules/cjs/loader.js:992:32)
A JavaScript error occurred in the main process
Uncaught Exception:
SyntaxError: Invalid left-hand side in assignment
    at Object../src/background.js (/home/cyberlobster/projects/libeleli/dist_electron/index.js:1780:1)
    at __webpack_require__ (/home/cyberlobster/projects/libeleli/dist_electron/index.js:20:30)
    at eval (webpack:///multi_./src/background.js?:1:18)
    at Object.0 (/home/cyberlobster/projects/libeleli/dist_electron/index.js:1791:1)
    at __webpack_require__ (/home/cyberlobster/projects/libeleli/dist_electron/index.js:20:30)
    at /home/cyberlobster/projects/libeleli/dist_electron/index.js:84:18
    at Object.<anonymous> (/home/cyberlobster/projects/libeleli/dist_electron/index.js:87:10)
    at Module._compile (internal/modules/cjs/loader.js:1152:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1173:10)
    at Module.load (internal/modules/cjs/loader.js:992:32)
```

**Comment by mlaurencin** [comment]
Thanks for reaching out!

Please provide the information that was requested by the [issue template](https://github.com/electron/electron/tree/master/.github/ISSUE_TEMPLATE) that was presented when you first filled out this issue. This is necessary because it's difficult to triage issues efficiently and correctly without enough information.

Thanks for understanding and meeting us half way :grinning:

**Comment by MarshallOfSound** [comment]
This is a bug in your build system, not in Electron itself.  You are using webpack which will automatically override `process.env.NODE_ENV` with a string as part of the build process.

i.e. this code

```js
process.env.NODE_ENV = 'foo';
```

Will be replaced with

```js
'development' = 'foo';
```

Hence the error "invalid left-hand side in assignment", because the resultant code is trying to assign a string to a string which is invalid.  You will need to turn off or bypass webpacks process.env.NODE_ENV replacement logic
