### ISSUE TITLE
Cannot start composer after Installing Latest version

### ISSUE THREAD

**Issue by UmaPrelude** [electron/electron#29083]
Hi,
I was using 1.3.1 desktop version in my machine after updating to 1.4.1, I am not able to run composer successfully, it stops in the loading screen itself.
After referring to Issue : https://github.com/microsoft/BotFramework-Composer/issues/5073

I ran from command prompt and seeing the below errors, please recommend the solution for this issue.

"(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For
 more information please check https://github.com/electron/electron/issues/18397
(node:7488) UnhandledPromiseRejectionWarning: Error: The specified module could not be found.
\\?\D:\Composer\InstallLocation\Bot Framework Composer\resources\app.asar.unpacked\node_modules\orchestrator-core\orchestrator-core.node
    at process.func (electron/js2c/asar.js:140:31)
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1016:18)
    at Object.func (electron/js2c/asar.js:140:31)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:816:32)
    at Module._load (internal/modules/cjs/loader.js:728:14)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:853:19)
(node:7488) UnhandledPromiseRejectionWarning: Error: The specified module could not be found.
\\?\D:\Composer\InstallLocation\Bot Framework Composer\resources\app.asar.unpacked\node_modules\orchestrator-core\orchestrator-core.node
    at process.func (electron/js2c/asar.js:140:31)
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1016:18)
    at Object.func (electron/js2c/asar.js:140:31)
    at Object.func [as .node] (electron/js2c/asar.js:149:18)
    at Module.load (internal/modules/cjs/loader.js:816:32)
    at Module._load (internal/modules/cjs/loader.js:728:14)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:853:19)
(node:7488) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function withou
t a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7488) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function withou
t a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:7488) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will ter
minate the Node.js process with a non-zero exit code.
(node:7488) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will ter
minate the Node.js process with a non-zero exit code."

Also immediately after installing new version i got this error as well.

![image](https://user-images.githubusercontent.com/65938026/117654953-11745b80-b1b4-11eb-9e6b-a5ca5402752d.png)

**Comment by UmaPrelude** [comment]
Sorry i will post it to composer team.
