### ISSUE TITLE
Error in electronic-builder

### ISSUE THREAD

**Issue by siylau** [electron/electron#29641]
OKAY  take it away `electron-builder`

TypeError: Cannot read property 'name' of undefined
    at exports.fromCallback (/Users/xxxx/Downloads/electron-vue-elementui-demo-master/node_modules/temp-file/node_modules/universalify/index.js:15:26)
    at Object.<anonymous> (/Users/xxxx/Downloads/electron-vue-elementui-demo-master/node_modules/temp-file/node_modules/fs-extra/lib/fs/index.js:57:27)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Users/xxxx/Downloads/electron-vue-elementui-demo-master/node_modules/temp-file/node_modules/fs-extra/lib/index.js:5:6)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-project@0.0.1 build: `node .electron-vue/build.js && electron-builder`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the my-project@0.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/xxx/.npm/_logs/2021-06-11T06_24_29_881Z-debug.log

**Comment by codebytere** [comment]
Please open this issue on [`electron-builder`](https://github.com/electron-userland/electron-builder). This team does not maintain it.

**Comment by zhoumh1988** [comment]
Did you fixed it? I have the same bug. I just run electron. Not build the project.
![image](https://user-images.githubusercontent.com/7434920/155254672-a7340f40-4ceb-40c8-843b-29a105bc0d04.png)

**Comment by zhoumh1988** [comment]
> 
Log4js resolution to 6.3.0.

"log4js": "^6.3.0", -> "log4js": "6.3.0",

**Comment by zhoumh1988** [comment]
> 

是的，就是log4j自动升级导致的，降级处理固定版本号就好。
