### ISSUE TITLE
[Bug]: yarn dev is not working after update electron 9 to 10

### ISSUE THREAD

**Issue by Devilanc** [electron/electron#30534]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

10.4.7

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Dev Build

### What arch are you using?

ia32

### Last Known Working Electron version

9.4.4

### Expected Behavior

yarn dev is not working after upgrade to electron 9.4.4 > 10.4.7

### Actual Behavior

it's also not working at electron 11,12,13.

yarn start is working at every version.

log says

App threw an error during load
Error: ENOENT: no such file or directory, open 'electron'
    at Object.openSync (fs.js:476:3)
    at Object.func [as openSync] (electron/js2c/asar_bundle.js:5:1846)
    at Object.readFileSync (fs.js:377:35)
    at Object.e.readFileSync (electron/js2c/asar_bundle.js:5:8872)
    at Module._extensions..js (internal/modules/cjs/loader.js:1106:18)
    at Object.newLoader [as .js] (C:\Users\Kim\Desktop\Dev\novaclient\node_modules\pirates\lib\index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)

how can i solve this issue?

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
