### ISSUE TITLE
[Bug]: Crypto SHA3-xxx not implemented?

### ISSUE THREAD

**Issue by Levminer** [electron/electron#30530]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.1.9

### What operating system are you using?

Windows

### Operating System Version

Windows 11 Pro 21H2 22000.132

### What arch are you using?

x64

### Expected Behavior

```js
const generateHash = (data) => {
		const hashed = crypto.createHash("sha3-512").update(data).digest("base64")

		return hashed
	},

console.log(generateHash("test")) // ns4IbpusSR+sXB0QRsoR1ze5KisuvZPwBde3EBEMCmeCiBZuf755aIOk8umzyp9IT1IdDORkNFzBrslneRScFA==
```

### Actual Behavior

App threw an error during load
Error: Digest method not supported
    at new Hash (internal/crypto/hash.js:46:19)
    at Object.createHash (crypto.js:115:10)
    at generateHash (C:\Code\GitHub\authme\lib\sha.js:10:25)
    at Object.<anonymous> (C:\Code\GitHub\authme\lib\main.js:21:13)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12913)
    at Module.require (internal/modules/cjs/loader.js:959:19)

### Additional Information

If using sha-xxx it works but with sha3-xxx it's dosen't works.

**Comment by nornagon** [comment]
BoringSSL does not have a SHA-3 implementation, so this is beyond our ability to implement at present. See https://www.imperialviolet.org/2017/05/31/skipsha3.html and https://github.com/w3c/webappsec-subresource-integrity/issues/11 for some somewhat related background.

Closing this as WONTFIX for now, if BoringSSL does add an implementation we should consider exposing it.
