### ISSUE TITLE
[Bug]: FATAL:platform_shared_memory_region_posix.cc(255) fixed by --disable-seccomp-filter-sandbox

### ISSUE THREAD

**Issue by powerman** [electron/electron#30758]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.2.1

### What operating system are you using?

Other Linux

### Operating System Version

Gentoo

### What arch are you using?

x64

### Expected Behavior

Slack 4.13.0-4.19.2 (based on Electron 11.2.3-13.2.1) should show it's main window and won't print this error on start:
```
[327241:0827/214511.475208:FATAL:platform_shared_memory_region_posix.cc(255)] This is frequently caused by incorrect permissions on /dev/shm. Try 'sudo chmod 1777 /dev/shm' to fix.
```

### Actual Behavior

Slack 4.13.0-4.19.2 prints mentioned above error message and I see only tray icon, no main window.

### Additional Information

Last version of Slack which works on my system is 4.12.2, because next versions added this call:
```js
external_electron_.app.enableSandbox()
```
Removing this call makes these versions to work.
Also these versions works if started with `--disable-seccomp-filter-sandbox`.

There are two issues here:

1. Unhelpful and misleading error message. It talks about "This is frequently caused by incorrect permissions on /dev/shm. Try 'sudo chmod 1777 /dev/shm' to fix." but my `/dev/shm` already have 1777 perms and 16GB of free space, so this issue isn't related to `/dev/shm` at all.
2. Broken sandbox support. (Installing /opt/slack/chrome-sandbox SUID doesn't make any changes.) I doubt it's because of my kernel/OS configuration because Chrome 92.0.4515.159 has full sandbox support:

![chrome-sandbox](https://user-images.githubusercontent.com/1354301/131377865-f42153a3-4ec2-4a43-89d7-e9393d492ae2.png)

**Comment by VerteDinde** [comment]
Hey @powerman, thanks for reporting this issue! 

Out of curiosity, does the default Electron demo app also exhibit this issue? You can install that app here: https://github.com/electron/electron-quick-start You'll need to manually set `setuid` via `sudo chown root chrome-sandbox && chmod 4755 chrome-sandbox`, but this should give us a better idea of if the issue is general to Electron or more Slack-specific. Once you try that out, could you let me know here and we can try next steps? 🙂 

Thanks so much!

**Comment by powerman** [comment]
At a glance - quick-start works just fine (window opens, I see app versions, quit using menu), here is console output:
```
$ npm start

> electron-quick-start@1.0.0 start /home/powerman/tmp/electron-quick-start
> electron .

(node:12081) electron: The default of nativeWindowOpen is deprecated and will be changing from false to true in Electron 15.  See https://github.com/electron/electron/issues/28511 for more information.
(Use `electron --trace-warnings ...` to show where the warning was created)
[12113:0909/222646.600921:ERROR:vaapi_wrapper.cc(1073)] vaQuerySurfaceAttributes failed, VA error: invalid parameter
[12113:0909/222646.600974:ERROR:vaapi_wrapper.cc(1020)] FillProfileInfo_Locked failed for va_profile VAProfileH264Main and entrypoint VAEntrypointVLD
[12113:0909/222646.601001:ERROR:vaapi_wrapper.cc(1073)] vaQuerySurfaceAttributes failed, VA error: invalid parameter
[12113:0909/222646.601021:ERROR:vaapi_wrapper.cc(1020)] FillProfileInfo_Locked failed for va_profile VAProfileH264High and entrypoint VAEntrypointVLD
```

**Comment by powerman** [comment]
But I didn't see enableSandbox call in quick-start, if it's not enabled then there is no surprise it works.

**Comment by powerman** [comment]
I've tried to add `app.enableSandbox()` at the end of the main.js, but this doesn't break anything.

**Comment by powerman** [comment]
Current slack-4.27.156 still doesn't work without `--disable-seccomp-filter-sandbox`.

**Comment by powerman** [comment]
Current slack-4.28.182 still doesn't work without `--disable-seccomp-filter-sandbox`:

```
$ slack
[30844:0110/064351.005143:FATAL:setuid_sandbox_host.cc(157)] The SUID sandbox helper binary was found, but is not configured correctly. Rather than run without sandboxing I'm aborting now. You need to make sure that /opt/slack/chrome-sandbox is owned by root and has mode 4755.
[1]    30844 trace trap  /usr/bin/slack
[30846:0100/000000.029900:ERROR:zygote_linux.cc(650)] write: Broken pipe (32)                       
```

Playing with `/opt/slack/chrome-sandbox` permissions doesn't helps - yes, current are `0755`, but changing to `4755` result in same effect as running with `--no-sandbox`: it doesn't crash but also doesn't show main window - there are only working icon in system tray and errors in console:

```
$ slack --no-sandbox
Initializing local storage instance
(electron) Sending uncompressed crash reports is deprecated and will be removed in a future version of Electron. Set { compress: true } to opt-in to the new behavior. Crash reports will be uploaded gzipped, which most crash reporting servers support.
[01/10/23, 06:45:39:874] info: 
╔═══════════════════════════════════════════════════════╗
║      Slack 4.28.182, linux 5.15.80-gentoo on x64      ║
╚═══════════════════════════════════════════════════════╝ 
[01/10/23, 06:45:39:875] info: Configured logger via 
{
  "enableConsoleTransport": true,
  "identifierOverride": "webapp-service-worker-console",
  "shouldUseNewBackend": false,
  "loggerInstanceCount": 2
}
[01/10/23, 06:45:39:875] info: Predefined values for process 
{
  "NODE_ENV": "production",
  "platform": "linux",
  "type": "browser",
  "timeZone": "Europe/Kiev",
  "PACKAGE_MANIFEST.productName": "Slack",
  "PACKAGE_MANIFEST.version": "4.28.182",
  "PACKAGE_MANIFEST.commit": "84613b9",
  "PACKAGE_MANIFEST.branch": "HEAD"
}
[31777:0110/064539.883126:ERROR:browser_main_loop.cc(270)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[31777:0110/064539.883483:ERROR:browser_main_loop.cc(270)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[31777:0110/064539.884452:ERROR:browser_main_loop.cc(270)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[31777:0110/064539.884625:ERROR:browser_main_loop.cc(270)] Gtk: gtk_widget_add_accelerator: assertion 'GTK_IS_ACCEL_GROUP (accel_group)' failed
[01/10/23, 06:45:40:066] info: Boots up new service worker version 
{
  "scriptUrl": "https://app.slack.com/service-worker.js?force_cold_boot=1",
  "scope": "https://app.slack.com/",
  "renderProcessId": 4,
  "versionId": 514
}
[01/10/23, 06:45:40:067] info: Jan-10 06:45:40.660 [SERVICE-WORKER] normalizing request URL for cache https://app.slack.com/client/TK74QTXGV 
{
  "versionId": 514
}
[01/10/23, 06:45:40:069] info: Jan-10 06:45:40.670 [SERVICE-WORKER] responding from cache (normalized) /boot/client.html 
{
  "versionId": 514
}
[31859:0110/064540.180644:ERROR:platform_shared_memory_region_posix.cc(217)] Creating shared memory in /dev/shm/.org.chromium.Chromium.8YbGZ9 failed: Operation not permitted (1)
[31859:0110/064540.180726:ERROR:platform_shared_memory_region_posix.cc(220)] Unable to access(W_OK|X_OK) /dev/shm: Operation not permitted (1)
[31859:0110/064540.180751:FATAL:platform_shared_memory_region_posix.cc(222)] This is frequently caused by incorrect permissions on /dev/shm.  Try 'sudo chmod 1777 /dev/shm' to fix.
Renderer process crashed - see https://www.electronjs.org/docs/tutorial/application-debugging for potential debugging information.
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at n.send (node:electron/js2c/browser_init:165:417)
    at b.send (node:electron/js2c/browser_init:161:2494)
    at /opt/slack/resources/app.asar/dist/main.bundle.js:262:6544
    at Array.forEach (<anonymous>)
    at /opt/slack/resources/app.asar/dist/main.bundle.js:262:6522
    at /opt/slack/resources/app.asar/dist/main.bundle.js:143:7146
    at /opt/slack/resources/app.asar/dist/main.bundle.js:130:21553
    at /opt/slack/resources/app.asar/dist/main.bundle.js:263:922
    at dispatch (/opt/slack/resources/app.asar/dist/main.bundle.js:130:18457)
    at Object.next (/opt/slack/resources/app.asar/dist/main.bundle.js:318:86691)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at n.send (node:electron/js2c/browser_init:165:417)
    at b.send (node:electron/js2c/browser_init:161:2494)
    at /opt/slack/resources/app.asar/dist/main.bundle.js:262:6544
    at Array.forEach (<anonymous>)
    at /opt/slack/resources/app.asar/dist/main.bundle.js:262:6522
    at /opt/slack/resources/app.asar/dist/main.bundle.js:143:7146
    at /opt/slack/resources/app.asar/dist/main.bundle.js:130:21553
    at /opt/slack/resources/app.asar/dist/main.bundle.js:263:922
    at dispatch (/opt/slack/resources/app.asar/dist/main.bundle.js:130:18457)
    at Object.next (/opt/slack/resources/app.asar/dist/main.bundle.js:318:86691)
^C
```

And only with `--disable-seccomp-filter-sandbox` it works ok.

**Comment by powerman** [comment]
It turns out this issue happens because of this kernel configuration:

```
# sysctl user.max_user_namespaces
user.max_user_namespaces = 0
```

It is configured this way because of recommendation on https://kernsec.org/wiki/index.php/Kernel_Self_Protection_Project/Recommended_Settings
Also it's worth to say google-chrome runs just fine on my system (but requires **either** SUID chrome-sandbox or non-zero user.max_user_namespaces).

**Comment by Galkon** [comment]
@powerman your response here is the closest one I can find to an issue I am seeing in electron 20.x through electron 22.x on macOS Mojave 10.14.5:

> Render frame was disposed before WebFrameMain could be accessed

Anywhere that I am calling `browserWindow.webContents.send()`, despite first checking `!webContents.isDestroyed() && !webContents.isLoading()`.

Electron 12.x through 19.x work fine.

**Comment by powerman** [comment]
Still actual on Slack 4.29.149, linux 6.1.19-gentoo on x64.

**Comment by powerman** [comment]
bump

**Comment by powerman** [comment]
bump

**Comment by powerman** [comment]
it's annoying to bump it again and again

**Comment by sbe-arg** [comment]
Bump

**Comment by powerman** [comment]
Just checked Slack 4.39.90 - it works fine as is, without extra options/disabling sandbox.
