### ISSUE TITLE
[Bug]: Imcompatible module version ONLY when using WMs

### ISSUE THREAD

**Issue by lygamac** [electron/electron#31185]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

15.0.0

### What operating system are you using?

Other Linux

### Operating System Version

Arch Linux 5.14.8-arch1-1

### What arch are you using?

x64

### Expected Behavior

No error, as in a Desktop Environment

### Actual Behavior

The module won't run due to incompatible module version 

```
> my-electron-app@1.0.0 start
> electron .

[75684:0929/140031.023313:ERROR:sandbox_linux.cc(374)] InitializeSandbox() called with multiple threads in process gpu-process.
(node:75650) UnhandledPromiseRejectionWarning: Error: The module '~/my-electron-app/node_modules/abstract-socket/build/Release/bindings.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 93. This version of Node.js requires
NODE_MODULE_VERSION 98. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1800)
    at Object.Module._extensions..node (node:internal/modules/cjs/loader:1170:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:5:1800)
    at Module.load (node:internal/modules/cjs/loader:982:32)
    at Module._load (node:internal/modules/cjs/loader:823:12)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Module.require (node:internal/modules/cjs/loader:1006:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at bindings (~/my-electron-app/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (~/my-electron-app/node_modules/abstract-socket/lib/abstract_socket.js:4:36)
(Use `electron --trace-warnings ...` to show where the warning was created)
(node:75650) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
```

### Testcase Gist URL

https://gist.github.com/lygamac/26feb922abc19bf93a46df407b31307a

### Additional Information

- I did [rebuild native modules](https://www.electronjs.org/docs/tutorial/using-native-node-modules#using-native-node-modules)
- Only happens when using i3wm, dwm, etc. (AwesomeWM seems to be fine?)
- Only happens with some packages

**Comment by codebytere** [comment]
You should, per docs, do this:

```
# Every time you run "npm install", run this:
./node_modules/.bin/electron-rebuild
```

you can also, if necessary, specify the version: https://github.com/electron/electron-rebuild
