### ISSUE TITLE
[Bug]: Cannot find external modules with Yarn PnP

### ISSUE THREAD

**Issue by jzecca** [electron/electron#31611]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

15.3.0

### Operating System Version

Ubuntu 20.04

### What arch are you using?

x64

### Expected Behavior

Being able to require an external dependency.

### Actual Behavior

Loading any other dependency leas to the following error:
```
Error: Cannot find module 'lodash'
Require stack:
- /home/zed-k/projects/test/index.js
- /home/zed-k/projects/test/.yarn/unplugged/electron-npm-15.3.0-23ceb53e1f/node_modules/electron/dist/resources/default_app.asar/main.js
- 
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:934:15)
    at external_module_.Module._resolveFilename (/home/zed-k/projects/test/.pnp.cjs:10550:66)
    at Function.n._resolveFilename (node:electron/js2c/browser_init:249:1128)
    at Function.Module._load (node:internal/modules/cjs/loader:779:27)
    at external_module_.Module._load (/home/zed-k/projects/test/.pnp.cjs:10412:55)
    at Function.c._load (node:electron/js2c/asar_bundle:5:13331)
    at Module.require (node:internal/modules/cjs/loader:1006:19)
    at require (node:internal/modules/cjs/helpers:93:18)
    at Object.<anonymous> (/home/zed-k/projects/test/index.js:3:17)
    at Module._compile (node:internal/modules/cjs/loader:1110:14)
```

### Additional Information

- Here is the smallest reproducer I could come with: https://github.com/jzecca/electron-yarn3

- Electron & native node modules can be loaded without any issue

**Comment by zcbenz** [comment]
For security reasons bundled Electron apps can only load modules that bundled together with the app, otherwise a global installed module can easily break the app's code.

If you don't know how to handle this, it is recommended to use toolings to build your app.
https://www.electronjs.org/docs/latest/tutorial/application-distribution#with-tooling
