### ISSUE TITLE
[Bug]: 16.0.0 takes SIGTRAP at startup under arm64 and Wayland

### ISSUE THREAD

**Issue by klossner** [electron/electron#31885]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

16.0.0

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 18.04.5

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

15.3.0

### Expected Behavior

Dead-simple application, running on arm64 with Wayland, displays its page.

### Actual Behavior

At startup:
node_modules/electron/dist/electron exited with signal SIGTRAP

### Additional Information

Clone this standard quick-start code:
[https://github.com/electron/electron-quick-start.git](https://github.com/electron/electron-quick-start.git)
Edit package.json to set the electron version to 16.0.0. (15.3.0 works fine.)
Do:
npm install
export DISPLAY=:0.0
./node_modules/.bin/electron --enable-features=UseOzonePlatform --ozone-platform=wayland .

On an arm64 under Wayland, it core-dumps at startup with a bad pointer at location 0xaaaad1639ffc. That address makes me think it ran off a page into non-existent memory, but gdb says otherwise:
   0xaaaad1639ff0:      ldr     x9, [x19, #520]
   0xaaaad1639ff4:      cmp     x8, x9
   0xaaaad1639ff8:      b.eq    0xaaaad163a014  // b.none
=> 0xaaaad1639ffc:      ldr     x10, [x8], #8
   0xaaaad163a000:      cmp     x10, x20
   0xaaaad163a004:      b.eq    0xaaaad163a0c0  // b.none

Register x8 contains 0x3800053000 which is *not* a valid memory address.

**Comment by ckerr** [comment]
Hey @klossner, thanks for reporting this.

What happens when you try to run Chromium with the same command-line flag on the same machine?

I _suspect_ it's something to do with a combination of Chromium's still-opt-in-experimental support of Wayland x an older version of Ubuntu and am wondering if Chromium displays the same behavior on the test machine. That would help the maintainers to know where to look.

**Comment by klossner** [comment]
Hey @ckerr , there's a Chromium 71.0.3545.0 that works on this board under Wayland with no Xwayland. It came from the board manufacturer. It looks like a custom build; it doesn't need those command-line flags to run. If you can point me to a Chromium 96 compiled for Ubuntu arm64, I can try it. I can't find one myself and I don't have the chops to build it from source.

**Comment by kaaax0815** [comment]
Same error when running on Rapberry Pi 4 with X11 and without the electron flags

**Comment by YuanTian1991** [comment]
I use Ubuntu 20.04, have the same error on vscode terminal, but if I use ubuntu terminal to run `npm run start`, it works fine... I think it's a issue with vscode ubuntu version...

**Comment by kaaax0815** [comment]
> I use Ubuntu 20.04, have the same error on vscode terminal, but if I use ubuntu terminal to run `npm run start`, it works fine... I think it's a issue with vscode ubuntu version...

No. Because it doesnt work for me in normal bash on raspberry os 5.10 (debian 11 buster)

**Comment by cherti** [comment]
@ckerr 
Chromium 97.0.4692.71 with `chromium --enable-features=UseOzonePlatform --ozone-platform=wayland` works flawlessly.

**Comment by mitchchn** [comment]
I am also seeing the segfault on amd64 in 16.x and higher. I built from source to get a better stack trace:

```
> /electron -ozone-platform=wayland

Electron 18.0.0-nightly.20220106 - Build cross platform desktop apps with JavaScript, HTML, and CSS
Usage: electron [options] [path]

A path to an Electron app may be specified. It must be one of the following:
  - index.js file.
  - Folder containing a package.json file.
  - Folder containing an index.js file.
  - .html/.htm file.
  - http://, https://, or file:// URL.

Options:
  -i, --interactive     Open a REPL to the main process.
  -r, --require         Module to preload (option can be repeated).
  -v, --version         Print the version.
  -a, --abi             Print the Node ABI version.
[4810:0110/145257.782742:ERROR:cursor_loader.cc(114)] Failed to load a platform cursor of type kNull
[4810:0110/145257.783039:ERROR:wayland_window.cc(393)] Not implemented reached in virtual void ui::WaylandWindow::SetWindowIcons(const gfx::ImageSkia &, const gfx::ImageSkia &)
Received signal 11 SEGV_ACCERR 7ff6d50eb580
#0 0x56327cb07d09 base::debug::CollectStackTrace()
#1 0x56327ca38633 base::debug::StackTrace::StackTrace()
#2 0x56327cb07791 base::debug::(anonymous namespace)::StackDumpSignalHandler()
#3 0x7ff6d3d9d750 (/usr/lib64/libc.so.6+0x4274f)
#4 0x563278bdb000 base::ObserverList<>::AddObserver()
#5 0x563278be0024 electron::WindowStateWatcher::WindowStateWatcher()
#6 0x563278bcf342 electron::NativeWindowViews::NativeWindowViews()
#7 0x563278bd2b1b electron::NativeWindow::Create()
#8 0x563278a27fc0 electron::api::BaseWindow::BaseWindow()
#9 0x563278a3b415 electron::api::BrowserWindow::BrowserWindow()
#10 0x563278a3dd1d electron::api::BrowserWindow::New()
#11 0x563278a3e255 gin_helper::internal::InvokeNew<>()
#12 0x563278a2ee8f gin_helper::Dispatcher<>::DispatchToCallback()
#13 0x56327a254c8a v8::internal::FunctionCallbackArguments::Call()
#14 0x56327a251e7a v8::internal::(anonymous namespace)::HandleApiCallHelper<>()
#15 0x56327a25068a v8::internal::Builtin_Impl_HandleApiCall()
#16 0x56327a2501bd v8::internal::Builtin_HandleApiCall()
#17 0x1f4c07edc4b8 <unknown>
  r8: 00003b26002d1403  r9: 00000001ffffffff r10: 00003b2601201590 r11: 0000000000000000
 r12: 00003b26013ec000 r13: 00007ffca57c7440 r14: 00003b26002f6500 r15: 00003b26013ec058
  di: 00003b26002f6500  si: 00003b260141c0c0  bp: 00007ffca57c6e80  bx: 00003b260141c0c0
  dx: 00007ff6d3f585e0  ax: 00007ff6d50eb580  cx: 0000000000000001  sp: 00007ffca57c6670
  ip: 0000563278bdb000 efl: 0000000000010212 cgf: 002b000000000033 erf: 0000000000000004
 trp: 000000000000000e msk: 0000000000000000 cr2: 00007ff6d50eb580
[end of stack trace]
[4850:0100/000000.822538:ERROR:gpu_init.cc(454)] Passthrough is not supported, GL is egl, ANGLE is 
Segmentation fault (core dumped)
```

Stubbing out this function:

```
[4810:0110/145257.783039:ERROR:wayland_window.cc(393)] Not implemented reached in virtual void ui::WaylandWindow::SetWindowIcons(const gfx::ImageSkia &, const gfx::ImageSkia &)
```

Does allow electron to run as did before, without a window frame. (It is possible that #29618 will restore the frame, although it still has the same segfault.)

**Comment by jplatte** [comment]
Not sure whether SIGTRAP and SIGSEGV can have the same root cause on different architectures but since #32436 is possibly a duplicate and I expect more people to watch this issue, here's a full stacktrace with debug symbols (as provided in GitHub releases) from the crash, using the latest v17 beta:

```
% gdb ./electron
GNU gdb (GDB) 11.2
<gdb copyright, help, stuff>
Reading symbols from ./electron...
Reading symbols from <path>/electron.debug...
(gdb) run --ozone-platform=wayland
Starting program: <path>/electron --ozone-platform=wayland
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
[New Thread 0x7ffff1bf6640 (LWP 65040)]
[Detaching after fork from child process 65041]
[Detaching after fork from child process 65042]
[Detaching after fork from child process 65043]
[New Thread 0x7ffff13f5640 (LWP 65046)]
[New Thread 0x7ffff0bf4640 (LWP 65047)]
[New Thread 0x7ffff03f3640 (LWP 65048)]
[New Thread 0x7fffefbf2640 (LWP 65049)]
[New Thread 0x7fffef3f1640 (LWP 65050)]
[New Thread 0x7fffeebf0640 (LWP 65051)]
[New Thread 0x7fffee3ef640 (LWP 65052)]
[New Thread 0x7fffed9ec640 (LWP 65053)]
[New Thread 0x7fffed1eb640 (LWP 65054)]
[New Thread 0x7fffec9ea640 (LWP 65055)]
[New Thread 0x7fffec1e9640 (LWP 65056)]
[New Thread 0x7fffeb9e8640 (LWP 65057)]

Electron 17.0.0-beta.7 - Build cross platform desktop apps with JavaScript, HTML, and CSS
Usage: electron [options] [path]

A path to an Electron app may be specified. It must be one of the following:
  - index.js file.
  - Folder containing a package.json file.
  - Folder containing an index.js file.
  - .html/.htm file.
  - http://, https://, or file:// URL.

Options:
  -i, --interactive     Open a REPL to the main process.
  -r, --require         Module to preload (option can be repeated).
  -v, --version         Print the version.
  -a, --abi             Print the Node ABI version.
[New Thread 0x7fffeb96a640 (LWP 65058)]
[New Thread 0x7fffeb146640 (LWP 65059)]
[New Thread 0x7fffea901640 (LWP 65060)]
[New Thread 0x7fffea0ea640 (LWP 65061)]
[New Thread 0x7fffe9752640 (LWP 65062)]
[New Thread 0x7fffe8f51640 (LWP 65063)]
[Thread 0x7fffe8f51640 (LWP 65063) exited]
[New Thread 0x7fffe8f51640 (LWP 65064)]
[New Thread 0x7fffe869a640 (LWP 65065)]
[New Thread 0x7fffe77ac640 (LWP 65067)]
[New Thread 0x7fffe7fad640 (LWP 65066)]
[New Thread 0x7fffe6fab640 (LWP 65068)]
[New Thread 0x7fffe67aa640 (LWP 65069)]
[New Thread 0x7fffe5fa9640 (LWP 65070)]
[New Thread 0x7fffe5788640 (LWP 65071)]
[New Thread 0x7fffe4f87640 (LWP 65072)]
[New Thread 0x7fffe4709640 (LWP 65073)]
[New Thread 0x7fffe3c38640 (LWP 65076)]
[65036:0126/132212.595772:ERROR:cursor_loader.cc(116)] Failed to load a platform cursor of type kNull
[65074:0126/132212.622584:ERROR:gpu_init.cc(454)] Passthrough is not supported, GL is egl, ANGLE is 
[65074:0126/132212.624860:ERROR:sandbox_linux.cc(377)] InitializeSandbox() called with multiple threads in process gpu-process.

Thread 1 "electron" received signal SIGSEGV, Segmentation fault.
std::__1::find_if<std::__1::__wrap_iter<base::internal::UncheckedObserverAdapter const*>, base::internal::ProjectedUnaryPredicate<base::ObserverList<x11::EventObserver, false, true, base::internal::UncheckedObserverAdapter>::HasObserver(x11::EventObserver const*) const::{lambda(auto:1 const&)#1}, base::identity>(base::ObserverList<x11::EventObserver, false, true, base::internal::UncheckedObserverAdapter>::HasObserver(x11::EventObserver const*) const::{lambda(auto:1 const&)#1}&, base::identity&)::{lambda(auto:1&&)#1}>(std::__1::__wrap_iter<base::internal::UncheckedObserverAdapter const*>, std::__1::__wrap_iter<base::internal::UncheckedObserverAdapter const*>, base::internal::ProjectedUnaryPredicate<base::ObserverList<x11::EventObserver, false, true, base::internal::UncheckedObserverAdapter>::HasObserver(x11::EventObserver const*) const::{lambda(auto:1 const&)#1}, base::identity>(base::ObserverList<x11::EventObserver, false, true, base::internal::UncheckedObserverAdapter>::HasObserver(x11::EventObserver const*) const::{lambda(auto:1 const&)#1}&, base::identity&)::{lambda(auto:1&&)#1}) (__first=..., __last=..., __pred=...) at ../../buildtools/third_party/libc++/trunk/include/algorithm:943
943	../../buildtools/third_party/libc++/trunk/include/algorithm: Datei oder Verzeichnis nicht gefunden.
(gdb) bt
#0  std::__1::find_if<std::__1::__wrap_iter<base::internal::UncheckedObserverAdapter const*>, base::internal::ProjectedUnaryPredicate<base::ObserverList<x11::EventObserver, false, true, base::internal::UncheckedObserverAdapter>::HasObserver(x11::EventObserver const*) const::{lambda(auto:1 const&)#1}, base::identity>(base::ObserverList<x11::EventObserver, false, true, base::internal::UncheckedObserverAdapter>::HasObserver(x11::EventObserver const*) const::{lambda(auto:1 const&)#1}&, base::identity&)::{lambda(auto:1&&)#1}>(std::__1::__wrap_iter<base::internal::UncheckedObserverAdapter const*>, std::__1::__wrap_iter<base::internal::UncheckedObserverAdapter const*>, base::internal::ProjectedUnaryPredicate<base::ObserverList<x11::EventObserver, false, true, base::internal::UncheckedObserverAdapter>::HasObserver(x11::EventObserver const*) const::{lambda(auto:1 const&)#1}, base::identity>(base::ObserverList<x11::EventObserver, false, true, base::internal::UncheckedObserverAdapter>::HasObserver(x11::EventObserver const*) const::{lambda(auto:1 const&)#1}&, base::identity&)::{lambda(auto:1&&)#1}) (__first=..., __last=..., __pred=...)
    at ../../buildtools/third_party/libc++/trunk/include/algorithm:943
#1  base::ranges::find_if<std::__1::__wrap_iter<base::internal::UncheckedObserverAdapter const*>, base::ObserverList<x11::EventObserver, false, true, base::internal::UncheckedObserverAdapter>::HasObserver(x11::EventObserver const*) const::{lambda(auto:1 const&)#1}, base::identity, std::__1::random_access_iterator_tag>(std::__1::__wrap_iter<base::internal::UncheckedObserverAdapter const*>, std::__1::__wrap_iter<base::internal::UncheckedObserverAdapter const*>, base::ObserverList<x11::EventObserver, false, true, base::internal::UncheckedObserverAdapter>::HasObserver(x11::EventObserver const*) const::{lambda(auto:1 const&)#1}, base::identity) (first=..., last=..., pred=..., proj=...)
    at ../../base/ranges/algorithm.h:465
#2  base::ranges::find_if<std::__1::vector<base::internal::UncheckedObserverAdapter, std::__1::allocator<base::internal::UncheckedObserverAdapter> > const&, base::ObserverList<x11::EventObserver, false, true, base::internal::UncheckedObserverAdapter>::HasObserver(x11::EventObserver const*) const::{lambda(auto:1 const&)#1}, base::identity, std::__1::random_access_iterator_tag>(std::__1::vector<base::internal::UncheckedObserverAdapter, std::__1::allocator<base::internal::UncheckedObserverAdapter> > const&, base::ObserverList<x11::EventObserver, false, true, base::internal::UncheckedObserverAdapter>::HasObserver(x11::EventObserver const*) const::{lambda(auto:1 const&)#1}, base::identity)
    (pred=..., range=<optimized out>, proj=...) at ../../base/ranges/algorithm.h:483
#3  base::ObserverList<x11::EventObserver, false, true, base::internal::UncheckedObserverAdapter>::HasObserver(x11::EventObserver const*) const (obs=0xd7000f7bf60, this=<optimized out>) at ../../base/observer_list.h:304
#4  base::ObserverList<x11::EventObserver, false, true, base::internal::UncheckedObserverAdapter>::AddObserver(x11::EventObserver*) (this=<optimized out>, obs=0xd7000f7bf60) at ../../base/observer_list.h:271
#5  x11::Connection::AddEventObserver(x11::EventObserver*) (this=0xd70002bed88, observer=0xd7000f7bf60) at ../../ui/gfx/x/connection.cc:486
#6  0x00005555576fdb0e in electron::WindowStateWatcher::WindowStateWatcher(electron::NativeWindowViews*) (this=0xd7000f7bf60, window=<optimized out>) at ../../electron/shell/browser/ui/x/window_state_watcher.cc:27
#7  0x00005555576ef042 in std::__1::make_unique<electron::WindowStateWatcher, electron::NativeWindowViews*>(electron::NativeWindowViews*&&) (__args=<optimized out>)
    at ../../buildtools/third_party/libc++/trunk/include/__memory/unique_ptr.h:725
#8  electron::NativeWindowViews::NativeWindowViews(gin_helper::Dictionary const&, electron::NativeWindow*) (this=0xd70002cfe00, options=..., parent=0x0) at ../../electron/shell/browser/native_window_views.cc:270
#9  0x00005555576f1e9b in electron::NativeWindow::Create(gin_helper::Dictionary const&, electron::NativeWindow*) (options=..., parent=0x0) at ../../electron/shell/browser/native_window_views.cc:1656
#10 0x00005555575a120e in electron::api::BaseWindow::BaseWindow(v8::Isolate*, gin_helper::Dictionary const&) (this=<optimized out>, isolate=0xd7000690000, options=...) at ../../electron/shell/browser/api/electron_api_base_window.cc:96
#11 0x00005555575b0305 in electron::api::BrowserWindow::BrowserWindow(gin::Arguments*, gin_helper::Dictionary const&) (this=0xd70002c5780, args=0x7fffffffc820, options=...)
    at ../../electron/shell/browser/api/electron_api_browser_window.cc:33
#12 0x00005555575b255c in electron::api::BrowserWindow::New(gin_helper::ErrorThrower, gin::Arguments*) (thrower=..., args=0x7fffffffc820) at ../../electron/shell/browser/api/electron_api_browser_window.cc:513
#13 0x00005555575b2b8d in base::RepeatingCallback<gin_helper::WrappableBase* (gin_helper::ErrorThrower, gin::Arguments*)>::Run(gin_helper::ErrorThrower, gin::Arguments*) const & (this=0xd7000f7b7d8, args=..., args=<optimized out>)
    at ../../base/callback.h:241
#14 gin_helper::internal::InvokeFactory<gin_helper::ErrorThrower, gin::Arguments*>(gin::Arguments*, base::RepeatingCallback<gin_helper::WrappableBase* (gin_helper::ErrorThrower, gin::Arguments*)> const&)
    (callback=..., args=<optimized out>) at ../../electron/shell/common/gin_helper/constructor.h:43
#15 gin_helper::internal::InvokeNew<gin_helper::WrappableBase* (gin_helper::ErrorThrower, gin::Arguments*)>(base::RepeatingCallback<gin_helper::WrappableBase* (gin_helper::ErrorThrower, gin::Arguments*)> const&, v8::Isolate*, gin_helper::Arguments*) (factory=..., isolate=<optimized out>, args=0x7fffffffc820) at ../../electron/shell/common/gin_helper/constructor.h:134
#16 0x00005555575a7edd in base::RepeatingCallback<void (v8::Isolate*, gin_helper::Arguments*)>::Run(v8::Isolate*, gin_helper::Arguments*) const & (this=0x7fffffffc848, args=0xd7000f7bf60, args=0x0) at ../../base/callback.h:241
#17 gin_helper::Invoker<gin_helper::IndicesHolder<0ul, 1ul>, v8::Isolate*, gin_helper::Arguments*>::DispatchToCallback(base::RepeatingCallback<void (v8::Isolate*, gin_helper::Arguments*)>) (this=0x7fffffffc850, callback=...)
    at ../../electron/shell/common/gin_helper/function_template.h:230
#18 gin_helper::Dispatcher<void (v8::Isolate*, gin_helper::Arguments*)>::DispatchToCallback(v8::FunctionCallbackInfo<v8::Value> const&) (info=<optimized out>) at ../../electron/shell/common/gin_helper/function_template.h:264
#19 0x000055555862eb79 in v8::internal::FunctionCallbackArguments::Call(v8::internal::CallHandlerInfo) (this=0x7fffffffc950, handler=...) at ../../v8/src/api/api-arguments-inl.h:152
#20 v8::internal::(anonymous namespace)::HandleApiCallHelper<true>(v8::internal::Isolate*, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::HeapObject>, v8::internal::Handle<v8::internal::FunctionTemplateInfo>, v8::internal::Handle<v8::internal::Object>, v8::internal::BuiltinArguments) (isolate=0xd7000690000, function=..., new_target=..., fun_data=..., args=..., receiver=...) at ../../v8/src/builtins/builtins-api.cc:112
#21 v8::internal::Builtin_Impl_HandleApiCall(v8::internal::BuiltinArguments, v8::internal::Isolate*) (args=..., isolate=0xd7000690000) at ../../v8/src/builtins/builtins-api.cc:138
#22 v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) (args_length=<optimized out>, args_object=<optimized out>, isolate=<optimized out>) at ../../v8/src/builtins/builtins-api.cc:130
#23 0x00003dbc07f0aaf8 in  ()
#24 0x00007fffffffca40 in  ()
#25 0x000000000000002c in  ()
#26 0x00007fffffffcaa8 in  ()
#27 0x00003dbc07e89bef in  ()
#28 0x00003dbc08472a05 in  ()
#29 0x00003dbc08472a05 in  ()
#30 0x000000000000000c in  ()
#31 0x00003dbc08002431 in  ()
#32 0x00003dbc080a3005 in  ()
#33 0x00003dbc080a1d01 in  ()
#34 0x0000000000000004 in  ()
#35 0x00003dbc08061371 in  ()
#36 0x0000000000000028 in  ()
#37 0x00007fffffffcb10 in  ()
#38 0x00003dbc07faba76 in  ()
#39 0x0000000000000000 in  ()
```

**Comment by klossner** [comment]
Electron 17.0.0 (the official release, not the beta) takes SIGSEGV on startup on arm64 under Wayland.

**Comment by theanonymousexyz** [comment]
> Electron 17.0.0 (the official release, not the beta) takes SIGSEGV on startup on arm64 under Wayland.

x86_64 too.

**Comment by TomMettam** [comment]
Gentoo user here.

I am **not** using Wayland but I had the wayland library installed, and I was getting this issue.

Simply uninstalling the library stopped Electron from crashing. It seems Electron is trying to use Wayland if it exists, even if it's not actually in use..

**Comment by klossner** [comment]
This problem persists in version 16 and 17 but is fixed in version 18. We have successfully deployed an app using version 18 in an IoT device.
