### ISSUE TITLE
[Bug]: ERR_FAILED load local file when start app sencond time on window 10 pro

### ISSUE THREAD

**Issue by tofishes** [electron/electron#32110]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a feature request that matches the one I want to file, without success.

### Electron Version

13.6.3

### What operating system are you using?

Windows

### Operating System Version

Windows 10 Pro version 19043.1055

### What arch are you using?

x64

### Last Known Working Electron version

13.0.0

### Expected Behavior

load file succces whether run any times.

### Actual Behavior

On windows 10 pro system, I install app and run app first time, it's ok.
When I exit app and restart, it will can't load file to show.

I get the error is like under:
 
```
{ Error: ERR_FAILED (-2) loading 'file://Y:\github.com\dataich\electron-sandbox-sample\src/index.html'
    at rejectAndCleanup (Y:\github.com\dataich\electron-sandbox-sample\node_modules\electron\dist\resources\electron.asar\browser\navigation-controller.js:72:21)
    at WebContents.stopLoadingListener (Y:\github.com\dataich\electron-sandbox-sample\node_modules\electron\dist\resources\electron.asar\browser\navigation-controller.js:113:9)
    at WebContents.emit (events.js:194:13)
  errno: -2,
  code: 'ERR_FAILED',
  url:
   'file://Y:\\github.com\\dataich\\electron-sandbox-sample\\src/index.html' }
```

If restart os, run app first time still be ok, and get error on second and more times.

Can help me?

### Additional Information

Maybe other reason is that the BrowserWindow can't tigger 'ready-to-show' event, the console.log not print in the event callback.

**Comment by tofishes** [comment]
I test some cases, find that when I create window with option.show = false, the window ready-to-show event and webContents did-finish-load event can't be triggered.

Only window 10 pro happens.

**Comment by tofishes** [comment]
我放弃了，我发现类似问题已经早已出现，至少从electron v8开始，到目前还没有修复。win10 pro总是间歇性不触发显示。

**Comment by tofishes** [comment]
I gave up. I found that similar problems had already occurred, at least since the Electron V8, and had not yet been fixed. Win10 Pro always intermittently does not trigger the display.
