### ISSUE TITLE
[Bug]:  'Command failed' is displayed when installing electron.

### ISSUE THREAD

**Issue by CBH37** [electron/electron#32338]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

12.0.0

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 20.04

### What arch are you using?

x64

### Expected Behavior

yarn add --dev electron

### Actual Behavior

yarn add v1.22.17
info No lockfile found.
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
[1/1] ⠁ electron
error /home/cbh37/vom/node_modules/electron: Command failed.
Exit code: 1
Command: node install.js
Arguments:
Directory: /home/cbh37/vom/node_modules/electron
Output:
RequestError: socket hang up
    at ClientRequest.<anonymous> (/home/cbh37/vom/node_modules/got/source/request-as-event-emitter.js:178:14)
    at Object.onceWrapper (node:events:510:26)
    at ClientRequest.emit (node:events:402:35)
    at ClientRequest.origin.emit (/home/cbh37/vom/node_modules/@szmarczak/http-timer/source/index.js:37:11)
    at TLSSocket.socketOnEnd (node:_http_client:471:9)
    at TLSSocket.emit (node:events:402:35)
    at endReadableNT (node:internal/streams/readable:1343:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

**Comment by ckerr** [comment]
Hi,

This looks like it might've been a temporary networking issue installing packages and when I try to repro using `yarn install` on an app that uses Electron 12.0.0 I am not seeing the error here.

So, can  you check and see if this problem is still occurring?

**Comment by miniak** [comment]
Electron 12 is not supported anymore
