### ISSUE TITLE
[Bug]: crash on linux in api::Tray::Destroy()

### ISSUE THREAD

**Issue by indutny-signal** [electron/electron#32581]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

16.0.7

### What operating system are you using?

Other Linux

### Operating System Version

Arch Linux

### What arch are you using?

x64

### Expected Behavior

App not crashing

### Actual Behavior

App is crashing with the following crash dump: https://gist.github.com/indutny-signal/7f8bae6036603c8e93a4465c77b6cc2f

Excerpt:

```
 0  signal-desktop-beta!v8::internal::GlobalHandles::Destroy(unsigned long*) [global-handles.cc : 258 + 0x0]
 1  signal-desktop-beta!electron::api::Tray::Destroy() [v8-persistent-handle.h : 477 + 0x4]
 2  signal-desktop-beta!gin::internal::Dispatcher<void (electron::api::Tray*)>::DispatchToCallbackImpl(gin::Arguments*) [callback.h : 241 + 0x2]
 3  signal-desktop-beta!gin::internal::Dispatcher<void (electron::api::Tray*)>::DispatchToCallback(v8::FunctionCallbackInfo<v8::Value> const&) [function_template.h : 218 + 0x7]
 4  signal-desktop-beta!v8::internal::Builtin_HandleApiCall(int, unsigned long*, v8::internal::Isolate*) [api-arguments-inl.h : 152 + 0x8]
...
21  signal-desktop-beta!electron::api::BaseWindow::OnWindowClosed() [electron_api_base_window.cc : 163 + 0x13]
...
38  signal-desktop-beta!non-virtual thunk to electron::api::WebContents::~WebContents() [electron_api_web_contents.cc : 933 + 0x7]
...
42  signal-desktop-beta!content::BrowserMainLoop::ShutdownThreadsAndCleanUp() [browser_main_loop.cc : 1028 + 0x4]
```

**Comment by codebytere** [comment]
@indutny-signal is there any kind of repro or actions you know are occurring prior to the crash?

**Comment by indutny-signal** [comment]
Unclear, this is reported by external users and they learned about the crash only after restarting the app. Looks like it could be coming from `app.quit()`, but I'm not entirely sure.

**Comment by nornagon** [comment]
The critical path here is:

1. The app is shutting down (`BrowserMainRunnerImpl::Shutdown`)
2. gin::Wrappable objects are being cleaned up (`CleanedUpAtExit::DoCleanup`)
3. A `WebContents` is being destroyed as part of that cleanup (`WebContents::~WebContents`)
4. which results in the associated `BrowserWindow` being destroyed (`BrowserWindow::CloseImmediately`)
5. which emits an event in JS (`BaseWindow::OnWindowClosed`)
6. which calls `tray.destroy()` (`Tray::Destroy`)

I suspect that at this point, the `Tray` object has already been freed, because `Tray` is also `CleanedUpAtExit`. So this ends up calling `Tray::Destroy()` on a freed object, which crashes.

There are a couple of possible fixes here. One is that perhaps we should not emit JS events during `CleanedUpAtExit::DoCleanup`. Another could be that there need to be multiple passes in `DoCleanup`, one that "closes" the objects (& emits any relevant JS events), and a second that actually does the deletion. Another is that freeing `Tray` should zero out the pointer in the associated v8 object, and then use the machinery in `gin_helper::Destroyable` to turn this from a crash into a JS error (`throw new TypeError("Object has been destroyed")`).

You should be able to work around this in your app for now by hooking the `quit` event, setting a flag when that happens, and then avoid calling `tray.destroy` if the flag is set.

**Comment by indutny-signal** [comment]
> You should be able to work around this in your app for now by hooking the `quit` event, setting a flag when that happens, and then avoid calling `tray.destroy` if the flag is set.

We will do that. Thanks for a suggestion!

**Comment by brjsp** [comment]
That stack trace was made before [this commit](https://github.com/electron/electron/commit/c5a2af7811e35acf67651725d1099b15de0c6ee4), but in Electron 19.0.11 the crash persists with a slightly different stack trace:
```
#0  v8::internal::GlobalHandles::NodeSpace<v8::internal::GlobalHandles::Node>::Free () at ../../v8/src/handles/global-handles.cc:293
#1  v8::internal::GlobalHandles::NodeSpace<v8::internal::GlobalHandles::Node>::Release () at ../../v8/src/handles/global-handles.cc:288
#2  0x00005578f89958fa in v8::PersistentBase<v8::Value>::Reset (this=0x4401c28cf0) at ../../v8/include/v8-persistent-handle.h:477
#3  gin_helper::Pinnable<electron::api::Tray>::Unpin (this=0x4401c28cf0) at ../../electron/shell/common/gin_helper/pinnable.h:26
#4  electron::api::Tray::Destroy (this=0x4401c28cd0) at ../../electron/shell/browser/api/electron_api_tray.cc:185
#5  0x00005578f8999515 in base::RepeatingCallback<void (electron::api::Tray*)>::Run(electron::api::Tray*) const & (args#0=0x4401c28cd0, this=0x7fff8c7b1848) at ../../base/callback.h:242
#6  gin::internal::Invoker<std::integer_sequence<unsigned long, 0ul>, electron::api::Tray*>::DispatchToCallback(base::RepeatingCallback<void (electron::api::Tray*)>) (callback=..., this=<synthetic pointer>) at ../../gin/function_template.h:181
#7  gin::internal::Dispatcher<void (electron::api::Tray*)>::DispatchToCallbackImpl(gin::Arguments*) (args=0x7fff8c7b1850) at ../../gin/function_template.h:213
#8  gin::internal::Dispatcher<void (electron::api::Tray*)>::DispatchToCallback(v8::FunctionCallbackInfo<v8::Value> const&) (info=...) at ../../gin/function_template.h:219
#9  0x00005578fa4102f5 in v8::internal::FunctionCallbackArguments::Call () at ../../v8/src/api/api-arguments-inl.h:147
#10 HandleApiCallHelper<false> () at ../../v8/src/builtins/builtins-api.cc:112
#11 0x00005578fa41103f in Builtin_Impl_HandleApiCall () at ../../v8/src/builtins/builtins-api.cc:142
#12 v8::internal::Builtin_HandleApiCall () at ../../v8/src/builtins/builtins-api.cc:130
```
The user [claims](https://bugzilla.opensuse.org/show_bug.cgi?id=1202333) it happens when logging out of an Xfce session with signal-desktop started.
