### ISSUE TITLE
[Bug]: GetVSyncParametersIfAvailable() failed for 1 times!

### ISSUE THREAD

**Issue by arjunj132** [electron/electron#32760]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.0.0

### What operating system are you using?

Other Linux

### Operating System Version

Debian GNU/Linux 11 (bullseye)

### What arch are you using?

x64

### Last Known Working Electron version

16.0.8

### Expected Behavior

The command `npm start` runs electron smoothly without any errors.

### Actual Behavior

The command logs out this:

```
> dinobrowse@1.0.0 start
> electron .

[20676:0204/182046.077429:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[20676:0204/182047.144782:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[20676:0204/182047.158435:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
```

### Testcase Gist URL

https://gist.github.com/1787a7f55987914d30b12cc0e4956b7b

**Comment by ckerr** [comment]
I can reproduce the issue with the testcase gist on Ubuntu 21.10 by starting and then exiting the app. I'm not sure what the trigger is; _sometimes_ I'll see `[46025:0209/114839.308166:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!` pop up when the app appears. But it always appears when exiting the app.

This first appears in v17.0.0-alpha.4. There are only a handful of commits between those two releases (https://github.com/electron/electron/compare/v17.0.0-alpha.3...v17.0.0-alpha.4) but one of them is a Chromium roll

**Comment by egon-isnoise** [comment]
I am still having this issue on Ubuntu 22. Gives me this error 3 times and then shuts down the app

**Comment by immortalt** [comment]
I am still having this issue on Ubuntu 22. Gives me this error 3 times but the app can run as normal.

**Comment by thamizh-qwerty** [comment]
Still having this issue on Ubuntu 22.0 and Node v18.7.0. 

Note: 
1. electron@15.0.0 - does not throws the error
2. But electron@18, electron@19 and electron@21 - throws ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!

**Comment by impietrito** [comment]
I'm having the same issue on Ubuntu 22.04

**Comment by smatvienko-tb** [comment]
having the same issue with google-chrome on Ubuntu 22
![image](https://user-images.githubusercontent.com/79898499/198822091-33e632af-1138-46d7-ac5b-c084fc35d721.png)
![image](https://user-images.githubusercontent.com/79898499/198822114-1c6f30ea-9c7d-4cc4-ba59-b2584c032d73.png)

**Comment by nornagon** [comment]
If this is showing up in Chromium then there's likely nothing we can do, file a bug at https://crbug.com.

**Comment by nebaron** [comment]
I got the same issue.
I have Ubuntu 22.04.1. But also, I have tried on Devian 11, and it works perfectly.

Here is the log:

```
➜  ~ google-chrome --enable-logging --v=1
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
[12671:12671:1101/124737.422686:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.ScreenSaver.GetActive: object_path= /org/freedesktop/ScreenSaver: org.freedesktop.DBus.Error.NotSupported: This method is not implemented
[12715:12715:1101/124752.455313:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[12715:12715:1101/124754.052443:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[12715:12715:1101/124757.593427:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
```

**Comment by arjunj132** [comment]
I reported a bug here: https://bugs.chromium.org/p/chromium/issues/detail?id=1383719

**Comment by IPKIN9** [comment]
just add this code in bellow your main.js file

**Comment by arjunj132** [comment]
> just add this code in bellow your main.js file 
app.commandLine.appendSwitch('ignore-gpu-blacklist'); 
app.commandLine.appendSwitch('disable-gpu'); 
app.commandLine.appendSwitch('disable-gpu-compositing');

It disables GPU though, right?

**Comment by IPKIN9** [comment]
Yaps, you can disable hardware acceleration to. Put this code 
app.disableHardwareAcceleration()

Look the documentation in below. I found this problem on ubuntu.

https://www.electronjs.org/docs/latest/tutorial/offscreen-rendering

**Comment by eaglehuntt** [comment]
This is affecting me. I am on Ubuntu 22.04.2 LTS

**Comment by abowen** [comment]
Happens to me too when using two different Electron apps (element-desktop + joplin-desktop)

**Comment by shaquibimdad** [comment]
# Happening with me on chrome, chromium and vscode 

### Vscode
```
[73190:0409/212507.583785:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[73190:0409/212507.584567:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[main 2023-04-09T15:55:08.572Z] update#checkForUpdates, state =  idle
[main 2023-04-09T15:55:08.572Z] update#setState checking for updates
[main 2023-04-09T15:55:08.572Z] resolveShellEnv(): skipped (VSCODE_CLI is set)
[main 2023-04-09T15:55:08.662Z] update#setState idle
[73154:0409/212538.996431:INFO:CONSOLE(620)] "%cTRACE color: #888 InteractiveSessionService#onWillSaveState: Persisting 0 sessions", source: vscode-file://vscode-app/opt/visual-studio-code/resources/app/out/vs/workbench/workbench.desktop.main.js (620)
[73154:0409/212557.191371:INFO:CONSOLE(1997)] "[[object Object]]s.tmpDir is not a function", source: vscode-file://vscode-app/opt/visual-studio-code/resources/app/out/vs/workbench/workbench.desktop.main.js (1997)
[73154:0409/212557.191405:INFO:CONSOLE(1997)] "TypeError: s.tmpDir is not a function
    at e._sendFirstFileOnDisk (/home/shaquibimdad/.vscode/extensions/msjsdiag.vscode-react-native-1.10.2/dist/rn-extension.js:1:25358)
    at Timeout._onTimeout (/home/shaquibimdad/.vscode/extensions/msjsdiag.vscode-react-native-1.10.2/dist/rn-extension.js:1:24162)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)", source: vscode-file://vscode-app/opt/visual-studio-code/resources/app/out/vs/workbench/workbench.desktop.main.js (1997)
[73154:0409/212639.018297:INFO:CONSOLE(620)] "%cTRACE color: #888 InteractiveSessionService#onWillSaveState: Persisting 0 sessions", source: vscode-file://vscode-app/opt/visual-studio-code/resources/app/out/vs/workbench/workbench.desktop.main.js (620)
[73154:0409/212739.040553:INFO:CONSOLE(620)] "%cTRACE color: #888 InteractiveSessionService#onWillSaveState: Persisting 0 sessions", source: vscode-file://vscode-app/opt/visual-studio-code/resources/app/out/vs/workbench/workbench.desktop.main.js (620)
[73190:0409/212814.705837:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
```

### Chrome

```
Log Messages
[1959:1959:0409/140204.192071:WARNING:sandbox_linux.cc(393)] : InitializeSandbox() called with multiple threads in process gpu-process.
[1959:1959:0409/140212.895308:ERROR:gl_surface_presentation_helper.cc(260)] : GetVSyncParametersIfAvailable() failed for 1 times!
[1959:1959:0409/140212.907863:ERROR:gl_surface_presentation_helper.cc(260)] : GetVSyncParametersIfAvailable() failed for 2 times!
[1959:1959:0409/140216.809130:ERROR:gl_surface_presentation_helper.cc(260)] : GetVSyncParametersIfAvailable() failed for 3 times!
```

**Comment by Konglomneshued** [comment]
```

[22564:0514/135424.421988:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!

[22564:0514/135424.426911:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!

[22564:0514/135427.561441:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!

```

**Comment by moccalotto** [comment]
I am still having this issue on manjaro. 
Node 20.4.0
electron 22.3.18

**Comment by blechdom** [comment]
me too:
ubuntu 22
node 20
electron 25

**Comment by KingAkeem** [comment]
Having this issue as well
electron 36
node 20
ubuntu 23

**Comment by aboode95** [comment]
Having the same issue with:
Obsidian 1.3.7 Appimage

In system:
OS: nix-build (Nix) 2.13.5 (NixOS)
Electron version: v25.3.1

**Comment by burkelyp** [comment]
bump

**Comment by slumtrimpet** [comment]
Had this issue on Electron 26.2.1 and was dead in the water.
Downgrading to 25.8.1 resolves it for now so we can keep rolling.

**Comment by pernydev** [comment]
Same problem for me on Fedora 36 (yes I do need to update). Running it just through bash. Downgrading to 25.8.1 worked to patch the window turning white but still get the 3 lines logged in console.

**Comment by liaminventions** [comment]
Strangely I can replicate this on my main laptop but not on my thinkpad. I have electron and electron25 installed on both computers.

as a result, webcord and armcord work on the thinkpad but not on the hp.

**Comment by Bidski** [comment]
I am also experiencing this issue on Arch Linux using [Netron](https://github.com/lutzroeder/netron). 

Using electron 26.2.1 it displays 
```
[17212:0920/091457.632834:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[17212:0920/091457.899662:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[17212:0920/091457.906780:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
```
and then the UI will, at some point, go blank with no other errors/warnings/messages reported.

If I downgrade electron to 25.8.1 then those 3 errors are still reported but the UI works as expected.

**Comment by agap-0251** [comment]
I'm experiencing this issue while running latest version of electron.
I have UBUNTU 22.04 LTS OS running on my  XIAOMI ULTRA NOTEBOOK.
```
[16565:1003/155217.279363:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[16565:1003/155221.276028:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[16565:1003/155231.760236:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
```

**Comment by cmdcolin** [comment]
can anyone confirm whether this specific issue (the GetVSyncParametersIsAvailable message) is directly related to the screen turning white, and maybe even how that is happening? some people in this thread suggest that they can use the app as usual while others report the screen going white

https://github.com/electron/electron/issues/32760#issuecomment-1726669803
https://github.com/electron/electron/issues/32760#issuecomment-1724988745

I just upgraded our app to electron 26 and had a user report they had screen going white and so I'm considering downgrading to 25

**Comment by Nama** [comment]
> can anyone confirm whether this specific issue (the GetVSyncParametersIsAvailable message) 

Guess so, it happens for me always on the second fail.

> some people in this thread suggest that they can use the app as usual while others report the screen going white

I think this is related to the electron version. I have the window turn white since electron 26.

This happens then I hover a text field or re-focus the window.

Heres a video:

https://github.com/electron/electron/assets/2297270/cfd2fcf1-a6bc-463a-86ce-6fa2df531ad3

**Comment by RihaanBH-1810** [comment]
I'm experiencing this issue while running latest version of electron. 

I have Fedora 39 workstation , electron version 28.0.0
```
[8108:1211/084630.301820:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[8108:1211/084634.650710:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[8108:1211/084646.123532:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
```

**Comment by oluijks** [comment]
Same issue, different version of Node

```
[316311:1212/221702.543191:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[316311:1212/221704.916150:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[316311:1212/221711.076161:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
```

Fedora: 39 - Gnome 45
Node: v20.9.0
Chromium 120.0.6099.56 / Electron 28.0.0

**Comment by polyntsov** [comment]
Same? issue with Obsidian after upgrading electron from 25.9.8 to 28.1.0 version:
```
2024-01-04 14:19:31 Loading main app package /usr/lib/obsidian/obsidian.asar
Updates disabled.
[16055:0104/171931.839009:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[16055:0104/171932.108530:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[16055:0104/171932.123955:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
```
After this electron upgrade, Obsidian renders empty window and is unusable, downgrade fixed the issue. However, after the downgrade these error messages remain, Obsidian is working.
Artix Linux, i3
Node: v21.5.0
Obsidian: v1.5.3

**Comment by romner-set** [comment]
> Same? issue with Obsidian after upgrading electron from 25.9.8 to 28.1.0 version:
> 
> ```
> 2024-01-04 14:19:31 Loading main app package /usr/lib/obsidian/obsidian.asar
> Updates disabled.
> [16055:0104/171931.839009:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
> [16055:0104/171932.108530:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
> [16055:0104/171932.123955:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
> ```
> 
> After this electron upgrade, Obsidian renders empty window and is unusable, downgrade fixed the issue. However, after the downgrade these error messages remain, Obsidian is working. Artix Linux, i3 Node: v21.5.0 Obsidian: v1.5.3

Same issue here, Archlinux running Hyprland with the same package versions

**Comment by olof-nord** [comment]
```
[28615:0106/152709.150872:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[28615:0106/152714.154981:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[28615:0106/152715.385988:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
```

Same problem with Fedora 39
node v20.9.0 
electron 26.6.2
GNOME 45.2
Wayland

**Comment by kemzops** [comment]
```
[19288:0215/030558.960614:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[19288:0215/030601.607436:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[19288:0215/030601.618438:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
```

Same issue, **Arch Linux** :

- Node `v20.11.0`
- Electron `28.2.3`
- GNOME `45.4` - Wayland

---

```js
app.disableHardwareAcceleration()
``` 
Disabling `Hardware Acceleration` seem to fix the issue.

#### Safe to ignore the error ?

**Comment by ZivoMartin** [comment]
Same issue on arch

**Comment by TimoStolz** [comment]
bump

```
$ ./Logseq-linux-x64-0.10.8.AppImage 
(rsapi) init loggers
08:21:08.509 › Logseq App(0.10.8) Starting... 
08:21:08.515 › restore proxy settings {:type "system"}
08:21:08.515 › set proxy to {:type "system"}
08:21:10.365 › :electron.handler/watch-dir {:path "/home/timo/.logseq/config"}
08:21:10.376 › :electron.handler/unwatch-dir {:path "/home/timo/cloud.psychisch.fit/Nullachtvierzehn/Beratungstool"}
08:21:10.377 › :electron.handler/watch-dir {:path "/home/timo/cloud.psychisch.fit/Nullachtvierzehn/Beratungstool"}
[16357:0412/082213.145035:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[16357:0412/082219.381239:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[16357:0412/082228.608332:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
Warning: /usr/lib32/amdvlk32.so: falsche ELF-Klasse: ELFCLASS32
Warning: loader_icd_scan: Failed loading library associated with ICD JSON /usr/lib32/amdvlk32.so. Ignoring this JSON
Warning: /usr/lib32/amdvlk32.so: falsche ELF-Klasse: ELFCLASS32
```

**Comment by TimoStolz** [comment]
bump

```
$ ./Logseq-linux-x64-0.10.8.AppImage 
(rsapi) init loggers
08:21:08.509 › Logseq App(0.10.8) Starting... 
08:21:08.515 › restore proxy settings {:type "system"}
08:21:08.515 › set proxy to {:type "system"}
08:21:10.365 › :electron.handler/watch-dir {:path "/home/timo/.logseq/config"}
08:21:10.376 › :electron.handler/unwatch-dir {:path "/home/timo/cloud.psychisch.fit/Nullachtvierzehn/Beratungstool"}
08:21:10.377 › :electron.handler/watch-dir {:path "/home/timo/cloud.psychisch.fit/Nullachtvierzehn/Beratungstool"}
[16357:0412/082213.145035:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[16357:0412/082219.381239:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[16357:0412/082228.608332:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
Warning: /usr/lib32/amdvlk32.so: falsche ELF-Klasse: ELFCLASS32
Warning: loader_icd_scan: Failed loading library associated with ICD JSON /usr/lib32/amdvlk32.so. Ignoring this JSON
Warning: /usr/lib32/amdvlk32.so: falsche ELF-Klasse: ELFCLASS32
```
on a current Archlinux with Gnome and Wayland.

**Comment by pafloxy** [comment]
bump!

```@pafloxy-terminal-vin:~$ obsidian
2024-04-14 13:11:14 Loading main app package /snap/obsidian/x1/resources/obsidian.asar
2024-04-14 13:11:14 Checking for update using Github
2024-04-14 13:11:14 Success.
2024-04-14 13:11:14 Latest version is 1.5.12
2024-04-14 13:11:14 App is up to date.
Warning: disabling flag --expose_wasm due to conflicting flags
Warning: disabling flag --expose_wasm due to conflicting flags
Warning: disabling flag --expose_wasm due to conflicting flags
Warning: disabling flag --expose_wasm due to conflicting flags
[7356:0414/151117.413270:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[7356:0414/151117.425666:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[7356:0414/151117.429297:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
Segmentation fault
```

**Comment by MishaProductions** [comment]
This issue also occurs with KDE with Wayland on arch linux

**Comment by ibahnasy** [comment]
Same problem on Ubuntu 24.04 beta.
gnome-shell 46 and Wayland.

**Comment by M1xel** [comment]
I am experiencing the same Issue with: KDE+Wayland on arch linux

**Comment by SalvatoreNoschese** [comment]
> I am experiencing the same Issue with: KDE+Wayland on arch linux

Mete too (plasma Wayland in arch Linux). I reported here: https://community.localwp.com/t/local-cannot-start/42611

**Comment by halida** [comment]
Any one knows how to `disableHardwareAcceleration`?

**Comment by kemzops** [comment]
> Any one knows how to `disableHardwareAcceleration`?

@halida  https://www.electronjs.org/docs/latest/tutorial/offscreen-rendering

**Comment by nobody5050** [comment]
Bump!

ubuntu 24.04 and wayland

**Comment by AJR07** [comment]
> just add this code in bellow your main.js file app.commandLine.appendSwitch('ignore-gpu-blacklist'); app.commandLine.appendSwitch('disable-gpu'); app.commandLine.appendSwitch('disable-gpu-compositing');

```
app.commandLine.appendSwitch('ignore-gpu-blacklist');
app.commandLine.appendSwitch('disable-gpu');
app.commandLine.appendSwitch('disable-gpu-compositing');
app.disableHardwareAcceleration()
```
This solved it for me, I'm using Arch :D

**Comment by SudoNova** [comment]
> just add this code in bellow your main.js file app.commandLine.appendSwitch('ignore-gpu-blacklist'); app.commandLine.appendSwitch('disable-gpu'); app.commandLine.appendSwitch('disable-gpu-compositing');

`NODE_OPTIONS='--disable-gpu --disable-gpu-rendering'` before calling cli does the same job.

**Comment by Sophistiqq** [comment]
Just came here to look how you guys fixed the issue, disabling the hardware acceleration using app.disableHardwareAcceleration fixed it for me.

**Comment by santheipman** [comment]
For those having this problem on Google Chrome, you might try to turn off the "Use graphics acceleration when available
" in Settings>System. This works for me.

**Comment by esimkowitz** [comment]
Updated Chromium bug link: https://issues.chromium.org/issues/40246239

Seems like they closed it as stale, not sure if anyone here has enough sway to reopen it or prioritize it with them?

**Comment by ErikApption** [comment]
> The current work-arounds here are unacceptable for me, because I need GPU acceleration.

On armbian/rk3588 (orange pi 5), this seems to completely stop the video playback and GPU is vital. Playback is paused "nicely" so you can work around it but in regular chromium, this works flawlessly.

**Comment by martin-braun** [comment]
Update from my end: My views were simply not updated, because unlike on MacOS, `window.on('show',...` wouldn't be called on Linux for some reason. Bounds don't need to be adjusted in that event anyways, so things load now.

I can clearly tell it uses X with `xwayland` under Wayland, unless I do `app.commandLine.appendSwitch("ozone-platform", "wayland")` which breaks rendering as described here.

**Comment by synovva** [comment]
now how will you be able to disable hardware acceleration on vs code or we better head back to vim

**Comment by superatomic** [comment]
This issue no longer occurs on Wayland for me since I updated Fedora Linux from version 40 to 41. I hope whatever change that fixed it is applied to all other Linux distributions soon.

**Comment by synovva** [comment]
to me almost anything that uses electron like vs code or the min browser exits imediately after starting. chrome is an exception though

**Comment by superatomic** [comment]
That's unfortunate to hear. It's an infuriating bug to deal with. What Linux distribution and version are you running?

**Comment by synovva** [comment]
sorry for the late reply.I nuked my archlinux with just a simple mistake `sudo rm -r /* `  instead or `sudo rm -r ./*` but to my suprise after resinstalling my arch linux everything works fine even vscode and min browser

**Comment by oluijks** [comment]
Someone kill this botaccount

**Comment by esimkowitz** [comment]
It's obvious a lot of people are still having this issue. To avoid diluting the thread and annoying the Electron maintainers, let's focus on just upvoting comments rather than adding a bunch of comments saying the same thing. If anyone has pull with the Chromium team, seems like this needs to be addressed by them.

**Comment by znmeb** [comment]
> It's obvious a lot of people are still having this issue. To avoid diluting the thread and annoying the Electron maintainers, let's focus on just upvoting comments rather than adding a bunch of comments saying the same thing. If anyone has pull with the Chromium team, seems like this needs to be addressed by them.

I am getting this in the Arduino IDE running in an Ubuntu 24.04 container hosted by Fedora 41 Silverblue on a machine with an NVIDIA GPU. Can someone please tell me exactly which software component in this humongous stack (Arduino IDE, Elektron, Chromium, GL, Ubuntu, Fedora, NVIDIA, Wayland) is failing so I know where to send logfiles, etc.? 

I don't have the time to troubleshoot this mountain; I want a *simple* reproducible test case I can present to a specific development team. If that has already been done, please post a link so I can upvote it there. Thanks!

**Comment by gleyconJ** [comment]
Idem

Look

```
[116930:1129/200727.095382:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
[116930:1129/200729.589435:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[116930:1129/200733.954941:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
(node:116814) electron: Failed to load URL: https://h.online-metrix.net/fp/sid_fp.html;CIS3SID=48A676B3FBA655E4D783C232F518E064?org_id=y6jn8c31&session_id=664cacd8-7415-4176-a12f-6499c7836750&nonce=7aad933b8be2714e with error: ERR_CONNECTION_REFUSED
(Use `electron --trace-warnings ...` to show where the warning was created)
(node:116814) electron: Failed to load URL: https://h.online-metrix.net/fp/sid_fp.html;CIS3SID=8120951EBAE9EA2F7AD66F4EAC02191E?org_id=y6jn8c31&session_id=664cacd8-7415-4176-a12f-6499c7836750&nonce=1a74cbc835a4f622 with error: ERR_CONNECTION_REFUSED
```

**Comment by mohammadferdowsi** [comment]
Hi
I had same problem. after some digging I found that electron uses GPU acceleration by default, in some system it may cause this response. 
To solve this problem use following code in your main.js file to disable this default electron logic:

`app.disableHardwareAcceleration();

**Comment by mohammadferdowsi** [comment]
> It's obvious a lot of people are still having this issue. To avoid diluting the thread and annoying the Electron maintainers, let's focus on just upvoting comments rather than adding a bunch of comments saying the same thing. If anyone has pull with the Chromium team, seems like this needs to be addressed by them.

`app.disableHardwareAcceleration();`

**Comment by SuperPauly** [comment]
Rebooting my machine fixed this error. on Ubuntu 24 with VSCode.

**Comment by codebytere** [comment]
Closing this as it's an upstream issue that we have no control over. See [many upstream issues](https://issues.chromium.org/issues?q=%22getvsyncparametersifavailable%22%20failed)
