### ISSUE TITLE
[Bug]: Electron doesn't build with system nodejs linked against OpenSSL 3.0 as webpack uses md4

### ISSUE THREAD

**Issue by cryptomilk** [electron/electron#32952]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

16.0.9

### What operating system are you using?

Other Linux

### Operating System Version

Fedora Rawhide

### What arch are you using?

x64

### Expected Behavior

Use at least [webpack 5.61.0](https://github.com/webpack/webpack/releases/tag/v5.61.0)

### Actual Behavior

```
[  333s] FAILED: gen/electron/js2c/renderer_init.js 
[  333s] python3 ../../electron/build/npm-run.py --silent webpack -- --config /home/abuild/rpmbuild/BUILD/electron-16.0.9/electron/build/webpack/webpack.config.renderer.js --output-filename=renderer_init.js --output-path=/home/abuild/rpmbuild/BUILD/electron-16.0.9/out/Release/gen/electron/js2c --env.buildflags=/home/abuild/rpmbuild/BUILD/electron-16.0.9/out/Release/gen/electron/buildflags/buildflags.h --env.mode=production
[  333s] NPM script 'webpack' failed with code '1':
[  333s] /home/abuild/rpmbuild/BUILD/electron-16.0.9/electron/node_modules/loader-runner/lib/LoaderRunner.js:133
[  333s] 		if(isError) throw e;
[  333s] 		            ^
[  333s] 
[  333s] Error: error:0308010C:digital envelope routines::unsupported
[  333s]     at new Hash (node:internal/crypto/hash:67:19)
[  333s]     at Object.createHash (node:crypto:130:10)
[  333s]     at module.exports (/home/abuild/rpmbuild/BUILD/electron-16.0.9/electron/node_modules/webpack/lib/util/createHash.js:135:53)
[  333s]     at NormalModule._initBuildHash (/home/abuild/rpmbuild/BUILD/electron-16.0.9/electron/node_modules/webpack/lib/NormalModule.js:417:16)
[  333s]     at handleParseError (/home/abuild/rpmbuild/BUILD/electron-16.0.9/electron/node_modules/webpack/lib/NormalModule.js:471:10)
[  333s]     at /home/abuild/rpmbuild/BUILD/electron-16.0.9/electron/node_modules/webpack/lib/NormalModule.js:503:5
[  333s]     at /home/abuild/rpmbuild/BUILD/electron-16.0.9/electron/node_modules/webpack/lib/NormalModule.js:358:12
[  333s]     at /home/abuild/rpmbuild/BUILD/electron-16.0.9/electron/node_modules/loader-runner/lib/LoaderRunner.js:373:3
[  333s]     at iterateNormalLoaders (/home/abuild/rpmbuild/BUILD/electron-16.0.9/electron/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
[  333s]     at iterateNormalLoaders (/home/abuild/rpmbuild/BUILD/electron-16.0.9/electron/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
[  333s]     at /home/abuild/rpmbuild/BUILD/electron-16.0.9/electron/node_modules/loader-runner/lib/LoaderRunner.js:236:3
[  333s]     at context.callback (/home/abuild/rpmbuild/BUILD/electron-16.0.9/electron/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
[  333s]     at makeSourceMapAndFinish (/home/abuild/rpmbuild/BUILD/electron-16.0.9/electron/node_modules/ts-loader/dist/index.js:59:5)
[  333s]     at successLoader (/home/abuild/rpmbuild/BUILD/electron-16.0.9/electron/node_modules/ts-loader/dist/index.js:41:5)
[  333s]     at Object.loader (/home/abuild/rpmbuild/BUILD/electron-16.0.9/electron/node_modules/ts-loader/dist/index.js:24:5)
[  333s]     at LOADER_EXECUTION (/home/abuild/rpmbuild/BUILD/electron-16.0.9/electron/node_modules/loader-runner/lib/LoaderRunner.js:119:14)
[  333s]     at runSyncOrAsync (/home/abuild/rpmbuild/BUILD/electron-16.0.9/electron/node_modules/loader-runner/lib/LoaderRunner.js:120:4)
[  333s]     at iterateNormalLoaders (/home/abuild/rpmbuild/BUILD/electron-16.0.9/electron/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
[  333s]     at Array.<anonymous> (/home/abuild/rpmbuild/BUILD/electron-16.0.9/electron/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
[  333s]     at Storage.finished (/home/abuild/rpmbuild/BUILD/electron-16.0.9/electron/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:43:16)
[  333s]     at /home/abuild/rpmbuild/BUILD/electron-16.0.9/electron/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:79:9
[  333s]     at /home/abuild/rpmbuild/BUILD/electron-16.0.9/electron/node_modules/graceful-fs/graceful-fs.js:90:16
[  333s]     at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3) {
[  333s]   opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
[  333s]   library: 'digital envelope routines',
[  333s]   reason: 'unsupported',
[  333s]   code: 'ERR_OSSL_EVP_UNSUPPORTED'
[  333s] }
```

### Additional Information

See also https://github.com/webpack/webpack/issues/13572

**Comment by codebytere** [comment]
@cryptomilk we don't build with OpenSSL _at all_ - we use BoringSSL in its place since that's what is bundled with Chromium.

**Comment by cryptomilk** [comment]
But the system nodejs probably does or might not allow the usage of md4:

Workaround:

```diff
Index: electron-16.0.9/electron/build/webpack/webpack.config.base.js
===================================================================
--- electron-16.0.9.orig/electron/build/webpack/webpack.config.base.js  2022-02-16 16:41:24.767092075 +0100
+++ electron-16.0.9/electron/build/webpack/webpack.config.base.js   2022-02-17 11:10:51.379512377 +0100
@@ -1,5 +1,12 @@
 const fs = require('fs');
 const path = require('path');
+
+// HACK: OpenSSL 3 does not support md4 any more, but webpack hardcodes it all
+// over the place: https://github.com/webpack/webpack/issues/13572
+const crypto = require("crypto");
+const crypto_orig_createHash = crypto.createHash;
+crypto.createHash = algorithm => crypto_orig_createHash(algorithm == "md4" ? "sha256" : algorithm);
+
 const webpack = require('webpack');
 const TerserPlugin = require('terser-webpack-plugin');
 const WrapperPlugin = require('wrapper-webpack-plugin');

```

**Comment by dsanders11** [comment]
@codebytere, I believe this issue is with the build scripts using Node, and Node's usage of OpenSSL. I ran into the same error during a build on my system, which I determined was related to Node v17 being my system node. Downgrading to Node v16 made the error go away.

Re-opening this as I do think it's valid - potentially Node v17 can't be used when building Electron at the moment.

**Comment by pcjbird** [comment]
so what's the better workaround?

**Comment by pcjbird** [comment]
> But the system nodejs probably is linked against OpenSSL 3.0 or a crypto policy doesn't allow allow the usage of md4 (e.g. FIPS):
> 
> Workaround:
> 
> ```diff
> Index: electron-16.0.9/electron/build/webpack/webpack.config.base.js
> ===================================================================
> --- electron-16.0.9.orig/electron/build/webpack/webpack.config.base.js  2022-02-16 16:41:24.767092075 +0100
> +++ electron-16.0.9/electron/build/webpack/webpack.config.base.js   2022-02-17 11:10:51.379512377 +0100
> @@ -1,5 +1,12 @@
>  const fs = require('fs');
>  const path = require('path');
> +
> +// HACK: OpenSSL 3 does not support md4 any more, but webpack hardcodes it all
> +// over the place: https://github.com/webpack/webpack/issues/13572
> +const crypto = require("crypto");
> +const crypto_orig_createHash = crypto.createHash;
> +crypto.createHash = algorithm => crypto_orig_createHash(algorithm == "md4" ? "sha256" : algorithm);
> +
>  const webpack = require('webpack');
>  const TerserPlugin = require('terser-webpack-plugin');
>  const WrapperPlugin = require('wrapper-webpack-plugin');
> ```

what should I do when I use Electron?

**Comment by pcjbird** [comment]
> @cryptomilk we don't build with OpenSSL _at all_ - we use BoringSSL in its place since that's what is bundled with Chromium. It's missing a few algorithms since it's a slimmed down fork of OpenSSL, but there's really not much we can do about that.

Then how to avoid this? What's the correct way to use electron?
