### ISSUE TITLE
[Bug]:  TypeError: electron__WEBPACK_IMPORTED_MODULE_0__.app.makeSingleInstance is not a function       at Module.eval (webpack:///./src/main/index.js?:123:69)       at eval (webpack:///./src/main/index.js?:166:30)       at Module../src/main/index.js (/Users/zxj/WebstormProjects/dcs-backup-plugin/dist/electron/main.js:540:1)       at __webpack_require__ (/Users/zxj/WebstormProjects/dcs-backup-plugin/dist/electron/main.js:21:30)       at eval (webpack:///./src/main/index.dev.js?:11:1)       at Object../src/main/index.dev.js (/Users/zxj/WebstormProjects/dcs-backup-plugin/dist/electron/main.js:528:1)       at __webpack_require__ (/Users/zxj/WebstormProjects/dcs-backup-plugin/dist/electron/main.js:21:30)       at eval (webpack:///multi_./src/main/index.dev.js_./src/main/index.js?:1:1)       at Object.0 (/Users/zxj/WebstormProjects/dcs-backup-plugin/dist/electron/main.js:551:1)       at __webpack_require__ (/Users/zxj/WebstormProjects/dcs-backup-plugin/dist/electron/main.js:21:30)

### ISSUE THREAD

**Issue by zhuxiujia** [electron/electron#33270]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.1.2

### What operating system are you using?

macOS

### Operating System Version

型号名称：	MacBook Pro   型号标识符：	MacBookPro18,2   芯片：	Apple M1 Max   核总数：	10（8性能和2能效）   内存：	32 GB   系统固件版本：	7429.81.3   操作系统加载程序版本：	7429.81.3   序列号（系统）：	JXR0P7WY2Y   硬件UUID：	F8B524C1-D9F3-50C0-BA5F-8AF4378E639B   预置UDID：	00006001-001210693EF8801E   激活锁状态：	已启用

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

11

### Expected Behavior

 TypeError: electron__WEBPACK_IMPORTED_MODULE_0__.app.makeSingleInstance is not a function
      at Module.eval (webpack:///./src/main/index.js?:123:69)
      at eval (webpack:///./src/main/index.js?:166:30)
      at Module../src/main/index.js (/Users/zxj/WebstormProjects/dcs-backup-plugin/dist/electron/main.js:540:1)
      at __webpack_require__ (/Users/zxj/WebstormProjects/dcs-backup-plugin/dist/electron/main.js:21:30)
      at eval (webpack:///./src/main/index.dev.js?:11:1)
      at Object../src/main/index.dev.js (/Users/zxj/WebstormProjects/dcs-backup-plugin/dist/electron/main.js:528:1)
      at __webpack_require__ (/Users/zxj/WebstormProjects/dcs-backup-plugin/dist/electron/main.js:21:30)
      at eval (webpack:///multi_./src/main/index.dev.js_./src/main/index.js?:1:1)
      at Object.0 (/Users/zxj/WebstormProjects/dcs-backup-plugin/dist/electron/main.js:551:1)
      at __webpack_require__ (/Users/zxj/WebstormProjects/dcs-backup-plugin/dist/electron/main.js:21:30)

### Actual Behavior

Older versions of the software cannot change the API in case of upgrading electron。

I don't want to change the API code, I just want it to work with apple M1 cpus

```js
const isSecondInstance = app.makeSingleInstance((commandLine, workingDirectory) => {
  // Someone tried to run a second instance, we should focus our window.
  const cmdstr =  commandLine[1]
  doCmd(cmdstr,true)
  if (mainWindow && !executeWithArg) {
    if (mainWindow.isMinimized()) mainWindow.restore()
    mainWindow.focus()
    mainWindow.show()
  }
})

``` 

TypeError: electron__WEBPACK_IMPORTED_MODULE_0__.app.makeSingleInstance is not a function
      at Module.eval (webpack:///./src/main/index.js?:123:69)
      at eval (webpack:///./src/main/index.js?:166:30)
      at Module../src/main/index.js (/Users/zxj/WebstormProjects/dcs-backup-plugin/dist/electron/main.js:540:1)
      at __webpack_require__ (/Users/zxj/WebstormProjects/dcs-backup-plugin/dist/electron/main.js:21:30)
      at eval (webpack:///./src/main/index.dev.js?:11:1)
      at Object../src/main/index.dev.js (/Users/zxj/WebstormProjects/dcs-backup-plugin/dist/electron/main.js:528:1)
      at __webpack_require__ (/Users/zxj/WebstormProjects/dcs-backup-plugin/dist/electron/main.js:21:30)
      at eval (webpack:///multi_./src/main/index.dev.js_./src/main/index.js?:1:1)
      at Object.0 (/Users/zxj/WebstormProjects/dcs-backup-plugin/dist/electron/main.js:551:1)
      at __webpack_require__ (/Users/zxj/WebstormProjects/dcs-backup-plugin/dist/electron/main.js:21:30)

### Testcase Gist URL

http://xxxx

### Additional Information

Older versions of the software cannot change the API in case of upgrading electron。

I don't want to change the API code, I just want it to work with apple M1 cpus

**Comment by erickzhao** [comment]
This API was deprecated and eventually removed: https://www.electronjs.org/docs/latest/breaking-changes#appmakesingleinstance

If you are upgrading your Electron app to a newer version, I would recommend changing your app code to use `app.requestSingleInstanceLock` instead.
