### ISSUE TITLE
[Bug]: electron-builder fails to build macOS universal package with Electron 18.0.1

### ISSUE THREAD

**Issue by MrMYHuang** [electron/electron#33564]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18.0.1

### What operating system are you using?

macOS

### Operating System Version

macOS 12.3

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

17.3.1

### Expected Behavior

`electron-builder -m pkg --universal` generates pkg file without error.

### Actual Behavior

electron-builder fails:
```
  • electron-builder  version=22.14.13 os=20.6.0
  • loaded configuration  file=/Users/runner/work/cbetar2/cbetar2/electronBuilderConfigs/mac.json
  • rebuilding native dependencies  dependencies=libxslt-myh@0.9.13, node1-libxmljsmt-myh@1.0.5 platform=darwin arch=x64
  • packaging       platform=darwin arch=x64 electron=18.0.1 appOutDir=dist/mac-universal--x64
  • downloading     url=https://github.com/electron/electron/releases/download/v18.0.1/electron-v18.0.1-darwin-x64.zip size=82 MB parts=6
  • downloaded      url=https://github.com/electron/electron/releases/download/v18.0.1/electron-v18.0.1-darwin-x64.zip duration=1.554s
  • rebuilding native dependencies  dependencies=libxslt-myh@0.9.13, node1-libxmljsmt-myh@1.0.5 platform=darwin arch=arm64
  • packaging       platform=darwin arch=arm64 electron=18.0.1 appOutDir=dist/mac-universal--arm64
  • downloading     url=https://github.com/electron/electron/releases/download/v18.0.1/electron-v18.0.1-darwin-arm64.zip size=84 MB parts=6
  • downloaded      url=https://github.com/electron/electron/releases/download/v18.0.1/electron-v18.0.1-darwin-arm64.zip duration=2.642s
  • packaging       platform=darwin arch=universal electron=18.0.1 appOutDir=dist/mac-universal
  ⨯ Expected all non-binary files to have identical SHAs when creating a universal build but "Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/MainMenu.nib/keyedobjects-101300.nib" did not  failedTask=build stackTrace=Error: Expected all non-binary files to have identical SHAs when creating a universal build but "Contents/Frameworks/Electron Framework.framework/Versions/A/Resources/MainMenu.nib/keyedobjects-101300.nib" did not
    at exports.makeUniversalApp (/Users/runner/work/cbetar2/cbetar2/node_modules/@electron/universal/src/index.ts:107:15)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at MacPackager.doPack (/Users/runner/work/cbetar2/cbetar2/node_modules/app-builder-lib/src/macPackager.ts:125:9)
    at MacPackager.pack (/Users/runner/work/cbetar2/cbetar2/node_modules/app-builder-lib/src/macPackager.ts:177:7)
    at Packager.doBuild (/Users/runner/work/cbetar2/cbetar2/node_modules/app-builder-lib/src/packager.ts:441:9)
    at Object.executeFinally (/Users/runner/work/cbetar2/cbetar2/node_modules/builder-util/src/promise.ts:12:14)
    at Packager._build (/Users/runner/work/cbetar2/cbetar2/node_modules/app-builder-lib/src/packager.ts:376:31)
    at Packager.build (/Users/runner/work/cbetar2/cbetar2/node_modules/app-builder-lib/src/packager.ts:337:12)
    at Object.executeFinally (/Users/runner/work/cbetar2/cbetar2/node_modules/builder-util/src/promise.ts:12:14)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! cbetar2@18.0.0 dist-mac: `npm run build-electron && electron-builder -m pkg -c electronBuilderConfigs/mac.json "-p" "always" "--universal"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the cbetar2@18.0.0 dist-mac script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
Ref: https://github.com/MrMYHuang/cbetar2/runs/5767240065?check_suite_focus=true

### Additional Information

`electron-builder -m pkg --universal` works well with Electron 17.3.1.

**Comment by codebytere** [comment]
@MrMYHuang `electron-builder` is not a package maintained by this project. Please open an issue on https://github.com/electron-userland/electron-builder instead.
