### ISSUE TITLE
[Bug]: Electron Installation Issue

### ISSUE THREAD

**Issue by arslan0tahir** [electron/electron#33921]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18.0.0

### What operating system are you using?

Windows

### Operating System Version

Window 10

### What arch are you using?

x64

### Last Known Working Electron version

nil

### Expected Behavior

I am trying to install electron using npm. I am behind proxy. All proxy related setting are configure correctly but installation of electron is causing following error. Whereas rest of npm packages are installing fine.

```
npm timing build:link:node_modules/extract-zip Completed in 39ms
npm timing build:link:node_modules/mkdirp Completed in 39ms
npm timing build:link:node_modules/electron Completed in 45ms
npm timing build:link:node_modules/global-agent/node_modules/semver Completed in 39ms
npm timing build:link:node_modules/semver Completed in 40ms
npm timing build:link Completed in 52ms
npm info run electron@18.1.0 postinstall node_modules/electron node install.js
npm info run electron@18.1.0 postinstall { code: 1, signal: null }
npm timing reify:rollback:createSparse Completed in 568ms
npm timing reify:rollback:retireShallow Completed in 1ms
npm timing command:install Completed in 37705ms
npm verb stack Error: command failed
npm verb stack     at ChildProcess.<anonymous> (C:\Users\poweruser.RED\AppData\Roaming\npm\node_modules\npm\node_modules\@npmcli\promise-spawn\lib\index.js:63:27)
npm verb stack     at ChildProcess.emit (node:events:526:28)
npm verb stack     at maybeClose (node:internal/child_process:1092:16)
npm verb stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:302:5)
npm verb pkgid electron@18.1.0
npm verb cwd E:\electron\harvest
npm verb Windows_NT 10.0.17763
npm verb node v16.14.2
npm verb npm  v8.7.0
npm ERR! code 1
npm ERR! path E:\electron\harvest\node_modules\electron
npm ERR! command failed
npm ERR! command C:\Windows\system32\cmd.exe /d /s /c node install.js
npm ERR! RequestError: getaddrinfo EAI_AGAIN npm.taobao.org
npm ERR!     at ClientRequest.<anonymous> (E:\electron\harvest\node_modules\got\source\request-as-event-emitter.js:178:14)
npm ERR!     at Object.onceWrapper (node:events:646:26)
npm ERR!     at ClientRequest.emit (node:events:538:35)
npm ERR!     at ClientRequest.origin.emit (E:\electron\harvest\node_modules\@szmarczak\http-timer\source\index.js:37:11)
npm ERR!     at Socket.socketErrorListener (node:_http_client:442:9)
npm ERR!     at Socket.emit (node:events:526:28)
npm ERR!     at emitErrorNT (node:internal/streams/destroy:157:8)
npm ERR!     at emitErrorCloseNT (node:internal/streams/destroy:122:3)
npm ERR!     at processTicksAndRejections (node:internal/process/task_queues:83:21)
npm verb exit 1
npm timing npm Completed in 37993ms
npm verb unfinished npm timer reify 1651038577475
npm verb unfinished npm timer reify:build 1651038602559
npm verb unfinished npm timer build 1651038602560
npm verb unfinished npm timer build:deps 1651038602560
npm verb unfinished npm timer build:run:postinstall 1651038602626
npm verb unfinished npm timer build:run:postinstall:node_modules/electron 1651038602627
npm verb code 1

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\poweruser.RED\AppData\Local\npm-cache\_logs\2022-04-27T05_49_37_220Z-debug-0.log
```

### Actual Behavior

nil

### Additional Information

nil

**Comment by jkleinsc** [comment]
Thanks for reaching out!

The issues tracker is used for feature requests and bug reports, so you will probably have better luck with this question at one of the links at [the project's Community page](https://www.electronjs.org/community) -- in particular, be sure to give [the Electron Discord server](https://discord.com/invite/electronjs) a try.

I hope this helps!
