### ISSUE TITLE
[Bug]: No module found [dmg-builder] error while trying to build the electron app. No error in production

### ISSUE THREAD

**Issue by AyishaImran** [electron/electron#34809]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18.2.3

### What operating system are you using?

Other (specify below)

### Operating System Version

Zorin above linux debian OS

### What arch are you using?

x64

### Expected Behavior

use 'npm run electron:serve' command and build the app for production.

### Actual Behavior

In the development environment there are no errors and I am able to run the electron app properly. But while trying build the electron app using 'npm run electron:serve' app shows an error dgm-builder not found error. 
 INFO  Building app with electron-builder:
  • electron-builder  version=22.14.13 os=5.13.0-44-generic
  • description is missed in the package.json  appPackageFile=/home/ayisha/projects/office-blox-ui/dist_electron/bundled/package.json
  • author is missed in the package.json  appPackageFile=/home/ayisha/projects/office-blox-ui/dist_electron/bundled/package.json
  • writing effective config  file=dist_electron/builder-effective-config.yaml
Error: Cannot find module 'dmg-license'
Require stack:
- /home/ayisha/projects/office-blox-ui/node_modules/vue-cli-plugin-electron-builder/node_modules/dmg-builder/out/dmgLicense.js
- /home/ayisha/projects/office-blox-ui/node_modules/vue-cli-plugin-electron-builder/node_modules/dmg-builder/out/dmg.js
- /home/ayisha/projects/office-blox-ui/node_modules/vue-cli-plugin-electron-builder/node_modules/dmg-builder/out/dmgUtil.js
- /home/ayisha/projects/office-blox-ui/node_modules/vue-cli-plugin-electron-builder/node_modules/app-builder-lib/out/macPackager.js
- /home/ayisha/projects/office-blox-ui/node_modules/vue-cli-plugin-electron-builder/node_modules/app-builder-lib/out/packager.js
- /home/ayisha/projects/office-blox-ui/node_modules/vue-cli-plugin-electron-builder/node_modules/app-builder-lib/out/index.js
- /home/ayisha/projects/office-blox-ui/node_modules/vue-cli-plugin-electron-builder/node_modules/electron-builder/out/builder.js
- /home/ayisha/projects/office-blox-ui/node_modules/vue-cli-plugin-electron-builder/node_modules/electron-builder/out/index.js
- /home/ayisha/projects/office-blox-ui/node_modules/vue-cli-plugin-electron-builder/index.js
- /home/ayisha/projects/office-blox-ui/node_modules/@vue/cli-service/lib/Service.js
- /home/ayisha/projects/office-blox-ui/node_modules/@vue/cli-service/bin/vue-cli-service.js
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/ayisha/projects/office-blox-ui/node_modules/vue-cli-plugin-electron-builder/node_modules/dmg-builder/src/dmgLicense.ts:7:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/ayisha/projects/office-blox-ui/node_modules/vue-cli-plugin-electron-builder/node_modules/dmg-builder/src/dmg.ts:13:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/home/ayisha/projects/office-blox-ui/node_modules/vue-cli-plugin-electron-builder/node_modules/dmg-builder/src/dmgUtil.ts:6:1)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
    at Module.load (node:internal/modules/cjs/loader:981:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/ayisha/projects/office-blox-ui/node_modules/vue-cli-plugin-electron-builder/node_modules/dmg-builder/out/dmgLicense.js',
    '/home/ayisha/projects/office-blox-ui/node_modules/vue-cli-plugin-electron-builder/node_modules/dmg-builder/out/dmg.js',
    '/home/ayisha/projects/office-blox-ui/node_modules/vue-cli-plugin-electron-builder/node_modules/dmg-builder/out/dmgUtil.js',
    '/home/ayisha/projects/office-blox-ui/node_modules/vue-cli-plugin-electron-builder/node_modules/app-builder-lib/out/macPackager.js',
    '/home/ayisha/projects/office-blox-ui/node_modules/vue-cli-plugin-electron-builder/node_modules/app-builder-lib/out/packager.js',
    '/home/ayisha/projects/office-blox-ui/node_modules/vue-cli-plugin-electron-builder/node_modules/app-builder-lib/out/index.js',
    '/home/ayisha/projects/office-blox-ui/node_modules/vue-cli-plugin-electron-builder/node_modules/electron-builder/out/builder.js',
    '/home/ayisha/projects/office-blox-ui/node_modules/vue-cli-plugin-electron-builder/node_modules/electron-builder/out/index.js',
    '/home/ayisha/projects/office-blox-ui/node_modules/vue-cli-plugin-electron-builder/index.js',
    '/home/ayisha/projects/office-blox-ui/node_modules/@vue/cli-service/lib/Service.js',
    '/home/ayisha/projects/office-blox-ui/node_modules/@vue/cli-service/bin/vue-cli-service.js'
  ]
}

**Comment by miniak** [comment]
This should be reported to https://github.com/electron-userland/electron-builder
