### ISSUE TITLE
Windows compile electron19 source code error

### ISSUE THREAD

**Issue by Dragon-S** [electron/electron#34898]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

19.0.8

### What operating system are you using?

Windows

### Operating System Version

windows11 version 21H2

### What arch are you using?

x64

### Expected Behavior

Compiled successfully

### Actual Behavior

Compilation failed. The error is as follows

The compilation error is as follows:

```console
D:\electron\electron-19-x-y\electron\src>ninja -C out/Testing electron
ninja: Entering directory `out/Testing'
[408/42140] ACTION //electron/shell/common/extensions/api:generated_api_types_schema_generator(//build/toolchain/win:win_clang_x64)
FAILED: gen/electron/shell/common/extensions/api/cryptotoken_private.cc gen/electron/shell/common/extensions/api/cryptotoken_private.h
D:/electron/depot_tools/bootstrap-2@3_8_10_chromium_23_bin/python3/bin/python3.exe ../../tools/json_schema_compiler/compiler.py ../../electron/shell/common/extensions/api/cryptotoken_private.idl --root=../../ --destdir=gen --namespace=extensions::api::%(namespace)s --generator=cpp --include-rules=extensions/common/api:extensions::api::%(namespace)s

../../electron\shell\common\extensions\api\cryptotoken_private.idl(5) : Unexpected EoF reached after

^
'canning error. Illegal character '
Traceback (most recent call last):
  File "../../tools/json_schema_compiler/compiler.py", line 211, in <module>
    result = GenerateSchema(opts.generator, file_paths, opts.root, opts.destdir,
  File "../../tools/json_schema_compiler/compiler.py", line 98, in GenerateSchema
    type_generator = CppTypeGenerator(api_model,
  File "D:\electron\electron-19-x-y\electron\src\tools\json_schema_compiler\cpp_type_generator.py", line 35, in __init__
    self._default_namespace = list(model.namespaces.values())[0]
IndexError: list index out of range
[425/42140] ACTION //electron:build_electron_definitions(//build/toolchain/win:win_clang_x64)
ninja: build stopped: subcommand failed.
```

**Comment by taras-nagorny** [comment]
![image](https://user-images.githubusercontent.com/108521352/190239184-ee19ea63-d065-47b4-a3b3-5e56829e85b3.png)
