### ISSUE TITLE
[Bug]: crashed under linux arm64

### ISSUE THREAD

**Issue by jebiao** [electron/electron#35829]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18.x.x 19.x.x 20.x.x 21.x.x

### What operating system are you using?

Other Linux

### Operating System Version

Linux version 4.4.131-20190726.kylin.server-generic (YHKYLIN-OS@Kylin) (gcc version 9.1.0 (Ubuntu 9.1.0-2ubuntu2~16.04) )

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

21.0.0

### Expected Behavior

works fine in my environment

### Actual Behavior

I need help!!!

### System Info

- version：Linux version 4.4.131-20190726.kylin.server-generic (YHKYLIN-OS@Kylin) (gcc version 9.1.0 (Ubuntu 9.1.0-2ubuntu2~16.04) )
- cpu arch：ARM64
- page_size: 65535 (getconf PAGE_SIZE)
- desktop: yes (X11)
- other: a virtual machine running on a cloud platform

### operate log

wget electron from github, electron-v*.*.*-linux-arm64.zip

1. exec script: ./electron .
  log info: 
  > Tracing and breakpoint traps

2. exec script: gdb electron
  log info:
```sh
  root@Kylin:/data1/electron/electron20.2# gdb electron
  GNU gdb (Ubuntu 7.11.1-0kord1~16.5) 7.11.1
  Copyright (C) 2016 Free Software Foundation, Inc.
  License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
  This is free software: you are free to change and redistribute it.
  There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
  and "show warranty" for details.
  This GDB was configured as "aarch64-linux-gnu".
  Type "show configuration" for configuration details.
  For bug reporting instructions, please see:
  <http://www.gnu.org/software/gdb/bugs/>.
  Find the GDB manual and other documentation resources online at:
  <http://www.gnu.org/software/gdb/documentation/>.
  For help, type "help".
  Type "apropos word" to search for commands related to "word"...
  Reading symbols from electron...(no debugging symbols found)...done.
  (gdb) r
  Starting program: /data1/electron/electron20.2/electron 
  [Thread debugging using libthread_db enabled]
  Using host libthread_db library "/lib/aarch64-linux-gnu/libthread_db.so.1".

  > Program received signal SIGTRAP, Trace/breakpoint trap.
  0x0000aaaaacc51650 in ?? ()
  (gdb) bt
  #0  0x0000aaaaacc51650 in ?? ()
  #1  0x0000ffffb547f490 in ?? () from /usr/lib/aarch64-linux-gnu/libstdc++.so.6
  Backtrace stopped: previous frame inner to this frame (corrupt stack?)
  (gdb) 
```

3. exec script: strace ./electron
  log info:
```sh
execve("./electron", ["./electron"], [/* 21 vars */]) = 0
brk(NULL)                               = 0xaaaae84e0000
faccessat(AT_FDCWD, "/etc/ld.so.nohwcap", F_OK) = 0
mmap(NULL, 65536, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0xffff8f000000
readlinkat(AT_FDCWD, "/proc/self/exe", "/data1/electron/electron20.2/ele"..., 4096) = 37
faccessat(AT_FDCWD, "/etc/ld.so.preload", R_OK) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/data1/electron/electron20.2/libffmpeg.so", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0\267\0\1\0\0\0\0\0\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=2548912, ...}) = 0
mmap(NULL, 4931248, PROT_READ, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0xffff8eb40000
mmap(0xffff8ebd0000, 1835008, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x80000) = 0xffff8ebd0000
mmap(0xffff8ed90000, 196608, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x230000) = 0xffff8ed90000
mmap(0xffff8edc0000, 65536, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x250000) = 0xffff8edc0000
mmap(0xffff8edd0000, 2244272, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_ANONYMOUS, -1, 0) = 0xffff8edd0000
close(3)                                = 0
openat(AT_FDCWD, "/data1/electron/electron20.2/libdl.so.2", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
openat(AT_FDCWD, "/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = 3
fstat(3, {st_mode=S_IFREG|0644, st_size=80391, ...}) = 0
mmap(NULL, 80391, PROT_READ, MAP_PRIVATE, 3, 0) = 0xffff8eb20000
close(3)                                = 0
faccessat(AT_FDCWD, "/etc/ld.so.nohwcap", F_OK) = 0
openat(AT_FDCWD, "/lib/aarch64-linux-gnu/libdl.so.2", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0\267\0\1\0\0\0\320\r\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0644, st_size=10400, ...}) = 0
mmap(NULL, 73960, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0xffff8eb00000
mmap(0xffff8eb10000, 65536, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0) = 0xffff8eb10000
close(3)                                = 0
openat(AT_FDCWD, "/data1/electron/electron20.2/libpthread.so.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
faccessat(AT_FDCWD, "/etc/ld.so.nohwcap", F_OK) = 0
openat(AT_FDCWD, "/lib/aarch64-linux-gnu/libpthread.so.0", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0\267\0\1\0\0\0\350[\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0755, st_size=139536, ...}) = 0
mmap(NULL, 177040, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0xffff8ead0000
mmap(0xffff8eaf0000, 65536, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x10000) = 0xffff8eaf0000
close(3)                                = 0
```

> ... I thought it was a useless log, so I removed it

```sh
openat(AT_FDCWD, "/data1/electron/electron20.2/libboost_filesystem.so.1.58.0", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
faccessat(AT_FDCWD, "/etc/ld.so.nohwcap", F_OK) = 0
openat(AT_FDCWD, "/usr/lib/aarch64-linux-gnu/libboost_filesystem.so.1.58.0", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\0\0\0\0\0\0\0\0\0\3\0\267\0\1\0\0\0000k\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0644, st_size=97008, ...}) = 0
mmap(NULL, 160712, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0xffff8c2f0000
mmap(0xffff8c310000, 65536, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x10000) = 0xffff8c310000
close(3)                                = 0
openat(AT_FDCWD, "/data1/electron/electron20.2/libkj-0.5.3.so", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
faccessat(AT_FDCWD, "/etc/ld.so.nohwcap", F_OK) = 0
openat(AT_FDCWD, "/usr/lib/aarch64-linux-gnu/libkj-0.5.3.so", O_RDONLY|O_CLOEXEC) = 3
read(3, "\177ELF\2\1\1\3\0\0\0\0\0\0\0\0\3\0\267\0\1\0\0\0\20\325\0\0\0\0\0\0"..., 832) = 832
fstat(3, {st_mode=S_IFREG|0644, st_size=157680, ...}) = 0
mmap(NULL, 221272, PROT_READ|PROT_EXEC, MAP_PRIVATE|MAP_DENYWRITE, 3, 0) = 0xffff8c2b0000
mmap(0xffff8c2e0000, 65536, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_FIXED|MAP_DENYWRITE, 3, 0x20000) = 0xffff8c2e0000
close(3)                                = 0
mprotect(0xffff8d7b0000, 65536, PROT_READ) = 0
mprotect(0xffff8c4c0000, 65536, PROT_READ) = 0
mprotect(0xffff8c510000, 65536, PROT_READ) = 0
mprotect(0xffff8c600000, 65536, PROT_READ) = 0
mprotect(0xffff8c690000, 65536, PROT_READ) = 0
mprotect(0xffff8c720000, 65536, PROT_READ) = 0
mprotect(0xffff8d640000, 65536, PROT_READ) = 0
mprotect(0xffff8cb30000, 65536, PROT_READ) = 0
mprotect(0xffff8cd40000, 65536, PROT_READ) = 0
mprotect(0xffff8d110000, 65536, PROT_READ) = 0
mprotect(0xffff8e940000, 65536, PROT_READ) = 0
mprotect(0xffff8d310000, 65536, PROT_READ) = 0
mprotect(0xffff8e4d0000, 65536, PROT_READ) = 0
mprotect(0xffff8d480000, 65536, PROT_READ) = 0
mprotect(0xffff8e5e0000, 65536, PROT_READ) = 0
mprotect(0xffff8e460000, 65536, PROT_READ) = 0
mprotect(0xffff8e7d0000, 65536, PROT_READ) = 0
mprotect(0xffff8ed90000, 131072, PROT_READ) = 0
mprotect(0xaaaacc8f0000, 5767168, PROT_READ) = 0
munmap(0xffff8eb20000, 80391)           = 0
set_tid_address(0xffff8c557e20)         = 98478
set_robust_list(0xffff8c557e30, 24)     = 0
rt_sigaction(SIGRTMIN, {0xffff8ead5600, [], SA_SIGINFO}, NULL, 8) = 0
rt_sigaction(SIGRT_1, {0xffff8ead56e8, [], SA_RESTART|SA_SIGINFO}, NULL, 8) = 0
rt_sigprocmask(SIG_UNBLOCK, [RTMIN RT_1], NULL, 8) = 0
getrlimit(RLIMIT_STACK, {rlim_cur=8192*1024, rlim_max=RLIM64_INFINITY}) = 0
--- SIGTRAP {si_signo=SIGTRAP, si_code=TRAP_BRKPT, si_pid=3327596112, si_uid=43690} ---
+++ killed by SIGTRAP +++
```
Tracing and breakpoint traps

### Additional Information

haved try：

1. wget  electron-quick-start from github, and exec npm i & npm start
2. pack electron demo as a deb package, and install it.
3. try electron version < 18, but need page_size is 4096, my environment is 65535

other important:
it is a virtual machine running on a cloud platform, I use vnc to connect remote desktop。

**Comment by jebiao** [comment]
I wget **electron-fiddle_0.30.0_arm64.deb** from github，install it，also crash。
dbclick open electron-fiddle，no response

1. exec script: electron-fiddle
log info :
> Segmentation fault
2. exec script: gdb electron-fiddle
log info: 
> GNU gdb (Ubuntu 7.11.1-0kord1~16.5) 7.11.1
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "aarch64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from electron-fiddle...(no debugging symbols found)...done.
(gdb) r
Starting program: /usr/bin/electron-fiddle 
During startup program terminated with signal SIGSEGV, Segmentation fault.
(gdb) bt
No stack.
(gdb)  

3. exec script: strace electron-fiddle
log info:
> execve("/usr/bin/electron-fiddle", ["electron-fiddle"], [/* 20 vars */]) = -1 EINVAL (Invalid argument)
--- SIGSEGV {si_signo=SIGSEGV, si_code=SI_KERNEL, si_addr=0} ---
+++ killed by SIGSEGV +++
Segmentation fault

**Comment by ZhengXL1988** [comment]
same error, I tried to compile, but failed。Has anyone compiled the electron on arm64 and PAGESIZE=64K，give me a compiled copy，tks

**Comment by nornagon** [comment]
Please attach a crash dump. You can collect them by adding the following snippet to your main process code, before app.whenReady:

```js
const { app, crashReporter } = require('electron')

console.log(app.getPath('crashDumps'))
crashReporter.start({ submitURL: '', uploadToServer: false })
```

Then reproduce the crash, zip up the crash dumps directory and attach it here.

**Comment by yueming408892434** [comment]
Hello, I have encountered similar problems. How did you solve them

**Comment by yueming408892434** [comment]
> 
hello ,have you solve it ?

**Comment by yueming408892434** [comment]
> same error, I tried to compile, but failed。Has anyone compiled the electron on arm64 and PAGESIZE=64K，give me a compiled copy，tks

Have you solved it?
