### ISSUE TITLE
[Bug]: HTTPError: Response code 404 (Not Found) for https://github.com/electron/electron/releases/download/v21.0.1/electron-v21.0.1-openbsd-x64.zip

### ISSUE THREAD

**Issue by joyboy67** [electron/electron#35855]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

21.0.1

### What operating system are you using?

Other (specify below)

### Operating System Version

OpenBSD (7.1)

### What arch are you using?

x64

### Expected Behavior

Success install

### Actual Behavior

Fail install

### Additional Information

```
$ doas yarn global add electron
yarn global v1.22.18
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
warning Workspaces can only be enabled in private projects.
[4/4] Building fresh packages...
error /usr/local/share/.config/yarn/global/node_modules/electron: Command failed.
Exit code: 1
Command: node install.js
Arguments: 
Directory: /usr/local/share/.config/yarn/global/node_modules/electron
Output:
HTTPError: Response code 404 (Not Found) for https://github.com/electron/electron/releases/download/v21.0.1/electron-v21.0.1-openbsd-x64.zip
    at EventEmitter.<anonymous> (/usr/local/share/.config/yarn/global/node_modules/got/source/as-stream.js:35:24)
    at EventEmitter.emit (node:events:526:28)
    at module.exports (/usr/local/share/.config/yarn/global/node_modules/got/source/get-response.js:22:10)
    at ClientRequest.handleResponse (/usr/local/share/.config/yarn/global/node_modules/got/source/request-as-event-emitter.js:155:5)
    at Object.onceWrapper (node:events:646:26)
    at ClientRequest.emit (node:events:538:35)
    at ClientRequest.origin.emit (/usr/local/share/.config/yarn/global/node_modules/@szmarczak/http-timer/source/index.js:37:11)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (node:_http_client:618:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:128:17)
    at TLSSocket.socketOnData (node:_http_client:482:22)
info Visit https://yarnpkg.com/en/docs/cli/global for documentation about this command.
```

**Comment by MarshallOfSound** [comment]
`OpenBSD` is not a supported platform (this is why the asset is not present)
