### ISSUE TITLE
How to solve exec_script error when trying to build Electron?

### ISSUE THREAD

**Issue by alexivaner** [electron/electron#36125]
Hello everyone I tried to build electron using custom WebRTC using this [guide ](https://www.electronjs.org/docs/latest/development/build-instructions-gn), I already follow step by step, and it works until I run this command:

`gn gen out/Release --args="import(\"//electron/build/args/release.gn\")"
`

Error will be shown below
```
ERROR at //electron/BUILD.gn:110:20: Disallowed exec_script call.
electron_version = exec_script("script/print-version.py",
                   ^--------------------------------------
The use of exec_script use is restricted in this build. exec_script
is discouraged because it can slow down the GN run and is easily
abused.

Generally nontrivial work should be done as build steps rather than
when GN is run. For example, if you need to compute a nontrivial
preprocessor define, it will be better to have an action target
generate a header containing the define rather than blocking the GN
run to compute the value.

The allowed callers of exec_script is maintained in the "//.gn" file
if you need to modify the whitelist.
See //electron/build/args/all.gn:2:21: which caused the file to be included.
root_extra_deps = [ "//electron" ]
                    ^-----------
Traceback (most recent call last):
  File "D:/Kerja/Octon/WebRTC/electron/src/build/vs_toolchain.py", line 585, in <module>
    sys.exit(main())
  File "D:/Kerja/Octon/WebRTC/electron/src/build/vs_toolchain.py", line 581, in main
    return commands[sys.argv[1]](*sys.argv[2:])
  File "D:/Kerja/Octon/WebRTC/electron/src/build/vs_toolchain.py", line 409, in CopyDlls
    _CopyRuntime(target_dir, runtime_dir, target_cpu, debug=False)
  File "D:/Kerja/Octon/WebRTC/electron/src/build/vs_toolchain.py", line 384, in _CopyRuntime
    _CopyUCRTRuntime(target_dir, source_dir, target_cpu, suffix)
  File "D:/Kerja/Octon/WebRTC/electron/src/build/vs_toolchain.py", line 325, in _CopyUCRTRuntime
    assert len(ucrt_files) > 0
AssertionError",
```

How to solve this error? Thank you for helping

**Comment by MarshallOfSound** [comment]
You need to run `gclient sync` every time you update / pull the electron codebase as it may have contained patch changes.

**Comment by alexivaner** [comment]
Hi, I already doing `gclient sync` but the error still there.
