### ISSUE TITLE
Realm crashes Electron app when Page Reload Everytime

### ISSUE THREAD

**Issue by aarati1908** [electron/electron#36407]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

21.0.0

### What operating system are you using?

Ubuntu

### Operating System Version

 20.04.5 LTS

### What arch are you using?

x64

### Last Known Working Electron version

18.2.1

### Expected Behavior

Electron app should not crash with realm library,

### How frequently does the bug occur?

All the time

### Description

Electron app crashes with realm whenever the page reload. 

**Here's the crash report:**

19:03:17.116 › deatiling { reason: 'crashed', exitCode: 139 }
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at s.send (node:electron/js2c/browser_init:169:631)
    at g.send (node:electron/js2c/browser_init:165:2144)
    at /usr/share/nginx/html/test/ecoproddlr01-desk-app/node_modules/electron-log/src/electronApi.js:205:23
    at Array.forEach (<anonymous>)

    at sendIpcToRenderer (/usr/share/nginx/html/test/ecoproddlr01-desk-app/node_modules/electron-log/src/electronApi.js:203:42)
    at Object.sendIpc (/usr/share/nginx/html/test/ecoproddlr01-desk-app/node_modules/electron-log/src/electronApi.js:185:5)
    at transport (/usr/share/nginx/html/test/ecoproddlr01-desk-app/node_modules/electron-log/src/transports/ipc.js:40:17)
    at runTransport (/usr/share/nginx/html/test/ecoproddlr01-desk-app/node_modules/electron-log/src/log.js:44:5)
    at runTransports (/usr/share/nginx/html/test/ecoproddlr01-desk-app/node_modules/electron-log/src/log.js:27:7)
    at log (/usr/share/nginx/html/test/ecoproddlr01-desk-app/node_modules/electron-log/src/log.js:21:3)

I called realm db js at end of the page as it is required in whole over site. At first time when js included it will not crash application works perfectly but if any page reload done in electron app instanstly crashes app and relaunch application. 

So is this limitatation of realm with electron app?

Version Used:
**"realm": "^10.21.1",**
Realm version: 10.21.1(Also Try with lower version of realm 10.4.0 still crash)
Electron JS Version: 18.2.1 (Also Try with 21.0.0 still crash)
NPM version: 8.19.2
Node Version: 14.18.1

Stuck with this point as i already used realm in electron app.

### Stacktrace & log output

```shell
19:03:17.116 › deatiling { reason: 'crashed', exitCode: 139 }
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at s.send (node:electron/js2c/browser_init:169:631)
    at g.send (node:electron/js2c/browser_init:165:2144)
    at /usr/share/nginx/html/test/ecoproddlr01-desk-app/node_modules/electron-log/src/electronApi.js:205:23
    at Array.forEach (<anonymous>)
    at sendIpcToRenderer (/usr/share/nginx/html/test/ecoproddlr01-desk-app/node_modules/electron-log/src/electronApi.js:203:42)
    at Object.sendIpc (/usr/share/nginx/html/test/ecoproddlr01-desk-app/node_modules/electron-log/src/electronApi.js:185:5)
    at transport (/usr/share/nginx/html/test/ecoproddlr01-desk-app/node_modules/electron-log/src/transports/ipc.js:40:17)
    at runTransport (/usr/share/nginx/html/test/ecoproddlr01-desk-app/node_modules/electron-log/src/log.js:44:5)
    at runTransports (/usr/share/nginx/html/test/ecoproddlr01-desk-app/node_modules/electron-log/src/log.js:27:7)
    at log (/usr/share/nginx/html/test/ecoproddlr01-desk-app/node_modules/electron-log/src/log.js:21:3)
```

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

**STEPS:**

1. Launch Electron APP at first time when Realm js is not called on first page , It works fine with as realm db CRUD perform very well.

2. Without page refresh all things are working fine but If page reload in Electron app anywhere then crash occour and relaunch application then again things are workings normal and it is reproduced everytime.

3. when i remove library of realm in my electron app. Application never crash.

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [Discord](https://discord.gg/electron) that should be willing to point you in the right direction.
