### ISSUE TITLE
[Bug]: Mac sync fails for v21.3.1 running scripts/update.py

### ISSUE THREAD

**Issue by Nic0S** [electron/electron#36453]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

v21.3.1

### What operating system are you using?

macOS

### Operating System Version

macOS 12.6.1

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

v20.3.7

### Expected Behavior

"e sync" on commit with tag v21.3.1 should complete successfully.

### Actual Behavior

I'm unable to successfully sync (using electron-build-tools) on the electron v21.3.1 commit due to the following error:

```
________ running 'python3 src/tools/clang/scripts/update.py' in '/Users/nico/electron2'
Downloading https://commondatastorage.googleapis.com/chromium-browser-clang/Mac_arm64/clang-llvmorg-16-init-8697-g60809cd2-1.tar.xz .......... Done.
Traceback (most recent call last):
  File "/Users/nico/electron2/src/tools/clang/scripts/update.py", line 377, in <module>
    sys.exit(main())
  File "/Users/nico/electron2/src/tools/clang/scripts/update.py", line 373, in main
    return UpdatePackage(args.package, args.host_os)
  File "/Users/nico/electron2/src/tools/clang/scripts/update.py", line 284, in UpdatePackage
    DownloadAndUnpackPackage(package_file, LLVM_BUILD_DIR, host_os)
  File "/Users/nico/electron2/src/tools/clang/scripts/update.py", line 193, in DownloadAndUnpackPackage
    DownloadAndUnpack(cds_full_url, output_dir)
  File "/Users/nico/electron2/src/tools/clang/scripts/update.py", line 168, in DownloadAndUnpack
    t = tarfile.open(mode='r:*', fileobj=f)
  File "/Users/nico/.asdf/installs/python/3.10.2/lib/python3.10/tarfile.py", line 1620, in open
    raise ReadError(f"file could not be opened successfully:\n{error_msgs_summary}")
tarfile.ReadError: file could not be opened successfully:
- method gz: ReadError('not a gzip file')
- method bz2: ReadError('not a bzip2 file')
- method xz: CompressionError('lzma module is not available')
- method tar: ReadError('invalid header')
Error: Command 'python3 src/tools/clang/scripts/update.py' returned non-zero exit status 1 in /Users/nico/electron2
Downloading https://commondatastorage.googleapis.com/chromium-browser-clang/Mac_arm64/clang-llvmorg-16-init-8697-g60809cd2-1.tar.xz .......... Done.
Traceback (most recent call last):
  File "/Users/nico/electron2/src/tools/clang/scripts/update.py", line 377, in <module>
    sys.exit(main())
  File "/Users/nico/electron2/src/tools/clang/scripts/update.py", line 373, in main
    return UpdatePackage(args.package, args.host_os)
  File "/Users/nico/electron2/src/tools/clang/scripts/update.py", line 284, in UpdatePackage
    DownloadAndUnpackPackage(package_file, LLVM_BUILD_DIR, host_os)
  File "/Users/nico/electron2/src/tools/clang/scripts/update.py", line 193, in DownloadAndUnpackPackage
    DownloadAndUnpack(cds_full_url, output_dir)
  File "/Users/nico/electron2/src/tools/clang/scripts/update.py", line 168, in DownloadAndUnpack
    t = tarfile.open(mode='r:*', fileobj=f)
  File "/Users/nico/.asdf/installs/python/3.10.2/lib/python3.10/tarfile.py", line 1620, in open
    raise ReadError(f"file could not be opened successfully:\n{error_msgs_summary}")
tarfile.ReadError: file could not be opened successfully:
- method gz: ReadError('not a gzip file')
- method bz2: ReadError('not a bzip2 file')
- method xz: CompressionError('lzma module is not available')
- method tar: ReadError('invalid header')
```

The xz package is installed with brew. Syncing does succeed on v20.3.7, and electron build tools is up to date. Is this an issue with my local setup, or an issue with the dependencies? I've tried generating a new build config with default settings but no luck.

**Comment by MarshallOfSound** [comment]
>  Is this an issue with my local setup, or an issue with the dependencies?

It's definitely an issue with your local setup, probably something specific to your python3 version / how you installed it.  Our `21-x-y` CI is chugging along nicely and we don't do anything weird / specific with `xz` 🤷
