### ISSUE TITLE
[Bug]: `webContents.print` fails on macOS with "No printers available on the network"

### ISSUE THREAD

**Issue by SkySails** [electron/electron#36897]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.0.1

### What operating system are you using?

macOS

### Operating System Version

macOS Ventura 13.0.1

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

Calling the below:

```ts
window.webContents.print(undefined)
```

Should open a print dialog, _regardless of whether or not any printers are configured_.

### Actual Behavior

When no printers are currently configured, calling the below:

```ts
window.webContents.print(undefined, console.log)
```

Yields
```ps
false  No printers available on the network
```

While calling 

```ts
window.webContents.executeJavaScript("window.print();")
```

Yields the expected dialog:

<img src="https://user-images.githubusercontent.com/46646495/212063265-9ce0a5e4-2fb5-423b-9de8-feea0e43966e.png" width="500px">

---

While I can use the second approach, it feels like a workaround rather than a solution.

The first approach works fine on Windows 10, perhaps because there are a few default printers such as "Microsoft Print to PDF"?

### Testcase Gist URL

https://gist.github.com/8570c187ab7c976b70fd84835db5f27c

### Additional Information

Could be slightly related to https://github.com/electron/electron/issues/24664. The error is not the same, but the result is. According to comments on that issue, this is "expected behavior" - but it is also noted that it is not per spec, as other applications behave differently.

**Comment by SkySails** [comment]
This issue is still present in `v24.1.2` as well as `v25.0.0-alpha.5`.

**Comment by SkySails** [comment]
This issue is still present in `v26.0.0-beta.8`.

Additionally, it looks like `undefined` is no longer acceptable, wich contradicts the types. Pressing print (native) yields:

```
(node:17207) UnhandledPromiseRejectionWarning: Error: webContents.print(): Invalid print settings specified.
    at WebContents.print (node:electron/js2c/browser_init:2:84359)
    at /private/var/folders/4d/5942_yrx0d3_wdvtrr8l221r0000gn/T/electron-fiddle-16690-OJTXZeaRLftR/main.js:34:63
    at new Promise (<anonymous>)
    at /private/var/folders/4d/5942_yrx0d3_wdvtrr8l221r0000gn/T/electron-fiddle-16690-OJTXZeaRLftR/main.js:34:5
    at WebContents.<anonymous> (node:electron/js2c/browser_init:2:89068)
    at WebContents.emit (node:events:513:28)
```

Changing this out for an empty object restores the old behavior, with `No printers available on the network` being logged instead. The JS solution still works!

**Comment by SkySails** [comment]
This issue is still present in `v27.0.2` as well as `28.0.0-alpha.6`.

**Comment by SkySails** [comment]
This issue is still present in v28.2.0 as well as 29.0.0-beta.4.

**Comment by SkySails** [comment]
This issue is still present in v30.0.1 and 31.0.0-alpha.2

**Comment by kasvith** [comment]
im also facing this issue

**Comment by SkySails** [comment]
This issue is still present in v32.0.1 and v33.0.0-alpha.1

Pressing the "Print native" button results in the following error message:
```
Error occurred in handler for 'print-native': No printers available on the network
```

**Comment by SkySails** [comment]
This issue is still present in v33.2.0 and v34.0.0-beta.5

**Comment by Emily1799** [comment]
Still occurs in 35.0.0-beta. We had a hell of a time figuring out why this was breaking only on our tester's computer...

**Comment by pushkin-** [comment]
bump

**Comment by codebytere** [comment]
This was fixed in https://github.com/electron/electron/pull/46587
