### ISSUE TITLE
[Bug]: throw new Error No valid out directory found; use one of ${presetDirs.join(',')} or set process.env.ELECTRON_OUT_DIR

### ISSUE THREAD

**Issue by Abhijrathod** [electron/electron#36984]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

18.10.0

### What operating system are you using?

Windows

### Operating System Version

Windows 

### What arch are you using?

x64

### Expected Behavior

throw new Error(`No valid out directory found; use one of ${presetDirs.join(',')} or set process.env.ELECTRON_OUT_DIR`);

 throw new Error(`No valid out directory found; use one of ${presetDirs.join(',')} or set process.env.ELECTRON_OUT_DIR`);
  ^

Error: No valid out directory found; use one of Testing,Release,Default,Debug or set process.env.ELECTRON_OUT_DIR
    at getOutDir (C:\Users\nueon\electron\script\lib\utils.js:55:9)
    at getElectronExec (C:\Users\nueon\electron\script\lib\utils.js:14:19)
    at Object.getAbsoluteElectronExec (C:\Users\nueon\electron\script\lib\utils.js:59:32) 
    at Object.<anonymous> (C:\Users\nueon\electron\script\start.js:3:28)
    at Module._compile (node:internal/modules/cjs/loader:1149:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1203:10)
    at Module.load (node:internal/modules/cjs/loader:1027:32)
    at Module._load (node:internal/modules/cjs/loader:868:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) 
    at node:internal/main/run_main_module:23:47

### Actual Behavior

throw new Error(`No valid out directory found; use one of ${presetDirs.join(',')} or set process.env.ELECTRON_OUT_DIR`);

### Additional Information

utils.js
throw new Error(`No valid out directory found; use one of ${presetDirs.join(',')} or set process.env.ELECTRON_OUT_DIR`);
  ^

Error: No valid out directory found; use one of Testing,Release,Default,Debug or set process.env.ELECTRON_OUT_DIR
    at getOutDir (C:\Users\nueon\electron\script\lib\utils.js:55:9)
    at getElectronExec (C:\Users\nueon\electron\script\lib\utils.js:14:19)
    at Object.getAbsoluteElectronExec (C:\Users\nueon\electron\script\lib\utils.js:59:32) 
    at Object.<anonymous> (C:\Users\nueon\electron\script\start.js:3:28)
    at Module._compile (node:internal/modules/cjs/loader:1149:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1203:10)
    at Module.load (node:internal/modules/cjs/loader:1027:32)
    at Module._load (node:internal/modules/cjs/loader:868:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12) 
    at node:internal/main/run_main_module:23:47

**Comment by codebytere** [comment]
Yes, this would happen if you try to run local tests without building locally. You should follow instructions in https://github.com/electron/build-tools.

**Comment by NoelTautges** [comment]
For anyone else who already built it confused about this in the future, you have to run the tests from within `[config root]/src/electron`:

https://github.com/electron/build-tools/blob/ac4f9a9063f29baa5b356a71b8182b36889a5405/src/e-test.js#L11-L17
