### ISSUE TITLE
[Bug]: An unhandled rejection has occurred inside Forge:

### ISSUE THREAD

**Issue by dragooncjw** [electron/electron#36994]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

22.0.3

### What operating system are you using?

macOS

### Operating System Version

macOS mojave 10.14.6

### What arch are you using?

x64

### Expected Behavior

make app for macOS.

### Actual Behavior

I create my project on windows. Then I push it to github, and download it on my macOS. Then I run `yarn make`, it shows error. But it runs successfully when I run `yarn start`. And every command on windows runs successfully.
Full error info shows below:
```
An unhandled rejection has occurred inside Forge:
RequestError: read ETIMEDOUT
at ClientRequest.<anonymous> (/Users/myname/Downloads/front-end/electron/efficienza/node_modules/_got@11.8.6@got/dist/source/core/index.js:970:111)
    at Object.onceWrapper (events.js:520:26)
    at ClientRequest.emit (events.js:412:35)
    at ClientRequest.emit (domain.js:475:12)
    at ClientRequest.origin.emit (/Users/myname/Downloads/front-end/electron/efficienza/node_modules/_@szmarczak_http-timer@4.0.6@@szmarczak/http-timer/dist/source/index.js:43:20)
    at TLSSocket.socketErrorListener (_http_client.js:475:9)
    at TLSSocket.emit (events.js:400:28)
    at TLSSocket.emit (domain.js:475:12)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
    at TLSWrap.onStreamRead (internal/stream_base_commons.js:209:20)
```

### Testcase Gist URL

https://github.com/dragooncjw/efficienza

**Comment by codebytere** [comment]
Please open this issue on the Forge [repo](https://github.com/electron/forge)
