### ISSUE TITLE
[Bug]: Desktop Capturer not consistently using PipeWire on Wayland

### ISSUE THREAD

**Issue by VerteDinde** [electron/electron#37524]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

23.0.0

### What operating system are you using?

Other Linux

### Operating System Version

Ubuntu 22.04, Fedora 35

### What arch are you using?

x64

### Last Known Working Electron version

22.3.2

### Expected Behavior

Desktop capturer should consistently return capturer sources. If on Wayland, the desktop capturer should use PipeWire. If on X11, the desktop capturer should use the X11 capturer.

### Actual Behavior

WebRTC's desktop capturer API falls back to the X11 capturer even when using Wayland. PipeWire itself will occassionally segfault when trying to return sources.

### Testcase Gist URL

https://gist.github.com/6dc823943ec22be638633768df29169e

### Additional Information

Following up on a conversation in this PR (#37511), which prevents a hard crash from occurring when trying to use the desktop capturer API, but doesn't resolve the underlying Wayland problem. We should default to the PipeWire capturer if we are using Wayland.

**Comment by VerteDinde** [comment]
As a follow up: it looks like we also have a crash occurring within the PipeWire capturer itself. Taken from another issue - this symbolicated crash [wayland_crash.txt](https://github.com/electron/electron/files/10922825/wayland_crash.txt)  is crashing within `BaseCapturerPipeWire::CaptureFrame()`. 

I put in [an input check on Electron's API side when creating the capturer](https://github.com/electron/electron/pull/37511/files#diff-73f755a575b1c517f40cd8358386c43c4ffb0eff9e8a7a9ab80c5f50a248dcf4R210) to make sure we wouldn't hard crash, but it looks like the capturer has been successfully created here. So the capturer is correctly finding PipeWire, but then failing further down the line, likely when trying to refresh thumbnails 🤔 Will keep digging into this and see what's going on. (cc @vially, just in case you might be interested)

**Comment by ckerr** [comment]
@VerteDinde Fiddle won't let me load that gist; could you modify it to use an Electron version that's not 999? :smile_cat:

**Comment by VerteDinde** [comment]
@ckerr Yes, so sorry! Here's the updated gist using latest 24-beta, I also updated the link in the original description 🙂 https://gist.github.com/5c9df25094b029595e7e4fc2256568ef

**Comment by nerijus** [comment]
It seems it is affecting screen sharing in Slack.

**Comment by fan87** [comment]
bump
```
#0  0x00005638349deb12 in webrtc::BaseCapturerPipeWire::CaptureFrame() ()
#1  0x0000563837df0426 in NativeDesktopMediaList::Worker::RefreshNextThumbnail() ()
#2  0x0000563837df282e in base::internal::Invoker<base::internal::BindState<void (NativeDesktopMediaList::Worker::*)(std::vector<content::DesktopMediaID, std::allocator<content::DesktopMediaID> >, gfx::Size const&), base::internal::UnretainedWrapper<NativeDesktopMediaList::Worker, base::unretained_traits::MayNotDangle, (base::RawPtrTraits)0>, std::vector<content::DesktopMediaID, std::allocator<content::DesktopMediaID> >, gfx::Size>, void ()>::RunOnce(base::internal::BindStateBase*) ()
#3  0x000056383413abac in base::TaskAnnotator::RunTaskImpl(base::PendingTask&) ()
#4  0x0000563834151dd6 in base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWorkImpl(base::LazyNow*) ()
#5  0x00005638341517e8 in base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork() ()
#6  0x0000563834152555 in non-virtual thunk to base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::DoWork() ()
#7  0x00005638340fe9c7 in base::MessagePumpDefault::Run(base::MessagePump::Delegate*) ()
#8  0x00005638341528f7 in base::sequence_manager::internal::ThreadControllerWithMessagePumpImpl::Run(bool, base::TimeDelta) ()
#9  0x000056383411e437 in base::RunLoop::Run(base::Location const&) ()
#10 0x000056383416db77 in base::Thread::Run(base::RunLoop*) ()
#11 0x000056383416dd2e in base::Thread::ThreadMain() ()
#12 0x00005638341808ea in base::(anonymous namespace)::ThreadFunc(void*) ()
#13 0x00007f977de9d44b in start_thread (arg=<optimized out>) at pthread_create.c:444
#14 0x00007f977df20e40 in clone3 () at ../sysdeps/unix/sysv/linux/x86_64/clone3.S:81
```

**Comment by Thatoo** [comment]
It affects screen sharing in all electron app when using Wayland.
Wayland becoming by default on all major Linux OS distribution, it's becoming quiet a big issue.
