### ISSUE TITLE
[Bug]: LMDB is not working with electron

### ISSUE THREAD

**Issue by kevinrichard31** [electron/electron#37632]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

23.1.4

### What operating system are you using?

Windows

### Operating System Version

windows 10 pro

### What arch are you using?

x64

### Expected Behavior

use lmdb with require in renderer.js

### Actual Behavior

```
Uncaught Error: No native build was found for platform=win32 arch=x64 runtime=electron abi=113 uv=1 libc=glibc node=18.12.1 electron=23.1.4
    loaded from: C:\Users\kevin\Desktop\PROJECT\my-electron-app and package: @GIGATREE_core/GIGATREE_core-win32-x64

    at load.path (C:\Users\kevin\Deskt…kages\index.js:71:9)
    at Object.load [as default] (C:\Users\kevin\Deskt…ages\index.js:23:25)
    at Object.<anonymous> (C:\Users\kevin\Deskt…ist\index.cjs:44:47)
    at Object.<anonymous> (C:\Users\kevin\Deskt…st\index.cjs:2875:3)
    at Module._compile (node:internal/modules/cjs/loader:1174:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1229:10)
    at Module.load (node:internal/modules/cjs/loader:1044:32)
    at Module._load (node:internal/modules/cjs/loader:885:12)
    at f._load (node:electron/js2c/asar_bundle:2:13330)
    at o._load (node:electron/js2c/renderer_init:2:3109)
```

**Comment by jkleinsc** [comment]
Thanks for reaching out and logging this issue! Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electronjs) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.
