### ISSUE TITLE
[Bug]: Enabling context isolation causes truncated error callstacks

### ISSUE THREAD

**Issue by pushkin-** [electron/electron#37637]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

23.1.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Expected Behavior

I expect that when the preload script invokes a callback that's set by the third-party page, an error in that callback will show the full callstack.

### Actual Behavior

The actual callstack (`new Error().stack`) is:

Error
    at anotherFunction (renderer.js:7:17)
    at Function.causeError (renderer.js:2:5)

But the one logged is:

VM5:5 Uncaught Error: Cannot read properties of undefined (reading 'b')
    at EventEmitter.<anonymous> (<anonymous>:5:3)
    at EventEmitter.emit (VM4 sandbox_bundle:2:35718)
    at Object.onMessage (VM4 sandbox_bundle:2:47921)

If I disable `contextIsolation`, I get the proper callstack:

Uncaught TypeError: Cannot read properties of undefined (reading 'b')
    at anotherFunction (renderer.js:9:26)
    at causeError (renderer.js:2:5)
    at EventEmitter.<anonymous> (<anonymous>:5:3)
    at EventEmitter.emit (node:electron/js2c/sandbox_bundle:2:35718)
    at Object.onMessage (node:electron/js2c/sandbox_bundle:2:47921)

Is this an inherent limitation of context isolation, or can this be fixed?

To repro, start my gist and wait 3 seconds. See the error in the devtools.

### Testcase Gist URL

https://gist.github.com/pushkin-/ad351cbc4d83499d9e8f65fc55c17d49

**Comment by MarshallOfSound** [comment]
Unfortunately this is an intentional limitation of context isolation, we copy the error message, not the full stack
