### ISSUE TITLE
无法安装依赖

### ISSUE THREAD

**Issue by rjl-cli** [electron/electron#38338]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.0.0

### What operating system are you using?

Windows

### Operating System Version

win10

### What arch are you using?

x64

### Last Known Working Electron version

16.0.0

### Expected Behavior

正常安装和使用的

### Actual Behavior

yarn add v1.22.19
[1/4] Resolving packages...
[2/4] Fetching packages...
[3/4] Linking dependencies...
[4/4] Building fresh packages...
error C:\Users\renjiali\Desktop\模板\electron\node_modules\electron: Command failed.
Exit code: 1
Command: node install.js
Arguments:
Directory: C:\Users\renjiali\Desktop\模板\electron\node_modules\electron
Output:
HTTPError: Response code 404 (Not Found)
    at Request._onResponseBase (C:\Users\renjiali\Desktop\模板\electron\node_modules\got\dist\source\core\index.js:913:31)
    at Request._onResponse (C:\Users\renjiali\Desktop\模板\electron\node_modules\got\dist\source\core\index.js:948:24)
    at ClientRequest.<anonymous> (C:\Users\renjiali\Desktop\模板\electron\node_modules\got\dist\source\core\index.js:962:23)
    at Object.onceWrapper (node:events:628:26)
    at ClientRequest.emit (node:events:525:35)
    at origin.emit (C:\Users\renjiali\Desktop\模板\electron\node_modules\@szmarczak\http-timer\dist\source\index.js:43:20)
    at HTTPParser.parserOnIncomingClient (node:_http_client:701:27)
    at HTTPParser.parserOnHeadersComplete (node:_http_common:119:17)
    at TLSSocket.socketOnData (node:_http_client:542:22)
    at TLSSocket.emit (node:events:513:28)
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.

### Additional Information

地区中国大陆

**Comment by miniak** [comment]
Electron 17 is not supported
