### ISSUE TITLE
[Bug]: wayland config does not work

### ISSUE THREAD

**Issue by goog** [electron/electron#38942]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

25.2.0

### What operating system are you using?

Other Linux

### Operating System Version

buildroot Linux 4.19.206

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

i want to run electron demo app(electron-quick-start-main)

### Actual Behavior

i have set the wayland display, but still need x11?
```bash
[sam@ok3568:~/electron-quick-start-main]# npm start --verbose
npm info it worked if it ends with ok
npm verb cli [ '/usr/bin/node', '/usr/bin/npm', 'start', '--verbose' ]
npm info using npm@6.14.11
npm info using node@v12.21.0
npm verb run-script [ 'prestart', 'start', 'poststart' ]
npm info lifecycle electron-quick-start@1.0.0~prestart: electron-quick-start@1.0.0
npm info lifecycle electron-quick-start@1.0.0~start: electron-quick-start@1.0.0

> electron-quick-start@1.0.0 start /home/sam/electron-quick-start-main
> electron . --enable-features=UseOzonePlatform --ozone-platform=wayland

/home/sam/electron-quick-start-main/node_modules/electron/dist/electron: error while loading shared libraries: libX11.so.6: cannot open shared object file: No such file or directory
npm verb lifecycle electron-quick-start@1.0.0~start: unsafe-perm in lifecycle true
npm verb lifecycle electron-quick-start@1.0.0~start: PATH: /usr/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/sam/electron-quick-start-main/node_modules/.bin:/bin:/sbin:/usr/bin:/usr/sbin
npm verb lifecycle electron-quick-start@1.0.0~start: CWD: /home/sam/electron-quick-start-main
npm info lifecycle electron-quick-start@1.0.0~start: Failed to exec start script
npm verb stack Error: electron-quick-start@1.0.0 start: `electron . --enable-features=UseOzonePlatform --ozone-platform=wayland`
npm verb stack spawn ENOENT
npm verb stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:48:18)
npm verb stack     at ChildProcess.emit (events.js:314:20)
npm verb stack     at maybeClose (internal/child_process.js:1022:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
npm verb pkgid electron-quick-start@1.0.0
npm verb cwd /home/sam/electron-quick-start-main
npm verb Linux 4.19.206
npm verb argv "/usr/bin/node" "/usr/bin/npm" "start" "--verbose"
npm verb node v12.21.0
npm verb npm  v6.14.11
npm ERR! code ELIFECYCLE
npm ERR! syscall spawn
npm ERR! file sh
npm ERR! errno ENOENT
npm ERR! electron-quick-start@1.0.0 start: `electron . --enable-features=UseOzonePlatform --ozone-platform=wayland`
npm ERR! spawn ENOENT
npm ERR!
npm ERR! Failed at the electron-quick-start@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 1, true ]
npm timing npm Completed in 7727ms

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/sam/.npm/_logs/2023-06-28T08_44_12_373Z-debug.log

```

**Comment by jkleinsc** [comment]
Thanks for reaching out and logging this issue! Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options.

Check out the [Electron community](https://www.electronjs.org/community#boilerplates). There are also a bunch of helpful people in this [Discord](https://discord.gg/electronjs) that should be willing to point you in the right direction. For your question, I'd recommend the Discord - we have many active help channels and mentors, as well as fellow devs, who can help you out.
