### ISSUE TITLE
[Bug]: MESA-INTEL: warning

### ISSUE THREAD

**Issue by medaminefh** [electron/electron#40094]
### Electron Version

^26.2.4

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 22.04.3 LTS

### What arch are you using?

x64

### Expected Behavior

I'm learning electron, so i followed [the official doc tutorial](https://www.electronjs.org/docs/latest/tutorial/tutorial-first-app), when I reach the 1st `yarn run start` command I expect to see `Hello from Electron 👋` in the console, BUT. ...

### Actual Behavior

```bash
A JavaScript error occurred in the main process
Uncaught Exception:
TypeError: Cannot read properties of undefined (reading 'length')
    at getIssuerSpecsFromModule (/home/medaminefh/Desktop/workspace/github.com/electronic/.pnp.cjs:9535:132)
    at require$$0.Module._resolveFilename (/home/medaminefh/Desktop/workspace/github.com/electronic/.pnp.cjs:9587:93)
    at Function._resolveFilename (node:electron/js2c/browser_init:2:117419)
    at Function.<anonymous> (node:internal/modules/cjs/loader:929:27)
    at require$$0.Module._load (/home/medaminefh/Desktop/workspace/github.com/electronic/.pnp.cjs:9524:31)
    at Function._load (node:electron/js2c/asar_bundle:2:13327)
    at node:electron/js2c/browser_init:2:122552
    at node:electron/js2c/browser_init:2:122755
    at node:electron/js2c/browser_init:2:122759
    at BuiltinModule.compileForInternalLoader (node:internal/bootstrap/loaders:334:7)
MESA-INTEL: warning: Ivy Bridge Vulkan support is incomplete
libva error: vaGetDriverNameByIndex() failed with unknown libva error, driver_name = (null)
```

### Additional Information

**Node v18.17.0**

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.

Your error: `TypeError: Cannot read properties of undefined (reading 'length')` indicates an issue with the JavaScript code written and not Electron itself.
