### ISSUE TITLE
[Bug]:  Network service crashed, restarting service.

### ISSUE THREAD

**Issue by ElCoyote27** [electron/electron#40328]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

17.0.0

### What operating system are you using?

Other Linux

### Operating System Version

RHEL8 and Fedora

### What arch are you using?

x64

### Expected Behavior

In the recent weeks, several Electron Apps that I am using on Linux have started to report this error message on Linux (RHEL8):

```[2400910:1025/102533.526148:ERROR:network_service_instance_impl.cc(663)] Network service crashed, restarting service.
```
Teams for Linux, reported here: https://github.com/IsmaelMartinez/teams-for-linux/issues/998
or
```5898:ERROR:network_service_instance_impl.cc(663)] Network service crashed, restarting service.```
Standard Notes, reported here: https://github.com/standardnotes/forum/issues/3312

This causes a delay of several seconds on startup. For teams on Linux, the App does not even work anymore.

### Actual Behavior

No error should be seen and the apps should work/start fine.

### Additional Information

RHEL8 and Fedora 37 x86_64

**Comment by ElCoyote27** [comment]
The error message ( network_service_instance_impl.cc(663)] ) is the same on both Apps (Standard Notes and Teams for Linux) so I guess it's a recent change in the electron engine that caused this. Both apps started reporting that message a few weeks ago.

**Comment by ElCoyote27** [comment]
Seems similar to closed bug: https://github.com/electron/electron/issues/31675 but the line referenced in the backtrace is different (663 vs 338)

**Comment by ElCoyote27** [comment]
Interestingly, teams-for-linux works/loads on Fedora 37 just fine, no longer on RHEL8 it seems

**Comment by ElCoyote27** [comment]
RHEL9 works too (as does Fedora37).
Any reason why electron on RHEL8 stopped working recently?

**Comment by jkleinsc** [comment]
Thank you for reaching out!

The version of Electron reported in this issue has reached end-of-life and is [no longer supported](https://www.electronjs.org/docs/latest/tutorial/electron-timelines#timeline), so this issue will be closed.

If you're still experiencing this issue on a [supported version](https://www.electronjs.org/releases/stable) of Electron, please file a new issue for that version of Electron.

Thanks in advance! Your help is appreciated.

**Comment by YeesterPlus** [comment]
IT HAPPENS ON SUPPORTED!

**Comment by YeesterPlus** [comment]
version 30.0.2 node 20.11.1 chromium 124.0.6367.91
command `acellus --no-sandbox --disable-gpu-compositing --in-process-gpu --no-zygote --no-network`
logs
```
Gtk-Message: 12:36:16.841: Failed to load module "appmenu-gtk-module"
[43925:0514/123617.229589:ERROR:network_service_instance_impl.cc(599)] Network service crashed, restarting service.
```

**Comment by adminy** [comment]
Same happened to slack, 
```
slack --no-sandbox
Initializing local storage instance
(electron) Sending uncompressed crash reports is deprecated and will be removed in a future version of Electron. Set { compress: true } to opt-in to the new behavior. Crash reports will be uploaded gzipped, which most crash reporting servers support.
Gtk-Message: 09:42:56.425: Failed to load module "colorreload-gtk-module"
[07/09/24, 09:42:56:569] info:
╔══════════════════════════════════════════════╗
║      Slack 4.38.125, linux 6.9.7 on x64      ║
╚══════════════════════════════════════════════╝
[07/09/24, 09:42:56:570] info: Configured logger via
{
  "enableConsoleTransport": true,
  "identifierOverride": "webapp-service-worker-console",
  "loggerInstanceCount": 2
}
[07/09/24, 09:42:56:570] info: Predefined values for process
{
  "NODE_ENV": "production",
  "platform": "linux",
  "type": "browser",
  "timeZone": "UTC",
  "PACKAGE_MANIFEST.productName": "Slack",
  "PACKAGE_MANIFEST.version": "4.38.125",
  "PACKAGE_MANIFEST.commit": "6307452",
  "PACKAGE_MANIFEST.branch": "HEAD"
}
[55228:0709/094256.593884:ERROR:network_service_instance_impl.cc(599)] Network service crashed, restarting service.
[07/09/24, 09:42:56:679] info:
╔══════════════════════════════════════════════╗
║      Slack 4.38.125, linux 6.9.7 on x64      ║
╚══════════════════════════════════════════════╝
[07/09/24, 09:42:56:680] info: Configured logger via
{
  "enableConsoleTransport": true,
  "identifierOverride": "webapp-console",
  "loggerInstanceCount": 3
}
[07/09/24, 09:42:56:680] info: Predefined values for process
{
  "NODE_ENV": "production",
  "platform": "linux",
  "type": "browser",
  "timeZone": "UTC",
  "PACKAGE_MANIFEST.productName": "Slack",
  "PACKAGE_MANIFEST.version": "4.38.125",
  "PACKAGE_MANIFEST.commit": "6307452",
  "PACKAGE_MANIFEST.branch": "HEAD"
}
[55228:0709/094256.742152:ERROR:network_service_instance_impl.cc(599)] Network service crashed, restarting service.
[55228:0709/094256.858747:ERROR:network_service_instance_impl.cc(599)] Network service crashed, restarting service.
[55228:0709/094256.994636:ERROR:network_service_instance_impl.cc(599)] Network service crashed, restarting service.
[55228:0709/094257.120805:ERROR:network_service_instance_impl.cc(599)] Network service crashed, restarting service.
[55228:0709/094257.241826:ERROR:network_service_instance_impl.cc(599)] Network service crashed, restarting service.
[55228:0709/094257.367229:ERROR:network_service_instance_impl.cc(599)] Network service crashed, restarting service.
[55228:0709/094257.498939:ERROR:network_service_instance_impl.cc(599)] Network service crashed, restarting service.
[55228:0709/094257.641260:ERROR:network_service_instance_impl.cc(599)] Network service crashed, restarting service.
[55228:0709/094257.769622:ERROR:network_service_instance_impl.cc(599)] Network service crashed, restarting service.
[55228:0709/094257.917354:ERROR:network_service_instance_impl.cc(599)] Network service crashed, restarting service.
[55228:0709/094258.063572:ERROR:network_service_instance_impl.cc(599)] Network service crashed, restarting service.
[55228:0709/094258.191171:ERROR:network_service_instance_impl.cc(599)] Network service crashed, restarting service.
[55228:0709/094258.327474:ERROR:network_service_instance_impl.cc(599)] Network service crashed, restarting service.
[55228:0709/094258.461512:ERROR:network_service_instance_impl.cc(599)] Network service crashed, restarting service.
[55228:0709/094258.603427:ERROR:network_service_instance_impl.cc(599)] Network service crashed, restarting service.
[55228:0709/094258.760682:ERROR:network_service_instance_impl.cc(599)] Network service crashed, restarting service.
[55228:0709/094258.886647:ERROR:network_service_instance_impl.cc(599)] Network service crashed, restarting service.
[55228:0709/094259.033199:ERROR:network_service_instance_impl.cc(599)] Network service crashed, restarting service.
[55228:0709/094259.158386:ERROR:network_service_instance_impl.cc(599)] Network service crashed, restarting service.
[55228:0709/094259.280227:ERROR:network_service_instance_impl.cc(599)] Network service crashed, restarting service.
[55228:0709/094259.409244:ERROR:network_service_instance_impl.cc(599)] Network service crashed, restarting service.
[55228:0709/094259.558013:ERROR:network_service_instance_impl.cc(599)] Network service crashed, restarting service.
[55228:0709/094259.682645:ERROR:network_service_instance_impl.cc(599)] Network service crashed, restarting service.
[55228:0709/094259.819657:ERROR:network_service_instance_impl.cc(599)] Network service crashed, restarting service.
[55228:0709/094259.952564:ERROR:network_service_instance_impl.cc(599)] Network service crashed, restarting service.
[55228:0709/094300.090851:ERROR:network_service_instance_impl.cc(599)] Network service crashed, restarting service.
[55228:0709/094300.219073:ERROR:network_service_instance_impl.cc(599)] Network service crashed, restarting service.
[55228:0709/094300.353429:ERROR:network_service_instance_impl.cc(599)] Network service crashed, restarting service.
[55228:0709/094300.524033:ERROR:network_service_instance_impl.cc(599)] Network service crashed, restarting service.
[55228:0709/094300.656652:ERROR:network_service_instance_impl.cc(599)] Network service crashed, restarting service.
[55228:0709/094300.804292:ERROR:network_service_instance_impl.cc(599)] Network service crashed, restarting service.
[55228:0709/094300.922638:ERROR:network_service_instance_impl.cc(599)] Network service crashed, restarting service.
[55228:0709/094301.064355:ERROR:network_service_instance_impl.cc(599)] Network service crashed, restarting service.
[55228:0709/094301.194985:ERROR:network_service_instance_impl.cc(599)] Network service crashed, restarting service.
[55228:0709/094301.342848:ERROR:network_service_instance_impl.cc(599)] Network service crashed, restarting service.
[55228:0709/094301.477080:ERROR:network_service_instance_impl.cc(599)] Network service crashed, restarting service.
[55228:0709/094301.613679:ERROR:network_service_instance_impl.cc(599)] Network service crashed, restarting service.
^C[55228:0709/094301.627911:ERROR:network_service_instance_impl.cc(599)] Network service crashed, restarting service.

**Comment by randyg503** [comment]
Same happened to element-desktop,

```
[root@######]: /># element-desktop --no-sandbox
/root/.config/Element exists: no
/root/.config/Riot exists: no
No update_base_url is defined: auto update is disabled
Fetching translation json for locale: en_EN
Resetting the UI components after locale change
[317670:0709/114115.473003:ERROR:network_service_instance_impl.cc(599)] Network service crashed, restarting service.
[317670:0709/114115.672919:ERROR:network_service_instance_impl.cc(599)] Network service crashed, restarting service.
[317670:0709/114115.855468:ERROR:network_service_instance_impl.cc(599)] Network service crashed, restarting service.
[317670:0709/114116.060788:ERROR:network_service_instance_impl.cc(599)] Network service crashed, restarting service.
[317670:0709/114116.245188:ERROR:network_service_instance_impl.cc(599)] Network service crashed, restarting service.
[317670:0709/114116.425804:ERROR:network_service_instance_impl.cc(599)] Network service crashed, restarting service.
[317670:0709/114116.623196:ERROR:network_service_instance_impl.cc(599)] Network service crashed, restarting service.
[317670:0709/114116.826175:ERROR:network_service_instance_impl.cc(599)] Network service crashed, restarting service.
[317670:0709/114117.026556:ERROR:network_service_instance_impl.cc(599)] Network service crashed, restarting service.
[317670:0709/114117.228987:ERROR:network_service_instance_impl.cc(599)] Network service crashed, restarting service.
[317670:0709/114117.404669:ERROR:network_service_instance_impl.cc(599)] Network service crashed, restarting service.
[317670:0709/114117.608856:ERROR:network_service_instance_impl.cc(599)] Network service crashed, restarting service.
[317670:0709/114117.803559:ERROR:network_service_instance_impl.cc(599)] Network service crashed, restarting service.
[317670:0709/114118.001066:ERROR:network_service_instance_impl.cc(599)] Network service crashed, restarting service.
[317670:0709/114118.212189:ERROR:network_service_instance_impl.cc(599)] Network service crashed, restarting service.
[317670:0709/114118.428726:ERROR:network_service_instance_impl.cc(599)] Network service crashed, restarting service.
[317670:0709/114118.629871:ERROR:network_service_instance_impl.cc(599)] Network service crashed, restarting service.
[317670:0709/114118.826052:ERROR:network_service_instance_impl.cc(599)] Network service crashed, restarting service.
[317670:0709/114119.006541:ERROR:network_service_instance_impl.cc(599)] Network service crashed, restarting service.
[317670:0709/114119.203486:ERROR:network_service_instance_impl.cc(599)] Network service crashed, restarting service.
[317670:0709/114119.399347:ERROR:network_service_instance_impl.cc(599)] Network service crashed, restarting service.
[317670:0709/114119.593433:ERROR:network_service_instance_impl.cc(599)] Network service crashed, restarting service.
[317670:0709/114119.780387:ERROR:network_service_instance_impl.cc(599)] Network service crashed, restarting service.
[317670:0709/114119.986050:ERROR:network_service_instance_impl.cc(599)] Network service crashed, restarting service.
[317670:0709/114120.179377:ERROR:network_service_instance_impl.cc(599)] Network service crashed, restarting service.
[317670:0709/114120.378298:ERROR:network_service_instance_impl.cc(599)] Network service crashed, restarting service.
[317670:0709/114120.585369:ERROR:network_service_instance_impl.cc(599)] Network service crashed, restarting service.
[317670:0709/114120.789636:ERROR:network_service_instance_impl.cc(599)] Network service crashed, restarting service.
[317670:0709/114121.001322:ERROR:network_service_instance_impl.cc(599)] Network service crashed, restarting service.
[317670:0709/114121.215115:ERROR:network_service_instance_impl.cc(599)] Network service crashed, restarting service.
[317670:0709/114121.397933:ERROR:network_service_instance_impl.cc(599)] Network service crashed, restarting service.
[317670:0709/114121.594584:ERROR:network_service_instance_impl.cc(599)] Network service crashed, restarting service.
[317670:0709/114121.799077:ERROR:network_service_instance_impl.cc(599)] Network service crashed, restarting service.
[317670:0709/114122.020937:ERROR:network_service_instance_impl.cc(599)] Network service crashed, restarting service.
[317670:0709/114122.203810:ERROR:network_service_instance_impl.cc(599)] Network service crashed, restarting service.
[317670:0709/114122.397209:ERROR:network_service_instance_impl.cc(599)] Network service crashed, restarting service.
```

**Comment by adminy** [comment]
I added the extra flags:
`--no-sandbox --disable-gpu-compositing --in-process-gpu --no-zygote --no-network`
and got:
```
[8043:0821/113017.568455:ERROR:network_service_instance_impl.cc(599)] Network service crashed, restarting service.
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at s.send (node:electron/js2c/browser_init:2:88887)
    at _.send (node:electron/js2c/browser_init:2:73499)
    at /nix/store/63m2lys3yrbibqc6gb8p4jd829sxgx1x-slack-4.38.125/lib/slack/resources/app.asar/dist/main.bundle.js:248:6596
    at Array.forEach (<anonymous>)
    at /nix/store/63m2lys3yrbibqc6gb8p4jd829sxgx1x-slack-4.38.125/lib/slack/resources/app.asar/dist/main.bundle.js:248:6574
    at /nix/store/63m2lys3yrbibqc6gb8p4jd829sxgx1x-slack-4.38.125/lib/slack/resources/app.asar/dist/main.bundle.js:19:7178
    at /nix/store/63m2lys3yrbibqc6gb8p4jd829sxgx1x-slack-4.38.125/lib/slack/resources/app.asar/dist/main.bundle.js:6:22706
    at /nix/store/63m2lys3yrbibqc6gb8p4jd829sxgx1x-slack-4.38.125/lib/slack/resources/app.asar/dist/main.bundle.js:249:920
    at dispatch (/nix/store/63m2lys3yrbibqc6gb8p4jd829sxgx1x-slack-4.38.125/lib/slack/resources/app.asar/dist/main.bundle.js:6:19599)
    at Object.next (/nix/store/63m2lys3yrbibqc6gb8p4jd829sxgx1x-slack-4.38.125/lib/slack/resources/app.asar/dist/main.bundle.js:297:92081)
[8043:0821/113017.721531:ERROR:network_service_instance_impl.cc(599)] Network service crashed, restarting service.
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at s.send (node:electron/js2c/browser_init:2:88887)
    at _.send (node:electron/js2c/browser_init:2:73499)
    at /nix/store/63m2lys3yrbibqc6gb8p4jd829sxgx1x-slack-4.38.125/lib/slack/resources/app.asar/dist/main.bundle.js:248:6596
    at Array.forEach (<anonymous>)
    at /nix/store/63m2lys3yrbibqc6gb8p4jd829sxgx1x-slack-4.38.125/lib/slack/resources/app.asar/dist/main.bundle.js:248:6574
    at /nix/store/63m2lys3yrbibqc6gb8p4jd829sxgx1x-slack-4.38.125/lib/slack/resources/app.asar/dist/main.bundle.js:19:7178
    at /nix/store/63m2lys3yrbibqc6gb8p4jd829sxgx1x-slack-4.38.125/lib/slack/resources/app.asar/dist/main.bundle.js:6:22706
    at /nix/store/63m2lys3yrbibqc6gb8p4jd829sxgx1x-slack-4.38.125/lib/slack/resources/app.asar/dist/main.bundle.js:249:920
    at dispatch (/nix/store/63m2lys3yrbibqc6gb8p4jd829sxgx1x-slack-4.38.125/lib/slack/resources/app.asar/dist/main.bundle.js:6:19599)
    at Object.next (/nix/store/63m2lys3yrbibqc6gb8p4jd829sxgx1x-slack-4.38.125/lib/slack/resources/app.asar/dist/main.bundle.js:297:92081)
[8043:0821/113017.879479:ERROR:network_service_instance_impl.cc(599)] Network service crashed, restarting service.
[8043:0821/113018.023341:ERROR:network_service_instance_impl.cc(599)] Network service crashed, restarting service.
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at s.send (node:electron/js2c/browser_init:2:88887)
    at _.send (node:electron/js2c/browser_init:2:73499)
    at /nix/store/63m2lys3yrbibqc6gb8p4jd829sxgx1x-slack-4.38.125/lib/slack/resources/app.asar/dist/main.bundle.js:248:6596
    at Array.forEach (<anonymous>)
    at /nix/store/63m2lys3yrbibqc6gb8p4jd829sxgx1x-slack-4.38.125/lib/slack/resources/app.asar/dist/main.bundle.js:248:6574
    at /nix/store/63m2lys3yrbibqc6gb8p4jd829sxgx1x-slack-4.38.125/lib/slack/resources/app.asar/dist/main.bundle.js:19:7178
    at /nix/store/63m2lys3yrbibqc6gb8p4jd829sxgx1x-slack-4.38.125/lib/slack/resources/app.asar/dist/main.bundle.js:6:22706
    at /nix/store/63m2lys3yrbibqc6gb8p4jd829sxgx1x-slack-4.38.125/lib/slack/resources/app.asar/dist/main.bundle.js:249:920
    at dispatch (/nix/store/63m2lys3yrbibqc6gb8p4jd829sxgx1x-slack-4.38.125/lib/slack/resources/app.asar/dist/main.bundle.js:6:19599)
    at Object.next (/nix/store/63m2lys3yrbibqc6gb8p4jd829sxgx1x-slack-4.38.125/lib/slack/resources/app.asar/dist/main.bundle.js:297:92081)
[8043:0821/113018.174709:ERROR:network_service_instance_impl.cc(599)] Network service crashed, restarting service.
[8043:0821/113018.328825:ERROR:network_service_instance_impl.cc(599)] Network service crashed, restarting service.
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at s.send (node:electron/js2c/browser_init:2:88887)
    at _.send (node:electron/js2c/browser_init:2:73499)
    at /nix/store/63m2lys3yrbibqc6gb8p4jd829sxgx1x-slack-4.38.125/lib/slack/resources/app.asar/dist/main.bundle.js:248:6596
    at Array.forEach (<anonymous>)
    at /nix/store/63m2lys3yrbibqc6gb8p4jd829sxgx1x-slack-4.38.125/lib/slack/resources/app.asar/dist/main.bundle.js:248:6574
    at /nix/store/63m2lys3yrbibqc6gb8p4jd829sxgx1x-slack-4.38.125/lib/slack/resources/app.asar/dist/main.bundle.js:19:7178
    at /nix/store/63m2lys3yrbibqc6gb8p4jd829sxgx1x-slack-4.38.125/lib/slack/resources/app.asar/dist/main.bundle.js:6:22706
    at /nix/store/63m2lys3yrbibqc6gb8p4jd829sxgx1x-slack-4.38.125/lib/slack/resources/app.asar/dist/main.bundle.js:249:920
    at dispatch (/nix/store/63m2lys3yrbibqc6gb8p4jd829sxgx1x-slack-4.38.125/lib/slack/resources/app.asar/dist/main.bundle.js:6:19599)
    at Object.next (/nix/store/63m2lys3yrbibqc6gb8p4jd829sxgx1x-slack-4.38.125/lib/slack/resources/app.asar/dist/main.bundle.js:297:92081)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at s.send (node:electron/js2c/browser_init:2:88887)
    at _.send (node:electron/js2c/browser_init:2:73499)
    at /nix/store/63m2lys3yrbibqc6gb8p4jd829sxgx1x-slack-4.38.125/lib/slack/resources/app.asar/dist/main.bundle.js:248:6596
    at Array.forEach (<anonymous>)
    at /nix/store/63m2lys3yrbibqc6gb8p4jd829sxgx1x-slack-4.38.125/lib/slack/resources/app.asar/dist/main.bundle.js:248:6574
    at /nix/store/63m2lys3yrbibqc6gb8p4jd829sxgx1x-slack-4.38.125/lib/slack/resources/app.asar/dist/main.bundle.js:19:7178
    at /nix/store/63m2lys3yrbibqc6gb8p4jd829sxgx1x-slack-4.38.125/lib/slack/resources/app.asar/dist/main.bundle.js:6:22706
    at /nix/store/63m2lys3yrbibqc6gb8p4jd829sxgx1x-slack-4.38.125/lib/slack/resources/app.asar/dist/main.bundle.js:249:920
    at dispatch (/nix/store/63m2lys3yrbibqc6gb8p4jd829sxgx1x-slack-4.38.125/lib/slack/resources/app.asar/dist/main.bundle.js:6:19599)
    at Object.next (/nix/store/63m2lys3yrbibqc6gb8p4jd829sxgx1x-slack-4.38.125/lib/slack/resources/app.asar/dist/main.bundle.js:297:92081)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at s.send (node:electron/js2c/browser_init:2:88887)
    at _.send (node:electron/js2c/browser_init:2:73499)
    at /nix/store/63m2lys3yrbibqc6gb8p4jd829sxgx1x-slack-4.38.125/lib/slack/resources/app.asar/dist/main.bundle.js:248:6596
    at Array.forEach (<anonymous>)
    at /nix/store/63m2lys3yrbibqc6gb8p4jd829sxgx1x-slack-4.38.125/lib/slack/resources/app.asar/dist/main.bundle.js:248:6574
    at /nix/store/63m2lys3yrbibqc6gb8p4jd829sxgx1x-slack-4.38.125/lib/slack/resources/app.asar/dist/main.bundle.js:19:7178
    at /nix/store/63m2lys3yrbibqc6gb8p4jd829sxgx1x-slack-4.38.125/lib/slack/resources/app.asar/dist/main.bundle.js:6:22706
    at /nix/store/63m2lys3yrbibqc6gb8p4jd829sxgx1x-slack-4.38.125/lib/slack/resources/app.asar/dist/main.bundle.js:249:920
    at dispatch (/nix/store/63m2lys3yrbibqc6gb8p4jd829sxgx1x-slack-4.38.125/lib/slack/resources/app.asar/dist/main.bundle.js:6:19599)
    at Object.next (/nix/store/63m2lys3yrbibqc6gb8p4jd829sxgx1x-slack-4.38.125/lib/slack/resources/app.asar/dist/main.bundle.js:297:92081)
[8043:0821/113018.496064:ERROR:network_service_instance_impl.cc(599)] Network service crashed, restarting service.
```

**Comment by soleen** [comment]
I am having the same issues with the latest official google-chrome, and Ubuntu 24.04 LTS release:

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 24.04.1 LTS
Release:	24.04
Codename:	noble

$ google-chrome --version
Google Chrome 129.0.6668.89 

$ google-chrome
[2142815:2142815:1003/095944.176281:ERROR:network_service_instance_impl.cc(613)] Network service crashed, restarting service.
...
```

**Comment by tschenkelz** [comment]
I have this issue with chromium-browser on fedora 42.

```
lsb_release -a
LSB Version:    n/a
Distributor ID: Fedora
Description:    Fedora Linux 42 (KDE Plasma Desktop Edition)
Release:        42
Codename:       n/a
```
```
chromium-browser --version
Chromium 137.0.7151.119 Fedora Project
```
