### ISSUE TITLE
gclient error on Windows 11

### ISSUE THREAD

**Issue by SheikhSajid** [electron/electron#40916]
I have followed all the [build instructions](https://www.electronjs.org/docs/latest/development/build-instructions-gn) for cloning the repo, but I keep getting an error when it tries to clone the `nodejs` repo.

### Interesting bits from the error:
At first, I thought it was a network issue when I saw the following error:

```
[0:12:08] error: RPC failed; curl 18 transfer closed with outstanding read data remaining
[0:12:08] error: 3713 bytes of body are still expected
[0:12:08] fetch-pack: unexpected disconnect while reading sideband packet
[0:12:08] fatal: early EOF
[0:12:08] fatal: fetch-pack: invalid index-pack output
```
I was initially connected to WiFi. I then connected my computer to Ethernet but that did not fix the issue.

Additionally, it seems to me that it is moving the `electron_node` directory to `_bad_scm\src\third_party\`. 
```
Conflicting directory C:\Users\sheik\Code\electron\src\third_party\electron_node moved to C:\Users\sheik\Code\electron\_bad_scm\src\third_party\electron_nodei891o0e_.
```
And Immediately after that, it throws another exception, indicating that it cannot find the `electron_node` directory (I assume because it had just moved it):
```
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\sheik\\Code\\electron\\src\\third_party\\electron_node' -> 'C:\\Users\\sheik\\Code\\electron\\_bad_scm\\src\\third_party\\electron_nodei891o0e_\\electron_node'
```
### Full error:
```
[0:12:08] error: RPC failed; curl 18 transfer closed with outstanding read data remaining
[0:12:08] error: 3713 bytes of body are still expected
[0:12:08] fetch-pack: unexpected disconnect while reading sideband packet
[0:12:08] fatal: early EOF
[0:12:08] fatal: fetch-pack: invalid index-pack output
Traceback (most recent call last):
  File "C:\src\depot_tools\gclient_scm.py", line 1250, in _Clone
    self._Run(clone_cmd,
  File "C:\src\depot_tools\gclient_scm.py", line 1601, in _Run
    gclient_utils.CheckCallAndFilter(cmd, env=env, **kwargs)
  File "C:\src\depot_tools\gclient_utils.py", line 714, in CheckCallAndFilter
    raise subprocess2.CalledProcessError(rv, args, kwargs.get('cwd', None),
subprocess2.CalledProcessError: Command 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://github.com/nodejs/node.git C:\\Users\\sheik\\Code\\electron\\src\\third_party\\_gclient_electron_node_nd8ev0m7' returned non-zero exit status 128 in C:\Users\sheik\Code\electron
[0:12:12] _____ Conflicting directory found in C:\Users\sheik\Code\electron\src\third_party\electron_node. Moving to C:\Users\sheik\Code\electron\_bad_scm\src\third_party\electron_nodei891o0e_.
----------------------------------------


Warnings:
Conflicting directory C:\Users\sheik\Code\electron\src\third_party\electron_node moved to C:\Users\sheik\Code\electron\_bad_scm\src\third_party\electron_nodei891o0e_.
Traceback (most recent call last):
  File "C:\src\depot_tools\gclient_scm.py", line 706, in update
    self._Clone(revision, url, options)
  File "C:\src\depot_tools\gclient_scm.py", line 1250, in _Clone
    self._Run(clone_cmd,
  File "C:\src\depot_tools\gclient_scm.py", line 1601, in _Run
    gclient_utils.CheckCallAndFilter(cmd, env=env, **kwargs)
  File "C:\src\depot_tools\gclient_utils.py", line 714, in CheckCallAndFilter
    raise subprocess2.CalledProcessError(rv, args, kwargs.get('cwd', None),
subprocess2.CalledProcessError: Command 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://github.com/nodejs/node.git C:\\Users\\sheik\\Code\\electron\\src\\third_party\\_gclient_electron_node_nd8ev0m7' returned non-zero exit status 128 in C:\Users\sheik\Code\electron

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\sheik\.vpython-root\store\python_venv-255kl8gtil4j7etaeosorbb908\contents\lib\shutil.py", line 791, in move
    os.rename(src, real_dst)
FileNotFoundError: [WinError 2] The system cannot find the file specified: 'C:\\Users\\sheik\\Code\\electron\\src\\third_party\\electron_node' -> 'C:\\Users\\sheik\\Code\\electron\\_bad_scm\\src\\third_party\\electron_nodei891o0e_\\electron_node'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\src\depot_tools\metrics.py", line 298, in print_notice_and_exit
    yield
  File "C:\src\depot_tools\gclient.py", line 4149, in <module>
    sys.exit(main(sys.argv[1:]))
  File "C:\src\depot_tools\gclient.py", line 4135, in main
    return dispatcher.execute(OptionParser(), argv)
  File "C:\src\depot_tools\subcommand.py", line 254, in execute
    return command(parser, args[1:])
  File "C:\src\depot_tools\gclient.py", line 3526, in CMDsync
    ret = client.RunOnDeps('update', args)
  File "C:\src\depot_tools\gclient.py", line 2281, in RunOnDeps
    work_queue.flush(revision_overrides,
  File "C:\src\depot_tools\gclient_utils.py", line 1026, in flush
    reraise(e[0], e[1], e[2])
  File "C:\src\depot_tools\gclient_utils.py", line 53, in reraise
    raise value
  File "C:\src\depot_tools\gclient_utils.py", line 1105, in run
    self.item.run(*self.args, **self.kwargs)
  File "C:\src\depot_tools\gclient.py", line 1128, in run
    self._got_revision = self._used_scm.RunCommand(
  File "C:\src\depot_tools\gclient_scm.py", line 133, in RunCommand
    return getattr(self, command)(options, args, file_list)
  File "C:\src\depot_tools\gclient_scm.py", line 592, in wrapper
    return_val = f(*args)
  File "C:\src\depot_tools\gclient_scm.py", line 709, in update
    self._DeleteOrMove(options.force)
  File "C:\src\depot_tools\gclient_scm.py", line 208, in _DeleteOrMove
    shutil.move(self.checkout_path, dest_path)
  File "C:\Users\sheik\.vpython-root\store\python_venv-255kl8gtil4j7etaeosorbb908\contents\lib\shutil.py", line 811, in move
    copy_function(src, real_dst)
  File "C:\Users\sheik\.vpython-root\store\python_venv-255kl8gtil4j7etaeosorbb908\contents\lib\shutil.py", line 435, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\sheik\.vpython-root\store\python_venv-255kl8gtil4j7etaeosorbb908\contents\lib\shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc, open(dst, 'wb') as fdst:
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\sheik\\Code\\electron\\src\\third_party\\electron_node'
```

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
