### ISSUE TITLE
[Bug]: depot_tools crashes while cloning from  https://github.com/nodejs/node.git with "RPC failed; curl 18 transfer closed with outstanding read data remaining" error

### ISSUE THREAD

**Issue by ssrdop** [electron/electron#41140]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

latest version (26.01.2024 - 28.2.0)

### What operating system are you using?

Windows

### Operating System Version

Windows 10 x64

### What arch are you using?

x64

### Expected Behavior

I am trying to build my build of electron due to this docs: https://www.electronjs.org/docs/latest/development/build-instructions-gn

After running this commands:
    $ mkdir electron && cd electron
    $ gclient config --name "src/electron" --unmanaged https://github.com/electron/electron
    $ gclient sync --with_branch_heads --with_tags

i hope to get all downloads done.

### Actual Behavior

But when glient does
running 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://github.com/nodejs/node.git D:\electronproj\electronsource2\electron\src\third_party\_gclient_electron_node_ix5kpiwc' in 'D:\electronproj\electronsource2\electron' 
command ive got same error every time (for example bellow)

[6:05:22] Cloning into 'D:\electronproj\electronsource2\electron\src\third_party\_gclient_electron_node_ix5kpiwc'...
[6:05:42] remote: Enumerating objects: 926195
[6:05:42] remote: Enumerating objects: 927252, done.
[6:05:42] remote: Counting objects:   0% (1/1057)
[6:05:42] remote: Counting objects:  10% (106/1057)
[6:05:42] remote: Counting objects: 100% (1057/1057)
[6:05:42] remote: Compressing objects:   0% (1/899)
[6:05:42] remote: Compressing objects:  10% (90/899)
[6:05:42] remote: Compressing objects: 100% (899/899)
[6:05:42] Receiving objects:   0% (1/927252)
[6:05:43] Receiving objects:   0% (441/927252), 148.00 KiB | 184.00 KiB/s
[6:05:45] Receiving objects:   0% (896/927252), 644.00 KiB | 196.00 KiB/s
[6:05:47] Receiving objects:   0% (1241/927252), 964.00 KiB | 191.00 KiB/s
[6:05:48] Receiving objects:   0% (1508/927252), 1.19 MiB | 202.00 KiB/s
[6:05:49] Receiving objects:   0% (1694/927252), 1.38 MiB | 202.00 KiB/s
[6:05:51] Receiving objects:   0% (2263/927252), 1.77 MiB | 206.00 KiB/s
[6:05:52] Receiving objects:   0% (2592/927252), 2.09 MiB | 236.00 KiB/s
[6:05:53] Receiving objects:   0% (2860/927252), 2.34 MiB | 239.00 KiB/s
...
[6:35:37] Receiving objects:  53% (498748/927252), 742.82 MiB | 594.00 KiB/s
[6:35:38] Receiving objects:  53% (499051/927252), 743.42 MiB | 473.00 KiB/s
[6:35:40] Receiving objects:  53% (499205/927252), 743.63 MiB | 384.00 KiB/s
[6:35:40] fatal: early EOF
[6:35:40] fatal: The remote end hung up unexpectedly
[6:35:40] fatal: index-pack failed
[6:35:40] error: RPC failed; curl 18 transfer closed with outstanding read data remaining

and after second attempt of gclient make this command:
6:40:10] fatal: early EOF
[6:40:10] fatal: The remote end hung up unexpectedly
[6:40:10] fatal: index-pack failed
[6:40:10] error: RPC failed; curl 18 transfer closed with outstanding read data remaining
Traceback (most recent call last):
  File "D:\electronproj\depottools\depot_tools\gclient_scm.py", line 1251, in _Clone
    self._Run(clone_cmd,
  File "D:\electronproj\depottools\depot_tools\gclient_scm.py", line 1602, in _Run
    gclient_utils.CheckCallAndFilter(cmd, env=env, **kwargs)
  File "D:\electronproj\depottools\depot_tools\gclient_utils.py", line 714, in CheckCallAndFilter
    raise subprocess2.CalledProcessError(rv, args, kwargs.get('cwd', None),
subprocess2.CalledProcessError: Command 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://github.com/nodejs/node.git D:\\electronproj\\electronsource2\\electron\\src\\third_party\\_gclient_electron_node_ix5kpiwc' returned non-zero exit status 128 in D:\electronproj\electronsource2\electron
[6:40:14] _____ Conflicting directory found in D:\electronproj\electronsource2\electron\src\third_party\electron_node. Moving to D:\electronproj\electronsource2\electron\_bad_scm\src\third_party\electron_node7xbozh1c.
----------------------------------------

Warnings:
Conflicting directory D:\electronproj\electronsource2\electron\src\third_party\electron_node moved to D:\electronproj\electronsource2\electron\_bad_scm\src\third_party\electron_node7xbozh1c.
Traceback (most recent call last):
  File "D:\electronproj\depottools\depot_tools\gclient_scm.py", line 707, in update
    self._Clone(revision, url, options)
  File "D:\electronproj\depottools\depot_tools\gclient_scm.py", line 1251, in _Clone
    self._Run(clone_cmd,
  File "D:\electronproj\depottools\depot_tools\gclient_scm.py", line 1602, in _Run
    gclient_utils.CheckCallAndFilter(cmd, env=env, **kwargs)
  File "D:\electronproj\depottools\depot_tools\gclient_utils.py", line 714, in CheckCallAndFilter
    raise subprocess2.CalledProcessError(rv, args, kwargs.get('cwd', None),
subprocess2.CalledProcessError: Command 'git -c core.deltaBaseCacheLimit=2g clone --no-checkout --progress https://github.com/nodejs/node.git D:\\electronproj\\electronsource2\\electron\\src\\third_party\\_gclient_electron_node_ix5kpiwc' returned non-zero exit status 128 in D:\electronproj\electronsource2\electron

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Petr\AppData\Local\.vpython-root\store\cpython+mv51e82p8tjkom3brp6rmmfnh0\contents\bin\Lib\shutil.py", line 825, in move
    os.rename(src, real_dst)
FileNotFoundError: [WinError 2] ▒▒ ▒▒▒▒▒▒▒ ▒▒▒▒▒ ▒▒▒▒▒▒▒▒▒ ▒▒▒▒: 'D:\\electronproj\\electronsource2\\electron\\src\\third_party\\electron_node' -> 'D:\\electronproj\\electronsource2\\electron\\_bad_scm\\src\\third_party\\electron_node7xbozh1c\\electron_node'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\electronproj\depottools\depot_tools\metrics.py", line 298, in print_notice_and_exit
    yield
  File "D:\electronproj\depottools\depot_tools\gclient.py", line 4149, in <module>
    sys.exit(main(sys.argv[1:]))
             ^^^^^^^^^^^^^^^^^^
  File "D:\electronproj\depottools\depot_tools\gclient.py", line 4135, in main
    return dispatcher.execute(OptionParser(), argv)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\electronproj\depottools\depot_tools\subcommand.py", line 254, in execute
    return command(parser, args[1:])
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\electronproj\depottools\depot_tools\gclient.py", line 3526, in CMDsync
    ret = client.RunOnDeps('update', args)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\electronproj\depottools\depot_tools\gclient.py", line 2281, in RunOnDeps
    work_queue.flush(revision_overrides,
  File "D:\electronproj\depottools\depot_tools\gclient_utils.py", line 1026, in flush
    reraise(e[0], e[1], e[2])
  File "D:\electronproj\depottools\depot_tools\gclient_utils.py", line 53, in reraise
    raise value
  File "D:\electronproj\depottools\depot_tools\gclient_utils.py", line 1105, in run
    self.item.run(*self.args, **self.kwargs)
  File "D:\electronproj\depottools\depot_tools\gclient.py", line 1128, in run
    self._got_revision = self._used_scm.RunCommand(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\electronproj\depottools\depot_tools\gclient_scm.py", line 133, in RunCommand
    return getattr(self, command)(options, args, file_list)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\electronproj\depottools\depot_tools\gclient_scm.py", line 593, in wrapper
    return_val = f(*args)
                 ^^^^^^^^
  File "D:\electronproj\depottools\depot_tools\gclient_scm.py", line 710, in update
    self._DeleteOrMove(options.force)
  File "D:\electronproj\depottools\depot_tools\gclient_scm.py", line 208, in _DeleteOrMove
    shutil.move(self.checkout_path, dest_path)
  File "C:\Users\Petr\AppData\Local\.vpython-root\store\cpython+mv51e82p8tjkom3brp6rmmfnh0\contents\bin\Lib\shutil.py", line 845, in move
    copy_function(src, real_dst)
  File "C:\Users\Petr\AppData\Local\.vpython-root\store\cpython+mv51e82p8tjkom3brp6rmmfnh0\contents\bin\Lib\shutil.py", line 436, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "C:\Users\Petr\AppData\Local\.vpython-root\store\cpython+mv51e82p8tjkom3brp6rmmfnh0\contents\bin\Lib\shutil.py", line 256, in copyfile
    with open(src, 'rb') as fsrc:
         ^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'D:\\electronproj\\electronsource2\\electron\\src\\third_party\\electron_node'

So i tried to run "gclient sync --with_branch_heads --with_tags" many times on different machines. Same errors while trying to clone electron node. My network is ok, i dont use any vpn. i tried to change git configs:

    git config --global http.postBuffer 524288000
    
    git config --global http.maxRequestBuffer 524288000
    
    git config --global core.compression 0

but id doesnot help at all.

Whats the problem? 

Whole log file attached
[full_log.txt](https://github.com/electron/electron/files/14065030/full_log.txt)

### Additional Information

I did all docs of depot_tools and electron build require, like system variables and etc.

**Comment by ckerr** [comment]
Most likely answer is that there was a server outage. I would wait awhile and try again.

The Electron project doesn't control those servers, so I'm going to close this ticket for now. If the outage persists, we'll report it upstream to the Chromium folks.

**Comment by ssrdop** [comment]
> Most likely answer is that there was a server outage. I would wait awhile and try again.
> 
> The Electron project doesn't control those servers, so I'm going to close this ticket for now. If the outage persists, we'll report it upstream to the Chromium folks.

Hey i dont this its server problems. Because i can run command manually.
