### ISSUE TITLE
[Bug]: Electron 28 : error with canvas library - macOS

### ISSUE THREAD

**Issue by jarnault** [electron/electron#41200]
Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

Electron Version
^28.0.0

What operating system are you using?
macOS

Operating System Version
macOS  Version 14.2.1 (23C71)

What arch are you using?
Apple M1 Max

Last Known Working Electron version
last v27

Expected Behavior
Preparing native dependencies Success

Actual Behavior
```
✖ Preparing native dependencies: 0 / 1
  › node-gyp failed to rebuild '***/node_modules/canvas'.
    For more information, rerun with the DEBUG environment variable set to "electron-rebuild".
    Error: `make` failed with exit code: 2
```

Testcase Gist URL

Additional Information
I'm trying to upgrade from Electron 27 to Electron 28.
After that, compiling works fine (`tsc -p src/electron --outDir dist`)
But starting Electron app fails (using `electron-forge start`)
Version:
- Electron: ^v28.0.0
- @electron-forge/* : 7.2.0
- canvas: 2.11.2

Complete error
```
Preparing native dependencies: 0 / 1
  › node-gyp failed to rebuild '***/node_modules/canvas'.
    For more information, rerun with the DEBUG environment variable set to "electron-rebuild".
    Error: `make` failed with exit code: 2
◼ Running generateAssets hook

›   SOLINK_MODULE(target) Release/canvas-postbuild.node
›   CXX(target) Release/obj.target/canvas/src/backend/Backend.o
› In file included from ../src/backend/Backend.cc:1:
  In file included from ../src/backend/Backend.h:6:
  ../../nan/nan.h:686:39: warning: 'IdleNotificationDeadline' is deprecated: Use MemoryPressureNotification() to influence the GC schedule. [-Wdeprecated-declarations]
›     return v8::Isolate::GetCurrent()->IdleNotificationDeadline(
  ^
  ***.electron-gyp/28.2.0/include/node/v8-isolate.h:1343:3: note: 'IdleNotificationDeadline' has been explicitly marked deprecated here
  V8_DEPRECATE_SOON(
  ^
 ***/.electron-gyp/28.2.0/include/node/v8config.h:561:41: note: expanded from macro 'V8_DEPRECATE_SOON'
  #   define V8_DEPRECATE_SOON(message) [[deprecated(message)]]
  ^
› In file included from ../src/backend/Backend.cc:1:
  In file included from ../src/backend/Backend.h:6:
  In file included from ../../nan/nan.h:60:
  In file included from ***/.electron-gyp/28.2.0/include/node/node.h:79:
  In file included from ***/.electron-gyp/28.2.0/include/node/v8.h:24:
› In file included from ***.electron-gyp/28.2.0/include/node/v8-array-buffer.h:12:
  ***.electron-gyp/28.2.0/include/node/v8-local-handle.h:261:5: error: static assertion failed due to requirement 'std::is_base_of<v8::Value, v8::Data>::value': …
  static_assert(std::is_base_of<T, S>::value, "type check");
  ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  ../../nan/nan_callbacks_12_inl.h:175:20: note: in instantiation of function template specialization 'v8::Local<v8::Value>::Local<v8::Data>' requested here
  cbinfo(info, obj->GetInternalField(kDataIndex));
  ^
› In file included from ../src/backend/Backend.cc:1:
  ../src/backend/Backend.h:
› 60:14: warning: private field 'backend' is not used [-Wunused-private-field]
  Backend* backend;
  ^
› 2 warnings and 1 error generated.
› make: *** [Release/obj.target/canvas/src/backend/Backend.o] Error 1

An unhandled rejection has occurred inside Forge:
Error: node-gyp failed to rebuild '***/node_modules/canvas'.
For more information, rerun with the DEBUG environment variable set to "electron-rebuild".

Error: `make` failed with exit code: 2
at NodeGyp.rebuildModule (***/node_modules/@electron/rebuild/lib/src/module-type/node-gyp.js:120:19)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async ModuleRebuilder.rebuildNodeGypModule (***/node_modules/@electron/rebuild/lib/src/module-rebuilder.js:98:9)
    at async ModuleRebuilder.rebuild (***/node_modules/@electron/rebuild/lib/src/module-rebuilder.js:128:14)
    at async Rebuilder.rebuildModuleAt (***/node_modules/@electron/rebuild/lib/src/rebuild.js:149:13)
    at async Rebuilder.rebuild (***/node_modules/@electron/rebuild/lib/src/rebuild.js:112:17)
```

**Comment by miniak** [comment]
This needs to be reported to NaN, it's not an Electron issue
