### ISSUE TITLE
[Bug]: error when setting resourcesPath attribute in process object in version 28.2.1

### ISSUE THREAD

**Issue by juanmacaballeror** [electron/electron#41285]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

28.2.1

### What operating system are you using?

Windows

### Operating System Version

Windows 10

### What arch are you using?

x64

### Last Known Working Electron version

28.2.0

### Expected Behavior

In the previous version, 28.2.0, you could set and modify the value of the resourcesPath attribute of the process. 

In version 28.2.0, I can do this;

setResourcesPath(app.isPackaged);

export const setResourcesPath = packaged => {
  if (!packaged) {
    process['resourcesPath'] = join(__dirname, '../resources');
    return process['resourcesPath'];
  } else return null;
};

### Actual Behavior

In version 28.2.1, error occurs;

TypeError: Cannot assign to read only property 'resourcesPath' of object '#<process>'
    at setResourcesPath (C:\Users\juan.caballero\Documents\fuentes\mtm-electron\dist\index.cjs:381:30)
    at startup (C:\Users\juan.caballero\Documents\fuentes\mtm-electron\dist\index.cjs:389:5)
    at Module.<anonymous> (C:\Users\juan.caballero\Documents\fuentes\mtm-electron\dist\index.cjs:403:1)
    at Module._compile (node:internal/modules/cjs/loader:1271:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1326:10)
    at Module.load (node:internal/modules/cjs/loader:1126:32)
    at Module._load (node:internal/modules/cjs/loader:967:12)
    at c._load (node:electron/js2c/node_init:2:13672)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/translators:169:29)
    at ModuleJob.run (node:internal/modules/esm/module_job:194:25)

**Comment by codebytere** [comment]
That's intended behavior consequent to https://github.com/electron/electron/pull/41114 - your being able to do that before was arguably a bug as it was designated read only in documentation cc @zcbenz
