### ISSUE TITLE
[Bug]: arm64 strip-binaries.py "Unable to recognise the format of the input file chrome_crashpad_handler"

### ISSUE THREAD

**Issue by theogravity** [electron/electron#41418]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

28.0.0

### What operating system are you using?

Ubuntu

### Operating System Version

Linux ip-xxx-xx-x-xx 6.2.0-1018-aws #18~22.04.1-Ubuntu SMP Wed Jan 10 22:54:16 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

### What arch are you using?

arm64 (including Apple Silicon)

### Expected Behavior

Executing `script/strip-binaries.py -d out/arm64` should strip the debug symbols out

### Actual Behavior

```
./electron/script/strip-binaries.py -d out/arm64
b"strip: Unable to recognise the format of the input file `out/arm64/chrome_crashpad_handler'\n"
Traceback (most recent call last):
  File "/home/ubuntu/electron-project/electron/src/./electron/script/strip-binaries.py", line 56, in <module>
    sys.exit(main())
  File "/home/ubuntu/electron-project/electron/src/./electron/script/strip-binaries.py", line 34, in main
    strip_binaries(args.directory, args.target_cpu)
  File "/home/ubuntu/electron-project/electron/src/./electron/script/strip-binaries.py", line 14, in strip_binaries
    strip_binary(binary_path, target_cpu)
  File "/home/ubuntu/electron-project/electron/src/./electron/script/strip-binaries.py", line 23, in strip_binary
    execute([
  File "/home/ubuntu/electron-project/electron/src/electron/script/lib/util.py", line 129, in execute
    raise e
  File "/home/ubuntu/electron-project/electron/src/electron/script/lib/util.py", line 122, in execute
    output = subprocess.check_output(argv, stderr=subprocess.STDOUT,
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['strip', '--discard-all', '--strip-debug', '--preserve-dates', 'out/arm64/chrome_crashpad_handler']' returned non-zero exit status 1.
```

### Additional Information

Used electron build tools with the following config:

```
e init --root=/home/ubuntu/electron-project/electron -f  --target-cpu=arm64 -i release --reclient=none config-arm64
e sync
cd electron
./src/build/linux/sysroot_scripts/install-sysroot.py --arch=arm64
sed -i 's/"custom_vars": {},/"custom_vars": { "checkout_arm": True, "checkout_arm64": True },/g' ./.gclient
e build --no-remote
./script/strip-binaries.py -d out/Release
```

**Comment by jkleinsc** [comment]
@theogravity you need to pass in the arch to strip-binaries:,
eg `./script/strip-binaries.py -d out/Release --target-cpu arm64`
