### ISSUE TITLE
[Bug]: Instalation error

### ISSUE THREAD

**Issue by dr-comeemeememem** [electron/electron#42278]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

30.0.8

### What operating system are you using?

Ubuntu

### Operating System Version

Ubuntu 22.04.1

### What arch are you using?

x64

### Expected Behavior

i expected it to complete installation
i also tried the beta and nightly version

### Actual Behavior

the installation resulted on an error 

### Additional Information

<pre><font color="#26A269"><b>owend@owend-Inspiron-580</b></font>:<font color="#12488B"><b>~</b></font>$ sudo npm install electron
<span style="background-color:#171421"><font color="#D0CFCC">npm</font></span> <span style="background-color:#171421"><font color="#C01C28">ERR!</font></span> <font color="#A347BA">code</font> 1
<span style="background-color:#171421"><font color="#D0CFCC">npm</font></span> <span style="background-color:#171421"><font color="#C01C28">ERR!</font></span> <font color="#A347BA">path</font> /home/owend/node_modules/electron
<span style="background-color:#171421"><font color="#D0CFCC">npm</font></span> <span style="background-color:#171421"><font color="#C01C28">ERR!</font></span> command failed
<span style="background-color:#171421"><font color="#D0CFCC">npm</font></span> <span style="background-color:#171421"><font color="#C01C28">ERR!</font></span> <font color="#A347BA">command</font> sh -c node install.js
<span style="background-color:#171421"><font color="#D0CFCC">npm</font></span> <span style="background-color:#171421"><font color="#C01C28">ERR!</font></span> /home/owend/node_modules/electron/install.js:45
<span style="background-color:#171421"><font color="#D0CFCC">npm</font></span> <span style="background-color:#171421"><font color="#C01C28">ERR!</font></span>   checksums: process.env.electron_use_remote_checksums ?? process.env.npm_config_electron_use_remote_checksums ? undefined : require(&apos;./checksums.json&apos;),
<span style="background-color:#171421"><font color="#D0CFCC">npm</font></span> <span style="background-color:#171421"><font color="#C01C28">ERR!</font></span>                                                         ^
<span style="background-color:#171421"><font color="#D0CFCC">npm</font></span> <span style="background-color:#171421"><font color="#C01C28">ERR!</font></span> 
<span style="background-color:#171421"><font color="#D0CFCC">npm</font></span> <span style="background-color:#171421"><font color="#C01C28">ERR!</font></span> SyntaxError: Unexpected token &apos;?&apos;
<span style="background-color:#171421"><font color="#D0CFCC">npm</font></span> <span style="background-color:#171421"><font color="#C01C28">ERR!</font></span>     at wrapSafe (internal/modules/cjs/loader.js:915:16)
<span style="background-color:#171421"><font color="#D0CFCC">npm</font></span> <span style="background-color:#171421"><font color="#C01C28">ERR!</font></span>     at Module._compile (internal/modules/cjs/loader.js:963:27)
<span style="background-color:#171421"><font color="#D0CFCC">npm</font></span> <span style="background-color:#171421"><font color="#C01C28">ERR!</font></span>     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
<span style="background-color:#171421"><font color="#D0CFCC">npm</font></span> <span style="background-color:#171421"><font color="#C01C28">ERR!</font></span>     at Module.load (internal/modules/cjs/loader.js:863:32)
<span style="background-color:#171421"><font color="#D0CFCC">npm</font></span> <span style="background-color:#171421"><font color="#C01C28">ERR!</font></span>     at Function.Module._load (internal/modules/cjs/loader.js:708:14)
<span style="background-color:#171421"><font color="#D0CFCC">npm</font></span> <span style="background-color:#171421"><font color="#C01C28">ERR!</font></span>     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
<span style="background-color:#171421"><font color="#D0CFCC">npm</font></span> <span style="background-color:#171421"><font color="#C01C28">ERR!</font></span>     at internal/main/run_main_module.js:17:47
</pre>

**Comment by babylard** [comment]
> Thanks for reaching out!
> 
> Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.

How helpful.

**Comment by karlpokus** [comment]
Bumping nodejs worked for me https://github.com/nodesource/distributions/blob/master/README.md

**Comment by karlpokus** [comment]
@codebytere If you add nodejs version to the issue checklist it might be easier to triage issues like this.

**Comment by ckerr** [comment]
Potentially resolved by electron/electron#48634, which removes the nullish coalescing operator for an unrelated reason
