### ISSUE TITLE
[Bug]: Error in post installation script

### ISSUE THREAD

**Issue by diehard2** [electron/electron#42289]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

30.0.8

### What operating system are you using?

Windows

### Operating System Version

Windows 11

### What arch are you using?

x64

### Expected Behavior

installation succeeds without error

### Actual Behavior

Installation fails with

```
npm info lifecycle @types/cacheable-request@6.0.3~postinstall: @types/cacheable-request@6.0.3
npm info lifecycle @types/yauzl@2.10.3~postinstall: @types/yauzl@2.10.3
npm info lifecycle universalify@0.1.2~postinstall: universalify@0.1.2
npm info lifecycle fs-extra@8.1.0~postinstall: fs-extra@8.1.0
npm info lifecycle wrappy@1.0.2~postinstall: wrappy@1.0.2
npm info lifecycle once@1.4.0~postinstall: once@1.4.0
npm info lifecycle end-of-stream@1.4.4~postinstall: end-of-stream@1.4.4
npm info lifecycle pump@3.0.0~postinstall: pump@3.0.0
npm info lifecycle get-stream@5.2.0~postinstall: get-stream@5.2.0
npm info lifecycle cacheable-request@7.0.4~postinstall: cacheable-request@7.0.4
npm info lifecycle got@11.8.6~postinstall: got@11.8.6
npm info lifecycle yauzl@2.10.0~postinstall: yauzl@2.10.0
npm info lifecycle @electron/get@2.0.3~postinstall: @electron/get@2.0.3
npm info lifecycle extract-zip@2.0.1~postinstall: extract-zip@2.0.1
npm info lifecycle electron@30.0.8~postinstall: electron@30.0.8

> electron@30.0.8 postinstall C:\Users\Stephen\Development\Electron\node_modules\electron
> node install.js

C:\Users\Stephen\Development\Electron\node_modules\electron\install.js:34
  } catch {
          ^

SyntaxError: Unexpected token {
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:537:28)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Function.Module.runMain (module.js:609:10)
    at startup (bootstrap_node.js:158:16)
    at bootstrap_node.js:578:3
npm verb lifecycle electron@30.0.8~postinstall: unsafe-perm in lifecycle true
npm verb lifecycle electron@30.0.8~postinstall: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;C:\Users\Stephen\Development\Electron\node_modules\electron\node_modules\.bin;C:\Users\Stephen\Development\Electron\node_modules\.bin;C:\Program Files\Microsoft\jdk-11.0.16.101-hotspot\bin;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64_win\mpirt;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\ia32_win\mpirt;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\intel64_win\compiler;C:\Program Files (x86)\Common Files\Intel\Shared Libraries\redist\ia32_win\compiler;C:\PROGRAM FILES\MICROSOFT MPI\BIN\;C:\WINDOWS\SYSTEM32;C:\WINDOWS;C:\WINDOWS\SYSTEM32\WBEM;C:\WINDOWS\SYSTEM32\WINDOWSPOWERSHELL\V1.0\;C:\PROGRAM FILES (X86)\GTKSHARP\2.12\BIN;C:\PROGRAM FILES\ANACONDA3;C:\PROGRAM FILES\ANACONDA3\SCRIPTS;C:\PROGRAM FILES\ANACONDA3\LIBRARY\BIN;C:\PROGRAM FILES (X86)\NVIDIA CORPORATION\PHYSX\COMMON;C:\PROGRAM FILES\DOTNET\;C:\PROGRAM FILES\NODEJS\;C:\PROGRAM FILES\GIT\CMD;C:\Program Files\WIDCOMM\Bluetooth Software\;C:\Program Files\WIDCOMM\Bluetooth Software\syswow64;C:\WINDOWS\system32;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\Git\cmd;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\170\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\150\Tools\Binn\;C:\Program Files\Microsoft SQL Server\150\Tools\Binn\;C:\Program Files\Microsoft SQL Server\150\DTS\Binn\;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\;C:\Program Files (x86)\dotnet\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files (x86)\Common Files\Acronis\SnapAPI\;C:\Program Files (x86)\Common Files\Acronis\VirtualFile\;C:\Program Files (x86)\Common Files\Acronis\VirtualFile64\;C:\Program Files (x86)\Common Files\Acronis\FileProtector\;C:\Program Files (x86)\Common Files\Acronis\FileProtector64\;C:\Program Files\NVIDIA Corporation\Nsight Compute 2022.4.0\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Users\Stephen\AppData\Local\Microsoft\WindowsApps;C:\Users\Stephen\AppData\Roaming\npm;C:\Users\Stephen\AppData\Local\GitHubDesktop\bin;C:\Users\Stephen\AppData\Local\Microsoft\WindowsApps;C:\Users\Stephen\.dotnet\tools;C:\Program Files\Azure Data Studio\bin;C:\Users\Stephen\AppData\Local\Programs\Microsoft VS Code\bin;;C:\Users\Stephen\.fnm
npm verb lifecycle electron@30.0.8~postinstall: CWD: C:\Users\Stephen\Development\Electron\node_modules\electron
npm info lifecycle electron@30.0.8~postinstall: Failed to exec postinstall script
npm verb unlock done using C:\Users\Stephen\AppData\Roaming\npm-cache\_locks\staging-0569b61327b2f5e6.lock for C:\Users\Stephen\Development\Electron\node_modules\.staging
npm WARN Error: EPERM: operation not permitted, rmdir 'C:\Users\Stephen\Development\Electron\node_modules\@szmarczak'
npm WARN  { Error: EPERM: operation not permitted, rmdir 'C:\Users\Stephen\Development\Electron\node_modules\@szmarczak'
npm WARN   stack: 'Error: EPERM: operation not permitted, rmdir \'C:\\Users\\Stephen\\Development\\Electron\\node_modules\\@szmarczak\'',
npm WARN   errno: -4048,
npm WARN   code: 'EPERM',
npm WARN   syscall: 'rmdir',
npm WARN   path: 'C:\\Users\\Stephen\\Development\\Electron\\node_modules\\@szmarczak' }
npm verb
npm verb Please try running this command again as root/Administrator.
npm verb stack Error: electron@30.0.8 postinstall: `node install.js`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:289:16)
npm verb stack     at emitTwo (events.js:125:13)
npm verb stack     at EventEmitter.emit (events.js:213:7)
npm verb stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
npm verb stack     at emitTwo (events.js:125:13)
npm verb stack     at ChildProcess.emit (events.js:213:7)
npm verb stack     at maybeClose (internal/child_process.js:927:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
npm verb pkgid electron@30.0.8
npm verb cwd C:\Users\Stephen\Development\Electron
npm verb Windows_NT 10.0.26120
npm verb argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "--verbose" "electron"
npm verb node v8.3.0
npm verb npm  v5.3.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@30.0.8 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron@30.0.8 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 1, true ]

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Stephen\AppData\Roaming\npm-cache\_logs\2024-05-27T20_16_45_723Z-debug.log
```

### Additional Information

I'm not doing anything fancy, I am trying to work with electron for the first time and can't get it to cleanly install. I have tried other versions with the same issue. I am attempting to install with powershell

```
npm init -y
npm install electron

```

and it fails with the same error message each time. I've tried installing as administrator also, with the same results. I have successully installed other packages via npm. Thanks for any help

[2024-05-27T20_20_33_709Z-debug.log](https://github.com/electron/electron/files/15461626/2024-05-27T20_20_33_709Z-debug.log)

**Comment by kenshanta** [comment]
Have you tried installing as the root user? because this error line
`
Error: EPERM: operation not permitted, rmdir 'C:\Users\Stephen\Development\Electron\node_modules\@szmarczak'
`

might pinpoint to some lack of permissions.

**Comment by diehard2** [comment]
thanks for the response @kenshanta. I see the same thing if I run as administrator

[2024-05-28T02_17_55_798Z-debug.log](https://github.com/electron/electron/files/15463132/2024-05-28T02_17_55_798Z-debug.log)

**Comment by codebytere** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. This forum is for raising bugs or requesting new features, and for most questions about Electron there are a lot of more appropriate [community options](https://github.com/electron/electron#community). There are helpful people in this [Discord](https://discord.gg/electronjs) or the [subreddit](https://www.reddit.com/r/electronjs) that should be willing to point you in the right direction.
