### ISSUE TITLE
[Bug]: App threw an error during load when use ffi-napi

### ISSUE THREAD

**Issue by fanybook** [electron/electron#43876]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

30.5.1

### What operating system(s) are you using?

macOS

### Operating System Version

macOS 12.6.2

### What arch are you using?

x64

### Last Known Working Electron version

20.3.8 (20.3.9 not work)

### Expected Behavior

can use 'ffi-napi'

### Actual Behavior
The application encountered an error during startup when require `ffi-napi`, but it appears that the main program has not crashed yet

```js
const ffi = require('ffi-napi')
const ref = require('ref-napi')
```

App threw an error during load
Error: Error in native callback
    at process.func [as dlopen] (node:electron/js2c/node_init:2:2214)
    at Module._extensions..node (node:internal/modules/cjs/loader:1470:18)
    at Object.func [as .node] (node:electron/js2c/node_init:2:2214)
    at Module.load (node:internal/modules/cjs/loader:1215:32)
    at Module._load (node:internal/modules/cjs/loader:1031:12)
    at c._load (node:electron/js2c/node_init:2:13801)
    at Module.require (node:internal/modules/cjs/loader:1240:19)
    at require (node:internal/modules/helpers:179:18)
    at load (/Users/admin/workspace-gitee/fanybook/electron-playground/app-main/node_modules/node-gyp-build/node-gyp-build.js:22:10)
    at Object.<anonymous> (/Users/admin/workspace-gitee/fanybook/electron-playground/app-main/node_modules/ref-napi/lib/ref.js:8:53)

**Comment by fanybook** [comment]
this seems to be a compatibility issue

> https://github.com/node-ffi-napi/node-ffi-napi/issues/238

**Comment by fanybook** [comment]
> Hi there, I am also facing same issue with electron upgrade and this library since its functionality is mandatory in the project I am working on.
﻿
I think it would be great someone from electron/node-ffi-napi should provide an official fork/patch adding the commented fixes and some instructions/recommendations even if gets archived in order to avoid third party forks.
﻿
So sticking to last electron compatible version 20.3.8 or trying out koffi package seem only ways for me who I am a 0 skills in C/C++ for writing my own node add-on.
﻿
In addition a personal recommendation for anyone thinking about installing any of the mentioned forks/packages:
﻿
@lwahonen/ffi-napi, @lwahonen/ref-napi or @breush/ffi-napi, @breush/ref-napi
﻿
Even if these are working and they are not malicious code, you should be aware that these projects are not 100% github forks and their integrity is not guaranteed, in other words they do not share the same history with this repo.
Maybe it is something their author could fix.
