### ISSUE TITLE
[Bug]: throwing "Electron failed to install correctly" in 32.1.2

### ISSUE THREAD

**Issue by hyperknot** [electron/electron#44008]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

32.1.2

### What operating system(s) are you using?

macOS

### Operating System Version

14.7

### What arch are you using?

arm64 (including Apple Silicon)

### Last Known Working Electron version

32.1.1

### Expected Behavior

pnpm electron should start. 32.1.1 works correctly, only .2 is broken

### Actual Behavior

```
pnpm electron
repo/electron/node_modules/.pnpm/electron@32.1.2/node_modules/electron/index.js:17
    throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again');
    ^

Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
    at getElectronPath (repo/electron/node_modules/.pnpm/electron@32.1.2/node_modules/electron/index.js:17:11)
    at Object.<anonymous> (repo/electron/node_modules/.pnpm/electron@32.1.2/node_modules/electron/index.js:21:18)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1548:10)
    at Module.load (node:internal/modules/cjs/loader:1288:32)
    at Module._load (node:internal/modules/cjs/loader:1104:12)
    at Module.require (node:internal/modules/cjs/loader:1311:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (repo/electron/node_modules/.pnpm/electron@32.1.2/node_modules/electron/cli.js:3:18)
    at Module._compile (node:internal/modules/cjs/loader:1469:14)

Node.js v20.17.0
```

**Comment by hyperknot** [comment]
Nevermind, removing my pnpm cache dir and node_modules and pnpm.lock seems to have solved it.

**Comment by CatStudioApp** [comment]
maybe it's a good idea to add this into the error message 

> Nevermind, removing my pnpm cache dir and node_modules and pnpm.lock seems to have solved it.

**Comment by erickzhao** [comment]
If you're using pnpm v10 or above, this may be caused by [`onlyBuiltDependencies`](https://pnpm.io/package_json#pnpmonlybuiltdependencies) rejecting unlisted `postinstall` scripts by default.

Try adding this to your `package.json`:

```json
{
  "pnpm": {
    "onlyBuiltDependencies": ["electron"]
  }
}

```

**Comment by AlbanianSoftware** [comment]
For pnpm, check pnpm approve-builds command and make sure you press space to select electron, otherwise it wont install it.
This solved it for me.
