### ISSUE TITLE
Failed patch "printing.patch" during "s sync" on Ubuntu 22

### ISSUE THREAD

**Issue by andyImatest** [electron/electron#44305]
### Preflight Checklist

- [x] I have read the [Contributing Guidelines](https://github.com/electron/electron/blob/main/CONTRIBUTING.md) for this project.
- [x] I agree to follow the [Code of Conduct](https://github.com/electron/electron/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [x] I have searched the [issue tracker](https://www.github.com/electron/electron/issues) for a bug report that matches the one I want to file, without success.

### Electron Version

master

### What operating system(s) are you using?

Ubuntu

### Operating System Version

Ubuntu 22.04.5 LTS

### What arch are you using?

x64

### Last Known Working Electron version

About a month ago I was able to checkout via "e sync" with no issues

### Expected Behavior

"e sync" should not fail when setting up a new repo.

### Actual Behavior

> e sync
.....
Applying: proxy_config_monitor.patch
Applying: gritsettings_resource_ids.patch
Applying: isolate_holder.patch
Applying: notification_provenance.patch
Applying: dump_syms.patch
Applying: command-ismediakey.patch
Applying: printing.patch
error: patch failed: ui/gtk/gtk_util.cc:227
error: ui/gtk/gtk_util.cc: patch does not apply
Patch failed at 0025 printing.patch
hint: Use 'git am --show-current-patch=diff' to see the failed patch
When you have resolved this problem, run "git am --continue".
If you prefer to skip this patch, run "git am --skip" instead.
To restore the original branch and stop patching, run "git am --abort".
Traceback (most recent call last):
  File "/home/electron/workspace/v32.2.1/src/electron/script/apply_all_patches.py", line 45, in <module>
    main()
  File "/home/electron/workspace/v32.2.1/src/electron/script/apply_all_patches.py", line 41, in main
    apply_config(json.load(config_json))
  File "/home/electron/workspace/v32.2.1/src/electron/script/apply_all_patches.py", line 29, in apply_config
    apply_patches(target)
  File "/home/electron/workspace/v32.2.1/src/electron/script/apply_all_patches.py", line 19, in apply_patches
    git.import_patches(
  File "/home/electron/workspace/v32.2.1/src/electron/script/lib/git.py", line 85, in import_patches
    am(repo=repo, **kwargs)
  File "/home/electron/workspace/v32.2.1/src/electron/script/lib/git.py", line 78, in am
    raise RuntimeError(f"Command {command} returned {proc.returncode}")
RuntimeError: Command ['git', '-C', 'src', '-c', 'user.name=Electron Scripts', '-c', 'user.email=scripts@electron', '-c', 'commit.gpgsign=false', 'am', '--keep-cr'] returned 128

If I try "e sync" again, it fails because a file is in a conflicted state.

> e sync
[0:00:20]  = [up to date]                  99.0.4844.9                   -> 99.0.4844.9
[0:00:20]  = [up to date]                  99.0.4844.94                  -> 99.0.4844.94
[0:00:20]  = [up to date]                  pre_blink_merge               -> pre_blink_merge
[0:00:24] Fetching origin
----------------------------------------
Error: 2> 
2> ____ src at 132.0.6779.0
2> 	Already in a conflict, i.e. (no branch).
2> 	Fix the conflict and run gclient again.
2> 	Or to abort run:
2> 		git-rebase --abort
2> 	See man git-rebase for details.
 
ERROR gclient sync failed

**Comment by andyImatest** [comment]
Somewhat related to this issue, it would be great if I could choose the branch or tag I want to checkout as part of the "e init" call, so I only need to "e sync" once.

**Comment by codebytere** [comment]
Already fixed: https://github.com/electron/electron/pull/44302
