### ISSUE TITLE
Unexpected end of input

### ISSUE THREAD

**Issue by Xstoudi** [electron/electron#5038]
* Electron version: 0.37.4
* Operating system: Debian 8

When i use ```electron .``` to start my Electron app, 
I get this error :
```
A JavaScript error occurred in the main process
Uncaught Exception:
SyntaxError: Unexpected end of input
    at Object.parse (native)
    at loadApplicationPackage (/usr/lib/node_modules/electron-prebuilt/dist/resources/default_app.asar/main.js:238:30)
    at Object.<anonymous> (/usr/lib/node_modules/electron-prebuilt/dist/resources/default_app.asar/main.js:293:5)
    at Module._compile (module.js:416:34)
    at Object.Module._extensions..js (module.js:425:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Object.<anonymous> (/usr/lib/node_modules/electron-prebuilt/dist/resources/electron.asar/browser/init.js:184:8)
    at Module._compile (module.js:416:34)
    at Object.Module._extensions..js (module.js:425:10)
```

I tried to reinstall Electron but nothing changes.

**Comment by Xstoudi** [comment]
Ok, I failed the package.json
