### ISSUE TITLE
Not able to script\bootstrap.py on Win 10

### ISSUE THREAD

**Issue by bpasero** [electron/electron#5149]
* Electron version: 0.37.5
* Operating system: Win 10

Trying to build Electron from source (0.37.5) on Windows 10, I am always presented with errors in the step `script\bootstrap.py`

Any clues?

```
C:\Python27\python.exe C:\GitDevelopment\electron\vendor\brightray\script\bootstrap --commit 9229f39b44ca1dde25db9c648547861286b61935 --target_arch ia32 https://s3.amazonaws.com/github-janky-artifacts/libchromiumcontent
Traceback (most recent call last):
  File "C:\GitDevelopment\electron\vendor\brightray\vendor\libchromiumcontent\script\download", line 186, in <module>
    sys.exit(main())
  File "C:\GitDevelopment\electron\vendor\brightray\vendor\libchromiumcontent\script\download", line 67, in main
    args.force)
  File "C:\GitDevelopment\electron\vendor\brightray\vendor\libchromiumcontent\script\download", line 127, in download_if_needed
    rm_rf(destination)
  File "C:\GitDevelopment\electron\vendor\brightray\vendor\libchromiumcontent\script\download", line 179, in rm_rf
    shutil.rmtree(path)
  File "C:\Python27\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Python27\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Python27\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Python27\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Python27\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Python27\lib\shutil.py", line 247, in rmtree
    rmtree(fullname, ignore_errors, onerror)
  File "C:\Python27\lib\shutil.py", line 256, in rmtree
    onerror(os.rmdir, path, sys.exc_info())
  File "C:\Python27\lib\shutil.py", line 254, in rmtree
    os.rmdir(path)
WindowsError: [Error 145] The directory is not empty: 'C:\\GitDevelopment\\electron\\vendor\\brightray\\vendor\\download\\libchromiumcontent\\src\\third_party\\webrtc\\examples\\objc\\AppRTCDemo'
Traceback (most recent call last):
  File "C:\GitDevelopment\electron\vendor\brightray\script\bootstrap", line 106, in <module>
    sys.exit(main())
  File "C:\GitDevelopment\electron\vendor\brightray\script\bootstrap", line 39, in main
    args.libcc_static_library_path)
  File "C:\GitDevelopment\electron\vendor\brightray\script\bootstrap", line 94, in setup_libchromiumcontent
    subprocess.check_call([sys.executable, download, '-s'] + args)
  File "C:\Python27\lib\subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Python27\\python.exe', 'C:\\GitDevelopment\\electron\\vendor\\brightray\\vendor\\libchromiumcontent\\script\\download', '-s', '-f', '-c', '9229f39b44ca1dde25db9c648547861286b61935', '--target_arch', 'ia32', 'https://s3.amazonaws.com/github-janky-artifacts/libchromiumcontent', 'C:\\GitDevelopment\\electron\\vendor\\brightray\\vendor\\download\\libchromiumcontent']' returned non-zero exit status 1
None
Traceback (most recent call last):
  File "script\bootstrap.py", line 211, in <module>
    sys.exit(main())
  File "script\bootstrap.py", line 44, in main
    args.libcc_static_library_path)
  File "script\bootstrap.py", line 121, in bootstrap_brightray
    execute_stdout([sys.executable, bootstrap] + args)
  File "C:\GitDevelopment\electron\script\lib\util.py", line 176, in execute_stdout
    raise e
subprocess.CalledProcessError: Command '['C:\\Python27\\python.exe', 'C:\\GitDevelopment\\electron\\vendor\\brightray\\script\\bootstrap', '--commit', '9229f39b44ca1dde25db9c648547861286b61935', '--target_arch', 'ia32', 'https://s3.amazonaws.com/github-janky-artifacts/libchromiumcontent']' returned non-zero exit status 1
```

**Comment by felixrieseberg** [comment]
Run the process as Administrator and ensure that you don't have leftover files. Seems like pretty typical "can't delete this" errors.

**Comment by bpasero** [comment]
@felixrieseberg thanks, ever since I abandoned Windows, these tricks dropped out of my developer mind.
