### ISSUE TITLE
Error: Cannot read property 'name' of undefined at valueToMeta (.../node_modules/electron-prebuilt/dist/resources/electron.asar/browser/rpc-server.js:76:41)

### ISSUE THREAD

**Issue by Taytay** [electron/electron#5215]
* Electron version: 0.37.6 (0.33 exhibited as well)
* Operating system: "Ubuntu 12.04 LTS"

We use Electron on Linux to run some tests, and we just began seeing this error:

```
00:21:39.567 [14629:0419/140939:INFO:CONSOLE(37)] "Error: Cannot read property 'name' of undefined
00:21:39.567 TypeError: Cannot read property 'name' of undefined
00:21:39.567     at valueToMeta (/home/vagrant/workspace/Evergreen_Test_Runner/ynab_web/node_modules/electron-prebuilt/dist/resources/electron.asar/browser/rpc-server.js:76:41)
00:21:39.568     at EventEmitter.<anonymous> (/home/vagrant/workspace/Evergreen_Test_Runner/ynab_web/node_modules/electron-prebuilt/dist/resources/electron.asar/browser/rpc-server.js:337:25)
00:21:39.568     at emitThree (events.js:110:13)
00:21:39.568     at EventEmitter.emit (events.js:188:7)
00:21:39.568     at EventEmitter.<anonymous> (/home/vagrant/workspace/Evergreen_Test_Runner/ynab_web/node_modules/electron-prebuilt/dist/resources/electron.asar/browser/api/web-contents.js:139:25)
00:21:39.569     at emitTwo (events.js:100:13)
00:21:39.569     at EventEmitter.emit (events.js:185:7)
00:21:39.569     at metaToValue (/home/vagrant/workspace/Evergreen_Test_Runner/ynab_web/node_modules/electron-prebuilt/dist/resources/electron.asar/renderer/api/remote.js:176:13)
00:21:39.569     at undefined.descriptor.get [as _externalStream] (/home/vagrant/workspace/Evergreen_Test_Runner/ynab_web/node_modules/electron-prebuilt/dist/resources/electron.asar/renderer/api/remote.js:125:16)
00:21:39.570     at xt (http://localhost:3000/ynab_shared_library/node_modules/lodash/index.js:1971:1)
00:21:39.570     at Yt (http://localhost:3000/ynab_shared_library/node_modules/lodash/index.js:2025:1)
00:21:39.570     at Nt (http://localhost:3000/ynab_shared_library/node_modules/lodash/index.js:2316:1)
00:21:39.570     at Ht (http://localhost:3000/ynab_shared_library/node_modules/lodash/index.js:2386:1)
00:21:39.570     at http://localhost:3000/ynab_shared_library/node_modules/lodash/index.js:2320:1
00:21:39.571     at xt (http://localhost:3000/ynab_shared_library/node_modules/lodash/index.js:1971:1)
00:21:39.571     at Yt (http://localhost:3000/ynab_shared_library/node_modules/lodash/index.js:2025:1)
00:21:39.571     at Nt (http://localhost:3000/ynab_shared_library/node_modules/lodash/index.js:2316:1)"
```

I am investigating to see what we've changed recently that would have caused this, but we didn't upgrade Electron. Is there an easy way for me to see the code in `browser/rpc-server.js:76:41` to get an idea of what this might be? I assume we're doing something wrong, and the fact that it's crashing in Electron is a red herring, but I'm not sure yet.

**Comment by zcbenz** [comment]
It seems that you are passing a object through `remote` module which is an object but does not have `constructor` property.

**Comment by Taytay** [comment]
Thanks Cheng!
