### ISSUE TITLE
Dialog.showMessageBox will not accept a NativeImage instance or null as an icon

### ISSUE THREAD

**Issue by danielrob** [electron/electron#5232]
* Electron version: Version 0.36.11 (0.36.11)
* Operating system: 10.11.4 (El Capitan)

The [dialog.showMessageBox api](http://electron.atom.io/docs/v0.27.0/api/dialog/#dialogshowmessageboxbrowserwindow-options-callback) states it accepts nativeImage instances. 

**Steps to reproduce / my code:**
```
const
    remote = require('remote'),
    dialog = remote.require('dialog'),
    nativeImage = require('electron').nativeImage,
    imgPath = "/Users/daniel/Desktop/img.png", 
    emptyInstance = nativeImage.createEmpty(), 
    imageInstance = nativeImage.createFromPath(imgPath);

dialog.showMessageBox({
  type: "none",
  title: 'confirm delete',
  message: 'What to do with rejects?',
  buttons: ['Cancel', 'Remove From Library', 'Move to Trash' ], 
  icon: imageInstance
});
```

**Expected result:**
Same as passing in `imgPath`, i.e. a message dialog box with the image.

**Actual result:**

```
Uncaught Error: Could not call remote function ``. Check that the function signature is correct. Underlying error: Error processing argument at index 8, conversion failure from 
Error: Could not call remote function ``. Check that the function signature is correct. Underlying error: Error processing argument at index 8, conversion failure from 
    at callFunction (/Users/daniel/app/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/atom.asar/browser/rpc-server.js:238:11)
    at EventEmitter.<anonymous> (/Users/daniel/app/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/atom.asar/browser/rpc-server.js:319:12)
    at emitMany (events.js:108:13)
    at EventEmitter.emit (events.js:182:7)
    at EventEmitter.<anonymous> (/Users/daniel/app/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/atom.asar/browser/api/web-contents.js:144:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at callFunction (/Users/daniel/app/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/atom.asar/browser/rpc-server.js:238:11)
    at EventEmitter.<anonymous> (/Users/daniel/app/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/atom.asar/browser/rpc-server.js:319:12)
    at emitMany (events.js:108:13)
    at EventEmitter.emit (events.js:182:7)
    at EventEmitter.<anonymous> (/Users/daniel/app/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/atom.asar/browser/api/web-contents.js:144:25)
    at emitTwo (events.js:87:13)
    at EventEmitter.emit (events.js:172:7)
    at metaToValue (/Users/daniel/app/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/atom.asar/renderer/api/remote.js:170:13)
    at remoteMemberFunction [as showMessageBox] (/Users/daniel/app/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/atom.asar/renderer/api/remote.js:110:18)
    at <anonymous>:2:8
    at InjectedScript._evaluateOn (<anonymous>:875:140)
    at InjectedScript._evaluateAndWrap (<anonymous>:808:34)
    at InjectedScript.evaluate (<anonymous>:664:21)

```
**Note**
Replacing `imageInstance` with `imgPath` works here, while using `emptyInstance` also results in the same error. A further issue is passing null here, keeps the default application icon. 

As far as I can tell this means there is no simple way (I need to load a transparent gif) to remove the default icon from the dialog box. Other than this it simply represents an inconsistency in the API/docs.

**Comment by zcbenz** [comment]
You are using dialog from the main process while passing the NativeImage instance from renderer process to it, so what `dialog.showMessageBox` sees is a remote object instead of a NativeImage instance.

To solve it you can either use image's path directly, or create the NativeImage instance in the main process: `nativeImage = require('electron').remote.nativeImage`.
