### ISSUE TITLE
[Build electron app error] The system cannot find the file specified

### ISSUE THREAD

**Issue by kenzouno1** [electron/electron#5402]
* Electron version:0.37.8
* Operating system: window 10 32bit

i'm cloned electron.git.cd to fodel electron and run command 

`python script\bootstrap.py -v`

but i see error 

`Running in verbose mode

git submodule sync

Traceback (most recent call last):

  File "script\bootstrap.py", line 259, in <module>
    sys.exit(main())

  File "script\bootstrap.py", line 37, in main
    update_submodules()

  File "script\bootstrap.py", line 128, in update_submodules
    execute_stdout(['git', 'submodule', 'sync'])

  File "D:\Hoctap\electron\electron\script\lib\util.py", line 173, in execute_stdout
    subprocess.check_call(argv, env=env)

  File "C:\Python27\lib\subprocess.py", line 535, in check_call
    retcode = call(*popenargs, **kwargs)

  File "C:\Python27\lib\subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()

  File "C:\Python27\lib\subprocess.py", line 710, in __init__
    errread, errwrite)

  File "C:\Python27\lib\subprocess.py", line 958, in _execute_child
    startupinfo)

WindowsError: [Error 2] The system cannot find the file specified`

I do not understand what this is in error.

**Comment by enlight** [comment]
Did you install `git` and add it to your `PATH`? Make sure you can rut `git` from the command prompt.

**Comment by kenzouno1** [comment]
oh.i'm re-install git and Problem solved.
I'm self-taught nodejs, electron from today and i thought it was an error by python or electron.Thanks.
