### ISSUE TITLE
fatal: reference is not a tree

### ISSUE THREAD

**Issue by ficristo** [electron/electron#5529]
* Electron version: current master
* Operating system: Windows 7

Running this command in cmd `python script\bootstrap.py -v --dev --target_arch=x64` it fails:
```
git submodule update --init --recursive
fatal: reference is not a tree: 549e55a22765ccf99e46b419b2dff6338bcac64a
Unable to checkout '549e55a22765ccf99e46b419b2dff6338bcac64a' in submodule path
'vendor/brightray/vendor/gyp'
Failed to recurse into submodule path 'vendor/brightray'
```

**Comment by zcbenz** [comment]
The submodule's URL has been changed, you need to run `git submodule sync` in the repo.

**Comment by ficristo** [comment]
The `bootstrap` script should already run `git submodule sync`.
Nevertheless I've run:
`git fetch upstream -ap`
`git rebase upstream/master`
`git clean -xdf`
`git submodule sync`
`python script\bootstrap.py -v --dev --target_arch=x64`
Still the same problem.

**Comment by ficristo** [comment]
This the full error:
```
Running in verbose mode
git submodule sync
Synchronizing submodule url for 'vendor/boto'
Synchronizing submodule url for 'vendor/breakpad'
Synchronizing submodule url for 'vendor/brightray'
Synchronizing submodule url for 'vendor/crashpad'
Synchronizing submodule url for 'vendor/depot_tools'
Synchronizing submodule url for 'vendor/native_mate'
Synchronizing submodule url for 'vendor/node'
Synchronizing submodule url for 'vendor/requests'
git submodule update --init --recursive
fatal: reference is not a tree: 549e55a22765ccf99e46b419b2dff6338bcac64a
Unable to checkout '549e55a22765ccf99e46b419b2dff6338bcac64a' in submodule path
'vendor/brightray/vendor/gyp'
Failed to recurse into submodule path 'vendor/brightray'
None
Traceback (most recent call last):
  File "script\bootstrap.py", line 259, in <module>
    sys.exit(main())
  File "script\bootstrap.py", line 37, in main
    update_submodules()
  File "script\bootstrap.py", line 129, in update_submodules
    execute_stdout(['git', 'submodule', 'update', '--init', '--recursive'])
  File "E:\Utenti\Filippo\github\electron\script\lib\util.py", line 177, in exec
ute_stdout
    raise e
subprocess.CalledProcessError: Command '['git', 'submodule', 'update', '--init',
 '--recursive']' returned non-zero exit status 1
```

**Comment by zcbenz** [comment]
You can probably remove the repo and then clone it again, git is really bad at handling submodule URL changes.

**Comment by ficristo** [comment]
@zcbenz Isn't more probably that on brightray module something wasn't pushed correctly?
However I'll try to clone again.

**Comment by zcbenz** [comment]
Our CI servers will complain if there is something wrong with the git setup.

**Comment by ficristo** [comment]
After a fresh clone seems to work :confused: 
Thank you for you patience.
