### ISSUE TITLE
Trouble running the test suite

### ISSUE THREAD

**Issue by stevekinney** [electron/electron#5539]
* Electron version: 1.0.1
* Operating system: OS X and Debian

I'm not sure if this is the right forum for this, but I've been having some trouble running the test sweet on multiple platforms. I get something resembling the following message on both Debian and OS X:

```
Traceback (most recent call last):
  File "./script/test.py", line 50, in <module>
    sys.exit(main())
  File "./script/test.py", line 35, in main
    subprocess.check_call([atom_shell, 'spec'] + sys.argv[1:])
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 535, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 522, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

On Debian, I've run `./scripts/bootstrap.py` and that just hangs on OS X. Running `bootstrap.py` doesn't seem to fix the issue.

I suspect I'm missing something.

**Comment by zcbenz** [comment]
The test.py uses Debug build for building, and `bootstrap.py` takes forever because it is downloading a rather large binary, you can call `bootstrap.py -v` to get the progress.
