### ISSUE TITLE
unable to bootstrap on OSX

### ISSUE THREAD

**Issue by cdaringe** [electron/electron#5686]
* Electron version: 1.1.2
* Operating system: osx/mavericks

```
cdieringer@Snapper-osx:~/node/electron$ python script/bootstrap.py -v
Running in verbose mode
git submodule sync --recursive
Synchronizing submodule url for 'vendor/boto'
Synchronizing submodule url for 'vendor/breakpad'
Synchronizing submodule url for 'vendor/breakpad/src'
Synchronizing submodule url for 'vendor/brightray'
Synchronizing submodule url for 'vendor/brightray/vendor/google-styleguide'
Synchronizing submodule url for 'vendor/brightray/vendor/gyp'
Synchronizing submodule url for 'vendor/brightray/vendor/libchromiumcontent'
Synchronizing submodule url for 'vendor/brightray/vendor/libchromiumcontent/vendor/depot_tools'
Synchronizing submodule url for 'vendor/brightray/vendor/libchromiumcontent/vendor/python-patch'
Synchronizing submodule url for 'vendor/crashpad'
Synchronizing submodule url for 'vendor/depot_tools'
Synchronizing submodule url for 'vendor/native_mate'
Synchronizing submodule url for 'vendor/node'
Synchronizing submodule url for 'vendor/requests'
git submodule update --init --recursive
fatal: reference is not a tree: e4d59bedfd3c7f4f254f4f5d036587bcd8152458
Unable to checkout 'e4d59bedfd3c7f4f254f4f5d036587bcd8152458' in submodule path 'vendor/requests'
None
Traceback (most recent call last):
  File "script/bootstrap.py", line 262, in <module>
    sys.exit(main())
  File "script/bootstrap.py", line 37, in main
    update_submodules()
  File "script/bootstrap.py", line 127, in update_submodules
    execute_stdout(['git', 'submodule', 'update', '--init', '--recursive'])
  File "/Users/cdieringer/node/electron/script/lib/util.py", line 177, in execute_stdout
    raise e
subprocess.CalledProcessError: Command '['git', 'submodule', 'update', '--init', '--recursive']' returned non-zero exit status 1
cdieringer@Snapper-osx:~/node/electron$ git log -1
commit 407a5d4415c5b6fb096516ecc5a0686fe1ae02b2
Merge: 4d56437 3e15021
Author: Kevin Sawicki <kevin@github.com>
Date:   Tue May 24 10:15:56 2016 -0700

    Merge pull request #5681 from electron/default-app-error-handling

    Tweak default app error handling
```

**Unable to checkout 'e4d59bedfd3c7f4f254f4f5d036587bcd8152458' in submodule path 'vendor/requests'**

See latest commit per the gitlog output.  Tips would be great!

**Comment by zcbenz** [comment]
All of our CI machines are building fine, so it should be local issue,  I suggest deleting the `vendor/requests` and then run bootstrap again, if it still doesn't work you can probably try deleting the  whole repo and then clone it again.

**Comment by cdaringe** [comment]
re-cloning did the trick. how bizarre. thanks!

**Comment by carakas** [comment]
I have the same issue, also tried recloning and it didn't fix it

**Comment by carakas** [comment]
this fixed my issue
https://github.com/boto/boto/issues/3507#issuecomment-224333221
