### ISSUE TITLE
npm ELIFECYCLE ERR! Exit status 3221226525 after app.quit();

### ISSUE THREAD

**Issue by mydansun** [electron/electron#5814]
* Electron version: 1.2.0
* Operating system: Windows 10
"electron-prebuilt": "^1.2.0"

```
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.1.0
npm ERR! npm  v3.8.6
npm ERR! code ELIFECYCLE
npm ERR! @ start: `electron app/main.js`
npm ERR! Exit status 3221226525
npm ERR!
npm ERR! Failed at the @ start script 'electron app/main.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron app/main.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     E:\UserDocument\Desktop\PROJECT\Electron\whatever\npm-debug.log
```

Here is npm-debug.log
```
0 info it worked if it ends with ok
1 verbose cli [ 'D:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@3.8.6
3 info using node@v6.1.0
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle @~prestart: @
6 silly lifecycle @~prestart: no script for prestart, continuing
7 info lifecycle @~start: @
8 verbose lifecycle @~start: unsafe-perm in lifecycle true
9 verbose lifecycle @~start: PATH: D:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;E:\UserDocument\Desktop\PROJECT\Electron\whatever\node_modules\.bin;D:\Program Files\nodejs;C:\ProgramData\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit\;C:\Program Files\Microsoft SQL Server\110\Tools\Binn\;C:\Program Files (x86)\Microsoft SDKs\TypeScript\1.0\;C:\Program Files\Microsoft SQL Server\120\Tools\Binn\;D:\php;D:\Program Files\TortoiseSVN\bin;C:\Program Files (x86)\Skype\Phone\;D:\Program Files (x86)\QuickTime\QTSystem\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;D:\Program Files\nodejs\;C:\Python27;C:\Users\mydan\AppData\Roaming\npm
10 verbose lifecycle @~start: CWD: E:\UserDocument\Desktop\PROJECT\Electron\whatever
11 silly lifecycle @~start: Args: [ '/d /s /c', 'electron app/main.js' ]
12 silly lifecycle @~start: Returned: code: 3221226525  signal: null
13 info lifecycle @~start: Failed to exec start script
14 verbose stack Error: @ start: `electron app/main.js`
14 verbose stack Exit status 3221226525
14 verbose stack     at EventEmitter.<anonymous> (D:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:239:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (D:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:850:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid @
16 verbose cwd E:\UserDocument\Desktop\PROJECT\Electron\whatever
17 error Windows_NT 10.0.10586
18 error argv "D:\\Program Files\\nodejs\\node.exe" "D:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
19 error node v6.1.0
20 error npm  v3.8.6
21 error code ELIFECYCLE
22 error @ start: `electron app/main.js`
22 error Exit status 3221226525
23 error Failed at the @ start script 'electron app/main.js'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the  package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     electron app/main.js
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]

```

**Comment by danhp** [comment]
Could you provide a minimal app or steps to reproduce the issue? It's currently a little hard to go off with just the logs.

**Comment by mydansun** [comment]
@danhp 
The code is too much...
Could you give me a scope at least?

**Comment by danhp** [comment]
The logs aren't pointing to anything in particular so I can't guide you with just that.

**Comment by HitomiTenshi** [comment]
Same problem here.

The bug isn't consistent, seems to happens only during development after a few page reloads with `CTRL + R`.

Steps to try:

1. start electron
2. do some changes in code
3. reload electron with `CTRL + R`
4. change UI a few times with jQuery
5. repeat step 2 to 4 a few times
6. electron might spit out some error code in console, that's pretty much the sign that it'll crash on exit. Doesn't always happen though, even after some error lines.

I usually know that my app is going to crash on exit if I see electron spit out some of these lines:

    [4300:0603/105019:ERROR:gles2_cmd_decoder.cc(14683)] [.CommandBufferContext.DisplayCompositor-00000212CA59ED40]GL ERROR :GL_INVALID_OPERATION : glCreateAndConsumeTextureCHROMIUM: invalid mailbox name
    [4300:0603/105019:ERROR:gles2_cmd_decoder.cc(7857)] [.CommandBufferContext.DisplayCompositor-00000212CA59ED40]RENDER WARNING: texture bound to texture unit 0 is not renderable. It maybe non-power-of-2 and have incompatible texture filtering.

I sadly don't know of a way to consistently reproduce `Exit status 3221226525`.

**Comment by paulcbetts** [comment]
```
0:000> .formats 0n3221226525
Evaluate expression:
  Hex:     00000000`c000041d
  Decimal: 3221226525
  Octal:   0000000000030000002035
  Binary:  00000000 00000000 00000000 00000000 11000000 00000000 00000100 00011101
  Chars:   ........
  Time:    ***** Invalid
  Float:   low -2.00025 high 0
  Double:  1.5915e-314

0:000> !error c000041d
Error code: (NTSTATUS) 0xc000041d (3221226525) - An unhandled exception was encountered during a user callback.
```

**Comment by necrifede** [comment]
I got same error using example from get-started site.

I'm using:
- Electron version: 1.2.2
- Operating system: Windows 7 (no SP)
- electron-prebuilt version ^1.2.0

I executed the steps mention in [http://electron.atom.io/#get-started](http://electron.atom.io/#get-started)
```
$ git clone https://github.com/electron/electron-quick-start
$ cd electron-quick-start
$ npm install && npm start
```

The "Hello World!" works fine, however the error appears once the application is closed.
```
c:\Users\nestor.v2\Desktop\electron\electron-quick-start>npm start

> electron-quick-start@1.0.0 start c:\Users\nestor.v2\Desktop\electron\electron-quick-start
> electron main.js



npm ERR! Windows_NT 6.1.7600
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
npm ERR! node v6.2.1
npm ERR! npm  v3.9.3
npm ERR! code ELIFECYCLE
npm ERR! electron-quick-start@1.0.0 start: `electron main.js`
npm ERR! Exit status 3221226525
npm ERR!
npm ERR! Failed at the electron-quick-start@1.0.0 start script 'electron main.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron-quick-start package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron main.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-quick-start
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron-quick-start
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\Users\nestor.v2\Desktop\electron\electron-quick-start\npm-debug.log
```

Addind the debug log generated [npm-debug.log.txt](https://github.com/electron/electron/files/308062/npm-debug.log.txt)

just to notice, I'm using Windows 7 without Service Pack, also my npm is working under a proxy, I don't think these fact could affect to reproduce the problem.

**Comment by Andrew-Webb** [comment]
On Windows 8, I can reliably reproduce this error on app close **when the DevTools are open**.

If you quit the app with the DevTools closed - no error.

This is 100% reproducible for me.

**Comment by Andrew-Webb** [comment]
Easy workaround:-

```javascript
// Quit when all windows are closed.
app.on('window-all-closed', function () {
  // On OS X it is common for applications and their menu bar
  // to stay active until the user quits explicitly with Cmd + Q
  if (process.platform !== 'darwin') {
    mainWindow.webContents.closeDevTools()
    app.quit()
  }
})
```

**Comment by zcbenz** [comment]
@Andrew-Webb Thanks for testing, I can also reproduce with the same steps.

I'm merging this to #4261, since their stack trace is exactly the same.
