### ISSUE TITLE
require('child_process').spawn does not work.

### ISSUE THREAD

**Issue by MariasStory** [electron/electron#5895]
* Electron version:
1.2.1

* Operating system:
ubuntu 16.04

* Code:
var spawn = require('child_process').spawn;
var child = spawn('./main/main');

* Output:
A JavaScript error occurred in the main process
Uncaught Exception:
Error: spawn ./main/main ENOENT
    at exports._errnoException (util.js:949:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
    at Function.Module.runMain (module.js:577:11)
    at startup (node.js:168:18)
    at node.js:457:3

* Work with:
node-v6.1.0-linux-x64
node-v4.4.5-linux-x64

**Comment by MariasStory** [comment]
Sorry. Just a wrong path to the executable.

Works like a charm.

Please close the issue
