### ISSUE TITLE
crash in electron 1.2.0 and 1.2.1 when use nodobjc to call objective-c framework

### ISSUE THREAD

**Issue by imlliu2005** [electron/electron#5927]
* Electron version:1.2.1 / 1.2.0
* Operating system:mac osx10.11.3

var nodobjc = require('nodobjc');
nodobjc.framework('/Users/apple/talk/screenshot.framework');

 I have a problem when my electron from 1.1.1 update to 1.2.0/1.2.1 when it use nodobjc call objective-c framework like this: 
App threw an error during load
TypeError: error setting argument 0 - writePointer: Buffer instance expected as third argument
at TypeError (native)
at Object.writePointer (/Users/apple/talk/electron-quick-start-master/node_modules/ref/lib/ref.js:742:11)
at Object.set (/Users/apple/talk/electron-quick-start-master/node_modules/ref/lib/ref.js:484:13)
at Object.alloc (/Users/apple/talk/electron-quick-start-master/node_modules/ref/lib/ref.js:516:13)
at Object.proxy as objc_getClassList
at Object.getClassList (/Users/apple/talk/electron-quick-start-master/node_modules/nodobjc/lib/core.js:111:20)
at Object.importFramework (/Users/apple/talk/electron-quick-start-master/node_modules/nodobjc/lib/import.js:321:26)
at Function.framework (/Users/apple/talk/electron-quick-start-master/node_modules/nodobjc/lib/index.js:225:18)
at Object. (/Users/apple/talk/electron-quick-start-master/main.js:14:9)
^C

**Comment by zcbenz** [comment]
It is probably because nodobjc is not compatible with V8 5.1, sorry we are not able to fix problems of third party modules.

**Comment by imlliu2005** [comment]
ok，if as you say,use electron 1.2.0 and later I can not call objective-c with nodobjc,it is a bad news for me and other developers on mac who use eletron and objective-c to develop apps.
thank you all the same, I will ask other for help.
