### ISSUE TITLE
Cannot find module autoUpdater? 

### ISSUE THREAD

**Issue by kunkinkan** [electron/electron#6006]
Why would I get this error?

It happens on this line: 

```
    if (isDevelopment || process.platform == "linux" || !electron.autoUpdater) {
      return;
    }

```

(and yes, it's a signed app).

```
ErrorCannot find module '../auto-updater'Error: Cannot find module '../auto-updater'
    at Module._resolveFilename (module.js:438:15)
    at Function.Module._resolveFilename (/Users/kunkinkan/Desktop/app/dist/osx/App.app/Contents/Resources/electron.asar/common/reset-search-paths.js:47:12)
    at Function.Module._load (module.js:386:25)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.get [as autoUpdater] (/Users/kunkinkan/Desktop/app/dist/osx/App.app/Contents/Resources/electron.asar/browser/api/exports/electron.js:17:14)
    at Object.App.autoUpdate (/Users/kunkinkan/Desktop/app/dist/osx/App.app/Contents/Resources/app.asar/main.js:108:66)
    at EventEmitter.<anonymous> (/Users/kunkinkan/Desktop/app/dist/osx/App.app/Contents/Resources/app.asar/main.js:1267:7)
    at emitOne (events.js:96:13)App.app
    at EventEmitter.emit (events.js:188:7)module.js:440
    throw err;
    ^

```

**Comment by kunkinkan** [comment]
just found something, if i define

`var autoUpdate = electron.autoUpdater; 
`
at the top (below other requires), it seems to work. don't even have to use that variable. All other code remains the same. After electron.autoUpdater will not throw an error in the method detailed previously. Very strange, is there something I'm doing wrong with modules?

**Comment by zcbenz** [comment]
I suggest seeking help from [the community](https://github.com/electron/electron#community), the issues list is for bug reports and feature requests.
