### ISSUE TITLE
Building shared library version of libchromiumcontent fails

### ISSUE THREAD

**Issue by tomotvos** [electron/electron#6065]
* Electron version: 1.2.2
* Operating system: Windows 10

You can trigger a build of libchromiumcontent in bootstrap.py with the --build_libchromiumcontent switch. This causes a static library build of libcc based on the hard-coded values in build-libchromiumcontent.py. If those switches are changed to build a shared library version of libcc, an error occurs about 3600 files into the build:

```
F:\Python27\python.exe P:\electron\vendor\brightray\vendor\libchromiumcontent\script\build -c all -t x64
ninja: Entering directory `vendor\chromium\src\out\Release_x64'
[2/2] STAMP obj\chromiumcontent\chromiumcontent_all.actions_depends.stamp
ninja: Entering directory `vendor\chromium\src\out_component\Release_x64'
[3589/14419] ACTION Generating Inspector protocol backend sources from protocol.json
FAILED: F:\Python27\python.exe gyp-win-tool action-wrapper environment.x64 protocol_sources_target_generateInspectorProtocolBackendSources_034c95cda95a31aeb229bddf186cfba8..rsp ..\..\third_party\WebKit\Source\platform\inspector_protocol
Traceback (most recent call last):
  File "CodeGenerator.py", line 274, in <module>
    generate("Backend")
  File "CodeGenerator.py", line 263, in generate
    h_template = jinja_env.get_template("/%s_h.template" % class_name)
  File "P:\electron\vendor\brightray\vendor\libchromiumcontent\vendor\chromium\src\third_party\jinja2\environment.py", line 791, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "P:\electron\vendor\brightray\vendor\libchromiumcontent\vendor\chromium\src\third_party\jinja2\environment.py", line 765, in _load_template
    template = self.loader.load(self, name, globals)
  File "P:\electron\vendor\brightray\vendor\libchromiumcontent\vendor\chromium\src\third_party\jinja2\loaders.py", line 132, in load
    bcc.set_bucket(bucket)
  File "P:\electron\vendor\brightray\vendor\libchromiumcontent\vendor\chromium\src\third_party\jinja2\bccache.py", line 184, in set_bucket
    self.dump_bytecode(bucket)
  File "P:\electron\vendor\brightray\vendor\libchromiumcontent\vendor\chromium\src\third_party\jinja2\bccache.py", line 221, in dump_bytecode
    f = open(self._get_cache_filename(bucket), 'wb')
IOError: [Errno 2] No such file or directory: '..\\..\\..\\..\\..\\out_component\\Release_x64/gen/blink/platform/inspector_protocol\\__jinja2_3fa3c4ed164343aa847d5f96785f69b779ec5ead.cache'
[3589/14419] CXX obj\third_party\angle\src\libGLESv2\libGLESv2.entry_points_gles_3_0.obj
ninja: build stopped: subcommand failed.
Traceback (most recent call last):
  File "P:\electron\vendor\brightray\vendor\libchromiumcontent\script\build", line 52, in <module>
    sys.exit(main())
  File "P:\electron\vendor\brightray\vendor\libchromiumcontent\script\build", line 38, in main
    subprocess.check_call([NINJA, '-C', config_dir, target])
  File "F:\Python27\lib\subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['P:\\electron\\vendor\\brightray\\vendor\\libchromiumcontent\\vendor\\depot_tools\\ninja.exe', '-C', 'vendor\\chromium\\src\\out_component\\Release_x64', 'chromiumcontent_all']' returned non-zero exit status 1
None
Traceback (most recent call last):
  File "P:\electron\script\build-libchromiumcontent.py", line 51, in <module>
    sys.exit(main())
  File "P:\electron\script\build-libchromiumcontent.py", line 34, in main
    execute_stdout([sys.executable, build, '-c', 'all', '-t', args.target_arch])
  File "P:\electron\script\lib\util.py", line 177, in execute_stdout
    raise e
subprocess.CalledProcessError: Command '['F:\\Python27\\python.exe', 'P:\\electron\\vendor\\brightray\\vendor\\libchromiumcontent\\script\\build', '-c', 'all', '-t', 'x64']' returned non-zero exit status 1
None
Traceback (most recent call last):
  File "script\bootstrap.py", line 263, in <module>
    sys.exit(main())
  File "script\bootstrap.py", line 45, in main
    build_libchromiumcontent(args.verbose, args.target_arch, defines)
  File "script\bootstrap.py", line 205, in build_libchromiumcontent
    execute_stdout(args + ['--target_arch', target_arch])
  File "P:\electron\script\lib\util.py", line 177, in execute_stdout
    raise e
subprocess.CalledProcessError: Command '['F:\\Python27\\python.exe', 'P:\\electron\\script\\build-libchromiumcontent.py', '-v', '--target_arch', 'x64']' returned non-zero exit status 1
```

While this is obviously deep in the chromium build steps, the static library build succeeds without issue, and so this might be due to setup or bootstrapping of the build.

**Comment by zcbenz** [comment]
I'm merging this to #6031 since they are essentially the same thing.

Currently building shared library version is not considered in the `--build_libchromiumcontent` flag, this flag's whole purpose was to make it easier to build for different Linux platforms.

**Comment by tomotvos** [comment]
The two issues are related, for sure, but not quite the same which is why I elected to make this one. The wording in #6031 is unfortunate. Really, when working with chromium, you want to do two things: build locally with PDBs available for debugging (and in the only practical way, which is to use shared libraries), and build a DEBUG version of chromium to get an extra boost of debugging power.

I don't think that --build_libchromiumcontent should be reserved for Linux...that seems unnecessarily narrow.

And yes, the Python script hard-codes the static library version, but it is trivial to change to "shared_library" or, ideally, pass on the command line. Further, I would argue that when you want to build chromium locally, would it not be in a debugging context when you want shared libraries for efficient electron linking?
