### ISSUE TITLE
Webview: preload js containing require() fails with ReferenceError: System is not defined

### ISSUE THREAD

**Issue by suchafreak** [electron/electron#6077]
Electron version: 1.2.2
Operating system: Windows 7 (64-bit)

Using a preload script with a webview, containing `require` gives the following exception 

```
...\node_modules\electron-prebuilt\dist\resources\electron.as…:131 ReferenceError: System is not defined
    at Object.<anonymous> (...\modules\wl-electron\dist\electron-package\scripts\vendor\Rx.js:207:1)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (...\dist\electron-package\wl-select.js:3:10)
    at Module._compile (module.js:541:32)(anonymous function) @ ...\wl-electron\node_modules\electron-prebuilt\dist\resources\electron.as…:131

```

Stripped down preload script:
`var Rx= require('./scripts/vendor/Rx.js');`

index.html containing webview:
```
<webview id="wl-preview" src="https://google.ch"
             preload="./wl-select.js" autosize="on" style="height: 740px;"></webview>

```
The BrowserWindow that loads the index.html is created like this:

`new BrowserWindow({width: 960, height: 480})`

So it should have nodeintegration enabled by default. But even setting nodeintegration explicitly on the webview doesn't help.

What am I missing or is this a bug? 
Regards,
-sascha

**Comment by suchafreak** [comment]
OK, found the problem: I was loading the wrong file. Should be Rx.umd.min.js - has nothing to do with electron. My mistake. Closing.
