### ISSUE TITLE
addDevToolsExtension() is missing from the BrowserWindow object.

### ISSUE THREAD

**Issue by SMLMRKHLMS** [electron/electron#6083]
* Electron version: 1.2.2
* Operating system: OS X El Capitan (Version 10.11)

I am attempting to add the React Dev Tools extension; however, when I try to utilize the `addDevToolsExtension()` method, I receive the following error:
```
App threw an error during load
TypeError: BrowserWindow.addDevToolsExtension is not a function
    at Object.<anonymous> (/Users/markholmes/Sites/electron-test/main.js:5:27)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at loadApplicationPackage (/Users/markholmes/Sites/electron-test/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/default_app.asar/main.js:267:12)
    at Object.<anonymous> (/Users/markholmes/Sites/electron-test/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/default_app.asar/main.js:302:5)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
```

I also logged the BrowserWindow object to the console, and this is what I am seeing:
```
{ [Function: BrowserWindow]
  fromId: [Function],
  getAllWindows: [Function],
  getFocusedWindow: [Function],
  fromWebContents: [Function],
  fromDevToolsWebContents: [Function] }
```

As you can see `addDevToolsExtension()` is nowhere to be found.

**Comment by kevinsawicki** [comment]
I believe that method is only available after the `ready` event fires on the `app`.

This should either be fixed to be available before `ready` or documented as such.

**Comment by SMLMRKHLMS** [comment]
@kevinsawicki Ah, I see. Thank you.

**Comment by kevinsawicki** [comment]
I'm going to reopen this to make sure we update these docs with this important information.

**Comment by vyorkin** [comment]
Maybe it should be mentioned here also https://github.com/electron/devtron/blame/master/README.md#L35.
And here http://electron.atom.io/devtron/, at the bottom, in the "Get started" section.
