### ISSUE TITLE
[build] [windows] Build failed Error: %1 is not a valid Win32 application

### ISSUE THREAD

**Issue by nhandl3** [electron/electron#629]
I have tried with:
- nodejs 32bit 0.10.31
- build nodejs from master branch (0.13.0-pre)
- cygwin
- cmd
- Visual Studio cmd.

All cause the same error as below.
Move to shorter path (d:\toollib\atom-editor\atom-shell -> c:\atomshell) can't help.
I cannot figure out what kind of this problem is. Please help, thank you.

```
Microsoft Windows [Version 6.1.7601]
Copyright (c) 2009 Microsoft Corporation.  All rights reserved.

d:\toollib\atom-editor\atom-shell>python script\bootstrap.py -v
Running in verbose mode
Synchronizing submodule url for 'vendor/breakpad'
Synchronizing submodule url for 'vendor/brightray'
Synchronizing submodule url for 'vendor/depot_tools'
Synchronizing submodule url for 'vendor/native_mate'
Synchronizing submodule url for 'vendor/node'



> atom-shell@0.15.9 preinstall d:\toollib\atom-editor\atom-shell
> node -e 'process.exit(0)'



module.js:356
  Module._extensions[extension](this, filename);
                               ^
Error: %1 is not a valid Win32 application.
d:\toollib\atom-editor\atom-shell\node_modules\atom-package-manager\node_modules\keytar\build\Release\keytar.node
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (d:\toollib\atom-editor\atom-shell\node_modules\atom-package-manager\node_modules\keytar\lib\keytar.js:4:12)
    at Object.<anonymous> (d:\toollib\atom-editor\atom-shell\node_modules\atom-package-manager\node_modules\keytar\lib\keytar.js:58:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)

Traceback (most recent call last):
  File "script\bootstrap.py", line 119, in <module>
    sys.exit(main())
  File "script\bootstrap.py", line 25, in main
    update_atom_modules('spec')
  File "script\bootstrap.py", line 73, in update_atom_modules
    execute([apm, 'install'])
  File "d:\toollib\atom-editor\atom-shell\script\lib\util.py", line 142, in execute
    raise e
subprocess.CalledProcessError: Command '['d:\\toollib\\atom-editor\\atom-shell\\node_modules\\atom-package-manager\\bin\\apm.cmd', 'install']' returned non-zero exit status 8

d:\toollib\atom-editor\atom-shell>
```

**Comment by havenchyk** [comment]
Hmm. But is it possible to run packaged 32bit application of 64bit Windows? I got the same error.
