### ISSUE TITLE
Electron and node express cluster issue 

### ISSUE THREAD

**Issue by ghaith-bash-imam** [electron/electron#6337]
"electron": "^0.4.1"
    "electron-packager": "^7.1.0"
    "electron-prebuilt": "^1.2.5"
    "express": "^4.14.0"

i am working on new app where i have to use cluster inside (express) electron .

```js
'use strict';

const electron			= require('electron');
const atom          	= electron.app
const BrowserWindow 	= electron.BrowserWindow 							
const dialog        	= electron.dialog;
const ipcMain       	= electron.ipcMain;
var cluster 			= require('cluster');
var numWorkers 			= require('os').cpus().length;
//------------------------------------------------------------
function createWindow() {
     var mainWindow = new BrowserWindow({
		  								width       	: 800, 
		  								height      	: 600,
		  								webPreferences	:{ 
			  								  				webSecurity 					 : false,
			  								  				allowDisplayingInsecureContent   : true,
			  								  				allowRunningInsecureContent      : true,
			  								  				experimentalFeatures             : true,
			  								  				experimentalCanvasFeatures		 : true
		  								  				}
	});
	//mainWindow.loadURL("file://"+_config.pathes.atom_UI+'index.html');
	mainWindow.loadURL("file://"+__dirname+'index.html');
	mainWindow.webContents.openDevTools();
	//_config.Dodebug?mainWindow.webContents.openDevTools():"";
	mainWindow.on('closed', () => {
    	mainWindow = null;
  	});
}
//------------------------------------------------------------
function init_atom(){
	atom.commandLine.appendSwitch("ignore-certificate-errors");
	atom.commandLine.appendSwitch("allow-running-insecure-content");
	atom.commandLine.appendSwitch("enable-usermedia-screen-capturing");
	
	atom.on('ready', createWindow);
		atom.on('window-all-closed', () => {
		  if (process.platform !== 'darwin') {
		    app.quit();
		  }
	});
	atom.on('activate', () => {
	  	if (win === null) {
	    	createWindow();
	  	}
	});
}
//------------------------------------------------------------
//------------------------------------------------------------
//------------------------------------------------------------
//------------------------------------------------------------
if(cluster.isMaster) {
	init_atom();
	console.log('Master cluster setting up ' + numWorkers + ' workers...');
    for(var i = 0; i < numWorkers; i++) {
        cluster.fork();
    }
    cluster.on('online', function(worker) {
        console.log('Worker ' + worker.process.pid + ' is online');
    });
    cluster.on('exit', function(worker, code, signal) {
        console.log('Worker ' + worker.process.pid + ' died with code: ' + code + ', and signal: ' + signal);
        console.log('Starting a new worker');
        cluster.fork();
    });
}else{
	var express				= require('express');
	var app     			= express();
	app.all('/*', function(req, res) {
	    res.send('process ' + process.pid + ' says hello!').end();
	})
    var server = app.listen(2000, function() {
        console.log('Process ' + process.pid + ' is listening to all incoming requests');
    });
}
```

in development every thing works as expected ,unlike when i package my app and run it from terminal  .

`Error: Cannot find module '/output/CMS-darwin-x64/CMS.app/Contents/MacOS/undefined'
    at Function.Module._resolveFilename (module.js:438:15)
    at Function.Module._load (module.js:386:25)
    at Function.Module.runMain (module.js:575:10)
    at startup (node.js:168:18)
    at node.js:457:3`

Any idea?

**Comment by zcbenz** [comment]
The cluster module works by forking a node process and passing current argv to it, so once your packaged your app the cluster module won't get the correct argv.

I suggest separating your server code into a script, and then use `child_process.fork` to execute it.

**Comment by kikill95** [comment]
@zcbenz you suggestion works very well
