### ISSUE TITLE
Cannot read property 'guest' of undefined

### ISSUE THREAD

**Issue by Aluxian** [electron/electron#6398]
* Electron version: v0.37.6
* Operating system: Any

Reported by one of [Whatsie](https://github.com/Aluxian/Whatsie)'s users [here](https://github.com/Aluxian/Whatsie/issues/211).

It happens after pressing `CtrlOrCmd+R` repeatedly, which calls `browserWindow.reload();`. So basically, in order to reproduce you have to call `browserWindow.reload();` repeatedly, as fast as possible.

```
TypeError: Cannot read property 'guest' of undefined
    at attachGuest (/opt/whatsie/resources/electron.asar/browser/guest-view-manager.js:163:42)
    at EventEmitter.<anonymous> (/opt/whatsie/resources/electron.asar/browser/guest-view-manager.js:212:10)
    at emitMany (events.js:121:13)
    at EventEmitter.emit (events.js:195:7)
    at EventEmitter.<anonymous> (/opt/whatsie/resources/electron.asar/browser/api/web-contents.js:128:25)
    at emitTwo (events.js:100:13)
    at EventEmitter.emit (events.js:185:7)
```

Has this been encountered before?

**Comment by Aluxian** [comment]
Note: I can't reproduce this in Electron 1.2.6 anymore, I'll ask the user to update and test again.

**Comment by Aluxian** [comment]
User not replying, I can't reproduce, no one seems to be having this issue as well, so closing.
