### ISSUE TITLE
Gulp build error

### ISSUE THREAD

**Issue by rgavs** [electron/electron#6732]
Operating system:
* Archlinux kernel 4.6.4

I have been able to use normally, but attempting to build yields the following error message, while I had been able to do so before.

<pre><code>$ gulp package:linux:64
&#8942
Packaging app for platform linux x64 using electron v1.3.2
[11:44:30] 'package:linux:64' errored after 35 s
[11:44:30] Error: Error: ENOENT: no such file or directory, stat '/home/ryan/workspace/GPMDP
node_modules/mocha/node_modules/.bin/supports-color'
at formatError (/usr/lib/node_modules/gulp/bin/gulp.js:169:10)
at Gulp.<anonymous> (/usr/lib/node_modules/gulp/bin/gulp.js:195:15)
at emitOne (events.js:96:13)
    at Gulp.emit (events.js:188:7)
    at Gulp.Orchestrator._emitTaskDone (/home/ryan/workspace/GPMDP/node_modules/orchestrator/index.js:264:8)
    at /home/ryan/workspace/GPMDP/node_modules/orchestrator/index.js:275:23
    at finish (/home/ryan/workspace/GPMDP/node_modules/orchestrator/lib/runTask.js:21:8)
    at cb (/home/ryan/workspace/GPMDP/node_modules/orchestrator/lib/runTask.js:29:3)
    at /home/ryan/workspace/GPMDP/node_modules/electron-packager/index.js:211:23
    at end (/home/ryan/workspace/GPMDP/node_modules/run-series/index.js:8:15)
    at done (/home/ryan/workspace/GPMDP/node_modules/run-series/index.js:11:10)
    at each (/home/ryan/workspace/GPMDP/node_modules/run-series/index.js:16:43)
    at buildLinuxApp (/home/ryan/workspace/GPMDP/node_modules/electron-packager/linux.js:10:23)
    at /home/ryan/workspace/GPMDP/node_modules/electron-packager/common.js:223:23
    at end (/home/ryan/workspace/GPMDP/node_modules/run-series/index.js:8:15)
    at done (/home/ryan/workspace/GPMDP/node_modules/run-series/index.js:11:10)
    at each (/home/ryan/workspace/GPMDP/node_modules/run-series/index.js:16:43)
    at doneOne (/home/ryan/workspace/GPMDP/node_modules/electron-packager/node_modules/fs-extra/lib/copy/ncp.js:237:23)
    at /home/ryan/workspace/GPMDP/node_modules/electron-packager/node_modules/fs-extra/lib/copy/ncp.js:122:11
    at /home/ryan/workspace/GPMDP/node_modules/graceful-fs/polyfills.js:211:15
    at FSReqWrap.oncomplete (fs.js:123:15)</code></pre>

I guess it's not finding my `/node_modules/mocha/node_modules/.bin/supports_color` directory for some reason, though I checked and it does exist
<pre><code>$ ls node_modules/mocha/node_modules/.bin/
supports_color</code></pre>
I don't know if this is an upstream electron issue (I did reinstall it) or some wonkiness on my machine... Either way, it still runs as intended, just an issue in this build process

**Comment by kevinsawicki** [comment]
> I don't know if this is an upstream electron issue

I don't think it is, it looks like a possible `electron-packager` issue or `grunt` issue, or some local corruption.

You might want to try cleaning out `node_modules` completely, reinstalling all the modules, and see if the issue persists.

Closing this out here, please open an issue on https://github.com/electron-userland/electron-packager if this issue persists.

**Comment by rgavs** [comment]
I don''t mean to reopen the issue, but just to say sorry I actually meant to post this within the corresponding electron project (Google Play Music Desktop Player); not here. Thanks though

**Comment by MarshallOfSound** [comment]
@rgavs Just uninstall and cleanly install.  It looks like NPM glitched
