### ISSUE TITLE
HTTPError: HTTP Error 403: Forbidden (libchromiumcontent) - bootstrapping on Windows 7 x32

### ISSUE THREAD

**Issue by Ldes** [electron/electron#6778]
Hi. Same trouble.

* Electron version: 1.3.2
* Operating system:  Windows 7 32bit
* MVS2015 Community Edition
* Node: v6.3.1-x86
* Command Prompt: as adminstrator

`python script\bootstrap.py -v --target_arch=ia32`

>C:\Python27\python.exe C:\Users\IEUser\Desktop\electron\electron\vendor\brightray\script\bootstrap --commit 086d162df096
2c12d2db5a9fbe488aa52ad9a327 --target_arch ai32 https://s3.amazonaws.com/github-janky-artifacts/libchromiumcontent
Downloading libchromiumcontent.zip...
https://s3.amazonaws.com/github-janky-artifacts/libchromiumcontent/win/ai32/086d162df0962c12d2db5a9fbe488aa52ad9a327/lib
chromiumcontent.zip
Traceback (most recent call last):
  File "C:\Users\IEUser\Desktop\electron\electron\vendor\brightray\vendor\libchromiumcontent\script\download", line 180,
 in <module>
    sys.exit(main())
  File "C:\Users\IEUser\Desktop\electron\electron\vendor\brightray\vendor\libchromiumcontent\script\download", line 61,
in main
    args.force)
  File "C:\Users\IEUser\Desktop\electron\electron\vendor\brightray\vendor\libchromiumcontent\script\download", line 126,
 in download_if_needed
    download(destination, base_url, commit, filename)
  File "C:\Users\IEUser\Desktop\electron\electron\vendor\brightray\vendor\libchromiumcontent\script\download", line 136,
 in download
    download_and_extract(destination, url)
  File "C:\Users\IEUser\Desktop\electron\electron\vendor\brightray\vendor\libchromiumcontent\script\download", line 149,
 in download_and_extract
    with contextlib.closing(urllib2.urlopen(url)) as u:
  File "C:\Python27\lib\urllib2.py", line 126, in urlopen
    return _opener.open(url, data, timeout)
  File "C:\Python27\lib\urllib2.py", line 397, in open
    response = meth(req, response)
  File "C:\Python27\lib\urllib2.py", line 510, in http_response
    'http', request, response, code, msg, hdrs)
  File "C:\Python27\lib\urllib2.py", line 435, in error
    return self._call_chain(*args)
  File "C:\Python27\lib\urllib2.py", line 369, in _call_chain
    result = func(*args)
  File "C:\Python27\lib\urllib2.py", line 518, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden
Traceback (most recent call last):
  File "C:\Users\IEUser\Desktop\electron\electron\vendor\brightray\script\bootstrap", line 98, in <module>
    sys.exit(main())
  File "C:\Users\IEUser\Desktop\electron\electron\vendor\brightray\script\bootstrap", line 31, in main
    args.libcc_static_library_path)
  File "C:\Users\IEUser\Desktop\electron\electron\vendor\brightray\script\bootstrap", line 86, in setup_libchromiumconte
nt
    subprocess.check_call([sys.executable, download, '-s'] + args)
  File "C:\Python27\lib\subprocess.py", line 504, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Python27\\python.exe', 'C:\\Users\\IEUser\\Desktop\\electron\\electron\\ve
ndor\\brightray\\vendor\\libchromiumcontent\\script\\download', '-s', '-f', '-c', '086d162df0962c12d2db5a9fbe488aa52ad9a
327', '--target_arch', 'ai32', 'https://s3.amazonaws.com/github-janky-artifacts/libchromiumcontent', 'C:\\Users\\IEUser\
\Desktop\\electron\\electron\\vendor\\brightray\\vendor\\download\\libchromiumcontent']' returned non-zero exit status 1

> None
Traceback (most recent call last):
  File ".\script\bootstrap.py", line 265, in <module>
    sys.exit(main())
  File ".\script\bootstrap.py", line 61, in main
    libcc_static_library_path)
  File ".\script\bootstrap.py", line 155, in bootstrap_brightray
    execute_stdout([sys.executable, bootstrap] + args)
  File "C:\Users\IEUser\Desktop\electron\electron\script\lib\util.py", line 180, in execute_stdout
    raise e
subprocess.CalledProcessError: Command '['C:\\Python27\\python.exe', 'C:\\Users\\IEUser\\Desktop\\electron\\electron\\ve
ndor\\brightray\\script\\bootstrap', '--commit', '086d162df0962c12d2db5a9fbe488aa52ad9a327', '--target_arch', 'ai32', 'h
ttps://s3.amazonaws.com/github-janky-artifacts/libchromiumcontent']' returned non-zero exit status 1

**Comment by kevinsawicki** [comment]
Electron requires Windows 8 or above, Windows 7 is no longer supported, closing this out.

**Comment by Ldes** [comment]
Ok. Just fix build-instructions-windows.md, for no frustrating by `Prerequisites` section ;)

**Comment by kevinsawicki** [comment]
> Electron requires Windows 8 or above, Windows 7 is no longer supported, closing this out.

My apologies, I totally mispoke, Windows 7 is still supported, Windows Vista isn't.

**Comment by kevinsawicki** [comment]
> --target_arch ai32 https://s3.amazonaws.com/github-janky-artifacts/libchromiumcontent

That line from the output you provided looks wrong, did you perhaps run --target_arch ai32` instead of `--target_arch ia32`?

**Comment by Ldes** [comment]
All ok with `ia32`
Looks like ~~keyboard~~hands is broken. My bad, I`m sorry.
