### ISSUE TITLE
Error with dgram UDP socket bind

### ISSUE THREAD

**Issue by khuongduybui** [electron/electron#689]
Consider this very simple "app.js" file:

```
require('app').on('ready', function() {
  require('dgram').createSocket('udp4').bind(60547);
});
```

With atom-shell up to 0.13.3, I can run multiple atom-shell instances for this app.
From atom-shell 0.14.0 and later I can only run ONE instance. Other instances will receive an uncaught exception

```
Error: bind EADDRINUSE
    at exports._errnoException (util.js:742:11)
    at dgram.js:222:28
    at dns.js:82:18
    at process._tickCallback (node.js:378:11)
```

**Comment by khuongduybui** [comment]
You are correct.
From node 0.11.13, the following code works:
```
require('app').on('ready', function() {
  require('dgram').createSocket({'type': 'udp4', 'reuseAddr': true}).bind(60547);
});
```
I put this on here in case someone have the same problem.
