### ISSUE TITLE
Problem with two windows 

### ISSUE THREAD

**Issue by fabdelgado** [electron/electron#6904]
* Electron version: 1.3
* Operating system: Mac, Windows

Hi , One question, I create two windows in electron js, after close window secondary and re open, launch error.

`Uncaught Exception:
Error: Object has been destroyed
    at Error (native)
    at click (/Users/fabiandelgado/desarrollo/dobled/tilo-desktop/build/background.js:181:17)
    at MenuItem.click (/Users/fabiandelgado/desarrollo/dobled/tilo-desktop/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/electron.asar/browser/api/menu-item.js:59:9)
    at Function.executeCommand (/Users/fabiandelgado/desarrollo/dobled/tilo-desktop/node_modules/electron-prebuilt/dist/Electron.app/Contents/Resources/electron.asar/browser/api/menu.js:121:15)`

Try add this code, not close window with ctrl + c in console

`prefsWindow.on('close', function(e){
        e.preventDefault();
        prefsWindow.hide();
    });`

Any idea?

**Comment by kevinsawicki** [comment]
Can you include what is happening on this line of code?

`/Users/fabiandelgado/desarrollo/dobled/tilo-desktop/build/background.js:181:17`

**Comment by fabdelgado** [comment]
@kevinsawicki  yes, https://gist.github.com/fabdelgado/f0b9fb4acf4dba22c6738684f88f8f23

**Comment by kevinsawicki** [comment]
@fabdelgado that file doesn't have a line `181` from your stack trace, which line in that file is being called when the error occurs?

**Comment by zcbenz** [comment]
Closing until more information is provided.
