### ISSUE TITLE
`npm run lint-cpp` fails on Linux

### ISSUE THREAD

**Issue by sboekhoff** [electron/electron#7070]
* Electron version: v1.3.5 commit 02ce727ff6f6d8afbc6235ab3e1bb127e765b2ab
* Operating system: Linux Mint 18 Cinnamon 64-bit

## TL;DR;

`/script/cpplint.py` tries to start the linting-script from the wrong source:

Possible solution:

```
diff --git a/script/cpplint.py b/script/cpplint.py
index 7ec3537..affa9a2 100755
--- a/script/cpplint.py
+++ b/script/cpplint.py
@@ -37,7 +37,7 @@ def list_files(directories, filters):
 
 
 def call_cpplint(files):
-  cpplint = os.path.join(SOURCE_ROOT, 'vendor', 'depot_tools', 'cpplint.py')
+  cpplint = os.path.join(SOURCE_ROOT, 'script', 'cpplint.py')
   execute([sys.executable, cpplint] + files)
```

## Steps to reproduce

I ran the following sequence of commands:

```shell
cd /tmp
git clone https://github.com/electron/electron.git
cd electron
npm install
npm run lint-js
npm run lint-docs
npm run lint-cpp
```
which gave the following output:

```
> electron@1.3.5 lint-cpp /tmp/electron
> python ./script/cpplint.py

/usr/bin/python: can't open file '/tmp/electron/vendor/depot_tools/cpplint.py': [Errno 2] No such file or directory

Traceback (most recent call last):
  File "./script/cpplint.py", line 45, in <module>
    sys.exit(main())
  File "./script/cpplint.py", line 26, in main
    call_cpplint(list(set(files) - set(IGNORE_FILES)))
  File "./script/cpplint.py", line 41, in call_cpplint
    execute([sys.executable, cpplint] + files)
  File "/tmp/electron/script/lib/util.py", line 170, in execute
    raise e
subprocess.CalledProcessError: Command '['/usr/bin/python', '/tmp/electron/vendor/depot_tools/cpplint.py', 'atom/common/draggable_region.h', 'atom/common/asar/archive.h', 'atom/browser/atom_browser_client.h', 'atom/common/keyboard_util.cc', 'atom/browser/ui/views/menu_model_adapter.cc', 'atom/browser/relauncher_mac.cc', 'atom/browser/net/url_request_fetch_job.h', 'atom/browser/browser.cc', 'atom/browser/atom_permission_manager.h', 'atom/common/api/remote_object_freer.cc', 'atom/browser/net/url_request_async_asar_job.cc', 'atom/browser/ui/x/x_window_utils.h', 'atom/common/native_mate_converters/gurl_converter.h', 'atom/browser/ui/win/atom_desktop_window_tree_host_win.h', 'atom/common/api/remote_object_freer.h', 'atom/browser/api/trackable_object.h', 'atom/common/native_mate_converters/accelerator_converter.h', 'atom/browser/api/atom_api_auto_updater.h', 'atom/app/node_main.cc', 'atom/browser/ui/win/notify_icon_host.cc', 'atom/browser/ui/views/win_frame_view.cc', 'atom/common/native_mate_converters/gfx_converter.cc', 'atom/browser/ui/views/menu_model_adapter.h', 'atom/common/api/event_emitter_caller.h', 'atom/common/color_util.h', 'atom/browser/common_web_contents_delegate_views.cc', 'atom/common/native_mate_converters/image_converter.h', 'atom/browser/browser_linux.cc', 'atom/common/native_mate_converters/net_converter.h', 'atom/common/crash_reporter/linux/crash_dump_handler.h', 'atom/app/atom_main.h', 'atom/browser/api/atom_api_system_preferences.h', 'atom/browser/native_window_views_win.cc', 'atom/browser/ui/views/global_menu_bar_x11.cc', 'atom/browser/node_debugger.h', 'atom/browser/javascript_environment.cc', 'atom/browser/ui/message_box.h', 'atom/common/api/atom_api_native_image.cc', 'atom/browser/api/atom_api_cookies.cc', 'atom/browser/ui/tray_icon_observer.h', 'atom/common/api/object_life_monitor.h', 'atom/browser/ui/x/window_state_watcher.h', 'atom/common/node_bindings_win.cc', 'atom/browser/web_contents_permission_helper.h', 'atom/common/crash_reporter/crash_reporter_linux.cc', 'atom/common/api/remote_callback_freer.h', 'atom/browser/ui/views/frameless_view.h', 'atom/common/api/atom_api_v8_util.cc', 'atom/common/platform_util_win.cc', 'atom/browser/api/atom_api_power_monitor.h', 'atom/browser/net/atom_url_request_job_factory.h', 'atom/browser/atom_browser_main_parts_posix.cc', 'atom/browser/login_handler.cc', 'atom/browser/unresponsive_suppressor.h', 'atom/browser/api/atom_api_debugger.h', 'atom/browser/api/atom_api_download_item.cc', 'atom/browser/ui/views/menu_delegate.cc', 'atom/browser/ui/x/window_state_watcher.cc', 'atom/browser/web_dialog_helper.cc', 'atom/browser/api/atom_api_web_contents.cc', 'atom/browser/ui/win/jump_list.cc', 'atom/browser/api/atom_api_web_request.cc', 'atom/browser/ui/win/notify_icon_host.h', 'atom/browser/ui/views/submenu_button.h', 'atom/common/atom_version.h', 'atom/browser/atom_javascript_dialog_manager.cc', 'atom/browser/relauncher.cc', 'atom/browser/relauncher.h', 'atom/browser/web_contents_preferences.cc', 'atom/browser/api/atom_api_tray.cc', 'atom/common/api/locker.h', 'atom/common/node_bindings.h', 'atom/browser/browser_win.cc', 'atom/browser/net/url_request_buffer_job.h', 'atom/browser/bridge_task_runner.h', 'atom/browser/ui/win/jump_list.h', 'atom/browser/native_window.h', 'atom/browser/net/asar/url_request_asar_job.h', 'atom/browser/ui/win/taskbar_host.h', 'atom/browser/atom_browser_main_parts.h', 'atom/common/atom_command_line.h', 'atom/browser/osr/osr_render_widget_host_view.h', 'atom/renderer/preferences_manager.cc', 'atom/browser/native_window_mac.h', 'atom/browser/javascript_environment.h', 'atom/browser/ui/win/message_handler_delegate.cc', 'atom/common/asar/archive.cc', 'atom/common/keyboard_util.h', 'atom/browser/api/atom_api_window.cc', 'atom/common/native_mate_converters/accelerator_converter.cc', 'atom/browser/net/asar/url_request_asar_job.cc', 'atom/browser/native_window_views.h', 'atom/browser/ui/file_dialog_win.cc', 'atom/browser/ui/views/frameless_view.cc', 'atom/browser/auto_updater.h', 'atom/browser/ui/tray_icon_cocoa.h', 'atom/browser/node_debugger.cc', 'atom/browser/web_contents_preferences.h', 'atom/browser/web_view_manager.cc', 'atom/renderer/atom_renderer_client.cc', 'atom/common/api/atom_api_crash_reporter.cc', 'atom/browser/atom_quota_permission_context.cc', 'atom/browser/atom_browser_main_parts.cc', 'atom/browser/native_window_views.cc', 'atom/browser/api/atom_api_web_request.h', 'atom/browser/api/event_emitter.cc', 'atom/browser/atom_browser_context.cc', 'atom/common/native_mate_converters/gfx_converter.h', 'atom/browser/api/atom_api_auto_updater.cc', 'atom/browser/login_handler.h', 'atom/browser/ui/win/atom_desktop_window_tree_host_win.cc', 'atom/common/crash_reporter/crash_reporter_mac.h', 'atom/browser/ui/views/win_frame_view.h', 'atom/common/color_util.cc', 'atom/browser/api/atom_api_session.cc', 'atom/renderer/node_array_buffer_bridge.h', 'atom/browser/ui/views/menu_delegate.h', 'atom/app/atom_main_delegate.cc', 'atom/browser/api/atom_api_menu_mac.h', 'atom/browser/ui/accelerator_util_views.cc', 'atom/common/native_mate_converters/value_converter.cc', 'atom/common/node_bindings_linux.h', 'atom/common/atom_command_line.cc', 'atom/browser/api/atom_api_debugger.cc', 'atom/browser/net/url_request_fetch_job.cc', 'atom/browser/ui/views/menu_bar.cc', 'atom/browser/net/url_request_async_asar_job.h', 'atom/browser/net/atom_cert_verifier.cc', 'atom/browser/atom_browser_client.cc', 'atom/browser/ui/accelerator_util.cc', 'atom/browser/ui/views/menu_bar.h', 'atom/browser/net/url_request_string_job.cc', 'atom/common/node_includes.h', 'atom/common/mouse_util.h', 'atom/common/crash_reporter/crash_reporter_win.h', 'atom/browser/ui/atom_menu_model.h', 'atom/common/native_mate_converters/callback.cc', 'atom/renderer/atom_render_view_observer.h', 'atom/browser/window_list.cc', 'atom/browser/net/url_request_string_job.h', 'atom/browser/api/save_page_handler.cc', 'atom/browser/api/frame_subscriber.h', 'atom/common/native_mate_converters/net_converter.cc', 'atom/browser/ui/file_dialog.h', 'atom/browser/osr/osr_output_device.cc', 'atom/browser/net/asar/asar_protocol_handler.h', 'atom/browser/api/atom_api_power_save_blocker.cc', 'atom/browser/api/atom_api_menu.h', 'atom/browser/net/http_protocol_handler.cc', 'atom/browser/web_view_guest_delegate.cc', 'atom/browser/browser.h', 'atom/browser/web_view_guest_delegate.h', 'atom/browser/atom_resource_dispatcher_host_delegate.h', 'atom/browser/api/atom_api_menu.cc', 'atom/browser/net/atom_cert_verifier.h', 'atom/browser/atom_security_state_model_client.cc', 'atom/renderer/preferences_manager.h', 'atom/browser/browser_observer.h', 'atom/browser/net/js_asker.h', 'atom/renderer/api/atom_api_spell_check_client.cc', 'atom/browser/lib/bluetooth_chooser.cc', 'atom/browser/web_dialog_helper.h', 'atom/browser/atom_resource_dispatcher_host_delegate.cc', 'atom/browser/api/atom_api_app.h', 'atom/browser/ui/win/notify_icon.cc', 'atom/browser/atom_download_manager_delegate.h', 'atom/browser/api/atom_api_download_item.h', 'atom/renderer/api/atom_api_web_frame.cc', 'atom/browser/web_contents_permission_helper.cc', 'atom/common/node_bindings_mac.cc', 'atom/common/native_mate_converters/blink_converter.cc', 'atom/app/uv_task_runner.h', 'atom/browser/relauncher_win.cc', 'atom/browser/common_web_contents_delegate.h', 'atom/common/native_mate_converters/callback.h', 'atom/renderer/guest_view_container.cc', 'atom/browser/api/trackable_object.cc', 'atom/common/key_weak_map.h', 'atom/browser/ui/views/submenu_button.cc', 'atom/browser/api/atom_api_protocol.h', 'atom/renderer/api/atom_api_renderer_ipc.cc', 'atom/browser/net/url_request_buffer_job.cc', 'atom/browser/window_list_observer.h', 'atom/app/atom_library_main.h', 'atom/browser/ui/x/event_disabler.cc', 'atom/browser/ui/x/event_disabler.h', 'atom/browser/ui/tray_icon_gtk.h', 'atom/browser/api/atom_api_protocol.cc', 'atom/app/atom_content_client.h', 'atom/browser/net/http_protocol_handler.h', 'atom/browser/native_window_observer.h', 'atom/browser/osr/osr_web_contents_view.h', 'atom/common/asar/scoped_temporary_file.cc', 'atom/browser/lib/bluetooth_chooser.h', 'atom/browser/mac/dict_util.h', 'atom/browser/render_process_preferences.h', 'atom/common/api/atom_api_shell.cc', 'atom/common/native_mate_converters/v8_value_converter.h', 'atom/browser/osr/osr_render_widget_host_view.cc', 'atom/browser/api/event_emitter.h', 'atom/common/chrome_version.h', 'atom/common/native_mate_converters/content_converter.h', 'atom/browser/atom_access_token_store.h', 'atom/browser/ui/win/taskbar_host.cc', 'atom/browser/api/save_page_handler.h', 'atom/common/api/atom_api_native_image.h', 'atom/common/native_mate_converters/image_converter.cc', 'atom/browser/api/atom_api_desktop_capturer.cc', 'atom/app/atom_content_client.cc', 'atom/common/native_mate_converters/ui_base_types_converter.h', 'atom/browser/unresponsive_suppressor.cc', 'atom/browser/atom_security_state_model_client.h', 'atom/browser/relauncher_linux.cc', 'atom/common/crash_reporter/win/crash_service_main.cc', 'atom/browser/net/atom_url_request_job_factory.cc', 'atom/browser/api/frame_subscriber.cc', 'atom/common/api/event_emitter_caller.cc', 'atom/browser/window_list.h', 'atom/common/options_switches.h', 'atom/browser/api/atom_api_web_view_manager.cc', 'atom/common/api/atom_bindings.cc', 'atom/common/asar/scoped_temporary_file.h', 'atom/browser/net/js_asker.cc', 'atom/common/crash_reporter/crash_reporter_win.cc', 'atom/browser/net/asar/asar_protocol_handler.cc', 'atom/common/atom_constants.h', 'atom/renderer/node_array_buffer_bridge.cc', 'atom/browser/ui/win/message_handler_delegate.h', 'atom/browser/net/atom_network_delegate.cc', 'atom/browser/api/atom_api_render_process_preferences.h', 'atom/browser/ui/drag_util_views.cc', 'atom/browser/web_view_manager.h', 'atom/browser/ui/atom_menu_model.cc', 'atom/browser/ui/message_box_win.cc', 'atom/browser/ui/views/global_menu_bar_x11.h', 'atom/common/node_bindings_mac.h', 'atom/browser/ui/drag_util.h', 'atom/browser/net/atom_ssl_config_service.h', 'atom/browser/api/atom_api_cookies.h', 'atom/browser/render_process_preferences.cc', 'atom/browser/ui/tray_icon_win.cc', 'atom/browser/api/event.h', 'atom/browser/ui/tray_icon_gtk.cc', 'atom/browser/ui/tray_icon.h', 'atom/browser/atom_browser_context.h', 'atom/common/native_mate_converters/blink_converter.h', 'atom/common/options_switches.cc', 'atom/app/uv_task_runner.cc', 'atom/renderer/api/atom_api_web_frame.h', 'atom/app/atom_main.cc', 'atom/common/node_bindings_win.h', 'atom/browser/api/event.cc', 'atom/common/node_bindings.cc', 'atom/common/platform_util.h', 'atom/browser/ui/views/native_frame_view.cc', 'atom/common/crash_reporter/crash_reporter_linux.h', 'atom/common/native_mate_converters/value_converter.h', 'atom/browser/ui/tray_icon.cc', 'atom/browser/osr/osr_web_contents_view.cc', 'atom/common/linux/application_info.cc', 'atom/browser/native_window.cc', 'atom/common/api/locker.cc', 'atom/app/node_main.h', 'atom/common/native_mate_converters/v8_value_converter.cc', 'atom/browser/atom_quota_permission_context.h', 'atom/browser/api/atom_api_app.cc', 'atom/browser/ui/win/notify_icon.h', 'atom/browser/net/atom_network_delegate.h', 'atom/browser/atom_speech_recognition_manager_delegate.cc', 'atom/renderer/atom_renderer_client.h', 'atom/common/platform_util_linux.cc', 'atom/browser/ui/file_dialog_gtk.cc', 'atom/common/google_api_key.h', 'atom/common/atom_constants.cc', 'atom/renderer/atom_render_view_observer.cc', 'atom/browser/api/atom_api_session.h', 'atom/browser/api/atom_api_global_shortcut.h', 'atom/common/api/atom_bindings.h', 'atom/browser/atom_access_token_store.cc', 'atom/common/api/atom_api_key_weak_map.h', 'atom/common/native_mate_converters/content_converter.cc', 'atom/browser/ui/views/menu_layout.cc', 'atom/common/api/atom_api_clipboard.cc', 'atom/browser/api/atom_api_render_process_preferences.cc', 'atom/browser/ui/x/x_window_utils.cc', 'atom/browser/bridge_task_runner.cc', 'atom/browser/api/atom_api_menu_views.h', 'atom/common/api/object_life_monitor.cc', 'atom/browser/api/atom_api_global_shortcut.cc', 'atom/browser/api/atom_api_screen.h', 'atom/browser/atom_permission_manager.cc', 'atom/common/crash_reporter/crash_reporter.h', 'atom/browser/atom_javascript_dialog_manager.h', 'atom/browser/ui/accelerator_util.h', 'atom/common/crash_reporter/win/crash_service.cc', 'atom/common/mouse_util.cc', 'atom/common/asar/asar_util.h', 'atom/browser/api/atom_api_window.h', 'atom/common/crash_reporter/win/crash_service.h', 'atom/browser/api/atom_api_tray.h', 'atom/browser/api/atom_api_desktop_capturer.h', 'atom/common/asar/asar_util.cc', 'atom/app/atom_main_delegate.h', 'atom/browser/api/atom_api_menu_views.cc', 'atom/browser/api/atom_api_web_contents.h', 'atom/common/draggable_region.cc', 'atom/common/crash_reporter/win/crash_service_main.h', 'atom/common/crash_reporter/linux/crash_dump_handler.cc', 'atom/browser/osr/osr_output_device.h', 'atom/renderer/api/atom_api_spell_check_client.h', 'atom/browser/api/atom_api_content_tracing.cc', 'atom/common/node_bindings_linux.cc', 'atom/utility/atom_content_utility_client.h', 'atom/common/native_mate_converters/file_path_converter.h', 'atom/browser/auto_updater.cc', 'atom/common/native_mate_converters/string16_converter.h', 'atom/renderer/guest_view_container.h', 'atom/browser/net/atom_ssl_config_service.cc', 'atom/browser/api/atom_api_system_preferences.cc', 'atom/browser/atom_download_manager_delegate.cc', 'atom/utility/atom_content_utility_client.cc', 'atom/browser/ui/views/native_frame_view.h', 'atom/browser/api/atom_api_screen.cc', 'atom/common/crash_reporter/crash_reporter.cc', 'atom/browser/ui/message_box_gtk.cc', 'atom/browser/common_web_contents_delegate.cc', 'atom/common/api/remote_callback_freer.cc', 'atom/browser/api/atom_api_power_save_blocker.h', 'atom/browser/ui/views/menu_layout.h', 'atom/common/api/atom_api_asar.cc', 'atom/browser/api/atom_api_dialog.cc', 'atom/browser/atom_speech_recognition_manager_delegate.h', 'atom/browser/api/atom_api_power_monitor.cc']' returned non-zero exit status 2

npm ERR! Linux 4.4.0-21-generic
npm ERR! argv "/home/sven/.nvm/versions/node/v6.5.0/bin/node" "/home/sven/.nvm/versions/node/v6.5.0/bin/npm" "run" "lint-cpp"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! electron@1.3.5 lint-cpp: `python ./script/cpplint.py`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron@1.3.5 lint-cpp script 'python ./script/cpplint.py'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     python ./script/cpplint.py
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/electron/npm-debug.log
```

Content of: `/tmp/electron/npm-debug.log`

```
0 info it worked if it ends with ok
1 verbose cli [ '/home/sven/.nvm/versions/node/v6.5.0/bin/node',
1 verbose cli   '/home/sven/.nvm/versions/node/v6.5.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'lint-cpp' ]
2 info using npm@3.10.3
3 info using node@v6.5.0
4 verbose run-script [ 'prelint-cpp', 'lint-cpp', 'postlint-cpp' ]
5 info lifecycle electron@1.3.5~prelint-cpp: electron@1.3.5
6 silly lifecycle electron@1.3.5~prelint-cpp: no script for prelint-cpp, continuing
7 info lifecycle electron@1.3.5~lint-cpp: electron@1.3.5
8 verbose lifecycle electron@1.3.5~lint-cpp: unsafe-perm in lifecycle true
9 verbose lifecycle electron@1.3.5~lint-cpp: PATH: /home/sven/.nvm/versions/node/v6.5.0/lib/node_modules/npm/bin/node-gyp-bin:/tmp/electron/node_modules/.bin:/home/sven/.nvm/versions/node/v6.5.0/bin:/home/sven/.nvm/versions/node/v6.5.0/bin:/home/sven/bin/groovy-current/bin:/home/sven/bin/apache-maven/bin:/home/sven/bin/mongodb/bin:/home/sven/bin/gradle/bin:/home/sven/bin/apache-derby/bin:/home/sven/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/sven/.rvm/bin:/home/sven/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/sven/.rvm/bin
10 verbose lifecycle electron@1.3.5~lint-cpp: CWD: /tmp/electron
11 silly lifecycle electron@1.3.5~lint-cpp: Args: [ '-c', 'python ./script/cpplint.py' ]
12 silly lifecycle electron@1.3.5~lint-cpp: Returned: code: 1  signal: null
13 info lifecycle electron@1.3.5~lint-cpp: Failed to exec lint-cpp script
14 verbose stack Error: electron@1.3.5 lint-cpp: `python ./script/cpplint.py`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/home/sven/.nvm/versions/node/v6.5.0/lib/node_modules/npm/lib/utils/lifecycle.js:242:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/home/sven/.nvm/versions/node/v6.5.0/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:877:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid electron@1.3.5
16 verbose cwd /tmp/electron
17 error Linux 4.4.0-21-generic
18 error argv "/home/sven/.nvm/versions/node/v6.5.0/bin/node" "/home/sven/.nvm/versions/node/v6.5.0/bin/npm" "run" "lint-cpp"
19 error node v6.5.0
20 error npm  v3.10.3
21 error code ELIFECYCLE
22 error electron@1.3.5 lint-cpp: `python ./script/cpplint.py`
22 error Exit status 1
23 error Failed at the electron@1.3.5 lint-cpp script 'python ./script/cpplint.py'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the electron package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     python ./script/cpplint.py
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs electron
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls electron
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by thomasjo** [comment]
Everything under `/vendor` are Git submodules, so you need to initialize and clone them; run e.g.
```
git submodule update --init --recursive
```

**Comment by sboekhoff** [comment]
Thanks @thomasjo .

I haven't worked with submodules, yet.

I suspected that there is something new, after running `grep -r "depot_tools"`:

```
script/cpplint.py:40:  cpplint = os.path.join(SOURCE_ROOT, 'vendor', 'depot_tools', 'cpplint.py')
script/build.py:22:  ninja = os.path.join('vendor', 'depot_tools', 'ninja')
script/pylint.py:14:  pylint = os.path.join(SOURCE_ROOT, 'vendor', 'depot_tools', 'pylint.py')
script/pylint.py:15:  settings = ['--rcfile=vendor/depot_tools/pylintrc']
.gitmodules:7:[submodule "vendor/depot_tools"]
.gitmodules:8:	path = vendor/depot_tools
.gitmodules:9:	url = https://chromium.googlesource.com/chromium/tools/depot_tools.git
```
