### ISSUE TITLE
Passing React Component Reference through remote.js throws error

### ISSUE THREAD

**Issue by MarshallOfSound** [electron/electron#7088]
* Electron version: `1.3.5`
* Operating system: Windows

When passing a React Component from Enzyme through `remote.js` some rather interesting errors get thrown.

```bash
Error: Implement me. Unknown stdin file type!
      at process.getStdin [as stdin] (internal/process/stdio.js:82:15)
      at valueToMeta (C:\Users\Samuel\projects\Google-Play-Music-Desktop-Player-UNOFFICIAL-\node_modules\electron\dist\resources\electron.asar\renderer\api\remote.js:67:35)
      at valueToMeta (C:\Users\Samuel\projects\Google-Play-Music-Desktop-Player-UNOFFICIAL-\node_modules\electron\dist\resources\electron.asar\renderer\api\remote.js:67:18)
      at valueToMeta (C:\Users\Samuel\projects\Google-Play-Music-Desktop-Player-UNOFFICIAL-\node_modules\electron\dist\resources\electron.asar\renderer\api\remote.js:67:18)
      at valueToMeta (C:\Users\Samuel\projects\Google-Play-Music-Desktop-Player-UNOFFICIAL-\node_modules\electron\dist\resources\electron.asar\renderer\api\remote.js:67:18)
      at valueToMeta (C:\Users\Samuel\projects\Google-Play-Music-Desktop-Player-UNOFFICIAL-\node_modules\electron\dist\resources\electron.asar\renderer\api\remote.js:67:18)
      at valueToMeta (C:\Users\Samuel\projects\Google-Play-Music-Desktop-Player-UNOFFICIAL-\node_modules\electron\dist\resources\electron.asar\renderer\api\remote.js:67:18)
      at valueToMeta (C:\Users\Samuel\projects\Google-Play-Music-Desktop-Player-UNOFFICIAL-\node_modules\electron\dist\resources\electron.asar\renderer\api\remote.js:67:18)
      at valueToMeta (C:\Users\Samuel\projects\Google-Play-Music-Desktop-Player-UNOFFICIAL-\node_modules\electron\dist\resources\electron.asar\renderer\api\remote.js:67:18)
```

Admittedly, passing a React Component through IPC is probably not a good plan.  But as far as I am aware, any properties that can't be passed through would just be stripped on the way.  I don't think an error should be thrown.

Trying to make a minimal example at the moment.

**Comment by kevinsawicki** [comment]
@MarshallOfSound do you know if this was something working in previously releases that has regressed?

**Comment by MarshallOfSound** [comment]
@kevinsawicki I went back to Electron `1.1.0` and the error is thrown in all of them.

I have attached a super minimal reproduction example.  Simply download the attached zip and run the following.

```bash
npm install
npm run test-good # This will pass
npm run test-bad # This will throw the error
```

[enzyme-crash.zip](https://github.com/electron/electron/files/458720/enzyme-crash.zip)
