### ISSUE TITLE
[BUG][Win10x64] Electron will not start if the project is in a drive mapped with imdisk

### ISSUE THREAD

**Issue by ImmortalPC** [electron/electron#7152]
* Electron version:
**1.3.5**
* Operating system:
**Windows 10x64**
* Node.js:
**v6.5.0**
* Description:
```
Electron will not start if the project is in a drive mapped with imdisk. (https://sourceforge.net/projects/imdisk-toolkit/)
```
* node.js location: **C:\Program Files\nodejs\**
* project location: **R:\Temp\xxx**

* Reproduction:
```
R:\Temp> git clone https://github.com/electron/electron-quick-start.git
Cloning into 'electron-quick-start'...
remote: Counting objects: 187, done.
remote: Total 187 (delta 0), reused 0 (delta 0), pack-reused 187
Receiving objects: 100% (187/187), 30.46 KiB | 0 bytes/s, done.
Resolving deltas: 100% (86/86), done.
Checking connectivity... done.


R:\Temp> cd electron-quick-start


R:\Temp\electron-quick-start> npm install
> electron@1.3.5 postinstall R:\Temp\electron-quick-start\node_modules\electron
> node install.js

electron-quick-start@1.0.0 R:\Temp\electron-quick-start
`-- electron@1.3.5
  +-- electron-download@2.1.2
  | +-- debug@2.2.0
  | | `-- ms@0.7.1
  | +-- home-path@1.0.3
  | +-- minimist@1.2.0
  | +-- mkdirp@0.5.1
  | | `-- minimist@0.0.8
  | +-- mv@2.1.1
  | | +-- ncp@2.0.0
  | | `-- rimraf@2.4.5
  | |   `-- glob@6.0.4
  | |     +-- inflight@1.0.5
  | |     | `-- wrappy@1.0.2
  | |     +-- minimatch@3.0.3
  | |     | `-- brace-expansion@1.1.6
  | |     |   +-- balanced-match@0.4.2
  | |     |   `-- concat-map@0.0.1
  | |     +-- once@1.4.0
  | |     `-- path-is-absolute@1.0.0
  | +-- nugget@1.6.2
  | | +-- pretty-bytes@1.0.4
  | | | +-- get-stdin@4.0.1
  | | | `-- meow@3.7.0
  | | |   +-- camelcase-keys@2.1.0
  | | |   | `-- camelcase@2.1.1
  | | |   +-- decamelize@1.2.0
  | | |   +-- loud-rejection@1.6.0
  | | |   | +-- currently-unhandled@0.4.1
  | | |   | | `-- array-find-index@1.0.1
  | | |   | `-- signal-exit@3.0.0
  | | |   +-- map-obj@1.0.1
  | | |   +-- normalize-package-data@2.3.5
  | | |   | +-- hosted-git-info@2.1.5
  | | |   | +-- is-builtin-module@1.0.0
  | | |   | | `-- builtin-modules@1.1.1
  | | |   | +-- semver@5.3.0
  | | |   | `-- validate-npm-package-license@3.0.1
  | | |   |   +-- spdx-correct@1.0.2
  | | |   |   | `-- spdx-license-ids@1.2.2
  | | |   |   `-- spdx-expression-parse@1.0.3
  | | |   +-- object-assign@4.1.0
  | | |   +-- read-pkg-up@1.0.1
  | | |   | +-- find-up@1.1.2
  | | |   | | `-- path-exists@2.1.0
  | | |   | `-- read-pkg@1.1.0
  | | |   |   +-- load-json-file@1.1.0
  | | |   |   | +-- graceful-fs@4.1.6
  | | |   |   | +-- parse-json@2.2.0
  | | |   |   | | `-- error-ex@1.3.0
  | | |   |   | |   `-- is-arrayish@0.2.1
  | | |   |   | +-- pify@2.3.0
  | | |   |   | `-- strip-bom@2.0.0
  | | |   |   |   `-- is-utf8@0.2.1
  | | |   |   `-- path-type@1.1.0
  | | |   +-- redent@1.0.0
  | | |   | +-- indent-string@2.1.0
  | | |   | | `-- repeating@2.0.1
  | | |   | |   `-- is-finite@1.0.1
  | | |   | |     `-- number-is-nan@1.0.0
  | | |   | `-- strip-indent@1.0.1
  | | |   `-- trim-newlines@1.0.0
  | | +-- progress-stream@1.2.0
  | | | +-- speedometer@0.1.4
  | | | `-- through2@0.2.3
  | | |   +-- readable-stream@1.1.14
  | | |   | `-- isarray@0.0.1
  | | |   `-- xtend@2.1.2
  | | |     `-- object-keys@0.4.0
  | | +-- request@2.74.0
  | | | +-- aws-sign2@0.6.0
  | | | +-- aws4@1.4.1
  | | | +-- bl@1.1.2
  | | | | `-- readable-stream@2.0.6
  | | | |   `-- isarray@1.0.0
  | | | +-- caseless@0.11.0
  | | | +-- combined-stream@1.0.5
  | | | | `-- delayed-stream@1.0.0
  | | | +-- extend@3.0.0
  | | | +-- forever-agent@0.6.1
  | | | +-- form-data@1.0.1
  | | | | `-- async@2.0.1
  | | | |   `-- lodash@4.15.0
  | | | +-- har-validator@2.0.6
  | | | | +-- chalk@1.1.3
  | | | | | +-- ansi-styles@2.2.1
  | | | | | +-- escape-string-regexp@1.0.5
  | | | | | +-- has-ansi@2.0.0
  | | | | | | `-- ansi-regex@2.0.0
  | | | | | +-- strip-ansi@3.0.1
  | | | | | `-- supports-color@2.0.0
  | | | | +-- commander@2.9.0
  | | | | | `-- graceful-readlink@1.0.1
  | | | | +-- is-my-json-valid@2.13.1
  | | | | | +-- generate-function@2.0.0
  | | | | | +-- generate-object-property@1.2.0
  | | | | | | `-- is-property@1.0.2
  | | | | | +-- jsonpointer@2.0.0
  | | | | | `-- xtend@4.0.1
  | | | | `-- pinkie-promise@2.0.1
  | | | |   `-- pinkie@2.0.4
  | | | +-- hawk@3.1.3
  | | | | +-- boom@2.10.1
  | | | | +-- cryptiles@2.0.5
  | | | | +-- hoek@2.16.3
  | | | | `-- sntp@1.0.9
  | | | +-- http-signature@1.1.1
  | | | | +-- assert-plus@0.2.0
  | | | | +-- jsprim@1.3.0
  | | | | | +-- extsprintf@1.0.2
  | | | | | +-- json-schema@0.2.2
  | | | | | `-- verror@1.3.6
  | | | | `-- sshpk@1.10.0
  | | | |   +-- asn1@0.2.3
  | | | |   +-- assert-plus@1.0.0
  | | | |   +-- bcrypt-pbkdf@1.0.0
  | | | |   | `-- tweetnacl@0.14.3
  | | | |   +-- dashdash@1.14.0
  | | | |   | `-- assert-plus@1.0.0
  | | | |   +-- ecc-jsbn@0.1.1
  | | | |   +-- getpass@0.1.6
  | | | |   | `-- assert-plus@1.0.0
  | | | |   +-- jodid25519@1.0.2
  | | | |   +-- jsbn@0.1.0
  | | | |   `-- tweetnacl@0.13.3
  | | | +-- is-typedarray@1.0.0
  | | | +-- isstream@0.1.2
  | | | +-- json-stringify-safe@5.0.1
  | | | +-- mime-types@2.1.11
  | | | | `-- mime-db@1.23.0
  | | | +-- node-uuid@1.4.7
  | | | +-- oauth-sign@0.8.2
  | | | +-- qs@6.2.1
  | | | +-- stringstream@0.0.5
  | | | +-- tough-cookie@2.3.1
  | | | `-- tunnel-agent@0.4.3
  | | +-- single-line-log@0.4.1
  | | `-- throttleit@0.0.2
  | +-- path-exists@1.0.0
  | `-- rc@1.1.6
  |   +-- deep-extend@0.4.1
  |   +-- ini@1.3.4
  |   `-- strip-json-comments@1.0.4
  `-- extract-zip@1.5.0
    +-- concat-stream@1.5.0
    | +-- inherits@2.0.3
    | +-- readable-stream@2.0.6
    | | +-- core-util-is@1.0.2
    | | +-- isarray@1.0.0
    | | +-- process-nextick-args@1.0.7
    | | +-- string_decoder@0.10.31
    | | `-- util-deprecate@1.0.2
    | `-- typedarray@0.0.6
    +-- debug@0.7.4
    +-- mkdirp@0.5.0
    | `-- minimist@0.0.8
    `-- yauzl@2.4.1
      `-- fd-slicer@1.0.1
        `-- pend@1.2.0



R:\Temp\electron-quick-start>npm start --verbose
npm info it worked if it ends with ok
npm verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
npm verb cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'start',
npm verb cli   '--verbose' ]
npm info using npm@3.10.3
npm info using node@v6.5.0
npm verb run-script [ 'prestart', 'start', 'poststart' ]
npm info lifecycle electron-quick-start@1.0.0~prestart: electron-quick-start@1.0.0
npm info lifecycle electron-quick-start@1.0.0~start: electron-quick-start@1.0.0

> electron-quick-start@1.0.0 start R:\Temp\electron-quick-start
> electron .


fs.js:1584
  return binding.realpath(pathModule._makeLong(path), options.encoding);
                 ^

Error: EISDIR: illegal operation on a directory, realpath 'R:\Temp\electron-quick-start\node_modules\electron\dist\resources\electron.asar'
    at Error (native)
    at realpathSync (fs.js:1584:18)
    at Object.fs.realpathSync (ELECTRON_ASAR.js:325:24)
    at Function.Module._findPath (module.js:167:25)
    at Function.Module._resolveFilename (module.js:438:25)
    at Function.Module._load (module.js:388:25)
    at Module.runMain (module.js:575:10)
    at run (bootstrap_node.js:360:7)
    at startup (bootstrap_node.js:152:9)
    at bootstrap_node.js:479:3

npm verb lifecycle electron-quick-start@1.0.0~start: unsafe-perm in lifecycle true
npm verb lifecycle electron-quick-start@1.0.0~start: PATH: C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin;R:\Temp\electron-quick-start\node_modules\.bin;C:\Program Files\nodejs;C:\Users\myUser\AppData\Roaming\npm
npm verb lifecycle electron-quick-start@1.0.0~start: CWD: R:\Temp\electron-quick-start
npm info lifecycle electron-quick-start@1.0.0~start: Failed to exec start script
npm verb stack Error: electron-quick-start@1.0.0 start: `electron .`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:242:16)
npm verb stack     at emitTwo (events.js:106:13)
npm verb stack     at EventEmitter.emit (events.js:191:7)
npm verb stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:40:14)
npm verb stack     at emitTwo (events.js:106:13)
npm verb stack     at ChildProcess.emit (events.js:191:7)
npm verb stack     at maybeClose (internal/child_process.js:877:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
npm verb pkgid electron-quick-start@1.0.0
npm verb cwd R:\Temp\electron-quick-start
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start" "--verbose"
npm ERR! node v6.5.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE
npm ERR! electron-quick-start@1.0.0 start: `electron .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-quick-start@1.0.0 start script 'electron .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron-quick-start package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron .
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-quick-start
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron-quick-start
npm ERR! There is likely additional logging output above.
npm verb exit [ 1, true ]

npm ERR! Please include the following file with any support request:
npm ERR!     R:\Temp\electron-quick-start\npm-debug.log
```

**Comment by zcbenz** [comment]
This is a bug of Node and had been fixed by https://github.com/nodejs/node/commit/08996fde3c08c0cfabc7cc3fe332d83f674ab099 in upstream, this will be fixed once Electron is upgraded to Node >= 6.4.0.

I'm closing this since the upgrade to Node 6.5.0 has been done at #7104 and will be included in Electron 1.4.0.
