### ISSUE TITLE
Error using NodObjC

### ISSUE THREAD

**Issue by liushaohua** [electron/electron#7167]
I'm trying to use NodObjC in my Electron app, but I can't seem to figure out how to require('nodobjc') without throwing an error. The stack trace is:
```javascript
App threw an error when running Error: Module version mismatch. Expected 48, got 47.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:158:20)
    at Object.Module._extensions..node (module.js:568:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:158:20)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at bindings (/Users/liushaohua/Documents/work/Talk/TalkTool-new/node_modules/nodobjc/node_modules/ref/node_modules/bindings/bindings.js:76:44)
```

**Comment by MarshallOfSound** [comment]
You need to rebuild native modules for Electron

Check out the docs for that here: https://github.com/electron/electron/blob/master/docs/tutorial/using-native-node-modules.md
