### ISSUE TITLE
TypeError when accessing remote objects

### ISSUE THREAD

**Issue by mikecao** [electron/electron#7196]
* Electron version: 1.3.5
* Operating system: Windows 7 x64

I am running into errors randomly whenever accessing remote methods. Errors like this:

```
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get (D:\dev\electron-v1.3.5-win32-x64\resources\electron.asar\browser\objects-registry.js:44:28)
    at EventEmitter.<anonymous> (D:\dev\electron-v1.3.5-win32-x64\resources\electron.asar\browser\rpc-server.js:305:31)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (D:\dev\electron-v1.3.5-win32-x64\resources\electron.asar\browser\api\web-contents.js:218:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
    at ObjectsRegistry.get (D:\dev\electron-v1.3.5-win32-x64\resources\electron.asar\browser\objects-registry.js:44:28)
    at EventEmitter.<anonymous> (D:\dev\electron-v1.3.5-win32-x64\resources\electron.asar\browser\rpc-server.js:305:31)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (D:\dev\electron-v1.3.5-win32-x64\resources\electron.asar\browser\api\web-contents.js:218:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
    at metaToValue (D:\dev\electron-v1.3.5-win32-x64\resources\electron.asar\renderer\api\remote.js:209:13)
    at remoteMemberFunction (D:\dev\electron-v1.3.5-win32-x64\resources\electron.asar\renderer\api\remote.js:110:18)
```

Or this:

```
TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
    at setObjectMembers (D:\dev\electron-v1.3.5-win32-x64\resources\electron.asar\renderer\api\remote.js:97:22)
    at loadRemoteProperties (D:\dev\electron-v1.3.5-win32-x64\resources\electron.asar\renderer\api\remote.js:163:5)
    at Object.getOwnPropertyDescriptor (D:\dev\electron-v1.3.5-win32-x64\resources\electron.asar\renderer\api\remote.js:178:7)
    at descriptor.get [as reload] (D:\dev\electron-v1.3.5-win32-x64\resources\electron.asar\renderer\api\remote.js:117:32)
```

I believe it is similar to #4733. I started getting these errors since 1.3.4. Previous versions had been working fine.

**Comment by kevinsawicki** [comment]
What object are you accessing when you see this error?

**Comment by kevinsawicki** [comment]
Another question, are you accessing a remote function in your own app when these occur or accessing a remote Electron API?

**Comment by mikecao** [comment]
This is from my application. It happens when I try to access any of the methods on `BrowserWindow`, like `maximize`, `minimize`, `reload`, etc. I have a class where I keep a reference to the current window by doing `this.currentWindow = remote.getCurrentWindow()` in the constructor, and calling it later by doing `this.currentWindow.reload()`.

**Comment by asherkin** [comment]
I'm getting this as well (in 1.4.0, just updated from 0.37.6), it does appear to be an object lifetime issue.

```
resources\electron.asar\renderer\api\remote.js:210
Uncaught (in promise) Error: Cannot read property 'object' of undefined(…)
    metaToValue    @ resources\electron.asar\renderer\api\remote.js:210
    descriptor.get @ resources\electron.asar\renderer\api\remote.js:129
    doStuff        @ resources\app\preload.js:166
```

In my preload script I have something like the following:
```
var electron = require('electron');
var settings = electron.remote.require('./settings');

if (settings.developer) {
    // ^ That one is fine.
}

var exports = {};

try {
    exports.subAPI = {
        doStuff: function() {
            if (settings.developer) {
                // ^ That one errors.
            }
        },
    };
} catch(e) {
    console.log('Failed to load subAPI: ' + e.message);
}

global.myAPI = exports;
```

settings.js just returns an object with properties.

**Comment by juturu** [comment]
@kevinsawicki - we are hitting this issue in the latest version of electron. 
remote.js:98 
Uncaught TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
_:51

I noticed there are couple of other places where setObjectMembers method is called and is not guarded. Is it possible to move the guard into setObjectMembers method?

**Comment by kevinsawicki** [comment]
> I noticed there are couple of other places where setObjectMembers method is called and is not guarded. Is it possible to move the guard into setObjectMembers method?

It is, can you open a new issue with some reproduction steps and we can discuss it more there?
