### ISSUE TITLE
App not ready error not thrown when requiring powerMonitor too early

### ISSUE THREAD

**Issue by salomvary** [electron/electron#7225]
* Electron version: v1.4.0
* Operating system: macOS 10.11.6

Given the following `main.js`:
```js
const {powerMonitor} = require('electron')
```

I get the following exception:

```
$ electron .
App threw an error during load
TypeError: Cannot match against 'undefined' or 'null'.
    at Object.<anonymous> (/usr/local/lib/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/api/power-monitor.js:2:46)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.get [as powerMonitor] (/usr/local/lib/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/api/exports/electron.js:65:14)
    at Object.<anonymous> (electron-test/main.js:1:87)
```

**Comment by kevinsawicki** [comment]
> const {powerMonitor} = require('electron')

Is this line being called before the app ready event fires? That could be your issue, although there is supposed to be a better error message displayed when this happens that seems to have regressed.

http://electron.atom.io/docs/api/power-monitor/

**Comment by salomvary** [comment]
Oh, the fact that even *requiring* the module will fail before app ready was totally unclear from the docs.

Instead of "You should not use this module" a better wording could be " You should not require  this module" in the docs.

**Comment by kevinsawicki** [comment]
Yeah, I'm going to reopen this since the custom error message should be thrown in this case instead of the cryptic `TypeError: Cannot match against 'undefined' or 'null'.` one.
