### ISSUE TITLE
Unable to build the debug target on x64 Windows 10

### ISSUE THREAD

**Issue by ZzZombo** [electron/electron#7247]
* Electron version: 1.4.0.
* Operating system: Windows 10 x64.

I managed to build the release target of Electron following the Windows build instructions, but the debug target constantly fails due to errors.

```
I:\Electron>python script\build.py -c D
ninja: Entering directory `out\D'
[1/1] LINK_EMBED electron.exe
FAILED: I:\<redacted>\Programs\Python_2.7\python.exe gyp-win-tool link-with-manifests environment.x64 True electron.exe "I:\<redacted>\Programs\Python_2.7\python.exe gyp-win-tool link-wrapper environment.x64 False link.exe /nologo /OUT:electron.exe @electron.exe.rsp" 1 mt.exe rc.exe "obj\electron.electron.exe.intermediate.manifest" obj\electron.electron.exe.generated.manifest ..\..\atom\browser\resources\win\atom.manifest
   Создается библиотека electron.lib и объект electron.exp
os_crypt.lib(os_crypt.os_crypt_win.obj) : error LNK2019: ссылка на неразрешенный внешний символ CryptProtectData в функции "public: static bool __cdecl OSCrypt::EncryptString(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > *)" (?EncryptString@OSCrypt@@SA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAV23@@Z)
os_crypt.lib(os_crypt.os_crypt_win.obj) : error LNK2019: ссылка на неразрешенный внешний символ CryptUnprotectData в функции "public: static bool __cdecl OSCrypt::DecryptString16(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &,class std::basic_string<wchar_t,struct std::char_traits<wchar_t>,class std::allocator<wchar_t> > *)" (?DecryptString16@OSCrypt@@SA_NAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@PEAV?$basic_string@_WU?$char_traits@_W@std@@V?$allocator@_W@2@@3@@Z)
electron.exe : fatal error LNK1120: неразрешенных внешних элементов: 2
Traceback (most recent call last):
  File "gyp-win-tool", line 323, in <module>
    sys.exit(main(sys.argv[1:]))
  File "gyp-win-tool", line 29, in main
    exit_code = executor.Dispatch(args)
  File "gyp-win-tool", line 71, in Dispatch
    return getattr(self, method)(*args[1:])
  File "gyp-win-tool", line 179, in ExecLinkWithManifests
    subprocess.check_call(ldcmd + add_to_ld)
  File "I:\<redacted>\Programs\Python_2.7\lib\subprocess.py", line 504, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'I:\<redacted>\Programs\Python_2.7\python.exe gyp-win-tool link-wrapper environment.x64 False link.exe /nologo /OUT:electron.exe @electron.exe.rsp electron.exe.manifest.res' returned non-zero exit status 1120
ninja: build stopped: subcommand failed.
```

**Comment by enlight** [comment]
This was fixed by https://github.com/electron/electron/pull/7230 so update your checkout and try again.
