### ISSUE TITLE
Issue installing asar on Windows

### ISSUE THREAD

**Issue by malcolmalex** [electron/electron#725]
Just installed node, and have my app working, but having a problem when trying to convert to asar. This seems to be hinting at chromium-pickle install issue.  Using atom-shell 0.18.1

Got this working like a champ on my mac - no problems. Any ideas appreciated.

```
C:\Users\maalex\Documents\GitHub\onsight-timer>npm install -g asar
|
> native-mate@0.2.5 install C:\Users\maalex\AppData\Roaming\npm\node_modules\asa
r\node_modules\chromium-pickle\node_modules\native-mate
> echo

ECHO is on.

> chromium-pickle@0.1.3 install C:\Users\maalex\AppData\Roaming\npm\node_modules
\asar\node_modules\chromium-pickle
> node-gyp rebuild


C:\Users\maalex\AppData\Roaming\npm\node_modules\asar\node_modules\chromium-pick
le>node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_m
odules\node-gyp\bin\node-gyp.js" rebuild
gyp WARN install got an error, rolling back install
gyp ERR! configure error
gyp ERR! stack Error: connect ETIMEDOUT
gyp ERR! stack     at errnoException (net.js:904:11)
gyp ERR! stack     at Object.afterConnect [as oncomplete] (net.js:895:19)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "node" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modu
les\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\maalex\AppData\Roaming\npm\node_modules\asar\node_modules\
chromium-pickle
gyp ERR! node -v v0.10.32
gyp ERR! node-gyp -v v1.0.1
gyp ERR! not ok

npm ERR! chromium-pickle@0.1.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the chromium-pickle@0.1.3 install script.
npm ERR! This is most likely a problem with the chromium-pickle package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls chromium-pickle
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nod
ejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "-g" "asar"
npm ERR! cwd C:\Users\maalex\Documents\GitHub\onsight-timer
npm ERR! node -v v0.10.32
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE
npm ERR! not ok code 0

C:\Users\maalex\Documents\GitHub\onsight-timer>
```

**Comment by timjroberts** [comment]
I had to install Python: https://www.python.org/downloads/windows/
Install version 2.7.9

**Comment by katopz** [comment]
Pretty close to me but I didn't have timeout problem https://github.com/bwin/grunt-asar/issues/7

@zcbenz Any hint is welcome. I'm taring my hair at the moment. :sob:
