### ISSUE TITLE
Can't install Electron

### ISSUE THREAD

**Issue by MustSeeMelons** [electron/electron#7453]
* Electron version: 1.4.2
* Operating system: Windows 10

When I try to run either
* npm install electron
* pnm install electron-prebuilt
or add electron as a dependency to package.json and then do
* npm install
I get the following error:

`> electron-prebuilt@1.4.2 postinstall C:\Users\Strautins\Desktop\code\node_modules\electron-prebuilt
> node install.js

C:\Users\Strautins\Desktop\code\node_modules\electron-prebuilt\node_modules\electron-download\node_modules\nugget\node_modules\single-line-log\node_modules\string-width\index.js:2
const stripAnsi = require('strip-ansi');
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (C:\Users\Strautins\Desktop\code\node_modules\electron-prebuilt\node_modules\electron-download\node_modules\nugget\node_modules\single-line-log\index.js:4:19)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
unbuild electron-prebuilt@1.4.2
npm ERR! weird error 8
npm ERR! not ok code 0`

If further information is required, I'd gladly give it.

**Comment by levrik** [comment]
Which version of Node you have?

**Comment by MustSeeMelons** [comment]
Node: v0.10.13
NPM: 1.3.2

**Comment by levrik** [comment]
You should upgrade your Node installation. I would suggest the latest version 6.7.0

**Comment by MustSeeMelons** [comment]
Issue fixed, so sorry I didn't think of updating node in the first place, though I had the latest version already.
