### ISSUE TITLE
Unable to use `window.open` in Electron@1.4.3

### ISSUE THREAD

**Issue by twolfson** [electron/electron#7519]
* Electron version: 1.4.3
* Operating system: Linux Mint 17.1

We recently received an error report of `karma-electron` no longer working with Electron@1.4.3 (https://github.com/twolfson/karma-electron/issues/16). After some debugging, we determined this is being caused by breaking functionality `window.open`. We have set up a minimal gist to reproduce the issue:

https://gist.github.com/twolfson/990cef4aa6dfca94282cf012a590a1e5

The stack trace we are getting is:

```
/home/todd/github/gist-electron-cannot-set-openerid/index.js:4
  throw err;
  ^

TypeError: Cannot set property 'openerId' of undefined
    at mergeBrowserWindowOptions (/home/todd/github/gist-electron-cannot-set-openerid/node_modules/electron/dist/resources/electron.asar/browser/guest-window-manager.js:44:35)
    at EventEmitter.<anonymous> (/home/todd/github/gist-electron-cannot-set-openerid/node_modules/electron/dist/resources/electron.asar/browser/guest-window-manager.js:144:13)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (/home/todd/github/gist-electron-cannot-set-openerid/node_modules/electron/dist/resources/electron.asar/browser/api/web-contents.js:219:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
```

which is likely caused by the changes to `browser/guest-window-manager.js`.

**Comment by MarshallOfSound** [comment]
Hm, this appears to be due to `webPreferences` not always being set on new Windows.

```js
options.webPreferences.openerId = embedder.id
```

Fix incoming

**Comment by MarshallOfSound** [comment]
Issue was caused by: a2b3cf95a747c331cabb0dd1f1e3ad93be6b3120
