### ISSUE TITLE
Error: Module version mismatch. Expected 50, got 47.

### ISSUE THREAD

**Issue by CarstenHoyer** [electron/electron#7557]
**Issue:**
Rebuilding keytar gives me a version mismatch.

App threw an error during load
Error: Module version mismatch. Expected 50, got 47.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:168:20)
    at Object.Module._extensions..node (module.js:583:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:168:20)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users//Workspace/electron-sample-apps/helloworld/node_modules/keytar/lib/keytar.js:4:12)

**Steps to reproduce:**
git clone https://github.com/hokein/electron-sample-apps.git samples && cd samples/helloworld
add "const keytar = require('keytar');" to main.js
npm install --save keytar && npm install --save-dev electron-rebuild
./node_modules/.bin/electron-rebuild
electron .

* Electron version: 1.4.3
* Operating system: OSX El Capitan 10.11.6
* npm: 3.10.7
* node: v6.7.0
* xcode is beta if this is in anyway relevant.

**Comment by CarstenHoyer** [comment]
Problem solved by specifying the target version.

./node_modules/.bin/electron-rebuild --version=1.4.3

Where version is the electron version.
