### ISSUE TITLE
Extension is haunting me.

### ISSUE THREAD

**Issue by bliitzkrieg** [electron/electron#7619]
* Electron version: v1.4.3
* Operating system: Win 10

Hey

I followed this guide https://www.xplatform.rocks/2016/07/02/using-augury-inside-of-your-electron-apps/ and tried to get Augury (https://augury.angular.io/) working with electron but unfortunately due to an API that Augury uses, it wasn't compatible with Electron (https://github.com/electron/electron/issues/6307). I removed the code from my main.js and removed the Augury extension from my chrome. For some reason when I run `electron .` to boot up my application, it throws an error trying to fetch the extension.

```
Reading C:\Users\bliitz\AppData\Local\Google\Chrome\User Data\Default\Extensions\elgalmkoelokbchhkhacckoklkejnhcd\1.2.1_0\manifest.json failed.
Error: ENOENT: no such file or directory, open 'C:\Users\bliitz\AppData\Local\Google\Chrome\User Data\Default\Extensions\elgalmkoelokbchhkhacckoklkejnhcd\1.2.1_0\manifest.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:168:20)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:501:29)
    at getManifestFromPath (C:\Users\bliitz\AppData\Roaming\npm\node_modules\electron\dist\resources\electron.asar\browser\chrome-extension.js:34:26)
    at App.<anonymous> (C:\Users\bliitz\AppData\Roaming\npm\node_modules\electron\dist\resources\electron.asar\browser\chrome-extension.js:354:26)
    at App.g (events.js:286:16)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:191:7)
```

The code is 100% gone and even the extension is gone but for some reason its still trying to retrieve it. I was thinking it may be some caching issue but have zero idea how to solve it.

Anybody have any idea?

**Comment by enlight** [comment]
Open the `%APPDATA%\Electron` folder and delete the `DevTools Extensions` file and `extensions` directory (or just remove your extension).

**Comment by bliitzkrieg** [comment]
Thank you sir!

**Comment by johny-bravo** [comment]
for me `%APPDATA%\Electron` did not solve it, `%APPDATA%\project-folder-name` did though

**Comment by jasonmerry** [comment]
This worked for me too :)

Anyone know how/where to let electron remove these when it closes rather than manually removing them?
