### ISSUE TITLE
electron use serialport :Module version mismatch. Expected 48, got 46.

### ISSUE THREAD

**Issue by kscorpio** [electron/electron#7649]
* Electron version: 1.1.2
* Operating system:  Ubuntu 16.04 x86_64-pc-linux
Node version : 4.2.0  4.6.0
serialport version 4.0.3

Uncaught Exception:
Error: Module version mismatch. Expected 48, got 46.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:158:20)
    at Object.Module._extensions..node (module.js:568:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:158:20)
    at Module.load (module.js:456:32)
    at tryModuleLoad (module.js:415:12)
    at Function.Module._load (module.js:407:3)
    at Module.require (module.js:466:17)
    at require (internal/module.js:20:19)
    at bindings (/home/kscorpio/ElevatorPlayer/electron/resources/app/node_modules/serialport/node_modules/bindings/bindings.js:76:44)

**Comment by MarshallOfSound** [comment]
Please read the docs on using native node modules.

https://github.com/electron/electron/blob/master/docs/tutorial/using-native-node-modules.md
