### ISSUE TITLE
Build fails with clang error (archive is not an object)

### ISSUE THREAD

**Issue by baxterbln** [electron/electron#7835]
* Electron version:  1.4.4
* Operating system: Ubuntu 16.04

```
ninja: Entering directory `out/R'
[1/237] SOLINK lib/libnode.so
[2/237] STAMP obj/atom_js2c.actions_depends.stamp
[3/237] ACTION atom_js2c: atom_js2c_805c0478a9ccb5f13d1e094b49407e5c
FAILED: if [ ! -e lib/libnode.so -o ! -e lib/libnode.so.TOC ]; then ../../vendor/llvm-build/Release+Asserts/bin/clang++ -shared -pthread -Wl,--whole-archive /home/neil/Downloads/electron/vendor/brightray/vendor/download/libchromiumcontent/static_library/libicuuc.a /home/neil/Downloads/electron/vendor/brightray/vendor/download/libchromiumcontent/static_library/libv8_libbase.a /home/neil/Downloads/electron/vendor/brightray/vendor/download/libchromiumcontent/static_library/libv8_libsampler.a /home/neil/Downloads/electron/vendor/brightray/vendor/download/libchromiumcontent/static_library/libv8_external_snapshot.a /home/neil/Downloads/electron/vendor/brightray/vendor/download/libchromiumcontent/static_library/libicui18n.a /home/neil/Downloads/electron/vendor/brightray/vendor/download/libchromiumcontent/static_library/libv8_base.a /home/neil/Downloads/electron/vendor/brightray/vendor/download/libchromiumcontent/static_library/libv8_libplatform.a -Wl,--no-whole-archive --sysroot=/home/neil/Downloads/electron/vendor/debian_wheezy_arm-sysroot -L/home/neil/Downloads/electron/vendor/debian_wheezy_arm-sysroot/lib/arm-linux-gnueabihf -Wl,-rpath-link=/home/neil/Downloads/electron/vendor/debian_wheezy_arm-sysroot/lib/arm-linux-gnueabihf -L/home/neil/Downloads/electron/vendor/debian_wheezy_arm-sysroot/usr/lib/arm-linux-gnueabihf -Wl,-rpath-link=/home/neil/Downloads/electron/vendor/debian_wheezy_arm-sysroot/usr/lib/arm-linux-gnueabihf -target arm-linux-gnueabihf -Wl,-O1 -Wl,--as-needed -Wl,--gc-sections -o lib/libnode.so -Wl,-soname=libnode.so @lib/libnode.so.rsp && { readelf -d lib/libnode.so | grep SONAME ; nm -gD -f p lib/libnode.so | cut -f1-2 -d' '; } > lib/libnode.so.TOC; else ../../vendor/llvm-build/Release+Asserts/bin/clang++ -shared -pthread -Wl,--whole-archive /home/neil/Downloads/electron/vendor/brightray/vendor/download/libchromiumcontent/static_library/libicuuc.a /home/neil/Downloads/electron/vendor/brightray/vendor/download/libchromiumcontent/static_library/libv8_libbase.a /home/neil/Downloads/electron/vendor/brightray/vendor/download/libchromiumcontent/static_library/libv8_libsampler.a /home/neil/Downloads/electron/vendor/brightray/vendor/download/libchromiumcontent/static_library/libv8_external_snapshot.a /home/neil/Downloads/electron/vendor/brightray/vendor/download/libchromiumcontent/static_library/libicui18n.a /home/neil/Downloads/electron/vendor/brightray/vendor/download/libchromiumcontent/static_library/libv8_base.a /home/neil/Downloads/electron/vendor/brightray/vendor/download/libchromiumcontent/static_library/libv8_libplatform.a -Wl,--no-whole-archive --sysroot=/home/neil/Downloads/electron/vendor/debian_wheezy_arm-sysroot -L/home/neil/Downloads/electron/vendor/debian_wheezy_arm-sysroot/lib/arm-linux-gnueabihf -Wl,-rpath-link=/home/neil/Downloads/electron/vendor/debian_wheezy_arm-sysroot/lib/arm-linux-gnueabihf -L/home/neil/Downloads/electron/vendor/debian_wheezy_arm-sysroot/usr/lib/arm-linux-gnueabihf -Wl,-rpath-link=/home/neil/Downloads/electron/vendor/debian_wheezy_arm-sysroot/usr/lib/arm-linux-gnueabihf -target arm-linux-gnueabihf -Wl,-O1 -Wl,--as-needed -Wl,--gc-sections -o lib/libnode.so -Wl,-soname=libnode.so @lib/libnode.so.rsp && { readelf -d lib/libnode.so | grep SONAME ; nm -gD -f p lib/libnode.so | cut -f1-2 -d' '; } > lib/libnode.so.tmp && if ! cmp -s lib/libnode.so.tmp lib/libnode.so.TOC; then mv lib/libnode.so.tmp lib/libnode.so.TOC ; fi; fi
/home/neil/Downloads/electron/vendor/brightray/vendor/download/libchromiumcontent/static_library/libicuuc.a: member /home/neil/Downloads/electron/vendor/brightray/vendor/download/libchromiumcontent/static_library/libicuuc.a(icuuc.appendable.o) in archive is not an object
clang: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.

Traceback (most recent call last):
  File "./script/create-dist.py", line 239, in <module>
    sys.exit(main())
  File "./script/create-dist.py", line 82, in main
    force_build()
  File "./script/create-dist.py", line 105, in force_build
    execute([sys.executable, build, '-c', 'Release'])
  File "/home/neil/Downloads/electron/script/lib/util.py", line 170, in execute
    raise e
subprocess.CalledProcessError: Command '['/usr/bin/python', '/home/neil/Downloads/electron/script/build.py', '-c', 'Release']' returned non-zero exit status 1
```

**Comment by zeke** [comment]
It looks like you're running the "Release" build script. Are you able to create a "Debug" build?

```
npm run build
```

**Comment by zcbenz** [comment]
The error means the linker installed on your system does not accept the prebuilt binaries of libchromiumcontent. It is possible that you didn't install the necessary dependencies required here:
http://electron.atom.io/docs/development/build-instructions-linux/#cross-compilation

Or it is possible your toolchain is not compatible with the prebuilt binaries of libchromiumcontent, in that case you have to build libchromiumcontent yourself.
