### ISSUE TITLE
Npm install error (only v1.4.5)

### ISSUE THREAD

**Issue by clusterberries** [electron/electron#7848]
* Electron version: 1.4.5
* Operating system: win10

Hi!
Recently I updated electron from 1.4.4 to 1.4.5 and reinstalled node_modules
I got an error during npm install (as I can see it fails on spellchecker modules install):

```
gyp ERR! configure error
gyp ERR! stack Error: iojs-v1.4.5.tar.gz local checksum d47724cf608ccdcc59aeabd5d508e169f92caef9ccf56b360bc97449b2bbc4aa not match remote 5be8e4ffbd9eb3a07b003530af5e1757c0a53e8ef9280b40634e3d6f4198995e
gyp ERR! stack     at deref (C:\Program Files (x86)\Nodist\bin\node_modules\npm\node_modules\node-gyp\lib\install.js:266:20)
gyp ERR! stack     at Request.<anonymous> (C:\Program Files (x86)\Nodist\bin\node_modules\npm\node_modules\node-gyp\lib\install.js:354:24)
gyp ERR! stack     at emitOne (events.js:82:20)
gyp ERR! stack     at Request.emit (events.js:169:7)
gyp ERR! stack     at IncomingMessage.<anonymous> (C:\Program Files (x86)\Nodist\bin\node_modules\npm\node_modules\request\request.js:969:12)
gyp ERR! stack     at emitNone (events.js:72:20)
gyp ERR! stack     at IncomingMessage.emit (events.js:166:7)
gyp ERR! stack     at endReadableNT (_stream_readable.js:921:12)
gyp ERR! stack     at nextTickCallbackWith2Args (node.js:442:9)
gyp ERR! stack     at process._tickCallback (node.js:356:17)
gyp ERR! System Windows_NT 10.0.14393
gyp ERR! command "C:\\Program Files (x86)\\Nodist\\v-x64\\4.6.1\\node.exe" "C:\\Program Files (x86)\\Nodist\\bin\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd D:\UNIF-CIRC\project\ansibleclient\src\electron\app\node_modules\keytar
gyp ERR! node -v v4.6.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files (x86)\\Nodist\\v-x64\\4.6.1\\node.exe" "C:\\Program Files (x86)\\Nodist\\bin\\node_modules\\npm\\bin\\npm-cli.js" "install" "--production" "--cache-min" "999999999" "--build-from-source"
npm ERR! node v4.6.1
npm ERR! npm  v4.0.1
npm ERR! code ELIFECYCLE

npm ERR! keytar@3.0.2 install: node-gyp rebuild
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the keytar@3.0.2 install script node-gyp rebuild.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the keytar package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs keytar
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls keytar
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     D:\UNIF-CIRC\project\ansibleclient\src\electron\app\npm-debug.log

    at ChildProcess.<anonymous> (D:\UNIF-CIRC\project\ansibleclient\src\electron\node_modules\electron-builder\src\util\util.ts:160:14)
    at ChildProcess.g (events.js:260:16)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:829:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
`From previous event:
    at spawn (D:\UNIF-CIRC\project\ansibleclient\src\electron\node_modules\electron-builder\src\util\util.ts:123:3)
    at spawnNpmProduction (D:\UNIF-CIRC\project\ansibleclient\src\electron\node_modules\electron-builder\src\util\util.ts:49:3)
    at Object.installDependencies (D:\UNIF-CIRC\project\ansibleclient\src\electron\node_modules\electron-builder\src\util\util.ts:20:122)
    at D:\UNIF-CIRC\project\ansibleclient\src\electron\node_modules\electron-builder\src\install-app-deps.ts:34:2
    at next (native)
From previous event:
    at tsAwaiter (D:\UNIF-CIRC\project\ansibleclient\src\electron\node_modules\electron-builder\src\util\awaiter.ts:10:47)
    at main (D:\UNIF-CIRC\project\ansibleclient\src\electron\node_modules\electron-builder\src\install-app-deps.ts:23:3)
    at Object.<anonymous> (D:\UNIF-CIRC\project\ansibleclient\src\electron\node_modules\electron-builder\out\install-app-deps.js:28:1)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:974:3
```

I thought that something wrong with node-gyp, keytar or with new version of node.js. I tried a lot of things, but found out that simple change from 1.4.5 to 1.4.4 solved my problem.
So, guys, maybe you have some ideas what went wrong, because it prevents update of electron module.

Thanks!

**Comment by lgeiger** [comment]
@clusterberries This sounds like the same issue as #7845. Hopefully it'll be fixed soon.

**Comment by thomasjo** [comment]
This is indeed a duplicate of #7845.

**Comment by clusterberries** [comment]
Thanks, I'll close this one then.

**Comment by kevinsawicki** [comment]
This should be fixed now, please comment if you still see issues.

**Comment by clusterberries** [comment]
@kevinsawicki, it works now, thanks!

**Comment by hovancik** [comment]
having same issue with `electron-v1.4.5-win32-x64.zip`
