### ISSUE TITLE
TypeError when accessing remote objects

### ISSUE THREAD

**Issue by juturu** [electron/electron#7918]
* Electron version: 1.4.5
* Operating system: Mac & Windows

I am running into errors randomly whenever accessing remote methods. 

Following is similar to #7196 
```
remote.js:98 
Uncaught TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
_:51
```

And one other 

```
electron.asar\renderer\api\remote.js:217 Uncaught Error: Cannot read property 'object' of undefined
TypeError: Cannot read property 'object' of undefined
    at ObjectsRegistry.get (electron.asar\browser\objects-registry.js:44:28)
    at EventEmitter.<anonymous> (electron.asar\browser\rpc-server.js:325:31)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
    at WebContents.<anonymous> (electron.asar\browser\api\web-contents.js:219:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
```

@kevinsawicki any ideas on fixing this?

**Comment by kevinsawicki** [comment]
> remote.js:98 
Uncaught TypeError: Cannot read property 'Symbol(Symbol.iterator)' of undefined
_:51

Are you able to provide a fuller stack trace for this one?

**Comment by juturu** [comment]
Unfortunately, didn't get the full stack trace for this.
