### ISSUE TITLE
Windows 64bit Autoupdater keep app updating again and agin 

### ISSUE THREAD

**Issue by weiway** [electron/electron#8040]
Electron version : 1.3.2
Platform : Windows10 64bit

let’s say my app is in version 2.0.2, and when app launches, autoupdater will ask
```
http://update-server-url/update/win64/2.0.2/RELEASES
```
and the server will response something like 
```
2C38B0E4052AF3E7CA159F1BE5AE7B0F7D5F621B http://update-server-url/download/2.0.2/windows_64/appname-2.0.2-full-x64.nupkg 69562367
```
Then autoupdater thinks that it’s a new version, and start to download and install.

Then app relaunches and, in the same version, start the above process again. 

My main.js looks like this
```
            //AUTO UPDATER LOGIC ----------
            autoUpdater.checkForUpdates();
            autoUpdater.on('error',err=>{
                console.log('ERRROR: ', err);
            });
            autoUpdater.on('update-not-available',err=>{
                console.log('NO UPDATE AVAILABLE: ', err);
            });
            autoUpdater.on('update-downloaded',()=>{
                console.log('UPDATE');
                updateWin = new BrowserWindow({
                    'title': "Updates Available",
                    'width': 600,
                    'height': 460,
                    'frame' : false,
                    'resizable' : false,
                    'alwaysOneTop':true,
                    'webPreferences' : {
                        nodeIntegration: false,
                        // might solve ia32 issue
                        allowDisplayingInsecureContent: true
                    }
                });

                updateWin.loadURL(updatePageURL);

                updateWin.on('close',()=>{
                    autoUpdater.quitAndInstall();
                })
            });
```

It seems that autoupdater failed to decide the latest version from local RLEASE file ? 

Here's the SquirrelSetup.log 
```
2016-11-21 14:38:46> Program: Starting Squirrel Updater: --processStart myapp.exe
2016-11-21 14:38:46> Program: Want to launch 'C:\Users\myuser\AppData\Local\myapp\app-2.0.2\myapp.exe'
2016-11-21 14:38:46> Program: About to launch: 'C:\Users\myuser\AppData\Local\myapp\app-2.0.2\myapp.exe':
2016-11-21 14:38:47> Program: Starting Squirrel Updater: --download http://updater-server-url/update/win64/2.0.2/RELEASES
2016-11-21 14:38:47> Program: Fetching update information, downloading from http://updater-server-url/update/win64/2.0.2/RELEASES
2016-11-21 14:38:47> CheckForUpdateImpl: Using existing staging user ID: 1eb06988-9b50-5c52-85f8-c676ae968ac2
2016-11-21 14:38:47> CheckForUpdateImpl: Downloading RELEASES file from http://updater-server-url/update/win64/2.0.2/RELEASES
2016-11-21 14:38:47> FileDownloader: Downloading url: http://updater-server-url/update/win64/2.0.2/RELEASES/RELEASES?id=myapp&localVersion=2.0.2&arch=amd64
2016-11-21 14:38:48> CheckForUpdateImpl: hwhat, local version is greater than remote version
2016-11-21 14:38:48> FileDownloader: Downloading file: http://updater-server-url/download/2.0.2/windows_64/myapp-2.0.2-full-x64.nupkg
2016-11-21 14:38:53> UpdateInfo: Couldn't get release notes for:myapp-2.0.2-full-x64.nupkg: System.Exception: Invalid 'ReleaseNotes' value in nuspec file at 'C:\Users\myuser\AppData\Local\myapp\packages\myapp-2.0.2-full-x64.nupkg'
   at Squirrel.ReleaseEntry.GetReleaseNotes(String packageDirectory)
   at Squirrel.UpdateInfo.<FetchReleaseNotes>b__19_0(ReleaseEntry x)
2016-11-21 14:38:53> Program: Starting Squirrel Updater: --update http://updater-server-url/update/win64/2.0.2/RELEASES
2016-11-21 14:38:53> Program: Starting update, downloading from http://updater-server-url/update/win64/2.0.2/RELEASES
2016-11-21 14:38:53> Program: About to update to: C:\Users\myuser\AppData\Local\myapp
2016-11-21 14:38:53> CheckForUpdateImpl: Using existing staging user ID: 1eb06988-9b50-5c52-85f8-c676ae968ac2
2016-11-21 14:38:53> CheckForUpdateImpl: Downloading RELEASES file from http://updater-server-url/update/win64/2.0.2/RELEASES
2016-11-21 14:38:53> FileDownloader: Downloading url: http://updater-server-url/update/win64/2.0.2/RELEASES/RELEASES?id=myapp&localVersion=2.0.2&arch=amd64
2016-11-21 14:38:53> CheckForUpdateImpl: hwhat, local version is greater than remote version
2016-11-21 14:38:53> FileDownloader: Downloading file: http://updater-server-url/download/2.0.2/windows_64/myapp-2.0.2-full-x64.nupkg
2016-11-21 14:38:58> ApplyReleasesImpl: Writing files to app directory: C:\Users\myuser\AppData\Local\myapp\app-2.0.2-full-x64
2016-11-21 14:38:59> ApplyReleasesImpl: Squirrel Enabled Apps: [C:\Users\myuser\AppData\Local\myapp\app-2.0.2\myapp.exe]
2016-11-21 14:38:59> ApplyReleasesImpl: Starting fixPinnedExecutables
2016-11-21 14:38:59> ApplyReleasesImpl: Examining Pin: 02 - Command Prompt.lnk
2016-11-21 14:38:59> ApplyReleasesImpl: Examining Pin: File Explorer.lnk
2016-11-21 14:38:59> ApplyReleasesImpl: Examining Pin: Google Chrome.lnk
2016-11-21 14:38:59> ApplyReleasesImpl: Examining Pin: Slack.lnk
2016-11-21 14:38:59> ApplyReleasesImpl: Fixing up tray icons
2016-11-21 14:38:59> ApplyReleasesImpl: cleanDeadVersions: for version 2.0.2
2016-11-21 14:38:59> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-2.0.2
2016-11-21 14:38:59> ApplyReleasesImpl: cleanDeadVersions: exclude folder app-2.0.2
2016-11-21 14:39:00> InstallHelperImpl: Couldn't write uninstall icon, don't care: System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at Squirrel.UpdateManager.InstallHelperImpl.<CreateUninstallerRegistryEntry>d__5.MoveNext()
2016-11-21 14:39:14> Program: Starting Squirrel Updater: --processStartAndWait myapp.exe
2016-11-21 14:39:14> Program: Want to launch 'C:\Users\myuser\AppData\Local\myapp\app-2.0.2\myapp.exe'
2016-11-21 14:39:14> Program: About to wait for parent PID 3640
2016-11-21 14:39:14> Program: About to launch: 'C:\Users\myuser\AppData\Local\myapp\app-2.0.2\myapp.exe':
```

**Comment by weiway** [comment]
It seems this issue is related to electron-builder and squirrel.windows. I'll close this issue here.
