### ISSUE TITLE
The cached remote.getGlobal() object failed after several times of window.reload()

### ISSUE THREAD

**Issue by jwu** [electron/electron#8128]
* Electron version:  1.14.+
* Operating system: Mac OSX

### Expected behavior

The cached remote object should return the properties in it.

### Actual behavior

When get the property in cached remote object will raised an error: 

```
Uncaught Error: Cannot get property 'bar' on missing remote object 1
Error: Cannot get property 'bar' on missing remote object 1
    at throwRPCError (/Users/johnny/jwu/electron-pitfalls/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/rpc-server.js:143:17)
    at EventEmitter.<anonymous> (/Users/johnny/jwu/electron-pitfalls/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/rpc-server.js:368:7)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
    at WebContents.<anonymous> (/Users/johnny/jwu/electron-pitfalls/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/api/web-contents.js:231:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
    at throwRPCError (/Users/johnny/jwu/electron-pitfalls/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/rpc-server.js:143:17)
    at EventEmitter.<anonymous> (/Users/johnny/jwu/electron-pitfalls/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/rpc-server.js:368:7)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
    at WebContents.<anonymous> (/Users/johnny/jwu/electron-pitfalls/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/api/web-contents.js:231:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
    at metaToValue (/Users/johnny/jwu/electron-pitfalls/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/renderer/api/remote.js:217:13)
    at Object.descriptor.get [as bar] (/Users/johnny/jwu/electron-pitfalls/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/renderer/api/remote.js:131:16)
    at <anonymous>:1:10
```

### How to reproduce

1. cache a remote global object via `remote.getGlobal()`
1. prevent reload window by cache the beforeunload event
1. try to get property from the remote object
1. you will see the error in your devtools. (if that doesn't happen, try reload again and again)

I create a very simple test project to reproduce this problem: https://github.com/jwu/electron-pitfalls, just clone it and run:

```
npm start reload-with-remote-cached
```

**Comment by MarshallOfSound** [comment]
See #7351

Their is an ongoing effort to fix this issue
