### ISSUE TITLE
Update to version 1.4.11 fails on ARM

### ISSUE THREAD

**Issue by eamiro** [electron/electron#8169]
Hello

Can't update electron from version 1.4.1 to version 1.4.11 on my raspberry pi 2

* Electron version: 1.4.11
* Operating system: Raspbian Jessie

> electron@1.4.11 postinstall /home/pi/lims/node_modules/electron
> node install.js

Here is the error message:

/home/pi/lims/node_modules/electron/install.js:22
  throw err
  ^

Error: read ECONNRESET
    at exports._errnoException (util.js:1036:11)
    at TLSWrap.onread (net.js:564:26)
- tweetnacl@0.14.3 node_modules/bcrypt-pbkdf/node_modules/tweetnacl
- isarray@1.0.0 node_modules/bl/node_modules/isarray
- readable-stream@2.0.6 node_modules/bl/node_modules/readable-stream
- bl@1.1.2 node_modules/bl
npm WARN optional Skipping failed optional dependency /pm2/chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fsevents@1.0.15
npm WARN lims@0.1.0 No repository field.
npm ERR! Linux 4.4.21-v7+
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "update" "--save-dev" "electron"
npm ERR! node v6.6.0
npm ERR! npm  v3.10.3
npm ERR! code ELIFECYCLE

npm ERR! electron@1.4.11 postinstall: `node install.js`
npm ERR! Exit status 1

**Comment by eamiro** [comment]
Finally update successful
