### ISSUE TITLE
npm i -g electron errors , unexpected JSON token at position 80

### ISSUE THREAD

**Issue by dessalines** [electron/electron#8188]
I'm trying to run `npm i -g electron`, and getting the following stacktrace errors:

```sh

> electron@1.4.12 postinstall /home/xxx/.nvm/versions/node/v7.2.1/lib/node_modules/electron
> node install.js

undefined:6
}{
 ^

SyntaxError: Unexpected token { in JSON at position 80
    at JSON.parse (<anonymous>)
    at exports.parse (/home/xxx/.nvm/versions/node/v7.2.1/lib/node_modules/electron/node_modules/rc/lib/utils.js:15:17)
    at addConfigFile (/home/xxx/.nvm/versions/node/v7.2.1/lib/node_modules/electron/node_modules/rc/index.js:31:20)
    at Array.forEach (native)
    at module.exports (/home/xxx/.nvm/versions/node/v7.2.1/lib/node_modules/electron/node_modules/rc/index.js:44:36)
    at Object.<anonymous> (/home/xxx/.nvm/versions/node/v7.2.1/lib/node_modules/electron/node_modules/electron-download/build/index.js:12:26)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
npm ERR! Linux 4.4.0-51-generic
npm ERR! argv "/home/xxx/.nvm/versions/node/v7.2.1/bin/node" "/home/xxx/.nvm/versions/node/v7.2.1/bin/npm" "install" "electron" "-g"
npm ERR! node v7.2.1
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
```

**Comment by kevinsawicki** [comment]
`electron-download` loads the npm configuration using the `rc` module.

Do you have any invalid JSON files at the following locations? https://github.com/dominictarr/rc#standards (replace `appname` with `npm`)

**Comment by dessalines** [comment]
There's no such folder `~/.config/npm` . I've installed npm with `nvm` also.

**Comment by kevinsawicki** [comment]
> There's no such folder ~/.config/npm . I've installed npm with nvm also.

Did you check all the locations at https://github.com/dominictarr/rc#standards ? It tries several places.

Could you grep for `}{` as well which might show the file as well?

**Comment by dessalines** [comment]
Yes, I did, there are no files in any of those locations. 

I wouldn't really know where to grep, since this fails: `npm i -g electron`, and no files appear to be written out when it fails. 


Now its giving a slightly different error:

```sh
$ npm i -g electron
/home/xxx/.nvm/versions/node/v6.5.0/bin/electron -> /home/xxx/.nvm/versions/node/v6.5.0/lib/node_modules/electron/cli.js

> electron@1.4.13 postinstall /home/xxx/.nvm/versions/node/v6.5.0/lib/node_modules/electron
> node install.js

undefined:1
{=true
 ^

SyntaxError: Unexpected token = in JSON at position 1
    at Object.parse (native)
    at exports.parse (/home/xxx/.nvm/versions/node/v6.5.0/lib/node_modules/electron/node_modules/rc/lib/utils.js:15:17)
    at addConfigFile (/home/xxx/.nvm/versions/node/v6.5.0/lib/node_modules/electron/node_modules/rc/index.js:31:20)
    at Array.forEach (native)
    at module.exports (/home/xxx/.nvm/versions/node/v6.5.0/lib/node_modules/electron/node_modules/rc/index.js:44:36)
    at Object.<anonymous> (/home/xxx/.nvm/versions/node/v6.5.0/lib/node_modules/electron/node_modules/electron-download/build/index.js:12:26)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
```

**Comment by kevinsawicki** [comment]
I've published a new version of `electron-download` that should address this, can you try re-installing?

**Comment by dessalines** [comment]
That did it! Thanks!
