### ISSUE TITLE
Failed to find Electron v1.4.13 for linux-arm64

### ISSUE THREAD

**Issue by nsisodiya** [electron/electron#8291]
* Electron version: 1.4.13
* Operating system:
```
uname -a
Linux pine64 3.10.104-2-pine64-longsleep #113 SMP PREEMPT Thu Dec 15 21:46:07 CET 2016 aarch64 aarch64 aarch64 GNU/Linux 
```
### Actual behavior

```sh
ubuntu@pine64:~$ npm install -g electron
/home/ubuntu/.nvm/versions/node/v7.3.0/bin/electron -> /home/ubuntu/.nvm/versions/node/v7.3.0/lib/node_modules/electron/cli.js

> electron@1.4.13 postinstall /home/ubuntu/.nvm/versions/node/v7.3.0/lib/node_modules/electron
> node install.js

/home/ubuntu/.nvm/versions/node/v7.3.0/lib/node_modules/electron/install.js:22
  throw err
  ^

Error: Failed to find Electron v1.4.13 for linux-arm64 at https://github.com/electron/electron/releases/download/v1.4.13/electron-v1.4.13-linux-arm64.zip
    at Request.<anonymous> (/home/ubuntu/.nvm/versions/node/v7.3.0/lib/node_modules/electron/node_modules/nugget/index.js:169:61)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at Request.onRequestResponse (/home/ubuntu/.nvm/versions/node/v7.3.0/lib/node_modules/electron/node_modules/request/request.js:986:10)
    at emitOne (events.js:96:13)
    at ClientRequest.emit (events.js:188:7)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:473:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:99:23)
    at TLSSocket.socketOnData (_http_client.js:362:20)
    at emitOne (events.js:96:13)
npm ERR! Linux 3.10.104-2-pine64-longsleep
npm ERR! argv "/home/ubuntu/.nvm/versions/node/v7.3.0/bin/node" "/home/ubuntu/.nvm/versions/node/v7.3.0/bin/npm" "install" "-g" "electron"
npm ERR! node v7.3.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! electron@1.4.13 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron@1.4.13 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ubuntu/npm-debug.log
```

**Comment by kevinsawicki** [comment]
`arm64` is not currently supported, only `armv7l`.

You can install that version by running `npm install --arch=armv7l electron@1.4.13`.

You can subscribe to #5706 to be notified about ARM64 support.
