### ISSUE TITLE
i`dont what happend with electron

### ISSUE THREAD

**Issue by yefengbar** [electron/electron#8316]
##when i input the commend: `ember g ember-electron` has a err
```
F:\ember-pack-test\node_modules\electron\install.js:22
  throw err
  ^
Error: read ECONNRESET
    at exports._errnoException (util.js:953:11)
    at TLSWrap.onread (net.js:563:26)
electron@1.4.13 postinstall: `node install.js`
Exit status 1
Error: electron@1.4.13 postinstall: `node install.js`
Exit status 1
    at EventEmitter.<anonymous> (F:\ember-pack-test\node_modules\npm\lib\utils\lifecycle.js:255:16)
    at emitTwo (events.js:106:13)
    at EventEmitter.emit (events.js:191:7)
    at ChildProcess.<anonymous> (F:\ember-pack-test\node_modules\npm\lib\utils\spawn.js:40:14)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:850:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)

```

1. env list:
2. node:6.2.0.
3. npm:3.8.9.
4. ember-cli:2.10.0
5. os:win10-64

**Comment by MarshallOfSound** [comment]
It looks like you experienced a network issue, try blowing away your node_modules folder and installing again.

`ECONNRESET` indicates your network connection was reset during the download of the Electron binaries
