### ISSUE TITLE
Issue with electron while using sqlite

### ISSUE THREAD

**Issue by sayanm01** [electron/electron#8324]
Hi there, I am new to electron. I am facing an issue on using sqlite with electron. I got some help with this link https://gist.github.com/maximilian-ruppert/9de273f72c1ba4aa62d6
but I was not able to compile sqlite package for the electron package V1.4.12 and node version v6.9.1  I amusing Windows 7 professional.

The error I am facing is as follows:

```
C:\Users\ky29991.node-gyp\iojs-1.4.12\deps\v8\include\v8.h(91) : see
declaration of 'v8::Object'
C:\Users\ky29991.node-gyp\iojs-1.4.12\deps\v8\include\v8.h(3064): error C2989:
'v8::Array' : class template has already been declared as a non-class template
[D:\Nitin\NodeJS\Final91216\electron\NodeJSSQLite\node_modules\sqlite3\build\n
ode_sqlite3.vcxproj]
C:\Users\ky29991.node-gyp\iojs-1.4.12\deps\v8\include\v8.h(71) : see
declaration of 'v8::Array'

C:\Users\ky29991.node-gyp\iojs-1.4.12\deps\v8\include\v8.h(3418): error C2238:
unexpected token(s) preceding ';' [D:\Nitin\NodeJS\Final91216\electron\NodeJSS
QLite\node_modules\sqlite3\build\node_sqlite3.vcxproj]
C:\Users\ky29991.node-gyp\iojs-1.4.12\deps\v8\include\v8.h(3419): error C2143:
syntax error : missing ';' before '<' [D:\Nitin\NodeJS\Final91216\electron\Nod
eJSSQLite\node_modules\sqlite3\build\node_sqlite3.vcxproj]
C:\Users\ky29991.node-gyp\iojs-1.4.12\deps\v8\include\v8.h(3419): error C4430:
missing type specifier - int assumed. Note: C++ does not support default-int [
D:\Nitin\NodeJS\Final91216\electron\NodeJSSQLite\node_modules\sqlite3\build\nod
e_sqlite3.vcxproj]
C:\Users\ky29991.node-gyp\iojs-1.4.12\deps\v8\include\v8.h(3420): error C2238:
unexpected token(s) preceding ';' [D:\Nitin\NodeJS\Final91216\electron\NodeJSS
QLite\node_modules\sqlite3\build\node_sqlite3.vcxproj]
C:\Users\ky29991.node-gyp\iojs-1.4.12\deps\v8\include\v8.h(3428): error C2061:
syntax error : identifier 'Value' [D:\Nitin\NodeJS\Final91216\electron\NodeJSS
QLite\node_modules\sqlite3\build\node_sqlite3.vcxproj]
C:\Users\ky29991.node-gyp\iojs-1.4.12\deps\v8\include\v8.h(3432): error C2061:
syntax error : identifier 'Value' [D:\Nitin\NodeJS\Final91216\electron\NodeJSS
QLite\node_modules\sqlite3\build\node_sqlite3.vcxproj]
C:\Users\ky29991.node-gyp\iojs-1.4.12\deps\v8\include\v8.h(3432): fatal error
C1003: error count exceeds 100; stopping compilation [D:\Nitin\NodeJS\Final9121
6\electron\NodeJSSQLite\node_modules\sqlite3\build\node_sqlite3.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe failed with exit code: 1
gyp ERR! stack at ChildProcess.onExit (C:\Users\ky29991\AppData\Roaming\npm
node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack at emitTwo (events.js:106:13)
gyp ERR! stack at ChildProcess.emit (events.js:191:7)
gyp ERR! stack at Process.ChildProcess._handle.onexit (internal/child_proces
s.js:215:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Users\ky29991\AppD
ata\Roaming\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild" "--target
=1.4.12" "--arch=x64" "--target_platform=win32" "--dist-url=https://atom.io/down
load/atom-shell" "--module_name=node_sqlite3" "--module_path=../lib/binding/node
-v48-win32-x64"
gyp ERR! cwd D:\Nitin\NodeJS\Final91216\electron\NodeJSSQLite\node_modules\sqlit
e3
gyp ERR! node -v v6.9.1
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
```

Thanking you,
Nitin Kandpal

**Comment by kevinsawicki** [comment]
@sayanm01 have you tried the answer here? http://stackoverflow.com/a/39063263/687965

**Comment by kevinsawicki** [comment]
That stackoverflow answer previously posted should help you build it successfully, I just followed that answer on Windows 10 using Electron 1.4.14 and was able to `require` sqlite3 in Electron and run the sample from https://github.com/mapbox/node-sqlite3#usage.

Closing this out.
