### ISSUE TITLE
windowManager emit getting error

### ISSUE THREAD

**Issue by rawatsandeep670** [electron/electron#8850]
* Electron version: 1.6.1
* Operating system: Window 7 - 64bit

### Expected behavior
send data one window to another window using **windowManager.bridge.emit**

### Actual behavior
Uncaught Error: Could not call remote function 'emit'. Check that the function signature is correct. Underlying error: Cannot read property 'id' of undefined
Error: Could not call remote function 'emit'. Check that the function signature is correct. Underlying error: Cannot read property 'id' of undefined
    at callFunction (C:\Users\Sandeep\AppData\Roaming\npm\node_modules\electron\dist\resources\electron.asar\browser\rpc-server.js:259:11)
    at EventEmitter.<anonymous> (C:\Users\Sandeep\AppData\Roaming\npm\node_modules\electron\dist\resources\electron.asar\browser\rpc-server.js:366:5)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (C:\Users\Sandeep\AppData\Roaming\npm\node_modules\electron\dist\resources\electron.asar\browser\api\web-contents.js:249:37)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
    at callFunction (C:\Users\Sandeep\AppData\Roaming\npm\node_modules\electron\dist\resources\electron.asar\browser\rpc-server.js:259:11)
    at EventEmitter.<anonymous> (C:\Users\Sandeep\AppData\Roaming\npm\node_modules\electron\dist\resources\electron.asar\browser\rpc-server.js:366:5)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (C:\Users\Sandeep\AppData\Roaming\npm\node_modules\electron\dist\resources\electron.asar\browser\api\web-contents.js:249:37)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
    at metaToValue (C:\Users\Sandeep\AppData\Roaming\npm\node_modules\electron\dist\resources\electron.asar\renderer\api\remote.js:218:13)
    at Object.remoteMemberFunction (C:\Users\Sandeep\AppData\Roaming\npm\node_modules\electron\dist\resources\electron.asar\renderer\api\remote.js:114:18)
    at setSmartFoxInstance (http://localhost:9000/scripts/services/deskTileView.js:751:34)
    at http://localhost:9000/scripts/services/deskTileView.js:199:33
    at CallbacksRegistry.apply (C:\Users\Sandeep\AppData\Roaming\npm\node_modules\electron\dist\resources\electron.asar\common\api\callbacks-registry.js:48:42)
    at EventEmitter.<anonymous> (C:\Users\Sandeep\AppData\Roaming\npm\node_modules\electron\dist\resources\electron.asar\renderer\api\remote.js:283:21)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)

### How to reproduce
open any window using **windowManager** e.g.
let myWindow = windowManager.open('home1', "welcom", 'http://localhost:9000/**.html', null, null, true);

after **onReady** calll
windowManager.bridge.emit('new_chat_message', {});

**Comment by MarshallOfSound** [comment]
@rawatsandeep670 `windowManager` is not an Electron API.  Should this issue be raised on that modules repository?

On a side note it just looks like you or the module is trying to pass a browserwindow through remote and passing undefined instead.

**Comment by rawatsandeep670** [comment]
@MarshallOfSound thanks for the response.

I have reported the issue in their repository [#34](https://github.com/TamkeenLMS/electron-window-manager/issues/34)

also, when you say it is passing undefined instead of the browserwindow reference, is it because of the code written by me or internally through the api?

**Comment by MarshallOfSound** [comment]
Without looking into how that module works based entirely on your usage code in your issue I would say it's probably the module not doing a undefined / null check somewhere.  Purely guessing though 😆 

Closing out as this should be tracked on that module 👍

**Comment by rawatsandeep670** [comment]
@MarshallOfSound thanks for your help :sweat_smile:
