### ISSUE TITLE
Can not use node_module using C++

### ISSUE THREAD

**Issue by kazkondo** [electron/electron#9071]
The latest Node.js version is 7.7.4 and the NODE_MODULE_VERSION is 51. 
But the latest Electron build with NODE_MODULE_VERSION 53 option so we get error when we try to use node modules with C++ module. The latest Node.js version is 7.7.4 and the NODE_MODULE_VERSION is 51, that means there is no way to make Electron application with C++ node modules.

* Electron version: 1.6.2
* Operating system: macOS

### Expected behavior

Build with NODE_MODULE_VERSION 51. 

### Actual behavior

Build with NODE_MODULE_VERSION 53.

### How to reproduce

Make sample application using https://github.com/atom/node-keytar, and launch with Electron 1.6.2.

```
Uncaught Exception:
Error: The module '/xxx/node_modules/keytar/build/Release/keytar.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 51. This version of Node.js requires
NODE_MODULE_VERSION 53. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or`npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/xxx/node_modules/keytar/lib/keytar.js:4:12)
    at Object.<anonymous> (/xxx/node_modules/keytar/lib/keytar.js:58:4)
```

**Comment by kazkondo** [comment]
I can fix by doing ./node_modules/.bin/electron-rebuild -v 1.6.2
