### ISSUE TITLE
Electron Fails to Build with Fatal error

### ISSUE THREAD

**Issue by dpati007** [electron/electron#9122]
* Electron version: Electron: 1.6.2	
* Operating system: Linux Ubuntu

### Expected behavior

Building Electron

### Actual behavior

dpatino@dpatino-desktop:~/Desktop/electron/script$ ./bootstrap.py
fatal: Not a git repository (or any of the parent directories): .git

Traceback (most recent call last):
  File "./bootstrap.py", line 264, in <module>
    sys.exit(main())
  File "./bootstrap.py", line 34, in main
    update_submodules()
  File "./bootstrap.py", line 127, in update_submodules
    execute_stdout(['git', 'submodule', 'sync', '--recursive'])
  File "/home/dpatino/Desktop/electron/script/lib/util.py", line 182, in execute_stdout
    execute(argv, env)
  File "/home/dpatino/Desktop/electron/script/lib/util.py", line 170, in execute
    raise e
subprocess.CalledProcessError: Command '['git', 'submodule', 'sync', '--recursive']' returned non-zero exit status 128

### How to reproduce

dpatino@dpatino-desktop:~/Desktop/electron/script$ ./bootstrap.py

**Comment by kevinsawicki** [comment]
@dpati007 did you clone the Electron repository or download it as a tarball?

The error looks to be because it isn't a Git repo so it can't update the submodules.

**Comment by dpati007** [comment]
In this case, I downloaded the .zip from the git repo, unzipped it in a windows environment and ssh'd it into the unix environment.
