### ISSUE TITLE
Could not build in ubuntu 16.04 libchromiumcontent/static_library/libffmpeg.so', needed by 'libffmpeg.so', missing and no known rule to make it

### ISSUE THREAD

**Issue by anandanand84** [electron/electron#9143]
Steps to reproduce.

```
./script/bootstrap.py --dev
./script/create-dist.py
```

Logs 

```
root@ubuntu-8gb-nyc3-01:~/electron# ./script/create-dist.py
ninja: Entering directory `out/R'
ninja: error: '/root/electron/vendor/brightray/vendor/download/libchromiumcontent/static_library/libffmpeg.so', needed by 'libffmpeg.so', missing and no known rule to make it

Traceback (most recent call last):
  File "./script/create-dist.py", line 257, in <module>
    sys.exit(main())
  File "./script/create-dist.py", line 84, in main
    force_build()
  File "./script/create-dist.py", line 109, in force_build
    execute([sys.executable, build, '-c', 'Release'])
  File "/root/electron/script/lib/util.py", line 170, in execute
    raise e
subprocess.CalledProcessError: Command '['/usr/bin/python', '/root/electron/script/build.py', '-c', 'Release']' returned non-zero exit status 1
```

**Comment by cifratila** [comment]
@anandanand84 From what I know if you pass `--dev`, then you don't get the static_library, so you would need to somehow point the bootstrap script to your local one, using: `--libcc_static_library_path`

I recomment just:
```
./script/bootstrap.py -v
./script/create-dist.py
```

**Comment by kevinsawicki** [comment]
> From what I know if you pass --dev, then you don't get the static_library

Yup, you are absolutely right, you cannot generate release builds (which `crete-dist.py` does) if you run bootstrap with `--dev` since the static library is not downloaded, only the shared library is.

Closing this out.
