### ISSUE TITLE
Electron Installation in Angular 4

### ISSUE THREAD

**Issue by hsrtechs** [electron/electron#9307]
*  electron@1.6.6
* Windows 10

### Expected behavior

Installation with angular 4 

### Actual behavior

Error on Post Install script

### How to reproduce
ng new project
cd project
npm install --save-dev electron

```
D:\electron\project1\node_modules\electron\install.js:47
  throw err
  ^
Error: read ECONNRESET
    at exports._errnoException (util.js:1050:11)
    at TLSWrap.onread (net.js:581:26)
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.1.1: wanted {"os":"darwin","arch":"any
"} (current: {"os":"win32","arch":"x64"})
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@1.6.6 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron@1.6.6 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron
npm ERR! There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
```
Full debug log https://gist.github.com/hsrtechs/ca939599fda9db2beaa8e3b04d675364

**Comment by MarshallOfSound** [comment]
> Error: read ECONNRESET

This indicates a network issue on your side of things while downloading the prebuilt Electron binaries.  Can you try on a different network, or just try again 👍 It's a sizeable download (40-50MB) so give it some time
