### ISSUE TITLE
Crash in electron 1.6.8 using remote when sandboxed

### ISSUE THREAD

**Issue by lneir** [electron/electron#9387]
Crash in electron remote.
* Electron version: 1.6.8
* Operating system: Mac OSX 10.10.5

This is only happening on 1.6.8.  Doesn't happen in 1.6.7.

Repo:
1. git clone https://github.com/lneir/electron-remote-issue
2. follow instructions in README
3. crash stack shown below.

This demo repo has sandboxing turned on and is using preload script to access remote class.

crash stack from renderer console:
Uncaught Error: Cannot call constructor on missing remote object 36
Error: Cannot call constructor on missing remote object 36
    at throwRPCError (/Users/lneir/IntelliJProjects/tests/electron-remote-issue/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/rpc-server.js:143:17)
    at EventEmitter.<anonymous> (/Users/lneir/IntelliJProjects/tests/electron-remote-issue/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/rpc-server.js:303:7)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
    at WebContents.<anonymous> (/Users/lneir/IntelliJProjects/tests/electron-remote-issue/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/api/web-contents.js:256:37)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
    at throwRPCError (/Users/lneir/IntelliJProjects/tests/electron-remote-issue/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/rpc-server.js:143:17)
    at EventEmitter.<anonymous> (/Users/lneir/IntelliJProjects/tests/electron-remote-issue/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/rpc-server.js:303:7)
    at emitThree (events.js:116:13)
    at EventEmitter.emit (events.js:194:7)
    at WebContents.<anonymous> (/Users/lneir/IntelliJProjects/tests/electron-remote-issue/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/browser/api/web-contents.js:256:37)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
    at metaToValue (<anonymous>:552:13)
    at new remoteFunction (<anonymous>:565:20)
    at HTMLButtonElement.<anonymous> (file:///Users/lneir/IntelliJProjects/tests/electron-remote-issue/index.html:15:17)

**Comment by tarruda** [comment]
Seems like a bug in objects-registry.js

It only increases reference count the first time an object is referenced, but this can cause problems with page reload. This sequence of events happened when testing @lneir example:

- initial load
- hello.js was added to objects-registry and referenced count increased
- reload
- hello.js was added to objects-registry(no reference count increased)
- after a while, garbage collection in renderer process caused the first reference to hello.js to be released
- browser process removes hello.js from object-registry even though it is still being referenced by the second context.

This was only noticed in 1.6.8 because of the memory leak fix(previously context were never released)

Pushed #9389 with fix
