### ISSUE TITLE
 Error: Cannot find module '../power-monitor'

### ISSUE THREAD

**Issue by jschimmoeller** [electron/electron#9392]
* Electron version: 1.6.6
* Operating system: windows 10

after I do the below command so that I can link in usb libraries and when i run it I get the below error.

npm rebuild --runtime=electron --target=1.6.6 --disturl=https://atom.io/download/atom-shell --build-from-source

> electron . --dev --debug

errr: { Error: Cannot find module '../power-monitor'
    at Module._resolveFilename (module.js:470:15)
    at Function.Module._resolveFilename (C:\Users\s2s-dev\projects\softphone-ui\app-container\node_modules\electron\dist\resources\electron.asar\common\reset-search-paths.js:35:12)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.get [as powerMonitor] (C:\Users\s2s-dev\projects\softphone-ui\app-container\node_modules\electron\dist\resources\electron.asar\browser\api\exports\electron.js:11:16)
    at App.<anonymous> (C:\Users\s2s-dev\projects\softphone-ui\app-container\app\main.js:341:11)
    at emitTwo (events.js:111:20)
    at App.emit (events.js:191:7) code: 'MODULE_NOT_FOUND' }

**Comment by jschimmoeller** [comment]
issue was with order of code and app.makeSingleInstance

**Comment by hexfusion** [comment]
@jschimmoeller could you provide a workaround please?

**Comment by jschimmoeller** [comment]
ok here is a github projects 

https://github.com/jschimmoeller/electron-power-monitor

if you look at the index.js file you will see sample code and when you run this code you will see that console log lines will print out even though you issued app.quit() because of makeSingleInstance.

now you will see a commented out return statement below the quit() .... uncomment it and then run it you will see that the console log lines dont show.  

So, the issue was code was executing when it should have just got out.  

hope this helps

**Comment by akashnimare** [comment]
I'm getting the same error and confirm that it's due to `app.makeSingleInstance`. What it the proper workaround for this?
cc @jschimmoeller, @kevinsawicki, @zcbenz

**Comment by hovancik** [comment]
Adding `return` (as per @jschimmoeller repo) is not working for me. Can we reopen this?

**Comment by hovancik** [comment]
So the solution seems to be `return` indeed, but whole `shouldQuit`block needs to be before any `app.on('ready', ....)`
