### ISSUE TITLE
Unable to debug electron app with electron-inspector. electron-prebuilt missing

### ISSUE THREAD

**Issue by msareen** [electron/electron#9401]
* Electron version: 1.6.1
* Operating system: Windows 10 (with Creator update)

### Expected behavior
While reading and applying instruction written on 
https://github.com/electron/electron/blob/master/docs/tutorial/debugging-main-process-node-inspector.md

**Command**
_node_modules\\.bin\\electron-inspector_ 

Should have started the inspector.

**But it throw error** 

_electron-inspector
node-inspector binaries are incompatible or missing.
Attempting to rebuild...
**Failed to load electron-prebuilt,** abandoning rebuild.
(node:14780) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 2): Error: Cannot find module 'electron-rebuild/lib/node-pre-gyp-fix'_

### How to reproduce

Is this problem is due to reason electron-prebuilt package is renamed to electron and electron-inspector is not updated accordingly?

**Comment by MarshallOfSound** [comment]
@msareen This is an issue with `electron-inspector` using hidden internals of the `electron-rebuild` module which have since changed.  If you lock `electron-rebuild` to `1.4.x` in your package.json this issue will disappear.

The root cause for this issue needs to be fixed at it's source though in `electron-inspector`

**Comment by msareen** [comment]
I tried locking it to version 1.4.x, and saw some progress, but it failed with following error. 

```
node-inspector binaries are incompatible or missing.
Attempting to rebuild...
Rebuilding native node-inspector modules for Electron 1.6.6
Rebuilding C:\Data\Applications\DupsFinders\node_modules\electron-inspector\node_modules/v8-profiler
node-pre-gyp fixer: C:/Data/Applications/DupsFinders/node_modules/electron-inspector/node_modules/v8-profiler/build/prof                                                    iler/v5.6.5/electron-v1.6-win32-x64 copied to C:/Data/Applications/DupsFinders/node_modules/electron-inspector/node_modu                                                    les/v8-profiler/build/profiler/v5.6.5/node-v53-win32-x64
Rebuilding C:\Data\Applications\DupsFinders\node_modules\electron-inspector\node_modules/v8-debug

> v8-debug@0.7.7 preinstall C:\Data\Applications\DupsFinders\node_modules\electron-inspector\node_modules\v8-debug
> node -e 'process.exit(0)'


> v8-debug@0.7.7 install C:\Data\Applications\DupsFinders\node_modules\electron-inspector\node_modules\v8-debug
> node-pre-gyp install --fallback-to-build

Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  debug.cc
  InjectedScriptHost.cc
  win_delay_load_hook.cc
..\src\debug.cc(38): error C2660: 'v8::Debug::Call': function does not take 1 arguments [C:\Data\Applications\DupsFinder                                                    s\node_modules\electron-inspector\node_modules\v8-debug\build\debug.vcxproj]
..\src\debug.cc(46): error C2660: 'v8::Debug::GetDebugContext': function does not take 0 arguments [C:\Data\Applications                                                    \DupsFinders\node_modules\electron-inspector\node_modules\v8-debug\build\debug.vcxproj]
..\src\debug.cc(46): error C2227: left of '->GetIsolate' must point to class/struct/union/generic type [C:\Data\Applicat                                                    ions\DupsFinders\node_modules\electron-inspector\node_modules\v8-debug\build\debug.vcxproj]
..\src\debug.cc(61): error C2660: 'v8::Debug::GetDebugContext': function does not take 0 arguments [C:\Data\Applications                                                    \DupsFinders\node_modules\electron-inspector\node_modules\v8-debug\build\debug.vcxproj]
..\src\debug.cc(66): error C2660: 'v8::Debug::GetDebugContext': function does not take 0 arguments [C:\Data\Applications                                                    \DupsFinders\node_modules\electron-inspector\node_modules\v8-debug\build\debug.vcxproj]
..\src\InjectedScriptHost.cc(173): warning C4996: 'v8::Object::GetRealNamedProperty': was declared deprecated [C:\Data\A                                                    pplications\DupsFinders\node_modules\electron-inspector\node_modules\v8-debug\build\debug.vcxproj]
  c:\data\applications\dupsfinders\node_modules\electron-rebuild\lib\headers\.node-gyp\iojs-1.6.6\deps\v8\include\v8.h(3                                                    220): note: see declaration of 'v8::Object::GetRealNamedProperty'
Failed to execute 'C:\Program Files\nodejs\node.exe C:\Data\Applications\node_modules\node-gyp\bin\node-gyp.js build --f                                                    allback-to-build --module=C:\Data\Applications\DupsFinders\node_modules\electron-inspector\node_modules\v8-debug\build\d                                                    ebug\v0.7.7\electron-v1.6-win32-x64\debug.node --module_name=debug --module_path=C:\Data\Applications\DupsFinders\node_m                                                    odules\electron-inspector\node_modules\v8-debug\build\debug\v0.7.7\electron-v1.6-win32-x64' (1)

node-pre-gyp ERR! Tried to download(404): https://node-inspector.s3.amazonaws.com/debug/v0.7.7/electron-v1.6-win32-x64.t                                                    ar.gz
node-pre-gyp ERR! Pre-built binaries not found for v8-debug@0.7.7 and electron@1.6.6 (electron-v1.6 ABI) (falling back t                                                    o source compile with node-gyp)
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Data\Applications\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.15063
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Data\\Applications\\node_modules\\node-gyp\\bin\\node-gyp.js                                                    " "build" "--fallback-to-build" "--module=C:\\Data\\Applications\\DupsFinders\\node_modules\\electron-inspector\\node_mo                                                    dules\\v8-debug\\build\\debug\\v0.7.7\\electron-v1.6-win32-x64\\debug.node" "--module_name=debug" "--module_path=C:\\Dat                                                    a\\Applications\\DupsFinders\\node_modules\\electron-inspector\\node_modules\\v8-debug\\build\\debug\\v0.7.7\\electron-v                                                    1.6-win32-x64"
gyp ERR! cwd C:\Data\Applications\DupsFinders\node_modules\electron-inspector\node_modules\v8-debug
gyp ERR! node -v v6.10.3
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok
node-pre-gyp ERR! build error
node-pre-gyp ERR! stack Error: Failed to execute 'C:\Program Files\nodejs\node.exe C:\Data\Applications\node_modules\nod                                                    e-gyp\bin\node-gyp.js build --fallback-to-build --module=C:\Data\Applications\DupsFinders\node_modules\electron-inspecto                                                    r\node_modules\v8-debug\build\debug\v0.7.7\electron-v1.6-win32-x64\debug.node --module_name=debug --module_path=C:\Data\                                                    Applications\DupsFinders\node_modules\electron-inspector\node_modules\v8-debug\build\debug\v0.7.7\electron-v1.6-win32-x6                                                    4' (1)
node-pre-gyp ERR! stack     at ChildProcess.<anonymous> (C:\Data\Applications\DupsFinders\node_modules\node-pre-gyp\lib\                                                    util\compile.js:83:29)
node-pre-gyp ERR! stack     at emitTwo (events.js:106:13)
node-pre-gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
node-pre-gyp ERR! stack     at maybeClose (internal/child_process.js:886:16)
node-pre-gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
node-pre-gyp ERR! System Windows_NT 10.0.15063
node-pre-gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Data\\Applications\\DupsFinders\\node_modules\\node                                                    -pre-gyp\\bin\\node-pre-gyp" "install" "--fallback-to-build"
node-pre-gyp ERR! cwd C:\Data\Applications\DupsFinders\node_modules\electron-inspector\node_modules\v8-debug
node-pre-gyp ERR! node -v v6.10.3
node-pre-gyp ERR! node-pre-gyp -v v0.6.34
node-pre-gyp ERR! not ok

npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Data\\Applications\\DupsFinders\\node_modules\\npm\\bin\\npm-cl                                                    i.js" "rebuild" "v8-debug" "--runtime=electron" "--target=1.6.6" "--arch=x64" "--update-binary"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! v8-debug@0.7.7 install: `node-pre-gyp install --fallback-to-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the v8-debug@0.7.7 install script 'node-pre-gyp install --fallback-to-build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the v8-debug package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-pre-gyp install --fallback-to-build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs v8-debug
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls v8-debug
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Data\Applications\DupsFinders\node_modules\electron-inspector\node_modules\npm-debug.log

(node:17332) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): Error: Process exited with                                                     code: 1

```

Is there is a easy/another way to debug electron main process step by step ?
