### ISSUE TITLE
4 electron tests failed to run with master branch latest revision

### ISSUE THREAD

**Issue by KarenHuang2016** [electron/electron#9442]
We tried to build and run tests for electron. There are 4 tests failed after master branch revision [fb85b26](https://github.com/electron/electron/commit/fb85b267671483ecad8daacd7e87869c4cb97912).
Could you please help to take a look at this? Thanks in advance!

**Repro steps:**
1. git clone https://github.com/electron/electron.git D:\Electron\src
2. Open a clean command prompt and browse to D:\Electron\src
3. set APPVEYOR=True
4. python script\bootstrap.py -v --target_arch=ia32
5. vendor\depot_tools\ninja.exe -C out\R electron -v -d keeprsp
6. out\R\electron.exe spec --ci

### Expected behavior
All tests passed

### Actual behavior
There are 4 tests failed as below:
**not ok 112 BrowserWindow module "web-preferences" option nativeWindowOpen option loads native addons correctly after reload**
  Error: Timeout of 30000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
      at D:\Electron\src\spec\node_modules\mocha\lib\runnable.js:232:19
**not ok 656 modules support third-party module runas can be required in renderer**
  Error: %1 is not a valid Win32 application.  
  \\?\D:\Electron\src\node_modules\runas\build\Release\runas.node
      at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:173:20)
      at Object.Module._extensions..node (module.js:598:18)
      at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:173:20)
      at Module.load (module.js:488:32)
      at tryModuleLoad (module.js:447:12)
      at Function.Module._load (module.js:439:3)
      at Module.require (module.js:498:17)
      at require (internal/module.js:20:19)
      at Object.<anonymous> (D:\Electron\src\node_modules\runas\lib\runas.js:4:11)
      at Object.<anonymous> (D:\Electron\src\node_modules\runas\lib\runas.js:47:4)
**not ok 657 modules support third-party module runas can be required in node binary**
  AssertionError: '%1 is not a valid Win32 application.\r\n\\\\?\\D:\\Electron\\src\\node_modules\\runas\\build\\Release\\runas.node' == 'ok'
      at ChildProcess.<anonymous> (D:\Electron\src\spec\modules-spec.js:22:20)
      at emitTwo (events.js:106:13)
      at ChildProcess.emit (events.js:194:7)
      at process.nextTick (internal/child_process.js:766:12)
      at _combinedTickCallback (internal/process/next_tick.js:73:7)
      at process._tickCallback (internal/process/next_tick.js:104:9)
**not ok 710 <webview> tag nodeintegration attribute loads native modules when navigation happens**
  AssertionError: 'Uncaught Error: Cannot find module \'D:\\Electron\\src\\spec\\node_modules\\runas\'' == 'function'
      at HTMLElement.listener2 (D:\Electron\src\spec\webview-spec.js:160:20)
      at WebViewImpl.dispatchEvent (D:\Electron\src\out\R\resources\electron.asar\renderer\web-view\web-view.js:175:22)
      at dispatchEvent (D:\Electron\src\out\R\resources\electron.asar\renderer\web-view\guest-view-internal.js:55:11)
      at EventEmitter.<anonymous> (D:\Electron\src\out\R\resources\electron.asar\renderer\web-view\guest-view-internal.js:72:7)
      at emitMany (events.js:127:13)
      at EventEmitter.emit (events.js:204:7)

**Comment by kevinsawicki** [comment]
This is probably related to https://github.com/electron/electron/commit/c19c14d0b3ba7967242002c2cd1b42e9cde6457e
