### ISSUE TITLE
MAC: Electron-builder fail for linux

### ISSUE THREAD

**Issue by 10SPD** [electron/electron#9462]
* Electron version: 1.7.0
* Operating system: OSX

### Expected behavior

Should build package for Linux distribution

### Actual behavior

NPM Version: 4.6.1
Node Version: v7.10.0

The build for OSX dmg and Windwos works fine, but when I try to build for Linux the package fails:

### Build Response
```
Packaging for linux x64 using electron 1.7.0 to release/linux-unpacked
Building AppImage for arch x64
Building deb
Error: Exit code: 1. Command failed: /Users/mikepriest/Library/Caches/electron-builder/fpm/fpm-1.8.1-20150715-2.2.2/fpm -s dir -t deb --architecture a
md64 --name ExamBrowser --force --after-install /var/folders/bd/rz559x1s3md7kmxdzgmfqy0h0000gn/T/electron-builder-VUIcpu/0-2-after-install --after-rem
ove /var/folders/bd/rz559x1s3md7kmxdzgmfqy0h0000gn/T/electron-builder-VUIcpu/0-3-after-remove --description
 Trifork ExamBrowser is a locked down web-browser to be used in secure high-stakes examination environments. --maintainer C. T. Lin <chentsulin@gmail.
com> --vendor C. T. Lin <chentsulin@gmail.com> --version 1.0.0 --package /Users/mikepriest/source/Browser/exambrowser-electron/release/ExamBrowser_1.0
.0_amd64.deb --url https://github.com/chentsulin/electron-react-boilerplate --deb-compression xz --depends gconf2 --depends gconf-service --depends li
bnotify4 --depends libappindicator1 --depends libxtst6 --depends libnss3 --depends libxss1 --license MIT /Users/mikepriest/source/Browser/exambrowser-
electron/release/linux-unpacked/=/opt/exambrowser /Users/mikepriest/source/Browser/exambrowser-electron/resources/icons/1024x1024.png=/usr/share/icons
/hicolor/1024x1024/apps/exambrowser.png /Users/mikepriest/source/Browser/exambrowser-electron/resources/icons/128x128.png=/usr/share/icons/hicolor/128
x128/apps/exambrowser.png /Users/mikepriest/source/Browser/exambrowser-electron/resources/icons/16x16.png=/usr/share/icons/hicolor/16x16/apps/exambrow
ser.png /Users/mikepriest/source/Browser/exambrowser-electron/resources/icons/24x24.png=/usr/share/icons/hicolor/24x24/apps/exambrowser.png /Users/mik
epriest/source/Browser/exambrowser-electron/resources/icons/256x256.png=/usr/share/icons/hicolor/256x256/apps/exambrowser.png /Users/mikepriest/source
/Browser/exambrowser-electron/resources/icons/32x32.png=/usr/share/icons/hicolor/32x32/apps/exambrowser.png /Users/mikepriest/source/Browser/exambrows
er-electron/resources/icons/48x48.png=/usr/share/icons/hicolor/48x48/apps/exambrowser.png /Users/mikepriest/source/Browser/exambrowser-electron/resour
ces/icons/512x512.png=/usr/share/icons/hicolor/512x512/apps/exambrowser.png /Users/mikepriest/source/Browser/exambrowser-electron/resources/icons/64x6
4.png=/usr/share/icons/hicolor/64x64/apps/exambrowser.png /Users/mikepriest/source/Browser/exambrowser-electron/resources/icons/96x96.png=/usr/share/i
cons/hicolor/96x96/apps/exambrowser.png /var/folders/bd/rz559x1s3md7kmxdzgmfqy0h0000gn/T/electron-builder-VUIcpu/0-4-exambrowser.desktop=/usr/share/ap
plications/exambrowser.desktop

{:timestamp=>"2017-05-14T18:05:04.286885+0200", :message=>"Debian tools (dpkg/apt) don't do well with packages that use capital letters in the name. I
n some cases it will automatically downcase them, in others it will not. It is confusing. Best to not use any capital letters at all. I have downcased
 the package name for you just to be safe.", :oldname=>"ExamBrowser", :fixedname=>"exambrowser", :level=>:warn}
{:timestamp=>"2017-05-14T18:05:04.299923+0200", :message=>"Debian packaging tools generally labels all files in /etc as config files, as mandated by p
olicy, so fpm defaults to this behavior for deb packages. You can disable this default behavior with --deb-no-default-config-files flag", :level=>:war
n}
{:timestamp=>"2017-05-14T18:05:04.633739+0200", :message=>"Debian packaging tools generally labels all files in /etc as config files, as mandated by p
olicy, so fpm defaults to this behavior for deb packages. You can disable this default behavior with --deb-no-default-config-files flag", :level=>:war
n}
{:timestamp=>"2017-05-14T18:05:05.006964+0200", :message=>"Process failed: gtar failed (exit code 2). Full command was:[\"gtar\", \"-C\", \"/var/folde
rs/bd/rz559x1s3md7kmxdzgmfqy0h0000gn/T/package-dir-staging-46259710e12e86414e3108cfa6201953fb85c7cdd6e4693b7ea68ab5e864\", \"-J\", \"--numeric-owner\"
, \"--owner\", \"0\", \"--numeric-owner\", \"--group\", \"0\", \"-cf\", \"/var/folders/bd/rz559x1s3md7kmxdzgmfqy0h0000gn/T/package-deb-build-a3f5e7dcc
71a06c595e2b037d40965e6c6a586a08248e7871f92825678aa/data.tar.xz\", \".\"]", :level=>:error}

 at /Users/mikepriest/source/Browser/exambrowser-electron/node_modules/electron-builder-util/src/util.ts:75:16
    at ChildProcess.exithandler (child_process.js:212:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:194:7)
    at maybeClose (internal/child_process.js:899:16)
    at Socket.<anonymous> (internal/child_process.js:342:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:191:7)
    at Pipe._handle.close [as _onclose] (net.js:511:12)
From previous event:
    at exec (/Users/mikepriest/source/Browser/exambrowser-electron/node_modules/electron-builder-util/src/util.ts:53:3)
    at /Users/mikepriest/source/Browser/exambrowser-electron/node_modules/electron-builder/src/targets/fpm.ts:176:11
    at Generator.next (<anonymous>)
From previous event:
    at FpmTarget.build (/Users/mikepriest/source/Browser/exambrowser-electron/node_modules/electron-builder/out/targets/fpm.js:227:11)
    at default.each.it (/Users/mikepriest/source/Browser/exambrowser-electron/node_modules/electron-builder/src/platformPackager.ts:107:87)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at postAsyncTasks.push.default.map.then (/Users/mikepriest/source/Browser/exambrowser-electron/node_modules/electron-builder/src/platformPackager.
ts:107:35)
From previous event:
    at LinuxPackager.packageInDistributableFormat (/Users/mikepriest/source/Browser/exambrowser-electron/node_modules/electron-builder/src/platformPac
kager.ts:107:8)
    at /Users/mikepriest/source/Browser/exambrowser-electron/node_modules/electron-builder/src/platformPackager.ts:102:10
    at Generator.next (<anonymous>)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at LinuxPackager.pack (/Users/mikepriest/source/Browser/exambrowser-electron/node_modules/electron-builder/out/platformPackager.js:169:11)
    at /Users/mikepriest/source/Browser/exambrowser-electron/node_modules/electron-builder/src/packager.ts:257:24
    at Generator.next (<anonymous>)

at xfs.stat (/Users/mikepriest/source/Browser/exambrowser-electron/node_modules/fs-extra-p/node_modules/fs-extra/lib/mkdirs/mkdirs.js:56:16)
    at /Users/mikepriest/source/Browser/exambrowser-electron/node_modules/graceful-fs/polyfills.js:287:18
    at FSReqWrap.oncomplete (fs.js:114:15)
From previous event:
    at Packager.doBuild (/Users/mikepriest/source/Browser/exambrowser-electron/node_modules/electron-builder/out/packager.js:379:11)
    at /Users/mikepriest/source/Browser/exambrowser-electron/node_modules/electron-builder/src/packager.ts:170:52
    at Generator.next (<anonymous>)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Packager.build (/Users/mikepriest/source/Browser/exambrowser-electron/node_modules/electron-builder/out/packager.js:274:11)
    at /Users/mikepriest/source/Browser/exambrowser-electron/node_modules/electron-builder/src/builder.ts:198:33
    at Generator.next (<anonymous>)
From previous event:
    at build (/Users/mikepriest/source/Browser/exambrowser-electron/node_modules/electron-builder/out/builder.js:70:21)
    at Object.<anonymous> (/Users/mikepriest/source/Browser/exambrowser-electron/node_modules/electron-builder/out/cli/build-cli.js:71:41)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:427:7)
    at startup (bootstrap_node.js:151:9)
    at bootstrap_node.js:542:3
```

### NPM Log
```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node',
1 verbose cli   '/usr/local/bin/npm',
1 verbose cli   'run',
1 verbose cli   'package-linux' ]
2 info using npm@4.6.1
3 info using node@v7.10.0
4 verbose run-script [ 'prepackage-linux', 'package-linux', 'postpackage-linux' ]
5 info lifecycle electron-exam-browser@0.12.0~prepackage-linux: electron-exam-browser@0.12.0
6 silly lifecycle electron-exam-browser@0.12.0~prepackage-linux: no script for prepackage-linux, continuing
7 info lifecycle electron-exam-browser@0.12.0~package-linux: electron-exam-browser@0.12.0
8 verbose lifecycle electron-exam-browser@0.12.0~package-linux: unsafe-perm in lifecycle true
9 verbose lifecycle electron-exam-browser@0.12.0~package-linux: PATH: /usr/local/lib/node_modules/npm/bin/node-gyp-bin:/Users/mikepriest/source/Browser/exambrowser-electron/node_modules/.bin:/usr/local/apache-maven/apache-maven-3.3.9/bin:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/apache-maven/apache-maven-3.3.9/bin:/Library/Java/JavaVirtualMachines/jdk1.8.0_45.jdk/Contents/Home/bin:
10 verbose lifecycle electron-exam-browser@0.12.0~package-linux: CWD: /Users/mikepriest/source/Browser/exambrowser-electron
11 silly lifecycle electron-exam-browser@0.12.0~package-linux: Args: [ '-c', 'npm run build && build --linux' ]
12 silly lifecycle electron-exam-browser@0.12.0~package-linux: Returned: code: 255  signal: null
13 info lifecycle electron-exam-browser@0.12.0~package-linux: Failed to exec package-linux script
14 verbose stack Error: electron-exam-browser@0.12.0 package-linux: `npm run build && build --linux`
14 verbose stack Exit status 255
14 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:194:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:194:7)
14 verbose stack     at maybeClose (internal/child_process.js:899:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid electron-exam-browser@0.12.0
16 verbose cwd /Users/mikepriest/source/Browser/exambrowser-electron
17 verbose Darwin 16.5.0
18 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "package-linux"
19 verbose node v7.10.0
20 verbose npm  v4.6.1
21 error code ELIFECYCLE
22 error errno 255
23 error electron-exam-browser@0.12.0 package-linux: `npm run build && build --linux`
23 error Exit status 255
24 error Failed at the electron-exam-browser@0.12.0 package-linux script.
24 error This is probably not a problem with npm. There is likely additional logging output above.
25 verbose exit [ 255, true ]
```

### How to reproduce

Try package for linux.

**Comment by enlight** [comment]
You you should open an issue at https://github.com/electron-userland/electron-builder
