### ISSUE TITLE
[solved] Electron build: node-gyp failed (LNK1106) after electron update from 1.6.7 to 1.6.8

### ISSUE THREAD

**Issue by d9k** [electron/electron#9532]
* Electron version: 1.6.8
* Operating system: Windows 7 x64
* Tested electron-builder versions: 16.8.4, 17.8.0
* Node-gyp version: 3.6.1
* ffi: 2.2.0

### Expected behavior

Successful build is expected as was for electron `v. 1.6.7.`

### Actual behavior

`> node_modules\.bin\build` command.

Following errors appear:

```
Rebuilding native production dependencies for win32:x64

> ffi@2.2.0 install C:\cr\MyElectronApp\app\node_modules\ffi
> node-gyp rebuild


C:\cr\MyElectronApp\app\node_modules\ffi>if not defined npm_config_node_gyp (node "C:\PROGRA~1\nodejs\node_modules\npm\b
in\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
  Building assembly file ..\..\..\deps\libffi\src\x86\win64.asm
   Assembling: ..\..\..\deps\libffi\src\x86\win64.asm
  prep_cif.c
  types.c
  raw_api.c
  java_raw_api.c
  closures.c
  ffi.c
  win_delay_load_hook.c
  ffi.vcxproj -> C:\cr\MyElectronApp\app\node_modules\ffi\build\Release\\libffi.lib
  ffi.cc
  callback_info.cc
  threaded_callback_invokation.cc
  win32-dlfcn.cc
  win_delay_load_hook.c
C:\Users\Administrator\.electron-gyp\.node-gyp\iojs-1.6.8\Release\iojs.lib : fatal error LNK1106: invalid file or disk
full: cannot seek to 0x2375D4 [C:\cr\MyElectronApp\app\node_modules\ffi\build\ffi_bindings.vcxproj]
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\MSBuild\12.0\bin\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\PROGRA~1\nodejs\node_modules\npm\node_modules\node-gyp\lib\build.js:276:23
)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Windows_NT 6.1.7601
gyp ERR! command "C:\\PROGRA~1\\nodejs\\node.exe" "C:\\PROGRA~1\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\
\node-gyp.js" "rebuild"
gyp ERR! cwd C:\cr\MyElectronApp\app\node_modules\ffi
gyp ERR! node -v v4.4.0
gyp ERR! node-gyp -v v3.3.0
gyp ERR! not ok

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\PROGRA~1\\nodejs\\node.exe" "C:\\PROGRA~1\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "rebuild" "ffi
" "ref"
npm ERR! node v4.4.0
npm ERR! npm  v2.14.20
npm ERR! code ELIFECYCLE
npm ERR! ffi@2.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ffi@2.2.0 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the ffi package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ffi
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!
npm ERR!     npm owner ls ffi
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\cr\MyElectronApp\app\npm-debug.log
Error: npm.cmd exited with code 1
    at ChildProcess.<anonymous> (C:\cr\MyElectronApp\node_modules\electron-builder\node_modules\electron-builder-util\sr
c\util.ts:129:14)
    at ChildProcess.g (events.js:260:16)
    at emitTwo (events.js:87:13)
    at ChildProcess.emit (events.js:172:7)
    at maybeClose (internal/child_process.js:827:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
From previous event:
    at spawn (C:\cr\MyElectronApp\node_modules\electron-builder\node_modules\electron-builder-util\src\util.ts:97:3)
    at C:\cr\MyElectronApp\node_modules\electron-builder\src\yarn.ts:136:5
From previous event:
    at rebuild (C:\cr\MyElectronApp\node_modules\electron-builder\out\yarn.js:95:22)
    at C:\cr\MyElectronApp\node_modules\electron-builder\src\yarn.ts:16:11
    at next (native)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at installOrRebuild (C:\cr\MyElectronApp\node_modules\electron-builder\out\yarn.js:33:21)
    at C:\cr\MyElectronApp\node_modules\electron-builder\src\packager.ts:404:13
    at next (native)
From previous event:
    at Packager.installAppDependencies (C:\cr\MyElectronApp\node_modules\electron-builder\out\packager.js:486:11)
    at C:\cr\MyElectronApp\node_modules\electron-builder\src\packager.ts:231:20
    at next (native)
From previous event:
    at Packager.doBuild (C:\cr\MyElectronApp\node_modules\electron-builder\out\packager.js:379:11)
    at C:\cr\MyElectronApp\node_modules\electron-builder\src\packager.ts:170:52
    at next (native)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
From previous event:
    at Packager.build (C:\cr\MyElectronApp\node_modules\electron-builder\out\packager.js:274:11)
    at C:\cr\MyElectronApp\node_modules\electron-builder\src\builder.ts:198:33
    at next (native)
From previous event:
    at build (C:\cr\MyElectronApp\node_modules\electron-builder\out\builder.js:70:21)
    at Object.<anonymous> (C:\cr\MyElectronApp\node_modules\electron-builder\out\cli\build-cli.js:71:41)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3
```

**Comment by cifratila** [comment]
@d9k From logs I see your node-gyp version is `gyp ERR! node-gyp -v v3.3.0` and not 3.6.0

I know building some native node modules on Windows can cause compilation errors on distros with Visual Studio 2015 Update 3 and some versions of node-gyp. Would try to search somewhere about some fixes or just upgrade node-gyp and/or node.

**Comment by d9k** [comment]
@cifratila, thanks!

```
>node-gyp -v
v3.6.1
```

But at the build log another version:
`gyp ERR! node-gyp -v v3.3.0`

Very strange...

**Comment by d9k** [comment]
`node-gyp 3.6.1` was installed at
`C:\Users\Administrator\AppData\Roaming\npm\node_modules\`

and `node-gyp 3.3.0` was located at
`C:\Program Files\nodejs\node_modules\npm\node_modules\`

I had to delete older version.

@cifratila, thanks, it works now!
