### ISSUE TITLE
Bootstrapping fails after some time

### ISSUE THREAD

**Issue by Herobone** [electron/electron#9575]
* Electron version: 1.6.2
* Operating system: Windows 10 64Bit

### Expected behavior

Finish the process and that all files are installed

### Actual behavior

The Python Script crashes and throws lots of Errors

### How to reproduce

I have Visual Studio 2017 installed!!! (I can't get 2015 anywhere)
I use Python 2.7!!!
I tried it with multiple consoles! (Hyper, Git Bash, Bash, Admin Bash, PowerShell)

$ cd electron
$ python script/bootstrap.py

### Console Output

git submodule status vendor/libchromiumcontent
 a3cff052273b659702c6a8728e28a3b45659cd76 vendor/libchromiumcontent (v51.0.2704.61-323-ga3cff05)

C:\Python27\python.exe C:\Users\user\Documents\electron\script\update.py
Das System kann den angegebenen Pfad nicht finden.
Traceback (most recent call last):
  File "vendor\gyp\gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "vendor\gyp\pylib\gyp\__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "vendor\gyp\pylib\gyp\__init__.py", line 538, in main
    return gyp_main(args)
  File "vendor\gyp\pylib\gyp\__init__.py", line 514, in gyp_main
    options.duplicate_basename_check)
  File "vendor\gyp\pylib\gyp\__init__.py", line 98, in Load
    generator.CalculateVariables(default_variables, params)
  File "vendor\gyp\pylib\gyp\generator\ninja.py", line 1685, in CalculateVariables
    gyp.msvs_emulation.CalculateCommonVariables(default_variables, params)
  File "vendor\gyp\pylib\gyp\msvs_emulation.py", line 1083, in CalculateCommonVariables
    msvs_version = gyp.msvs_emulation.GetVSVersion(generator_flags)
  File "vendor\gyp\pylib\gyp\msvs_emulation.py", line 934, in GetVSVersion
    allow_fallback=False)
  File "vendor\gyp\pylib\gyp\MSVSVersion.py", line 447, in SelectVisualStudioVersion
    raise ValueError('Could not locate Visual Studio installation.')
ValueError: Could not locate Visual Studio installation.
None
Traceback (most recent call last):
  File "script\bootstrap.py", line 299, in <module>
    sys.exit(main())
  File "script\bootstrap.py", line 67, in main
    run_update(defines, args.msvs)
  File "script\bootstrap.py", line 270, in run_update
    execute_stdout(args)
  File "C:\Users\user\Documents\electron\script\lib\util.py", line 181, in execute_stdout
    raise e
subprocess.CalledProcessError: Command '['C:\\Python27\\python.exe', 'C:\\Users\\user\\Documents\\electron\\script\\update.py']' returned non-zero exit status 1

**Comment by cifratila** [comment]
@Herobone I think Electron hasn't been tested with VS 2017 and a lot of the underlying modules used for building will probably not work in there, for example the one you pointed out is gyp.

I think you cannot even yet compile Chromium using VS 2017, the requirement is still VS 2015 Update 3.

**Comment by kevinsawicki** [comment]
Closing this out, VS 2015 is required, you can download it from https://my.visualstudio.com/Downloads?q=visual%20studio%20community%202015%20update%203 with a free account.
