### ISSUE TITLE
bootstrap.py failing on windows

### ISSUE THREAD

**Issue by brandonecraig** [electron/electron#963]
Running python script\bootstrap.py from the Visual Studio command prompt is giving me this error. I'm on windows 7.

```
C:\Users\me\Documents\GitHub\atom-shell>python script\bootstrap.py

> atom-shell@0.20.3 preinstall C:\Users\me\Documents\GitHub\atom-shel
l
> node -e 'process.exit(0)'


> keytar@2.0.3 install C:\Users\me\Documents\GitHub\atom-shell\node_m
odules\atom-package-manager\node_modules\keytar
> node-gyp rebuild


C:\Users\me\Documents\GitHub\atom-shell\node_modules\atom-package-man
ager\node_modules\keytar>node "C:\Program Files (x86)\nodejs\node_modules\npm\bi
n\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild

> oniguruma@3.0.5 install C:\Users\me\Documents\GitHub\atom-shell\nod
e_modules\atom-package-manager\node_modules\first-mate\node_modules\oniguruma
> node-gyp rebuild


C:\Users\me\Documents\GitHub\atom-shell\node_modules\atom-package-man
ager\node_modules\first-mate\node_modules\oniguruma>node "C:\Program Files (x86)
\nodejs\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-
gyp.js" rebuild
gypnpm WARN package.json github-url-from-git@1.1.1 No repository field.

> git-utils@2.2.0 install C:\Users\me\Documents\GitHub\atom-shell\nod
e_modules\atom-package-manager\node_modules\git-utils
> node-gyp rebuild


C:\Users\me\Documents\GitHub\atom-shell\node_modules\atom-package-man
ager\node_modules\git-utils>node "C:\Program Files (x86)\nodejs\node_modules\npm
\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild

npm ERR! keytar@2.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the keytar@2.0.3 install script.
npm ERR! This is most likely a problem with the keytar package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls keytar
npm ERR! There is likely additional logging output above.
npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\\Program Files (x86)\\nodejs\\\\node.exe" "C:\\Program File
s (x86)\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
npm ERR! cwd C:\Users\Brandon Craig\Documents\GitHub\atom-shell
npm ERR! node -v v0.10.35
npm ERR! npm -v 1.4.28
npm ERR! code ELIFECYCLE

Traceback (most recent call last):
  File "script\bootstrap.py", line 127, in <module>
    sys.exit(main())
  File "script\bootstrap.py", line 27, in main
    update_node_modules('.')
  File "script\bootstrap.py", line 68, in update_node_modules
    execute_stdout([NPM, 'install'])
  File "C:\Users\Brandon Craig\Documents\GitHub\atom-shell\script\lib\util.py",
line 150, in execute_stdout
    execute(argv)
  File "C:\Users\Brandon Craig\Documents\GitHub\atom-shell\script\lib\util.py",
line 138, in execute
    raise e
subprocess.CalledProcessError: Command '['npm.cmd', 'install']' returned non-zer
o exit status 1
```

**Comment by brandonecraig** [comment]
If anyone is curious, I got past this by uninstalling all versions of .NET and reinstalling 4.5.1

**Comment by jimgraham** [comment]
I also had this issue. I did the following 

 * Reinstalled VS 2012 Express to get the 2012 version of the VC++ build tools
 * ran `npm config set msvs_version 2012 --global` as per http://kevgriffin.com/specifying-visual-studio-version-in-npm-installs/

Perhaps an update to the docs?

**Comment by zcbenz** [comment]
@jimgraham Have you tried VS 2013 Community Edition?

**Comment by jimgraham** [comment]
@zcbenz I have VS 2013 pro already installed (it's my primary IDE) 

I can test this out on a clean VirtualBox install tomorrow if that helps.

**Comment by zcbenz** [comment]
I guess it is caused by multiple versions of VS installed, I'll add this to docs, so no need to have another test.  And thanks for finding it out.
