### ISSUE TITLE
Electron build failed in Linux & Windows (robotjs 0.4.7 failed in travis & normalize-package-data cannot find in Appveyor)

### ISSUE THREAD

**Issue by fyhao** [electron/electron#9658]
* Electron version: 1.6.10
* Operating system: Travis Linux / Appveyor Windows

### Expected behavior

Successfully built Electron

### Actual behavior

Travis & Appveyor built failed as:

Travis error: https://travis-ci.org/fyhao/electron-wf/jobs/239000922
`
make: *** [Release/obj.target/robotjs/src/robotjs.o] Error 1
make: Leaving directory `/home/travis/build/fyhao/electron-wf/node_modules/robotjs/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/travis/.nvm/versions/node/v8.0.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:285:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:197:12)
gyp ERR! System Linux 4.8.12-040812-generic
gyp ERR! command "/home/travis/.nvm/versions/node/v8.0.0/bin/node" "/home/travis/.nvm/versions/node/v8.0.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/travis/build/fyhao/electron-wf/node_modules/robotjs
gyp ERR! node -v v8.0.0
gyp ERR! node-gyp -v v3.6.1
gyp0m ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! robotjs@0.4.7 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the robotjs@0.4.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2017-06-03T04_40_58_770Z-debug.log
The command "eval npm install  " failed 3 times.
The command "npm install " failed and exited with 1 during .
Your build has been stopped.
`
Appveyor error: https://ci.appveyor.com/project/electron-bot/electron-prebuilt/branch/master/job/80njubw65q42297i
`
 fsevents@1.1.1 install C:\projects\electron-wf\node_modules\fsevents
> node install
> electron-prebuilt@1.4.13 postinstall C:\projects\electron-wf\node_modules\electron-prebuilt
> node install.js
> electron@1.6.10 postinstall C:\projects\electron-wf\node_modules\electron
> node install.js
> electron-wf@0.1.0 postinstall C:\projects\electron-wf
> install-app-deps
Error: Cannot find module 'normalize-package-data'
    at Function.Module._resolveFilename (module.js:455:15)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\projects\electron-wf\node_modules\electron-builder\out\util\readPackageJson.js:202:23)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at _load_readPackageJson (C:\projects\electron-wf\node_modules\electron-builder\out\cli\install-app-deps.js:61:31)
    at C:\projects\electron-wf\node_modules\electron-builder\out\cli\install-app-deps.js:26:56
    at next (native)
From previous event:
    at main (C:\projects\electron-wf\node_modules\electron-builder\out\cli\install-app-deps.js:36:21)
    at Object.<anonymous> (C:\projects\electron-wf\node_modules\electron-builder\out\cli\install-app-deps.js:72:1)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.runMain (module.js:590:10)
    at run (bootstrap_node.js:394:7)
    at startup (bootstrap_node.js:149:9)
    at bootstrap_node.js:509:3
npm ERR! code ELIFECYCLE
npm ERR! errno 4294967295
npm ERR! electron-wf@0.1.0 postinstall: `install-app-deps`
npm ERR! Exit status 4294967295
npm ERR! 
npm ERR! Failed at the electron-wf@0.1.0 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\appveyor\AppData\Roaming\npm-cache\_logs\2017-06-03T04_39_54_431Z-debug.log
The batch file cannot be found.
Command exited with code 1
`

### How to reproduce
Refer the issue here: https://github.com/fyhao/electron-wf/issues/123
The failed build in travis: https://travis-ci.org/fyhao/electron-wf/jobs/239000922
The failed build in appveyor: https://ci.appveyor.com/project/electron-bot/electron-prebuilt/branch/master/job/80njubw65q42297i
The package json: https://github.com/fyhao/electron-wf/blob/master/package.json

**Comment by codebytere** [comment]
We are no longer implementing bugfixes for versions of Electron <= `1.7.x`, so i'm going to close this issue but if it is still persisting in more recent versions of Electron we can certainly reopen it!
