### ISSUE TITLE
npm install electron on Windows 10 error!!!

### ISSUE THREAD

**Issue by BobOntario** [electron/electron#9707]
I am trying to install electron using npm:
```
npm install electron --save-dev
```

[npm-debug.log.txt](https://github.com/electron/electron/files/1062185/npm-debug.log.txt)
[npm-debug.log.txt](https://github.com/electron/electron/files/1062181/npm-debug.log.txt)
```
electron@1.6.10 postinstall C:\Electron\node_modules\electron
> node install.js

C:\Electron\node_modules\electron\install.js:47
  throw err
  ^

Error: unable to get local issuer certificate
    at Error (native)
    at TLSSocket.<anonymous> (_tls_wrap.js:1092:38)
    at emitNone (events.js:86:13)
    at TLSSocket.emit (events.js:185:7)
    at TLSSocket._finishInit (_tls_wrap.js:610:8)
    at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:440:38)
npm WARN Electron@1.0.0 No description
npm WARN Electron@1.0.0 No repository field.
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "electron"
npm ERR! node v6.11.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! electron@1.6.10 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron@1.6.10 postinstall script 'node install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Electron\npm-debug.log
```

**Comment by Dmitry1987** [comment]
Hey guys, and I got similar error but not about certificate:
it's same version 1.6.10 so i thought I'll not open a new issue.  Anyone knows what it is?  (I just run 'npm install' in that vue-electron-boilerplate folder)
```
19779 verbose lifecycle electron@1.6.10~postinstall: CWD: C:\mydata\electron\electron-vue-boilerplate\node_modules\electron
19780 silly lifecycle electron@1.6.10~postinstall: Args: [ '/d /s /c', 'node install.js' ]
19781 silly lifecycle electron@1.6.10~postinstall: Returned: code: 1  signal: null
19782 info lifecycle electron@1.6.10~postinstall: Failed to exec postinstall script
19783 verbose unlock done using C:\Users\dima.shmakov\AppData\Roaming\npm-cache\_locks\staging-0f217cf1e953b83d.lock for C:\mydata\electron\electron-vue-boilerplate\node_modules\.staging
19784 warn electron-vue-boilerplate@1.0.0 No repository field.
19785 verbose stack Error: electron@1.6.10 postinstall: `node install.js`
19785 verbose stack Exit status 1
19785 verbose stack     at EventEmitter.<anonymous> (C:\Users\dima.shmakov\AppData\Roaming\nvm\v8.1.2\node_modules\npm\lib\utils\lifecycle.js:283:16)
19785 verbose stack     at emitTwo (events.js:125:13)
19785 verbose stack     at EventEmitter.emit (events.js:213:7)
19785 verbose stack     at ChildProcess.<anonymous> (C:\Users\dima.shmakov\AppData\Roaming\nvm\v8.1.2\node_modules\npm\lib\utils\spawn.js:40:14)
19785 verbose stack     at emitTwo (events.js:125:13)
19785 verbose stack     at ChildProcess.emit (events.js:213:7)
19785 verbose stack     at maybeClose (internal/child_process.js:897:16)
19785 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
19786 verbose pkgid electron@1.6.10
19787 verbose cwd C:\mydata\electron\electron-vue-boilerplate
19788 verbose Windows_NT 6.1.7601
19789 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install"
19790 verbose node v8.1.2
19791 verbose npm  v5.0.3
19792 error code ELIFECYCLE
19793 error errno 1
19794 error electron@1.6.10 postinstall: `node install.js`
19794 error Exit status 1
19795 error Failed at the electron@1.6.10 postinstall script.
19795 error This is probably not a problem with npm. There is likely additional logging output above.
19796 verbose exit [ 1, true ]

```

@BobOntario  did you solve your issue btw?

**Comment by sofianguy** [comment]
Thanks for reaching out!

Because we treat our issues list as the team's backlog, we close issues that are questions since they don't represent a task needing to be completed. For most questions about Electron there are a lot of options. 
Check out the [Electron community](https://github.com/electron/electron#community). There are also a bunch of helpful people in this [community forum](https://discuss.atom.io/c/electron) that should be willing to point you in the right direction.
