### ISSUE TITLE
Error on starting electron application

### ISSUE THREAD

**Issue by talhaanees** [electron/electron#9715]
I have been working on electron for a whole month to develop an application. But today suddenly at around 11:30 am all my electron applications stopped working. I have no idea what happened but they all give the same error. I tried this:

# Clone the Quick Start repository
```
$ git clone https://github.com/electron/electron-quick-start
```
# Go into the repository
```
$ cd electron-quick-start
```
# Install the dependencies and run
```
$ npm install && npm start
```

 to see if the basic stuff works but no luck. This is the error I get:
```
internal/child_process.js:319
    throw errnoException(err, 'spawn');
    ^

Error: spawn EPERM
    at exports._errnoException (util.js:1018:11)
    at ChildProcess.spawn (internal/child_process.js:319:11)
    at Object.exports.spawn (child_process.js:378:9)
    at Object.<anonymous> (G:\**********\electron-quick-start\node_modules\electron\cli.js:
7:18)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "D:\\Applications\\Node.js\\node.exe" "D:\\Applications\\Node.js\\node_modules\\npm\\bin\\npm-cli.js" "sta
rt"
npm ERR! node v6.10.3
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! electron-quick-start@1.0.0 start: `electron .`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the electron-quick-start@1.0.0 start script 'electron .'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the electron-quick-start package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     electron .
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs electron-quick-start
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls electron-quick-start
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     G:\************\electron-quick-start\npm-debug.log
```

**Comment by pierreneter** [comment]
Try run as admin your `cmd` and run `$ npm install && npm start` again. If it still error. Let me know.

**Comment by enlight** [comment]
Closing this issue since the OP hasn't responded in a while.
