### ISSUE TITLE
Installation fails because of wrong checksum of electron-v1.6.11-linux-x64.zip

### ISSUE THREAD

**Issue by TheJJ** [electron/electron#9836]
* Electron version: v1.6.11
* Operating system: Gentoo Linux

### Expected behavior

I'm trying to install electron in [`riot-web`](https://github.com/vector-im/riot-web) with `npm install electron`. Apart from funny dependency errors (`fs.realpath`, `core-util-is`, `process-nextick-args`, `util-deprecate`, fixed by manual `npm install $names`),
the installation fails because of a wrong checksum.

I'd expect that electron would install...

### Actual behavior

`npm install electron` yields `Error: Generated checksum for "electron-v1.6.11-linux-x64.zip" did not match expected checksum.`:

```
$ npm install --verbose electron
....
npm info lifecycle electron@1.6.11~postinstall: electron@1.6.11

> electron@1.6.11 postinstall /home/jj/devel/riot-web/node_modules/electron
> node install.js

Downloading electron-v1.6.11-linux-x64.zip
[============================================>] 100.0% of 48.75 MB (1.77 MB/s)
/home/jj/devel/riot-web/node_modules/electron/install.js:47
  throw err
  ^

Error: Generated checksum for "electron-v1.6.11-linux-x64.zip" did not match expected checksum.
    at ChecksumMismatchError.ErrorWithFilename (/home/jj/devel/riot-web/node_modules/sumchecker/build.js:41:124)
    at new ChecksumMismatchError (/home/jj/devel/riot-web/node_modules/sumchecker/build.js:56:133)
    at Hash.<anonymous> (/home/jj/devel/riot-web/node_modules/sumchecker/build.js:203:22)
    at emitNone (events.js:105:13)
    at Hash.emit (events.js:207:7)
    at emitReadable_ (_stream_readable.js:502:10)
    at emitReadable (_stream_readable.js:496:7)
    at addChunk (_stream_readable.js:263:7)
    at readableAddChunk (_stream_readable.js:239:11)
    at Hash.Readable.push (_stream_readable.js:197:10)
npm verb lifecycle electron@1.6.11~postinstall: unsafe-perm in lifecycle true
npm verb lifecycle electron@1.6.11~postinstall: PATH: /usr/lib64/node_modules/npm/bin/node-gyp-bin:/home/jj/devel/riot-web/node_modules/electron/node_modules/.bin:/home/jj/devel/riot-web/node_modules/.bin:/usr/x86_64-pc-linux-gnu/gcc-bin/6.3.0:/usr/lib/llvm/4/bin:/usr/local/bin:/usr/bin:/bin:/opt/bin:/usr/lib64/opencascade-6.9.1/ros/lin/bin:/usr/games/bin:/home/jj/bin
npm verb lifecycle electron@1.6.11~postinstall: CWD: /home/jj/devel/riot-web/node_modules/electron
npm info lifecycle electron@1.6.11~postinstall: Failed to exec postinstall script
npm verb unlock done using /home/jj/.npm/_locks/staging-3443e8273d89e58b.lock for /home/jj/devel/riot-web/node_modules/.staging
npm verb stack Error: electron@1.6.11 postinstall: `node install.js`
npm verb stack Exit status 1
npm verb stack     at EventEmitter.<anonymous> (/usr/lib64/node_modules/npm/lib/utils/lifecycle.js:283:16)
npm verb stack     at emitTwo (events.js:125:13)
npm verb stack     at EventEmitter.emit (events.js:213:7)
npm verb stack     at ChildProcess.<anonymous> (/usr/lib64/node_modules/npm/lib/utils/spawn.js:40:14)
npm verb stack     at emitTwo (events.js:125:13)
npm verb stack     at ChildProcess.emit (events.js:213:7)
npm verb stack     at maybeClose (internal/child_process.js:897:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:208:5)
npm verb pkgid electron@1.6.11
npm verb cwd /home/jj/devel/riot-web
npm verb Linux 4.11.2-JJ
npm verb argv "/usr/bin/node" "/usr/bin/npm" "install" "--verbose" "electron"
npm verb node v8.1.2
npm verb npm  v5.0.3
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron@1.6.11 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron@1.6.11 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm verb exit [ 1, true ]
```

### How to reproduce

  $ git clone https://github.com/vector-im/riot-web.git
  $ npm install
  $ npm install electron

### Moar info

I deleted `.electron` `.npm` `node_modules` and have no idea how I should further debug this. A first step would be to persuade `npm` to keep files after the failed installation, because now they're deleted instantly after the failure.

**Comment by andres-lowrie** [comment]
I posted a similar issue over here: https://github.com/electron-userland/electron-prebuilt/issues/264

Don't know if I should close that one and just track this one

**Comment by MarshallOfSound** [comment]
@andres-lowrie It should be tracked on the `prebuilt` repo
