### ISSUE TITLE
Cannot find module exception

### ISSUE THREAD

**Issue by oniseijin** [electron/electron#9873]
* Electron version: 1.4.13
* Operating system: OSX 10.2 + Windows 7

### Expected behavior

Electron should load all modules. 

### Actual behavior

Uncaught Exception (extract below)

### How to reproduce

Simply launch electron.

Application works fine when running with `npm start`. The package was made with electron-packager, but it seems core Electron issue to me.  Generally works without lodash dependency, but given the application works fine with npm start, something due to the combination of lodash and the native package is an issue. 

<pre>
Uncaught Exception:
Error: Cannot find module 'lodash/identity'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (/Users/ryan/workspace/koan/koan_edm_electron/dist/EDM-darwin-x64/EDM.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/ryan/workspace/koan/koan_edm_electron/dist/EDM-darwin-x64/EDM.app/Contents/Resources/app/node_modules/async/detect.js:7:17)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/ryan/workspace/koan/koan_edm_electron/dist/EDM-darwin-x64/EDM.app/Contents/Resources/app/node_modules/async/index.js:52:15)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
</pre>

Current dependencies: 
<pre>
 "asar": "0.13.0",
    "async": "^2.4.1",
    "bluebird": "^3.5.0",
    "debug": "^2.6.8",
    "electron-default-menu": "1.0.1",
    "hasbin": "^1.2.3",
    "lodash": "4.17.4",
    "net": "^1.0.2",
    "node-notifier": "5.1.2",
    "os-homedir": "1.0.2",
    "rimraf": "2.6.1"
</pre>

**Comment by MarshallOfSound** [comment]
@oniseijin Is lodash in your `devDeps` or `deps`?

**Comment by MarshallOfSound** [comment]
GitHub issues are for feature requests and bug reports, questions about using Electron should be directed to the [community](https://github.com/electron/electron#community) or to the [Slack Channel](http://atom-slack.herokuapp.com/).

**Comment by oniseijin** [comment]
deps, but it also is a dependency of asar so it is picked up indirectly from there anyways. I'm now downgrading deps to determine if there is some weird combination of the above

**Comment by MarshallOfSound** [comment]
It it works in dev and doesn't work when packaged one of two things are happening

* It is being pruned out by `npm prune --production`
* It is being ignored by the `ignore` config for `electron-packager`

Sometimes a combination of the two, I would recommend as a debugging step removing your `ignore` config and setting `prune` to false and seeing if everything works.

**Comment by oniseijin** [comment]
Thanks, my bad, it was an ignore statement propagated across all that was causing it. Much appreciated. Last minute changed done 6 months ago that wasn't caught.
