### ISSUE TITLE
Adonisjs with Electron

### ISSUE THREAD

**Issue by chiqui3d** [electron/electron#9889]
I always get the same error:

`info adonis:framework +0ms serving app on null:null
Error: Invalid listen argument: [object Object]
    at Server.listen (net.js:1384:13)
    at Server.listen (/var/www/adoniselectron/adonis/node_modules/adonis-framework/src/Server/index.js:261:31)
    at fold.Registrar.register.then (/var/www/adoniselectron/adonis/bootstrap/http.js:103:14)
    at process._tickCallback (internal/process/next_tick.js:103:7)
    at Module.runMain (module.js:607:11)
    at run (bootstrap_node.js:424:7)
    at startup (bootstrap_node.js:147:9)
    at bootstrap_node.js:544:3
`

To get adonis server use:

`server              = require('./adonis/server')`

Then I open the url in:

`mainWindow.loadURL('http://localhost:3333');`

Full main.js code:

```const electron      = require('electron')
// Module to control application life.
const app          = electron.app
// Module to create native browser window.
const BrowserWindow = electron.BrowserWindow

const path          = require('path')
const url           = require('url')
const electronify   = require('electronify-server');
server              = require('./adonis/server')


// Keep a global reference of the window object, if you don't, the window will
// be closed automatically when the JavaScript object is garbage collected.
let mainWindow

function createWindow () {
  
  // Create the browser window.
    mainWindow = new BrowserWindow({width: 800, height: 600})

    mainWindow.loadURL('http://localhost:3333');
    mainWindow.focus();

  // Open the DevTools.
  // mainWindow.webContents.openDevTools()

  // Emitted when the window is closed.
  mainWindow.on('closed', function () {
    // Dereference the window object, usually you would store windows
    // in an array if your app supports multi windows, this is the time
    // when you should delete the corresponding element.
    mainWindow = null
  })
}

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow)

// Quit when all windows are closed.
app.on('window-all-closed', function () {
  // On OS X it is common for applications and their menu bar
  // to stay active until the user quits explicitly with Cmd + Q
  if (process.platform !== 'darwin') {
    app.quit()
  }
})

app.on('activate', function () {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (mainWindow === null) {
    createWindow()
  }
})

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and require them here.
```

So would it be possible to use adonis with electron?

**Comment by chiqui3d** [comment]
The problem that when calling the server file with
`var server = require ('./adonis/ server.js'),`
,not find .env file, so copy also to the root folder of electron. 

All right
