### ISSUE TITLE
Failed to run script\bootstrap.py with VS2017

### ISSUE THREAD

**Issue by KarenHuang2016** [electron/electron#9994]
**Environment:** Windows Sever 2016 + VS 2017.2

### How to reproduce
1. git clone https://github.com/electron/electron.git D:\Electron\src
2. Open a clean command prompt and browse to D:\Electron\src
3. python script\bootstrap.py -v --target_arch=ia32

### Expected behavior
bootstrap.py run successfully

### Actual behavior
The full log info please see attachment. 
[electron_x86_bootstrap.txt](https://github.com/electron/electron/files/1144224/electron_x86_bootstrap.txt)

The system cannot find the path specified.
Traceback (most recent call last):
  File "vendor\gyp\gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "vendor\gyp\pylib\gyp\__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "vendor\gyp\pylib\gyp\__init__.py", line 538, in main
    return gyp_main(args)
  File "vendor\gyp\pylib\gyp\__init__.py", line 514, in gyp_main
    options.duplicate_basename_check)
  File "vendor\gyp\pylib\gyp\__init__.py", line 98, in Load
    generator.CalculateVariables(default_variables, params)
  File "vendor\gyp\pylib\gyp\generator\ninja.py", line 1685, in CalculateVariables
    gyp.msvs_emulation.CalculateCommonVariables(default_variables, params)
  File "vendor\gyp\pylib\gyp\msvs_emulation.py", line 1083, in CalculateCommonVariables
    msvs_version = gyp.msvs_emulation.GetVSVersion(generator_flags)
  File "vendor\gyp\pylib\gyp\msvs_emulation.py", line 934, in GetVSVersion
    allow_fallback=False)
  File "vendor\gyp\pylib\gyp\MSVSVersion.py", line 447, in SelectVisualStudioVersion
    raise ValueError('Could not locate Visual Studio installation.')
ValueError: Could not locate Visual Studio installation.
Running in verbose mode
git submodule sync --recursive
git submodule update --init --recursive
C:\tools\python2\python.exe setup.py build
C:\tools\python2\python.exe setup.py build
npm.cmd install --verbose
git submodule status vendor/libchromiumcontent
 8cfd08f84e415f3c8e5fde061f8e17400ef8aa7f vendor/libchromiumcontent (v51.0.2704.61-375-g8cfd08f)
C:\tools\python2\python.exe D:\Electron\src\script\update.py
None
Traceback (most recent call last):
  File "script\bootstrap.py", line 249, in <module>
    sys.exit(main())
  File "script\bootstrap.py", line 64, in main
    run_update(defines, args.msvs)
  File "script\bootstrap.py", line 226, in run_update
    execute_stdout(args)
  File "D:\Electron\src\script\lib\util.py", line 184, in execute_stdout
    raise e
subprocess.CalledProcessError: Command '['C:\\tools\\python2\\python.exe', 'D:\\Electron\\src\\script\\update.py']' returned non-zero exit status 1

**Comment by TheShikharGupta** [comment]
I am facing the same problem.
Environment: Windows 10 Home + MSVS 2017
Same expected behaviour
**Actual behaviour**
C:\python27\python.exe C:\Users\Shikhar\electron\script\update.py
The system cannot find the path specified.
Traceback (most recent call last):
  File "vendor\gyp\gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "vendor\gyp\pylib\gyp\__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "vendor\gyp\pylib\gyp\__init__.py", line 538, in main
    return gyp_main(args)
  File "vendor\gyp\pylib\gyp\__init__.py", line 514, in gyp_main
    options.duplicate_basename_check)
  File "vendor\gyp\pylib\gyp\__init__.py", line 98, in Load
    generator.CalculateVariables(default_variables, params)
  File "vendor\gyp\pylib\gyp\generator\ninja.py", line 1685, in CalculateVariables
    gyp.msvs_emulation.CalculateCommonVariables(default_variables, params)
  File "vendor\gyp\pylib\gyp\msvs_emulation.py", line 1083, in CalculateCommonVariables
    msvs_version = gyp.msvs_emulation.GetVSVersion(generator_flags)
  File "vendor\gyp\pylib\gyp\msvs_emulation.py", line 934, in GetVSVersion
    allow_fallback=False)
  File "vendor\gyp\pylib\gyp\MSVSVersion.py", line 447, in SelectVisualStudioVersion
    raise ValueError('Could not locate Visual Studio installation.')
ValueError: Could not locate Visual Studio installation.
None
Traceback (most recent call last):
  File "script\bootstrap.py", line 261, in <module>
    sys.exit(main())
  File "script\bootstrap.py", line 65, in main
    run_update(defines, args.msvs)
  File "script\bootstrap.py", line 238, in run_update
    execute_stdout(args)
  File "C:\Users\Shikhar\electron\script\lib\util.py", line 184, in execute_stdout
    raise e
subprocess.CalledProcessError: Command '['C:\\python27\\python.exe', 'C:\\Users\\Shikhar\\electron\\script\\update.py']' returned non-zero exit status 1

**Comment by buszito** [comment]
me too :/ the same status

**Comment by thebigtoona** [comment]
Hey all, 

I've been learning to build applications with electron and node, and running through tutorials i ran into this issue.  Here is the research I have done so far.  I will continue to crawl the code, test hypotheses, and attempt to locate the issue, and will also continue to update any findings.  I'm not a professional dev by any means so I don't really know if I am looking in the correct place.  I know python but it will take me quite awhile to crawl all of this and make sense of it. I'm also not very familiar with Windows. Win 10 is my first Windows OS since XP and I was previously using Linux as my primary OS.  Any help with this would be greatly appreciated.   

### My findings so far 

The research I  have done suggests that the issue lies in the ability to locate visual studio properly, and that Visual Studio 2013 works but later versions do not.  I have also found research indicating that gyp is suffering from being further updated, but I am not sure about this.  

Crawling the code in util.py and MSVSVersion.py and the error 'None' in the snippet above suggest to me that this may be a setting/reg path issue? It appears that MSVSVersion.py uses the windows reg keys to locate the installation. 

The specific version of Visual Studio is also tying into this somehow because there are reports of 2013 working while later version do not. I do not have VS 2013 at this time, so I cannot attest to it working and I can't troubleshoot anything specific to that version of the software at this time. If anyone has it and CAN test it, please share your result with me.  

My thought train at this time is that maybe the way that the path for 2013 and 2017 look different in a manner that might be hard-coded in and maybe that's why 2017 is getting rejected but this is only a theory. 

### Steps to reproduce: 
in Powershell, in the root dir of the project: 
 * git clone https://github.com/electron/electron.git
 * cd electron  
 * python2 script\bootstrap.py -v

### Other commands I have run to troubelshoot this issue: 
* npm config set msvs_version 2017 --global
* setx GYP_MSVS_VERSION 2017

*note that i am using python2 as the python command in powershell as i have both 2 and 3 installed on this machine.*

### Build Environment 
Windows 10 Pro 
Python 2.7.14
Visual studio 2017 community
Node Version v9.1.0
Electron Version  v1.7.9

### This is the code snippet: 
```
F:\Program Files (x86)\Python27\python2.exe F:\Projects\diskr\diskr\electron\script\update.py
The system cannot find the path specified.
Traceback (most recent call last):
  File "vendor\gyp\gyp_main.py", line 16, in <module>
    sys.exit(gyp.script_main())
  File "vendor\gyp\pylib\gyp\__init__.py", line 545, in script_main
    return main(sys.argv[1:])
  File "vendor\gyp\pylib\gyp\__init__.py", line 538, in main
    return gyp_main(args)
  File "vendor\gyp\pylib\gyp\__init__.py", line 514, in gyp_main
    options.duplicate_basename_check)
  File "vendor\gyp\pylib\gyp\__init__.py", line 98, in Load
    generator.CalculateVariables(default_variables, params)
  File "vendor\gyp\pylib\gyp\generator\ninja.py", line 1685, in CalculateVariables
    gyp.msvs_emulation.CalculateCommonVariables(default_variables, params)
  File "vendor\gyp\pylib\gyp\msvs_emulation.py", line 1083, in CalculateCommonVariables
    msvs_version = gyp.msvs_emulation.GetVSVersion(generator_flags)
  File "vendor\gyp\pylib\gyp\msvs_emulation.py", line 934, in GetVSVersion
    allow_fallback=False)
  File "vendor\gyp\pylib\gyp\MSVSVersion.py", line 447, in SelectVisualStudioVersion
    raise ValueError('Could not locate Visual Studio installation.')
ValueError: Could not locate Visual Studio installation.
None
Traceback (most recent call last):
  File "./script/bootstrap.py", line 261, in <module>
    sys.exit(main())
  File "./script/bootstrap.py", line 65, in main
    run_update(defines, args.msvs)
  File "./script/bootstrap.py", line 238, in run_update
    execute_stdout(args)
  File "F:\Projects\diskr\diskr\electron\script\lib\util.py", line 184, in execute_stdout
    raise e
subprocess.CalledProcessError: Command '['F:\\Program Files (x86)\\Python27\\python2.exe', 'F:\\Projects\\diskr\\diskr\\electron\\script\\update.py']' returned non-zero exit status 1
```

**Comment by jkleinsc** [comment]
If you are building Electron for versions 2.0.0 and earlier, you need to use VS2015: https://github.com/electron/electron/blob/1-7-x/docs/development/build-instructions-windows.md

**Comment by warpdesign** [comment]
@jkleinsc is VC2017 ok as well or must it be VC2015? The download link in the build instructions points to the most recent (2017) VC version.

I downloaded and installed this one and get the same error.

Also, what VC elements should be installed to compile Electron? There are a lot of C/C++ options/SDK to choose from when running the installer and the readme doesn't tell what's needed.

**Comment by jkleinsc** [comment]
@warpdesign it depends what version of Electron you are building.  If you are building 3-0-x or master, you need VS2017.  Versions 2.0.x and earlier need VS2015.
As far as specifics, this doc has more information:
https://chromium.googlesource.com/chromium/src/+/master/docs/windows_build_instructions.md#Visual-Studio (Master and 3-0-x)
or for 2-0-x and earlier:
https://chromium.googlesource.com/chromium/src/+/61.0.3163.100/docs/windows_build_instructions.md

**Comment by warpdesign** [comment]
Thank you @jkleinsc this is exactly what I was looking for! Since I'm building 2-0-x I have to install VS2015.
